### ISSUE TITLE
Form block: Ability to add cc and bcc addresses for submissions received

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/jetpack#13738] opened 2019-10-12 16:31 UTC
#### Is your feature request related to a problem? Please describe.

Users would like to add "cc" and "bcc" to form submissions, which aren't currently possible with the form Block but can be done with third-party solutions like Contact Form 7 plugin.

#### Describe the solution you'd like
It would be nice and make our form more competitive if we could do this.

#### Additional context
As requested here: #2407387-zen

**Comment by davipontesblog** [comment] 2019-10-12 16:32
Related: https://github.com/Automattic/jetpack/issues/631

**Comment by jeherve** [comment] 2019-10-14 07:33
Closing as duplicate of #631, since the requests are the same.

**Closed by jeherve** 2019-10-14 07:33 UTC
Labels: Contact Form, WordPress.com Block Editor
