### ISSUE TITLE
Allow adding of URL parameters to publicize urls

### ISSUE THREAD

**Issue by yuk75** [Automattic/jetpack#2391] opened 2015-07-11 04:12 UTC
Googles URL builder is an important part of Google Analytics and tracking traffic and stats. Before jetpack I would add these myself using the builder and then I would use bit.ly to make them short. I am almost 100% sure that it wont work if you add it to a short url instead of the original URL.

I think allowing this, even allowing users to customise it for each network, would be a really fantastic idea. Then we can say the Campaign Source is Facebook, or Twitter, and the medium is Tweet, or Status, or what ever and not have to just lump it under "SocialMedia" and "SocialPost" :).

Example parameters from Googles URL builder:
www.example.com/?utm_source=CampaignSource&utm_medium=CampaignMedium&utm_term=CampaignKeywords&utm_content=CampaignContent&utm_campaign=CampaignName

Googles URL builder: https://support.google.com/analytics/answer/1033867?hl=en

**Comment by jeherve** [comment] 2015-07-11 09:31
That's a good suggestion, and something we may allow again once we implement #261. It would allow you to use custom shortlinks again, or use custom URLs in the Publicize message.

I'm going to close this issue as duplicate of #26, and mention your idea there.

**Closed by jeherve** 2015-07-11 09:31 UTC
