### ISSUE TITLE
Settings UI: include unique IDs / anchors so one can create links to a specific section

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6420] opened 2017-02-15 17:32 UTC
When helping Jetpack users, we often direct them to specific areas of their Jetpack dashboard. Up until now, we would explain things like so: "Please go to Jetpack > Settings > Appearance and open the "Mobile Theme" card", and we would send them a link to the Settings page.

I think it would be nice to add unique IDs to each section or section header on the new Settinsg page, so we can send links to a specific section.

**Comment by MichaelArestad** [comment] 2017-02-15 17:33
I think we can probably get clever with the sectionheader component to at least point the user to the right group. Another option might be to see if we can animate it a bit on focus to really highlight where the HE is pointing the user.

**Comment by MichaelArestad** [comment] 2017-02-15 17:34
Or maybe apply it to the form elements themselves.

**Comment by dereksmart** [comment] 2017-10-31 21:02
Duplicate of #5693

**Closed by dereksmart** 2017-10-31 21:02 UTC
Labels: Admin Page, [Type] Enhancement
