### ISSUE TITLE
Feature Request: Carousel show all gallery images in single slider

### ISSUE THREAD

**Issue by peiche** [Automattic/jetpack#25430] opened 2022-08-10 15:28 UTC
### Impacted plugin

Jetpack

### What

I would like the carousel to show all gallery images within a single post.

### How

If there are multiple gallery blocks in a post or page, clicking on an image will only show the carousel slider for the images within that gallery block. I would like the carousel slider to be able to page through all the gallery images in the post, across all gallery blocks within that post.

**Comment by jeherve** [comment] 2022-08-10 15:39
Thanks for the feedback!

However, I'm afraid I do not have any good news for you. Linking multiple carousels together is not something that's possible right now. Carousels are closely tied to galleries, and there is consequently no relationship between 2 carousels on a page, just like there is no relationship between 2 galleries.

Keeping galleries clearly separate from each other is done by design, but also to avoid any issues on pages that include multiple posts (such as archive pages, or home page) and where multiple galleries from multiple posts would not be related.

Since implementing such a change would require a complete redesign of the Carousel feature, that's not something we'll be able to implement for you.

I'll consequently close this issue as "Won't Fix".

**Closed as completed by jeherve** 2022-08-10 15:39 UTC
Labels: [Feature] Carousel, New Feature, [Closed] Won't Fix, [Plugin] Jetpack
