### ISSUE TITLE
Portfolios - Add Filter or UI option to change the "project-type" slug 

### ISSUE THREAD

**Issue by seejacobscott** [Automattic/jetpack#7261] opened 2017-05-29 22:30 UTC
It would be great to have the option to change the URL slug used for the Portfolio project types from 'project-type' to a custom word or phrase. 

Requested in 3235470-t

**Comment by jeherve** [comment] 2017-05-30 10:23
Closing as duplicate of #949

**Closed by jeherve** 2017-05-30 10:23 UTC
Labels: Custom Content Types
