### ISSUE TITLE
Premium Content Block - Pay Now on mobile showing blank screen

### ISSUE THREAD

**Issue by janmckell** [Automattic/jetpack#33140] opened 2023-09-18 11:20 UTC
### Impacted plugin

Jetpack

### Quick summary

A user reached out to describe that several of their potential customers could not pay for the premium content subscription.

6845655-zd-a8c

They don't have screenshots, but they described the issue in a great amount of detail.

I will share my summary of the issue, and then their detailed response after looking for more evidence, about the case.

Initial summary of issue:

> This occurs after clicking on a button in their Premium Content Block. They had a friend try to test the payment modal and could not proceed. The page goes white and freezes after clicking on ‘Pay Now’.

I asked for more detailed information and they updated with the following:

> My friend who was not able to complete the payment on mobile (iPhone) has now been able to complete it successfully on his laptop (Macbook, Chrome browser).
> 
> I have now logged in to my Stripe account, and found that the unsuccessful payments actually show up in there, under 'Payments'. It shows my friend's three attempted purchases (mobile) on Friday as "Incomplete", while his purchase today (desktop) is marked "Succeeded". The unsuccessful payments have not shown up anywhere in the Wordpress backend, but they are shown here in Stripe. There is another incomplete payment from someone else (2 months ago) which I did not know about, and one more on (8 months ago). In contrast, there are plenty of "Succeeded" payments before and since. Next to each "Incomplete" payment, it says, "The customer must complete an additional authentication step." Under the 'Fraud & risk' section, there is a report which states that one recent payment "Failed 3DS authentication", while other payments "Passed 3DS".
> 
> So it seems to me that the problem is something to do with payment authentication on mobile, when somebody clicks 'Pay Now' on our website.

I am not sure how to test this, and tried to test it using test data (Stripe test card, with sandbox, etcetera) but I am not savvy with this and do not know how to successfully test further at this time, so escalating here.

### Steps to reproduce

From mobile, click on 'purchase' button in their Premium Content Block
Click 'Pay Now'

### A clear and concise description of what you expected to happen.

Expected the payment modal to open

### What actually happened

Screen was white with no modal

### Impact

One

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple

**Comment by jeherve** [comment] 2023-09-18 12:50
cc @Automattic/gold Is that something you could look into? 

Thank you!

**Comment by cuemarie** [comment] 2023-09-19 20:21
📌 REPRODUCTION RESULTS
- Tested on Simple (Premium Plan) – Could not replicate
- Tested on Atomic – Replicated _somewhat_

📌 FINDINGS/SCREENSHOTS/VIDEO
Tested using iPhone Safari, subscribing to Paid Content on an Atomic site.  My payment did succeed, however my mobile browser only lead to a white screen after subscribing. It's possible this was a slow-to-load screen, but it stayed for probably 10 seconds, at which point I refreshed, then had to select `Log In`, but after those 2 steps my subscribing account could see the expected content. 

<img width="350" alt="screenshot" src="https://github.com/Automattic/jetpack/assets/27249804/5ab20759-ec36-43ff-be15-4973b6017b85">

When testing on a simple site, I was able to subscribe without issue.  

In both cases, I was not required to perform any authentication step after "pay now".  I performed these tests in a Private Safari tab which was already logged in to my subscriber WordPress.com account, and I submitted the matching email for that account below the payment form.

>Next to each "Incomplete" payment, it says, "The customer must complete an additional authentication step." Under the 'Fraud & risk' section, there is a report which states that one recent payment "Failed 3DS authentication", while other payments "Passed 3DS".
>
>So it seems to me that the problem is something to do with payment authentication on mobile, when somebody clicks 'Pay Now' on our website.

This specific detail seems unique and wasn't something I was able to reproduce.  If there's authentication happening behind the scenes while the subscriber is facing a white screen, and the user cancels/hits Back, or has slow network connection, I wonder if that could disrupt some authentication process?

📌 ACTIONS
- Since I can't repro, lowering to Normal priority

**Comment by n3f** [comment] 2023-09-19 21:16
While testing this (it's really convoluted for iphone) I did find a bug with the way our caching works that is being addressed in D122408-code. The problem there was 3DS purchases created a cache where the user didn't have the subscription so after a successful purchase they couldn't see the content until the cache expired.

I was unable to reproduce this exact error however:

![Kapture 2023-09-19 at 13 54 18](https://github.com/Automattic/jetpack/assets/6354169/987500da-ae89-4af1-bc3c-6fbe28567e73)

Of course if you fail the purchase it does put the purchase in the incomplete state (which is expected).

It's possible that the version of 3DS that their bank is using is causing the issue, but that might be impossible to debug.

**Comment by janmckell** [comment] 2023-09-20 16:28
What should I advise the customer to do? @n3f

**Comment by n3f** [comment] 2023-09-20 19:27
> What should I advise the customer to do? @n3f

Tell them we were unable to replicate, but we found a related issue that might have solved the issue.  Also advise that it appears that the window can blank for a bit as the systems are communicating and there might be a bit of a wait until it responds.  We will work on developing a better UI/experience for this period (it only shows on mobile).

**Comment by n3f** [comment] 2024-02-14 00:14
I tried to replicate this today and it appears to have been solved. I'm going to close now, but feel free to re-open if there are further reports.

**Closed as completed by n3f** 2024-02-14 00:14 UTC
Labels: Bug, [Pri] Normal, Customer Report [LEGACY], [Plugin] Jetpack, Triaged, [Platform] Simple, [Feature] Paid Content, [Feature Group] Customer Seller Experience
