### ISSUE TITLE
PHP Fatal - Class 'Jetpack_SEO_Utils' not found

### ISSUE THREAD

**Issue by samiff** [Automattic/jetpack#19511] opened 2021-04-12 22:15 UTC
#### Steps to reproduce the issue

1. Spin up a new site with Jetpack 9.6 installed (I used JN to test).
2. Make sure error logging is turned on.
3. Activate Jetpack and connect to WordPress.com
    * I've only noticed the error logged this far after connecting like this. Before/after connection I'm not noticing the error.
4. Observe in error logs that a Fatal was thrown:

```
Uncaught Error: Class 'Jetpack_SEO_Utils' not found in /public/wp-content/plugins/jetpack/json-endpoints/class.wpcom-json-api-get-site-endpoint.php:4
```

Backtrace:

```
wp_xmlrpc_server->serve_request,
IXR_Server->IXR_Server,
IXR_Server->__construct,
IXR_Server->serve,
IXR_Server->call,
IXR_Server->multiCall, IXR_Server->call,
Jetpack_XMLRPC_Methods::json_api,
require_once('/plugins/jetpack/class.json-api-endpoints.php'),
require_once('/plugins/jetpack/json-endpoints.php'),
require_once('/plugins/jetpack/json-endpoints/class.wpcom-json-api-get-site-endpoint.php')
```

_Maybe_ something was recently changed connection/load-jetpack wise?

#### Misc.

- Internal: p9dueE-2Jo-p2 , p1617891379056600-slack-CBG1CP4EN

**Comment by dd32** [comment] 2021-04-13 06:41
I've seen this on WordPress.org as well, starting after the Jetpack 9.6 update (Previously running 9.3).

The only additional context I can offer is this:
```
POST https://cn.wordpress.org/support/xmlrpc.php?for=jetpack&token=...&timestamp=...&nonce=...&body-hash=...&signature=...

<?xml version="1.0"?>
<methodCall>
<methodName>system.multicall</methodName>
<params>
<param><value><array><data>
 <value><struct>
 <member><name>methodName</name><value><string>jetpack.jsonAPI</string></value></member>
 <member><name>params</name><value><array><data>
 <value><array><data>
 <value><string>GET</string></value>
 <value><string>https://public-api.wordpress.com/rest/v1.1/sites/186277750?http_envelope=1</string></value>
 <value><string></string></value>
 <value><int>186277750</int></value>
 <value><array><data>
</data></array></value>
 <value><string></string></value>
</data></array></value>
 <value><boolean>0</boolean></value>
</data></array></value></member>
</struct></value>
</data></array></value></param>
</params></methodCall>
```

**Comment by kraftbj** [comment] 2021-04-14 22:16
Some notes ... the SEO tools is loaded via `module-extras` which fires in the `load_modules` function within Jetpack. That function will return early in this circumstances:

```
if (
			! self::is_connection_ready()
			&& ! $is_offline_mode
			&& ! self::is_onboarding()
			&& (
				! is_multisite()
				|| ! get_site_option( 'jetpack_protect_active' )
			)
		) {
			return;
		}
```

I _think_ this may be a side effect of https://github.com/Automattic/jetpack/pull/19276/files which changed `is_active` to `is_connection_ready` (cc: @fgiannar ).

Or maybe https://github.com/Automattic/jetpack/pull/19259 which updated what xmlrpc methods are returned on is_active vs is_connected ?

Not really sure yet.

**Comment by jenhooks** [comment] 2021-04-16 19:16
[This is being reported in a forums thread here. ](https://wordpress.org/support/topic/jetpack-dashboard-unable-to-properly-communicate-with-the-server/)

**Comment by samiff** [comment] 2021-04-16 19:37
> [This is being reported in a forums thread here. ](https://wordpress.org/support/topic/jetpack-dashboard-unable-to-properly-communicate-with-the-server/)

Thanks Jen, the PHP fatal error being reported in this issue should not affect the site in a negative way. @fgiannar is currently working to see if the error can be fixed/suppressed in the short term, and in the worse case the issue should be resolved when 9.7 releases.

**Comment by fgiannar** [comment] 2021-04-19 09:34
Created a [corresponding GH issue in calypso](https://github.com/Automattic/wp-calypso/issues/52059) with a proposed fix.

**Comment by rinatkhaziev** [comment] 2021-04-21 03:12
Here's the stacktrace:

```
File web/app/plugins/jetpack/json-endpoints/class.wpcom-json-api-get-site-endpoint.php line 3
File web/app/plugins/jetpack/json-endpoints.php line 32 in require_once
File web/app/plugins/jetpack/class.json-api-endpoints.php line 2169 in require_once args
File web/app/plugins/jetpack/class-jetpack-xmlrpc-methods.php line 178 in require_once args
File web/wp/wp-includes/IXR/class-IXR-server.php line 121 in Jetpack_XMLRPC_Methods::json_api args
File web/wp/wp-includes/IXR/class-IXR-server.php line 211 in IXR_Server::call args
File web/wp/wp-includes/IXR/class-IXR-server.php line 109 in IXR_Server::multiCall args
File web/wp/wp-includes/IXR/class-IXR-server.php line 59 in IXR_Server::call args
File web/wp/wp-includes/IXR/class-IXR-server.php line 27 in IXR_Server::serve args
File web/wp/wp-includes/IXR/class-IXR-server.php line 35 in IXR_Server::__construct args
File web/wp/wp-includes/class-wp-xmlrpc-server.php line 191 in IXR_Server::IXR_Server args
File web/wp/xmlrpc.php line 87 in wp_xmlrpc_server::serve_request args
```

The most interesting part (IMO :)) is 

```
IXR_Server::IXR_Server arguments
0	
{
  "jetpack.jsonAPI": [
    "Jetpack_XMLRPC_Methods",
    "json_api"
  ],
  "jetpack.unlinkUser": [
    "<CircularReference type:(Jetpack_XMLRPC_Server) ref:(000000005656875c0000000054b9c365)>",
    "unlink_user"
  ],
  "jetpack.syncObject": [
    {
      "class": "Automattic\\Jetpack\\Sync\\Sender",
      "value": []
    },
    "sync_object"
  ],
  "jetpack.getUser": [
    "<CircularReference type:(Jetpack_XMLRPC_Server) ref:(000000005656875c0000000054b9c365)>",
    "get_user"
  ],
  "jetpack.remoteRegister": [
    "<CircularReference type:(Jetpack_XMLRPC_Server) ref:(000000005656875c0000000054b9c365)>",
    "remote_register"
  ],
  "jetpack.disconnectBlog": [
    "Jetpack_XMLRPC_Methods",
    "disconnect_blog"
  ],
  "jetpack.featuresAvailable": [
    "Jetpack_XMLRPC_Methods",
    "features_available"
  ],
  "jetpack.idcUrlValidation": [
    "<CircularReference type:(Jetpack_XMLRPC_Server) ref:(000000005656875c0000000054b9c365)>",
    "validate_urls_for_idc_mitigation"
  ],
  "jetpack.remoteProvision": [
    "<CircularReference type:(Jetpack_XMLRPC_Server) ref:(000000005656875c0000000054b9c365)>",
    "remote_provision"
  ],
  "jetpack.verifyAction": [
    {
      "class": "Jetpack_XMLRPC_Server",
      "value": {
        "user": false,
        "error": {
          "class": "WP_Error",
          "value": {
            "errors": {
              "invalid_request": [
                "Invalid Request"
              ]
            },
            "error_data": {
              "invalid_request": 403
            }
          }
        }
      }
    },
    "verify_action"
  ],
  "jetpack.testConnection": [
    "<CircularReference type:(Jetpack_XMLRPC_Server) ref:(000000005656875c0000000054b9c365)>",
    "test_connection"
  ],
  "jetpack.featuresEnabled": [
    "Jetpack_XMLRPC_Methods",
    "features_enabled"
  ],
  "jetpack.getHeartbeatData": [
    "Automattic\\Jetpack\\Heartbeat",
    "xmlrpc_data_response"
  ],
  "jetpack.remoteConnect": [
    "<CircularReference type:(Jetpack_XMLRPC_Server) ref:(000000005656875c0000000054b9c365)>",
    "remote_connect"
  ]
```

Seems that it happens during `https://public-api.wordpress.com/rest/v1/sites/%s/sync/status` request?

**Comment by mzakariya** [comment] 2021-04-22 17:21
3924133-zen

xmlrpc.php responds with error to Jetpack's requests:

> <h1>Error thrown</h1><p>Class 'Jetpack_SEO_Utils' not found</p>

This site has separately had connection issues. Asking them to try reinstalling/reconnecting Jetpack.

**Comment by jeherve** [comment] 2021-04-22 19:59
@fgiannar x-posting here:

> Given that the class is "only" used to bring in constants, maybe we could just copy them in `projects/plugins/jetpack/json-endpoints/class.wpcom-json-api-get-site-endpoint.php` for a quick fix?

What do you think about this as a dirty fix for this release?

**Comment by jeherve** [comment] 2021-05-04 10:16
Closing this for now, as per discussion in https://github.com/Automattic/wp-calypso/issues/52059#issuecomment-825492366

**Comment by daria2303** [comment] 2021-05-14 11:00
3984888-zd-woothemes
PHP Fatal error:  Uncaught Error: ‘Jetpack_SEO_Utils’ not found

**Comment by jeherve** [comment] 2021-05-14 11:04
@daria2303 Do you happen to know what version of Jetpack they run on their site? If they do not run Jetpack 9.7, could they try updating?

**Comment by rinatkhaziev** [comment] 2021-05-14 20:05
I can confirm that after switching my personal site from 9.6 to 9.7 the error is gone now and the connection stopped breaking on every deploy 😬

**Comment by daria2303** [comment] 2021-05-19 06:26
> @daria2303 Do you happen to know what version of Jetpack they run on their site? If they do not run Jetpack 9.7, could they try updating?

Yes, it's 9.7. (They are able to edit site in incognito mode only. )

**Comment by jeherve** [comment] 2021-05-19 08:36
Thank you. Reopening this issue.

For more details about that last report. It's an Atomic site, ID `191519316`:

```
[14-May-2021 08:28:36 UTC] PHP Fatal error:  Uncaught Error: Class 'Jetpack_SEO_Utils' not found in /wordpress/plugins/jetpack/9.7/json-endpoints/class.wpcom-json-api-get-site-endpoint.php:3
Stack trace:
#0 /wordpress/plugins/jetpack/9.7/json-endpoints.php(32): require_once()
#1 /wordpress/plugins/jetpack/9.7/class.json-api-endpoints.php(2169): require_once('/wordpress/plug...')
#2 /wordpress/plugins/jetpack/9.7/class-jetpack-xmlrpc-methods.php(178): require_once('/wordpress/plug...')
#3 /wordpress/core/5.7.2/wp-includes/IXR/class-IXR-server.php(121): Jetpack_XMLRPC_Methods::json_api(Array)
#4 /wordpress/core/5.7.2/wp-includes/IXR/class-IXR-server.php(211): IXR_Server->call('jetpack.jsonAPI', Array)
#5 /wordpress/core/5.7.2/wp-includes/IXR/class-IXR-server.php(109): IXR_Server->multiCall(Array)
#6 /wordpress/core/5.7.2/wp-includes/IXR/class-IXR-server.php(59): IXR_Server->call('system.multical...', Array)
#7 /wordpress/core/5.7.2/wp-includes/IXR/class-IXR-server.php(27): IXR_Server->serve('<?xml version="...')
#8 /wordpress/core/5.7.2/wp-includes/IXR/class-IXR-server.php(35): IXR_Server->__construct(Array, false, false)
#9 /wordpress/core/5.7.2/wp-includes/class-wp-xmlrpc-server.php(191): IXR_Server->IXR_Server(Array)
#10 /wordpress/core/5.7.2/xmlrpc.php(87): wp_xmlrpc_server->serve_request()
#11 {main}
  thrown in /wordpress/plugins/jetpack/9.7/json-endpoints/class.wpcom-json-api-get-site-endpoint.php on line 3
```

@fgiannar What do you think about going back on our potential workaround discussed here:
https://github.com/Automattic/jetpack/issues/19511#issuecomment-825145126

**Comment by jeherve** [comment] 2021-05-19 08:56
It seems that the problem was fixed after May 14 on Atomic, so we should be all set now. I'll close this issue again. If it starts happening again, do not hesitate to reopen.

**Comment by jeherve** [comment] 2021-07-08 07:42
Reopening as this seems to be back:
p1625691436323300-slack-CDLH4C1UZ

**Comment by sajmes** [comment] 2021-07-15 12:23
Seeing this here 4142677-zd-woothemes after reconnecting Jetpack

**Comment by devNigel** [comment] 2021-07-19 04:26
Another case: 4157666-zen

**Comment by kraftbj** [comment] 2021-07-19 16:55
I think I have a potential load time issue that is causing this to open, but not fully sure what's happening yet.

We don't load modules code, including the SEO files, until `plugins_loaded` very late, but we load the XMLRPC methods as part of the config package, at `plugins_loaded, 2`.

I'm thinking that something is firing on the `plugins_loaded` hook between priority 2 and priority 100 when `load_modules` fires. 

A couple of thoughts on ways to approach this:

1. We could really track down this specifically. 
2. Look into why we're loading parts of Jetpack in `load-jetpack.php` directly instead of part of some of the initialization routines.
3. For things we know we're going to load always (like these SEO functions), let's direct require them earlier?

**Comment by samiff** [comment] 2021-07-19 22:59
@devNigel Just for reference, while we are working to suppress this error message, from what we've seen it shouldn't be causing any actually conflicts with functionality on the site.

**Closed** 2021-07-20 12:08 UTC
Labels: Connect Flow, SEO Tools, [Status] In Progress, [Type] Bug, [Type] Happiness Request

**Comment by fgiannar** [comment] 2021-07-20 12:13
@kraftbj Many thanks for working on this ❤️
