### ISSUE TITLE
WP beta 4.3

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#2343] opened 2015-07-02 21:38 UTC
I am seeing a lot of PHP error notices while running Jetpack (master) on the latest WP trunk saying that.
```Notice: The called constructor method for WP_Widget is deprecated since version 4.3.0! Use
__construct()```

**Comment by kraftbj** [comment] 2015-07-02 21:53
Duplicate of #2323

**Closed by kraftbj** 2015-07-02 21:53 UTC
Labels: bug, Good First Bug
