### ISSUE TITLE
Jetpack subscription emails not working well with media and text block

### ISSUE THREAD

**Issue by geoffguillain** [Automattic/jetpack#35530] opened 2024-02-08 03:20 UTC
### Impacted plugin

Jetpack

### Quick summary

There is an email subscription feature available with Jetpack.

When a post is using the Media and Text block from Gutenberg when an email notification is sent the block will not break into 2 rows even if the checkbox "Stack on mobile" is checked.

The output will depend on email clients but in the best-case scenario the padding/margin is missed, and in the worst-case scenario the image is squeezed and distorted. (cf screenshot below)

Here is a post example: 
https://geoffsandbox.wordpress.com/2024/02/08/media-and-text-block-email-notification-vs-columns/ 

The feed: 
https://wordpress.com/read/blogs/171197280/posts/40

Screenshot of the email output on Mail macOS:
_While the media and text block fails, replicating the layout with a column block works as expected._
<img width="404" alt="image" src="https://github.com/Automattic/jetpack/assets/4668242/fea33af3-a67e-48e2-b503-67a1ddd24bb0">

### Steps to reproduce

1. Subscribe to a site new post email notifications
2. Create a new post with a block "media and text" and publish it
3. The email client will have some difficulties to render the "media and text" block properly

### A clear and concise description of what you expected to happen.

I would have expected that the 'media and text" block would break into 2 separate rows for email notifications even more if the stack on mobile checkbox is on.
The email output should be the same as the feed output (eg: https://wordpress.com/read/blogs/171197280/posts/40) or as the column block (cf screenshot)

### What actually happened

The email client tries to render the block and media in a single row, removes the margin, and creates distorted images (depending on the email client)

### Impact

All

### Available workarounds?

No and the platform is unusable

### Logs or notes

All email clients I have been able to test fail to render properly the media and text block

**Comment by rickmgithub** [comment] 2024-02-08 10:04
I have tried to replicate this but I'm having problems with my own set up.

My understanding is 

1) Ensure you have a site ready on an account
2) Subscribe to that site from another account and ensure you have email notifications, etc set to receive the publication notice.
3) On the site, publish a post with a text/media block
4) When the post arrives it will show a corrupted media/text block view as per the OPs screenshot.

Leaving open for next PA to check this can be replicated

**Comment by geoffguillain** [comment] 2024-02-08 10:14
Hey @rickmgithub 

Yes, I have:
 - Created an account on WP.com
 - Subscribe to my own blog
 - Posted an article with a media and text block
 - The email received is not displayed correctly
 
 The original issue was discovered on a [partner website](https://docfestjazz.org/2024/01/25/docfest-24-presents-mark-holden/), but I have been able to replicate with ease on a default account/theme on WP.com

**Comment by bizanimesh** [comment] 2024-02-08 10:53
👋 I was testing this one and can reproduce it. 

The stack option looks working fine [on the live site](https://jpcomplete.mystagingwebsite.com/2024/02/08/new-email/) ([screenshot](https://github.com/Automattic/jetpack/assets/52444539/860f2c69-277e-4682-a747-40083a6e41cf)), but on the newsletter email, it is not working as it is working on the site ([screenshot](https://github.com/Automattic/jetpack/assets/52444539/fa85402b-dc1d-4a17-ad4b-ed4007b47adf)).

**Comment by jeherve** [comment] 2024-02-23 08:55
closing this as duplicate of #35503.

**Closed as completed by jeherve** 2024-02-23 08:55 UTC
Labels: Bug, [Closed] Duplicate, [Feature] Subscriptions, [Pri] Normal, [Plugin] Jetpack, Triaged, [Status] Priority Review Triggered
