### ISSUE TITLE
Add `@wordpress/i18n-text-domain` Eslint rule

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#17091] opened 2020-09-07 10:39 UTC
#### Is your feature request related to a problem? Please describe.
Add [`@wordpress/eslint-plugin`](https://github.com/WordPress/gutenberg/tree/021f69b184ef8da97f18d7279bcc48ccb546901a/packages/eslint-plugin#readme) which would give you a bunch of i18n related rules. Specifically you could ensure `jetpack` textdomain is always present for Gutenberg extensions.

Initially it could be defined in [extensions's eslint config](https://github.com/Automattic/jetpack/blob/e245daa4d4b9553e1a378a091c6ae01ebc853ade/extensions/.eslintrc.js) and once `@wordpress/i18n` is used elsewhere in Jetpack, at the root config.

See example:

https://github.com/Automattic/wp-calypso/blob/575477d44dd7d63f41031bc8216d822c12c16d9d/apps/editing-toolkit/.eslintrc.js#L5-L10

#### Additional context
See https://github.com/WordPress/gutenberg/pull/20555

**Comment by jeherve** [comment] 2020-09-07 10:41
Closing as duplicate of #15374 and #16481

**Closed by jeherve** 2020-09-07 10:41 UTC
Labels: Build, Internationalization, [Type] Enhancement

**Comment by simison** [comment] 2020-09-07 11:53
Ahh! Thanks. Dunno why my searching failed so badly for this one. :-)
