### ISSUE TITLE
Loading jetpack.css even though it is not needed

### ISSUE THREAD

**Issue by grappler** [Automattic/jetpack#2322] opened 2015-06-28 20:35 UTC
My site was loading `jetpack.css` when I enabled `add_filter( 'jetpack_implode_frontend_css', '__return_false' );` no CSS files where loaded from Jetpack. It would be great if `jetpack.css` had some of the checks that the single files have.

Related: https://github.com/Automattic/jetpack/issues/1258

**Comment by kraftbj** [comment] 2015-06-29 15:21
I'm unable to duplicate this.

The testing protocol I went through (logged in for all cases):
1. Enabled various front-end JP modules
2. Visited front-end of site. jetpack.css listed as a source.
3. Added `add_filter( 'jetpack_implode_frontend_css', '__return_false' );` to a functionality plugin
4. Returned to front-end. jetpack.css not loaded, individual CSS enqueued. 

Could you provide any additional information that would allow me to duplicate this? Thanks!

**Comment by grappler** [comment] 2015-07-04 15:07
Sorry, you misunderstood me. The simplest way to test it is to 
1. disable all of the modules
2. Return to front end and jetpack.css is still being loaded.

There is no need for the CSS file to be loaded.

**Comment by jeherve** [comment] 2015-07-04 15:16
@grappler Just to be 100% clear about the problem, can you reproduce after adding `add_filter( 'jetpack_implode_frontend_css', '__return_false' );`? Or is that problem not related to the filter at all?

In #1915, we stopped loading `jetpack.css` when Jetpack was in development mode or not connected to WordPress.com. Once you connect to WordPress.com, however, we start loading the file, regardless of the modules currently active on the site. It might be useful to wait until a first module is enabled, but that would cause issues with CSS files that do not depend on a module being enabled, like `modules/theme-tools/responsive-videos/responsive-videos.css`.

Ultimately, the best way to manage jetpack.css would be to monitor files that are not enqueued yet, or that have been dequeued, and concatenate accordingly. That's the issue we're discussing in #1258. But that will require some work, since we currently do not have a way to regenerate jetpack.css on the fly depending on the files enqueued on the site.

**Comment by grappler** [comment] 2015-07-04 15:31
> can you reproduce after adding `add_filter( 'jetpack_implode_frontend_css', '__return_false' );`?
The Jetpack CSS files are not loaded when the filter is added. This would be a bug then if `modules/theme-tools/responsive-videos/responsive-videos.css` needs to be loaded.

> It might be useful to wait until a first module is enabled, but that would cause issues with CSS files that do not depend on a module being enabled, like `modules/theme-tools/responsive-videos/responsive-videos.css`.
I did not know that there functionality that is not able to be disabled in the options.

**Comment by jeherve** [comment] 2015-07-04 15:45
> The Jetpack CSS files are not loaded when the filter is added.

Perfect. That's the expected behaviour. All good there.

> This would be a bug then if `modules/theme-tools/responsive-videos/responsive-videos.css` needs to be loaded.

The file will be loaded, even if you added the filter, as long as your theme supports Responsive Videos. You can find out how to add support to your theme here:
http://jetpack.me/support/responsive-videos/

> I did not know that there is functionality that is not able to be disabled in the options.

It's actually not enabled by default. Responsive Videos is what we call a theme tool. It's part of Jetpack, but is not loaded unless your theme supports it. You can find a list of the different theme tools here:
https://github.com/Automattic/jetpack/tree/3.5.3/modules/theme-tools

I'm going to close this issue now, as the problem is essentially the same as in #1258: we need to find a way to dynamically generate `jetpack.css` based on the files enqueued on the site. Feel free to subscribe to the other issue to follow our progress on this, or share your ideas!

**Closed by jeherve** 2015-07-04 15:45 UTC
Labels: reporter feedback

**Comment by grappler** [comment] 2015-07-04 15:56
Ok, this issue could be solved by just checking if any of the modules or theme tools are activated and the load the jetpack.css. If none of them are activated the the jetpack.css is not needed.

I was thinking about extending the function like so.
```php
public function implode_frontend_css(  $travis_test = false  ) {
	...
	// Check if a module is activated that needs the CSS
	if ( current_theme_supports( 'jetpack-responsive-videos' ) || Jetpack::is_module_active( 'publicize' ) ) {
		return;
	}
	...
}
```

**Comment by jeherve** [comment] 2015-07-04 16:00
That's true, but it won't scale very well as we add more css files to the concatenated `jetpack.css` stylesheet. We would have to check for quite a few things! 

I'd rather have this happen automatically, whenever a stylesheet is enqueued.

Feel free to add your suggestion to the other issue, though, so everyone following the issue can chime in with their opinion.
