### ISSUE TITLE
Feedback statuses (specifically archive)

### ISSUE THREAD

**Issue by jtsternberg** [Automattic/jetpack#13910] opened 2019-10-31 14:54 UTC
#### Is your feature request related to a problem? Please describe.
Right now, there's no way to process feedback. It just sits there, and can only be trashed or spammed.

#### Describe the solution you'd like
As we process feedback, it would be ideal to archive it, and for only non-archived to show by default.

#### Describe alternatives you've considered
Also thought about having a checkbox column on the feedback page to mark them as reviewed.

**Comment by jeherve** [comment] 2019-10-31 15:03
Closing as duplicate of #13001

**Closed by jeherve** 2019-10-31 15:03 UTC
Labels: Contact Form, [Type] Duplicate
