### ISSUE TITLE
Latest Instagram Posts: issue with connecting with Instagram

### ISSUE THREAD

**Issue by marutim** [Automattic/jetpack#17330] opened 2020-09-30 14:46 UTC
#### Steps to reproduce the issue

1. Create a new page or edit an existing page.
2. Add the latest Instagram posts block
3. Click on "Connect to Instagram" button to see the issue.

#### What I expected
- I expect the connection to happen and retrieve latest Instagram posts from my account

#### What happened instead
- The connection fails with the error "An error occurred. Please try again later."

**Screenshots**
![](https://d.pr/i/93WL8z+)

(_Direct link to the image:_ https://d.pr/i/93WL8z)

**Comment by jamiepalatnik** [comment] 2020-09-30 15:34
I was able to recreate this as well. Also reported in 24174511-hc.

**Comment by creativecoder** [comment] 2020-09-30 15:41
Note that this seems to be a problem with Facebook's Instagram API--I don't see anything we can do. Here's a status incident regarding the endpoint used to power the block (https://graph.instagram.com/me/media)

https://developers.facebook.com/status/issues/370520597643291/

**Comment by asheliza29** [comment] 2020-09-30 16:00
I was able to recreate this as well on my test site. Also reported in 3362370-hc.

**Comment by creativecoder** [comment] 2020-09-30 17:26
The [Facebook API issue](https://developers.facebook.com/status/issues/370520597643291/) appears to be resolved. The Lastest Instagram Posts block should be working again (and is on my sites where I use it). I'm going to close this out, but feel free to re-open if needed.

**Comment by davoraltman** [comment] 2021-09-03 10:22
@creativecoder We've had a report of another case in 4268529-zen. It's an isolated case and we aren't able to reproduce it with other IG accounts. Do you have any idea why this issue could still be present somewhere while?

**Comment by xpurichan** [comment] 2021-09-03 16:17
I was the HE involved in the the ticket that Davor has mentioned above yesterday. I experienced another issue with a user unable to connect IG to the legacy IG widget today, in 4271213-zd.

In this case they do not get the error message and instead they can add the widget but when they go to connect IG they popup window (where they would authorize the connection to IG) is blank. The popup window will either remain open and blank, or just appear blank and then disappear within a second.

**Comment by Greatdane** [comment] 2021-09-03 22:16
Regarding 4268529-zd-woothemes

The API shows this response, (a 200 success code, but error when loading the images)

```
{
    "body": {
      "images": "ERROR",
      "external_name": "[redacted]"
    },
    "status": 200,
    "headers": {
      "Allow": "GET"
    }
  }
```

**Comment by formosattic** [comment] 2021-09-05 03:37
+1 4271363-zd-woothemes

Clearing cache, reconnecting didn't help.

**Comment by edwinho89** [comment] 2021-09-21 04:33
31784744-hc

**Comment by Robertght** [comment] 2021-09-21 05:17
I can replicate [this case](https://github.com/Automattic/jetpack/issues/17330#issuecomment-912431313) on my end as well.

**Comment by yansern** [comment] 2021-09-23 06:05
I am unable to replicate this issue and it appears that this issue is largely intermittent.

ℹ️  **My only advice is that if a user reports not able to connect to Instagram, try again later.** Unless it is persistent over the next few days for that particular user, then it is something we should look into.

📊  I am unable to pull data from 20 days ago (fails on logstash), based on the last 7 days window, failing to connect to Instagram seems to be an issue that comes and go, with an abnormal peek between 21-22 Sep, which is around the time that you were able to replicate it @Robertght.

![image](https://user-images.githubusercontent.com/1287077/134460956-1ca20a78-0bf2-4c1b-b986-b2dc62bb36c7.png)

For now I'm closing this issue as not replicable.

**Closed by yansern** 2021-09-23 06:05 UTC
Labels: [Type] Bug, [Type] Happiness Request, [Block] Latest Instagram Posts

**Comment by desnum** [comment] 2022-02-09 16:03
Another case in 34110016-hc

**Comment by jartes** [comment] 2022-12-02 13:21
Another one in 36799021-hc
