### ISSUE TITLE
Bug: Email form - Subscription module: label for: wrong id

### ISSUE THREAD

**Issue by s-a-s-k-i-a** [Automattic/jetpack#2757] opened 2015-09-25 22:32 UTC
Hello!

my html validator spits out an error because of wrong label for subscription field. 
Using Jetpack 3.7
file: https://github.com/Automattic/jetpack/blob/master/modules/subscriptions.php
line: 764

https://github.com/Automattic/jetpack/pull/2756

**Comment by jeherve** [comment] 2015-09-27 12:11
Thanks for the report.  Is duplicate of #2618. Patch submitted in #2632

**Closed by jeherve** 2015-09-27 12:11 UTC
