### ISSUE TITLE
Instant Search: pagination can reload existing items when several items have the same timestamp if sorting by date

### ISSUE THREAD

**Issue by bluefuton** [Automattic/jetpack#19514] opened 2021-04-13 03:18 UTC
#### Steps to reproduce the issue

1. Go to a site with Jetpack Search installed and several products or pages have the same creation timestamp
2. Navigate to `/?s=&sort=newest`
3. Use the "load more results" button

Internal users can see an example in https://github.com/Automattic/jpop-issues/issues/6540.

#### What I expected
"Load more results" would load the next page of results.

#### What happened instead
"Load more results" loads the same products again.

**Screenshots**

<img width="1000" alt="Screen Shot 2021-04-13 at 15 15 57" src="https://user-images.githubusercontent.com/17325/114491735-3506bd80-9c6b-11eb-86a3-003a184b4494.png">

**Comment by jsnmoon** [comment] 2021-04-22 19:54
Similar, but probably no the root cause in this issue: #16188.

**Comment by kangzj** [comment] 2021-04-23 09:03
@jsnmoon I think you were right. In short, the API returns the same page_handle for search request and results in same results as well for the following request.  

The reason is that, there's no offset  (named from) in page_handle when sort by time (class.wpcom-json-api-search-site-v1-3-endpoint.php#L967), so if the timestamp of the last item (page_handle->ts) is the same in one page is the same as it's in the next page, the next page_handle would be the same, which leads to the return of the same items by the API all the time.

And the code between L1278 to L1279 in class.wpcom-json-api-search-site-v1-3-endpoint.php looks very interesting, will be worth investigating.

**Comment by kangzj** [comment] 2021-05-03 08:21
fixed in r225101-wpcom

**Closed by kangzj** 2021-05-03 08:21 UTC
Labels: Instant Search, Search, [Status] In Progress, [Type] Bug
