### ISSUE TITLE
PHP 7.1 Compatibility

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#6106] opened 2017-01-16 14:31 UTC
Synopsis: As PHP 7.1 becomes more and more popular, we should make sure Jetpack is fully compatible.

Responsible: @zinigor

Complete: 70%

Difficulty:  10

Last Updated: May 3rd, 2017 (by @zinigor)

**Comment by zinigor** [comment] 2017-01-16 14:55
According to #5821, Jetpack is fully compatible with PHP 7.1, but we can't merge it yet because it fails with WordPress 4.6. I propose we add 7.1 to `allow_failures` for now and merge it anyway.

**Comment by jeherve** [comment] 2017-01-16 14:58
We've had multiple reports of failures with PHP 7.1 in the past few weeks, so more unit tests is definitely good.

**Comment by cena** [comment] 2017-01-23 18:41
Error logs from a user with 7.1.1 in 3018870-t.  

Downgrading to 7.0 resolved.

**Comment by richardmtl** [comment] 2017-03-17 15:30
Error logs from another user with 7.1 in 3110100-t.

Downgrading to 7.0 resolved them.

**Comment by csonnek** [comment] 2017-04-04 18:31
Error logs from another user: 3141978-t

Asked to downgrade to 7.0 to see if that resolves the issue. Will report back once they respond.

**Comment by xyzulu** [comment] 2017-04-05 05:48
Evn on Jetpack 4.8, php 7.1 is still a no-go for me. Disabling opcache works of course.

**Comment by zinigor** [comment] 2017-05-03 19:05
@xyzulu have you tried upgrading to latest PHP 7.1 since they have deployed a fix for the opcache segfault? If you can try the newest version, that would be very helpful. And if it still doesn't work, can you give us at least some error messages and logs?

Thank you!

**Comment by xyzulu** [comment] 2017-05-03 21:06
7.1.4 still same issue..

**Comment by zinigor** [comment] 2017-05-04 09:27
@xyzulu can you please describe the symptoms you're getting? Also, how is your opcache configured? I'm running 7.1.4 with opcache enabled through FPM, albeit on the settings close to default, and I can't reproduce any errors.

**Comment by xyzulu** [comment] 2017-05-04 09:31
* Switch to php 7.1 (opcache enabled .. FPM) then visit the Jetpack dashboard on wordpress.com
* Attempting to retrieve the site settings/plugins etc shows you an error

**Comment by zinigor** [comment] 2017-05-04 14:47
Thank you, I was able to reproduce, currently trying to narrow it down to file a bug. It doesn't look like it has something to do with Jetpack code, though. I'll post here when I find out more.

**Comment by zinigor** [comment] 2017-05-04 21:11
Created [a new bug report for PHP 7.1.4](https://bugs.php.net/bug.php?id=74543), let's see where that goes.

**Comment by jenhooks** [comment] 2017-06-30 19:00
3298603-t 

User is reporting that the iOS app app shows no posts, pages, or comments. Gets the following error when trying to update:

```
Unable to sync
The Jetpack site is inaccessible or returned an error: transport error -- http
status code was not 200
(502) [-32300]
```

Asked them for server error logs, and requested that they ask their host to roll back their PHP version.

**Comment by kraftbj** [comment] 2017-07-12 15:29
@zinigor On the PHP bug report, can you add a permalink to the code? `master` has changed in the last couple of months and not sure which lines segfault now.

**Comment by pandy06269** [comment] 2017-08-01 20:43
I'm getting the same on a clean install of Ubuntu 16.04.2, PHP 7.1.7 (FPM), Apache, latest WordPress and Jetpack.

PHP FPM log shows very little:

[01-Aug-2017 20:40:15] WARNING: [pool www] child 3372 exited on signal 11 (SIGSEGV) after 21.649971 seconds from start
[01-Aug-2017 20:40:15] NOTICE: [pool www] child 3375 started

**Comment by HansVanEijsden** [comment] 2017-08-01 21:00
@pandy06269 yep, you're not the only one. Thousands of Wordpress clients here on my fresh new PHP 7.1.7 servers, all the same problems. The only "solution" here was defining ```if ( defined( 'XMLRPC_REQUEST' ) && true === XMLRPC_REQUEST ) { ini_set( 'opcache.enable', 0 ); }``` in all the ```wp-config.php``` files of all the clients... 😳

**Comment by kraftbj** [comment] 2017-08-01 22:33
There hasn't been any traction on the PHP bug report. @zinigor Is it time for us to shiv something in place to work around this?

**Comment by kraftbj** [comment] 2017-08-02 22:42
@zinigor is this really only blocked by https://github.com/Automattic/jetpack/issues/6629 ?

Can we mark this one as closed and defer only to 6629?

**Comment by zinigor** [comment] 2017-08-17 17:38
Yes, let's close this one and leave only the remaining issue, thanks!

**Closed by zinigor** 2017-08-17 17:38 UTC
Labels: General, Master Issue, [Pri] High, [Type] Bug
