### ISSUE TITLE
Jetpack Social Menu: Unnecessary code being outputted

### ISSUE THREAD

**Issue by danieldudzic** [Automattic/jetpack#22144] opened 2021-12-20 21:42 UTC
### Impacted plugin

Jetpack

### Steps to Reproduce

1. On an Atomic site, activate the theme Penscratch 2.
2. Check the page source code.
3. You will notice SVG definitions are loaded even if those icons are not used anywhere.

### A clear and concise description of what you expected to happen.

Jetpack to output the SVG code only for the icons being actually used.

### What actually happened

SVG code being outputted for all icons:

![142197266-be198aad-1750-4b8f-944c-b71739bf4a29](https://user-images.githubusercontent.com/905781/146836267-434e00a8-5dd9-49a9-bc20-d8c63cc0fc75.png)

### Other information

Originally reported: https://github.com/Automattic/themes/issues/5112

### Browser

Firefox

**Comment by jeherve** [comment] 2022-01-03 10:25
Closing as duplicate of #16673.

**Closed by jeherve** 2022-01-03 10:25 UTC
Labels: [Type] Bug, Extra Sidebar Widgets, [Plugin] Jetpack
