### ISSUE TITLE
Vimeo shortcode: Vimeo embedded videos are letterboxed in 3.9

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#3332] opened 2016-01-22 14:41 UTC
Confirmed a user report that starting in 3.9, Vimeo videos that are embedded by simply pasting the Vimeo link into a post are page are letterboxed, whereas in 3.8.2 they were not.

Screenshot of video in 3.8.2: https://www.dropbox.com/s/qh1m569vszoxxqb/Screen%20Shot%202016-01-21%20at%208.59.19%20AM.png?dl=0

Screenshot of same video in 3.9: https://www.dropbox.com/s/a4j2qlbaae5kdd9/Screen%20Shot%202016-01-21%20at%208.56.20%20AM.png?dl=0

2501625-t

**Comment by chaselivingston** [comment] 2016-01-22 14:53
Also reported in 2501935-t

**Comment by Leland** [comment] 2016-01-22 21:42
Am seeing this on a client's site as well. The Shortcode Embed module in 3.9 altered the sizes of all oEmbeds added via plain text links across the site – not just Vimeo videos.

[Vimeo oEmbed 3.8.2](https://cloud.githubusercontent.com/assets/714017/12523437/c5d21238-c10b-11e5-9f61-e4c3ad418839.png) / [Vimeo oEmbed 3.9.1](https://cloud.githubusercontent.com/assets/714017/12523436/c5d1583e-c10b-11e5-928a-b6e13b85c710.png)
[Youtube oEmbed 3.8.2](https://cloud.githubusercontent.com/assets/714017/12523596/af69ce18-c10c-11e5-92fa-a2a3f3fb2bdd.png) / [Youtube oEmbed 3.9.1](https://cloud.githubusercontent.com/assets/714017/12523603/bdd98420-c10c-11e5-9a09-16f2b36b17fb.png)

**Comment by kraftbj** [comment] 2016-01-24 04:25
For Vimeo, caused by 2f5f7b8e54cf18499020dee23f63a87bb4aa5db1
I wasn't able to duplicate a YouTube difference between those two versions, but the offending Vimeo commit brings Vimeo to the same method YouTube embeds used.

I might be missing something, but what is the advantage of Jetpack getting involved on plain-text links for either Vimeo or YouTube? Both will oEmbed on Core without Jetpack.

**Comment by jeherve** [comment] 2016-02-03 14:19
Also reported here:
https://wordpress.org/support/topic/vimeo-embeds-broken?replies=1&view=all

**Comment by chaselivingston** [comment] 2016-03-01 15:43
Also reported in 2557125-t

**Comment by eliorivero** [comment] 2016-03-02 21:13
I haven't had luck reproducing this. It works fine if I embed a Vimeo video pasting the link or if I use it in a shortcode. I commented/uncommented this line `add_action( 'init', 'wpcom_vimeo_embed_url_init' );` and cleared oEmbed cache during tests but it worked in the same way. Tested with Twenty 12, 15 and 16 in WP 4.5 beta 1, with no other plugins enabled, with [this link](https://vimeo.com/142495451).
Were any of you able to reproduce it? If so, can you post the conditions under which you were able to reproduce? Vimeo link, theme, other plugins, WP version, everything helps.

**Comment by chaselivingston** [comment] 2016-03-02 21:58
@eliorivero Looks like it may have been fixed/started working, I'm not seeing this behavior anymore. Could be related to something that was done in WordPress 4.5 perhaps?

**Comment by eliorivero** [comment] 2016-03-04 13:52
Couldn't tell for sure but if it's working for you too I'm closing for now. Everyone feel free to reopen the issue if you can reproduce and add the steps and extra information so we can reproduce it as well.

**Closed by eliorivero** 2016-03-04 13:52 UTC
Labels: Shortcodes, [Type] Bug
