### ISSUE TITLE
Jetpack not resizing images according to `width` and `height` attributes.

### ISSUE THREAD

**Issue by asafm7** [Automattic/jetpack#21887] opened 2021-11-28 11:11 UTC
### Impacted plugin

Jetpack

### Steps to Reproduce

Using the native Media & Text block.

Image size set to Large.

### A clear and concise description of what you expected to happen.

If I understand correctly Jetpack is supposed to automatically resize images according to the image `width` and `height` attributes.

If it is supposed to do so, it seems it is sometimes failing. Please see the screenshot attached. Maybe it is related to Lazy Loading?

![image](https://user-images.githubusercontent.com/14274769/143765139-4135dc49-3f3a-4259-a164-9e9783cc456d.png)

The link to the page: (I might resize the images manually by the time you get to it)
https://eyalshifroni.com/

### What actually happened

Images are "resized" to their original size.

### Operating System

Windows

### OS Version

10

### Browser

Chrome/Chromium

**Comment by jeherve** [comment] 2021-11-29 07:04
Thanks for the report. 

It would be interesting to know what is the markup of those images when you disable the image CDN feature under Jetpack > Settings > Performance? Could you give it a try, and let us know what you find?

Thank you!

**Comment by asafm7** [comment] 2021-11-29 10:19
Thanks for your reply.

So without the image CDN, the `width` and `height` for the image in the screenshot are 1024 and 1024.

When the CDN is enabled the dimensions are changed retroactively after page load. Apparently, too late.

You can see it in this video:
https://www.loom.com/share/acd940b94bb943149c681fecfb4f4705

You wouldn't be able to reproduce it on the site as I replaced the image with a resized version.

Let me know I can do anything else to help.

**Comment by jeherve** [comment] 2021-12-03 17:52
Thank you for the extra details, that's super helpful!

May I ask what your settings are under Settings > Media in your dashboard?

Could you also check your theme's `functions.php` file, and let me know if you find any `$content_width` value defined there? 

*******

Potentially related: #7291, #4175

**Comment by asafm7** [comment] 2021-12-03 19:03
Thanks for your reply.

I couldn't find `$content_width` defined in either the parent or child theme `functions.php`s.

The media settings:
![image](https://user-images.githubusercontent.com/14274769/144658404-4fae17d1-073b-4cd6-8569-5b8eb86993ae.png)

**Comment by asafm7** [comment] 2021-12-20 09:56
@jeherve do you need any more information from me?

**Comment by jeherve** [comment] 2022-01-03 12:31
No, thank you, that was helpful. I was not able to understand what was happening, but we'll update this issue when we manage to solve the issue!

**Comment by jeherve** [comment] 2024-01-15 12:30
Closing as duplicate of #35005.

**Closed by jeherve** 2024-01-15 12:30 UTC
Labels: [Type] Bug, [Feature] Photon, [Pri] Normal, [Plugin] Jetpack
