### ISSUE TITLE
Subscription Emails - Language Defaults to English, not Site Language

### ISSUE THREAD

**Issue by donalirl** [Automattic/jetpack#16559] opened 2020-07-23 08:19 UTC
#### Steps to reproduce the issue

1. Add a Subscription block to your site
2. Set your site's language to something other than English, such as French
3. Subscribe to the site using an email address **not connected to a WordPress.com account**
4. See the language of the subscription confirmation email is in English

#### What I expected

I expected the language of the email to be in the site's language, like French in the above example.

#### What happened instead

The email arrived in English.

As I understand it, if my WordPress.com account's interface language is set to French, I'll get the email in French. Or Russian is my account is set to Russian. That makes sense. 

But for subscribers without a WordPress.com account, it makes more sense to have it in the site's language. This is because the subscriber is browsing a site in French, and subscribes to that site using a French subscription form, so it is a safe assumption that they understand French. Therefore, it's logical that they receive an email in French, not English.

**Screenshots**
![Dj2CTS](https://user-images.githubusercontent.com/30727666/88265431-d716fc00-cd10-11ea-8177-a63a5e6a6562.png)

#22836384-hc

**Comment by jeherve** [comment] 2020-07-23 11:02
This may be a duplicate of #1122. 

Could you check the steps described here? https://github.com/Automattic/jetpack/issues/1122#issuecomment-613917680

If you're experiencing something different, I would recommend reopening that issue.

**Closed by jeherve** 2020-07-23 11:02 UTC
Labels: Internationalization, Subscriptions, [Pri] Low, [Status] Needs Author Reply, [Type] Bug
