### ISSUE TITLE
Sharing: Ability for users to define their own email templates

### ISSUE THREAD

**Issue by dartiss** [Automattic/jetpack#7106] opened 2017-05-02 18:35 UTC
A WordPress VIP client has requested an ability to modify the layout of the sharing email via a simple templating method.

> We’d like to be able to edit a template, that would let us customize how the email looks when the user shares it. Right now, when they share it – it looks very “bloggy” and we’d like to be able to customize it a bit more.

#65279-z

**Comment by jeherve** [comment] 2017-05-03 21:08
Closing as duplicate of #419

**Closed by jeherve** 2017-05-03 21:08 UTC
Labels: Sharing
