### ISSUE TITLE
Tiled Galleries: adding an option to turn  CDN on/off 

### ISSUE THREAD

**Issue by StefMattana** [Automattic/jetpack#19675] opened 2021-04-28 06:51 UTC
Writing on behalf of a user [from the JP forum](https://wordpress.org/support/topic/site-accelerator-formerly-photon-disabled-issue/) as they still need to create a GH account for them. 

They basically suggest creating two options for the Media related to the way we handle the Tiled Galleries: 

- > transform your galleries to tiled (without CDN)
- > use CDN for load images, more simple, faster and you can change to the standard gallery when you want, you no will break your galleries in time.

They also suggest adding an easy way to revert the tiled gallery to a standard WordPress gallery.

**Comment by jeherve** [comment] 2021-04-28 07:41
Closing as duplicate of #19658

**Closed by jeherve** 2021-04-28 07:41 UTC
Labels: Tiled Gallery, [Block] Tiled Gallery, [Type] Feature
