### ISSUE TITLE
VR shortcode shows an error after it quits trying to load.

### ISSUE THREAD

**Issue by csabarakasz** [Automattic/jetpack#32799] opened 2023-08-31 19:27 UTC
### Impacted plugin

Jetpack

### Quick summary

The user reported that the VR block stopped working on their site, which I was able to replicate. As matter a fact, it gives me an error on our own [Embedding 360° Photos and Virtual Reality (VR) Content](https://wordpress.com/support/embedding-360-photos-and-virtual-reality-vr-content/) page:

![j4lzyPMu7QzfaIxHom1iXfMkfWbSIxCWYphm5G5y.jpg](https://github.com/Automattic/jetpack/assets/84539773/59442e1d-f90d-43db-b528-9ffcb91a4f84)

The image is there: https://en-support.files.wordpress.com/2016/12/vr-shortcode-360.jpg but the VR code fails to load: https://vr.me.sh/view/?view=360&url=https://en-support.files.wordpress.com/2016/12/vr-shortcode-360.jpg

Console return this error:
![1uikvHfflA2Z22GsHhdYCB6F1RTx4McARmFVidia.jpg](https://github.com/Automattic/jetpack/assets/84539773/a9aaef5b-fce4-4f63-976c-1d8627628931)

with `We cannot complete this request, remote server returned an unexpected status code (400)`

User report: 6663821-zd-a8c

From what I was able to understand, Jetpack CDN gives up the loading process. 

### Steps to reproduce

Upload a VR image, include the shortcode and visit the live site. 

Or visit: https://wordpress.com/support/embedding-360-photos-and-virtual-reality-vr-content/

In some cases, uploading a smaller version of the image helped. But it used to work before with the larger image as well (User feedback.)

### Impact

One

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Chrome: Version 116.0.5845.110 (Official Build) (arm64)
Replicated in Firefox 117.0 (64-bit) and Safari (Version 16.5) as well

**Comment by cuemarie** [comment] 2023-08-31 19:36
Quick note on

> Or visit: https://wordpress.com/support/embedding-360-photos-and-virtual-reality-vr-content/

This support doc shows the 360 images without issue for me, in Firefox 117.0 (64-bit) (latest version).

![Markup on 2023-08-31 at 15:40:27](https://github.com/Automattic/jetpack/assets/27249804/18a449f4-3b1b-417c-acb3-59c6ea8e3815)

Will test further across browsers, but lowering priority for the moment.

**Comment by cuemarie** [comment] 2023-08-31 22:46
📌 REPRODUCTION RESULTS
- Tested on https://wordpress.com/support/embedding-360-photos-and-virtual-reality-vr-content/ – Could Not Replicate 
- Tested on Customer's Site – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
I'm unable to replicate this issue so far; wondering if this hasn't been resolved already. 

Screenshot of guide doc behavior is in previous comment; shared a recording of what I'm seeing on the customer's site here: p1693521870436529/1692694623.999249-slack-CBG1CP4EN

📌 ACTIONS
- Requested author feedback

📌 Message to Author
@csabarakasz can you retest and let me know if you're still able to replicate this as you were before?

**Comment by csabarakasz** [comment] 2023-09-03 13:41
@cuemarie Interestingly, the error seems to be country-connected. When I tested again from my end, I could replicate all the issues mentioned before on the user's site or the Support doc. 

Then I tried with VPN, using USA servers, and the issue went away. Unusual. 

Since I can replicate this issue on multiple sites, I wonder if this is somehow Jetpack/country-specific. 

Here is my recording: p1693748465463109/1692694623.999249-slack-CBG1CP4EN

**Comment by jeherve** [comment] 2023-09-04 10:29
This is most likely happening because the original image is quite big (17.2Mb):
https://en-support.files.wordpress.com/2016/12/vr-shortcode-360.jpg

Our CDN most likely failed to download the image at some point, and some of us see a broken image as a result, depending on which node of the CDN we're hitting.

I have now nuked the cache for that image, allowing the CDN to try to download a new copy for all its nodes. Hopefully it will help!

**Comment by davemart-in** [comment] 2024-10-15 16:24
This seems edge case and there has been no movement in over a year, so I'm closing the issue.

**Closed as completed by davemart-in** 2024-10-15 16:24 UTC
Labels: Bug, [Feature] Photon, [Pri] Low, Customer Report [LEGACY], [Plugin] Jetpack, Triaged
