### ISSUE TITLE
Sync: don't sync broken image URLs

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#20302] opened 2021-07-07 19:24 UTC
We've had a couple of support issues recently where the images displayed for Jetpack Search do not have the correct urls and so result in 404s for the images. Examples in https://github.com/Automattic/jpop-issues/issues/6704 and https://github.com/Automattic/jpop-issues/issues/6706

Frustratingly for the user and HEs it is tough to debug because everything on the main site seems to work. I think that often it is related to migrating between domains, or old urls in the DB. My guess is that the main site is able to correct for these problems but the data that we sync is not correct and so when we index it there are other problems. We could maybe hack around it in the indexing, but it likely will show up in other features as well.

**I think the best solution would be for Sync to actually correct the broken image urls rather than syncing data that won't work. Seems like this could even be a feature of Scan or something where it notifies the user of potential problems.**

Currently the way image extraction works for Search is that we use the data that has been synced and then extract the images that are not too small. On the indexing side we use this code (but running on wpcom): https://github.com/Automattic/jetpack/blob/e8e395ad3bb575f1df9dc932a9831bf44d8a250a/projects/plugins/jetpack/_inc/lib/class.media-extractor.php#L383

**Comment by bobmatyas** [comment] 2021-07-20 13:00
Another example of this on 4160038-zen.

**Comment by bobmatyas** [comment] 2021-08-04 12:45
Additional reports on:

* 4188742-zen
* 4160038-zen

**Comment by bobmatyas** [comment] 2021-08-09 19:11
Another report here:

* 4160038-zen

**Comment by bobmatyas** [comment] 2021-11-02 21:59
We have another instance of this in: 4424128-zen

**Comment by robfelty** [comment] 2021-11-03 18:18
I looked into 4424128-zen, and did a bit more debugging, and discovered that indeed that instant-search is simply reading the value from the index, while elsewhere in WordPress, the url is being constructed on the fly. I think we should solve this on the frontend. I'll need to figure out how to create a proper pull request for Jetpack, as my `git push` to a new branch failed, but I wanted to get some feedback from the @Automattic/jetpack-search team to see if this approach is on the right track.
```diff
diff --git a/projects/plugins/jetpack/modules/search/instant-search/lib/hooks/use-photon.js b/projects/plugins/jetpack/modules/search/instant-search/lib/hooks/use-photon.js
index 2da9d1b48..ec4d2c55d 100644
--- a/projects/plugins/jetpack/modules/search/instant-search/lib/hooks/use-photon.js
+++ b/projects/plugins/jetpack/modules/search/instant-search/lib/hooks/use-photon.js
@@ -17,6 +17,22 @@ function stripQueryString( url ) {
        return url.split( '?', 1 )[ 0 ];
 }

+/**
+ * Returns only the relative path of the image, after the query string has
+ * already been stripped
+ *
+ * @param {string} url - Image URL
+ * @returns {string} - relative path of image
+ */
+function getImagePath( url ) {
+       if ( ! url ) {
+               return '';
+       }
+       // first strip out any protocols
+       url = url.replace( /[a-z:]*\/\//, '' );
+       return url.split( '/' ).slice( 1 ).join( '/' );
+}
+
 /**
  * Hook for returning a Photonized image URL given width and height parameters.
  *
@@ -37,6 +53,12 @@ export function usePhoton( initialSrc, width, height, isPhotonEnabled = true ) {
                ?.substring( initialSrcWithoutQueryString.lastIndexOf( '.' ) + 1 )
                .toLowerCase();
        const isSupportedImageType = supportedImageTypes.includes( fileExtension );
+       initialSrc =
+               window.location.protocol +
+               '//' +
+               window.location.hostname +
+               '/' +
+               getImagePath( initialSrcWithoutQueryString );

        useEffect( () => {
                if ( isPhotonEnabled && isSupportedImageType ) {
```

**Comment by jsnmoon** [comment] 2021-11-04 21:27
> [...] I think we should solve this on the frontend. I'll need to figure out how to create a proper pull request for Jetpack, as my `git push` to a new branch failed, but I wanted to get some feedback from the jetpack-search team to see if this approach is on the right track. (@robfelty)

The `getImagePath` function seems reasonable and an obvious candidate for some rudimentary unit testing.

I think we'll want to verify the correctness of the `initialSrc` mutation in the `usePhoton` hook; I can see it failing if WordPress is installed on a subdirectory instead of the root. We handle this in other parts of Instant Search via the `JetpackInstantSearchOptions.homeUrl` like [so](https://github.com/Automattic/jetpack/blob/017dd147fdb0bd314d95dd5819e77a477f52837d/projects/plugins/jetpack/modules/search/instant-search/lib/query-string.js#L54).

I have a concern, though: Does this mean that our search index data is no longer the source of truth? By reconstructing the image URL in the front-end, we're now relying on a combination of index data and front-end logic to determine the "true" location of the image URLs. This will likely be a hindrance to productizing our search API for public consumption in the future.

**Comment by gibrown** [comment] 2021-11-05 15:04
I think that code won't work if their images are hosted on another site. There are definitely cases where the host name will not match the current site so I'm not sure we can easily rewrite it in JS. We currently extract the images from post content which can include just an image tag for an image that is not stored as an attachment.

Is `post_content_filtered` a viable option on the indexing side? Does that have the correct url in these cases?

**Comment by robfelty** [comment] 2021-11-05 17:13
How does it happen that the hostname does not match the current site?

I think the best thing to do is try to mimic the core WordPress functionality as closely as possible. I looked into this very briefly today on the API side, and I think it is probably doable there, which might be our best bet. 

I don't think that `post_content_filtered` will work, because the issue is not about images in the post_content, but rather the featured image, which is in post meta. Maybe there is an equivalent filter for post meta?

 I guess one thing we want to ask ourselves is whether or not we want to force a full sync and re-index when the user changes the siteurl. Perhaps that is necessary, but it seems like it would be nice not to have to do that.

**Comment by gibrown** [comment] 2021-11-15 21:34
> How does it happen that the hostname does not match the current site?

The image could be hosted somewhere else. For instance wp.com sites may have the image at xyz.wordpress.com even though there is a mapped domain name.

> I think the best thing to do is try to mimic the core WordPress functionality as closely as possible.

This makes sense to me too, maybe we need to pull apart the code that WP uses and replicate it in some way? Or run some of the image extraction code during the sync process? https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/_inc/lib/class.media-extractor.php is the same code (mostly) that we use for our indexing.

**Comment by bobmatyas** [comment] 2021-11-22 20:53
Another report in 4536728-zen

**Comment by robfelty** [comment] 2021-11-24 13:58
Thanks for the pointer @gibrown - that was very helpful.
I narrowed it down to [this line in post.php](https://github.com/WordPress/wordpress-develop/blob/ba943e113d3b31b121f77a2d30aebe14b047c69d/src/wp-includes/post.php#L6401)
> $file = get_post_meta( $post->ID, '_wp_attached_file', true );

It turns out that for featured images, sometimes they have a postmeta of `_wp_attached_file`, but sometimes they don't, and instead have either `_thumbnail_id` and/or `jetpack_featured_image`. If there is no `$file` found, then the fallback is to use the `guid`, which is the behavior we are seeing in these cases.

I can think of at least 2 different options for how to fix this:
1. In WP Core `post.php`, if `_wp_attached_file` is not set, also check for `_thumbnail_id`.
2. When we are indexing content into Elasticsearch, we could make this check.

**Comment by robfelty** [comment] 2021-12-03 11:27
I deployed a fix for this today. In the future, whenever a site using Jetpack Instant Search updates its siteurl, we will re-index all the posts, and the image urls should all refer to the new siteurl. If there are still sites having issues currently, we should be able to re-index them, and that should fix the problem. 

I think we can probably close this one now, but I will wait for some additional feedback from others first.

**Comment by gibrown** [comment] 2021-12-03 16:01
Really nice find. I think let's close this and we can reopen if more user reports come in.

Just to note, the easiest way to trigger a re-index is probably to just trigger a full sync for the site.

**Comment by robfelty** [comment] 2021-12-06 12:56
Unfortunately this change broke a bunch of other urls :(

Re-opening, and looking for a fix.

**Comment by robfelty** [comment] 2021-12-07 16:58
I deployed another fix today, which I think should fix it once and all.

**Closed** 2021-12-13 14:35 UTC
Labels: [Type] Bug, [Package] Sync, [Status] Proposal, Search, [Type] Happiness Request
