### ISSUE TITLE
Google Calendar block will not load in editor

### ISSUE THREAD

**Issue by dhackneya8c** [Automattic/jetpack#33540] opened 2023-10-10 16:42 UTC
### Impacted plugin

Jetpack

### Quick summary

When trying to add a Google Calendar block on a simple site, it immediately shows this error:

![Screenshot on 2023-10-10 at 09-28-03](https://github.com/Automattic/jetpack/assets/24231249/9d866262-1c10-4622-9593-55fae638671f)

As a result, the block cannot be used at all in its current state. Copying and pasting the Google Calendar URL into a paragraph line produces the block, but a permissions error appears even if the calendar is set to public:

<img width="995" alt="Screenshot 2023-10-10 at 9 43 33 AM" src="https://github.com/Automattic/jetpack/assets/24231249/531c8057-61c3-4865-a2ea-8ca9144e635c">

### Steps to reproduce

1. Open a simple site page or post for editing 
2. Try to add a Google Calendar block

### A clear and concise description of what you expected to happen.

The block should appear with an input field to add your Google Calendar

### What actually happened

The block displays a previewing error

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

**Comment by anomiex** [comment] 2023-10-10 17:34
Thanks for the report!

This was presumably caused by a recent update to the Gutenberg plugin on Simple sites. It's already fixed in Jetpack trunk (in #33428 / https://github.com/Automattic/jetpack/pull/33428/commits/97042c83807e8cf5e4f61be704d4b85c41a3c9fc) and will be deployed to Simple with the next daily deploy.

**Closed as completed by anomiex** 2023-10-10 17:34 UTC
Labels: Bug, [Pri] Normal, [Focus] Blocks, [Plugin] Jetpack, [Platform] Simple, Needs triage, [Feature] Misc Blocks
