### ISSUE TITLE
Error token

### ISSUE THREAD

**Issue by tkthiago2** [Automattic/jetpack#7324] opened 2017-06-08 12:59 UTC
#### What happened instead

unknown_token: It looks like your Jetpack connection is broken. Try disconnecting from WordPress.com then reconnecting.

We had trouble connecting.
Tente novamente
WordPress.com was unable to reach your site and approve the connection. Try again by clicking the button above; if that doesn't work you may need to contact support.
Error Details
transport error - HTTP status code was not 200 (502)
By connecting your site, you agree to share details between WordPress.com and .Tente novamente

**Comment by zinigor** [comment] 2017-06-08 17:30
This looks like it's a duplicate of #7322. Are you using nginx to host your site? If so, can you try using the suggested settings and trying again?

Please reopen the issue if you are having a different problem. Thank you!

**Closed by zinigor** 2017-06-08 17:30 UTC
