### ISSUE TITLE
Upload Site Icon Errors With No Such File or Directory

### ISSUE THREAD

**Issue by RehanSaeed** [Automattic/jetpack#2210] opened 2015-06-02 13:45 UTC
I simply try to upload a new site icon and I get the following errors:

Warning: getimagesize(D:\home\site\wwwroot/wp-content/uploads/2015/06/Icon1-temp.png): failed to open stream: No such file or directory in D:\home\site\wwwroot\wp-content\plugins\jetpack\modules\site-icon\jetpack-site-icon.php on line 688 Warning: Division by zero in D:\home\site\wwwroot\wp-content\plugins\jetpack\modules\site-icon\jetpack-site-icon.php on line 364 Warning: Division by zero in D:\home\site\wwwroot\wp-content\plugins\jetpack\modules\site-icon\jetpack-site-icon.php on line 492 Warning: Division by zero in D:\home\site\wwwroot\wp-content\plugins\jetpack\modules\site-icon\jetpack-site-icon.php on line 493

Could this have something to do with me having the Azure Storage plug-in installed, so all my images come from the Azure CDN?

**Comment by kraftbj** [comment] 2015-06-02 16:05
> Could this have something to do with me having the Azure Storage plug-in installed, so all my images come from the Azure CDN?

@RehanSaeed Most likely yes. It looks like the cause of the error is we're expecting the temporary file we uploaded to exist in /wp-content/uploads/, but it isn't there.

I'm not familiar enough with the Azure plugin currently to speculate deeper what the problem may be.

**Comment by RehanSaeed** [comment] 2015-06-02 19:33
Looks like Site Icon will not work with any plugin enabling use of CDN's. There is another feature suggestion I have seen advocating the use of the media manager rather than a file selector for the image. Using the media manager would probably solve this issue also.

**Comment by kraftbj** [comment] 2015-06-02 21:35
A lot of CDNs will keep a local copy of the image in the uploads folder, which I think is what we're expecting here. Using the media manager would likely solve this though, agreed.

**Comment by kraftbj** [comment] 2015-07-28 03:09
Going to mark this as closed since Site Icon was merged/adapted into Core, so an issue like this (if remains) is a core issue.

**Closed by kraftbj** 2015-07-28 03:09 UTC
Labels: bug, Site Icon
