### ISSUE TITLE
Carousel: exits to site main page

### ISSUE THREAD

**Issue by khaoticdude** [Automattic/jetpack#24021] opened 2022-04-20 16:46 UTC
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Enable Jetpack Carousel
2. Open image within a post to initiate the carousel
3. Try exit the image by clicking the given exit indicator

### A clear and concise description of what you expected to happen.

When you exit the carousel image, you should be sent back to the post (same as if you pressed "escape" in the carousel)

### What actually happened

When trying to exit an image that is opened via the carousel, you are redirected to the site's main page. There seems to be an overlay issue or something.

### Operating System

Linux

### Browser

Firefox

**Comment by jeherve** [comment] 2022-04-22 10:29
I cannot seem to reproduce on my end. Could you post a link to a page where you experience this problem? 

Could you also try with a different theme, like one of the default WordPress themes, and let us know if this still happens?

Thank you!

**Comment by khaoticdude** [comment] 2022-04-22 14:41
https://khaoticdev.net/hack-the-box-shibboleth/I will try another theme and report back.On Apr 22, 2022 05:29, Jeremy Herve ***@***.***> wrote:
I cannot seem to reproduce on my end. Could you post a link to a page where you experience this problem?
Could you also try with a different theme, like one of the default WordPress themes, and let us know if this still happens?
Thank you!

**Comment by khaoticdude** [comment] 2022-04-23 16:35
Looks like trying with a Wordpress theme works fine. This leads me to assume it may be some custom CSS I added.

**Comment by khaoticdude** [comment] 2022-04-23 16:48
> Looks like trying with a Wordpress theme works fine. This leads me to assume it may be some custom CSS I added.

Removed all custom CSS and still get the issue. I guess the theme changed at some point.

**Comment by khaoticdude** [comment] 2022-04-23 19:31
Seems to be an issue with the Travern theme and jetpack

**Comment by jeherve** [comment] 2022-04-25 16:38
Thanks for the extra details. Is this the theme you're using?
https://themeforest.net/item/tavern-professional-restaurant-theme/10984149

**Comment by khaoticdude** [comment] 2022-04-25 17:17
No, this is the theme I am user https://flythemes.net/wordpress-themes/travel-wordpress-theme/

I reached out to the theme's support email and they requested I give them login credentials so they can check the backend on my server. I can't tell if it was a joke or not...

**Comment by jeherve** [comment] 2022-04-25 17:22
Thanks, I had missed the extra "r" in the theme's  name :)

Since it's a premium theme I cannot download it to test on a test site of mine, but looking at the demo page, I see that the theme loads a number of js files on each page. Do you have a way to deactivate some of the features that rely on JavaScript in the theme settings? I see there are different sliders that rely on JavaScript for example. That may help us narrow things down a bit, and figure out what's causing this.

**Comment by khaoticdude** [comment] 2022-04-25 18:25
You should be able to install the theme via the WP theme panel. That's how I installed it.

**Comment by jeherve** [comment] 2022-04-26 11:15
Thank you! The theme is indeed available in the WordPress.org theme directory as well, and I was able to reproduce the issue with that theme active. 👍 

I've updated the description in #6244 so it's now a lot easier to reproduce and investigate.

I'll close this issue now that we can continue the investigation in the original issue. Thanks for all the details!

**Closed by jeherve** 2022-04-26 11:15 UTC
Labels: [Type] Bug, Carousel, [Status] Needs Author Reply, [Plugin] Jetpack
