### ISSUE TITLE
Publicize: Facebook does not use the "Excerpt" content

### ISSUE THREAD

**Issue by hunterhogan** [Automattic/jetpack#1183] opened 2014-10-11 17:18 UTC
Website: www.hunterthinks.com
When I create a new post (not a custom post type), if I set the "Excerpt" field, when Publicize posts the content to Facebook, it does not use the information in the Excerpt box. Instead, it behaves as if the excerpt did not exist.

Example from Facebook: https://www.facebook.com/hunterthinks/posts/826086950777004
For comparison, the same post on Google+, with the Excerpt value displayed: https://plus.google.com/u/0/+HunterHogan/posts/Z76xwubhiVA

Until recently, this issue was trivial. However, I have started to restrict access to some posts, including the post listed above. I do not want some of the content of the post to "leak" because of the Publicize feature. I want the Publicize module to respect the Excerpt feature.

I looked for settings that might affect this but I could not find any. If there is a setting, please advise. If this issue is beyond your control, please advise.

Thank you for your time.

**Comment by mikeyarce** [comment] 2015-02-10 18:15
In my tests I get the same error - on initial crawl Facebook does not use the `og:description` from Jetpack, but later on it does.  Other social networks I publicize to work fine, just not FB.

**Comment by jeherve** [comment] 2015-04-16 13:48
Also suggested here:
https://wordpress.org/support/topic/publicize-includes-long-text-excerpt-and-coding?replies=1&view=all

**Comment by richterd** [comment] 2015-04-28 17:46
Hi, I have a similar issue: The first time "Facebook crawls the page" or "Jetpack sends the content to Facebook" (I don't know what method is used here), the post content includes shortcode tags. Later on everything works fine...

**Comment by jeherve** [comment] 2015-07-10 17:16
Also suggested here:
https://wordpress.org/support/topic/publicize-posting-quirks-to-facebook-and-twitter?replies=6&view=all

**Comment by jeherve** [comment] 2015-07-27 12:24
As reported in https://github.com/Automattic/jetpack/issues/508#issuecomment-125183772 , this issue also applies to posts that are broken up with the More tag.

**Comment by machtwebseiten** [comment] 2015-07-28 08:59
Just to add my 2 cents: we have the same "bug" on our Wordpress installation. It always generates it's own excerpt and adds [??? more words] on the end. As our blog is not in English this is annoying for our readers so now we are back to posting articles to facebook manually until this issue is resolved

**Comment by jeherve** [comment] 2015-10-05 15:52
Also suggested here:
https://wordpress.org/support/topic/remove-xxx-more-words-from-facebook-post-shorter-facebook-excerpt?replies=1&view=all

**Comment by blissio** [comment] 2016-02-01 10:47
Any news on getting this fixed?

**Comment by jeherve** [comment] 2016-02-01 12:34
@blissio No yet, but we'll update this issue as soon as we make progress on this.

**Comment by jeherve** [comment] 2016-02-01 13:46
Also reported here:
https://wordpress.org/support/topic/reduce-excerpt-when-sharing?replies=4&view=all

**Comment by sergiovilar** [comment] 2016-04-04 21:35
I have the same issue, any news about the fix?

**Comment by jeherve** [comment] 2016-04-07 21:36
@sergiovilar No news here, but we'll update this issue when we make some progress on this.

**Comment by sergiovilar** [comment] 2016-04-07 22:30
@jeherve I wanna help, could you give me some tips to solve or look for the issue?

**Comment by jeherve** [comment] 2016-04-08 08:35
@sergiovilar I'm afraid you won't be able to help here, since the Publicize code generating that content lives on WordPress.com.

**Comment by annezazuu** [comment] 2016-04-13 09:12
reported here #2148408-t

**Comment by AlbertoTurmina** [comment] 2016-05-24 18:53
No solution?

**Comment by annezazuu** [comment] 2016-08-03 20:42
brought up in 2764553-t

**Comment by scarstocea** [comment] 2016-08-09 14:45
brought up in #2771083-t

**Comment by stappjno** [comment] 2016-08-19 07:14
Is there a working Workaround for this? If we have to live with the more words thing it would be really nice if we can translate it because our website is in german and the english "more words" looks really ugly.

**Comment by jeherve** [comment] 2016-08-19 10:53
@stappjno The phrase should be translated into your site's language, as set under Settings > General in your dashboard. If that doesn't seem to work, could you [send us an email](http://jetpack.com/contact-support/) with more information about your site so we can take a look?

In the meantime, if you wanted to remove this from your Facebook updates, you could use the Publicize box appearing right above the Publish button; if you specify a custom Publicize message there, it will replace the automated excerpt.

I hope this helps.

**Comment by stappjno** [comment] 2016-08-19 11:08
@jeherve Thank you! We have set the language of the wordpress-installation to de but that doesn't translate the "more words" part. But we are confident with the solution to write the small exerpt. If there is a such solution, why is this issue still open?

**Comment by jeherve** [comment] 2016-08-19 11:12
> that doesn't translate the "more words" part. 

Could you contact us via email, so we can take a closer look at your site and its Jetpack settings?

Thanks!

> If there is a such solution, why is this issue still open?

The solution I offered is only a workaround. Ideally, whenever you use the "Excerpt" meta box appearing below the visual editor, that custom excerpt should be used instead of the automated excerpt currently generated by Publicize. Once that's how Publicize behaves, we'll close this issue.

**Comment by jeherve** [comment] 2016-08-25 16:02
Also reported here:
https://wordpress.org/support/topic/how-to-limit-the-words-or-characters-displaying-as-descrtiption-into-fb-post?replies=1

**Comment by jeherve** [comment] 2016-09-27 14:28
Also suggested here:
https://wordpress.org/support/topic/jetpack-posting-to-facebook-with-xx-more-words/#post-8179626

**Comment by jenhooks** [comment] 2016-10-03 01:21
2854260-t

**Comment by lamdayap** [comment] 2016-10-09 11:33
Brought up here: 2854416-t

**Comment by annezazuu** [comment] 2016-10-22 18:04
2883450-t

**Comment by jeherve** [comment] 2016-11-16 21:23
Also reported here:
https://wordpress.org/support/topic/get-rid-of-xxx-more-words-in-publicize/

**Comment by gregwp** [comment] 2016-12-05 21:34
Also here: 2945568-t

**Comment by rmens** [comment] 2017-01-11 18:13
This is kinda crazy. A plugin that is vetted by WordPress as preferred solution lacking this kind of features for years....

**Comment by brunocvcunha** [comment] 2017-02-01 04:13
+1

**Comment by lamdayap** [comment] 2017-02-19 22:58
3066467-t

**Comment by rmens** [comment] 2017-02-19 23:04
For anyone reading this and looking for a solution. I installed "NextScripts: Social Networks Auto-Poster" as gap-filler for Facebook. This plugin isn't as sleek as jetpack, but get's the job done.

Regarding: https://github.com/Automattic/jetpack/issues/1183#issuecomment-207316449. Outsourcing a basic function as getting an excerpt to the WordPress.com cloud is crazy. What was the developer thinking? 😂

**Comment by annezazu** [comment] 2017-04-25 22:37
3174542-t

**Comment by jeherve** [comment] 2017-05-05 18:10
Also reported here:
https://wordpress.org/support/topic/remove-just-xxx-more-words-with-a-filter/

**Comment by SiobhyB** [comment] 2017-08-29 20:00
624643-z

**Comment by rmens** [comment] 2017-12-28 17:32
Just received a glowing _Jetpack year in review_ e-mail talking about "social media scheduling".

How come all these new features are developed while basic functions like this are ignored?

**Comment by gravityrail** [comment] 2018-01-10 00:01
890187-z

**Comment by jeherve** [comment] 2018-01-10 19:23
We are not working on Publicize right now, but when we do this issue will be one of the ones at the top of our to-do list.

We'll comment on the issue once we make progress on this.

> Or even a way to remove publicize generating any excerpts at all for the mean time while a solution is being found?

Unfortunately no. Right now the only work-around is to manually specify a custom message as I explained here:
https://github.com/Automattic/jetpack/issues/1183#issuecomment-240988458

**Comment by sarahblackstock** [comment] 2018-02-12 17:59
Requested in mobile app support. internal ref: #260594-h

**Comment by jeherve** [comment] 2018-02-16 11:38
Also in 956516-zen

**Comment by bikedorkjon** [comment] 2018-02-22 20:03
Also in 969963-zen

**Comment by mzakariya** [comment] 2018-03-10 01:03
Reported in 998383-zen

**Comment by silentdragoon** [comment] 2018-04-25 13:58
Any ETA on this fix?

**Comment by jeherve** [comment] 2018-04-25 17:36
@silentdragoon Not at the moment, but we'll update this issue once we start working on Publicize again and make progress on this.

**Comment by juliasydnor** [comment] 2018-05-22 15:21
reported in 1174076-zen

**Comment by cezariuszmarek** [comment] 2018-05-27 17:40
Please fix it or at least let us translate the "xx more words" text.

**Comment by jeherve** [comment] 2018-05-28 06:51
@cezariuszmarek You should be able to translate the string in your own language here:
https://translate.wordpress.com/

Here is the (already translated) string in Polish, for example:
https://translate.wordpress.com/projects/wpcom/pl/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=41085&filters%5Btranslation_id%5D=1329456

If that translation does not appear for your site, could you contact us via [this contact form](https://jetpack.com/contact-support/?rel=support) and give us more details about your site, so we can investigate?

Thank you!

**Comment by juliasydnor** [comment] 2018-05-31 08:51
1187746-zen

**Comment by brezocordero** [comment] 2018-06-27 17:44
1226327-zen

**Comment by Uranbold** [comment] 2018-08-30 09:55
Come ooon! +1

**Comment by Uranbold** [comment] 2018-09-11 03:53
Guys any Developer Documentation on this section? I have looked over the publicize codes and can't find the correct section. I wanna help and fix this issue

**Comment by jeherve** [comment] 2018-09-11 08:59
@Uranbold The code behind this feature lives on WordPress.com, so you will not be able to help fixing the problem I am afraid.

We will update this issue once we start working on this.

**Comment by jeherve** [comment] 2018-09-11 13:30
Coming back to this, I believe this can now be closed. This issue is no longer relevant now that [we cannot use Publicize to publish posts to a personal Facebook Profile](https://en.blog.wordpress.com/2018/07/23/sharing-options-from-wordpress-com-to-facebook-are-changing/), where a custom excerpt was previously built by Publicize.

On Facebook Pages, such an excerpt is not built nor displayed anywhere:

<img width="516" alt="e0ecab2f776677bfca538a1624239345 _screenshot 2018-09-11 at 15 26 05" src="https://user-images.githubusercontent.com/426388/45363271-5f85cb00-b5d7-11e8-8508-85c09e21f844.png">

**Comment by jeherve** [comment] 2019-04-25 19:27
Reopening as automated excerpts are still generated in some scenarios.

**Comment by jrmain** [comment] 2019-10-23 10:34
In response to your officious little stalebot: speaking only for myself, I long ago grew weary of waiting for this problem to be fixed, and found workarounds. I'd be happy to go through the process of demonstrating the problem again if I thought there was any chance you'd be fixing it.

**Comment by samjhamdy** [comment] 2020-01-21 22:18
Requested again in #2648546-zen

**Comment by kraftbj** [comment] 2020-01-21 22:27
@jeherve 
> Reopening as automated excerpts are still generated in some scenarios.

To be clear, which scenarios are you referring to? I want to make sure we're parsing out if this issue is with our Publicize code or the situation where Facebook will scrape a site the first time it is shared, but not yet process the og information, resulting in unexpected results for the first share only.

**Comment by jeherve** [comment] 2020-01-22 08:47
> To be clear, which scenarios are you referring to?

Sure thing! Try the following:

- Connect to a Facebook Page. 
- Create a new post with the following content:
https://gist.github.com/jeherve/72c1f74ac724b994793967d0e66207dd
- Save your post as a draft.
- Add a custom excerpt.
- Save again just to be sure.
- Publish it. Do not set a custom Publicize message.
- The post will be published on your Facebook Page with an automated excerpt instead of the custom excerpt you created (that excerpt properly appears in OG tags, but that's not what we push to Facebook):

![image](https://user-images.githubusercontent.com/426388/72878871-103bc880-3cfc-11ea-8f7a-971028526a2d.png)

**Comment by rmens** [comment] 2020-01-22 21:22
I can confirm the scenario in https://github.com/Automattic/jetpack/issues/1183#issuecomment-577072297

**Comment by itsTallulah** [comment] 2020-03-04 20:39
Reported in #102395-zen - Generated excerpts are overriding the manually set Publicize excerpt in cases of posts with <ol> in their first few lines on one site, and doing it with no specific pattern on another.

**Comment by mewt** [comment] 2020-05-20 03:50
the issue still happening in my site.  We can't custome this message?

**Comment by jeherve** [comment] 2020-05-20 10:48
> We can't custome this message?

You should be able to customize the message that gets posted to Facebook by filling in the Publicize description field as explained here:
https://jetpack.com/support/publicize/#how-to-add-custom-excerpts

The bug reported here (an automated excerpt being used instead of the manual excerpt, when you don't use the custom Publicize description field) still exists.

**Comment by mewt** [comment] 2020-05-21 16:14
> > We can't custome this message?
> 
> You should be able to customize the message that gets posted to Facebook by filling in the Publicize description field as explained here:
> https://jetpack.com/support/publicize/#how-to-add-custom-excerpts
> 
> The bug reported here (an automated excerpt being used instead of the manual excerpt, when you don't use the custom Publicize description field) still exists.

Thanks for reply. I will give a try.

**Comment by mewt** [comment] 2020-05-26 05:26
I solved this problem using https://wordpress.org/plugins/always-use-jetpack-open-graph/ . The problem casue by double open graph (yoast , rank math , etc).

**Comment by ady001** [comment] 2020-10-04 15:53
The issue with the nagging text content must be fixed! I can't believe that after 6 years is not resolved. 
**How hard can it be to have a simple option in the Publicize settings to choose what it should share and/or a word count limit ?!**

**Comment by ady001** [comment] 2020-10-04 15:54
> 
> 
> I solved this problem using https://wordpress.org/plugins/always-use-jetpack-open-graph/ . The problem casue by double open graph (yoast , rank math , etc).

NO, it does not work! the long text is not related to the open graph data, Publicize gets the text directly from the article.

**Comment by rmens** [comment] 2020-10-04 18:35
Is it possible to bump the priority of this bug to ‘high’? It’s been 6 years and this ticket is still active with complaints.

**Comment by JustinFreid** [comment] 2021-01-29 21:21
Also bumping this to hopefully get a fix...

**Comment by LondonAppDev** [comment] 2021-04-12 08:39
This feature would be much appreciated.

**Comment by kimerlin81** [comment] 2021-08-31 13:22
Recently address in 4244513-zd-woothemes

**Comment by pablinos** [comment] 2021-09-10 17:29
I've just created D66698-code which should fix this problem.

@jeherve Is it easy for you to test?

**Comment by jeherve** [comment] 2021-09-14 12:20
> Is it easy for you to test?

Yeah, gave it a try just now, I think it works well.

As I mentioned on your patch, I think it would be nice to get rid of the "Continue reading" text that's appended to the excerpt, but maybe that's something that can be addressed later?

<img width="541" alt="Screenshot 2021-09-14 at 14 18 35" src="https://user-images.githubusercontent.com/426388/133256474-baf28bfe-efcd-45c0-81f6-2cea07d9266f.png">

**Comment by pablinos** [comment] 2021-09-23 10:14
Great, I've deployed the fix (r232174-wpcom) and it's fixed the issue for me.

I'm not getting the 'Continue reading' text that you have @jeherve, so I think this is probably be adding by the theme. I'll open a separate issue to address that. First thoughts are that maybe we shouldn't run the excerpt filters on the text, or we could detect a link, to the post being shared, towards the end of the excerpt and remove it.

**Closed by pablinos** 2021-09-23 10:14 UTC
Labels: [Type] Bug, Publicize, [Pri] Normal, [Type] Happiness Request
