### ISSUE TITLE
Simple Payments: payment value not passed to Paypal

### ISSUE THREAD

**Issue by sophiegyo** [Automattic/jetpack#14362] opened 2020-01-16 09:53 UTC
Looks like something's broken in the communication between Simple Payments and Paypal.
User first reported that they couldn't select more than 2 items of a Simple Payments item that had "Allow people to buy more than one item at a time." selected, then I observed the Paypal pop-up consistently disappearing when attempting to make a purchase.

#### Steps to reproduce the issue

1. Go to https://take2adventure.com/holiday-clubs/
2. Select a Simple Payments item to buy, click on Purchase
3. See the Paypal pop-up appear, then disappear.

#### What I expected
The Paypal pop-up should allow me to complete the transaction

#### What happened instead
Not that.

There are console errors indicating the amount due was not passed through to Paypal, so I guess the connection is timing out, which is why the pop-up disappears.

Tested in Chrome and Firefox, same result in both. Tested in incognito windows, in case of cookies, same result.
ETA: also tested both the block, and in the Classic Editor -  same result.
Replicated the error on another Simple site, and an AT BIZ site.  (side note: Simple Payments purchase button is broken due to the AMP plugin as well, I had to set my AT site AMP to "transitional" for the button to show).

**Screenshots**
Video showing the console errors and disappearing pop-up: https://d.pr/v/DBoixa
Recording of the AT site: https://d.pr/i/ZHQEJx

![simplepaymentsconsoleerrors](https://user-images.githubusercontent.com/36608681/72513697-a29c2200-384d-11ea-898a-f6e05a1710be.png)

The errors in the console (summarised list):

* ppxo_no_token_passed_to_payment 
* ppxo_unhandled_error 
* Uncaught Error: Error: No value passed to payment

I saved the log file of the console as well, for more detailed info:
[consoleerrors.log](https://github.com/Automattic/jetpack/files/4070442/consoleerrors.log)

**Comment by jeherve** [comment] 2020-01-16 11:47
I was able to reproduce in Chrome but not in Firefox.

I wonder if this may be caused by the upcoming x-domain cookie changes. It seems worth looking into.

Internal reference: pb6Nl-daR-p2#comment-92471

> Simple Payments purchase button is broken due to the AMP plugin as well, I had to set my AT site AMP to "transitional" for the button to show

Yes, the feature is not compatible with AMP yet: #9730

**Comment by sophiegyo** [comment] 2020-01-16 12:26
>I was able to reproduce in Chrome but not in Firefox. 

I realised I forgot to include my version info!
OS: Mac Mojave 10.14.6
Firefox: 72.0.1
Chrome: 79.0.3945.117

**Comment by artpi** [comment] 2020-01-16 13:19
Preliminary debugging says it is something on our servers and has nothing to do with cookies, iframes, etc.
PayPal API stopped giving sane responses and it may be connected to IMMENSE PayPal service availability problems we have been seeing in Neutron.

**Comment by artpi** [comment] 2020-01-16 18:45
We have investigated the logs and are in touch with PayPal to get this resolved as quickly as possible

**Comment by hacchism** [comment] 2020-01-17 22:05
Another report.

Page: https://emeraldmountainsanctuary.com/2020-my-creative-spark-workshop-payment/

**Comment by pauljacobson** [comment] 2020-01-19 10:18
I have another report here: 2641857-zen (discussion here: p1579295540011700-slack-C096PD42U )

**Comment by kosiew** [comment] 2020-01-20 09:51
Another report https://autopay.wordpress.com/2020/01/19/simple-payments-payment-did/

**Comment by n3f** [comment] 2020-01-20 20:10
While we were having PayPal API outage issues last week, it appears that many of these errors might be resolved by the users logging into their PayPal accounts to unrestrict their accounts. 
 See p1579543712021200-slack-C096PD42U for additional information.

**Comment by jeherve** [comment] 2020-01-24 12:45
Closing this now, as per the above ^

**Closed by jeherve** 2020-01-24 12:45 UTC
Labels: Simple Payments, [Pri] High, [Type] Bug, [Type] Happiness Request
