### ISSUE TITLE
Stats: Weekly/Monthly Stats showing single day in tooltip 

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/jetpack#18109] opened 2020-12-16 12:30 UTC
#### Steps to reproduce the issue

1. Go to Jetpack > Site Stats in wp-admin
2. Click on the 'Weeks' or 'Months' tabs
3. Hover over the stats for a week/month
4. See the tooltip from the 'Days' tab.

#### What I expected

The tooltip should indicate the relevant date range.

#### What happened instead

It indicates a specific day, which corresponds to the 'Days' tab.

**Screenshots**
![image](https://user-images.githubusercontent.com/1990037/102348897-6cee4480-3f9a-11eb-8d9c-817f67f6dd90.png)

Reported in https://wordpress.org/support/topic/tooltips-on-stats-pages-wrong/

**Comment by htdat** [comment] 2021-01-06 07:28
3622193-zen

**Comment by htdat** [comment] 2021-01-08 02:59
https://wordpress.org/support/topic/jetpack-statistics-bug/

**Comment by mzakariya** [comment] 2021-01-14 00:04
https://wordpress.org/support/topic/stats-bug-weekly-monthly-totals-not-showing/

**Comment by kbrown9** [comment] 2021-01-14 06:06
I'm working on a potential fix for this in D55329-code.

**Comment by kbrown9** [comment] 2021-01-18 20:41
This bug was caused by a problem with the script coming from WPCOM, and we've fixed the script in D55329-code. This bug should now be fixed, so I'm closing this issue.

Let us know if you encounter any problems!

**Closed by kbrown9** 2021-01-18 20:41 UTC
Labels: Stats, [Pri] Low, [Type] Bug
