### ISSUE TITLE
Subscription: Allow for importing of Subscribers/Followers from other services

### ISSUE THREAD

**Issue by jordesign** [Automattic/jetpack#17477] opened 2020-10-14 03:00 UTC
#### Is your feature request related to a problem? 
When moving to utilise Jetpack Subscriptions it can be useful to be able to import existing subscribers from another service - in my particular case Mailchimp

#### Describe the solution you'd like
It would be great to have an import tool that allowed you to import followers/subscribers from another service. This could be as simple as a CSV import.

#### Describe alternatives you've considered
Currently the option is to email existing subscribers on your own service - and ask them to visit your site to use the Jetpack Subscribe feature.

#### Additional context
I'm unaware of what the potential implications of doing this are in regard to SPAM legislation in different locations, and if subscribers would still need to confirm.

**Comment by jeherve** [comment] 2020-10-14 08:51
Closing as duplicate of #535. 

> I'm unaware of what the potential implications of doing this are in regard to SPAM legislation in different locations

Spam was indeed a concern we had discussed in the original issue.

**Closed by jeherve** 2020-10-14 08:51 UTC
Labels: Subscriptions

**Comment by jordesign** [comment] 2020-10-14 20:00
Thanks @jeherve

**Comment by jeherve** [comment] 2022-12-15 16:25
I wanted to close the loop on this by pointing out that this feature is now available. Here is how you can use it:
https://wordpress.com/support/launch-a-newsletter/import-subscribers-to-a-newsletter/
