### ISSUE TITLE
Sharing through Publicize, but CPT permalinks don't display correctly within Facebook.

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#3473] opened 2016-02-29 19:10 UTC
Hey guys. 

I've got a site running jetpack and woo commerce. I've got publicize enabled and set to post to a facebook page of mine. Within my WordPress site, I've got my permalinks structure set to custom, along with the permalink structure for the products custom post type which (which is the issue)

Here's what it looks like when posted to facebook:
![screen shot 2016-02-29 at 1 59 31 pm](https://cloud.githubusercontent.com/assets/214813/13405785/248e7e56-deee-11e5-93f3-b63504c127c7.png)

Product CPT permalinks
![image](https://cloud.githubusercontent.com/assets/214813/13405585/247a7e16-deed-11e5-8fe7-cbf5076e69f8.png)

I'm guessing Jetpack just isn't picking up on this CPT permalink structure. 

What I expected: CPT Permalinks to be accurately displayed on facebook

This isn't really directed related, but here's the custom permalink structure for my post, but I'm not having this issue with posts:
https://cloudup.com/cdCC-cGmIWn

@samhotchkiss @zinigor @dereksmart

**Comment by jeherve** [comment] 2016-02-29 20:44
Closing as duplicate of https://github.com/Automattic/io/issues/429
(see comments at the bottom of a more recent update on that issue).

Until this is fixed, you can get pretty permalinks back in Publicize by activating the WP.me Shortlinks module (no, it won't add WP.me shortlinks to Publicize).

**Comment by jeffgolenski** [comment] 2016-02-29 21:06
@jeherve thanks for the quick response! Are any additional steps needed or should that just take care of things? haven't much experience with our shortlinks.

**Comment by jeherve** [comment] 2016-02-29 21:07
That's all you need to do! It won't change things for the posts that were already publicized, but you'll get full permalinks for your future Publicized posts.

**Closed** 2016-03-14 09:35 UTC
Labels: Publicize, [Team]  I/O, [Type] Bug, [Type] Duplicate

**Comment by jeherve** [comment] 2016-05-30 07:32
The problem should now be fixed!
