### ISSUE TITLE
Secondary user unable to link to wp.com on first try. 

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#7410] opened 2017-06-30 11:46 UTC
As the title suggests, it fails on the first try being presented with a "Return to your site" message, but succeeds on the second try.  

I was only able to reproduce it in current beta.  5.0 works well. 

This happens for any secondary user at any user role.  

![secondary-user-fail](https://user-images.githubusercontent.com/7129409/27734273-1ba14c3e-5d68-11e7-83b4-5e90d16a30cc.gif)

**Comment by zinigor** [comment] 2017-06-30 20:48
@dereksmart has tried bisecting and it turned out that ef08131 might have introduced the problem. But I can't connect a secondary user on my installation even when I revert that commit.

**Comment by roccotripaldi** [comment] 2017-07-03 16:57
I do not think this is a Jetpack 5.1 issue. I'm able to reproduce in 5.0 also.

I'm tracing this issue to Calypso:
- when a user attempting to link their account lands in calypso, we issue a request to the site
- the request comes back because the site is already connected
- we add that site to their site list even though they are not connected
- we end up in the weird state where we cannot connect

cc: @sirreal for verification

**Comment by sirreal** [comment] 2017-07-03 21:39
Looks like this might be the same as https://github.com/Automattic/wp-calypso/issues/15666

> cc: @sirreal for verification

I'll check this tomorrow.

**Comment by kristarella** [comment] 2017-07-04 08:30
I have a report of this from a user, and I can replicate on my own primary site, and a test site. I am unable to connect a second user on any number of attempts:

Steps to replicate:
1. Other user clicks "Link to WordPress.com" from Jetpack > Settings
2. Successfully logs in to WordPress.com and gets "return to site" button
3. Returns to site and gets same "You are not connected to WordPress.com. Link to WordPress.com" message.

I and user have tested repeatedly and cannot connect. There is no record in RC that user was connected to the site. No errors in Jetpack Debug for site.

**Comment by zinigor** [comment] 2017-07-04 09:49
cc @roccotripaldi 
I'm closing this issue because it needs to be fixed on WordPress.com and doesn't need Jetpack code modification. Feel free to reopen if needed.

**Closed by zinigor** 2017-07-04 09:49 UTC
Labels: General, [Pri] BLOCKER, [Type] Bug
