### ISSUE TITLE
Publicize: modals get cropped/hidden on mobile

### ISSUE THREAD

**Issue by markjaquith** [Automattic/jetpack#3088] opened 2015-12-01 17:28 UTC

**Comment by jeherve** [comment] 2015-12-01 17:41
@markjaquith Could you post a screenshot? I tried to reproduce on one of my sites, but the modals appear to be displayed properly:

![2015-12-01 17 39 19](https://cloud.githubusercontent.com/assets/426388/11508819/fd85c4d8-985a-11e5-9707-b43e06ad6b74.png)

This was on an Android phone running 5.1.1, in Chrome, and when clicking on the Widgets module title under Jetpack > Settings.

**Comment by markjaquith** [comment] 2015-12-01 19:03
http://i.imgur.com/ey6NbJC.png

Twitter connect success dialog. Cannot access the checkbox to share the account. iPhone 6S Plus.

**Comment by jeherve** [comment] 2015-12-01 19:05
Thanks, that helps!

**Comment by jeherve** [comment] 2015-12-02 13:23
Somewhat related: #2709

The whole sharing settings screen would benefit from a redesign to be responsive and accessible.

Until that happens, the only way to manage Sharing and Publicize on mobile is via Calypso:
https://wordpress.com/sharing

**Comment by jeherve** [comment] 2017-01-13 14:50
Closing this for now since we're now developing a new Publicize settings screen that will be responsive and live under Jetpack > Settings.

**Closed by jeherve** 2017-01-13 14:50 UTC
Labels: Publicize, [Team]  I/O, [Type] Bug
