### ISSUE TITLE
Social Media Icons not shown on PC in Chrome

### ISSUE THREAD

**Issue by annezazuu** [Automattic/jetpack#4159] opened 2016-06-19 18:38 UTC
In 2695030-t, a user found that they cannot view the Social Media Icons on a PC in Chrome whereas on a Mac in Chrome they show up without a problem:

**PC  + Chrome**
![pcchrome 1](https://cloud.githubusercontent.com/assets/11266471/16179146/a31313b2-361a-11e6-822a-e12d34f7feb6.png)

**Mac + Chrome**

<img width="362" alt="screen shot 2016-06-17 at 2 18 37 pm" src="https://cloud.githubusercontent.com/assets/11266471/16179141/953f01a6-361a-11e6-9897-017c29b13ef6.png">

I'm not entirely sure what is causing this but it appears to be specific to PCs.

**Comment by jeherve** [comment] 2016-06-20 07:26
I can't seem to reproduce in IE11 or Chrome on a PC. I'll ask the site owner for more info.

**Comment by annezazuu** [comment] 2016-06-21 15:43
Using the current update of Google Chrome - Version 51.0.2704.103 and Windows 10 Home, Version 1511 @jeherve

**Comment by ebinnion** [comment] 2016-06-21 15:46
In the PC + Chrome screenshot, I don't even see the "Hey Social!!!" widget header. Are we sure that the widget was set when the user took the screenshot?

**Comment by jeherve** [comment] 2016-11-15 15:19
Closing for now, since none of us seem to be able to reproduce.

**Closed by jeherve** 2016-11-15 15:19 UTC
Labels: Extra Sidebar Widgets, [Status] Needs Author Reply, [Type] Bug
