### ISSUE TITLE
Settings UI Dev Mode: missing some offline module toggles

### ISSUE THREAD

**Issue by wunc** [Automattic/jetpack#7047] opened 2017-04-24 17:36 UTC
Some offline module toggles that were previously available on the settings page (Beautiful Math, Extra Sidebar Widgets, Custom CSS, Widget Visibility, and etc.) while in development mode are now missing from the UI in v4.8.

Issue #6991 suggested using the `/wp-admin/admin.php?page=jetpack_modules` interface, but there's no link to it on the current settings page that I can see.

#### Steps to reproduce the issue

- Enable development mode: `define( 'JETPACK_DEV_DEBUG', true);`
- Install and activate Jetpack 4.8.2
- Visit the Jetpack > Settings page

#### What I expected

See toggles for the above-mentioned modules.

#### What happened instead

No exposed toggles for the above-mentioned modules.

**Comment by jeherve** [comment] 2017-04-24 20:32
Closing as duplicate of #6861

**Closed by jeherve** 2017-04-24 20:32 UTC
