### ISSUE TITLE
Enhancement:

### ISSUE THREAD

**Issue by gabrieino2** [Automattic/jetpack#25664] opened 2022-08-16 22:06 UTC
### Impacted plugin

Jetpack

### What

Adjustable spacing for tiled gallery block 

### How

Right now the spacing between images in the tiled gallery block is set.  Also, it seems like the width is a little less than the native image size and gallery blocks in Wordpress.  It would be nice if you could adjust the spacing between each image in the tiled gallery blocks and the spacing between the tiled gallery and the blocks on either side.

**Comment by jeherve** [comment] 2022-08-17 06:51
Closing as duplicate of #9548.

**Closed as completed by jeherve** 2022-08-17 06:51 UTC
Labels: [Closed] Duplicate, [Feature] Tiled Gallery, [Pri] Low, [Block] Tiled Gallery, [Plugin] Jetpack
