### ISSUE TITLE
Instant Search: Default search results when JavaScript is disabled

### ISSUE THREAD

**Issue by tiagonoronha** [Automattic/jetpack#19546] opened 2021-04-15 10:28 UTC
#### Steps to reproduce the issue

1. Disable JavaScript in the browser
2. Search for something on the site
3. You should get a "No results found" message

#### What I expected

I expected to still be able to get search results with JavaScript disabled. At the very least instead of "No results found" it should display a "Search requires JavaScript" type of message.

Default search results are bypassed here: https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/modules/search/class-jetpack-instant-search.php#L266-L291. 

**Screenshots**

![search](https://user-images.githubusercontent.com/1177726/114855050-669f9600-9ddd-11eb-84cd-2b69deef2b98.png)

**Comment by mdrovdahl** [comment] 2021-08-23 18:36
Dupe of #14885

**Closed by mdrovdahl** 2021-08-23 18:36 UTC
Labels: [Type] Bug, Search, Instant Search
