### ISSUE TITLE
Absolutely a step backwards for Jetpack UI in the latest update.

### ISSUE THREAD

**Issue by robertdall** [Automattic/jetpack#5121] opened 2016-09-07 19:21 UTC
There was nothing wrong with the 4.0 install UI. One list of all the modules that you could see at a glance they all had their own icons it was easy and efficient to look at what was installed and what wasn't. Sure I could check the search icon with isn't remotely user friendly even intuitive that you can click the search icon to see a list. 

![jetpack-settings](https://cloud.githubusercontent.com/assets/1909677/18324806/39e0b88c-74f3-11e6-83c8-f56a9ed663d1.png)

There is too much padding on the list. You have scroll to see what was is installed and absolutely no more bulk options. That is also completely horrible and a huge step backwards for Jetpack. You guys made major gains over the years with me and others improving how your plugin works making it easier and faster to check setting and move on and this just throws that all away.

![jetpack-settings-new](https://cloud.githubusercontent.com/assets/1909677/18325019/39203e9e-74f4-11e6-9678-c6eecf21d488.png)

For 99% of the install I create, 99% of the wordpress users I work, talk with, help, with want to see at a glance what the settings are. Most people are the set and forget it type and this completely new UI increase time lost to finding the setting. With the categories on the side you could segment the list to what you wanted to see. But This top menu UI is just horribly bad, space consuming time consuming, error prone (did I leave a module on another screen I forgot to check bad) 

I am sorry if I sound rude or ungrateful for the massive amount of work that goes into this plugin. But this truly a step backwards for usability and efficiency and makes me never want to install jetpack on another install.

Signed a very annoyed Robert Dall

**Comment by jeherve** [comment] 2016-09-07 19:27
Closing as duplicate of #4534.

**Closed by jeherve** 2016-09-07 19:27 UTC

**Comment by robertdall** [comment] 2016-09-07 19:29
Come on @jeherve This is not a duplicate of just the bulk option. That is clearly a bad decision. But the entire UI took a huge back step with this release.

**Comment by jeherve** [comment] 2016-09-07 19:33
I think we should be able to address your concerns when introducing bulk editing, as the bulk interface will need to be a bit different from the existing one.

Feel free to share your ideas on that other issue, as the new interface is being built!

**Comment by samhotchkiss** [comment] 2016-09-07 19:33
Robert-- We really do appreciate your feedback here, and will consider it as we iterate.  Many hours, discussions, user interviews and user tests were put into the current direction, and we do fully believe in it, but we will be iterating on it.

In particular, the concept of bulk settings and the ability to apply a configuration set from one site to another (duplicating all the settings you made previously on another site) are high on our priority list, and we'll be continuing to work hard on improving our user experience.

I'd encourage you to [join in our beta program](https://jetpack.com/beta/), where you're able to give feedback throughout our development process.  We highly value feedback from our beta testers at all stages of development, and would welcome you to help us make the best Jetpack possible.

Thank you!
