### ISSUE TITLE
Automatic Posting of Posts To Socialmedia Also Posts Woocommerce Products!

### ISSUE THREAD

**Issue by mikebronner** [Automattic/jetpack#9421] opened 2018-04-26 02:12 UTC
#### Steps to reproduce the issue
- Set up automattic posting to social media in Jetpack settings.
- Add new Woocommerce products.

#### What I expected
- Only actual posts, not products, would be cross-posted.

#### What happened instead
- May thousand products got pushed out to social media, alienating many of our users.

**Comment by jeherve** [comment] 2018-04-26 15:15
Closing as duplicate of #7316

@mikebronner That is in fact the expected behaviour. You can deactivate this option thanks to the code snippet in #7316

**Closed by jeherve** 2018-04-26 15:15 UTC
Labels: Publicize, [Type] Duplicate
