### ISSUE TITLE
Admin Page: notifications are broken.

### ISSUE THREAD

**Issue by zinigor** [Automattic/jetpack#4910] opened 2016-08-23 08:39 UTC
#### Steps to reproduce the issue
- Load the admin page
- Try to open the notifications sidebar.

#### What I expected
- The notification sidebar to open.

#### What happened instead
- It doesn't open
- I get errors in the console:
![notes-bug](https://cloud.githubusercontent.com/assets/374293/17885506/941197de-692e-11e6-9729-e5dd52461bf1.png)

#### Bisect
I have tried bisecting and it pins the problem down to 4eb279d, which is very weird. I don't really see anything in that commit that might have polluted the lodash global variable. cc @dmsnell , you probably know what could have caused this.

**Comment by jeherve** [comment] 2016-08-23 09:23
I can't seem to be able to reproduce on my end, when running the latest `master-stable`.

**Comment by oskosk** [comment] 2016-08-23 12:11
You're right. that commit and PR were the ones introducing that error into Jetpack but it was due to dops-components' ExternalLink which was polluting the underscore global. It was fixed before this branch got merged. you may be running an old version of dops-components. Closing as it was fixed

**Closed by oskosk** 2016-08-23 12:11 UTC
Labels: Admin Page, [Type] Bug
