### ISSUE TITLE
Edge Browser and slowness in /wp-admin/

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#7860] opened 2017-09-25 19:47 UTC
I'll let the user explain it, as it's pretty clear:

> When using the Edge Browser to edit my site, the wp-admin pages often became 
unavailable.
>I contacted Siteground support and they traced the error to the jetpack add in:
>
>'I found out the cause of the issue. 
>The Jetpack plugin creates the issue. It appears that some code inside the file 
>'class.jetpack-json-api-plugins-endpoint.php' is the real cause. 
>This file is located in the Jetpack's folder, then the sub-folder called 
>'jetpack'. 
>
>The problematic line of code is located on 214th line, inside the 
>'class.jetpack-json-api-plugins-endpoint.php' file.
>
>$dom_doc->loadHTML( mb_convert_encoding( $action_link, 'HTML-ENTITIES', 'UTF-8' 
>) );

What additional information (if any) would be helpful here?

700743-zen

**Comment by zinigor** [comment] 2017-09-27 04:24
Oh wow, how could they have tracked a browser issue to [a line of code in the JSON API](https://github.com/Automattic/jetpack/blob/master/json-endpoints/jetpack/class.jetpack-json-api-plugins-endpoint.php#L214)?

I'd suggest the user to try a different browser, just to make sure it's not being reproduced. If the issue is really what Siteground say here, it should be slow in all browsers.

It would be really nice to have a look at the site and see the requests and responses that we send to that endpoint. But that would require at least admin access.

**Comment by richardmtl** [comment] 2017-09-27 14:24
I've asked the user for admin credentials and to test in another browser.

**Comment by jeherve** [comment] 2017-11-03 15:10
Closing since we don't have any more info for now.

**Closed by jeherve** 2017-11-03 15:10 UTC
Labels: Performance, WPCOM API, [Pri] High, [Status] Needs Author Reply, [Type] Bug
