### ISSUE TITLE
Widget Visibility: Add Device Filters as an option (i.e., mobile/desktop)

### ISSUE THREAD

**Issue by mzakariya** [Automattic/jetpack#7677] opened 2017-08-23 16:53 UTC
#### Steps to reproduce the issue
- Use Widget Visibility in Jetpack

#### What I expected
- Ability to filter widget visibility based on Mobile v. Desktop v. Tablet users

#### What happened instead
- Feature request; option doesn't exist

`644194-zen`

**Comment by jeherve** [comment] 2017-09-08 11:05
Closing as duplicate of #1140

**Closed by jeherve** 2017-09-08 11:05 UTC
Labels: Widget Visibility, [Type] Feature
