### ISSUE TITLE
JavaScript error when interacting with Safe Mode

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#5834] opened 2016-12-08 21:23 UTC
With an IDC in progress and the Safe Mode prompt appears, @BandonRandon reports the following error:

```
TypeError: analytics.tracks is undefined[Learn More]  idc-notice.js:220:4
    trackAndBumpMCStats https:///wp-content/plugins/jetpack/_inc/idc-notice.js:220:4
    confirmSafeMode https:///wp-content/plugins/jetpack/_inc/idc-notice.js:94:3
    n.event.dispatch https:///wp-admin/load-scripts.php:3:12392
    n.event.add/r.handle https:///wp-admin/load-scripts.php:3:9156
```

This is preventing the JS from firing when attempting to confirm Safe Mode and disables the rest of the Settings page from working, including the Disconnect link.

**Comment by BandonRandon** [comment] 2016-12-08 21:33
This is also happening when clicking "Fix Jetpack's Connection".

 To confirm a bit regarding the settings pages not loading, pushState is changing the Jetpack Admin Page. Yet,  the settings themselves do not load. `https:///wp-admin/admin.php?page=jetpack#/settings`

Clicking on Site Stats returns
>   unknown_token: It looks like your Jetpack connection is broken. Try disconnecting from WordPress.com then reconnecting. 

Let me know if there are additional details that would be helpful. Was able to replicate on both Firefox and Chromium on Linux Mint 18.1 Beta.

**Comment by jeherve** [comment] 2024-12-18 15:42
I cannot seem to be able to reproduce this anymore. Since the modal was refactored, it must be fixed by now.

**Closed by jeherve** 2024-12-18 15:42 UTC
Labels: [Type] Bug, IDC
