### ISSUE TITLE
Performance: spin.js is 10K of unminified JS and it doesn't seem to be used anywhere

### ISSUE THREAD

**Issue by alshakero** [Automattic/jetpack#15543] opened 2020-04-24 10:48 UTC
Hi!

This might be a super quick performance low-hanging fruit.

#### Steps to reproduce the issue

1. Have your Chrome DevTools on the network tab.
2. Create a new post on any WP.com site (go to https://wordpress.com/block-editor/post/ and pick a site). You should see network requests taking place. 
3. Press <kbd>option</kbd> + <kbd>command</kbd> + <kbd>F</kbd>. This allows you to search the body of every network response. And search for `initVML` (just an arbitrary string from spin.js source). You'll find the file that has it. And you'll see spin.js unminified source. 
4. Search again for `spinner` using the same method. And you won't see any JS file using this string (you'll only see CSS files - unrelated). This isn't conclusive as some other page might be using the spinner, but it's unlikely since [we have our own spinner now](https://github.com/Automattic/jetpack/tree/master/_inc/client/components/spinner) and [a GitHub search for `spinner`](https://github.com/Automattic/jetpack/search?q=spinner&unscoped_q=spinner) doesn't yield any occurrence for spin.js function, except within the source of spin.js itself. And the last time [the file was touched is 7 years ago](https://github.com/Automattic/jetpack/blob/master/_inc/spin.js). It's on v1.3 and spin.js has v4.1.0 released.

Thanks a lot!

/cc @sgomes

**Comment by jeherve** [comment] 2020-04-24 11:00
Closing as duplicate of #13555.

> it doesn't seem to be used anywhere

We still use it for 2 things: Carousel and the Comics post type. We've stopped using it everywhere else.

**Closed by jeherve** 2020-04-24 11:00 UTC
Labels: General, Performance, [Pri] Low, [Type] Duplicate
