### ISSUE TITLE
Display Posts Widget shows Sharing buttons if "show excerpt" option is set

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#3290] opened 2016-01-18 17:37 UTC
1. Delete all transients from your site.
2. Make sure Sharing is active, and that there are buttons to display. 
3. Add a Display Posts widget to any sidebar
4. Use your own domain as the Blog URL
5. Make sure "show excerpts" is checked
6. See that each post displayed in the widget has sharing buttons.

Expected: no sharing buttons should appear in the widget at all. 

Note: does not happen when querying posts from a wordpress.com site

**Comment by dereksmart** [comment] 2016-01-18 17:49
This is only happening for some sites, and persists even if Sharing is inactive.  

For example, try pulling from dereksmart.wpsandbox.me or csonnek.wpsandbox.me

**Comment by dereksmart** [comment] 2016-01-18 17:57
this only happens with #3207

**Comment by bisko** [comment] 2016-01-18 19:22
As this was recently in my domain I will check it out :)

**Comment by dereksmart** [comment] 2016-01-18 19:45
Update:  I can only reproduce this when the *remote* site has BOTH of these options checked 

https://cloudup.com/cVDzFzOI8_A

**Comment by bisko** [comment] 2016-01-18 20:47
It seems that Sharedaddy adds the share buttons to the excerpts and that is the content that is returned by the remote site. 

It is reproduced on both `master` and #3207 as the code that runs them is the same - just render what is returned in the excerpt.

**Comment by jeherve** [comment] 2016-01-19 11:22
I'd be tempted to move this to the 3.9 milestone We'll want to avoid adding so many new elements to all the sites that use the Display Posts widget.

**Comment by jeherve** [comment] 2016-01-19 11:51
@bisko let me know this is broken in the current widget as well. Moving this back to 3.9.1.

**Comment by zinigor** [comment] 2016-04-04 07:04
@jeherve @dereksmart what do you think of an approach similar to #3612? Having an action do the code insertion looks far better to me than using a filter.

**Comment by jeherve** [comment] 2016-04-04 15:21
@zinigor This could work, yes.

**Comment by oskosk** [comment] 2018-03-21 13:38
I couldn't reproduce either. Tried every piece of tip left here (sites and settings details). But testin this was useful to come up with #9107. Closing this one. @dereksmart please reopen if you can still reproduce

**Closed by oskosk** 2018-03-21 13:38 UTC
Labels: Extra Sidebar Widgets, FixTheFlows, [Pri] Low, [Type] Bug
