### ISSUE TITLE
Tiled Gallery Block: Tiled Mosaic display uses image filepath with height value set as width

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/jetpack#20063] opened 2021-06-11 17:30 UTC
#### Steps to reproduce the issue

1. Create a Tiled Gallery block with Tiled Mosaic style selected
2. Publish your post. You may see exceptionally blurry images in the mosaic thumbnails.
3. Right-click and 'Copy Image Location' to get the image path for the mosaic display.

#### What I expected

Images should not use the height value as the width

#### What happened instead

Images are distorted as the height attribute is being used for the width:

https://sandalwood.mystagingwebsite.com/2021/06/11/tiled-gallery/

**Screenshots**

Example:

<img width="715" alt="Screenshot on 2021-06-11 at 13-22-51" src="https://user-images.githubusercontent.com/45246438/121726197-3eb87000-cab8-11eb-9579-d3f28122222f.png">

**Comment by ivan-ottinger** [comment] 2021-11-03 09:10
Hello @bobmatyas 👋🏼 

thanks or the report.

I am having trouble reproducing the issue. Would it be possible to share a screenshot of your Tiled Gallery block settings - or maybe even better - a screen recording showing how the issue can be reproduced? 

When testing images of specific sizes on my end, the width of the image is used. For example:

* [image that is 968 px wide and 1134 px high](https://user-images.githubusercontent.com/25105483/140032705-85b3cb3c-f8e8-40c2-aba0-fd6f67608396.png) has the following link: `/wp-content/uploads/2021/11/Markup-on-2021-11-03-at-091551-874x1024.png?strip=info&w=968&ssl=1`
* [image that is 1670 px wide and 722 px high](https://user-images.githubusercontent.com/25105483/140032722-25213fb5-9915-4902-9d9c-881e112998ff.png) has the following link: `/wp-content/uploads/2021/11/Markup-on-2021-11-03-at-091604-1024x443.png?strip=info&w=1670&ssl=1`

I think the issue could be related to the way the images are displayed in [your example](https://sandalwood.mystagingwebsite.com/2021/06/11/tiled-gallery/) where they are stacked one on top of another; but I couldn't get to that view and the images always arranged in a fashion similar to this:

![Markup on 2021-11-03 at 10:07:34](https://user-images.githubusercontent.com/25105483/140033783-739b1c31-a913-42e0-9c72-bfcfc60aff82.png)

**Comment by bobmatyas** [comment] 2021-11-04 12:13
@ivan-ottinger I'm wondering if this was actually fixed by another code change. I created this issue based on 6448-gh-Automattic/jpop-issues. However, when looking at the example in that original issue, it appears to have been resolved.

**Comment by ivan-ottinger** [comment] 2021-11-04 12:31
Thanks for sharing @bobmatyas! 👍🏼 

Yeah, it looks like the issue has been fixed by another code change.
→ I am closing this issue.

We can still reopen in case it comes up again.

**Closed by ivan-ottinger** 2021-11-04 12:31 UTC
Labels: [Type] Bug, Tiled Gallery, [Status] Needs Author Reply, [Type] Happiness Request, [Block] Tiled Gallery
