### ISSUE TITLE
AI Assistant: non-English text output

### ISSUE THREAD

**Issue by jerrysarcastic** [Automattic/jetpack#33256] opened 2023-09-21 19:48 UTC
### Impacted plugin

Jetpack

### Quick summary

When using AI Assistant, sometime output is in a different language.  This happens randomly and can be difficult to replicate but can be spotted in the screencast (from my test site) here:

https://github.com/Automattic/jetpack/assets/1967448/d46c3936-75c9-4d2a-8dbf-238d4143c48d

### Steps to reproduce

1. open post or page and edit text in an existing paragraph block.
2. Invoke AI assistant and choose 'Expand' 'Summarize' 'Make longer' or 'Make shorter'
3. Check output

### A clear and concise description of what you expected to happen.

My text is in English, and I would expect the AI output to be in English as well.

### What actually happened

Output is mostly in English, but sometimes (randomly it seems) output is in a different language instead.  Spanish in my case.

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

This has been reported by the owner of a wpcom simple site in https://wordpress.com/forums/topic/ai-assistant-writing-in-random-languages/ and in my subsequent testing I was able to replicate on my WOA site (but not on a simple site) so this may be difficult to replicate.

Site owner reports they see many different languages randomly and confirms their account and site have always been set to English.  My test site and account are also set to EN.  I spotted output in Spanish but the site owner above reports also seeing German, French, and other languages they do not recognize.

**Comment by cuemarie** [comment] 2023-09-21 22:27
📌 REPRODUCTION RESULTS
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
Wasn't able to replicate this. Ran a bunch of prompts on the AI Assistant on an AT site, asked it to rewrite multiple times, shorter and longer, etc. 

📌 Message to Devs
CC @jeherve for awareness- any thoughts?

**Comment by supernovia** [comment] 2023-09-22 23:56
Another case here: https://wordpress.com/forums/topic/ai-assistant-writing-in-random-languages/?view=all#post-3991142

**Comment by supernovia** [comment] 2023-09-22 23:57
And a third case here: https://wordpress.com/forums/topic/jetpack-ai/page/3/?view=all#post-3990948

**Comment by formosattic** [comment] 2023-09-23 04:03
I was able to reproduce the issue but inconsistently, by testing either editing an existing text or using the AI block to create new content.  I use jurassic ninja for testing.

The issue also happens when changing the Tone, and even when Translating to English (from English).

As a temporary fix, you can try using the Translate option in the AI Assistant to get the content back in the preferred language. The option is available in the Paragraph block settings, or the AI block settings.

| Paragraph block settings | AI block settings |
| ------------- | ------------- |
| ![image](https://github.com/Automattic/jetpack/assets/15944096/3a4cedf2-cca9-4c6e-8fa9-2e1e2fc472a9)  | ![image](https://github.com/Automattic/jetpack/assets/15944096/a4491f8e-6a26-405a-9787-49bdce264b10)  |







+1 7073864-zd-a8c

**Comment by pehaa** [comment] 2023-09-25 05:29
Another case here 6847078-zd-a8c

**Comment by alinclamba** [comment] 2023-09-27 13:09
Another one: 7060687-zd-a8c

**Comment by dhasilva** [comment] 2023-09-27 15:07
https://wordpress.com/forums/topic/ai-assistant-writing-in-random-languages/#post-3991223

A tentative fix (https://github.com/Automattic/jetpack/pull/33211) was merged and released for WPCOM at the next daily deploy, so it should be live from around September 22 onwards.
The comment above says that "Hi there. I have noticed that as of today, the ai is working fine again. I hope taht it will stay that way!", so it seems to be working for this user.

For Jetpack users it will be included in the next Jetpack release, which seems to be scheduled for 2023-10-10.
If any user reports this problem after September 23, please check if they are on WPCOM or Jetpack, as this is expected to happen to Jetpack users.

**Comment by formosattic** [comment] 2023-10-14 05:11
As of October 12, 2023, [Jetpack 12.7](https://jetpack.com/blog/jetpack-12-7-ai-excerpts-newsletter-tiers-improved-social-sharing-and-more/) is live. 

A Jetpack user (see ref: https://github.com/Automattic/jetpack/issues/33256#issuecomment-1732202804) confirmed the issue is no longer happening.

**Comment by cuemarie** [comment] 2023-10-17 19:13
Thanks for the update @formosattic !

📌 ACTIONS
- Closing as fixed by https://github.com/Automattic/jetpack/pull/33211

**Closed as completed by cuemarie** 2023-10-17 19:13 UTC
Labels: Bug, [Pri] Normal, [Focus] Blocks, Customer Report [LEGACY], [Plugin] Jetpack, Triaged, [Platform] Simple, [Platform] Atomic, [Block] AI Assistant
