### ISSUE TITLE
Paid Content block: Add option to log in to view content for logged out paying subscribers

### ISSUE THREAD

**Issue by filipanoscampos** [Automattic/jetpack#32061] opened 2023-07-25 14:41 UTC
### Impacted plugin

Jetpack

### What

When a paying subscriber is logged out of WordPress.com and tried to view content inside a Paid Content block, they only see the option to subscribe. This is confusing to users.

**Comment by cuemarie** [comment] 2023-07-25 17:38
Closing as duplicate of https://github.com/Automattic/jetpack/issues/32062

**Closed as not planned by cuemarie** 2023-07-25 17:38 UTC
Labels: [Closed] Duplicate, [Feature] Subscriptions, New Feature, Earn, [Plugin] Jetpack
