### ISSUE TITLE
Activity log: Retain logs for a minimum of 6 months

### ISSUE THREAD

**Issue by dartiss** [Automattic/jetpack#8876] opened 2018-02-19 15:01 UTC
Allow retention of activity logs for at least 6 months - this is a requirement of Enterprise users (specifically, in this case, at the request of a WordPress.com VIP users who is currently using the activity log).

**Comment by jeherve** [comment] 2018-02-19 21:49
Closing as duplicate of 1550-gh-jpop-issues

**Closed by jeherve** 2018-02-19 21:49 UTC
Labels: Activity Log
