### ISSUE TITLE
Jetpack Prevents Menu Items from being added

### ISSUE THREAD

**Issue by wdac-davy** [Automattic/jetpack#5193] opened 2016-09-23 17:25 UTC
Topic was closed previously so here is the previous issue with my updates posted. Previous issue link: https://github.com/Automattic/jetpack/issues/5033

**Original Post:**

Jetpack version: Version 3.9.2
WordPress version: 4.3.2

When Jetpack was turned on and I went to Appearance > Menus, checked a menu item to add, and clicked "Add to menu", the icon would spin and spin and not do anything. I left it running for about 10 minutes and it still kept spinning.

I checked the console and got an internal server error for the file: /wp-admin/admin-ajax.php as soon as I clicked "Add to menu".

Deactivating Jetpack and trying to add a menu item works successfully without issue.

**Update**
Updated to latest versions (wp: 4.6.1, Jetpack: 4.3.1)

No change with adding menus, but the errors in console have changed slightly.

Console errors are as follows: 

```
(index):481 WebSocket connection to 'wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data' failed: Error during WebSocket handshake: Unexpected response code: 403pinghubAdd @ (index):481pinghubConnect @ (index):450handlePinghubMessage @ (index):432receiveMessage @ (index):170(anonymous function) @ (index):249dispatch @ ??/wp-includes/js/jquery/jquery.js,/wp-content/js/postmessage.js?m=1377267974j:4r.handle @ ??/wp-includes/js/jquery/jquery.js,/wp-content/js/postmessage.js?m=1377267974j:4
load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,utils,jquery-ui-widget,jquery…:4 POST https://mydomain.com/wp-admin/admin-ajax.php 500 (Internal Server Error)send @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,utils,jquery-ui-widget,jquery…:4ajax @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,utils,jquery-ui-widget,jquery…:4n.(anonymous function) @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,utils,jquery-ui-widget,jquery…:4addItemToMenu @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,utils,jquery-ui-widget,jquery…:83(anonymous function) @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,utils,jquery-ui-widget,jquery…:83each @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,utils,jquery-ui-widget,jquery…:2each @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,utils,jquery-ui-widget,jquery…:2addSelectedToMenu @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,utils,jquery-ui-widget,jquery…:83(anonymous function) @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,utils,jquery-ui-widget,jquery…:83dispatch @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,utils,jquery-ui-widget,jquery…:3r.handle @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,utils,jquery-ui-widget,jquery…:3
(index):481 WebSocket connection to 'wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data' failed: Error during WebSocket handshake: Unexpected response code: 403pinghubAdd @ (index):481pinghubConnect @ (index):450handlePinghubMessage @ (index):432receiveMessage @ (index):170(anonymous function) @ (index):249dispatch @ ??/wp-includes/js/jquery/jquery.js,/wp-content/js/postmessage.js?m=1377267974j:4r.handle @ ??/wp-includes/js/jquery/jquery.js,/wp-content/js/postmessage.js?m=1377267974j:4
```

**Comment by jeherve** [comment] 2016-09-26 09:34
Closing as duplicate of #5033

**Closed by jeherve** 2016-09-26 09:34 UTC
