### ISSUE TITLE
JITM to enable Photon CDN disappears and settings change not visible until reload

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#12891] opened 2019-06-28 04:03 UTC
#### Steps to reproduce the issue

1. Go to the Jetpack dashboard, on a site without the asset CDN enabled
2. See the prompt to activate Photon CDN
3. Click "Activate"
4. No user feedback, prompt disappears. Browsing to settings does not show Photon CDN is enabled until I reload the page.

#### What I expected
- Feedback telling me Photon CDN is enabled
- Setting to be enabled when I browse to the Settings->Performance tab

#### What happened instead
- Weird loading of next JITM
- Setting not enabled until I reloaded the page

**Video**

https://cloudup.com/ccV0oqdQ8L4

**Comment by jeherve** [comment] 2019-07-03 10:54
> Feedback telling me Photon CDN is enabled

This is odd, I get a very different behaviour on my end: I do see the temporary "Activating" status, as well as the "activated" status for 2 seconds as planned.

https://cl.ly/7f56bc5eb5d5

This is when using Jetpack 7.5.1.

Can you reproduce the behaviour from your video on a different site?

> Setting to be enabled when I browse to the Settings->Performance tab

This is a duplicate of #11288

**Comment by jeherve** [comment] 2021-02-25 09:40
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.

**Closed by jeherve** 2021-02-25 09:40 UTC
Labels: FixTheFlows, JITM, [Status] Needs Author Reply, [Type] Bug
