### ISSUE TITLE
JetPack Posting Feature image via Email Feature

### ISSUE THREAD

**Issue by ajames-ajcoms** [Automattic/jetpack#14603] opened 2020-02-08 12:23 UTC
The feature to add a feature image using short codes while posting via email will be a huge help to those who travel and post. I see this has come up for a feature request many times, but somehow has always been pushed back.  Maybe there are new developments or innovations that can make it work this time around. 

#### Describe the solution you'd like.....

A short code, or as an image attachment with some sort of instruction in the email body that enables me to send an email with a picture and have jetpack plug in post that specific image as my feature image on the new post.

**Comment by jeherve** [comment] 2020-02-10 07:52
Closing as duplicate of #11366

**Closed by jeherve** 2020-02-10 07:52 UTC
Labels: Post By Email

**Comment by ajames-ajcoms** [comment] 2020-02-10 15:03
Hello.  Does this mean someone is working on this? I ask because the ticket
you reference below as a duplicate seems closed by the last comment in it.

Please let me know

Thanks
Anoop

**Comment by jeherve** [comment] 2020-02-10 15:07
@ajames-ajcoms No one is working on this right now, no. #11366 is still open, and we'll post updates there if we start working on this!
