### ISSUE TITLE
Sharing email dropdown not responsive

### ISSUE THREAD

**Issue by cyphix333** [Automattic/jetpack#12235] opened 2019-05-01 20:52 UTC
Hello,

Have noticed the email option in JetPack's sharing functionality isn't responsive.

#### Steps to reproduce the issue

1. Enable email sharing option in Settings -> Sharing -> Configure your sharing buttons
2. Check a page they are output on and click the email icon to show the dropdown

#### What I expected

I expected it to be responsive to all screen sizes.

#### What happened instead

It for the most part seemed to always dropdown in the same place regardless of screen size and was not usable as it displayed outside the viewport as well as creating horizontal scroll bars.

**Screenshots**

https://i.imgur.com/RUN7WBE.png

**Comment by jeherve** [comment] 2019-05-02 11:07
Closing as duplicate of #6617

**Closed by jeherve** 2019-05-02 11:07 UTC
Labels: Sharing, [Type] Duplicate
