### ISSUE TITLE
Search: Index media library items for searching

### ISSUE THREAD

**Issue by gsmumbo** [Automattic/jetpack#16684] opened 2020-08-02 18:10 UTC
Right now Jetpack Search is able to index posts and pages, but not the entirety of the media library. This means that media that has been uploaded but not assigned to a post/page is left out of the search.

Indexing the entirety of the media library means that users of the site can search for a photo for example and pull it up directly, despite it never being published to a page.

**Comment by gsmumbo** [comment] 2020-08-02 18:10
Requested in zen-3191469

**Comment by jeherve** [comment] 2020-08-03 08:09
cc @gibrown I assumed we indexed all media, regardless of whether it was attached to a post or not?

**Comment by gibrown** [comment] 2020-08-03 14:45
@jeherve hmmm, I thought/think we would be indexing all cases also. Do we have a specific example (post_id)? Maybe because https://github.com/Automattic/wpes-lib/blob/master/src/indices/jetpack-search-v2-index.php#L414 doesn't contain "inherit" as a list of post statuses? We should probably open a jpop-issue for this.

BTW, extra records for every image is also one of the more common complaints from users about the total cost, so I am glad to hear another example where someone specifically wants the image results.

**Comment by htdat** [comment] 2020-08-06 01:59
I am working on this ticket 3191469-zen so the issue **seems not** about indexing. Instead, it's the issue that they want to use Jetpack Search in WordPress Media (WP Admin). 

We asked:

>  you would like users to be able to use Jetpack Search to search for specific media items in your media library even if they aren't assigned to posts or pages?

They confirmed: 

> Yes, exactly that.

I think we need to tweak this request a bit to reflect exactly what they want.

**Comment by gibrown** [comment] 2020-08-10 16:41
Cool. Ya, closing in favor of https://github.com/Automattic/jetpack/issues/13295 (and I expanded on the details of that issue). Not a small feature, but definitely under discussion.

**Closed by gibrown** 2020-08-10 16:41 UTC
Labels: Search, [Type] Enhancement, [Type] Happiness Request
