### ISSUE TITLE
Non-logged In Visitors in Mobile Safari see Browser Warning After Submitting Comment on HTTP Site

### ISSUE THREAD

**Issue by ntpixels** [Automattic/jetpack#3781] opened 2016-05-09 21:47 UTC
#### What I expected
Any visitor (logged in or not) able to submit comments to sites without error warnings when using Safari on mobile devices and computers.

#### What happened instead
Visitors see a warning stating "This form is not secure. Are you sure you want to submit it?" when submitting a comment on their mobile device if they are not logged in.

#### Steps to reproduce the issue
The site does not have an SSL certificate. But the form is being submitted through a form embedded within an iframe. The error only appears on Safari on mobile devices. It does not occur on Firefox, Chrome (desktop or mobile), or Chrome on the desktop.

Things to keep in mind:
- Safari has an option to “Ask before sending a non-secure form to a secure website.” that visitors can enable. But the security warning may dissuade visitors from commenting.
- It may be similar to this [mixed content issue](https://wordpress.org/support/topic/jetpack-comments-mixed-content-warning-caused-by-included-script)

**Comment by ntpixels** [comment] 2016-05-09 21:50
2649298-t

**Comment by jeherve** [comment] 2016-05-10 10:11
Closing as duplicate of #3565

**Closed by jeherve** 2016-05-10 10:11 UTC
Labels: Comments
