### ISSUE TITLE
verify_secrets_missing error after 4.2 update debacle 

### ISSUE THREAD

**Issue by chuckreynolds** [Automattic/jetpack#4778] opened 2016-08-12 21:17 UTC
#### Steps to reproduce the issue
Related to #4751 - this shows up in admin now and modules don't work. 
Deactivating / Reactivating doesn't work.
Uninstalling / Reinstalling doesn't work.

#### What happened instead
This shows up on Jetpack admin pages. 
![screen shot 2016-08-12 at 10 11 04](https://cloud.githubusercontent.com/assets/46185/17630696/2fb94b36-6075-11e6-96a3-927bc46d1454.png)

Any way to fix that in the DB or completely uninstall everything including DB rows but backup module settings?

**Comment by chuckreynolds** [comment] 2016-08-13 00:54
- Object caching flushed. 
- Cloudflare cache flushed just in case.
Still an issue. 

I put Jetpack into development mode for now as the features they use should be okay with that; at least they have access to them now.

**Comment by chuckreynolds** [comment] 2016-08-13 05:33
note for reference:  enabled jetpack development mode in wp-config

**Comment by jeherve** [comment] 2016-08-15 11:53
Sorry about that! It seems your Jetpack options got messed up during the update. Could you try to delete all Jetpack options, and then go through the connection flow again?
`wp option delete jetpack_options`

If that doesn't help, could you post your site URL here so I can have a look?

If you want it to remain private, you can also contact us via this contact form:
http://jetpack.com/contact-support/

**Comment by chuckreynolds** [comment] 2016-08-15 21:22
Same issue after doing that. 

new `jetpack_options` is 
```
a:3:{s:7:"version";s:16:"4.1.1:14xxxxxxxxxx";s:28:"fallback_no_verify_ssl_certs";i:0;s:9:"time_diff";i:0;}
```
(note: I x'd out that number in case it was unique to our site). 
I'll contact via the form. ty :)

**Comment by jeherve** [comment] 2016-08-16 11:09
> I'll contact via the form. ty :)

Thanks! It might indeed be best, as I would need to find out more about your site since I can't reproduce on my end.

I'll close this issue and we'll continue that conversation via email.

**Closed by jeherve** 2016-08-16 11:09 UTC
Labels: General, [Status] Needs Author Reply, [Type] Bug
