### ISSUE TITLE
Conflict between Photon and Revslider

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#10221] opened 2018-09-26 15:32 UTC
Originally reported in 1444268-zen as well as in a chat I had but don't have the link for it anymore.

When using the Revslider (Revolution Slider) plugin on a site, along with Photon, images do not appear.  It seems that the plugin replaces the `src` URL of an image file with a `data:image/gif:base64` which fails to load. With Photon off, the images work as expected.

**Comment by jeherve** [comment] 2018-09-26 16:33
Since this is a Premium plugin this is going to be hard for us to test things. 

Does this happen regardless of the Lazy Images module?

**Comment by richardmtl** [comment] 2018-09-26 17:31
I've asked the reporter to try.

**Comment by tmmbecker** [comment] 2019-02-20 15:38
1817568-zen

I've asked them to answer the question about Lazy Images.

**Comment by ntpixels** [comment] 2019-02-20 23:38
Update for 1817568-zen
The issue occurs whether Lazy Load is enabled or not. They have also said they will reach out to the plugin's developer for more information.

**Comment by annezazu** [comment] 2020-02-16 18:59
2718094-zen

**Comment by jenhooks** [comment] 2020-02-20 10:57
2730598-zen

**Comment by cena** [comment] 2020-03-01 16:40
2730598-zen

**Comment by druesome** [comment] 2020-08-11 18:23
I can confirm that this is fixed based on my tests.  Closing this issue.  For more info: p9F6qB-5y4

**Closed by druesome** 2020-08-11 18:23 UTC
Labels: Photon, [Status] Needs Author Reply, [Type] Bug, [Type] Happiness Request
