### ISSUE TITLE
My Jetpack: activate button for VideoPress card is failing on the first click, but working on the second

### ISSUE THREAD

**Issue by lhkowalski** [Automattic/jetpack#30199] opened 2023-04-19 18:43 UTC
Steps to reproduce:

- Install and activate Jetpack, VideoPress standalone and Social standalone, all bleeding edge
- Deactivate both Jetpack and VideoPress standalone plugins
- Go to My Jetpack
- Click on the Activate button for VideoPress
- An error will pop in the console:

![image](https://user-images.githubusercontent.com/6760046/233169863-abeba1f0-e651-43bc-bf7b-9b8ce7404669.png)

- Click it again, now it will activate

This video shows the issue happening:

https://user-images.githubusercontent.com/6760046/233170053-7c48e720-f4b5-476f-8452-6aa837be7493.mov

Expected behavior:

- it should activate on the first time, without error

**Comment by nunyvega** [comment] 2023-04-20 08:27
I just tested it and can replicate the issue. 
I noticed that while it returns an error the first time you try to activate it, it actually works. If you click on “Activate” just once, the plugin is actually enabled. Refreshing the MJ page also shows it active after one attempt.

**Comment by nunyvega** [comment] 2023-04-20 09:57
Looks like the issue is that we are returning false here:
https://github.com/Automattic/jetpack/blob/trunk/projects/packages/status/src/class-modules.php#L392
and then fail this check:
https://github.com/Automattic/jetpack/blob/trunk/projects/packages/my-jetpack/src/products/class-hybrid-product.php#L132

**Comment by dhasilva** [comment] 2023-04-21 20:00
Cannot reproduce the issue, it must have been fixed with another issue:

https://user-images.githubusercontent.com/8486249/233724353-effbc782-6f25-4c10-9346-e55bf051747a.mp4

**Comment by dhasilva** [comment] 2023-04-21 20:01
Closing as the issues seems to be fixed already.

**Closed as completed by dhasilva** 2023-04-21 20:01 UTC
Labels: Bug, [Package] My Jetpack, [Pri] TBD
