### ISSUE TITLE
Jetpack Tiled Gallery pls use nicer thumbnails (or custom if wanted)

### ISSUE THREAD

**Issue by s-a-s-k-i-a** [Automattic/jetpack#2052] opened 2015-04-29 18:47 UTC
The first image shows the thumbnails that the tiled gallery generates. The second one shows, the cropped, nicer thumbs generated by WordPress. Please make a possibility available to use WP thumbnails, instead of Photon squeezes.

Thanks!
![jetpack-thumbs](https://cloud.githubusercontent.com/assets/3524165/7398694/e560792e-eeb0-11e4-9d65-880eb4d9b6e9.jpg)
![wp-thumbs](https://cloud.githubusercontent.com/assets/3524165/7398695/e7f6dcf0-eeb0-11e4-90c9-c03121d7dbfa.jpg)

**Comment by jeherve** [comment] 2015-04-30 11:20
Closing as duplicate of #1526

**Closed by jeherve** 2015-04-30 11:20 UTC
