### ISSUE TITLE
JITM: Two identical JITMs shown after connection

### ISSUE THREAD

**Issue by brbrr** [Automattic/jetpack#11045] opened 2018-12-28 05:13 UTC
#### Steps to reproduce the issue

1. Start with fresh site e.g. JN 
2. Go through connection flow via wp-admin
3. after selecting free plan you'll be redirected to Jetpack Dashboard where 2 identical JITMs will be shown

#### What I expected

To see only 1 JITM

#### What happened instead
See screenshot

**Screenshots**
![image](https://user-images.githubusercontent.com/5654161/50503395-5b53bf80-0a99-11e9-9371-370ed1c3e75d.png)

**Comment by oskosk** [comment] 2018-12-31 15:06
Just got the same. Labeling as high priority

**Comment by jeherve** [comment] 2019-01-02 15:08
I can't seem to reproduce right now, with a fresh JN site. Did you purchase a plan during setup, or did you do anything to refresh that page's URL at some point?

@oskosk If you can still reproduce, do you think you could check the Network tab for `/wp-json/jetpack/v4/jitm` calls? Is `message_path` the same for the 2 calls you see?

**Comment by oskosk** [comment] 2019-01-03 14:33
Will try to repro, I just used a fresh JN site with free plan

**Comment by oskosk** [comment] 2019-01-03 14:33
I'm thinking that it was probably Jetpack 6.8.1 (stable)

**Comment by oskosk** [comment] 2019-01-03 14:51
In the http access logs from that moment, I found something strange. Indeed two requests were made to the `/wp-json/jetpack/v4/jitm` endpoint:

```
192.0.87.33 - - [31/Dec/2018:15:04:35 +0000] "GET /?rest_route=%2Fjetpack%2Fv4%2Fjitm&message_path=calypso%3Aundefined%3Aadmin_notices&_for=jetpack&token=blabla&timestamp=1546268673&nonce=blabla&body-hash&signature=blabla HTTP/1.1" 200 33 "https://plastic-anteater.jurassic.ninja/?rest_route=%2Fjetpack%2Fv4%2Fjitm&message_path=calypso%3Aundefined%3Aadmin_notices&_for=jetpack&token=blabla&timestamp=1546268673&nonce=blabla&body-hash&signature=blabla" "Jetpack by WordPress.com" "-" 853 1.223 "2" "1.220" "plastic-anteater.jurassic.ninja"

192.0.86.80 - - [31/Dec/2018:15:04:35 +0000] "GET /?rest_route=%2Fjetpack%2Fv4%2Fjitm&message_path=calypso%3Ajetpack-connect%3Aadmin_notices&_for=jetpack&token=blabla&timestamp=1546268673&nonce=AXSXk1wDIQ&body-hash&signature=blabla HTTP/1.1" 200 458 "https://plastic-anteater.jurassic.ninja/?rest_route=%2Fjetpack%2Fv4%2Fjitm&message_path=calypso%3Ajetpack-connect%3Aadmin_notices&_for=jetpack&token=blabla&timestamp=1546268673&nonce=blabla&body-hash&signature=blabla" "Jetpack by WordPress.com" "-" 865 0.861 "656" "0.860" "plastic-anteater.jurassic.ninja"
```

Note the `message_path=calypso%3Aundefined%3Aadmin_notices` on the first request.

**Comment by jeherve** [comment] 2019-01-03 14:54
That is odd indeed. How would that `message_path` get passed here?

**Comment by oskosk** [comment] 2019-01-03 17:05
I think this one has the smell of a duplicate of #11028 due a to an early redirection happening as soon as we get back from WordPress.com

**Closed** 2019-01-08 10:21 UTC
Labels: Admin Page, JITM, [Pri] High, [Type] Bug
