### ISSUE TITLE
Body class "infinite-scroll" only when Infinite Scroll enabled

### ISSUE THREAD

**Issue by kamiyeye** [Automattic/jetpack#5456] opened 2016-10-30 13:46 UTC
#### Steps to reproduce the issue

Enable infinite scroll in theme

```
    add_theme_support( 'infinite-scroll', array(
        'container' => 'posts-container'
    ) );
```

Add CSS to hide native pagination

```
.infinite-scroll .post-navigation {
    display:none;
}
```

With Jetpack deactivated, checking posts page to see no navigation there.
#### The problem

Infinite scroll works well with Jetpack installed and the corresponding feature enabled, the problem is we need to ensure the theme work out of the box and perform basic functionality without relying on plugins, so when Jetpack not installed, the post navigation is invisible because of "display:none", because by `add_theme_support( 'infinite-scroll'), the class "infinite-scroll" is added to body no matter if Jetpack exists 
#### What I expected

Adding body class only when Jetpack activated and the feature is enabled.

**Comment by jeherve** [comment] 2016-10-31 21:34
That's an interesting issue, especially if it happens even when Jetpack is deactivated. In that case, that would point towards a WordPress core issue, not a Jetpack one. Either way, it's something that should be fixed :)

Could you let me know how the different parameters you added to your `add_theme_support( 'infinite-scroll')` call, so I can try to reproduce?

is there maybe a theme I can download where you could reproduce the issue?

**Comment by eliorivero** [comment] 2017-02-10 20:43
Closing since this ticket is invalid: `add_theme_support` doesn't add a class to `body`. In addition if this happens when Jetpack is deactivated then Jetpack is not the one adding anything.

**Closed by eliorivero** 2017-02-10 20:43 UTC
Labels: Infinite Scroll, [Pri] Low, [Status] Needs Author Reply, [Team] tdiv, [Type] Bug, [Type] Good First Bug
