### ISSUE TITLE
Subscription Widget: Optional text and Success message fields not working as expected.

### ISSUE THREAD

**Issue by RCowles** [Automattic/jetpack#1654] opened 2015-02-18 23:06 UTC
The success message for the Blog Subscription widget does not seem to be working as expected. The success message does not show after submitting the form, and instead the original text persists.

Steps to repro:

1. Create a Blog Subscriptions widget with default settings:

![screen shot 2015-02-18 at 2 56 49 pm](https://cloud.githubusercontent.com/assets/1421894/6258590/a21f2b92-b77e-11e4-8534-04198241e9ab.png)
2. On the front end, fill out and submit the form:

![screen shot 2015-02-18 at 2 57 36 pm](https://cloud.githubusercontent.com/assets/1421894/6258596/b2f54f96-b77e-11e4-9571-6cabe5ebddb2.png)

**Expected result**: Text from the "Success message" field shows in place of original text. 
**Actual result**: Original text is shown, with no success message. 

![screen shot 2015-02-18 at 2 57 47 pm](https://cloud.githubusercontent.com/assets/1421894/6258664/616de88a-b77f-11e4-8fce-bde541ca7bb6.png)

This was reported in the forums [here](https://wordpress.org/support/topic/deleting-spam-followers-language-whole-blogpost-in-notification-e-mail?replies=2#post-6586595) but I've also repro'd on my sandbox in Chrome and Firefox.

**Comment by dereksmart** [comment] 2015-02-19 20:23
Hm, I've failed to reproduce this running current master on both FF and Chrome.  Also using 2015.  
https://cloudup.com/cMW-Rzfj5Yy
https://cloudup.com/cHxtPgvFoaU
https://cloudup.com/c86Szg0y8mz

**Comment by RCowles** [comment] 2015-02-19 20:28
Hm... I'll dig into this deeper today.

**Comment by jessefriedman** [comment] 2015-03-09 14:09
Chrome (latest) running 2015 I was also unable to reproduce the problem. https://cloudup.com/c7NeJNTgHhl

**Comment by samhotchkiss** [comment] 2015-03-10 13:32
@RCowles - bump...

Can we get some verifiable proof that this issue exists?  Let's close if that doesn't come to light in the next few days...

**Comment by RCowles** [comment] 2015-03-10 18:40
Sorry for letting this one fall through the cracks. I'm traveling today, but I'll investigate tomorrow.

**Comment by samhotchkiss** [comment] 2015-03-12 02:42
No worries!  Fly safe, thanks @RCowles!

**Comment by RCowles** [comment] 2015-03-12 23:48
Hm... I'm unable to repro. I tried using 3.4-beta on a brand new install as well as on the install that produced the error before. Nothin'.

I've asked the user if they're still running into trouble. Will update this Issue when I hear back.

**Comment by yelly** [comment] 2015-03-13 13:11
If there really is a problem (although I can't reproduce it either), it's probably with code I wrote. Fell free to assign to me.

**Comment by samhotchkiss** [comment] 2015-03-16 17:23
Alright, closing this for now, please reopen @RCowles if it becomes reproducible

**Closed by samhotchkiss** 2015-03-16 17:23 UTC
Labels: bug, Subscriptions

**Comment by RCowles** [comment] 2015-03-16 17:33
Sounds like a plan. No reply from the user, will reopen if necessary.

**Comment by RCowles** [comment] 2015-03-19 17:30
Just to close the loop, it seems the issue has been resolved as of
