### ISSUE TITLE
Form Block: Allow border colour customisation

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/jetpack#26434] opened 2022-09-26 13:00 UTC
### Impacted plugin

Jetpack

### What

Add border colour setting

### How

Currently, we can't control the border colour for the field. Therefore, when the block is placed in a container that has a different background colour than the activated theme, it can be ugly, and there is no way for users to change it.

Some example:
![dotcompatterns wordpress com_2020_01_24_contact-8_](https://user-images.githubusercontent.com/908665/192282513-e1fc1c84-bcae-402a-bf4e-f04aee55e543.png)

**Comment by jeherve** [comment] 2022-12-12 11:39
Closing as duplicate of #27525.

**Closed as completed by jeherve** 2022-12-12 11:39 UTC
Labels: [Closed] Duplicate, Enhancement, [Pri] Normal, [Plugin] Jetpack, [Block] Form
