### ISSUE TITLE
Redirect to Boost Settings after upgrade from my-jetpack

### ISSUE THREAD

**Issue by haqadn** [Automattic/jetpack#39579] opened 2024-09-30 12:16 UTC
When upgrading from Boost's pricing table or CTA's the user is redirect to Boost purchase success page. However, this is not true for upgrades from My Jetpack. My Jetpack should also redirect to purchase success page on Boost.

pfln9p-Pk-p2#takeaway-always-redirect-to-boost

**Comment by dilirity** [comment] 2024-10-10 09:16
I'm not sure if something has changed, but activating Boost via the My Jetpack page and then upgrading from the My Jetpack page, redirects to Boost's dashboard after the process is done.

![Image](https://github.com/user-attachments/assets/0e7e6bf0-95bf-473d-ae93-5c83242b26c3)

**Comment by dilirity** [comment] 2024-10-10 09:19
I'm not sure if something changed since this issue was created, but activating and upgrading boost (same as the video), now links the user to Boost's settings page, not My Jetpack.

Looking at the code in calypso - that is indeed the case. Not sure what happened in the video.

EDIT:
Also - it's not possible to redirect to a sub-page in calypso. It always redirects to the main product page after a purchase.

**Comment by jeherve** [comment] 2024-11-05 14:30
> I'm not sure if something changed since this issue was created, but activating and upgrading boost (same as the video), now links the user to Boost's settings page, not My Jetpack.

Does this mean this can now be closed?

**Comment by dilirity** [comment] 2024-11-06 09:51
I think we can close it, it is no longer reproducible.

**Closed as completed by dilirity** 2024-11-06 09:51 UTC
Labels: Bug, [Pri] Normal, Plans, [Plugin] Boost, [Package] My Jetpack, Triaged
