### ISSUE TITLE
Comments: Users in Edge and Incognito/Private browsers cannot comment when login is required

### ISSUE THREAD

**Issue by alexjgustafson** [Automattic/jetpack#4803] opened 2016-08-15 18:52 UTC
If users must be registered and logged in to comment, then they will get a 403 error when commenting from Edge or incognito/private browsers.

#### Steps to reproduce the issue
1) Setup a site with the following:
- Jetpack comments module enabled
-" Users must be registered and logged in to comment " checked in discussion settings
-" Anyone can register" checked in general settings

2) Use Microsoft Edge, Chrome Incognito, Safari Private, or Firefox Private
3) Sign up as a user on the test site, login as that user
4) Leave a comment on post that is open for commenting

Could not replicate in Chrome, Firefox, Safari or IE 11 (in normal browsing instead of private)

#### What I expected
To possible see a loading symbol and/or "Submitting Comment" then for the comment to appear on the site or othewise reach owner moderation

#### What happened instead

Shown error message "Sorry, comments are closed for this item."
JavaScript console shows an error:
`Failed to load resource: the server responded with a status of 403 ()`
from source:  /wp-comments-post.php?for=jetpack 

In Edge it reads as:
`HTTP403: FORBIDDEN - The server understood the request, but is refusing to fulfill it.`
In wp-admin the comment does not appear for site owner

**Comment by kraftbj** [comment] 2016-08-15 19:14
When logged in and using "public" browsing mode, the comment request goes from the local browser to jetpack.wordpress.com which redirects the request to /wp-comments-post.php?for=jetpack. That last jump also accesses the cookies, including the logged in cookie, allowing the comment through.

This process uses third-party cookies, which must be enabled. Private modes disable third-party cookies by design.

I'm going to mark this as `wontfix` for the time being.

**Closed** 2016-08-15 21:43 UTC
Labels: Comments, [Status] wontfix

**Comment by Flytrap23** [comment] 2016-08-16 00:52
3rd party cookies are turned on for IE and I was not using an InPrivate browser for testing.

**Comment by alexjgustafson** [comment] 2016-08-16 10:33
@kraftbj makes sense for the private browsing, but when I replicated in Edge 3rd party cookies were on for sure.

**Comment by Flytrap23** [comment] 2016-08-16 20:13
Looks like the case was closed, so I'll use something else for comments.
