### ISSUE TITLE
Autoresponder option on Form blocks

### ISSUE THREAD

**Issue by vinnykaur** [Automattic/jetpack#32654] opened 2023-08-24 09:55 UTC
### Impacted plugin

Jetpack

### What

Add an autorespond feature for the form blocks. An autoresponder email option is a feature that sends out an email to the person who submits the form.  
Like this one: https://www.jotform.com/help/26-setting-up-an-autoresponder-email/

This was first requested here: pd4QKa-R2-p2

**Comment by cuemarie** [comment] 2023-08-24 22:44
Could be added to the list of options we provide under `On Submission` - https://wordpress.com/support/wordpress-editor/blocks/form-block/#submission-settings

📌 ACTIONS
- Feature request kept

**Comment by jeherve** [comment] 2023-08-28 16:17
Closing as duplicate of #25022.

**Closed as completed by jeherve** 2023-08-28 16:17 UTC
Labels: [Closed] Duplicate, Enhancement, [Feature] Forms, [Pri] Normal, [Plugin] Jetpack, [Block] Form, [Feature] Forms Blocks
