### ISSUE TITLE
Connect Stripe: excessive amount of congrats messages

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#33400] opened 2023-09-29 09:16 UTC
### Impacted plugin

Jetpack

### Steps to reproduce

1. Don't have Stripe connected
2. At the sidebar at post access panel, click to connect stripe
3. Do the Stripe Jazz
4. Upon returning to the editor, see loads of congrats messages

<img width="1708" alt="image" src="https://github.com/Automattic/jetpack/assets/87168/a9522a9c-6a1c-457a-a68f-1bf54b4ac57a">

### Impact

All

### Available workarounds?

No but the platform is still usable

### Logs or notes

Tested on locally running Jetpack. I've been connecting/disconnecting stripe few times in the past for this site.

Chrome browser.

**Comment by jeherve** [comment] 2023-09-29 13:38
cc @Automattic/gold Is that something you could look at?

Thank you!

**Comment by n3f** [comment] 2023-09-29 16:55
@simison Was this a WPCOM or Jetpack site. Were you in calypso at any point (just for enabling stripe maybe)?

**Comment by chrismccluskey** [comment] 2023-09-29 22:49
I'm able to replicate this in Jetpack running locally. For me, I only get 2 notifications, and this seems to happen whenever the `stripe_connect_success=gutenberg` is in the url. To replicate, run jetpack locally using a name other than localhost (to avoid dev mode) and visit `/wp-admin/post-new.php?stripe_connect_success=gutenberg`.

**Comment by chrismccluskey** [comment] 2023-09-29 23:00
It looks like `stripe-connection-notification.js` is what dispatches this notice, not from inside of a function, but as a result of it being `import`ed. It's only imported inside `editor.js`. It seems that. `editor.js` is imported more than once.

**Comment by monsieur-z** [comment] 2024-05-08 19:18
I haven't been able to reproduce the issue: I'm seeing only one success message. Closing the issue.

**Closed as completed by monsieur-z** 2024-05-08 19:18 UTC
Labels: Bug, [Pri] Normal, [Focus] Blocks, Earn, [Plugin] Jetpack, [Feature] Earn Blocks
