### ISSUE TITLE
Post By Email Featured Image

### ISSUE THREAD

**Issue by sageBrownell** [Automattic/jetpack#7478] opened 2017-07-18 13:45 UTC
Would it be possible to opt in for the first image on a Post-By-Email post to be set as the featured image? Users could then go in and set a different one if they'd like, but this would fill it out so no post appears broken depending on the theme.

Original request: 3328306-t

**Comment by woodfin** [comment] 2017-07-18 16:16
Love to see this as a feature.

**Comment by jeherve** [comment] 2017-09-07 12:30
Closing as duplicate of #376 

@sageBrownell @woodfin You can use a plugin like [this one](http://wordpress.org/plugins/simple-auto-featured-image/) to automatically set up a Featured Image for a post.

**Closed by jeherve** 2017-09-07 12:30 UTC
Labels: Post By Email, [Pri] Low, [Type] Feature
