### ISSUE TITLE
Stats: Number placeholder is incorrectly displayed for Japanese users

### ISSUE THREAD

**Issue by naokomc** [Automattic/jetpack#6537] opened 2017-03-01 01:01 UTC
#### Steps to reproduce
1. Go to Options -> General and switch the language to Japanese
2. Go to Jetpack Dashboard screen (/wp-admin/admin.php?page=jetpack#/dashboard)
3. Check under "Best overall day". The number placeholder is not replaced with a number.

Correct Japanese translation exists for the stable branch:

https://translate.wordpress.org/projects/wp-plugins/jetpack/stable/ja/default?filters%5Bterm%5D=%25%28number%29s&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

#### Browser / OS version

Chrome 56.0.2924.87, OSX 10.11.6
WordPress 4.7.2, Jetpack 4.6

#### Screenshot / Video

Japanese:

![japanese](https://cloud.githubusercontent.com/assets/34067/23441295/d6192f36-fe64-11e6-855e-879561b355ca.png)

French translation looks ok.

![french](https://cloud.githubusercontent.com/assets/34067/23441294/d6107f62-fe64-11e6-8fbf-039840794d5f.png)

#### Context / Source

Ticket: #1493279-t

**Comment by jeherve** [comment] 2017-03-01 09:35
Closing as duplicate of #5749

**Closed by jeherve** 2017-03-01 09:35 UTC
Labels: Stats, [Type] Bug
