### ISSUE TITLE
Refused to frame https://subscribe.wordpress.com/

### ISSUE THREAD

**Issue by matthewdevaney** [Automattic/jetpack#31331] opened 2023-06-12 17:13 UTC
### Impacted plugin

Jetpack

### Quick summary

This error message appears in console when a user tries to subscribe to my website. 

Refused to frame ‘https://subscribe.wordpress.com/&#8217; because an ancestor violates the following Content Security Policy directive: “frame-ancestors http://matthewdevaney.com/ 

### Steps to reproduce

Reproduction steps:

1. Go to [matthewdevaney.com](https://www.matthewdevaney.com/)
2. Attempt to subscribe on the sidebar
3. Error message appears: subscribe.wordpress.com refused to connect.
Additionally, this error appears in the console

### A clear and concise description of what you expected to happen.

The subscribe email sends properly but the iFrame does not disappear. Nor does the form get updated with a "confirm your email" message.

### What actually happened

Error message:

Refused to frame ‘https://subscribe.wordpress.com/&#8217; because an ancestor violates the following Content Security Policy directive: “frame-ancestors http://matthewdevaney.com/ 

Description:

This error message appears in console. When a user tries to subscribe to my website they get the error subscribe.wordpress.com refused to connect. a

Images

![image](https://github.com/Automattic/jetpack/assets/34290969/74d324f1-cae8-4c24-87c3-7be1846bb83e)

![image](https://github.com/Automattic/jetpack/assets/34290969/d6b35af5-0b6b-4a1a-8da4-dda6a161719d)

### Impact

All

### Available workarounds?

No and the platform is unusable

**Comment by worldomonation** [comment] 2023-06-13 03:18
Pinging @jeherve as you triaged Matt's last issue (quickly and very in-depth, I might add - thank you).

**Comment by jeherve** [comment] 2023-06-13 09:11
Could you give it another try? It seems to work on my end in Chrome right now.

If you continue to see that message, could you let me know what browser you're currently using?

**Comment by matthewdevaney** [comment] 2023-06-13 12:18
@jeherve 

My site is behaving differently this morning. Now a pop-over appears upon subscribe. But I don't want this behaviour. On Jetpack version 10 there was no pop-up. This is what I upgraded from.  How can I remove the pop-up?

It also adds a token to the URL parameters. This messed up my redirection to another page upon success. How can I remove the token?

![image](https://github.com/Automattic/jetpack/assets/34290969/2603e7f1-a167-4751-9c03-1bf720001976)

**Comment by jeherve** [comment] 2023-06-13 13:38
> My site is behaving differently this morning. Now a pop-over appears upon subscribe.

That is indeed the new subscribe behavior that was introduced in Jetpack 12.2. I'm not quite sure why it didn't work for you yesterday. Is it possible that you were using a different browser, or that somehow you were loading your site using HTTP instead of HTTPS?

> This messed up my redirection to another page upon success. How can I remove the token?

I assume you've been using the `jetpack_subscriptions_form_submission` filter to create that custom redirection. That filter did indeed stop working with this release. That is a bug, and we'll look into it. I opened #31351 to keep track of the problem.

> But I don't want this behaviour. On Jetpack version 10 there was no pop-up. This is what I upgraded from. How can I remove the pop-up?

We do not offer a way to opt out of the new subscribe modal when using the Subscribe block. You could, however, revert to using a legacy Subscriptions widget instead; this legacy widget is now impacted by the change. Here is how you could go about it:

1. Add the following code to a functionality plugin on your site. [Here is how you could do this for example](https://jetpack.com/support/adding-code-snippets/).

```php
/**
 * Force the display of the legacy Jetpack Subscriptions widget.
 *
 * @see https://github.com/Automattic/jetpack/issues/31331
 *
 * @param array $widgets An array of excluded widget-type IDs.
 */
add_filter(
	'widget_types_to_hide_from_legacy_widget_block',
	function ( $widgets ) {
		// Remove the "blog_subscription" widget from the excluded list,
		// if if has been added in there.
		if ( ( $key = array_search( 'blog_subscription', $widgets ) ) !== false ) {
			array_splice( $widgets, $key, 1 );
		}

		return $widgets;
	},
	99
);
```

2. Go to Appearance > Widgets in your dashboard, and locate the Subscribe block.
3. Below it, Add a "Legacy Widget" block.
4. In the legacy widget dropdown, select Jetpack's Blog Subscriptions widget.
5. Customize the widget to match your Subscribe block settings.
6. Remove the Subscribe block.

I hope this helps.

Since we track the remaining issue in #31351, I will now close this issue.

**Closed as completed by jeherve** 2023-06-13 13:38 UTC
Labels: Bug, [Feature] Subscriptions, [Status] Needs Author Reply, [Pri] Low, [Block] Subscribe, Customer Report [LEGACY], [Plugin] Jetpack

**Comment by matthewdevaney** [comment] 2023-06-13 14:20
@jeherve 
I created this snippet as you described.

![image](https://github.com/Automattic/jetpack/assets/34290969/90afdbd8-a84e-4223-8dee-8e893d4858b9)

Then I activated the snippet.

![image](https://github.com/Automattic/jetpack/assets/34290969/8f93424b-ebb0-4810-9b3d-7a946ca5b4ba)

Where is the legacy widget block in Appearance > Widgets?

![image](https://github.com/Automattic/jetpack/assets/34290969/d1b13b58-83d4-440b-a89b-f81c1d6a8232)

**Comment by jeherve** [comment] 2023-06-13 14:26
> Where is the legacy widget block in Appearance > Widgets?

Ah, that should be even easier; since you're using the classic widgets interface, you should not even need the code snippet. You should find the widget towards the top of the list, it's named "Blog Subscriptions (Jetpack)".

**Comment by matthewdevaney** [comment] 2023-06-13 14:55
@jeherve 
Blog subscriptions is already part of the sidebar.  There has been no change in the widget behaviour since adding the code snippet.

![image](https://github.com/Automattic/jetpack/assets/34290969/555b4091-8ae5-4776-a74a-ad013d0bcfb1)

**Comment by jeherve** [comment] 2023-06-13 15:31
How about the widget in your site's footer? Is it a block, or a subscriptions widget?

**Comment by matthewdevaney** [comment] 2023-06-13 15:45
The footer is a subscriptions widget. Not a block.

**Comment by matthewdevaney** [comment] 2023-06-14 00:45
I reverted my Jetpack plugin back to v10.4 and its working well again. I think I'll stay on that old version.

**Comment by jeherve** [comment] 2023-06-14 10:41
I've been trying to reproduce this issue but I seem to be missing something about your site setup.

Coud you let me know how you added the Subscriptions widget at the bottom of each post?

Thank you!

**Comment by matthewdevaney** [comment] 2023-06-14 12:41
I added the footer via Customize Menu > Widgets > Footer > Jetpack Blog Subscription.

The widget is back to v10.4 so you’ll not be able to reproduce errors in my site any longer.

**Comment by jeherve** [comment] 2023-06-14 12:59
Could you let me know how you added the form at the bottom of each one of your posts, when looking at single posts, like on this screenshot?

<img width="971" alt="image" src="https://github.com/Automattic/jetpack/assets/426388/80a522b7-f0a0-4591-98fe-b1d84c4cf42c">

Thank you.

**Comment by matthewdevaney** [comment] 2023-06-14 13:46
@jeherve.
I made my own reusable block.

The useable block has a grey background with an H3 title and description text. I placed a subscription widget with no title in the useable block. And i updated styling with additional custom css.

What made you interested in it?

**Comment by jeherve** [comment] 2023-06-15 13:25
> What made you interested in it?

I'm still interested in trying to reproduce the issues you're experiencing on my own test site. Unfortunately, even when using the same Cream Blog Pro theme and the same reusable block and 2 subsriptions widgets, I'm still having no luck. Whenever I use the subscriptions widgets, I do not get the modal, as expected. On your site, however, the subscription widgets' default behavior is overwritten just like if there was a Subscribe Block somewhere else on the page. I'm just not sure where yet.

In any case, #31351 remains open to fix the redirection issue.

**Comment by mgozdis** [comment] 2023-12-13 23:45
Additional user report: 7401061-zd-a8c 
It seems to be referencing the staging URL instead of production URL, possibly after syncing staging to production. Console shows: `Refused to frame 'https://subscribe.wordpress.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors http://notarealstagingurl.wpcomstaging.com https://notarealstagingurl.wpcomstaging.com".`

Their primary site address is set to a custom domain but submitting the form is using their staging site URL - this is an actual staging site URL and not their free URL for production site. Reconnecting Jetpack on the production site resolved the issue.
