### ISSUE TITLE
Facebook page plugin widget error

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/jetpack#17797] opened 2020-11-13 15:58 UTC
#### Steps to reproduce the issue

1. Add a Facebook page plugin widget to any widget area.
2. Add a title and the url of a public Facebook page.
3. View a page containing the widget area in Firefox.
4. See error, e.g.

![image](https://user-images.githubusercontent.com/1990037/99092268-d4465c80-25c8-11eb-92fc-1b61996c2ecc.png)

Note: it has worked for me in Chrome, but some users have reported the same issue in Chrome and Edge too.

Several reports here:
- https://wordpress.org/support/topic/jetpack-plugin-facebook/
- https://wordpress.org/support/topic/facebook-feed-plugin-jetpack/

#### What I expected

Facebook page displays with no errors.

**Comment by kbrown9** [comment] 2020-11-13 16:07
The problem appears to be caused by a Facebook bug. There are few discussions about this in the Facebook developer support forums:

https://developers.facebook.com/community/threads/883138175424476
https://developers.facebook.com/community/threads/369847697559402

**Comment by jeherve** [comment] 2020-11-16 09:40
I'll close this issue in favor of the main Facebook bug ticket:
https://developers.facebook.com/support/bugs/2526305424326407/

**Closed by jeherve** 2020-11-16 09:40 UTC
Labels: Extra Sidebar Widgets, [Type] Bug

**Comment by QualtechAPP** [comment] 2020-11-16 16:47
I have the same issue, facebook plugin can't work on browser like firefox, opera, safari, just only chrome working.  how to fix that problem?

**Comment by jeherve** [comment] 2020-11-16 16:50
@QualtechAPP I'm afraid there isn't much you can do to fix it; we'll need to wait for Facebook to fix the issue. You can subscribe to the issue to get updates when the problem gets fixed:
https://developers.facebook.com/support/bugs/2526305424326407/

**Comment by QualtechAPP** [comment] 2020-11-16 16:54
Hi Jeherve,
Thanks for comment, indeed. hope the issue they can solve ASAP.
