### ISSUE TITLE
AMP - Bullet list showing up after the sharing buttons on the AMP page

### ISSUE THREAD

**Issue by htdat** [Automattic/jetpack#12639] opened 2019-06-11 07:37 UTC
#### Steps to reproduce the issue

1. Use a default theme, e.g: Twenty Nineteen, Twenty Seventeen. 
2. Active official sharing buttons.
3. Visit AMP version of posts.
4. The bullets display like this: 

![1z0tCNQw](https://user-images.githubusercontent.com/10045087/59252404-3d000b80-8c56-11e9-8b5b-bfbaeb1a0cb8.png)

#### What I expected

Official sharing buttons. 

#### What happened instead

Display bullets not nicely. 

#### Other info 

- Reported in 2094355-zen
- I can confirm the issue as well.

**Comment by jeherve** [comment] 2019-06-11 08:42
I can't seem to reproduce on my end.

- What mode did you use under the AMP menu?
- What are your Validation Handling settings on that same page?
- What version of the AMP plugin were you using?

**Comment by jeiseman** [comment] 2019-06-12 02:38
Hi jeherve,

Make sure you use the "official" buttons and you will see the problem on the AMP page. I was able to reproduce this problem with Twenty Seventeen and with Twenty Nineteen on a fresh WordPress install. The only plugins were the AMP plugin and JetPack. I had three buttons: Print, Facebook, and Twitter. I used the latest version of WordPress and the latest version of the plugins. You can see this here: https://mafw.club/wordpress/2018/08/15/wordpress-resources-at-siteground/?amp
I tried using a different AMP plugin (Accelerated Mobile Pages) and got the same result.

If I use any other button style (other than Official Buttons) then I don't see the problem (e.g., Icon & Text, Icon Only, or Text Only).

The author of this issue was also able to reproduce the problem.

Jon

**Comment by jeherve** [comment] 2019-06-13 10:08
> Make sure you use the "official" buttons and you will see the problem on the AMP page.

Thank you! That seems to be it indeed.

**Comment by jeherve** [comment] 2019-06-19 18:10
Leaving this opened for now as there are still some display issues with the post footers.

**Comment by jeherve** [comment] 2020-07-01 13:20
This should be fixed by #15497.

**Closed by jeherve** 2020-07-01 13:20 UTC
Labels: AMP, Sharing, [Type] Bug, [Type] Happiness Request
