### ISSUE TITLE
New Double Read More Link in Subscription Email

### ISSUE THREAD

**Issue by grovesr** [Automattic/jetpack#34372] opened 2023-11-29 19:27 UTC
### Impacted plugin

Jetpack

### Quick summary

Jetpack newsletter subscribers are getting new post notification emails with two links to read the post:
1. "Continue reading Post Name" this is a link to the post after the "read more" tag
2. "Read more of this post" this is a link to the top of the post, not the more tag

I noticed this using WP 6.4.1 and the Flato theme. I switched back to the Twenty Twenty-Four theme and it still occurs. Is there a filter for the email content?

### Steps to reproduce

1. publish new post
2. look for notification email as a newsletter subscriber

I noticed this using WP 6.4.1 and the Flato theme. I switched back to the Twenty Twenty-Four theme and it still occurs.

### A clear and concise description of what you expected to happen.

I expected a single link to the post after more tag content of the post in the newsletter notification email body

### What actually happened

I got two links to the post in the body of the newsletter email. One to the post at the more tag and one to the top of the post

### Impact

One

### Available workarounds?

No and the platform is unusable

### Logs or notes

Noticed using Flato and Twenty Twenty-Four themes

**Comment by bobmatyas** [comment] 2023-11-29 22:42
Hi @grovesr -

Thanks for your report. I tried to replicate this, but I didn't have the same results as you. Could you share a screenshot and more information about your steps when writing the post?

This is what I got after adding paragraph blocks separated by a "read more" block.

![Annotation on 2023-11-29 at 17-39-32](https://github.com/Automattic/jetpack/assets/45246438/4e668878-18ea-4a22-aa41-ee15d3a8c7b5)

**Comment by jeherve** [comment] 2023-11-30 08:30
Potentially related:

- #15447
- #7178 

Following those issues and how they were resolved, I don't immediately see any obvious regressions here (and we cannot reproduce the issue as mentioned above).

@Automattic/apex Do you think you could double-check on your end, since you're currently working on improving the display of those emails?
Thank you!

@grovesr It would be super helpful if you could let us know your site URL as well as give us an example of a post where you saw the issue, so we can investigate further. If you want your site URL to remain private, you can also contact us via this contact form:
http://jetpack.com/contact-support/?rel=support
Thank you!

**Comment by grovesr** [comment] 2023-11-30 12:30
My site url is https://robsapps.a2hosting.com/wordpress-36yrdream and the newly published post can be found here https://robsapps.a2hosted.com/wordpress-36yrdream/2023/11/29/second-test-of-a-new-pot/. Here is a screeenshot of the newsletter email in gmail 
![jetpack_newseletter_email_issue](https://github.com/Automattic/jetpack/assets/3090185/98cd4eb0-7c56-4ba1-8ccc-cf24c8d968d7)

**Comment by ivan-ottinger** [comment] 2023-11-30 13:10
> My site url is https://robsapps.a2hosting.com/wordpress-36yrdream and the newly published post can be found here https://robsapps.a2hosted.com/wordpress-36yrdream/2023/11/29/second-test-of-a-new-pot/. Here is a screeenshot of the newsletter email in gmail

Thanks for sharing the details and the screenshot. That helps!

It looks like some kind of edge-case is occurring here. When sending myself a test email related to the post above, instead of getting the "Continue reading..." link, I get the same "Read more of this post" link twice:

![Markup on 2023-11-30 at 14:02:15](https://github.com/Automattic/jetpack/assets/25105483/0a7bc00c-7f31-4e97-aae5-0748162e56a8)

This is regardless of a post I test with (still related to the same site). I haven't been able to reproduce with other site yet.

**Comment by jeherve** [comment] 2023-11-30 13:19
Thank you!

I haven't been able to reproduce either, but I wonder if there may be a difference between your setup and ours:

- Could you let us know what your settings are under Settings > Reading > "For each post in a feed, include"?
- Did you write your post using the block editor, or are you maybe using the classic editor plugin on your site?
- I wonder if the first link could be added by your theme, but the markup doesn't add up with what's set in the Flato theme:
https://themes.trac.wordpress.org/browser/flato/1.3/functions.php#L335

**Comment by ivan-ottinger** [comment] 2023-11-30 13:20
Alright, I was able to reproduce the issue.

The site has likely the following setting (in https://wordpress.com/settings/newsletter/) enabled:

![Markup on 2023-11-30 at 14:19:21](https://github.com/Automattic/jetpack/assets/25105483/30b86ca9-3074-4078-b09f-37a59dff2436)

**Comment by grovesr** [comment] 2023-11-30 13:37
That is correct. I have excerpt selected.

**Comment by grovesr** [comment] 2023-11-30 13:42
Here is the result with "Full Text" selected in Settings->Reading->for each
post in a feed, include. As you can see it doesn't actually include the
full text, only the text up to the more tag and there is still an issue
with double links. I am using the block editor.
[image: jetpack_newsletter_email_with_full_text_selected.png]

**Comment by ivan-ottinger** [comment] 2023-11-30 13:45
> Could you let us know what your settings are under Settings > Reading > "For each post in a feed, include"?

We have decoupled the "feed" setting from how the post is rendered in _New Post_ emails. In other words, there are now two separate toggles:

- "For each new post email, include" available at https://wordpress.com/settings/newsletter/ - used in _New Post_ emails
- "For each post in a feed, include" available in _Reading → Settings_ (`/wp-admin/options-reading.php`) - used in site feeds

---

> That is correct. I have excerpt selected.

> Here is the result with "Full Text" selected in Settings->Reading->for each
post in a feed, include. As you can see it doesn't actually include the
full text, only the text up to the more tag and there is still an issue
with double links. I am using the block editor.
[image: jetpack_newsletter_email_with_full_text_selected.png]

If you switch the "For each new post email, include"  to "Full text" (in https://wordpress.com/settings/newsletter/ ), then you shouldn't see the duplicated link on the bottom of your emails.

**Comment by grovesr** [comment] 2023-11-30 13:49
I did that and that was the result in the last email snapshot. I only got
the excerpt and there were still two links. I did a few more tests by
deactivating some other plugins "Classic Editor" and "GTMetrix" to see if
that changed anything, but same results. The only other plugins beyond
Jetpack are Loginizer and Wordpress Importer. I'll try deactivating those
as well and see what happens

**Comment by grovesr** [comment] 2023-11-30 13:54
Another try with all non-jetpack plugins disabled and "full text" selected.
[image: jetpack_newsletter_email_another_try.png]
[image: settings_reading_include.png]

**Comment by ivan-ottinger** [comment] 2023-11-30 13:57
Unfortunately, the screenshots aren't displaying here, but I believe you have changed the setting "For each post in a feed, include" setting in _Reading → Settings_, instead of "For each new post email, include" in https://wordpress.com/settings/newsletter/.

These are two different settings that have very similar name. 🙂

**Comment by grovesr** [comment] 2023-11-30 14:08
Interesting. I only have one choice "for each post in a feed include".
There is no radio button (or even a form field at all) for "for each new
post email include" under Settings->Reading

**Comment by grovesr** [comment] 2023-11-30 14:17
Sorry I didn't realize I had to access the jetpack settings from my wordpress.com account to see all of the available settings. If I access the admin through my self hosted site, I don't see the setting, but I do see the setting when accessing the admin through wordpress.com. In any case, I now only see one link in the email, but I am also not seeing the full text in the email, even though I have selected Full Text "For each new post email, include"
![jetpack_newsletter_email_for_each_new_post_email_include_full_text](https://github.com/Automattic/jetpack/assets/3090185/b68e25b1-e37a-4c32-9cec-4a2794878e82)

**Comment by ivan-ottinger** [comment] 2023-11-30 14:54
> Sorry I didn't realize I had to access the jetpack settings from my wordpress.com account to see all of the available settings. If I access the admin through my self hosted site, I don't see the setting, but I do see the setting when accessing the admin through wordpress.com.

No worries. I think we could consider adding that "For each new post email, include" setting to WP Admin as well in the future; to make it easier to access the setting.

> In any case, I now only see one link in the email, but I am also not seeing the full text in the email, even though I have selected Full Text "For each new post email, include"

This is likely because the post includes the "Read more" block. If you remove that block from the post, the email should include the full post content.

Basically, both the "Read more" block and and the "For each new post email, include" setting result in similar outcome in the _New Post_ email.

The "Read more" block can be placed anywhere in the post and that's how it signals where the content should be "cut". On the other hand, the "For each new post email, include" applies to all posts and the location of where the content is "cut" is predefined.

In other words:

- if you would like to have full post displayed in the email, I would suggest removing the "Read more" block from the post and keeping the "For each new post email, include" set to "Full text".
- if you would like to have just an excerpt displayed in the email, I would suggest either to set the "For each new post email, include" to "Excerpt" (without having the "Read more" block in the post content) -- or -- keeping the "For each new post email, include" at "Full text" and manually placing the "Read more" block to the post content.

This is the "Read more" block I am referring to:

![Markup on 2023-11-30 at 15:52:38](https://github.com/Automattic/jetpack/assets/25105483/a094ec41-b7d4-4826-b9b8-b3c3820a3edc)

**Comment by grovesr** [comment] 2023-11-30 15:00
Great. I understand! Since I am used to placing my own more tag, I will continue doing so and leave the setting at Full Text. I guess that is the reason there ended up being two links because there were two different mechanisms attempting to add a link?

**Comment by ivan-ottinger** [comment] 2023-11-30 15:27
> Great. I understand! Since I am used to placing my own more tag, I will continue doing so and leave the setting at Full Text. I guess that is the reason there ended up being two links because there were two different mechanisms attempting to add a link?

Yes. That is correct. There are two ways to achieve similar results. Each is for different use case:

- "For each new post email, include" set to "Excerpt" is one setting that applies to all posts at once (the user then doesn't need to place the "Read more" button to each post)
- "Read more" block (for users that need more flexibility and are alright with adding the block to each post manually)

I am closing this issue for now but feel free to reopen if you have further questions on the topic. We will be happy to help.

**Comment by bobmatyas** [comment] 2023-12-04 20:51
@ivan-ottinger, I tested this using the settings on WPCOM with a self-hosted Jetpack site running on Pressable (JP v12.9). When I receive the email, it is only an excerpt based on what is selected in the feed settings. The newsletter setting doesn't seem to change it.

Post content:

![Screenshot_at_December_4th_2023_-_3 39 33_pm(1)](https://github.com/Automattic/jetpack/assets/45246438/43b8db69-6730-457f-8c8b-a339f70546aa)

Setting:

![Annotation on 2023-12-04 at 15-35-58](https://github.com/Automattic/jetpack/assets/45246438/f9e595e2-a32e-4594-83a4-a46e7f1a1464)

Email:

![Screenshot_at_December_4th_2023_-_3 37 29_pm](https://github.com/Automattic/jetpack/assets/45246438/4bbb177d-bfe0-4662-8f2f-fb21fc2546c3)


When I reverse this ("Excerpt" on WPCOM and "Full Text" in WP Admin), it sends just the excerpt as expected. 

Would it be best to open a new issue for this?

**Comment by ivan-ottinger** [comment] 2023-12-05 16:07
Hey @bobmatyas 👋🏼 Thanks for your comment. Could you please share with us the site address so we could take a closer look?

You can respond here (if it is ok for you to have the site address shared publicly) as the issue seems to be related. Thank you.

**Comment by ivan-ottinger** [comment] 2023-12-06 08:50
Related discussion: p1701852289281549-slack-C02TCEHP3HA.

**Comment by ivan-ottinger** [comment] 2023-12-07 08:07
Resolved in p1701852289281549-slack-C02TCEHP3HA. We run into the following issue: https://github.com/Automattic/jetpack/issues/27763.

**Closed as completed by ivan-ottinger** 2023-12-07 08:07 UTC
Labels: Bug, [Feature] Subscriptions, [Pri] Normal, [Plugin] Jetpack, Triaged, [Status] Priority Review Triggered
