### ISSUE TITLE
Jetpack JITM Package: remove dependencies

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/jetpack#12579] opened 2019-06-05 20:07 UTC
In the [initial PR](https://github.com/Automattic/jetpack/pull/12516) for making a JITM package,  we left a few Jetpack-specific dependencies.

We need to circle back and remove them on the next iteration.

**Comment by gititon** [comment] 2019-06-06 15:30
In progress

**Comment by gititon** [comment] 2019-06-06 19:57
Started with https://github.com/Automattic/jetpack/pull/12596

**Comment by gravityrail** [comment] 2019-06-27 19:10
Dupe of https://github.com/Automattic/jetpack/issues/12686

**Closed by gravityrail** 2019-06-27 19:10 UTC
Labels: JITM, Jetpack DNA, [Status] In Progress
