### ISSUE TITLE
Related Posts: Warning: invalid argument supplied for foreach() 

### ISSUE THREAD

**Issue by bobbingwide** [Automattic/jetpack#11813] opened 2019-04-02 14:23 UTC
Having just enabled Jetpack's Related Posts in a WPMS subdomain when I viewed some content that included a pre-existing Related Posts block the following message was displayed.
```
Warning: Invalid argument supplied for foreach() in /home/bworguk/public_html/wp-content/plugins/jetpack/modules/related-posts/jetpack-related-posts.php on line 1491
```
#### Steps to reproduce the issue

1. Enable Related Posts
2. Create content with the Related Posts block
3. Copy the generated block from one subdomain to another
4. Enable Related Posts in the other subdomain
5. View the content containing the copied block

#### What I expected

No warning.

#### What happened instead
Warning was displayed the first time that the post was viewed after re-enabling Related posts.

**Screenshots**
Sorry, I didn't capture a screenshot.

**Comment by jeherve** [comment] 2019-04-02 17:03
Could you try to reproduce the issue once again once Jetpack 7.2 is released in the next couple of hours? We've made some changes to that part of the plugin, so this may be fixed now.

Thank you.

**Comment by bobbingwide** [comment] 2019-04-13 14:48
In my local development environment. When I upgraded to 7.2.1 I no longer had the capability to use jetpack/related-posts block. I notice there's a jetpack/repeat-visitor block though.

**Comment by bobbingwide** [comment] 2019-04-13 15:34
It's now line 1484

![image](https://user-images.githubusercontent.com/2474435/56081883-ec149800-5e09-11e9-92b1-963a2aa18bc5.png)

**Comment by jeherve** [comment] 2019-04-15 10:04
Do you have a custom caching solution on this site? If so, could you tell us more about it?

**Comment by jeherve** [comment] 2020-09-24 17:33
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.

**Closed by jeherve** 2020-09-24 17:33 UTC
Labels: Gutenberg, Related Posts, [Pri] High, [Status] Needs Author Reply, [Type] Bug

**Comment by bobbingwide** [comment] 2020-09-25 06:58
That’s fine. No, there was no custom caching. It would appear that the problem has been resolved. One day I’ll update my documentation to include the screenshot.
