### ISSUE TITLE
Sharing / AMP: unsupported services are still displayed when using Official Buttons

### ISSUE THREAD

**Issue by Zabi09** [Automattic/jetpack#14217] opened 2019-12-12 11:02 UTC
Firstly I am using the latest version of both AMP and jetpack - https://prnt.sc/q9s3uv and if I use the official button option - https://prnt.sc/q9s76p then the output of the AMP is really not looking good.
See this screenshots:
https://prnt.sc/q9s5jv
https://prnt.sc/q9s6fp

**Comment by htdat** [comment] 2019-12-17 09:30
@jeherve this seems a duplicate of https://github.com/Automattic/jetpack/issues/12639 ?

**Comment by jeherve** [comment] 2019-12-17 10:01
@htdat Yes you're right. Closing this as duplicate.

**Closed by jeherve** 2019-12-17 10:01 UTC
Labels: AMP, Sharing, [Type] Bug, [Type] Duplicate
