### ISSUE TITLE
Sharing: Add vk.com 

### ISSUE THREAD

**Issue by davoraltman** [Automattic/jetpack#3760] opened 2016-05-03 08:58 UTC
Found this in vk.com docs:

http://vk.com/dev/share_details

There's also this plugin - https://wordpress.org/plugins/vkontakte-api/

per 2645847-t

**Comment by SPEC1AL1ST** [comment] 2016-05-03 09:15
Very nice idea!

**Comment by jeherve** [comment] 2016-05-03 09:28
Closing as duplicate of #849

> There's also this plugin - https://wordpress.org/plugins/vkontakte-api/

If you'd like to add the VK.com button to Jetpack's Sharing module, you're better off using this plugin:
https://wordpress.org/plugins/vk-sharing-jetpack/

**Closed by jeherve** 2016-05-03 09:28 UTC
Labels: Sharing, [Type] Enhancement
