### ISSUE TITLE
SSO: Wrong CTA on user profile page when unlinked 

### ISSUE THREAD

**Issue by dereksmart** [Automattic/jetpack#2345] opened 2015-07-03 15:10 UTC
Currently you'll see this CTA on your profile page if your user account is unlinked: 

https://cloudup.com/cuOs4PfBuIL

Clicking that will give you an missing_token error.  

It should be the same flow as PBE: 
https://cloudup.com/cvvs8-W8slt

**Comment by georgestephanis** [comment] 2015-07-03 15:33
missing_token?  That sounds like a site specific bug.

**Comment by dereksmart** [comment] 2015-07-03 15:38
I don't think so - https://github.com/Automattic/jetpack/blob/1cb8b0a0ab0e2e2b826c62a3ec48de62692398be/class.jetpack-client.php#L33

since the user isn't connected, they don't have a token.

**Comment by jeherve** [comment] 2015-07-03 15:39
Closing as duplicate of #1216

**Closed by jeherve** 2015-07-03 15:39 UTC
Labels: bug, SSO
