### ISSUE TITLE
Jetpack Search - Instant Search - Doesn't respect currency selection in WooCommerce, defaults to $.

### ISSUE THREAD

**Issue by scosgro** [Automattic/jetpack#19500] opened 2021-04-10 23:51 UTC
#### Steps to reproduce the issue

1. Activate WooCommerce
2. In WooCommerce settings, set your currency to something that is not USD, or a currency that does not use the $ symbol. 
3. Activate Jetpack Search, and use it to search for products. 
4. Products that appear in the instant search will use $ by default, instead of the currency you have set in your WooCommerce settings. 

Originally a user report. Screenshots from a test site (not a real store). 

WooCommerce Settings:
![image](https://user-images.githubusercontent.com/30731356/114287589-ccc29c80-9a1c-11eb-8778-8c7f2819ec46.png)
![image](https://user-images.githubusercontent.com/30731356/114287598-d6e49b00-9a1c-11eb-9c26-d20a9b8932fd.png)

Vs what appears in Jetpack Search:
![image](https://user-images.githubusercontent.com/30731356/114287578-bf0d1700-9a1c-11eb-9545-9b822a3b9d0d.png)

#### What I expected
Jetpack Search to show WooCommerce products in the currency that the store's settings are set to.

#### What happened instead
Regardless of the store's currency settings, the $ appeared instead. 

**Screenshots**

**Comment by bluefuton** [comment] 2021-04-11 21:55
Thanks @scosgro. We're presenting the formatted price from the API in the front end, so I suspect something must be amiss on the Elasticsearch side. I'll triage this today.

**Comment by bluefuton** [comment] 2021-04-12 03:30
I can confirm this bug. The API is returning the $ (&#036;) in all cases. cc @gibrown 

<img width="528" alt="Screen Shot 2021-04-12 at 15 29 15" src="https://user-images.githubusercontent.com/17325/114336857-040f8580-9ba4-11eb-9cec-2924086ade37.png">

**Comment by bluefuton** [comment] 2021-04-12 03:45
Looks like the `woocommerce_currency` option is empty, so it's defaulting to USD:

```
> switch_to_blog( ... );
> echo get_option( 'woocommerce_currency' );

> echo get_option( 'woocommerce_currency', 'USD' );
USD
```

Is it perhaps not being synced to the Jetpack shadow/cache site?

**Comment by gibrown** [comment] 2021-04-12 17:27
I guess we found a bug caused by my failure to prioritize getting https://github.com/Automattic/jetpack/pull/18870 merged...

**Comment by bluefuton** [comment] 2021-04-13 03:32
@scosgro we're actively working on fixing this. In the meantime, in case the original reporter is interested, one of our customers has an ingenious temporary workaround using CSS:

https://lapidoule.com/?s=

The styles are:

```
li.jetpack-instant-search__search-result .woocommerce-Price-currencySymbol::before {
    content: "€";
    font-size: 15px;
}

li.jetpack-instant-search__search-result .woocommerce-Price-currencySymbol {
    font-size: 0;
}
```

**Comment by bluefuton** [comment] 2021-04-13 23:41
This should be resolved in r224218-wpcom. We're now picking up the correct blog option when we index the site.

Sites will need to be reindexed for this change to take effect. This should happen the next time a product or page is changed on the user's site.

@scosgro if there are any user sites you would like me to manually reindex so this is change is instantly picked up, drop me a message with the blog IDs.

**Closed by bluefuton** 2021-04-13 23:41 UTC
Labels: Instant Search, Involves Happiness, Search, [Pri] High, [Type] Bug
