### ISSUE TITLE
Instant Search: always show filters

### ISSUE THREAD

**Issue by keoshi** [Automattic/jetpack#14179] opened 2019-12-05 11:53 UTC
#### Steps to reproduce the issue

- In the demo select the filter "Media".
- Search for "css".

#### What I expected

I would expect the filters list to still be visible.

#### What happened instead

The filters are hidden, preventing me from broadening my query.

Also note that the query is `?post_types=attachment&s=css` but the UI doesn't reflect that, showing nothing but an search box with “css”.

![image](https://user-images.githubusercontent.com/390760/70233048-b2581f00-1755-11ea-9011-c00299b13ea1.png)

#### Screen capture

![jps-filters-01](https://user-images.githubusercontent.com/390760/70233058-b97f2d00-1755-11ea-9bd7-b30b5584ba2b.gif)

**Comment by keoshi** [comment] 2019-12-05 12:13
Related: https://github.com/Automattic/jetpack/issues/13814

**Comment by gibrown** [comment] 2019-12-06 18:27
Kinda a duplicate of #8716 

I think we need to do some noodling on what this should look like.

We should definitely have something that makes it easy to clear the applied filters, and maybe we should always show what filters have been applied somewhere. I think when there are no results we should probably be recommending suggesting alternative filtering or alternative searches in the "No Results" section. We should probably be doing this down at the bottom of the page even when there are results to nudge the user towards refining their query rather than just paging through results.

**Comment by jsnmoon** [comment] 2020-01-09 22:18
> #### What I expected
>
> I would expect the filters list to still be visible.

> We should definitely have something that makes it easy to clear the applied filters

> maybe we should always show what filters have been applied somewhere

💯

**Comment by gibrown** [comment] 2020-02-24 17:54
Related to #14615

**Closed** 2021-10-05 21:00 UTC
Labels: [Status] In Progress, Search, Instant Search
