### ISSUE TITLE
Share code inserted into og:description

### ISSUE THREAD

**Issue by iamjohnford** [Automattic/jetpack#2723] opened 2015-09-18 13:32 UTC
I've not had the chance to completely debug this but I noticed a funny og:description showing up on a site I just launched. The sharing services content is getting added and then stripped out again. So, some of the text will remain. Here's how it happens.

Filter is added for the_excerpt
modules/sharedaddy/sharing-services.php:736: 
```
add_filter( 'the_excerpt', 'sharing_display', 19 );
```

the_excerpt is triggered
functions.opengraph.php:107
```
$tags['og:description'] = wp_kses( trim( apply_filters( 'the_excerpt', $tags['og:description'] ) ), array() );
```

sharing_display gets called and sends back the text
modules/sharedaddy/sharing-services.php:562
```
function sharing_display( $text = '', $echo = false ) {
  ...
  return $text.$sharing_content;
}
```

**Comment by kraftbj** [comment] 2015-09-18 16:22
Quick first idea, we could `remove_filter`/`add_filter` around the og_description?

**Comment by kraftbj** [comment] 2015-09-18 16:22
@iamjohnford Could you include a link to the site with the issue in place? A first look at my test site didn't reveal it.

**Comment by iamjohnford** [comment] 2015-09-18 16:37
I put in a temporary fix for the site so it's not live. The site was using share icons with official buttons - Twitter, Facebook, and Pocket. The sharing label is set to Share Article. The og:description would show the description text (maybe from an excerpt?) a newline and then "Share ArticlePocket" was printed after. I printed out the og:description early and saw that it was including all of the share content. Then I'm guessing another function/filter stripped that out.

**Comment by iamjohnford** [comment] 2015-09-20 09:36
Here are steps I used on a vagrant install to reproduce with twentyfourteen and Jetpack master:

* Enable Sharing via Jetpack and add the following settings:
  * Enable Pocket as a sharing service
  * Add a Sharing label (so you can see it in the og:description)
  * Show buttons on Posts
* Edit a post and make sure it has an excerpt - this is the key item to trigger the filter
* View source of post to see incorrect og:description which will look like this:

```
<meta property="og:description" content="[excerpt]
[sharing label]Pocket" />
```

**Comment by kraftbj** [comment] 2015-09-21 21:00
Quick acknowledgement to say thanks for the repo steps. I haven't had a chance to reproduce yet, but my sense is this is a valid bug. Marking it for 3.8.

**Comment by jeherve** [comment] 2015-09-22 13:01
Also reported here:
https://wordpress.org/support/topic/excerpts-doesnt-shown-anymore-when-sharing-new-posts

Ideally, we should use the unfiltered excerpt and content to generate the description tag.

**Comment by jeherve** [comment] 2015-09-27 15:21
Also reported here:
https://wordpress.org/support/topic/og-description-picking-up-sharing?replies=1&view=all

**Comment by kraftbj** [comment] 2015-09-27 19:17
Confirmed it on my own site too. Agreed on unfiltered excerpt. Is there any case where we want the filters, except for the sharing_display?

**Comment by kraftbj** [comment] 2015-09-27 19:22
The filters were added to grab other filters via https://github.com/Automattic/jetpack/pull/2378 , which makes sense, so need to be smarter than just grabbing the unfiltered excerpt, which is what was done previously.

**Comment by jeherve** [comment] 2015-09-28 10:34
Nice catch!

I assume we also need to take other plugins into account, as I'm sure there are dozens of other plugins hooking into `the_excerpt`. We wouldn't want any of these plugins to output extra content into the Open Graph Meta tags.

Since #2378 aimed to fix encoding issues, how about removing the filters and only convert HTML entities with `html_entity_decode()`, like we do [here](https://github.com/Automattic/jetpack/blob/3.7/modules/related-posts/jetpack-related-posts.php#L764).

**Comment by Michael-DST** [comment] 2015-10-01 19:13
Does anyone have a fix for this?  I am wanting to deploy my site tomorrow and it is hard to do that when post descriptions are showing up in Facebook as "Share this:FacebookTwitterTumblrRedditEmailPrint" :(

**Comment by Michael-DST** [comment] 2015-10-01 19:19
Commenting out [this line](https://github.com/Automattic/jetpack/blob/master/functions.opengraph.php#L108) worked for me.  Superhack FTW. :)

**Comment by kraftbj** [comment] 2015-10-09 22:11
Before testing it to confirm it'll meet both issues' goals, I like the `html_entity_decode()` solution. I'd like to also see unit tests on the og tags to help catch a regression (that we almost introduced).

**Comment by paulschreiber** [comment] 2015-10-10 01:19
I suggest changing the filter to `the_title` instead. Would that work?

**Comment by jeherve** [comment] 2015-10-21 18:27
Also reported here:
https://wordpress.org/support/topic/publicizesharing-share-this-text-is-in-ogdescription?replies=4&view=all

**Comment by HaraldWalker** [comment] 2015-10-21 18:37
Fix takes too long! This is hurting social sharing of many sites.

**Comment by kraftbj** [comment] 2015-10-27 01:59
@paulschreiber I think `'the_title` is reasonable. My only fear is if others are using `the_title` to do odd things, who knows what could happen.

By default, `the_title` runs `wptexturize`, `convert_chars`, and `trim`. We could probably run those same three against the og:description and call it a day without fear of another plugin mucking up things.

**Comment by paulschreiber** [comment] 2015-10-27 03:47
@kraftbj We're already applying the_title to og:title — using that makes sense. (It makes less sense to use the filter for one and custom code for the other.)

**Comment by kraftbj** [comment] 2015-10-27 04:51
Understood, but that's also filtering the title. This issue is coming about because of unexpected additions tacked onto a filter, so trying to avoid that causing things to go sideways by using a filter for a different bit of content.

All that said, I put in the PR to get the ball rolling so we can close this issue in 3.8 and not punt it forward. I'll defer to whatever approach the dev team opts to go with. I don't have a dog in the fight, short of wanting the sharedaddy leftovers out sooner rather than later.

**Closed** 2015-10-28 20:02 UTC
Labels: bug, Needs Review, Sharing, Unit Tests
