### ISSUE TITLE
Form block shows 50% fields in separate lines

### ISSUE THREAD

**Issue by ariel-maidana** [Automattic/jetpack#34567] opened 2023-12-11 12:50 UTC
### Impacted plugin

Jetpack

### Quick summary

When two 50% fields are added to a Form block, they are shown on different lines instead of side by side on the live view of the page. They are shown side by side in the editor:

Editor view:

![imagen](https://github.com/Automattic/jetpack/assets/4965723/4ce11943-0628-4d7e-a8b0-26ce0d3ed630)

Preview and live view:

![imagen](https://github.com/Automattic/jetpack/assets/4965723/b95c6042-cdd2-4424-82e6-e3e7a5c293af)

### Steps to reproduce

1. Create a Form block.
2. Add two fields and set the field width to 50%.
3. Save as draft or publish.
4. Check the preview and/or visit the page on the live site.

### A clear and concise description of what you expected to happen.

The two 50% fields should be side by side, as they appear in the editor: 

![imagen](https://github.com/Automattic/jetpack/assets/4965723/4ce11943-0628-4d7e-a8b0-26ce0d3ed630)

### What actually happened

The fields appear stacked:

![imagen](https://github.com/Automattic/jetpack/assets/4965723/b95c6042-cdd2-4424-82e6-e3e7a5c293af)

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

7387565-zd-a8c
Reproduced on test site.

**Comment by ariel-maidana** [comment] 2023-12-11 12:52
Please notify 7387565-zd-a8c when a fix is deployed.

**Comment by anomiex** [comment] 2023-12-11 14:58
> 1. Create a Form block.
> 2. Add two fields and set the field width to 50%.
> 3. Save as draft or publish.
> 4. Check the preview and/or visit the page on the live site.

Could not reproduce following these instructions. The Form block needs to additionally be set to the "Outlined" style (select the Form block itself, then in the block settings pane choose the Styles icon to see the option). When adding that step, I was able to reproduce on a self-hosted dev site as well as on Simple.

It appears that what happens is that the "Outlined" and "Animated" styles add a wrapper with class `contact-form__inset-label-wrap` around the field, and this wrapper is always 100% width rather than respecting the percentage width setting. 

I see @monsieur-z has recently been working on the forms, pinging him.

> Please notify 7387565-zd-a8c when a fix is deployed.

To set expectations: We (devs) will probably forget to do this.

The deployment process goes something like this:

* First, a fix has to be written and merged. This issue will either get auto-closed when the fix is merged, or it will get manually closed some time later (perhaps months later if no one does right away in response to a GitHub notification on the issue about the fix being merged) when someone happens to look back at it and see that a fix was merged.
* At some point usually within the next working day, changes are deployed in a batch to Simple. Likely by a different team from whoever did the fix.
* Each week (usually) changes are deployed to Atomic, with one team preparing the weekly release and a different team deploying it.
* The plugin release for self-hosted sites happens monthly.

**Closed as completed** 2023-12-15 14:59 UTC
Labels: Bug, [Feature] Forms, [Pri] Low, Customer Report [LEGACY], [Plugin] Jetpack, [Block] Form, Triaged, [Platform] Simple, [Status] Priority Review Triggered, [Feature] Forms Blocks
