### ISSUE TITLE
Stats: Role Restrictions Not Respected

### ISSUE THREAD

**Issue by arinoch** [Automattic/jetpack#31358] opened 2023-06-13 01:09 UTC
### Quick summary

Users who do not have permission to view Jetpack Stats can still view Jetpack Stats.

### Steps to reproduce

1. On an atomic site (feature not available on simple), navigate to Tools > Marketing > Traffic > Jetpack stats.
2. Expand the UI to reveal the role restriction options.
3. Uncheck everything except the administrator role.
4. Add a test user to your site. Give them any role other than administrator.

### What you expected to happen

Non-admins should be denied stats access.

### What actually happened

In my test, I could view stats as a contributor.

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

**Comment by worldomonation** [comment] 2023-06-13 03:36
📌 REPRODUCTION RESULTS
Tested on Simple – not applicable
Tested on Atomic – reproduced
Replicable outside of Dotcom – took a quick look but did not see options to limit stats visibility, so assuming not applicable.

📌 FINDINGS/SCREENSHOTS/VIDEO
**AT**

Limiting the stats to Administrators only.
<img width="1156" alt="Screenshot 2023-06-13 at 12 22 11 PM" src="https://github.com/Automattic/wp-calypso/assets/6549265/7f8e57dc-7244-451b-80d4-aac4d2193a1a">

Invited user is able to see Jetpack Stats under Sidebar > Stats.
<img width="1270" alt="Screenshot 2023-06-13 at 12 29 39 PM" src="https://github.com/Automattic/wp-calypso/assets/6549265/c2ee3dfb-3e6b-473d-a8d8-08f0769c015c">

📌 ACTIONS
- set priority to Normal, as:
    - the site is still usable
    - uncertain whether the availability of stats to a wider audience than intended is a high priority issue
- assigning to Others column.-

If you do not agree, please feel free to chime in!

**Comment by jeherve** [comment] 2023-06-13 16:23
@Automattic/red Do you think you could take a look? This seems like a pretty big regression.

Thank you!

**Comment by jsnmoon** [comment] 2023-06-13 21:00
Limiting access to Calypso Stats by user role has yet to be a priority for the team, so I can see why this edge case slipped through the cracks. 

Note that I'm having trouble reproducing this mostly because I can't seem to find the same controls at `Tools > Marketing > Traffic`:

> EDIT: Clipped large image

Can anyone advise? (EDIT: See solution below)

Note that this does not occur on Jetpack sites, which check for `view_stats` permission before allowing access.

**Comment by worldomonation** [comment] 2023-06-14 05:01
@jsnmoon Are you using an AT site? As noted in the initial steps to reproduce, you have to use an AT site because the equivalent feature does not exist in Simple.

**Comment by jsnmoon** [comment] 2023-06-14 18:23
> Are you using an AT site? As noted in the initial steps to reproduce, you have to use an AT site because the equivalent feature does not exist in Simple. (@worldomonation)

Good catch! I thought I was, but my test site's plan had elapsed and reverted into a Simple site. I can reproduce this as expected now and will continue investigating.

**Comment by jsnmoon** [comment] 2023-06-14 21:16
As far as I can tell, access control using the current user's roles was never implemented in Calypso Stats (please correct me if I'm mistaken). As such, I'd classify this as a product defect rather than a regression.

I created [a pull request](https://github.com/Automattic/wp-calypso/pull/78210) to begin remedying this issue on Calypso, but I'm afraid a complete fix will require changes to our backend as well (i.e., fix the `stats_is_blog_user` function being invoked [here](https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/sal/class.json-api-site-base.php#L921)).

**Comment by kangzj** [comment] 2023-12-12 01:46
Closing as fixed with https://github.com/Automattic/wp-calypso/pull/78210

**Closed as completed by kangzj** 2023-12-12 01:46 UTC
Labels: Bug, [Feature] Stats Data, [Pri] Normal, [Plugin] Jetpack, [Platform] Atomic, [Package] Stats Data, [Package] Stats Admin
