### ISSUE TITLE
SSO does not work whenever one hides wp-login and wp-admin

### ISSUE THREAD

**Issue by theblackwidower** [Automattic/jetpack#1699] opened 2015-03-01 10:31 UTC
So, my new site just went live, and it's running Jetpack because I like it. Particularly the single-sign-on feature. Makes things much easier, since I'm always logged onto WordPress.com anyway, and it uses two-step and other good stuff like that.

But once the site went live, I was advised to do what I could to hide wp-login and wp-admin. I quickly found a plugin that did the job, but quickly ran into a problem when I noticed the SSO button was missing.

I alerted the developers of that plugin to the issue: https://github.com/srtfisher/Lockdown-WPAdmin/issues/12

But then I decided to install a new comprehensive security plugin (https://wordpress.org/plugins/better-wp-security/) that did the same thing, only this time, the SSO button was there again! 

Yay that! Then I clicked on it, and got a 404 error on wordpress.com.

Seems the way the button works, I click on it, and it redirects to this URL: 
https://wordpress.com/[whatever I set as the name of the login page]?action=jetpack-sso&site_id=[numbers]&sso_nonce=[something else I'm sure I should redact]

Now, this could be a problem with the security plugin, but I'm pretty sure the problem originates in Jetpack. Which is why I'm posting this here. If someone can find an elegant solution to this, please provide. I would love to keep using single sign on, while still keeping the backend hidden. I just don't know how yet.

**Comment by jeherve** [comment] 2015-03-02 13:10
Closing as duplicate of #1511.

**Closed by jeherve** 2015-03-02 13:10 UTC
