### ISSUE TITLE
Publicize: Format the "disconnected" state similar to other Publish box items

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6049] opened 2017-01-06 17:00 UTC
#### Steps to reproduce the issue
- Install Jetpack
- Activate Publicize
- Go to Posts > Add New

#### What I expected
I expected to see Publicize appear within the Publish metabox, in a similar fashion to the other items there (e.g. to look "native").

#### What happened instead
Instead, it looks inconsistent:

![screen shot 2017-01-06 at 9 53 59 am](https://cloud.githubusercontent.com/assets/108942/21725569/2e3ab020-d3f6-11e6-8cca-2e859531f8ae.png)

I think we should make it look more like the other items, something along the lines of:

![screen shot 2017-01-06 at 10 01 00 am](https://cloud.githubusercontent.com/assets/108942/21725751/fabf964c-d3f6-11e6-8976-c9e9aa948952.png)

**Comment by jeherve** [comment] 2018-02-23 17:34
Closing as duplicate of #8919

**Closed by jeherve** 2018-02-23 17:34 UTC
Labels: FixTheFlows, Publicize, [Status] Needs Design Review
