### ISSUE TITLE
"Notify me of new posts via email." still appears even after subscription module disabled.

### ISSUE THREAD

**Issue by dericleeyy** [Automattic/jetpack#12904] opened 2019-06-28 14:10 UTC
#### Steps to reproduce the issue

1. Go to Jetpack > Settings > Discussions
2. Disable
 * Show a "follow blog" option in the comment form
 * Show a "follow comments" option in the comment form
 * Allow users to subscribe to your posts and comments and receive notifications via email

#### What I expected
The comments form should hide the follow options depending on settings.

#### What happened instead
The following blog and comments checkbox still shows after disabling the option.
The follow comment checkbox only disappears if subscription module is disabled. However, the follow blog option is still shown.

**Comment by edequalsawesome** [comment] 2019-06-30 16:14
Issue also reported in #13684175-hc 

Follow-up here: #2140373-zen

**Comment by jeherve** [comment] 2019-07-03 10:23
I believe this is a duplicate of #10047.

Could you test and confirm that the toggles in fact revert to their previous state, and that using the old checkboxes under Settings > Discussion works?

**Comment by edequalsawesome** [comment] 2019-07-03 16:27
@jeherve On my self-hosted test site, I've turned off the option to subscribe to post updates in WP Admin > Jetpack > Settings > Discussion:

![Jetpack > Settings > Discussion](https://cld.wthms.co/RHwCXa+)

But the option to follow the site by email is still appearing under the comment form: 

![Follow Site by Email in Comment Form](https://cld.wthms.co/aurura+)

The setting for my test site on WordPress.com match the settings in WP Admin -- I don't think there's another spot that I need to check to deactivate it, but if there is, let me know and I'll give it a look!

**Comment by jeherve** [comment] 2019-07-03 17:33
Thank you, that's helpful! It seems to be an issue with the Comment module, that overwrites the default comment form and does not appear to respect the site's module status.

To reproduce, one must:
- Disable the Subscriptions module on a Jetpack site.
- Enable the Comments module.
- Visit a post with a comment form.
- Expand the comment form.

@lancewillett It looks like you recently made some changes in D28395-code that may have caused this regression.

For a Jetpack site with the Subscriptions module disabled, `stb_enabled` is set to a boolean, `false`. If the module is enabled, once that setting is synchronized back to wpcom it will be set to a string `1`.

**Comment by lancewillett** [comment] 2019-07-10 16:44
To confirm, is this only an issue when managing settings in Calypso for a Jetpack site?

**Comment by edequalsawesome** [comment] 2019-07-10 17:51
@lancewillett I had made the changes through WP Admin on my self-hosted test site -- the changes then synced back to Calypso, but I didn't touch anything there directly.

**Comment by xpurichan** [comment] 2019-08-14 16:25
Also reported in 14571431-hc. 

When I replicated the problem on my test site it didn't matter if I toggled the comment options in Calypso or Jetpack's WP Admin settings. I also had the subscriptions module for Jetpack enabled contrary to @jeherve steps above.

**Comment by juliasydnor** [comment] 2019-08-23 15:31
Reported in 2296011-zen

**Comment by mbhthompson** [comment] 2019-10-10 21:06
Reported in 2410393-zen

**Comment by katiebethbrown** [comment] 2019-11-14 02:50
Reported in 2477894-zen, and duplicated on my test site.

Toggling off the Subscribe to Blog option via Calypso does change the `stb_enabled` option from `1` to an empty value (similar to the Subscribe to Comment option) but the form doesn't seem to respect the option on the front end.

**Comment by bikedorkjon** [comment] 2019-12-24 05:47
2581814-zen

**Comment by bikedorkjon** [comment] 2020-01-21 01:59
Customer above is still having an issue with this and the CSS we are providing them is not working which I believe is due to us loading comments in an iframe.

**Comment by joendotcom** [comment] 2020-01-22 15:59
2638309-zen

**Comment by bikedorkjon** [comment] 2020-01-23 08:06
2646412-zen

**Comment by xpurichan** [comment] 2020-02-07 17:48
18248829-hc

**Comment by gamebits** [comment] 2020-04-30 13:02
I'm having this problem on my site as well. Of the three options:

1. Let visitors subscribe to new posts and comments via email
2. Enable the “subscribe to site” option on your comment form
3. Enable the “subscribe to comments” option on your comment form

I've tried these settings combinations in wp-admin, with the following results:

* All three options disabled = "Notify me of new posts via email" displays.
* First option enabled = "Notify me of new posts via email" displays.
* First & second option enabled = "Notify me of new posts via email" displays.
* First & third option enabled = " Notify me of new comments via email" &  "Notify me of new posts via email" display.
* All three options enabled = " Notify me of new comments via email" &  "Notify me of new posts via email" display.

Similar changes in Calypso had identical results.

"Let visitors use a WordPress.com, Twitter, Facebook, or Google account to comment" is enabled.

**Comment by CompChris** [comment] 2020-05-01 19:52
20756655-hc

**Comment by rahul020691** [comment] 2020-05-23 10:09
The same user as Chris came back after 22 days asking for a fix
21332436-hc

**Comment by codi0** [comment] 2020-06-20 16:37
Same problem on a newly installed site. Jetpack comments enabled, all subscription settings disabled. All configured from local install's WordPress admin area.

Very surprised this has not been fixed in over a year. It's not earth shattering, but it's mis-leading to visitors and the option can't be hidden via css due to the form being loaded via iframe.

**Comment by mattptodd** [comment] 2020-07-28 00:48
Ok, bringing some light to this.  The problem only happens when you click "Let visitors use Wordpress......"  as soon as that is unchecked, the form goes back to normal and the notify via email is not there.  I hope that helps.  I turned off all features one at a time to find when it happens.  I also dug through the plugin code and have not yet found "notify me" in there.

**Comment by KokkieH** [comment] 2020-09-03 08:51
Another report in https://wordpress.org/support/topic/cant-disable-notify-me-of-new-posts-by-email/

**Comment by griersongithub** [comment] 2020-11-12 18:30
3481609-hc looking for a fix, I will suggest turning off the comments feature.

**Comment by kbrown9** [comment] 2020-12-08 17:49
another report: 3556550-zen

**Comment by kbrown9** [comment] 2020-12-15 20:47
I have a proposed solution for this bug ready for review in D54065-code.

**Comment by kbrown9** [comment] 2020-12-28 18:54
The solution I mentioned above is now live, and this bug should be fixed. I'm closing this issue. If anyone notices problems, let us know.

**Closed by kbrown9** 2020-12-28 18:54 UTC
Labels: Comments, Subscriptions, [Type] Bug, [Type] Happiness Request
