### ISSUE TITLE
Form Block: Background color not consistent between editor and live version

### ISSUE THREAD

**Issue by coder-karen** [Automattic/jetpack#23114] opened 2022-02-25 11:17 UTC
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Testing with the 10.7 Beta, add a form block and change the background color. Try with several themes, and in some cases the form background in the editor will be the same color for the form frame as well as form input fields, in other cases the form fields will be a lighter color. 

### A clear and concise description of what you expected to happen.

* The expectation was that the form input fields would be the same in both the editor and the live preview (and that the background color wouldn't necessarily affect the form fields).

### What actually happened

I didn't test any themes that showed the form input fields as white in the editor itself, but most showed the input fields a lighter shade than the form frame. This differed from the live version of the form, which showed the input field with a white background, or even a darker background (the same as the frame). Here's an example from Dalston and Twenty Twenty Two:

Editor:
<img width="330" alt="Screenshot 2022-02-25 at 11 07 36" src="https://user-images.githubusercontent.com/16754605/155705035-1521ecfb-650e-4be7-844a-1b966f899e9e.png">
Live:
<img width="330" alt="Screenshot 2022-02-25 at 11 08 10" src="https://user-images.githubusercontent.com/16754605/155705163-2e440488-3d94-49b1-ab0a-50dafd613115.png">

Additionally, with some themes the background color is the same for both the form framing and input fields (in both the editor and live). Here is an example from the 'Quadrant Yellow' theme:

Editor:
<img width="330" alt="Screenshot 2022-02-25 at 10 50 41" src="https://user-images.githubusercontent.com/16754605/155704465-e969f685-2903-47fb-8336-f3721057dd7a.png">
Live:
<img width="330" alt="Screenshot 2022-02-25 at 11 04 25" src="https://user-images.githubusercontent.com/16754605/155704587-7bf804c9-267a-44f9-85b1-a5c4502c19e9.png">

### Other information

This was reported here: p8oabR-Oy-p2#comment-6026

Another thought - having an option to change the background color of the form input fields as well as the form frame could solve both issues? Since there are so many ways a theme can override the form input field color it seems.

### Operating System

macOS

### Browser

Chrome/Chromium, Firefox

### Browser Version(s)

98

**Comment by ivan-ottinger** [comment] 2022-02-25 17:27
I have looked at the issue quickly and these are the findings:

> I didn't test any themes that showed the form input fields as white in the editor itself, but most showed the input fields a lighter shade than the form frame. This differed from the live version of the form, which showed the input field with a white background, or even a darker background (the same as the frame). Here's an example from Dalston and Twenty Twenty Two:

The reason for this color difference is the following style applied to the form fields:

```css
background: rgba(255, 255, 255, 0.5);
```

This style is applied in the editor only because the form fields are disabled there (to prevent user using them in the editor):

```css
textarea.disabled {
	background: rgba(255, 255, 255, 0.5);
	border-color: rgba(220, 220, 222, 0.75);
	box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.04);
	color: rgba(44, 51, 56, 0.5);
}
```

Also adding this to our team's backlog to take a look.

**Comment by ivan-ottinger** [comment] 2022-07-06 10:31
Another report (Twenty Twenty-Two theme): p8oabR-T0-p2#comment-6463.

**Comment by JuanLucha** [comment] 2022-11-10 11:58
@ivan-ottinger checking that Twenty Twenty-Two theme comment, I can see that the issue is marked as resolved. I tried to reproduce it myself and I couldn't.

**Comment by ivan-ottinger** [comment] 2022-11-14 15:45
> @ivan-ottinger checking that Twenty Twenty-Two theme comment, I can see that the issue is marked as resolved. I tried to reproduce it myself and I couldn't.

That's true. I wasn't able to reproduce the issue anymore either. All themes I checked (Twenty Twenty Two, Dalston and Quadrant Yellow - mentioned in this thread) display the Form block background correctly now (consistently between the editor and the published page).

One thing I noticed though is that some themes have style inconsistencies elsewhere in the block styles, e.g. Submit button is different, or form field height vary:

**Dalston theme:**

| Editor | Saved Page |
| ------------- | ------------- |
| ![Markup on 2022-11-14 at 14:13:58](https://user-images.githubusercontent.com/25105483/201672681-d52b3574-c8ce-49ec-a6c3-45d5bf510fd0.png) | ![Markup on 2022-11-14 at 14:14:17](https://user-images.githubusercontent.com/25105483/201672683-55ee8f52-b9c4-47d0-9372-1eb731062de6.png) |

→ Created a separate issue for the Dalston theme: https://github.com/Automattic/themes/issues/8578 and mentioned there that more themes are affected.

---

I would say it is OK to close this one issue as it is already fixed.

**Closed by ivan-ottinger** 2022-11-14 15:45 UTC
Labels: [Type] Bug, [Plugin] Jetpack, [Block] Contact Form
