### ISSUE TITLE
On un-install remove JetPack options set from wp_options db table

### ISSUE THREAD

**Issue by lukecav** [Automattic/jetpack#4172] opened 2016-06-20 19:24 UTC
As easy way to remove these options on plugin un-install

_transient_timeout_jetpack_https_test
_transient_jetpack_https_test
jetpack_file_data
jetpack_available_modules
jetpack_log

**Comment by jeherve** [comment] 2016-06-20 19:32
Closing as duplicate of #2502

**Closed by jeherve** 2016-06-20 19:32 UTC
