### ISSUE TITLE
Whatsapp button block preview close itself in block editor

### ISSUE THREAD

**Issue by AbhijitNage123** [Automattic/jetpack#17901] opened 2020-11-25 15:35 UTC
- Whatsapp button block preview close itself in the block editor

#### Steps to reproduce the issue

1. Go to 'the page in block editor'
2. Click on '+ icon'
3. Scroll down to 'the Whatsapp button block'
4. See an error

#### What I expected

- Block preview should be visible without closing the panel.

**Screenshots**
- https://share.getcloudapp.com/rRu0Xeb8

I am facing the issue while sharing the PR but below code help you to resolve the issue. please check : )
`example: {
		innerBlocks: [
			{
				name: 'jetpack/whatsapp-button',
				attributes: {
					countryCode: '1',
					phoneNumber: '555-123-4567',
				},
			},
		]
	},`

**Comment by jeherve** [comment] 2020-11-25 17:11
I can't seem to be able to reproduce at the moment. Could you tell us more about your setup (version of WordPress, Jetpack, Gutenberg, whether you use other plugins like Elementor), and let us know if you still experience the same issue when deactivating other plugins?

Could you also check for Javascript errors on the page, as explained here:
https://wordpress.org/support/article/using-your-browser-to-diagnose-javascript-errors/

Let me know what you find!

**Comment by AbhijitNage123** [comment] 2020-11-26 07:58
Jetpack by WordPress.com - Version 9.1 

WordPress Version 5.5.3

There is no console error in the editor.

The preview closes the popover by itself when I hover the Whatsapp button - https://share.getcloudapp.com/rRu0PzoA

jetpack > extension > block > send-a-message > index.js replace example:{} with

`example: {
innerBlocks: [
			{
				name: 'jetpack/whatsapp-button',
				attributes: {
					countryCode: '1',
					phoneNumber: '555-123-4567',
				},
			},
		]
}`

**Comment by jeherve** [comment] 2020-11-26 14:27
Thank you. 

Do you experience similar issues when deactivating all other plugins on the site?

**Comment by AbhijitNage123** [comment] 2020-11-26 14:48
I'm experiencing the same issue on a fresh WordPress installation with only Jetpack plugin install. Are you able to reproduce?

**Comment by jeherve** [comment] 2020-11-26 15:01
> Are you able to reproduce?

I was just able to reproduce now. I couldn't reproduce before because I was running WP 5.6 Beta.

It appears to be an issue with the block editor itself, and it is fixed in the upcoming version of WordPress, 5.6, scheduled to be released on December 8:

https://videopress.com/v/8ZFl34S6

Until WP 5.6 is available, I think you should be able to solve the issue on your site by installing the Gutenberg plugin. 

I hope this helps.

**Closed by jeherve** 2020-11-26 15:01 UTC
Labels: [Block] Send a message, [Status] Needs Author Reply
