### ISSUE TITLE
Jetpack CRM: New UI not scaling properly on mobile screens

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/jetpack#35166] opened 2024-01-22 13:43 UTC
### Impacted plugin

CRM

### Quick summary

The navigation menu on the Jetpack CRM pages within the WordPress Admin dashboard is not collapsing into a mobile version when the pages are viewed on a mobile device. This is causing all the CRM pages in WordPress Admin to have a horizontal scroll.

Originally Reported by @gaurav1984 on:
https://github.com/Automattic/jpop-issues/issues/8379

Forums thread:
https://wordpress.org/support/topic/screen-adaptation-issues-on-mobile-devices/#post-16858271

### Steps to reproduce

View CRM on a mobile device

### What actually happened

![250257443-72b7656c-d711-43fe-ad6f-5427d4994917](https://github.com/Automattic/jetpack/assets/45246438/8451f0a6-0f89-43d7-9d19-257e295dfdcf)

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

**Comment by tbradsha** [comment] 2024-01-22 18:42
Yes, there are plenty of issues in mobile view; closing as a duplicate of Automattic/zero-bs-crm#2608.

**Closed as completed by tbradsha** 2024-01-22 18:42 UTC
Labels: Bug, [Pri] High, Triaged, [Plugin] CRM, [Status] Priority Review Triggered
