### ISSUE TITLE
Search: filtering without search not working in the overlay

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#15175] opened 2020-03-29 17:57 UTC
Steps:
- start from front end of a site with instant search and sidebar filters on
- click on a filter (works, opens overlay and shows correct results)
- change the filtering (doesn't work, the results don't update)

This was tested on the `add/search-plan` branch. Maybe it works on `master` ?

**Comment by jsnmoon** [comment] 2020-03-29 21:00
I can't reproduce this locally. Could you disable the manual `siteId` override and see if it's still reproducible? 

This override can create a mismatch between the filters on the front-end (generated by the local WP backend) and the filters on the overlay (provided by the API).

**Comment by gibrown** [comment] 2020-03-29 22:17
Ya, I am running it without that override. It doesn't always happen, i'm not sure what the pattern is, but sometimes clicking around on the filters causes it to happen and other times not.

Do you see it happening on http://gibrown.wpsandbox.me/main

**Comment by jsnmoon** [comment] 2020-03-29 22:59
@gibrown: This should be fixed with 611eb20e0ea679aea3164ca2fe5090826760d6e3. Please reopen if it still persists.

**Closed by jsnmoon** 2020-03-29 22:59 UTC
Labels: Instant Search, Search, [Pri] High, [Type] Bug
