### ISSUE TITLE
Social Media Icons: Update to use Social Logos instead of Genericons

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#4250] opened 2016-06-29 19:03 UTC
Currently the social media icons widget is still using the old Instagram logo, and should be updated to use the newly redesigned one. Here's what the new one looks like, for reference: 

![fhmfmmefomkgmgjg](https://cloud.githubusercontent.com/assets/831377/16464974/9e4ca3e6-3e0a-11e6-979d-75f0b963f0ec.png)

Since we added [Social Logos](https://github.com/Automattic/social-logos) in #4096, we could replace all Social Media Icons by the new, up to date, Social Logos.

**Comment by jeherve** [comment] 2016-06-30 12:11
Updated the issue for a solution that would ensure that all logos are kept up to date.

**Comment by seejacobscott** [comment] 2017-02-08 22:13
user requested update on Instagram icon here 3047883-t

**Comment by jeherve** [comment] 2017-09-07 12:38
Closing as duplicate of #7433

**Closed by jeherve** 2017-09-07 12:38 UTC
Labels: Extra Sidebar Widgets, [Type] Enhancement, [Type] Good First Bug
