### ISSUE TITLE
Calypsoify: Icon alignment issues with core WordPress admin toolbar

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/jetpack#10571] opened 2018-11-08 11:09 UTC
#### Steps to reproduce 

- Start with a self-hosted WordPress site and install Jetpack
- Ensure this self-hosted WordPress has the core admin toolbar enabled. If your site has [WordPress.com toolbar](https://jetpack.com/support/masterbar/) enabled, it would need to be disabled
- Visit `{example.com}/wp-admin/plugins.php?calypsoify=1`

#### What is expected 

The admin toolbar at the top has proper icons and alignment

#### What happens instead 

The admin toolbar at the top has misplaced icons and alignment can be seen to be broken. 

On hovering over these icons, the styling can be seen to be incorrect/broken as well

#### Screenshots 

<img width="1281" alt="screenshot 2018-11-08 at 13 48 24" src="https://user-images.githubusercontent.com/18581859/48194866-32099380-e374-11e8-8a37-0d92a8ecdd21.png">

**Comment by jeherve** [comment] 2018-11-08 11:59
I can't seem to be able to reproduce the issue on my end. The toolbar looks like this for me on a Jetpack site:

<img width="1505" alt="screenshot 2018-11-08 at 12 57 47" src="https://user-images.githubusercontent.com/426388/48197385-ea740f00-e355-11e8-9822-3f04afcb806c.png">

And on an Atomic site:

<img width="1507" alt="screenshot 2018-11-08 at 12 58 37" src="https://user-images.githubusercontent.com/426388/48197442-07a8dd80-e356-11e8-8423-ea8e746c9395.png">

> Ensure this self-hosted WordPress has the core admin toolbar enabled. If your site has WordPress.com toolbar enabled, it would need to be disabled

How did you go about disabling the masterbar module on that site? Calypsoify requires the Masterbar module, and should force-activate it for you if it is disabled. That is most likely the issue here.

**Comment by arunsathiya** [comment] 2018-11-08 12:13
>Calypsoify requires the Masterbar module, and should force-activate it for you if it is disabled. That is most likely the issue here.

I should have been more clear here. I had this code on my site to have the WordPress.com toolbar disabled. 

```
function disable_wpcomtoolbar ( $modules ) {
    if ( isset( $modules['masterbar'] ) ) {
      unset( $modules['masterbar'] );
    }
    return $modules;
}    
add_filter( 'jetpack_get_available_modules', 'disable_wpcomtoolbar' );
```

I just tested with a few other Jetpack sites and I am not able to reproduce what I had mentioned on my original report. I see the same behaviour as the ones you have seen.

**Comment by jeherve** [comment] 2018-11-08 13:44
Thank you for the extra details. I can't seem to reproduce, even with that code; we do indeed force the Masterbar module on, whether you've hidden it or not. Even if the module is marked as unavailable, we call the masterbar files directly in Calypsoify:
https://github.com/Automattic/jetpack/blob/ef344485e06ef677768c4a415f4bed44e8b80faf/modules/class.jetpack-calypsoify.php#L45

As a result, in my tests Calypsoify looked good even when masterbar was not available, because it was turned on for me anyway.

I think you may have been caught in a weird case scenario where the masterbar was active, and then you made it unavailable and then called Calypsoify. 

Can you still reproduce the problem on that site?

**Comment by arunsathiya** [comment] 2018-11-08 14:13
>where the masterbar was active, and then you made it unavailable and then called Calypsoify.

I just tested the process in this order, and I am able to reproduce the issue in the original report. 

- On a fresh site, I enabled `masterbar` and then used the above code.
- Called Calypsoify and noticed that the section was broken.
- Removed the entered code.
- The view becomes normal again with the `masterbar`

![screenshot 2018-11-08 at 19 38 23](https://user-images.githubusercontent.com/18581859/48203738-4b1f3e00-e38e-11e8-8d5f-9c1ab54258dd.png)
<div align="center"><sup>Calling Calypsoify after making the `masterbar` unavailable</sup></div> 

![screenshot 2018-11-08 at 19 38 49](https://user-images.githubusercontent.com/18581859/48203739-4bb7d480-e38e-11e8-8f1e-93bce540594c.png)
<div align="center"><sup>On making `masterbar` available again</sup></div> 

I guess I could say this is an expected behaviour at this stage.

**Comment by jeherve** [comment] 2018-11-08 14:48
I would agree. I'll close this as `wontfix`.

**Closed by jeherve** 2018-11-08 14:48 UTC
Labels: Calypsoify, [Status] Wontfix
