### ISSUE TITLE
Gutenberg: The Tiled Gallery Block is displaying distorted images on the carousel when using square tiles style

### ISSUE THREAD

**Issue by guicmazeredo** [Automattic/jetpack#11150] opened 2019-01-15 22:08 UTC
#### Steps to reproduce the issue

1. Add a Tilled Gallery to a page or post with a few images.
2. Convert the block style to Square Tiles.
3. Publish the page.
4. Open the page on the live site. 
5. Click on the images to see them on the carousel. (You can compare to the image in the media gallery to see the issue clearly). 

#### What I expected

I expected to see the image in the original aspect ratio. Original image on the media gallery:

![screen shot on 2019-01-15 at 20-03-35](https://user-images.githubusercontent.com/426388/51247280-ee8f5f00-198c-11e9-8575-218f4f09a060.png)

#### What happened instead

The image is displaying distorted. Image on the carousel:

![screen shot on 2019-01-15 at 20-03-17](https://user-images.githubusercontent.com/426388/51247294-f8b15d80-198c-11e9-8337-be2cdf93bee3.png)

#### Browser / OS version

Chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by jeherve** [comment] 2019-01-16 11:49
@guicmazeredo Could you let me know if the problem keeps happening when you deactivate the Photon feature? 

Could you also copy the image HTML you can get from the browser console, and paste it here?

**Comment by guicmazeredo** [comment] 2019-01-16 12:42
Hey @jeherve ! I actually tested on a simple site so there is no way to deactivate Photon, right?

This is what I got on the Browser Console:

http://cld.wthms.co/0tqJa6

And this is the HTML code:

```
<div class="jp-carousel-slide selected" itemprop="associatedMedia" itemscope="" itemtype="https://schema.org/ImageObject" style="left: 0px; width: 405px; height: 225px; top: 40px; position: relative; transform: translate3d(538px, 0px, 0px);"><img src="https://azeredotest.files.wordpress.com/2019/01/13.jpg?resize=400%2C400&amp;w=720&amp;h=" itemprop="image" style="width: 100%; height: 100%;" width="720" height="400" srcset="https://azeredotest.files.wordpress.com/2019/01/13.jpg?resize=400%2C400&amp;w=720&amp;h=&amp;zoom=2 2x" src-orig="https://azeredotest.files.wordpress.com/2019/01/13.jpg?resize=400%2C400&amp;w=2000&amp;h=" scale="2"></div>
<img src="https://azeredotest.files.wordpress.com/2019/01/13.jpg?resize=400%2C400&amp;w=720&amp;h=" itemprop="image" style="width: 100%; height: 100%;" width="720" height="400" srcset="https://azeredotest.files.wordpress.com/2019/01/13.jpg?resize=400%2C400&amp;w=720&amp;h=&amp;zoom=2 2x" src-orig="https://azeredotest.files.wordpress.com/2019/01/13.jpg?resize=400%2C400&amp;w=2000&amp;h=" scale="2">
```

Since I'm not sure if that's what you were asking for I'm also leaving the test page a set up:

https://azeredotest.wordpress.com/tiled-gallery/

I also tested on an Atomic site to see just now to see if disabling the photon feature would sort it and I found a new issue. The Tiled Gallery block is not displaying a gallery on the live site. It's displaying a list of single images instead. You can check that here:

https://guiworknotes.blog/tiled-gallery/

And when clicking on images they won't open the carousel. I hope that helps! Let me know if you need anything else from me.

**Comment by lizswafford** [comment] 2019-01-16 16:05
Also reported on a simple site here: 9528222-hc

**Comment by sirreal** [comment] 2019-01-17 10:57
1723608-zen may be another example of this

**Comment by jeherve** [comment] 2019-01-17 16:43
Thanks for the extra details. The problem appears to be limited to WordPress.com simple sites in my tests. This is odd since the Carousel files are in sync.

@guicmazeredo Does this happen if you try to insert a squared tiled gallery in a classic block on a wpcom simple site?

> I also tested on an Atomic site to see just now to see if disabling the photon feature would sort it and I found a new issue.  

I can't seem to reproduce the issue on my own Atomic site. Could you tell me more about how you created the gallery? Did you use a specific gallery block style?

**Comment by jeherve** [comment] 2019-01-18 11:06
> No. The regular squared gallery on a classic block works fine. 

@sirreal Sounds like we are back to the Tiled Gallery block; it seems linked to the markup used on WordPress.com sites, and the image resize implementation there maybe?

**Comment by sirreal** [comment] 2019-01-22 21:22
I'll see if I can find the cause of this in the next few weeks.

**Comment by sirreal** [comment] 2019-02-04 16:50
I've been unable to reproduce this.

In the testing instructions, this is unclear:

> 1. Add a Tilled Gallery to a page or post with a few images.
> 1. Convert the block style to Square Tiles.

Should the first step be a _Gallery_ block, which you convert to a _Tiled Gallery_ block?

**Comment by retnonindya** [comment] 2019-03-06 10:13
Reported here: 10974687-hc

**Comment by GeoJunkie** [comment] 2019-03-07 15:42
> Reported here: 10974687-hc. Simple site. Happened on pictures with square size.

This user came back in 1856577-zen with more details on what was going on. I did notice they seemed to be switching back and forth between Classic and Gutenberg modes, which may be having an impact.

**Comment by KentFack** [comment] 2019-03-11 17:01
I am experiencing this on Galleries on a self-hosted WordPress site, running the Twenty-Nineteen theme.

**Comment by susanjanec** [comment] 2019-03-27 14:21
This seems to be happening when using the Circle style as reported by user here: 1911588-zen
Simple site.

The user is reporting that some images are being stretched out and parts are cut off on the sides or at the bottom.

I also tested this on my own test site, tried the Circle Style and Square style and some of the images appear to stretch out and appear distorted: https://susanjanewptestsite12345.blog/gallery-2/

**Comment by sirreal** [comment] 2019-04-17 16:09
Observed the issue: pYGoO-Oh-p2

**Comment by wynwin** [comment] 2019-04-23 16:19
Another report here: 12289276-hc

**Comment by jeherve** [comment] 2019-04-24 19:39
Another report in #12148

**Comment by simison** [comment] 2019-04-30 08:36
another in https://github.com/Automattic/jetpack/issues/12200

**Comment by fresatomica** [comment] 2019-05-09 13:54
Another report in #12672170-hc. Here, however, the issue affects the images in general: https://stiviaggi.com/2019/04/24/viaggio-in-sicilia-orientale-una-settimana-meravigliosa-tra-catania-siracusa-e-val-di-noto/

**Comment by sirreal** [comment] 2019-05-09 13:58
@fresatomica This one appears to be a classic Tiled Gallery, not the Tiled Gallery block. That may be a different issue.

> Another report in #[12672170-hc](https://href.li/?https://mc.a8c.com/support-stats/happychat/transcript.php?id=12672170).

**Comment by damiannep** [comment] 2019-05-09 14:09
I have a similar issue in #2019313-zen. In this case, the image seems to be distorted in the square tiles gallery but okay in the slideshow.

**Comment by juliasydnor** [comment] 2019-05-09 22:08
@sirreal I think it may still be the same issue. I was able to reproduce only on WP.com simple sites, like @jeherve mentioned above (but in either editor). The behaviour seems to be exactly the same - square tiled galleries are squished instead of cropped. Perhaps it's a JP issue rather than Gutenberg?

Simple site: https://cld.wthms.co/hJ6Ibm
vs
Self-hosted site: https://cld.wthms.co/OvFX7Z

**Comment by damiannep** [comment] 2019-05-10 06:08
@juliasydnor There is an issue for this posted at #7861-wpcom.

**Comment by sirreal** [comment] 2019-05-10 07:08
@juliasydnor Yes, the issue here will likely be with the carousel and not with any of the galleries.

**Comment by Robertght** [comment] 2019-05-12 06:45
I tested https://github.com/Automattic/wp-calypso/issues/32936 and it worked well for me in the new editor, but not in the Classic one. Thoughts?

**Comment by rickmgithub** [comment] 2019-05-17 19:04
New example here - #2038233-zd

User is using a classic block in Gutenberg on a simple (premium) site.

The images appear correctly in the editor but not when published.

**Comment by katinthehatsite** [comment] 2019-05-17 19:09
Similar issue in 2035382-zen

<img width="1353" alt="Screen Shot 2019-05-17 at 3 08 05 PM" src="https://user-images.githubusercontent.com/25575134/57950569-a7bb6280-78b5-11e9-906f-bb712fd241a3.png">

The user has a classic block with the gallery in it and is using Gutenberg now.

**Comment by aleone89** [comment] 2019-05-23 07:59
Reported on zen-2034112

**Comment by Praful** [comment] 2019-05-24 15:41
I have the same issue in the carousel. The issue seems to be that if the photo is one orientation (say, landscape) but the jpg properties say rotate 90 deg (ie the photo is really portrait), the carousel works out the dimension of the photo based on the original landscape orientation then rotates and stretches the photo. For an example, see [here](https://prafulkapadia.com/2019/03/29/wandering-around-berlin/). There are three images in the tiled view that should be portrait but the tiled gallery shows them as landscape. When viewed in the carousel, they're rotated (correctly) then stretched (incorrectly).

**Comment by jamiepalatnik** [comment] 2019-05-27 23:21
Also reported in 3337490-hc. Images in carousel display normally when Tiled Mosaic layout is selected, but appear stretched and distorted in the carousel when Circles layout is selected.

**Comment by eduardozulian** [comment] 2019-06-27 19:48
Another report on 2132588-zen. Recommended the user to change to the Mosaic Tiled Gallery for now.

**Comment by eduardozulian** [comment] 2019-06-27 20:07
While yet there isn't a fix, it's possible to use CSS to mitigate the issue:

```
/* Gallery Carousel stretch images workaround */
.jp-carousel-slide img {
	object-fit: contain;
}
```

Before and after images below:

![before (1)](https://user-images.githubusercontent.com/1136160/60297156-fff67300-98fd-11e9-852c-18c4f08ef7f8.png)
![after (1)](https://user-images.githubusercontent.com/1136160/60297172-0684ea80-98fe-11e9-9396-bb600f319ea3.png)

**Comment by ashercantrell** [comment] 2019-07-09 22:25
Encountered the same issue in HC-10378444 with the Circle Tiles style. I switched it to Mosaic instead and the carousel works okay. User has Personal, so CSS isn't an option.

**Comment by mikeicode** [comment] 2019-07-10 10:47
Another case on 13790361-hc

Through testing I found this only happens on Simple sites. On AT sites the full size image is opened in the carousel, on Simple sites the same square image is opened (when using the Square or Circle styles) which results in the distorted image.

AT Site opens correct image:

![img](https://d.pr/Dv8XPw+)

Simple opens the square version (and it is stretched):

![img](https://d.pr/FHkIYP+)

**Comment by carinapilar** [comment] 2019-07-29 19:20
I had this issue on a personal site, it was an Atomic site using the Tiled Gallery block and the Tiled Mosaic style.

Even though the images were showing in the right orientation when editing the page and on the site, the ones that were having this behavior were with the wrong orientation when checking the media library **on WP-Admin**.

Here's how it shows on the carousel:

![Screen Shot 2019-07-29 at 16 12 17](https://user-images.githubusercontent.com/16104522/62075523-b1e5cf80-b21b-11e9-8b3e-7d9846f08508.png)

And how it shows on WP-Admin:

![Image](https://user-images.githubusercontent.com/16104522/62075535-ba3e0a80-b21b-11e9-9cf9-23940dae61e1.png)

After I fixed the orientation on WP-Admin, the carousel started showing the image correctly. Original image size orientation is "Rotate 90 CW".

Although it's an AT site, it seems a similar issue, but please, let me know if it's not or should be reported elsewhere.

**Comment by sirreal** [comment] 2019-09-14 18:38
Changes in D27606-code may help inform the fix.

**Comment by KokkieH** [comment] 2019-09-23 05:15
Another report in https://en.forums.wordpress.com/topic/jetpack-gallery-block-distorted-images/

**Comment by khristiansnyder** [comment] 2019-09-25 16:52
Another in 15489796-hc

**Comment by mikeicode** [comment] 2019-11-08 15:09
Another 16527124-hc

**Comment by kathrynwp** [comment] 2019-11-22 21:11
Another report in 16847412-hc

**Comment by michaeldcain** [comment] 2019-11-24 19:10
I ran into this issue on a simple site over the weekend and created a fix in D35881-code. Let me know if I can help apply that to Jetpack sites.

**Comment by simison** [comment] 2019-11-24 19:19
@michaeldcain you rock! Can you see the same file and code that you fixed in Jetpack, or are they out of sync?

@jeherve or @kraftbj would you be able to help to sync the fix back to Jetpack?

**Comment by michaeldcain** [comment] 2019-11-24 19:40
@simison: the file exists (jetpack-carousel.js), but the changes I made were grouped with some WPcom code. I had a hard time following the reports here, so didn't know if it was indeed a Jetpack issue, or just WPcom as @jeherve's [comment suggested](https://github.com/Automattic/jetpack/issues/11150#issuecomment-455242231).

I can take a look tomorrow on a Jetpack site and figure out a better fix if the issue exists there too.

**Comment by jeherve** [comment] 2019-11-25 08:58
We shouldn't have to sync anything here. The fix is contained within wpcom-only code (inside the `jetpack-carousel.js` file), so there is nothing to sync from r199844-wpcom.

Since all reports above are from simple sites, I think this can be closed now.

@michaeldcain Thanks for the fix!

**Closed by jeherve** 2019-11-25 08:58 UTC
Labels: Carousel, Gutenberg, Tiled Galleries, [Block] Tiled Gallery, [Type] Bug, [Type] Happiness Request
