### ISSUE TITLE
Dragging social items/icons from iPadPro not working

### ISSUE THREAD

**Issue by zetaraffix** [Automattic/jetpack#7360] opened 2017-06-18 06:45 UTC
Good morning,
working from an IPad, on the admin panel, the drag-dropping of available social nets for sharing doesn't work, touching the icons highlights text but doesn't trigger any action so icons can't be moved to the enableing area.

**Comment by zinigor** [comment] 2017-06-19 08:30
Thank you for reporting that problem! We'll try to take a look at it, and meanwhile you can set up your sharing buttons the way you want them by using WordPress.com. If your Jetpack instance is connected, you can open WordPress.com, then:
- go to "My Sites",
- click "Switch site" and select the site you need to set up,
- click "Sharing" in the left sidebar,
- follow the instructions on the screen.

**Comment by jeherve** [comment] 2017-09-07 11:07
Closing as duplicate of #141. Since we now focus our efforts on the new interface available under Jetpack > Settings and on WordPress.com, I'd recommend using those screens to manage your Jetpack settings from an iPad.

**Closed by jeherve** 2017-09-07 11:07 UTC
Labels: Sharing, [Type] Bug
