### ISSUE TITLE
Concatenated jetpack.css should only include CSS for active modules

### ISSUE THREAD

**Issue by joendotcom** [Automattic/jetpack#7656] opened 2017-08-18 13:40 UTC
From https://developer.jetpack.com/hooks/jetpack_implode_frontend_css/ :
> Instead of including a separate CSS file for each Jetpack feature, Jetpack enqueues only one file, built by concatenating all CSS from all Jetpack features. This limit the number of requests made when loading a site.

However, the CSS file could be a lot more compact by only including the CSS for modules in use.

#### Steps to reproduce the issue

Note: To test this, set up a Jetpack with *only* Subscriptions module enabled and make sure to add the Blog Subscriptions widget.

1. Load Jetpack site and check network console. A ~12KB jetpack.css file will be loaded.

<img width="715" alt="screen shot 2017-08-18 at 15 33 36" src="https://user-images.githubusercontent.com/8905369/29461177-0357288a-842b-11e7-9c2f-85c91deebecf.png">

2. Add the filter `add_filter( 'jetpack_implode_frontend_css', '__return_false' );` 

3. Load Jetpack site and check network console. A ~307B subscriptons.css file will be loaded:
<img width="896" alt="screen shot 2017-08-18 at 15 35 08" src="https://user-images.githubusercontent.com/8905369/29461180-07b2f526-842b-11e7-9515-b8fe2afa94d2.png">

#### What I expected

Jetpack only includes CSS for active modules

#### What happened instead

Jetpack includes all CSS.

Ref: 636984-zen

**Comment by kraftbj** [comment] 2017-08-18 13:47
I'm on the fence of considering this as a duplicate of https://github.com/Automattic/jetpack/issues/1258 .

I believe at the time of implementation, working on-the-fly concatenation provided a performance hit for typical installs vs the one file approach.

The feature is probably due, at some point, for a refactor, namely after one of the major servers start offering server push on HTTP2, since individual files would be better in those cases, etc.

**Comment by georgestephanis** [comment] 2017-08-18 13:52
I think this is a "PRs Welcome" issue.  I'd love to only serve up the relevant modules, maybe storing a cached concatenated css file in the uploads directory somewhere?

**Comment by georgestephanis** [comment] 2017-08-18 13:54
Incidentally, it doesnt include all css, just those we decided are worth the tradeoff -- small or common ones to save on http requests and connections.

**Comment by joendotcom** [comment] 2017-08-18 14:08
@kraftbj
> I'm on the fence of considering this as a duplicate of #1258 .
Apologies, I misread that issue as closed. Certainly related.

**Comment by kraftbj** [comment] 2017-08-18 15:20
> maybe storing a cached concatenated css file in the uploads directory somewhere?

Yeah, maybe something like:
1. have an option set if a custom file is done (created and verified it exists)
2. if the option is not set, use jetpack.css as is or just implode false, kick off a cron job to build it in the background set the option.
3. when a module/feature setting is changed, delete the option and queue up a cron job.

**Comment by htdat** [comment] 2017-08-25 10:25
Another user reports the same issue with Contact Form module: 
* Disable Contact Form module. 
* Jetpack CSS file still loads the styles for this module and override the user's contact forms style.

Ref: 650030-zen

**Comment by tannerchung** [comment] 2017-08-26 06:36
> Another user reports the same issue with Contact Form module:

Yes that was me! I have to turn off Jetpack completely in order to avoid having the Contact Form affecting the current contact form I have. This is adversely affecting business since I'm also offering clients free personal Jetpack subscriptions, namely the 30 day backups and Photon CDN, but now I cannot promise this to them and I'm worried similar situations like this will happen in the future.

**Comment by kraftbj** [comment] 2017-08-28 17:28
Hi @tannerchung - you can add the `add_filter( 'jetpack_implode_frontend_css', '__return_false' );` via your theme's functions.php file or a core functionality plugin to disable jetpack.css, which will only load individual module CSS files.

**Comment by jeherve** [comment] 2017-09-08 13:19
> I'm on the fence of considering this as a duplicate of #1258 .

I'm going to go ahead and close as duplicate. I agree they're similar.

**Closed by jeherve** 2017-09-08 13:19 UTC
Labels: Performance, [Pri] Normal, [Type] Enhancement
