### ISSUE TITLE
Automatically activate VideoPress when a user intends to upload videos.

### ISSUE THREAD

**Issue by zinigor** [Automattic/jetpack#9184] opened 2018-03-29 13:47 UTC
Currently the prompt to use VideoPress only activates the module, while it could prompt for a new video upload. cc @keoshi 

#### Steps to reproduce the issue
> Had to click the “Activate Video Hosting” and then “Upload Videos Now”. Can’t we make that one click only? The only other setting I could find that does this is Google Analytics. Why wouldn’t we want to auto-activate when someone clicks “Upload Videos Now” from the plans page?

**Comment by kraftbj** [comment] 2018-03-29 13:59
Duplicate of https://github.com/Automattic/jetpack/issues/7362

**Comment by keoshi** [comment] 2018-03-29 14:21
This is not really a duplicate. If #7362 is closed then this will be obsolete, but until then this is a smaller fix for a button in the plans page when there's explicit user intent to upload videos.

**Comment by jeherve** [comment] 2021-12-03 15:17
I think this was fixed as we made changes to the settings UI in the past year. Closing

**Closed by jeherve** 2021-12-03 15:17 UTC
Labels: [Type] Enhancement, VideoPress, FixTheFlows
