### ISSUE TITLE
Testimonials: Still Active After Disabling Custom Content Type Module

### ISSUE THREAD

**Issue by philiparthurmoore** [Automattic/jetpack#2890] opened 2015-10-24 13:20 UTC
Steps to reproduce:
1. Turn on Custom Content Types
2. Turn on Testimonials under writing settings page.
3. Add a Testimonial
4. Turn off Custom Content Types
5. Testimonials still show in the sidebar and there does not appear to be a way to get rid of it unless I turn Custom Content Types back on and disable Testimonials from the writing settings page, and then turn 
   Custom Content Types back off.

https://cloudup.com/cat4Lv_bBiS

Suggested fix: make sure that Testimonials and Portfolios get turned off on module deactivation to avoid this confusion.

**Comment by kraftbj** [comment] 2015-10-24 13:38
Without checking out the code yet: either that or check for module activation in addition to simply the setting. If both aren't true, then don't include the CPT.

**Comment by philiparthurmoore** [comment] 2015-10-24 22:44
> either that or check for module activation in addition to simply the setting. If both aren't true, then don't include the CPT.

Even better.

**Comment by mrwweb** [comment] 2015-11-19 19:20
I can confirm this bug: https://wordpress.org/support/topic/testimonials-active-regardless-of-jetpack-custom-content-types-module?replies=1#post-7675546

**Comment by jeherve** [comment] 2015-11-20 15:59
@mrwweb I think the 2 issues are actually a bit different. I replied in #3044

**Comment by jeherve** [comment] 2015-11-20 16:04
Since there seems to be a bit of confusion, I'd like to clarify things a bit:

1. Testimonials and / or Portfolios should get unregistered when you go to Settings > Writing and uncheck the CPT box => that works. ✅
2. Testimonials and / or Portfolios should get unregistered when you deactivate the Custom Content Types module. => that doesn't work and we need to fix that. 🐛
3. Testimonials and / or Portfolios should not be registered if the Custom Content Types module is deactivated, regardless of any active theme features (like `add_theme_support( 'jetpack-testimonial' );`). Since the Custom Content Types module is on by default on every Jetpack installation, if someone went into the trouble of deactivating the module once, we should respect that setting. => that doesn't work and we need to fix that. 🐛

**Comment by cliffordp** [comment] 2015-12-29 13:29
> '2. Testimonials and / or Portfolios should get unregistered when you deactivate the Custom Content Types module. => that doesn't work and we need to fix that. 🐛

This is still happening on WP 4.4 and Jetpack 3.8.2. Should this issue be Open instead of Closed?

**Comment by cliffordp** [comment] 2015-12-29 13:33
Just chiming in to say this is still happening on WP 4.4 and Jetpack 3.8.2.

Thanks for working on it.

**Comment by eliorivero** [comment] 2015-12-29 13:39
@cliffordp this will be included in the upcoming 3.9 release. You can see the milestone (at the beginning of this issue, on the right side bar, below the labels) that this was/will be included in, which is directly related to the plugin version.

**Comment by jeherve** [comment] 2016-04-13 16:28
Also reported here:
https://wordpress.org/support/topic/custom-post-types-are-deactivated-but-testimonials-still-appear?replies=3&view=all#post-8272878

**Comment by dereksmart** [comment] 2018-02-23 13:53
This should no longer be an issue, as our UI shows specific toggles for each of the CPT's

**Closed by dereksmart** 2018-02-23 13:53 UTC
Labels: Custom Content Types, [Type] Bug
