### ISSUE TITLE
Masterbar: missing footer and linked help icon

### ISSUE THREAD

**Issue by designsimply** [Automattic/jetpack#7011] opened 2017-04-20 01:14 UTC
The Calypso My Sites menu has an a footer with a linked help icon and Jetpack Masterbar does not.

![screen shot 2017-04-19 at wed apr 19 6 58 05 pm](https://cloud.githubusercontent.com/assets/1119271/25208801/38d7f918-2534-11e7-9ceb-6ba4f1eb12cb.png)
<sup>Seen at https://wordpress.com/settings/general/alittletestblog.com and http://alittletestblog.com/wp-admin/options-general.php (click on My Sites) using Safari 10.1 on Mac OS X 10.12.4.</sup>

Tested with WordPress 4.7.3 and Jetpack Beta (Build 1736160) on WP Engine.

**Comment by jeherve** [comment] 2019-05-24 21:05
Reopening as the navigation drawers were added back in #12454

**Comment by jeherve** [comment] 2019-05-24 21:06
Closing as duplicate of #9098

**Closed by jeherve** 2019-05-24 21:06 UTC
Labels: Masterbar, [Pri] Normal, [Type] Bug, [Type] Duplicate
