### ISSUE TITLE
Podcast Player: Doesn't work in Preview (Calypso)

### ISSUE THREAD

**Issue by WunderBart** [Automattic/jetpack#15047] opened 2020-03-19 12:34 UTC
#### Steps to reproduce the issue

1. Go to `wordpress.com/pages/<yoursite.blog>` and edit one of your pages.
2. In the editor, add `Podcast Player` block to the page.
3. Use the https://anchor.fm/s/9400d7c/podcast/rss URL to initialize the Player.
4. Click `Preview` button in the top-right corner.
5. On the preview page, click one of Player's episodes.

#### What I expected
Podcast episode should start playing and it should be indicated on the Player's interface.

#### What happened instead
Link to the episode opened in a new tab as if the JS wasn't there. I couldn't see any error in the console.

**Comment by marekhrabe** [comment] 2020-03-27 14:33
For easier reproducing: this can be reproduced by opening any post or page on a wpcom simple site and adding `?preview=true&iframe=true`. No need to go though calypso and preview there.

I know the root cause, currently looking into it…

**Comment by marekhrabe** [comment] 2020-03-27 15:34
jetpack-iframe-preview.js is very likely responsible. It handles click on `document` and stops the propagation. Our React component never gets a chance to react to the event and thus the default link action happens - it opens the episode page. In a new tab because preview frames include `<base target="_blank" />`

We need to figure out how to make jetpack-iframe-preview compatible with this. I'm thinking about introducing some sort of data-attribute on the root of our player (like `jetpack-iframe-ignore`) which will make the JS in jetpack-iframe-preview.js ignore the click and let us handle it.

**Comment by marekhrabe** [comment] 2020-03-30 12:06
Fixed in D41067-code together with #15191.

**Closed** 2020-03-31 10:25 UTC
Labels: Gutenberg, [Block] Podcast Player, [Type] Bug
