### ISSUE TITLE
Gutenberg: og:image tag does not pick the image from blocks

### ISSUE THREAD

**Issue by htdat** [Automattic/jetpack#10501] opened 2018-11-01 08:47 UTC
#### Steps to reproduce the issue

Jetpack_PostImages:: from_html does not 
1. Create a post in Gutenberg
2. Add an existing image from Media Library to an image block. 
3. Save the post and view the HTML source of the post.
4. ERROR: `og:image` is using `https://s0.wp.com/i/blank.jpg`

If I add images through Classic Editor, there is no issue. 

#### What I expected

`og:image` should use the correct image. 

#### Debug more 

I notice the differences are `width` and `height` attributes of <img> tags when viewing the code editor: 

* Classic Editor - they do exist. 
* Gutenberg - they do not exist. 

By default, the image block looks like this - the `og:image` tag is picked wrongly with the steps above: 

```
<!-- wp:image {"id":139} -->
<figure class="wp-block-image"><img src="https://vu.hoangdat.blog/wp-content/uploads/2018/09/logo-1-768x767.jpg" alt="" class="wp-image-139"/></figure>
<!-- /wp:image -->
```

If I "hack" a bit and add `width` and `height` attributes - the `og:image` tag is picked correctly. 

```
<!-- wp:image {"id":139} -->
<figure class="wp-block-image"><img src="https://vu.hoangdat.blog/wp-content/uploads/2018/09/logo-1-768x767.jpg" alt="" class="wp-image-139"/></figure>
<!-- /wp:image -->
``` 

### My testing enviroment

* WP 4.9.8
* JP 6.6.1, Release Candidate, Bleeding Edge
* Gutenberg 4.1.1 

#### Possible Code 

From https://github.com/Automattic/jetpack/blob/5a51ff2eed23ef4ff22f0d2e2f985d33eb413e1d/functions.opengraph.php#L169

>		$image_info       = jetpack_og_get_image( $image_width, $image_height );

Then https://github.com/Automattic/jetpack/blob/5a51ff2eed23ef4ff22f0d2e2f985d33eb413e1d/functions.opengraph.php#L289

> 			$post_images = Jetpack_PostImages::get_images( get_the_ID(), array( 'width' => $width, 'height' => $height ) );

Then https://github.com/Automattic/jetpack/blob/51afab4639c4c5419d8eb99605fd4afb483aff57/class.jetpack-post-images.php#L381-L384

```
			$meta = array(
				'width'  => (int) $image_tag->getAttribute( 'width' ),
				'height' => (int) $image_tag->getAttribute( 'height' ),
			);

```

**Comment by htdat** [comment] 2018-11-01 08:48
ticket: 1528871-zen 

I am using `[Pri] High` as we're using Jetpack_PostImages in many places in Jetpack.

**Comment by simison** [comment] 2018-11-01 11:09
This is because of Gutenberg outputting image HTML without width/height attributes:

```html
<!-- wp:image {"id":77} -->
<figure class="wp-block-image"><img src="http://localhost/wp-content/uploads/2018/10/example.png" alt="" class="wp-image-77"/></figure>
<!-- /wp:image -->
```

Image tags without width/height are ignored:

https://github.com/Automattic/jetpack/blob/7ce8c1a76257cde38e7372da992e2bc8ca3604f2/class.jetpack-post-images.php#L398-L409

The solution could pick ID from `{"id":77}` or `wp-image-77`, load media object and use that as OG image.

**Comment by jeherve** [comment] 2018-11-01 11:29
This is a duplicate of this issue:
#10007

See my comment there for a detailed answer and a link to a Gutenberg PR that should solve the issue:
https://github.com/Automattic/jetpack/issues/10007#issuecomment-423178318

Since there was no movement on that PR, maybe we should consider disabling our size checks for posts created with Gutenberg.

**Comment by simison** [comment] 2018-11-01 11:31
> Since there was no movement on that PR, maybe we should consider disabling our size checks for posts created with Gutenberg.

This sounds good. Suppose FB won't penalize if we send smaller than 200px, it just won't pick it up.

**Comment by kraftbj** [comment] 2018-11-01 13:42
> This sounds good. Suppose FB won't penalize if we send smaller than 200px, it just won't pick it up.

It may because of Publicize. Since we have accounted for it, I haven't tried recently, but generally, if there are issues with the OG tags, Publicize will fail.

**Comment by kristarella** [comment] 2018-11-02 00:31
> The solution could be to pick media ID from {"id":77} or wp-image-77, load media object and use that as an OG image.

This seems potentially more robust, since you can check the width of the image in the database rather than just the width that is set in the post itself. If the image in the post is < 200px, but the original is larger, the original could be used for `og:image`

**Comment by KokkieH** [comment] 2018-12-18 10:36
Noting we've had another user report of this [here](https://wordpress.org/support/topic/publicize-open-graph-ogimage-tag-wont-use-wp5-image-block-images/).

**Comment by annezazu** [comment] 2018-12-20 23:57
1638869-zen

**Comment by bikedorkjon** [comment] 2018-12-21 07:37
1638869-zen would like a response when we have a fix

**Comment by coder-karen** [comment] 2019-01-02 13:40
1682946-zen

**Closed** 2019-01-03 16:51 UTC
Labels: Gutenberg, Publicize, [Pri] High, [Type] Bug
