### ISSUE TITLE
Prefix upcoming events widget class

### ISSUE THREAD

**Issue by gareth-gillman** [Automattic/jetpack#6231] opened 2017-01-30 11:28 UTC
A client has an events based theme which also has a widget with the same class as the Jetpack upcoming events widget. This causes either JP to not activate due to a fatal error or it produces a php error rendering the site unusable (error is cannot redeclare class).

As far as I can tell, every other widget in JP is prefixed apart from this one, this won't cause issues in 99% of cases but unfortunately my client has a theme which is causing the 1%.

**Comment by jeherve** [comment] 2017-01-30 11:34
Closing as duplicate of #6145

@gareth-gillman If you'd like, you can use the snippet [here](https://github.com/Automattic/jetpack/issues/6145#issuecomment-274571861) on your client's site until the next Jetpack release, where the problem will be fixed.

**Closed by jeherve** 2017-01-30 11:34 UTC
