### ISSUE TITLE
404 missing widgets.wp.com SCSS assets in Edge console logs

### ISSUE THREAD

**Issue by ntwb** [Automattic/jetpack#4408] opened 2016-07-14 22:22 UTC
#### Steps to reproduce the issue

Open `/wp-admin` in WordPress 4.5.3 with Jetpack 4.1.1 in Microsoft Edge browser.

Right click any element in the dashboard and click "Inspect element" and switch to the developer tools "console" tab.

(Microsoft Edge 38.14372.0.0 Microsoft EdgeHTML 14.14372)

#### What I expected

To not see any 404 not found widgets.wp.com missing SCSS asset errors
#### What happened instead

The following 404 not found widgets.wp.com missing SCSS asset errors
```
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR)GET - https://widgets.wp.com/client/boot/stylesheets/style.scss
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR)GET - https://widgets.wp.com/client/boot/stylesheets/shared/reset.scss
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR)GET - https://widgets.wp.com/client/boot/stylesheets/shared/colors.scss
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR)GET - https://widgets.wp.com/client/boot/stylesheets/shared/typography.scss
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR)GET - https://widgets.wp.com/client/boot/stylesheets/shared/sizes.scss
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR)GET - https://widgets.wp.com/client/boot/stylesheets/shared/extends.scss
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR)GET - https://widgets.wp.com/client/boot/stylesheets/shared/animations.scss
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR)GET - https://widgets.wp.com/client/boot/stylesheets/shared/buttons.scss
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR)GET - https://widgets.wp.com/client/boot/stylesheets/shared/forms.scss
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR)GET - https://widgets.wp.com/client/boot/stylesheets/main.scss
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR)GET - https://widgets.wp.com/client/boot/stylesheets/block-user.scss
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR)GET - https://widgets.wp.com/client/boot/stylesheets/note-common.scss
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR)GET - https://widgets.wp.com/client/boot/stylesheets/actions.scss
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR)GET - https://widgets.wp.com/client/suggestions/styles.scss
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR)GET - https://widgets.wp.com/client/boot/stylesheets/spinner.scss
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR)GET - https://widgets.wp.com/client/boot/stylesheets/overlay-bars.scss
```

**Comment by jeherve** [comment] 2016-07-18 09:47
Thanks for the report. We're aware of the issue, and tracking it internally since this is related to the Notifications module, that gets loaded directly from WordPress.com.

Here are my notes from our internal ticket:

> This seems to be a standard MS Edge behaviour:
> 
> > The source map file will only be downloaded if you have source maps enabled and your dev tools open.
> 
> - http://stackoverflow.com/a/35151109/1045686
> - https://github.com/MaxCDN/bootstrap-cdn/issues/629
> 
> And the solution seems to be to remove all references to those files from the built files:
https://github.com/MaxCDN/bootstrap-cdn/issues/629#issuecomment-187481226
>
> While that's not really an issue for most people, it would clean things up for folks looking at developer tools in Edge, while on a Jetpack site or a WordPress.com site.

I'll close this issue as duplicate, but I'll let you know as soon as the problem is fixed.

**Closed by jeherve** 2016-07-18 09:47 UTC

**Comment by ntwb** [comment] 2016-07-18 11:05
That works for me @jeherve, great resources with those links and explains the sourcemaps issue, cheers for these 👍
