### ISSUE TITLE
Lock down the 'Email' sharing option to decrease utility to spammers.

### ISSUE THREAD

**Issue by georgestephanis** [Automattic/jetpack#448] opened 2014-04-04 20:27 UTC
https://github.com/Automattic/jetpack/blob/master/modules/sharedaddy/sharing-sources.php#L196-L324

It's possible to stuff too much data into the sender name.  Let's give the email sharing module a once over and add some sane limits.

[Update from @designsimply 4-Apr-2018]

Confirming this still appears to be an issue based on recent reports in the following summary:

* 2014-07-31 - WP Engine disables email sharing. (https://github.com/Automattic/jetpack/issues/448#issuecomment-50784872)
* 2014-09-23 - issue closed with: character limit, honeypot, uses Akismet (if enabled). (#1053)
* 2015-01-31 - WP Engine re-enables email sharing. (https://github.com/Automattic/jetpack/issues/448#issuecomment-72352961)
* 2016-11-04 - issue reopened. (https://github.com/Automattic/jetpack/issues/448#issuecomment-258566916)
* 2017-02-01 - 34sp.com host reports the problem. (3251872-t)
* 2017-06-08 - 1&1 host reports the problem. (3251872-t)
* 2017-06-26 - disabled email sharing as a default. (#7329)
* 2017-07-04 - latest public user report I could find via links above. (<a href="https://wordpress.org/support/topic/jetpack-sharing-email-can-be-abused-for-spam/page/3/#post-9283709">wporg forums</a>)
* 2017-11-01 - latest private user report noted on this issue. (767682-zen)

What to do with new issues reported where Akismet is confirmed enabled:

<blockquote>It would be more effective to post these tickets to the internal Akismet P2 for review.</blockquote>

Source: https://github.com/Automattic/jetpack/issues/448#issuecomment-294254795

**Comment by kraftbj** [comment] 2015-01-09 20:35
Per WP Engine support ticket 313781, this feature should be re-enabled on their platform "next week".

**Comment by boogah** [comment] 2015-01-12 21:09
Sorry about the delay on this! WPE had an internal code freeze over the holidays and this fix was deemed "non-critical". We're in the process of thawing out right now, but I'm doing everything I can to make this happen ASAP.

**Comment by richardmtl** [comment] 2015-01-27 16:57
@boogah Hi! We were wondering if this was enabled yet; could you let us know? Thanks!!

**Comment by boogah** [comment] 2015-01-27 17:00
@richardmtl It was supposed to go out as part of a deploy late last week. That deploy was halted and pushed back because of an issue with unrelated code during testing.

I'm really pushing hard to get this out ASAP. If we run into any other snags getting it out this week, I'll let you know!

**Comment by boogah** [comment] 2015-01-28 17:32
I'm sitting in an internal chat room where the change is supposed to go out today. If it doesn't, I'll make sure to drop an update here.

**Comment by boogah** [comment] 2015-01-29 01:34
The deploy had to be briefly halted, but is still running. I'm going to check back in on this in the morning and will update here once I know what's up.

**Comment by richardmtl** [comment] 2015-01-29 15:10
THanks @boogah !

**Comment by boogah** [comment] 2015-01-30 01:20
@richardmtl Here's where we are right now...

The phased deploy we've been running since Wednesday required some pretty intensive server-side jobs to be run. In some cases — depending on the size & scope of sites on the server — the server side jobs are running *very* slowly.

Because of how the deploy last week failed, we're actually okay with things taking a little longer. But this means that the rollout is **still** going. So we're breaking with our "No deploys on Friday" rule to monitor the most recent phase tonight, sniff out any potential issues — we're hopeful that there will be none — and finish the last little bit of this deploy tomorrow.

So what does this mean for Jetpack? Well, at this point the majority of our customers — outside of a large handful of accounts — should be able to use email sharing again without any issues.

As soon as we hit 100% on the deploy tomorrow, I'll update you one last time.

**Comment by richardmtl** [comment] 2015-01-31 18:16
Thanks for the update, @boogah ! There was no real rush for things on our end, it was more a matter of keeping tabs on where things are with this. I appreciate the candor! :)

**Comment by boogah** [comment] 2015-02-01 05:55
The deploy finished after I had left for the day on Friday, but it appears to be done now.

Let me know if you see anyone still reporting issues!

**Comment by paulprins** [comment] 2016-10-08 13:30
Sorry to reopen but when using Jetpack with Autoptimize this fix breaks. it is throwing an element not found error when the JS is loaded in the header and agregating inline JS. Not a major issue but there is a simple fix that can be implemented.

The fix is to wrap the javascript request in a jquery ready event handler ala:
`<script>jQuery( document ).ready( function(){ document.getElementById('jetpack-source_f_name').value = ''; });</script>`

This `.ready()` approach is used elsewhere in the same `sharedaddy/sharing-sources.php` file. Implementing this fix will resolve a number of fringe issues using sharedaddy.

**Comment by jeherve** [comment] 2016-10-10 11:35
@paulprins Thanks for the report. I created #5291 with your patch.

**Comment by jeherve** [comment] 2016-11-04 22:53
Reopening this, as it seems some spammers found a way around the honey pot.

Reported here:
https://wordpress.org/support/topic/spam-attack-by-jetpack-share-e-mail/

**Comment by jeherve** [comment] 2016-11-04 23:04
Another report here:
https://wordpress.org/support/topic/email-sharing-button-recaptcha/

**Comment by jeherve** [comment] 2016-11-05 12:30
Another report here:
https://wordpress.org/support/topic/jetpack-hacked/#post-8398136

**Comment by jeherve** [comment] 2016-11-05 12:32
Also reported here:
https://wordpress.org/support/topic/jetpack-sharing-email-can-be-abused-for-spam/#post-8160632

**Comment by jenhooks** [comment] 2016-11-07 21:18
Report here: 2903871-t

**Comment by alexjgustafson** [comment] 2016-11-10 19:24
2912663-t

**Comment by alexjgustafson** [comment] 2016-11-10 19:28
2906649-t

**Comment by grappler** [comment] 2017-01-27 09:17
I can open a seperate issue if need be but there is an issue with the JS snippet when jQuery is loaded in the footer.
`<script>jQuery( document ).ready( function(){ document.getElementById('jetpack-source_f_name').value = ''; });</script>`

It may be better to use `wp_add_inline_script()` instead where the dependency on jQuery can be defined.

**Comment by jeherve** [comment] 2017-01-27 10:46
@grappler This issue is logged in #1223

**Comment by richardmtl** [comment] 2017-02-01 15:47
Report from a host (with log details) in 3038290-t

**Comment by chaselivingston** [comment] 2017-02-01 19:43
More share by email spam reported in 3035121-t

**Comment by csonnek** [comment] 2017-02-21 15:14
Also happening in 3070308-t

**Comment by kraftbj** [comment] 2017-04-12 22:31
3152833-t with over 12k emails in a month. For users who are offloading SMTP to a service like SendGrid, this is costing our customers/users real money.

**Comment by macmanx2** [comment] 2017-04-14 21:12
Also reported in 3162551-t, "the spam emails are causing us to hit our website database’s query limit, then I’m boxed out for 1-2 hours until my query limit resets. I only get a few minutes of digging and investigating in before the site (and my wp-admin access) is suspended again."

**Comment by cfinke** [comment] 2017-04-14 23:23
If the sharing module is passing these to Akismet (as it appears to be, based on the code), and spammers still aren't being caught, it would be more effective to post these tickets to the internal Akismet P2 for review.

**Comment by kraftbj** [comment] 2017-04-17 16:03
AK would only be used on sites with AK enabled and on a plan, so not sure if that's enough globally. I'll check with my ticket above if they're using AK and get info for you @cfinke if applicable.

**Comment by richardmtl** [comment] 2017-05-09 15:54
> We used the share buttons option on our website, but yesterday this part was
hacked. We received hundreds of emails on our server which were sent through the
share buttons option of the Jetpack plugin

3203234-t

**Comment by aheckler** [comment] 2017-05-30 14:08
3235509-t

**Comment by lamdayap** [comment] 2017-06-08 14:30
two reports here:

https://wordpress.org/support/topic/jetpack-sharing-email-can-be-abused-for-spam/page/3/#post-9205849
https://wordpress.org/support/topic/jetpack-sharing-email-can-be-abused-for-spam/page/3/#post-9206841

**Comment by csonnek** [comment] 2017-06-08 16:00
Requested here: 3251872-t

**Comment by lamdayap** [comment] 2017-06-16 14:45
reported again here: https://wordpress.org/support/topic/jetpack-sharing-email-can-be-abused-for-spam/page/3/#post-9229524

User included their findings.

**Comment by lamdayap** [comment] 2017-06-26 09:21
reported here: https://wordpress.org/support/topic/email-share-button-abused-for-spamming/

**Comment by rickybanister** [comment] 2017-06-28 16:31
also 3291588-t

**Comment by kraftbj** [comment] 2017-06-28 16:41
NB: As of JP 5.1, E-Mail Sharing will be disabled unless Akismet is active or the site owner specifically adds it via a filter.

**Comment by aheckler** [comment] 2017-08-28 14:01
A report of this in 649683-zen, but user has disabled Email sharing button and has Akismet installed. Digging for more info.

**Comment by richardmtl** [comment] 2017-11-01 15:54
in 767682-zen the user does not have Akismet yet they said they were having spam sent from the email button. Digging some more.

**Comment by designsimply** [comment] 2018-04-04 23:11
#bug-scrub

I tested email sharing with the following steps on a site hosted at WP Engine running WordPress 4.9.5 and Jetpack 6.0:

1. Go to WP Admin > Jetpack > Settings > Sharing > Sharing buttons > "Configure your sharing buttons".
1. Click "Edit sharing buttons".
1. Add the email sharing option and save changes.
1. Open a post on the front-end or a page on the site where social sharing buttons are displayed.
1. Try sending a post via the email social sharing button.

<strong>Result:</strong> I was able to share via email normally. There is no reCaptcha (but I understand that may be something I would need to install separately). I am not sure what else to check/report beyond this in terms of testing steps 🙂 and I may turn off email sharing since it is a known risk for spam (but would be happy to test further with more guidance about what to look for!).

**Comment by designsimply** [comment] 2018-04-04 23:14
Confirming this still appears to be an issue based on recent reports in the following summary:

* 2014-07-31 - WP Engine disables email sharing. (https://github.com/Automattic/jetpack/issues/448#issuecomment-50784872)
* 2014-09-23 - issue closed with: character limit, honeypot, uses Akismet (if enabled). (#1053)
* 2015-01-31 - WP Engine re-enables email sharing. (https://github.com/Automattic/jetpack/issues/448#issuecomment-72352961)
* 2016-11-04 - issue reopened. (https://github.com/Automattic/jetpack/issues/448#issuecomment-258566916)
* 2017-02-01 - 34sp.com host reports the problem. (3251872-t)
* 2017-06-08 - 1&1 host reports the problem. (3251872-t)
* 2017-06-26 - disabled email sharing as a default. (#7329)
* 2017-07-04 - latest public user report I could find via links above. (<a href="https://wordpress.org/support/topic/jetpack-sharing-email-can-be-abused-for-spam/page/3/#post-9283709">wporg forums</a>)
* 2017-11-01 - latest private user report noted on this issue. (767682-zen)

What to do with new issues reported where Akismet is confirmed enabled:

<blockquote>It would be more effective to post these tickets to the internal Akismet P2 for review.</blockquote>

Source: https://github.com/Automattic/jetpack/issues/448#issuecomment-294254795

**Comment by jeherve** [comment] 2018-04-05 08:58
> There is no reCaptcha (but I understand that may be something I would need to install separately)

Yes, here is how:
https://jetpack.com/support/sharing/#captcha

>  I am not sure what else to check/report beyond this in terms of testing steps

There is not much you can test for, short of looking at your logs for repeated direct requests to `?share=email&nb=1`, and outgoing emails.

**Comment by brbrr** [comment] 2018-06-29 09:04
Fixed in #9585

**Closed by brbrr** 2018-06-29 09:04 UTC
Labels: Sharing, [Pri] High, [Type] Bug
