### ISSUE TITLE
Comment Subscriptions: make post type filterable

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/jetpack#7594] opened 2017-08-04 18:58 UTC
Currently, the 'Subscribe to Comments' checkbox on appears for post_type=post.

We should allow for other types of posts to show it.

**Comment by jeherve** [comment] 2017-09-07 19:34
Related: #760

**Comment by jeherve** [comment] 2018-09-04 16:37
Closing as duplicate of #760

**Closed by jeherve** 2018-09-04 16:37 UTC
Labels: Subscriptions, [Type] Duplicate, [Type] Enhancement
