### ISSUE TITLE
Contact Form block: Form is removed on refreshing the page

### ISSUE THREAD

**Issue by yashitamittal11** [Automattic/jetpack#13279] opened 2019-08-21 04:55 UTC
#### Steps to reproduce the issue

1. Add a form block to a post/page on simple or AT site
2. Make some changes to the form and publish the page 
3. Refresh the page again
4. See error: The _Add Form_ button is displayed again. The user does not see the actual form and has to add the form again and again

The user can see the form on the frontend but it does not show on the backend.

#### What I expected
I expected to see the contact form added to the page/post on refreshing the page

#### What happened instead
The contact form displayed a button to add the form again on refreshing the page

**Screenshots**
![screenshot](https://d.pr/ooo75i+)

ZD: #2290075-zen

**Comment by jeherve** [comment] 2019-08-21 09:39
Closing as duplicate of #12286

**Closed** 2019-08-22 08:42 UTC
Labels: Contact Form, [Type] Duplicate
