### ISSUE TITLE
Boost: Pricing tables out of sync

### ISSUE THREAD

**Issue by haqadn** [Automattic/jetpack#37207] opened 2024-05-03 12:02 UTC
The pricing tables from my Jetpack vs the one in Boost do not match.

Ideally they should be sharing the component so they are never out of sync.

![Image](https://github.com/Automattic/jetpack/assets/3737780/d493007b-7e7d-4f5b-913b-b5ef12b787a6)
![Image](https://github.com/Automattic/jetpack/assets/3737780/f85c585a-b849-4dab-8b01-695793bbe216)

**Comment by dilirity** [comment] 2024-10-31 10:10
This was already resolved in https://github.com/Automattic/jetpack/pull/39130.

It's also a duplicate of https://github.com/Automattic/jetpack/issues/38947.

**Closed as completed by dilirity** 2024-10-31 10:10 UTC
Labels: [Plugin] Boost
