### ISSUE TITLE
Module Overrides: Allow a custom reason to be set.

### ISSUE THREAD

**Issue by pablinos** [Automattic/jetpack#20150] opened 2021-06-23 11:04 UTC
#### Is your feature request related to a problem? Please describe.

Whilst working on a problem related to VideoPress, there was an issue where the module toggle was being disabled by some custom JS. It turned out this was related to the private site feature on WordPress.com. Only the UI was being disabled rather than the module being completely removed because otherwise the feature was displayed on the My Plan screen of the dashboard.

The modules were being disabled as they were features that couldn't be used while the site was private, but the message was quite generic.

<img width="281" alt="image" src="https://user-images.githubusercontent.com/96462/123085874-a8bb0880-d41a-11eb-8028-28c659571575.png">

#### Describe the solution you'd like

I'd like the ability to be able to add a reason for the override, that would be displayed instead. Having a message like "This feature can't be enabled while your site is private" or "This feature conflicts with 'Amazing SEO Plugin'" would help let people know why, and what they would need to do in order to enable it.

**Comment by jeherve** [comment] 2021-06-23 14:05
Closing as duplicate of #12491.

**Closed by jeherve** 2021-06-23 14:05 UTC
Labels: [Block] VideoPress, [Type] Enhancement

**Comment by pablinos** [comment] 2021-06-23 14:48
Thanks @jeherve! I obviously didn't search hard enough for similar issues, sorry about that.

**Comment by jeherve** [comment] 2021-06-23 14:55
No worries! We have A LOT of issues in here :)
