### ISSUE TITLE
Compatibility: WooCommerce product editing broken with Advanced Schedule Posts.

### ISSUE THREAD

**Issue by zinigor** [Automattic/jetpack#34188] opened 2023-11-17 17:07 UTC
### Impacted plugin

Jetpack

### Quick summary

Editing WooCommerce products is broken when Jetpack is installed together with WooCommerce and [Advanced Schedule Posts](https://wordpress.org/plugins/advanced-schedule-posts/). Clicking "Edit" brings up a form with an empty product titled "AUTO-DRAFT".

### Steps to reproduce

1. Set up a testing site with Jetpack and WooCommerce.
2. Activate Jetpack, connect to WordPress.com.
3. Set up WooCommerce up to the point where you have at least one product.
4. Activate Advanced Schedule Posts.
5. Go to the Products page listing all available products.
6. Click "Edit" next to any product in the list.

### A clear and concise description of what you expected to happen.

I expected the editor to be pre-filled with the product details, as usually happens when editing.

### What actually happened

An empty product is displayed with the title "AUTO-DRAFT".

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic, Self-hosted

**Comment by liviopv** [comment] 2023-11-18 13:48
📌 REPRODUCTION RESULTS
- Tested on Atomic – Replicated
 
📌 FINDINGS/SCREENSHOTS/VIDEO
Atomic site, WooCommerce 8.3, Jetpack 12.9-a.1, Advanced Scheduled Posts 2.1.8

![CleanShot 2023-11-18 at 14 42 26@2x](https://github.com/Automattic/jetpack/assets/14153300/a8713f81-a77e-4f13-9092-fd24023a6c4a)


📌 ACTIONS
- Closed as this is a plugin conflict that needs to be fixed by Advanced Scheduled Posts

📌 Message to Author
@zinigor I'm closing this one because it's not something that would be fixed by an a8c team. You can try to reach out to the plugin developer at https://wordpress.org/support/plugin/advanced-schedule-posts/

The plugin you're using was last updated 2 years ago, it sounds like it was abandoned by the developer. It might be good to consider a different plugin.

**Closed as completed by liviopv** 2023-11-18 13:48 UTC
Labels: Bug, [Pri] High, [Plugin] Jetpack, [Platform] Atomic, Needs triage, [Status] Priority Review Triggered
