### ISSUE TITLE
Payment Blocks: Premium content block displays buttons incorrectly on the editor

### ISSUE THREAD

**Issue by rcrdortiz** [Automattic/jetpack#26632] opened 2022-10-05 08:19 UTC
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Edit or create a post
2. Add a premium content block.

### A clear and concise description of what you expected to happen.

I expected the **Subscribe** and **Log in** button to be on the same row

### What actually happened

The **Subscribe** and **Log in** buttons are on different rows.

### Browser

Google Chrome/Chromium

### Other information

This is how it currently looks like
![Captura de Pantalla 2022-10-05 a las 10 13 03](https://user-images.githubusercontent.com/1989914/194014217-9fb2e349-1ba6-45e3-b318-cdea5d431991.png)

### Reproducibility

Consistent

### Severity

All

**Comment by dsas** [comment] 2022-10-05 08:25
Not sure if something has changed so this now happens, but it might just be related to this: https://github.com/Automattic/jetpack/blob/fc9d9978a70a443c00823899bd02256ed136c4e4/projects/plugins/jetpack/extensions/blocks/recurring-payments/editor.scss#L4-L6

**Comment by Copons** [comment] 2022-12-08 10:42
Closing as duplicate of https://github.com/Automattic/wp-calypso/issues/66639

**Closed as not planned by Copons** 2022-12-08 10:42 UTC
Labels: Bug, [Block] Payment Button, [Block] Paid Content, [Plugin] Jetpack
