### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined method stdClass::exists

### ISSUE THREAD

**Issue by oempire** [Automattic/jetpack#8200] opened 2017-11-17 09:12 UTC
#### Steps to reproduce the issue

showing in debug log, after the latest lot of updates (havent updated to WP 4.9 yet)

```
[16-Nov-2017 04:23:44 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method stdClass::exists() in /var/www/mmedu.com/public_html/wp-includes/capabilities.php:620
Stack trace:
#0 /var/www/mmedu.com/public_html/wp-includes/functions.php(2554): user_can(Object(stdClass), 'unfiltered_html')
#1 /var/www/mmedu.com/public_html/wp-content/plugins/jetpack/sync/class.jetpack-sync-module-users.php(90): get_allowed_mime_types(Object(stdClass))
#2 /var/www/mmedu.com/public_html/wp-content/plugins/jetpack/sync/class.jetpack-sync-module-users.php(117): Jetpack_Sync_Module_Users->add_to_user(Object(stdClass))
#3 /var/www/mmedu.com/public_html/wp-includes/class-wp-hook.php(298): Jetpack_Sync_Module_Users->expand_user(Array, 1)
#4 /var/www/mmedu.com/public_html/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array)
#5 /var/www/mmedu.com/public_html/wp-content/plugins/jetpack/sync/class.jetpack-sync-sender.php(148): apply_filters('jetpack_sync_be...', Array, 1)
#6 /var/www/mmedu.com/public_html/w in /var/www/mmedu.com/public_html/wp-includes/capabilities.php on line 620`
```

**Comment by zinigor** [comment] 2017-11-17 13:19
cc @lezama it looks like instead of the `WP_User` the filter gets called with a `stdClass` object. Do you have any idea how that could happen? Custom filters, plugins or theme functionality?

**Comment by lezama** [comment] 2017-11-17 15:26
@enejb could you give this a check?

**Comment by gititon** [comment] 2017-11-17 20:22
Hi @oempire, I'll be looking into this for you. 

Can you please let me know the steps you took on your site that resulted in this stack trace / error so that I can attempt to reproduce it? Thanks in advance!

**Comment by enejb** [comment] 2017-11-17 21:34
I wonder if https://github.com/Automattic/jetpack/pull/8204 also fixes this case.

**Comment by oempire** [comment] 2017-11-18 03:09
hi @gititon that's just with wp debug enabled,  populating the log as users are navigating the site.

Almost all of Jetpack functions are actually disabled on the site, we mainly use for vaultpress

**Comment by oskosk** [comment] 2018-02-22 19:29
@oempire could you confirm that this is still happening after a few new versions have been released?

**Comment by enejb** [comment] 2018-04-05 22:31
I am going to close this since we haven't hear back from the user.

**Closed by enejb** 2018-04-05 22:31 UTC
Labels: Sync, [Pri] High, [Status] Bug Scrub, [Type] Bug
