### ISSUE TITLE
Dashboard Widget: Footer details

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/jetpack#1768] opened 2015-03-13 15:48 UTC
![screen shot 2015-03-13 at 8 45 42 am](https://cloud.githubusercontent.com/assets/3220162/6641814/6c69baee-c95d-11e4-8bca-5ec6ac6b91e1.png)

I just installed the Beta - seems weird that after a few minutes I would already have 35 blocked Malicious attempts?  Or is this a placeholder?

The "Activate Akismet" button also should be better vertically centred.

**Comment by mikeyarce** [comment] 2015-03-13 15:51
Note: I also did not have BP installed on my test site.

If I don't have Akismet installed, this text also looks slightly off centre horizontally - and doesn't really communicate what the link does.  Will it take me to a new tab telling me more about Akismet?  Will it install the plugin on my site?  Is it a free plugin?
![screen shot 2015-03-13 at 8 49 54 am](https://cloud.githubusercontent.com/assets/3220162/6641887/f0f0f3e0-c95d-11e4-8af0-e3c4dccad808.png)

**Comment by jeherve** [comment] 2015-03-14 10:48
I can reproduce the alignment issue:

![screen shot 2015-03-14 at 11 46 46 am](https://cloud.githubusercontent.com/assets/426388/6651378/f596e14c-ca3f-11e4-9dd1-e4433aff781e.png)

**Comment by jeherve** [comment] 2015-03-14 10:50
And a few more layout issues with the widget:

![screen shot 2015-03-14 at 11 49 43 am](https://cloud.githubusercontent.com/assets/426388/6651384/49a60d94-ca40-11e4-9d6a-fae3537512f8.png)

**Comment by samhotchkiss** [comment] 2015-03-16 17:10
@mikeyarce : we've definitely seen multiple cases where people's blocked attack counts can go up significantly immediately after installing.  Many sites are pretty constantly under slow brute force attacks.  We've even seen people get into the thousands of blocked attacks within minutes of installing

**Comment by samhotchkiss** [comment] 2015-03-16 19:40
@jeherve - I'm not seeing these issues any more, it looks like they were cleaned up.  Will you update and see if they're still there, and, if not, close?

**Comment by mikeyarce** [comment] 2015-03-16 19:41
@samhotchkiss thanks for the tip!  That's good for us to know since that will likely be a question we get from a lot of users :)

**Comment by jeherve** [comment] 2015-03-17 07:40
@samhotchkiss I still see some alignment issues. Some of the elements are left aligned, while others are centered:

![screen shot 2015-03-17 at 8 39 28 am](https://cloud.githubusercontent.com/assets/426388/6683065/34a2667a-cc81-11e4-9993-74cf7f509f75.png)

**Comment by jeffgolenski** [comment] 2015-03-18 13:47
Left aligned!

**Comment by samhotchkiss** [comment] 2015-04-01 14:58
This was resolved in 3.4

**Closed by samhotchkiss** 2015-04-01 14:58 UTC
Labels: bug, General
