### ISSUE TITLE
Search: changes to Woo currency settings are not synced

### ISSUE THREAD

**Issue by bluefuton** [Automattic/jetpack#19906] opened 2021-05-21 00:10 UTC
#### Steps to reproduce the issue

1. On a test site with Jetpack Search and WooCommerce installed, perform a search for a product
2. In wp-admin, go to WooCommerce > Settings and alter the currency settings (symbol, separators, number of decimal places)
3. Perform another search for a product

#### What I expected
When I change the currency settings in WooCommerce, those new settings are reflected in the price displayed by Jetpack Search.

#### What happened instead
The Jetpack Search results still show the old currency settings.

**Screenshots**

<img width="418" alt="Screen Shot 2021-05-21 at 11 58 00" src="https://user-images.githubusercontent.com/17325/119063365-0380cf00-ba2d-11eb-80d0-9bf991a4fcdf.png">
<img width="719" alt="Screen Shot 2021-05-21 at 11 58 25" src="https://user-images.githubusercontent.com/17325/119063367-05e32900-ba2d-11eb-82aa-32e6f87356c7.png">

**Comment by bluefuton** [comment] 2021-05-21 00:10
@gibrown could https://github.com/Automattic/jetpack/pull/19674 help resolve this?

**Comment by gibrown** [comment] 2021-05-21 16:30
I would think this is covered by the existing case here: https://github.com/Automattic/jetpack/blob/c3e1af1a45faab15f2a76a690b61daaa77e6ec8e/projects/packages/sync/src/modules/class-woocommerce.php#L370

**Comment by bluefuton** [comment] 2021-06-27 22:10
@gibrown can we nominate this one for further investigation if we're lucky enough to have support time available? (And more generally, what's the best way to flag issues for backend ES support?)

**Comment by mdbitz** [comment] 2021-11-17 18:28
Misc notes as I was curious

The currency option is persisted to the [meta](https://opengrok.a8c.com/source/xref/trunk/wp-content/plugins/elasticsearch/indexing/wpes-lib/src/indices/jetpack-search-v7-post-doc-builder.php?r=234837#79) of the doc generated for the products. 

Need to check how the render is generated as we may need to move the data so the global option isn't saved to individual docs and read the option at display time if this data isn't overwritten on an individual product level.

**Comment by mdbitz** [comment] 2021-11-17 18:57
https://github.com/Automattic/jetpack/blob/e8e395ad3bb575f1df9dc932a9831bf44d8a250a/projects/plugins/jetpack/modules/search/instant-search/components/search-result-product.jsx#L95

The Price display is based off the formatted value which is saved to the individual product docs in the index. 

To have instant search results display the updated format it would currently require a bulk index. However it might be more appropriate to move the wc_price logic to the rendering in jsx that way a bulk index isn't required.

**Comment by bluefuton** [comment] 2021-11-18 03:30
Thanks for digging into this @mdbitz!

> However it might be more appropriate to move the wc_price logic to the rendering in jsx that way a bulk index isn't required.

When developing this we did consider duplicating `wc_price` into the Preact app, but there were complications we uncovered beyond the currency symbol and currency position. I wrote about this in p9xfpQ-1do-p2. Ideally we would like all the price formatting to happen on the server-side.

**Comment by mdbitz** [comment] 2021-12-02 14:35
@bluefuton Hey Chris. I wanted to reach out and let you know that we added a new indexing trigger for the woocommerce_currency option.

Do you mind retesting and let us know if this can be closed? As an FYI it has to re-index every product so it won't be instantaneous you should be able to monitor the debugger for status of the bulk index.

**Comment by bluefuton** [comment] 2021-12-02 21:36
Thank you @mdbitz! I'll give it a re-test :)

**Comment by bluefuton** [comment] 2021-12-05 23:12
@mdbitz unfortunately this didn't seem to do the trick on my test site (blog ID 84860689). I changed the currency from Euro to UK pound and the currency position from left to right:
<img width="698" alt="Screen Shot 2021-12-06 at 11 58 31" src="https://user-images.githubusercontent.com/17325/144767779-0189513f-3d0c-4336-b8cb-27e3436172c0.png">

I've left a reasonable time for the sync to happen but the products are still displaying in Euros. There are only 3 products on the site (11 records in total) so should have been a speedy sync.

<img width="662" alt="Screen Shot 2021-12-06 at 12 12 35" src="https://user-images.githubusercontent.com/17325/144767819-74f1ec40-30a8-4ca7-87ca-f52a166bdc44.png">

**Comment by mdbitz** [comment] 2021-12-06 15:09
Interesting.

I'm showing that the 'woocommerce_currency' option is GBP on your site, however when I look at the WP.com Cache I'm getting false returned. This is because in the WP.com Cache the option and most woocommerce options are being saved in the no autoload tables.

Working on a patch in D71064, but need to make sure I understand full consequences of the changes.

At this time I don't see currency position being included in the formatted_price. We should track that in a separate ticket as based on the way `get_woocommerce_price_format` works we can't simply pass the raw option value to the wc_price format but will need to duplicate the filter value.

**Comment by mdbitz** [comment] 2021-12-06 15:22
<img width="864" alt="Screen Shot 2021-12-06 at 9 39 56 AM" src="https://user-images.githubusercontent.com/5784663/144872444-7e1b0eb0-e175-4838-99a5-31f2f02bce10.png">

@bluefuton Chris I triggered the update of the option and showed the bulk index job triggered and now the currency has changed in the display.  I'm showing anecdotally around ~5 mins for the bulk index to trigger due to dedupe logic however I'm still learning how it works in full :)

**Comment by mdbitz** [comment] 2021-12-06 15:57
Actually no 2nd issue needed. the scope of this fully covers all 5 options in the "Currency options" setting. We'll work through updating the index so it references all the options fully and also triggers the bulk index as needed.

**Comment by bluefuton** [comment] 2021-12-06 20:25
> Please update the option back to EURO and lets see if it updates automattically, I'm seeing it on my test site but best for the 2nd validation.

Thanks @mdbitz! Just switched it back to Euro and will keep an eye out to see if it updates.

**Comment by bluefuton** [comment] 2021-12-06 20:30
...and it's updated! Within a few minutes:

<img width="889" alt="Screen Shot 2021-12-07 at 09 30 09" src="https://user-images.githubusercontent.com/17325/144917863-27c887a6-673a-4cbe-b285-d01733d1a82c.png">

🥳

**Comment by mdbitz** [comment] 2021-12-07 16:46
In Progress :: working through handling of all price related settings in D71145 and D71146

**Comment by mdbitz** [comment] 2021-12-08 17:17
Pending Team Review :: updates and tests are in place once I get feedback from the team we'll roll changes out.

**Comment by mdbitz** [comment] 2021-12-09 16:44
@bluefuton Hey Chris, I have pushed out the changes to the platform so that all the options used by wc_price are now adhered to. Let me know if you see any concerns or if good to close this out. As before expect a 5 minute delay before the changes pick up.

**Comment by bluefuton** [comment] 2021-12-09 21:45
Thanks @mdbitz! Currency, currency position, thousand separator, decimal separator worked great.

The only one that wasn't applied was number of decimals:

<img width="658" alt="Screen Shot 2021-12-10 at 10 40 21" src="https://user-images.githubusercontent.com/17325/145480178-b9138a26-bc9e-4e6b-88eb-851bbe534da6.png">

<img width="705" alt="Screen Shot 2021-12-10 at 10 42 00" src="https://user-images.githubusercontent.com/17325/145480237-ad97df59-d77d-4102-955d-09491a1d303a.png">

**Comment by bluefuton** [comment] 2021-12-13 20:51
Great! I can confirm 3 decimals on my test site now:

<img width="158" alt="Screen Shot 2021-12-14 at 09 51 03" src="https://user-images.githubusercontent.com/17325/145886819-318bf656-d912-41d1-a581-37c0c85eb0c0.png">

Thanks for making this work @mdbitz 🎉

**Comment by bluefuton** [comment] 2021-12-21 04:39
@mdbitz I just switched my currency settings around again on bluefuton.wpsandbox.me and it doesn't appear to have synced the number of decimals:

<img width="684" alt="Screen Shot 2021-12-21 at 17 35 39" src="https://user-images.githubusercontent.com/17325/146871953-db4571df-80c6-4be1-93cd-b8db2c241273.png">

<img width="690" alt="Screen Shot 2021-12-21 at 17 38 40" src="https://user-images.githubusercontent.com/17325/146871997-c9088640-fbee-4944-b7a0-baa6df01e046.png">

Any idea why this option in particular might not be syncing on this site?

**Comment by mdbitz** [comment] 2022-01-19 14:01
Circled back to this and found a bug in the Sync mappings on WP.com that had this option sanitizing as a string vs a integer.

I've resolved the error in D73353 and asked colleagues to audit options to ensure there are no other mapping issues.

**Comment by mdbitz** [comment] 2022-01-19 14:01
Marking this closed as I can confirm in the logs that this is fully resolved.

**Closed by mdbitz** 2022-01-19 14:01 UTC
Labels: [Type] Bug, Search, Instant Search

**Comment by gibrown** [comment] 2022-01-19 21:56
yay!
