### ISSUE TITLE
Sharing Block: disallow adding multiples of same service type

### ISSUE THREAD

**Issue by samiff** [Automattic/jetpack#35286] opened 2024-01-29 02:21 UTC
Currently you're able to add multiple of the same service types (e.g., multiple Print buttons). The original implementation only allows each service type to be added once.

<img width="357" alt="Screenshot 2024-01-28 at 7 17 06 PM" src="https://github.com/Automattic/jetpack/assets/15803018/d26475d2-e473-422d-8531-c78fae8500d4">

**Comment by jeherve** [comment] 2024-01-29 11:16
closing as duplicate of #35047.

**Comment by samiff** [comment] 2024-01-29 16:57
Reopening as it doesn't seem like #35184 addresses this particular issue: adding multiples of the same service type (not multiples of the sharing block itself).

@andrii-lysenko Could you confirm please. I don't see this issue as a blocker particularly, so understand if it heads to the backlog for now.

**Comment by andrii-lysenko** [comment] 2024-01-29 17:35
@samiff Thanks for reporting this. Yes, definitely this one is not addressed in the PR that was merged. Unfortunately, there's no tools that will prevent adding multiple blocks of the same variation to the page (or at least I'm not aware of these). We can keep this issue open and look into it later, but I would say chances are pretty low we would be able to fix this.

**Comment by jeherve** [comment] 2024-02-27 15:30
@keoshi What's your take on this? Should we just not allow a site owner to add multiples of the same button on the same line?

Thanks!

**Comment by keoshi** [comment] 2024-02-28 08:22
We mentioned this before a couple of times before, but I believe we should have the Social Icons block as our north star. At least for the first couple of iterations, it seems like a good idea to not diverge much from that core block.

As you can see, the Social Icons block also allows people to add multiple icons of the same type.

<img width="223" alt="image" src="https://github.com/Automattic/jetpack/assets/390760/681b07fd-f492-49a5-a3c7-32da0a1cdec3">

Would not worry about it too much for now since, even if at the cost of increasing user error, it provides maximum flexibility.

**Comment by andrii-lysenko** [comment] 2024-02-28 20:55
We are closing this issue according to the comment above. We could always revisit it if we would find it needed in the future.

**Closed as completed by andrii-lysenko** 2024-02-28 20:55 UTC
Labels: Bug, [Feature] Sharing, [Pri] Low, [Block] Sharing Buttons, [Block] Sharing Button
