### ISSUE TITLE
Remote data could not be fetched - Facebook pictures

### ISSUE THREAD

**Issue by neo22s** [Automattic/jetpack#8298] opened 2017-12-04 14:23 UTC
#### Steps to reproduce the issue

If you have pictures delivered from FB CDN on a page or loaded by any plugin and you have photon enabled the pictures won't load returning a 403 with error message:

"We cannot complete this request, remote data could not be fetched"

#### What I expected

Pictures should not add the i0.wp.com so they are not cached on wordpress servers and they can be displayed.

https://i0.wp.com/scontent.xx.fbcdn.net/v/t31.0-8/24131615_1995842950695459_8069248489101477710_o.jpg?oh=67c5ba58142bae9344f7cf9adc14e287&oe=5AC84824

#### What happened instead

Picture loading form FB CDN directly:
https://scontent.xx.fbcdn.net/v/t31.0-8/24131615_1995842950695459_8069248489101477710_o.jpg?oh=67c5ba58142bae9344f7cf9adc14e287&oe=5AC84824

**Comment by jeherve** [comment] 2017-12-05 09:26
I can't seem to be able to reproduce the issue on my end. Photon ignores that image when I insert it into one of my posts, as per the `jetpack_photon_banned_domains` function we use to make sure that domain (and a few others) do no go through Photon.

Could you let me know how you add that image to your site? Somehow it appears that you found a way to bypass that function.

Could you also let me know if you use the `jetpack_photon_skip_for_url` filter anywhere on your site?

Thanks!

**Comment by neo22s** [comment] 2017-12-05 12:01
I am using the plugin https://srizon.com/product/srizon-facebook-album/

Not working since only few days ago. I have contacted the plugin developer too.

Thanks a lot.

**Comment by AfzalH** [comment] 2017-12-05 13:14
I'm the developer of that Facebook album plugin. I didn't use any Jetpack hook on my plugin. Many users reported that issue and I suggested them to disable photon/photo optimization part of Jetpack believing it can't be fixed from my code

**Comment by jeherve** [comment] 2017-12-05 13:44
@AfzalH Thanks for chiming in!

Could you let me know how you insert the images in the post content? Do you hook into a specific WordPress filter, like `post_content`?

**Comment by AfzalH** [comment] 2017-12-05 14:40
Via shortcode. the shortcode handler function does the necessary api call etc and outputs the img tag  with src=something-provided-by-facebook

**Comment by jeherve** [comment] 2017-12-06 11:02
@AfzalH Could you try to add the following around the function that outputs the img tag:
https://github.com/jeherve/traktivity/commit/5301f0f00c95ae982389612c7dec33d07416c08f

Let me know how it goes!

**Comment by thekillerpunch** [comment] 2018-04-18 22:42
Please help out having the same issue on my website
am having : We cannot complete this request, remote data could not be fetched
https://i0.wp.com/www.thekillerpunch.com/wp-content/uploads/2018/04/Akwa-Ibom-State-Former-PDP-Exco-member-resigns.jpg?w=480&ssl=1

But if you remove the https://i0.wp.com/, the image is showing
https://www.thekillerpunch.com/breaking-akwa-ibom-state-former-pdp-exco-member-resigns-says-udom-promotes-supervises-political-vampirism/

what should i do please?

**Comment by jeherve** [comment] 2018-04-19 08:48
@thekillerpunch Your issue seems to be quite different. It appears that that image is not accessible on your site, so our CDN can't access it either:

http://www.thekillerpunch.com/wp-content/uploads/2018/04/Akwa-Ibom-State-Former-PDP-Exco-member-resigns.jpg
<img width="1550" alt="screenshot 2018-04-19 at 10 44 50" src="https://user-images.githubusercontent.com/426388/38981193-156f1196-43bf-11e8-8e9d-920377c0978d.png">

Once your image is publicly accessible, Jetpack's Image CDN will be able to access it as well.

I hope this helps. If you need more information, don't hesitate to contact us via email here:
https://jetpack.com/contact-support/?rel=support

I'll now close this issue since it hasn't seen any activity since last year.

**Closed by jeherve** 2018-04-19 08:48 UTC
Labels: Photon, [Status] Needs Author Reply, [Type] Bug

**Comment by jair2018** [comment] 2020-01-03 20:31
Will the picture be stored on jetpack an actual file that stays there forever or will it be deleted when i delete the my wordpress server?
Explain please in detail

**Comment by jeherve** [comment] 2020-01-06 12:04
> Will the picture be stored on jetpack an actual file that stays there forever or will it be deleted when i delete the my wordpress server?

@jair2018 You can refer to this support document for more information:
https://jetpack.com/support/site-accelerator/

> That means that we host your images from our servers
> [...]
> No cache invalidations – currently the images are cached “forever”

The image is consequently a copy of the original image, stored on our servers forever.

If you have any more questions, do not hesitate to contact us:
https://jetpack.com/contact-support/?rel=support

**Comment by neo22s** [comment] 2020-01-06 12:24
Stored forever? So what if someone wants to delete a picture? You do not
face any legal issues?

**Comment by jeherve** [comment] 2020-01-06 13:39
> Stored forever? So what if someone wants to delete a picture?

As mentioned in the support document I linked to above, you can contact us if you would like a specific image to be deleted.
