### ISSUE TITLE
[E-mails] Decrease size of the email's titles

### ISSUE THREAD

**Issue by foleynotrose** [Automattic/jetpack#24053] opened 2022-04-22 16:23 UTC
### Impacted plugin

Jetpack

### What

User would like the title of the post to be in a smaller font

### How

![image](https://user-images.githubusercontent.com/26651984/164755194-6f5b79df-0054-46ea-b80d-bed7bc748cc3.png)

**Comment by zdenys** [comment] 2022-04-26 14:26
5078586-zd-woothemes

**Comment by mashikag** [comment] 2022-05-04 15:29
@mtias this is perhaps another issue/report that should be handled by design first.

**Comment by yansern** [comment] 2022-05-05 15:30
This is another issue but targeting specifically New Post Like e-mail when heading is inside a blockquote. A separate issue should be created.
<img width="727" alt="image" src="https://user-images.githubusercontent.com/1287077/166958682-31241d5e-9c60-4dcb-8d8b-93eb837522d3.png">

**Comment by mashikag** [comment] 2022-05-05 15:41
> This is another issue but targeting specifically New Post Like e-mail when heading is inside a blockquote. A separate issue should be created.
@yansern the issue is now created https://github.com/Automattic/wp-calypso/issues/63346.

**Comment by mashikag** [comment] 2022-05-07 13:01
Therefore the following still needs to be addressed by the design team. cc @mtias 

> 2. The issue on font-weight: 900 being too bold is a pretty subjective opinion so that requires design input. However, one thing to note is that font-weight: 900 also applies to mail clients that doesn't use the "SF Pro Display" font, primarily Windows & Android users. And this is an example of what they are seeing.
![image](https://user-images.githubusercontent.com/2019970/167255556-e8671507-e787-4b68-a899-31e8b6b53430.png)

**Comment by mtias** [comment] 2022-05-09 09:37
The big and bold title treatment is a big part of the design intention. We should definitely address the discrepancy with the mobile design concepts and any leaks to general h1 elements in the body.

**Closed** 2022-05-09 11:30 UTC
Labels: [Type] Enhancement, Subscriptions, [Status] Needs Design
