### ISSUE TITLE
Jetpack Image Carousel closes to the previous visited page, if page is not loaded fully

### ISSUE THREAD

**Issue by dericleeyy** [Automattic/jetpack#11157] opened 2019-01-17 08:51 UTC
#### Steps to reproduce the issue

1. Create a post with a tiled gallery
2. Go to the homepage
3. Click on the post with the tiled gallery
4. Before the post finish loading, open one of the images in the image carousel and close it (Use Chrome Dev Tools > Network > Throttling > Slow 3G if the page loads too fast to simulate a slow loading page

#### What I expected
Carousel close to the post page

#### What happened instead
Carousel close to the previous page (home page)

**Screenshots**
https://drive.google.com/file/d/1HIGYKRsYDA2JvqEY72uxLWSNe1tjmFTL/view?usp=sharing (Restricted to Automattic)

**Comment by sirreal** [comment] 2019-01-17 08:58
Duplicate of #6244

**Closed by sirreal** 2019-01-17 08:58 UTC
Labels: Carousel, [Type] Bug
