### ISSUE TITLE
Sharing: Google + Default Icon creates console error

### ISSUE THREAD

**Issue by annezazu** [Automattic/jetpack#8207] opened 2017-11-18 00:07 UTC
To replicate: 
- Make sure latest version of Jetpack is installed
- Head to https://wordpress.com/sharing/buttons/[enteryoursiteurl]
- Set up the Button style to be "Official Buttons"
- View a post with the sharing buttons enabled.

You'll find this error:

`Uncaught TypeError: Cannot read property 'render' of undefined
    at HTMLDivElement.<anonymous> ((index):451)
    at Function.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.each (jquery.js?ver=1.12.4:2)
    at HTMLScriptElement.renderGooglePlus1 ((index):447)`

If you use any of the other options, it works. 

hat tip @ashleighaxios for finding this :)

**Comment by jeherve** [comment] 2017-11-20 14:20
Closing as duplicate of #8129

**Closed by jeherve** 2017-11-20 14:20 UTC
Labels: Google+, Sharing
