### ISSUE TITLE
Publicize: Error message should probably have a link to contact support

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#4326] opened 2016-07-07 01:23 UTC
While doing some 4.2 testing I ran across this error when trying to connect a Facebook account:

<img width="812" alt="screen shot on 2016-07-06 at 21-19-19" src="https://cloud.githubusercontent.com/assets/831377/16639669/c38afc4c-43bf-11e6-91d4-4a0d2daabce2.png">

It seems like we could include a link or something to contact support instead of just leaving the user to find it themselves.

**Comment by briancolinger** [comment] 2017-02-10 17:21
@chaselivingston, I've grepped the codebases of 4.6 and 4.2 for this error message and was unable to find it. Do you have a way to reproduce this issue?

**Comment by chaselivingston** [comment] 2017-02-10 17:33
@briancolinger I believe the code for this error message may live on wpcom instead of in the plugin itself.

**Comment by briancolinger** [comment] 2017-02-10 19:42
I've opened a new ticket for this issue here #7843-wpcom.
Closing this one since this is a wordpress.com issue.

**Closed by briancolinger** 2017-02-10 19:42 UTC
Labels: Publicize, [Pri] Low, [Type] Enhancement, [Type] Good First Bug
