### ISSUE TITLE
Settings UI: Make it easier for users to find hidden modules

### ISSUE THREAD

**Issue by zoonini** [Automattic/jetpack#7050] opened 2017-04-24 20:05 UTC
A user in my local WordPress meetup group was looking for a recipe plugin, so I suggested she try Jetpack's recipe shortcode, since it's built right in and very handy and easy to use. 

The user came back to say that she couldn't figure out how to activate the shortcodes module within Jetpack, as it wasn't listed anywhere in the settings. I took a look myself, and after about _10 minutes_ of searching around the new settings interface, I absolutely could not find it, either. I also then noticed that many other popular modules are also missing, like the contact form. I searched the Jetpack documentation in vain as well - the Shortcodes Embed page makes no special mention of any special steps to activate it.

I then headed to the Jetpack page at WordPress.org, planning to search the forums and see if I could figure out where the heck all those modules had gone. Lo and behold, a 2-star review right on the first Jetpack page on wp.org gave me the answer:

![jetpack by wordpress com wordpress plugins-1](https://cloud.githubusercontent.com/assets/334237/25356115/1d726fb0-2907-11e7-9708-bc6cd678f80f.png)

This is how I discovered that many modules are now accessible only by clicking a tiny "Debug" link all the way at the very bottom of the settings page:

![jetpack wp engine test site wordpress-1](https://cloud.githubusercontent.com/assets/334237/25356276/9a710a62-2907-11e7-99c0-031afffa3690.png)

...and then buried within the next page full of text, in very small writing that says "Access the full list of Jetpack modules available on your site."

![wp engine test site wordpress](https://cloud.githubusercontent.com/assets/334237/25356310/b6172878-2907-11e7-9cf2-159844d4eebe.png)

There is almost no chance a regular user would find these missing modules on their own. Heck, three developers and tech-support staff very familiar with Jetpack were unable to find it on their own.

I do understand wanting to simplify the options within Jetpack, but the current iteration makes it impossible for users to find hidden features they may be looking for. (To say nothing of making it difficult for users to "discover" features they may find useful but didn't know Jetpack offered. I can see many users installing a separate contact-form plugin now, not realizing that Jetpack comes with one built in.)

As a temporary workaround for now, could we please consider adding something like this to **each settings screen**, maybe just above the "We're here to help" section:

**Looking for more features? See all modules**

...with a link to all the modules?

This will prevent a lot of frustration.

**Comment by jeherve** [comment] 2017-04-24 20:32
Closing as duplicate of #6861

**Closed by jeherve** 2017-04-24 20:32 UTC
