### ISSUE TITLE
Notes: Australian Notifications JS doesn't exist

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#2791] opened 2015-10-02 14:53 UTC
Steps to reproduce:

1. Enable the Notifications module on your site.
2. Go to Settings > General
3. Switch your site language to English Australian (`en_AU`)
4. Check your browser console:

> https://widgets.wp.com/languages/notifications/en-au.json Failed to load resource: the server responded with a status of 404 (Not Found)

I assume it's missing because we don't have `en_AU` on WordPress.com.

- Reported here: https://wordpress.org/support/topic/httpswidgetswpcomlanguagesnotificationsen_usjson-404?replies=16&view=all#post-7491159
- Related: #2698
- cc @dmsnell @akirk

**Comment by elliott-stocks** [comment] 2015-10-02 15:20
I also noticed this on `ja_JP`.

**Comment by jeherve** [comment] 2015-10-02 15:22
@elliott-stocks Right! 

The fix should be similar for this issue and for #2789.

**Comment by ntwb** [comment] 2015-10-03 11:20
> I also noticed this on `ja_JP`.

This is correct, the Japanese locale is `ja` not, `ja_JP` :smirk: 

As such this works as expected: https://widgets.wp.com/languages/notifications/ja.json

The other workaround is for us Aussies to translate Jetpack ;) (We will get to it eventually, I promise)

**Comment by kraftbj** [comment] 2015-12-07 22:22
en-ca impacted as well per 2444063-t

**Comment by grappler** [comment] 2016-01-29 17:34
Same issue for `de_CH`

**Comment by zocoloco** [comment] 2016-02-02 20:36
Any update on this? Getting this javascript error: 404 not found https://widgets.wp.com/notifications/build.min.js.map?3dec33ed91316fa5002b5b41bdd49d57

**Comment by jeherve** [comment] 2016-02-02 20:39
@zocoloco That's a different issue, and something we're tracking in another GitHub issue on an internal repository. We'll get that error fixed soon. It shouldn't affect your experience in the dashboard, though.

Let us know if it does!

**Comment by zocoloco** [comment] 2016-02-03 05:06
@jeherve thanks for the update! I appreciate it.

**Comment by ntwb** [comment] 2016-02-03 08:20
So this is still 404'ing https://widgets.wp.com/languages/notifications/en-au.json even though Jetpack is now 100% translated for en_AU: https://translate.wordpress.org/locale/en-au/default/wp-plugins/jetpack, presuming this is something not yet switched from the translation projects move to w.org from https://translate.wordpress.com/projects/jetpack?

**Comment by akirk** [comment] 2016-02-03 08:46
As @jeherve said in the initial post, the problem is not the Jetpack translation but that we don't have an en-au locale on WordPress.com. I think we can do some mapping server-side so that this will be fixed without having to change something in Jetpack.

**Comment by Josephvb10** [comment] 2016-02-04 10:10
@jeherve  This exact same issue is happening when selecting the `es_mx` language; the URL https://widgets.wp.com/languages/notifications/es-mx.json doesn't  exist (but https://widgets.wp.com/languages/notifications/es.json does).

**Comment by TheArcturian** [comment] 2016-02-16 15:17
The same for Norwegian as well: Failed to load widgets.wp.com/languages/notifications/nb.json

**Comment by jeherve** [comment] 2016-03-01 08:37
Same issue for `en-nz`

**Comment by ntwb** [comment] 2016-03-15 21:22
Also to note that no doubt the same will be true for `en-ca` and `en-za` (Canada and South Africa respectively)

**Comment by Josephvb10** [comment] 2016-04-17 06:17
How's possible that this bug hasn't been fixed? This causes a plain 404 error on many pages and has been over half a year since it was first reported. @jeherve

**Comment by jeherve** [comment] 2016-04-17 13:11
@Josephvb10 We didn't find a solution that would fix all languages at once just yet, but once we do we'll update this issue!

**Comment by jeherve** [comment] 2016-04-18 11:32
Same issue with `nb` (`nb_NO`, and `no` on WordPress.com).

**Comment by elliott-stocks** [comment] 2016-04-18 11:37
@jeherve Can we make use of ``facebook_locale`` here, similar to #2789?

**Comment by jeherve** [comment] 2016-04-18 11:42
@elliott-stocks I'm afraid not. The problem is on WordPress.com, where not all locales exist yet. Using `facebook_locale` would still return 404 for most of the languages mentioned above.

We'll need to introduce some mapping on WordPress.com so we can have a response for all locales, or fallback to the proper code we use on WordPress.com.

We'll try to tackle this in Jetpack 4.0.1.

**Comment by jeherve** [comment] 2016-05-11 09:15
@akirk Can you think of something we could do to address this issue on WordPress.com?

**Comment by ntwb** [comment] 2016-05-17 05:46
> Can you think of something we could do to address this issue on WordPress.com?

Why not add the missing locales to wp.com?

**Comment by akirk** [comment] 2016-07-20 05:48
We deployed a fix on the WordPress.com that should have resolved this issue. Please report back if you encounter a case that we have missed. Thanks!

**Closed by akirk** 2016-07-20 05:48 UTC
Labels: Notifications, [Type] Bug

**Comment by arc909** [comment] 2017-08-11 11:31
JetPack 5.2.1 on site http://www.ancpl.com

404 - https://widgets.wp.com/languages/notifications/en-au.json

**Comment by akirk** [comment] 2017-08-11 12:20
@arc909 thanks for reporting! 

For English based language there is no fallback necessary (because the fallback US English is the default) but we've now stopped the 404 and return a 200.
