### ISSUE TITLE
implode_frontend_css on wp_print_styles priority using negative index

### ISSUE THREAD

**Issue by drrobotnik** [Automattic/jetpack#1463] opened 2014-12-30 04:03 UTC
By setting the priority to -1 you essentially load your scripts after the main themes style.css making it a nuisance to override jetpack styles.

https://github.com/Automattic/jetpack/commit/c79c92637ec31d1ead399867b1b4c18b2daec5bd

**Comment by jeherve** [comment] 2018-09-05 08:17
Closing as duplicate of #1500

**Closed by jeherve** 2018-09-05 08:17 UTC
Labels: General, [Type] Duplicate, [Type] Enhancement
