### ISSUE TITLE
Facebook Page Plugin falls back to English for German formal (de_DE_formal)

### ISSUE THREAD

**Issue by Zodiac1978** [Automattic/jetpack#6956] opened 2017-04-10 13:59 UTC
#### Steps to reproduce the issue
Adding the FB Page Plugin extra sidebar widget and set your blog to "Deutsch (Sie)" (German formal language)

#### What I expected
FB Page Plugin in German formal or German (maybe FB just supports German in general)

#### What happened instead
FB Page Plugin is using English

Related #2789

**Comment by jeherve** [comment] 2017-04-10 15:06
Closing as duplicate of #5468

**Closed by jeherve** 2017-04-10 15:06 UTC
