### ISSUE TITLE
Gutenberg: Carousel always opens to first Image in gallery

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/jetpack#10957] opened 2018-12-12 13:43 UTC
#### Steps to reproduce
- Start with a Jetpack site, or with a WordPress.com site (as it carries Jetpack's features) 
- Use WordPress Editor (Gutenberg) to insert a gallery block (Jetpack gallery takes over as per https://github.com/Automattic/jetpack/issues/10246)
- Visit the gallery in the live page
- Click on any image in the gallery (ideally not the first one to reproduce this issue)

#### What I expected
I expected the carousel to open to the image I clicked on.

#### What happened instead
Carousel always opens to the first image in the gallery set, no matter which one is clicked. 

#### Situation with classic editor

When one activates `Classic editor` plugin on the site and try to insert a carousel, one can notice that the carousel works as expected - the image clicked on opens first.

#### Browser / OS version
Any

Previously reported at https://github.com/Automattic/wp-calypso/issues/29255 by @jruud

**Comment by jeherve** [comment] 2018-12-12 13:45
Closing as duplicate of #10747

**Closed by jeherve** 2018-12-12 13:45 UTC
Labels: Carousel, Gutenberg, [Type] Bug, [Type] Duplicate

**Comment by arunsathiya** [comment] 2018-12-13 11:40
Ah, I had missed that. Thanks!
