### ISSUE TITLE
Site Stats on Dashboard->Home broken on 5.0 Beta 1

### ISSUE THREAD

**Issue by Ipstenu** [Automattic/jetpack#10412] opened 2018-10-26 15:44 UTC
Logging in to my beta test site, the site stats (which should actually be disabled since I'm in DEV mode) throw an error

"This meta box, from the Jetpack by WordPress.com plugin, isn't compatible with the block editor."

![screen shot 2018-10-26 at 26 oct - 4 42 50 pm](https://user-images.githubusercontent.com/807903/47577284-62960a00-d93e-11e8-92be-c0d99031643f.jpg)

**Comment by jeherve** [comment] 2018-10-26 16:19
Thanks for the report!

To clarify, you're running WordPress with the Beta tester plugin and the "bleeding edge nightlies" option selected? Is Gutenberg active on your test site?

**Comment by Ipstenu** [comment] 2018-10-26 19:36
Gutenberg is NOT active. 

Beta Tester is on 5.0-beta1-43823 at the moment.

**Comment by jeherve** [comment] 2018-10-26 20:02
Thanks for the extra details. I can reproduce the problem.

This seems to be related to this core ticket:
https://core.trac.wordpress.org/ticket/45192

There are more reports here:
- https://core.trac.wordpress.org/ticket/45112#comment:12
- https://github.com/WordPress/gutenberg/issues/11058

It would appear that a fix was committed to the `5.0` branch
here earlier today:
https://core.trac.wordpress.org/changeset/43830

That should hopefully fix things. I'll run some tests to find out.

**Comment by jeherve** [comment] 2018-10-26 20:20
hm no, it does not solve the issue. I've commented here with my findings so far:

https://core.trac.wordpress.org/ticket/45112#comment:27

I'll close this issue when this gets addressed in Core, or we'll see what we can do in Jetpack to fix this. 

P.S.: for anyone else having some trouble reproducing this on a fresh site, don't forget to turn on `WP_DEBUG`; the message won't appear if `WP_DEBUG` is set to `false`.

**Comment by jeherve** [comment] 2018-11-07 18:19
Closing this as the problem seems to be fixed now.
https://core.trac.wordpress.org/ticket/45112#comment:32

**Closed by jeherve** 2018-11-07 18:19 UTC
Labels: Gutenberg, Stats, [Type] Bug
