### ISSUE TITLE
Related posts: add 'show_excerpt' option

### ISSUE THREAD

**Issue by marcelomazza** [Automattic/jetpack#7718] opened 2017-08-30 12:17 UTC
The related posts module outputs HTML with the excerpt:

https://github.com/Automattic/jetpack/blob/8758b98cfc3fe277f3f45d9ca52171d0fb33ba71/modules/related-posts/related-posts.js#L130

and is then hidden with CSS in:

https://github.com/Automattic/jetpack/blob/8758b98cfc3fe277f3f45d9ca52171d0fb33ba71/modules/related-posts/related-posts.css#L159-L162

---

As with the 'show_date' option that allows to show/hide the output of the date, it would be great to have a 'show_excerpt' option to show/hide the excerpt.

Additionaly, this option could be used to hide the excerpt from the `title` attribute of the anchor tag:

![image](https://user-images.githubusercontent.com/384622/29871922-e2608544-8d63-11e7-9d45-dfb9f9ab3a7c.png)

**Comment by jeherve** [comment] 2017-09-08 13:00
Closing as duplicate of #3235. The filter suggested there would give you full control over the excerpt.

**Closed by jeherve** 2017-09-08 13:00 UTC
Labels: Related Posts, [Type] Enhancement
