### ISSUE TITLE
FEATURE: Sortable Column of Views in All Posts

### ISSUE THREAD

**Issue by mitchellkrogza** [Automattic/jetpack#6161] opened 2017-01-25 15:20 UTC
A feature request I would love to see.

I currently use the plugin https://wordpress.org/plugins/post-views-counter/ which creates a sortable column in Posts > All Posts which helps immensely with finding old articles on a site that do not get much traffic.

Their stats however are quite inconsistent with what is reported by Jetpack, Jetpack actually reports more hits on articles than this plugin.

I would love to see Jetpack introduce a column called Post Views into the plugin which could allow a quick sort from highest to lowest or vice versa. It would be a great add on for Jetpack and reduce the need of having one extra plugin.

**Comment by jeherve** [comment] 2017-01-25 17:08
Closing as duplicate of #858

**Closed by jeherve** 2017-01-25 17:08 UTC
