### ISSUE TITLE
[Earn] Fix the Payments block selector

### ISSUE THREAD

**Issue by artpi** [Automattic/jetpack#28523] opened 2023-01-23 09:43 UTC
Originally spotted by @n3f:

> The payments block appears that lets you choose:

![](https://user-images.githubusercontent.com/6354169/213801319-d1bfe153-7c16-4033-94cd-9e357f483d2b.png)

> But only the middle button works... Anyone else seeing something similar. (It's the same for me on trunk).

I was trying to point out when did this problem occur, and even after rolling back to mid-december, the problem is still there. It seems unrelated to our paid-newsletter work, but nevertheless - seems like a problem

## Reproduction path

This will be only possible on WPCOM testing flow as the premium content block is only available on wpcom:

1. Sync to wpcom
2. insert `/payment` on a site with enabled payment features
3. Observe that donation and premium content blocks are not able to be selected.

**Comment by romarioraffington** [comment] 2023-03-14 23:52
Noting here that the Donation button works on a Jetpack site.

https://user-images.githubusercontent.com/7076981/225166819-36e4b0ac-8221-465c-8667-696b0734f8e8.mov

**Comment by artpi** [comment] 2023-03-15 11:23
It does not on a bestmemberships.
Maybe we broke it with the newsletter work? Since newsletters are not active in JP yet, maybe that is the issue?

**Comment by artpi** [comment] 2023-03-15 11:29
It seems like the promblem is only on WPCOM simple
See https://membershiproduction.wordpress.com/wp-admin/post-new.php

**Comment by romarioraffington** [comment] 2023-03-16 01:10
Yes yes, the problem is isolated to WPCOM Simple

**Comment by romarioraffington** [comment] 2023-03-18 01:53
> Maybe we broke it with the newsletter work? Since newsletters are not active in JP yet, maybe that is the issue?

@n3f  mentioned that this issue pre-dated our merge; I've checked but couldn't find why our code would cause this issue.  It's very interesting that neither the donation nor the premium-content are available as separate blocks on WPCOM

What I've discovered so far. I'll appreciate any help @Automattic/gold as I think I'm a bit stuck

1. Premium content seems to be unavailable:

```
    [premium-content] => Array
        (
            [available] =>
            [unavailable_reason] => missing_module
            [details] => Array
                (
                )

        )
```

2. `Automattic\Jetpack\Extensions\Donations\render_block` doesn't seem to be called for the Donation blcok

**Comment by dsas** [comment] 2023-03-23 11:39
> It's very interesting that neither the donation nor the premium-content are available as separate blocks on WPCOM

There's probably two or three issues here:
 * The premium content block is unavailable
 * The donations block also is in some way broken and isn't available in the inserter
 * The payments block selector isn't robustly handling the above problems.

**Comment by dsas** [comment] 2023-03-23 11:41
This issue has also been [filed against calypso](https://github.com/Automattic/wp-calypso/issues/74804) and escalated p1679521739387739-slack-C02FMH4G8 on dotcom.

Right now I can't reproduce it, but my ability to reproduce it seems rather sporadic, so I don't want to assume that means it's fixed itself.

**Comment by danielbachhuber** [comment] 2023-04-10 11:19
New report with some debugging https://github.com/Automattic/jetpack/issues/30006#issuecomment-1501704758

**Comment by romarioraffington** [comment] 2023-04-10 18:35
Noting here that even-though this ticket is assigned to me, I've had higher priority tickets to work on over the past 3 weeks. Any help is appreciated.

**Comment by WunderBart** [comment] 2023-04-11 12:56
> Observe that donation and premium content blocks are not able to be selected.

This is most likely caused by a block visibility setting in user preferences. If you go to **Options** > **Preferences** > **Blocks** > **Visible blocks** and search for the `Donations Form` or `Premium Content` block, you'll probably find it disabled. Turning it on should fix the issue (see the video below).

https://user-images.githubusercontent.com/1451471/231167157-d8b058dd-9055-4619-8690-48f86bf3fc35.mov

Thanks @danielbachhuber and @tyxla for help with figuring this one out! 🚀 

---

For the fix part, it should probably be handled in Jetpack. For example, we could check the block availability when rendering the Payments block and make the buttons initially disabled with a CTA to check the preferences. What do you think, @artpi @dsas @romarioraffington?

**Comment by romarioraffington** [comment] 2023-04-11 16:59
> For the fix part, it should probably be handled in Jetpack. For example, we could check the block availability when rendering the Payments block and make the buttons initially disabled with a CTA to check the preferences. What do you think, @artpi @dsas @romarioraffington?

Thanks for the help with debugging this issue.  A few clarifying questions here. I suspect Earn's product manager, @artpi, would be in the best position to answer this. 

1. Is there a use case where the Donation block should be hidden? 
2. This "bug" seems to be affecting several sites, should we make the Donation block visible by default?
3.  Should we change the visibility of the Donation block when the Payment block is inserted?

**Comment by millerf** [comment] 2023-04-12 14:42
@romarioraffington  Can we:
- Have a look at the logic behind why the setting is false on yours and not on @n3f 's 
- Make sure the setting is `true` by default
- Set the setting to true if one block is added
- Maybe add a "disabled" UI in the donation blocks ?

**Comment by romarioraffington** [comment] 2023-04-12 23:50
## Notes

### State
1. The visibility of a block in Gutenberg is determined is stored in redux state in `settings.allowedBlockTypes`
1. The `UPDATE_SETTINGS` action is used to update this state
1. Absence of the block name from the redux state results in the block not being made visible.
1. On load, the `jetpack/donations` block is missing from the state.
1. When the visibility of the donation block changes in Preferences, `jetpack/donations`  is inserted in the state and works as expected.


### Expected behavior
1. [Based on our documentation](https://wordpress.com/support/wordpress-editor/blocks/donations/), the donation block should be visible for all WPCOM paid plans
1. The block should be visible in the list of blocks upon typing `/`
1. The block should work as expected in the Payments block

### A screenshot of the `settings.allowedBlockTypes` redux state when visibility is enabled 
<img width="827" alt="Screenshot 2023-04-12 at 6 38 03 PM" src="https://user-images.githubusercontent.com/7076981/231610247-bf73195c-ff19-4806-897f-1dd49394b6bd.png">

**Comment by romarioraffington** [comment] 2023-04-13 21:42
### Update

1. This "bug" doesn't appear to affect newly created sites
2. I don't see where we are intentionally hiding the donation block from the editor 
3. I've created [a PR ](https://github.com/Automattic/jetpack/pull/30095) to make the Donations, Payment Button, and Premium Content block visible when clicked from the Payment Block.

**Comment by dsas** [comment] 2023-04-17 10:39
An earlier investigation found that the root cause for the weird allowed blocks state is possibly due to p2: p1678770434676469/1675417267.339259-slack-C45SNKV4Z

**Closed as completed** 2023-04-18 14:27 UTC
Labels: Bug, [Status] In Progress, [Pri] Normal, Earn, [Plugin] Jetpack, [Block] Payments
