### ISSUE TITLE
Tiled Galleries: Square tiled galleries stretch top image if there's only one in the first row

### ISSUE THREAD

**Issue by jillb** [Automattic/jetpack#5975] opened 2016-12-21 16:39 UTC
#### Steps to reproduce the issue

Create an image gallery using Square Tiles. Upload a number of images that results in one image in the top row. (3n + 1 ;) )

#### What I expected

![properimage](https://cloud.githubusercontent.com/assets/2213130/21396943/ee45221c-c76f-11e6-82e2-78caee13e28a.jpg)

#### What happened instead

![image](https://cloud.githubusercontent.com/assets/2213130/21396629/dff3c606-c76e-11e6-839f-5ceec71d925d.png)

#### Solutions

1. This is the CSS workaround I used for my clients' sites, in case it's helpful:

.gallery-row,
.gallery-row .gallery-group,
.tiled-gallery.type-square .gallery-row:first-child .gallery-group .tiled-gallery-item img {
	height: auto !important;
}

2. The other option is to crop it as a square, just as all the other images in the gallery are cropped squares. Without being stretched vertically as it is now.

**Comment by jeherve** [comment] 2017-02-13 18:21
Closing as we can't seem to be able to reproduce the issue anymore:
https://github.com/Automattic/jetpack/pull/6022#issuecomment-278072129

**Closed by jeherve** 2017-02-13 18:21 UTC
Labels: Tiled Galleries, [Pri] Low, [Type] Enhancement, [Type] Good First Bug

**Comment by jillb** [comment] 2017-02-13 22:54
Hello,

Thanks for looking into the issue. It is in fact still an issue for me on WordPress.com sites. I tried it again in the customizer of the above mentioned site (removing my CSS I had put in to fix the issue) and in the customizer preview it is still doing the exact same thing:

https://edsoconstruction.com/portfolio/

Scroll down to the second photo gallery on the page.

Thanks!

**Comment by jillb** [comment] 2017-02-13 22:59
I don't think I have the capability of reopening this ticket as it was closed by you, not by me.

https://github.com/isaacs/github/issues/583

Please reopen it. Thanks

**Comment by jeherve** [comment] 2017-02-14 09:38
Thanks for the extra details. Since this issue is specific to WordPress.com sites and can't be reproduced on Jetpack sites, I've moved it to our internal bug tracker on WordPress.com: 7844-wpcom

I'll let you know as soon as this is fixed.

**Comment by jillb** [comment] 2017-02-14 13:38
Thanks!
