### ISSUE TITLE
Email sharing overrides default sender (from) address for the site

### ISSUE THREAD

**Issue by galbaras** [Automattic/jetpack#5621] opened 2016-11-14 04:15 UTC
I use the plugin SMTP Mailer to send email via Amazon SES. The plugin configuration includes settings for "from name" and "from email", which should be the default for the site.

#### Steps to reproduce the issue

Share a post via email.

#### What I expected

Email should come from addressed configure in SMTP Mailer plugin: `Family Matters <info@ronitbaras.com>`

#### What happened instead

Email comes from `Sender Name <wordpress@ronitbaras.com>`, where `Sender Name` is the name entered by the sender on the email sharing form.

Since `wordpress@ronitbaras.com` is not a valid user in the domain, failure notices are lost and it's likely that some servers reject the shared email.

#### What should happen

Jetpack should not set the from name and address. It should either send the email using the default settings or (better, I think) provide options for these in the sharing settings.

**Comment by jeherve** [comment] 2016-11-14 10:45
What plugin do you use to configure WordPress to send out the emails? Is it possible that this possible doesn't use `wp_mail_from` to overwrite the from address?

Could you try to set up [Postman](https://wordpress.org/plugins/postman-smtp/), and see if it helps?

> Jetpack should not set the from name and address. It should either send the email using the default settings or (better, I think) provide options for these in the sharing settings.

Related: #3504 (cc @kraftbj).

I don't believe we'll ever add options in the sharing settings, as the options would be confusing to most users; the email sharing button is supposed to work out of the box, much like all the other sharing buttons.

**Comment by galbaras** [comment] 2016-11-15 06:45
As you can see [in the plugin code](https://plugins.trac.wordpress.org/browser/smtp-mailer/trunk/main.php), both wp_mail_from and wp_mail_from_name are used and filtered, but the plugin respects an explicit email address when that's passed to it, which is what Jetpack is doing.

I think this is another case of Jetpack trying to handle every possible case, rather than expecting sites to be configured properly. The function sharing_email_send_post() should not be setting the "From:" header. It should leave it alone and allow the site's setup to take care of this.

**Comment by kraftbj** [comment] 2016-11-15 20:37
@galbaras For the from e-mail address, it's applying the `wp_mail_from` filter ( https://github.com/Automattic/jetpack/blob/master/modules/sharedaddy/sharedaddy.php#L23 ), but we don't filter the name right now.

IIRC, to set the reply-to header, we needed a from header set as well.

For the record, the commit that added this wasn't trying to address improperly configured servers, but ensure that an e-mail is sent out from a domain within the admin's control, in theory, while still preserving the feature of being able to reply back to the share to reply to the sharer.

I'll investigate this a bit more.

**Comment by kraftbj** [comment] 2016-11-15 21:37
Apologies, no. That's the expected behavior. Since the item is being shared from one person to another, we opted to include the sharer's name in the "From". Otherwise, on a default install, the sender would be "WordPress" which is confusing.

In either case, https://plugins.trac.wordpress.org/browser/smtp-mailer/trunk/main.php#L578 should be filtering over what we pass to the plugin anyhow. If nothing else, we might be over-cautious by using the `wp_mail_from` filter since `wp_mail()` should be applying it late anyhow.

Please do correct me if I'm wrong, but going to close this ticket for the time being. Happy to re-open.

**Comment by galbaras** [comment] 2016-11-16 01:56
That's not what I see in the code. Both the standard wp_mail() and the one in the SMTP Mailer plugin explode and clean $headers and THEN check for the from address and use defaults if it's not set.

Jetpack should simply not provide that value and can still use the reply-to header. Why not test it and see?

**Comment by kraftbj** [comment] 2016-11-16 15:33
I was incorrect in that the `from` was required to be set to work, but without it, the default `from` name is "WordPress" per Core and not the person sending. It reads more as spam from a site than a personal share from an individual, so we set it to read better.

I tested out the `wp_mail_from` and `wp_mail_from_name` filters with Core's `wp_mail` and both overrode what Jetpack set for an e-mail share. The code in the plugin looks like it should do the same since it filters right before passing to the phpmailer.

In your case, you may want to suggest to the other plugin to have an option to "hard overwrite" a specific passed e-mail/from or you can add custom code to override it. You could use something like

```
add_filter( 'wp_mail_from', 'never_use_default_from_address');
function never_use_default_from_address( $email ){
if ( 'wordpress@domain.com' == $email {
$email = 'info@domain.com';
}
return $email;
}
```

All that said, it's a possibility that we could use the `wp_mail_from_name` filter instead to avoid directly setting the from value to make it a bit more flexible for this particular plugin. We would need to think through how to do it to conflict the least with others who are already using that filter. For example, we could use it at priority 9 to set it before others who are using it, if they use the default of 10, but it would be setting it later still than we have previously.

**Comment by galbaras** [comment] 2016-11-16 22:39
Actually, Jetpack is specifically setting the filter to wordpress@, NOT the sender, with this line (23):

`	$from_email = apply_filters( 'wp_mail_from', 'wordpress@' . $sitename );
`

It's the wrong thing to expect settings like these to be overridden by theme code. The correct way to do it is simply not to set it to anything and not to pass the from address to wp_mail().

Yes, the best to do is to remove the handling of the from address from the sharing code and set the from name through a filter. In this case, the filter priority should be high enough to override the default, although in some situations, this may trigger spam filters, because the name won't match the user ID.

One way to handle this situation is with a "Sender:" header, which you can set to a local email address, while using the actual sender's name and email in the "From:" header. The recipient will get the message "on behalf of" the real sender. The only problem with this approach is that there is no default for the "Sender:" header, and we're back to wordpress@, which is what I'm trying to avoid :(

**Comment by kraftbj** [comment] 2016-11-17 21:26
Jetpack is setting the name to the name provider by the sharer (line 25, `$headers[] = sprintf( 'From: %1$s <%2$s>', $data['name'], $from_email );`. From previously `the default from name is "WordPress" per Core and not the person sending. It reads more as spam from a site than a personal share from an individual, so we set it to read better.`

I don't think there is a "right" or a "wrong" way in this case. The SMTP plugin could be "wrong" for not letting you have an option to override the e-mail address when passed via the function while giving you an option to change the default `from` address via an UI. Not a right or a wrong, only the solution that worked for the majority of cases that doesn't for you right now. Is there another solution wholly within Jetpack that would fit the original use case and your case? Very well might be. Are there other solutions wholly within the SMTP plugin? Sure. Other solutions through a bit of custom code to massage the two plugins working together? Yep.

In our case, we're trying to account for the majority of sites that are running WordPress straight without using that SMTP plugin and the sites that are customized by using WordPress filters (which still work).

**Comment by galbaras** [comment] 2016-11-18 03:43
The value of  $from_mail is set on line 23. Unless there is a filter on wp_from_email, this is set to wordpress@, which is given explicitly as the default value on that line.

`$from_email = apply_filters( 'wp_mail_from', 'wordpress@' . $sitename );`

As you can see on line 25, $data['name'] comes from the form submission, but $from_mail doesn't. It's only set on line 23. The submitted email address is only used in the "Reply-to:" header.

My testing shows that this is indeed reflected in the actual message headers.

Setting something that shouldn't be set and causing extra work to theme developers is definitely "wrong". I see no reason to create the "From:" header. Instead, Jetpack can use the 'wp_mail_from_name' filter, which overrides the name without changing the address.

This is actually the second issue I'm involved with that gets the response "we're trying to cater for everyone" after I demonstrate that you're not catering for me, which is kind of annoying.

**Comment by kraftbj** [comment] 2016-11-30 15:41
Using the name filter is an option that we'd entertain a PR for, but not something on our immediate radar. Since we need to support 5.2, it can't be an anonymous function and would need to remove the filter after our wp_mail call to ensure there's not a bleed with any other e-mails being sent on the same request.

The from name being set is required in any PR though for the reasons I mentioned above. Again, in this case, since the core filters are being respected and only an issue with a particular implementation of a plugged version of wp_mail not applying that plugin's setting via a filter itself, I don't think it is critical for Jetpack to account for that type of usage.

For the record, we don't need to cater for everyone, but we try to develop for the majority while making things extendable enough for most of the minority cases.

**Comment by galbaras** [comment] 2016-12-01 01:13
Brandon, thank you for accepting this.

What reason was there for using the "From:" header, other than to specify the from address? If this can be done through the filter, the header is NOT required. Both the standard wp_mail() function and the one in SMTP Mailer check for this header and default to a filtered version of `wordpress@` if it's missing.

**Comment by jeherve** [comment] 2022-07-01 11:26
This can now be closed since we now use mailto instead of a custom email sharing button (see #24040).

**Closed by jeherve** 2022-07-01 11:26 UTC
Labels: [Type] Enhancement, Sharing, [Pri] Low, Good For Community
