### ISSUE TITLE
Carousel: improve display on mobile devices.

### ISSUE THREAD

**Issue by humanfiles** [Automattic/jetpack#6069] opened 2017-01-10 23:27 UTC
One reason I like the Jetpack Carousel is because the Tiled Gallery is the most elegant out there. Secondly, I think the carousel itself is pretty nice on a desktop computer, and anything I don't like is easily solved with CSS.

But on to what I don't like... I don't like the way the carousel works on mobile, especially on a smartphone. To me it's a little clunky to try to navigate with the arrows, especially being used to swiping full-screen, the way Facebook displays images from a gallery. 

For the time being, I've found a solution in a plugin called PhotoSwipe Masonry, though their tiled galleries aren't nearly as elegant. This leads to the next issue/request that I have, that I'm not solving with PhotoSwipe...

It would be very beneficial to be able to launch a mobile-friendly swipe gallery from a single link... either a text link, a button, or the link applied to a single image. And of course having the option of doing this while the tiled thumbnail gallery is hidden. As a photographer, it would be nice to show a few strong images in the post, then have a link to the rest of the images in the story. 

This would created a clean, strong presentation, and bring me back to Jetpack Carousel pretty quickly.

**Comment by jeherve** [comment] 2017-01-11 20:26
> To me it's a little clunky to try to navigate with the arrows, especially being used to swiping full-screen, the way Facebook displays images from a gallery.

Jetpack's Carousel already supports swiping on mobile devices. I've just tested it in Chrome on an Android device and it works well.

If that doesn't work for you, could you give me an example of a gallery where you experience issues, and let me know what mobile device you used?

> It would be very beneficial to be able to launch a mobile-friendly swipe gallery from a single link... either a text link, a button, or the link applied to a single image. 

That makes sense. How would you imagine the interface to look like for such a feature? How would one go about creating a gallery, but not actually inserting the gallery into the post or page?

**Comment by humanfiles** [comment] 2017-01-11 22:01
Yes, you are right, Carousel does support swipe. Let me explain a bit further. I'm viewing with an iPhone 6. 

When I launch the Jetpack Carousel on my iPhone, I get something that kind of resembles what I might experience on a desktop. The biggest issue would be that the image doesn't fill the entire screen, regardless of whether it's vertical or horizontal. Also, or maybe as a result, the header and footer of the browser (in this case, Safari for mobile) remain visible. When you turn the device to view the gallery horizontally, the footer and header does disappear, only to reappear when you move to the next image by touching the current image. In my experience, it's very touchy. The footer ends up blocking part of the image, and doesn't go away until you restart the gallery. It ends up being an interrupted experience, and I find it discouraging to try to show a gallery when passing my device to someone else to view.

Perhaps with the extensive use of Facebook I've been conditioned to view galleries in full-screen, navigate with a simple swipe, the header and footer disappears, and the images respond when turning the device vertically or horizontally. But that happens to be the easiest, most enjoyable experience. (Really note the way Facebook galleries work on mobile in comparison.)  As the result, I've turned to a plugin like PhotoSwipe Masonry, which replicates the Facebook experience quite well. I just don't like the PhotoSwipe Tiled Galleries as much as Jetpack.

And speaking of the thumbnail gallery, here's how I envision it working. It's simple... in the window where you create a gallery, a "Hide Thumbnail Gallery?" checkbox would be great. If this is checked, then a window could provide a URL to be used to create the link that would specifically launch that gallery. The reason I think this would be a good option is that a photographer (or any information source, really) might want to show a few strong images in a post to support a story, but then follow up with a link to the rest of the images, without the distraction of the thumbnail gallery. 

Lastly, one thing that I didn't mention is that it might also be nice to have the option of the carousel being a free-running slideshow. That's not a priority to me, but it would be nice. 

I'm coming from the position of a photographer who wants control over the way galleries are displayed; plus I curate an online photo magazine, where I'm managing many galleries. Aesthetics are important. I think Jetpack Carousel is a great product, but it's just not doing it for me on mobile.

Thanks for responding! I hate to complain about good plugins, but I'm sure you guys like real-world opinions based on usage and experience.

**Comment by jeherve** [comment] 2017-01-12 14:09
> Also, or maybe as a result, the header and footer of the browser (in this case, Safari for mobile) remain visible. When you turn the device to view the gallery horizontally, the footer and header does disappear, only to reappear when you move to the next image by touching the current image.

I'm afraid that's the default mobile browser behaviour. You can check on other sites, but I believe that's the expected behaviour. The header and footer menus disappear as you scroll down the page (at least that's how it works on Android, I can't speak for iOS.)

> Perhaps with the extensive use of Facebook I've been conditioned to view galleries in full-screen, navigate with a simple swipe, the header and footer disappears, and the images respond when turning the device vertically or horizontally. But that happens to be the easiest, most enjoyable experience. 

While that's true for the native Facebook app, browsing Facebook in a mobile browser doesn't offer that full-screen experience since they face the same limitations.

[PhotoSwipe Masonry](https://wordpress.org/plugins/photoswipe-masonry/), however, has a solution that is far better than Facebook or Jetpack's Carousel on mobile, I agree. It looks as good as Facebook's native app experience.

I think it would be nice to implement something like this whenever we iterate on the current version of Carousel.

Here are a few visuals to make things clearer, and so we know what to aim for. The actual pictures are just examples, ignore that :)

**Carousel today**:

![carousel](https://cloud.githubusercontent.com/assets/426388/21891932/580b040c-d8d5-11e6-873e-163c9a4ad935.png)

**Facebook Mobile**:

![facebook-mobile](https://cloud.githubusercontent.com/assets/426388/21891944/61e5e6e0-d8d5-11e6-8957-d356294b0f20.png)

**Facebook App**:

![facebook-app](https://cloud.githubusercontent.com/assets/426388/21891954/74f5c462-d8d5-11e6-8372-ca1469b79af9.png)

**PhotoSwipe Masonry**:

![photoswipe-masonry](https://cloud.githubusercontent.com/assets/426388/21891961/80bf6faa-d8d5-11e6-854b-464edd2de06a.png)

> And speaking of the thumbnail gallery, here's how I envision it working. It's simple... in the window where you create a gallery, a "Hide Thumbnail Gallery?" checkbox would be great. If this is checked, then a window could provide a URL to be used to create the link that would specifically launch that gallery. 

I'll create a new GitHub issue for this, to avoid losing some of your suggestions. We try to keep each issue focussed on one bug / feature, so I'll create separate issues for your other suggestions.

-> #6081 - Carousel: provide option to hide gallery behind a link

> one thing that I didn't mention is that it might also be nice to have the option of the carousel being a free-running slideshow.

Moved to #6082

**Comment by humanfiles** [comment] 2017-01-14 20:38
Yes, when I was speaking of mobile, I was only considering the behavior of the mobile app, not mobile browser access.

Thanks for considering these changes!

**Comment by krogsgard** [comment] 2017-03-13 15:57
A primary problem with Carousel on mobile devices is that the image is often no larger or simpler to see once it receives "focus" versus viewing the gallery, and then if you try to pinch or manually zoom / magnify the image, it is completely broken.

Below are two images, one with default focus, then one with focus + zoom.

![2017-03-13 10 40 28](https://cloud.githubusercontent.com/assets/787877/23862131/3bebbbf2-07da-11e7-9eaf-49eb1c2f9a16.png)
![2017-03-13 10 40 22](https://cloud.githubusercontent.com/assets/787877/23862130/3bea8732-07da-11e7-95da-29f7d61b2ab5.png)

In the second scenario (zoom or magnify after focus), doing this action does not allow for moving around the image, and often times goes to some other image. Also note how the zoomed image isn't centered, which is what happens by default, and trying to center it by dragging it just causes more problems. In short, it's totally broken.

Compare that experience to PhotoSwipe, which I believe has a terrifix UX.

![2017-03-13 10 44 01](https://cloud.githubusercontent.com/assets/787877/23862129/3be7d46a-07da-11e7-997a-cfba9b863755.png)
![2017-03-13 10 43 54](https://cloud.githubusercontent.com/assets/787877/23862132/3bed6a56-07da-11e7-97d0-f75a3bf9adce.png)

First off, the initital focus on an image is full width. In Jetpack, the padding on left and right delude the whole point of focus, often times making (landscape especially) images tiny. In this instance, you get full phone bleed, and it rotates nicely if you change the phone to landscape. Jetpack leaves close to 50% of the screen empty when the phone is rotated to landscape.

PhotoSwipe:
![2017-03-13 10 51 21](https://cloud.githubusercontent.com/assets/787877/23862534/3e7b5a70-07db-11e7-9904-e0f3abad45ae.png)

Jetpack:
![2017-03-13 10 50 56](https://cloud.githubusercontent.com/assets/787877/23862535/3e7c59fc-07db-11e7-99e5-4ff19da5a3d5.png)

Finally, there are several general touch and gesture issues that are complicated on Jetpack and not on some other gallery options. I often find myself trying to do one thing, and something else happens. It's hard to pin down exactly what, but I just know that when I view a mobile gallery using Jetpack, it makes me sad and that's not an ideal emotion :)

Hopefully this helps this conversation some.

More broadly, I think a great modal experience would be core material, and I wrote about some of what's out there right now, if it's helpful for reference. It's an older post that doesn't get into as much of the mobile part of the UX, but I was asked by a Jetpack team member to include a link to it here. 
https://make.wordpress.org/test/2015/02/26/core-support-for-wordpress-images-to-open-in-a-modal-window/

Cheers!

**Comment by konepartners** [comment] 2018-03-28 15:58
Hello,
I totally agree with the humanfiles and krogsgard view on the Carousel behavior.
While it is really perfect on a browser, it is not the case on an Android mobile.
Only one example, when a picture is (even a bit) to small to fit the screen and you enlarge it, this action complety mess up the behavior of the carousel. And do not try to swipe at that time, the workflow is lost.
What I see as a perfect carousel example is the way 500px.com shows gallery... that is very nice and usable. I invite you to have a look at 500px.com
Since this topic has been raised one year ago, would you telle me if sth has been enhanced since. Is it the case ? 
Note: Do not get it wrong, I like and I use Jetpack every day, that is maybe why I would like to see it being enhanced where it needs to be :-)
Cheers,
Xavier

**Comment by ga5tan** [comment] 2018-06-26 08:59
is there any progress in this ?
I would also love for mobile(android) view for picture to fill whole screen and just swipe it right left, pinch to zoom ???

**Comment by antermoia** [comment] 2021-01-20 16:38
Adding my vote to improve Carousel on mobile, which I also brought up here:

[https://wordpress.org/support/topic/carousel-on-mobile-3/](https://wordpress.org/support/topic/carousel-on-mobile-3/)

**Comment by fabiankessler** [comment] 2021-04-04 00:39
+1

I have a free site on wordpress.com and this carousel is used, there is no other option. Pictures use not even 50% of the pixels on mobile, makes it useless for me. Also on tablet and desktop it's not enough, feels old, but I could live with that.

**Comment by apeatling** [comment] 2021-06-22 17:36
This will be addressed in https://github.com/Automattic/jetpack/pull/20107

**Comment by ga5tan** [comment] 2021-06-22 18:15
wow, that would be great.
Is it just coming in next JetPack update? Or how do we get it?
Does it have to be switched as default viewer or will it auto default to be used?

**Comment by apeatling** [comment] 2021-06-22 18:17
The goal is to get it in before the code freeze for the next Jetpack version. If that happens it will be in the next version and it will replace the existing carousel automatically.

**Comment by ga5tan** [comment] 2021-06-22 18:21
What freeze? It's 31C here :)

**Comment by jeherve** [comment] 2021-06-22 18:27
@ga5tan True! We'll attempt a [freeze](https://en.wikipedia.org/wiki/Freeze_(software_engineering)) anyway ;) . The next one is scheduled for June 28, 2021. Having that change ready by that date would allow us to make it available to [all Beta testers](http://jetpack.com/beta) for a week, and then to have the change available to everyone in the next major release of Jetpack, on July 6, 2021.

If all our changes aren't ready by that date, we'll keep working on them and aim to make them available in the next version of Jetpack, in the beginning of August.

**Comment by ga5tan** [comment] 2021-06-22 18:35
I'll keep my fingers crossed. I could betatest, but u prolly have plenty of those, right?

**Comment by jeherve** [comment] 2021-06-23 08:16
> I'll keep my fingers crossed. I could betatest, but u prolly have plenty of those, right?

There are already people who will test indeed, but we're always happy to get more feedback, from more people! :)

**Closed** 2021-06-29 13:42 UTC
Labels: Carousel, [Pri] Low, [Status] In Progress, [Status] Proposal, [Type] Feature
