### ISSUE TITLE
Slideshow block: Full width and wide width display shows scaled down images

### ISSUE THREAD

**Issue by benchilcote** [Automattic/jetpack#12178] opened 2019-04-25 10:47 UTC
_Jump to most recent technical analysis from June 2022: https://github.com/Automattic/jetpack/issues/12178#issuecomment-1157025213_

#### Steps to reproduce
1. Activate a twenty nineteen child theme
2. Create a page/post
3. Add new Slideshow Block and add one or more large images
4. Set display mode to full width
5. Publish and view page

#### What I expected

I expected the images to extend to the edge of the browser window.

#### What happened instead

The images are displayed as a scaled down version surrounded by grey space.  

Note: This happens with wide width display as well.

#### Screenshot / Video

![Annotation on 2019-3-4](https://user-images.githubusercontent.com/11636210/56730224-61933900-6725-11e9-8199-960420f042d8.png)

![Screen Shot 2019-04-25 at 6 25 08 AM](https://user-images.githubusercontent.com/11636210/56730240-6f48be80-6725-11e9-84c8-d886c064f3a5.png)

![Screen Shot 2019-04-25 at 6 19 46 AM](https://user-images.githubusercontent.com/11636210/56730254-78399000-6725-11e9-8e60-d036f43d8037.png)

![Screen Shot 2019-04-25 at 6 20 49 AM](https://user-images.githubusercontent.com/11636210/56730271-84bde880-6725-11e9-951c-aa11baa6d13e.png)

#### Other

#1984153-zen

**Comment by liviopv** [comment] 2019-06-12 14:56
I was able to reproduce this reliably on all the WordPress.com Gutenberg-ready themes on a simple site.

**Comment by liviopv** [comment] 2019-06-12 15:50
Also reproduced with a fresh jurassic.ninja site:

![Screenshot](https://cld.wthms.co/f5JiWQ+)
Screenshot: https://cld.wthms.co/f5JiWQ

**Comment by blazevivan** [comment] 2019-06-12 17:41
I was able to find the thread where we tried to find out more about this bug. 

One example from the user's site: https://cld.wthms.co/ZwmZEb

**Comment by eduardozulian** [comment] 2019-07-06 16:05
The thing is that we're making the wrapper full-width but keeping the images with a max-size of 100%. A workaround, for now, is to force this with some custom CSS:

```
/* Slideshow Full Width block: make the images full width as well */
.wp-block-jetpack-slideshow.alignfull .wp-block-jetpack-slideshow_image {
  width: 100vw;
  max-width: unset;
  object-fit: cover;
}
```

Result:

<img width="872" alt="Captura de Tela 2019-07-06 às 13 05 11" src="https://user-images.githubusercontent.com/1136160/60758568-bb9a5f80-9fee-11e9-954f-07647040479c.png">

**Comment by liviopv** [comment] 2019-07-19 16:00
Also reported in 2192074-zen on the Olsen theme.

Sent a mod on Edu's code above as a workaround

**Comment by arunsathiya** [comment] 2019-11-25 15:42
2516263-zen. Shared @eduardozulian's CSS workaround for now.

**Comment by GeoJunkie** [comment] 2019-12-22 19:55
Brought up during a Quick Start Session. Provided to user in 2579322-zen

**Comment by kriskorn** [comment] 2020-01-15 06:59
Another report in 2633401-zen.
Provided Eduardo's workaround.

**Comment by aisajib** [comment] 2020-02-05 07:15
The user at #18347729-hc faced the same issue. Provided the CSS from above.

**Comment by neo22s** [comment] 2020-04-28 00:08
> The thing is that we're making the wrapper full-width but keeping the images with a max-size of 100%. A workaround, for now, is to force this with some custom CSS:
> 
> ```
> /* Slideshow Full Width block: make the images full width as well */
> .wp-block-jetpack-slideshow.alignfull .wp-block-jetpack-slideshow_image {
>   width: 100vw;
>   max-width: unset;
>   object-fit: cover;
> }
> ```
> 
> Result:
> 
> <img alt="Captura de Tela 2019-07-06 às 13 05 11" width="872" src="https://user-images.githubusercontent.com/1136160/60758568-bb9a5f80-9fee-11e9-954f-07647040479c.png">

thanks, but not sure why is not taking the fulls size image and it uses a resized version = ?resize=768%2C512

strange and ugly bug

**Comment by edequalsawesome** [comment] 2020-04-29 20:58
Also reported in #20693968-hc, provided CSS as a workaround

**Comment by neo22s** [comment] 2020-04-29 21:05
> Also reported in #20693968-hc, provided CSS as a workaround

did it work for you?

**Comment by eduardozulian** [comment] 2020-05-05 19:39
@neo22s it's not taking the full size because this particular CSS code does not alter how WordPress is loading the image. Try to change your content width to a higher number under Customizer > CSS > Media Width and see if that helps.

**Comment by eduardozulian** [comment] 2020-07-10 13:08
Reported on 11677309-hc

**Comment by neo22s** [comment] 2020-07-10 13:28
```
function composer_child_setup_theme() {
$GLOBALS['content_width'] = 2000;
}
add_action( 'init', 'composer_child_setup_theme' );
```

this did work

**Comment by KristinaKay** [comment] 2020-07-10 15:34
Another case here: #3112051-z. Provided CSS workaround.

**Comment by zdenys** [comment] 2020-07-22 10:47
Another case 3153628-zen. Provided CSS workaround.

**Comment by kathleenjross** [comment] 2020-08-05 16:48
Another case with 23161957-hc. Provided CSS workaround.

**Comment by carinapilar** [comment] 2020-11-12 13:37
Another case on 25586681-hc. The workaround with the CSS fixed it.

I also would like to add that if you're working with **an Atomic site**, you might want to disable Performance & speed > Enable site accelerator > Speed up image load times, since when that's active you get a very small image in the Slideshow:

![SlideshowWithPerformanceEnabled](https://user-images.githubusercontent.com/16104522/98946577-d0381300-24d2-11eb-84f7-aae84d192e56.png)

**Comment by lakellie** [comment] 2020-12-16 17:15
Another request in 26092400-hc

**Comment by jeherve** [comment] 2021-01-11 11:36
Also reported in p8oabR-B4-p2#comment-4875

**Comment by synora** [comment] 2021-02-02 11:01
Also reported in 25918060hc.

**Comment by scosgro** [comment] 2021-02-18 00:47
Also reported in #3746575-zen

**Comment by zdenys** [comment] 2021-02-19 09:09
Another report in 12055082-hc.

**Comment by tbradsha** [comment] 2021-03-03 18:51
26799118-hc

**Comment by zdenys** [comment] 2021-05-06 10:09
29433467-hc

**Comment by mikeicode** [comment] 2021-08-05 13:22
30981984-hc

**Comment by Greatdane** [comment] 2021-08-10 23:35
29564878-hc

**Comment by donalirl** [comment] 2021-08-11 00:19
I had a customer who could use this feature. I gave a CSS fix that they were very happy with. Ref: #31066278-hc

**Comment by jordesign** [comment] 2022-02-03 07:08
Confirming I am still able to recreate this.

**Comment by rickmgithub** [comment] 2022-03-20 10:50
Same again here 4876778-zd

They wanted to make the images fit the whole slideshow block but on experimenting the images when set to full sizes ended up like this 

<img width="1585" alt="Markup 2022-03-20 at 10 48 00" src="https://user-images.githubusercontent.com/13706336/159158701-0c4eca80-f105-4cce-a1ef-2149868b7206.png">
 
They wanted to expand the image as well to make it bigger but both CSS code workarounds didn't work for this site on Rivington theme.

**Comment by danielbachhuber** [comment] 2022-06-15 22:52
## Debugging

I _think_ I was able to recreate the issue on a WoA site with the following steps:

1. Switched theme to Twenty Nineteen.
2. Created a new test post and added a Slideshow block:
    1. Uploaded two images with 4000+ px width.
    2. Changed the alignment to 'Full Width' and image size to 'Full Size'.

<img width="1742" alt="image" src="https://user-images.githubusercontent.com/36432/173941575-36bb9117-04a6-47ae-90fb-f924458803d0.png">

3. Observed that the Slideshow block doesn't span full width on the frontend:

<img width="1689" alt="image" src="https://user-images.githubusercontent.com/36432/173942701-242688a9-5978-4b5e-a4e4-c486b06e4bd0.png">

4. Switched the Slideshow block to 'Wide Width' and observed the same problem:

<img width="1709" alt="image" src="https://user-images.githubusercontent.com/36432/173942616-7be7c841-b106-4fb1-930e-a83bf4b9841c.png">

I was able to recreate the same problematic behavior in a local environment with Jetpack in Offline Mode.

## Analysis

The images display full width in Twenty Nineteen with the following CSS:

```
.wp-block-jetpack-slideshow.alignfull .wp-block-jetpack-slideshow_slide {
	display: flex;
}

.wp-block-jetpack-slideshow.alignfull .wp-block-jetpack-slideshow_slide .wp-block-jetpack-slideshow_image {
	max-width: none;
	max-height: none;
}
```

The [originally suggested CSS](https://github.com/Automattic/jetpack/issues/12178#issuecomment-508936857) also works in my testing:

```
.wp-block-jetpack-slideshow.alignfull .wp-block-jetpack-slideshow_image {
	width: 100vw;
	max-width: unset;
	object-fit: cover;
}
```

<img width="1730" alt="image" src="https://user-images.githubusercontent.com/36432/173949344-8457df51-1558-41c4-a0e8-c057dce11467.png">

## Next Steps

To fully resolve the issue, I might suggest these steps:

1. Look at other blocks to see how they handle `alignfull` and `alignwide`.
2. Look at recent CSS changes in Jetpack to see how they're evaluated.
3. Determine expected width for `alignwide` with the Slideshow block.
4. Produce CSS for `alignfull` and `alignwide`.
5. Test CSS against a variety of theme contexts.

**Comment by msilbers** [comment] 2022-06-30 19:32
reported in 35949201-hc
provided the CSS workaround for now

**Comment by csabarakasz** [comment] 2022-07-25 09:07
Same issue:

- [ ] 23372705-hc

Additional note. The slideshow was working fine. The user installed the hidden page and post title plugin and the slideshow broke. Removed, and deleted the plugin, but the slideshow stayed broken!

**Comment by coder-karen** [comment] 2022-07-25 09:28
The fix for this issue will be in the next Jetpack release (11.2, Aug 2), and before that in the Jetpack Beta release (Tues 26th July). The Beta release will also be offered to WoA sites so this fix may be live on those sites before the end of this week.

@csabarakasz I installed that plugin ('Hide page and post title') on a test site and it didn't seem to break the slideshow there so it looks like there could be other factors at play (theme, other plugins). If it came up again though and doesn't appear to be site specific feel free to add this information to another issue.

**Comment by aisajib** [comment] 2022-08-08 08:32
Forgive me if this isn't the right place (Happy to open a new issue), but I noticed the Slideshow block now crops the images when full-width is selected. I believe that, unlike Cover blocks, Slideshow blocks should show the image in full without cropping in. Could you check and see if it's related to this or if I should open a new issue?

**Comment by danielbachhuber** [comment] 2022-08-08 11:20
@aisajib Can you share the specific example you're referring to?

**Comment by aisajib** [comment] 2022-08-08 13:17
> @aisajib Can you share the specific example you're referring to?

Sure! Sorry! This was reported by the user on live chat. You can see it replicated on my test site here: https://wptutos.wordpress.com/2022/08/08/slideshow-block/

You'll notice when the block is Full Width, the image is significantly cropped. It's keeping the same aspect ratio, but I think keeping the image appearing in full should be the priority?

**Comment by danielbachhuber** [comment] 2022-08-08 13:27
> Sure! Sorry! This was reported by the user on live chat. You can see it replicated on my test site here: pHW9b-1B5-p2

@aisajib Great! I can see what you're referring to:

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/36432/183427174-b6805578-3c56-4a22-8bfd-f97eb2264f3e.png">

vs. 

<img width="1393" alt="image" src="https://user-images.githubusercontent.com/36432/183427243-a1fd21b7-0f9d-4245-9f22-a356364b01ec.png">

> You'll notice when the block is Full Width, the image is significantly cropped. It's keeping the same aspect ratio, but I think keeping the image appearing in full should be the priority?

The product decision we made was actually the opposite: when the block is full width, the image is scaled to fit the width and cropped if necessary.

If the customer wants to "undo" this change across their entire site, this CSS will do the trick:

```css
.wp-block-jetpack-slideshow.alignfull .wp-block-jetpack-slideshow_container .wp-block-jetpack-slideshow_image {
	max-width: inherit;
	width: auto;
}
```

From p9cu9o-3ww-p2

**Comment by aisajib** [comment] 2022-08-08 13:45
Thanks @danielbachhuber ! I assume the user can't make the images go full width while showing the full, uncropped images? That's what the user wants, basically. The images should go full width, but they should not be cropped.

**Comment by danielbachhuber** [comment] 2022-08-08 15:30
> I assume the user can't make the images go full width while showing the full, uncropped images? That's what the user wants, basically. The images should go full width, but they should not be cropped.

@aisajib Your assumption is correct — this isn't easily possible at this time.

**Comment by aisajib** [comment] 2022-08-08 16:02
Thank you! I appreciate the help here. :) I've passed this on to the user and suggested some workarounds.

**Comment by edwinho89** [comment] 2022-08-12 03:48
Just want to add this chat: 36435810-hc raised the same inquiry as what @aisajib pointed out. 

Shared workaround on the above. Perhaps having an option to toggle cropping or not would on full width would fit the best of both worlds?

**Comment by danielbachhuber** [comment] 2022-08-12 12:19
> Just want to add this chat [...] raised the same inquiry

Thanks for letting us know!

> Perhaps having an option to toggle cropping or not would on full width would fit the best of both worlds?

We decided against it (https://github.com/Automattic/jetpack/pull/25107#issuecomment-1189434235) but may reconsider depending on how much feedback comes in.

**Comment by ariel-maidana** [comment] 2022-09-13 19:31
On a site, images appear zoomed in both if the Alignment is set to "None" or "Align Center".
5548552-zd-woothemes
Please inform the user of any new fixes and workarounds.

**Comment by danielbachhuber** [comment] 2022-09-13 19:44
@ariel-maidana Given the age of this issue, can you open a new issue with the full details and steps to reproduce? Feel free to cc me and I'll look at it when I have some time.

**Closed by danielbachhuber** 2022-09-13 19:44 UTC
Labels: [Type] Bug, [Status] In Progress, [Focus] Blocks, [Block] Slideshow, [Type] Happiness Request, Build Maintenance

**Comment by ariel-maidana** [comment] 2022-09-13 19:59
@danielbachhuber Thank you! Reported it here: https://github.com/Automattic/themes/issues/6581
