### ISSUE TITLE
Slideshow block doesn't play well inside vertical aligned columns

### ISSUE THREAD

**Issue by mrleemon** [Automattic/jetpack#14524] opened 2020-01-30 10:38 UTC
#### Steps to reproduce the issue

1. Add a columns block (using the 50%-50% layout preset)
2. Add a slider block inside one of the columns and add some images to it
3. Set a vertical alignment in the columns block (top, center or bottom)

#### What I expected
A usable slider block 

#### What happened instead
The slider block disappears

**Screenshots**

![alignment-none](https://user-images.githubusercontent.com/2060659/73442207-a69f6800-4354-11ea-8798-802883c96a54.jpg)
![alignment-top](https://user-images.githubusercontent.com/2060659/73442215-aacb8580-4354-11ea-9fa6-291024fc0a85.jpg)
![alignment-center](https://user-images.githubusercontent.com/2060659/73442219-ac954900-4354-11ea-8943-cd2f86ed29e8.jpg)
![alignment-bottom](https://user-images.githubusercontent.com/2060659/73442221-adc67600-4354-11ea-9848-848c11f6ea15.jpg)

I'm using WP 5.3.2 with the Twenty Twenty theme and Jetpack 8.1.1

**Comment by mrleemon** [comment] 2020-01-30 11:46
Tried this with the latest Firefox (72) and Chrome (79) with equal results.

**Comment by mrleemon** [comment] 2020-01-30 12:11
If I add `width: 100%` to the `.wp-block-column.is-vertically-aligned-top`, `.wp-block-column.is-vertically-aligned-center` and `.wp-block-column.is-vertically-aligned-bottom` CSS rules in Gutenberg the slider block works as expected:

```
.wp-block-column.is-vertically-aligned-center {
    align-self: center;
    width: 100%; /* new */
}
```

Maybe this is a fix for Gutenberg itself, not Jetpack.

**Comment by jeherve** [comment] 2020-01-30 13:23
> Maybe this is a fix for Gutenberg itself, not Jetpack.

Since it happens on WP 5.3.2, even when the Gutenberg plugin is not active, we will most likely need to come up with a patch until the problem is fixed in Gutenberg and then WordPress Core.

**Closed** 2020-04-27 11:24 UTC
Labels: Gutenberg, [Block] Slideshow, [Pri] Normal, [Type] Bug, [Type] Happiness Request
