### ISSUE TITLE
Admin Page: Cannot activate Widget Visibility module with "Plain" permalinks

### ISSUE THREAD

**Issue by jubstuff** [Automattic/jetpack#4522] opened 2016-07-24 18:11 UTC
#### Steps to reproduce the issue

1. Set permalinks to _Plain_
2. Activate Jetpack
3. Try to activate the _Widget Visibility_ module

#### What I expected

The _Widget Visibility_ module to be activated

#### What happened instead
Nothing.

In the error console I get:

```
PUT http://test.dev/?rest_route=/jetpack/v4/module/widget-visibility/activate 405 (Not Allowed)
```

That URL returns this

```
{
    "code": "rest_no_route",
    "message": "No route was found matching the URL and request method",
    "data": {
        "status": 404
    }
}
```

Setting permalinks to whatever value makes it work again.

**Comment by jeherve** [comment] 2016-07-25 09:14
Could you let me know what version of Jetpack you're currently using?

Thanks!

**Comment by jubstuff** [comment] 2016-07-25 09:24
Hello @jeherve,

This was with the latest commit in the `master` branch, version _4.3-alpha_ :)

**Comment by jeherve** [comment] 2016-07-25 09:35
Could you try switching to `master-stable`, and let me know if it helps?

**Comment by jubstuff** [comment] 2016-07-25 18:04
No, it doesn't help.

It seems that without pretty permalinks those routes don't work.

Other endpoints are working, though.

http://test.dev/?rest_route=/
http://test.dev/?rest_route=/jetpack/v4/connection-status

**Comment by eliorivero** [comment] 2016-07-29 14:49
Can't reproduce the issue, works fine for me with default permalinks. It's odd that this wouldn't work specifically for Widget Visibility module activation, it should fail for every module activation. 

Regarding default permalinks, we don't use query variables in the endpoints that might affect the URL (since default permalinks use the rest_route query variable). Also, we don't respond with a 405 error in our endpoints so if something is replying that, it must be the REST server. I also activated the latest [REST API](https://github.com/WP-API/WP-API) plugin to see if it was conflicting somehow but it's ok. Finally the phrase "Not Allowed" is not found in WordPress core or Jetpack so I'm not sure where that is coming from.

I'm closing this for now, if you have any extra information not shared previously that might help to reproduce the issue, feel free to reopen it.

**Closed by eliorivero** 2016-07-29 14:49 UTC
Labels: Admin Page, Widget Visibility, [Type] Bug
