### ISSUE TITLE
Admin UI: Use descriptive class names

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#15405] opened 2020-04-10 18:58 UTC
#### Is your feature request related to a problem? Please describe.

Yes. VIP reported that they were not able to target a setting within our admin UI to customize the styling, in this case hiding the toggle.  I was able to roughly clobber something together with this:

```
.jp-settings-container div[title="Performance"] ~ .jp-form-settings-card .jp-form-settings-group .jp-form-fieldset { display: none; }
```

But, it doesn't work in all cases, it likely doesn't work on non-English sites, and there are likely side effects where we're hiding other things. 😞 

#### Describe the solution you'd like

It'd be ideal if each of our settings section had a class name that described what the setting was for. For example, for the settings card for Search it might be ideal if the card had a class name like `.search` or `.jetpack-module-settings-search`. With that in place, we'd then allow much more flexibility in styling for VIP or others.

#### Describe alternatives you've considered

N/A

#### Additional context

N/A

**Comment by jeherve** [comment] 2020-04-14 10:43
Closing as duplicate of #5693.

**Closed** 2020-04-27 10:22 UTC
Labels: Admin Page, [Type] Enhancement
