### ISSUE TITLE
Sizes Attribute Missing When Using Photon with RICG Responsive Images

### ISSUE THREAD

**Issue by devinsays** [Automattic/jetpack#2804] opened 2015-10-03 21:23 UTC
I've been testing out the RICG Responsive Images plugin (https://wordpress.org/plugins/ricg-responsive-images/) since it is being proposed for merge into WordPress core.

When both Photon and RICG Responsive Images are activated, it appears that the "sizes" attribute is removed from images. This is leading to much larger images being loaded than required (at least in the themes I tested with).

I'll cross post this on this to the RICG repo, I just thought it'd be worth taking a look at.

**Comment by devinsays** [comment] 2015-10-03 21:31
Posted this issue to RICG repo along with example markup showing the issue: https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/issues/204

**Comment by joemcgill** [comment] 2015-10-03 21:49
For performance reasons, we recently switched from using `wp_get_attachment_image_src` to `image_get_intermediate_size` to retrieve the `width` value of an attachment. Photon alters the width value that is returned to `wp_get_attachment_image_src` via a filter on `image_downsize`, which was allowing us to short-circuit the calculation of the srcset.

You can see the changeset here: https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/commit/c3057fb90c518aeef4c1ed248a93a22c1193ebf7

When/if our functionality is merged into core, Photon should be able to filter out `srcset` and `sizes` attributes directly.

**Comment by kraftbj** [comment] 2015-10-05 14:45
@joemcgill I haven't dug into this to grok the issue, but it is related/duplicate of #2281 ?

**Comment by joemcgill** [comment] 2015-10-05 14:54
Hi @kraftbj. This is a separate, but related, issue to #2281. It's likely that Photon will need to filter the values of `srcset` and `sizes` attributes once those attributes become natively supported in core. In earlier implementations of our plugin, `srcset` and `sizes` wouldn't get added to an image if the height and width values coming from `wp_get_attachement_image_src` had been filtered to return `0`.

**Comment by kraftbj** [comment] 2015-10-07 21:42
Nothing that this must land in 3.8 as RICG has been merged into Core for a 4.4 (Dec 8th) release.

**Comment by joemcgill** [comment] 2015-10-08 00:52
@kraftbj The original issue as reported has been fixed in trunk. The next question is how Photon wants to interact with `srcset` and `sizes` in core. If those attributes are unnecessary when Photon is enabled, you could remove the `wp_make_content_images_responsive` function from the `the_content` filter. You may also want to remove those attributes from galleries and an other dynamically generated images by adding a filter to `wp_get_attachment_image_attributes`.

**Comment by kraftbj** [comment] 2015-10-29 03:02
I believe this is fixed as of #2885 and #2915. I'm going to open a new ticket for converting Photon to use srcset's pixel density descriptor instead of our JS solution, aiming for that to be a bit longer down the road (the release after the one in dev).

The two PRs basically lets the 4.4 core functionality work, filtering the srcset through Photon to make all image variations served through the CDN.

If I miss anything, either ping me to reopen this or open a new ticket. Thanks all!

**Closed by kraftbj** 2015-10-29 03:02 UTC
Labels: bug, Photon
