### ISSUE TITLE
Comments: Unable to comment using Facebook, Twitter, Google accounts.

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/jetpack#18227] opened 2021-01-07 10:04 UTC
#### Steps to reproduce the issue

1. Enable Jetpack Comments
2. Visit a post and go to the comment form.
3. Try to connect to Facebook, Twitter, or Google

#### What I expected

The connection would succeed and I would be able to comment.

#### What happened instead

For Facebook and Twitter, the authorization just loads forever after logging in:

![image](https://user-images.githubusercontent.com/1990037/103879211-75d0c280-50cf-11eb-8d08-a3eab06ea954.png)

For Google, it appears to connect, but then just displays the usual comment form again.

Test site example: https://prominent-cormorant.jurassic.ninja/2021/01/06/hello-world/

Also reported here:

- https://wordpress.org/support/topic/unable-to-connect-social-to-post-comment/
- https://wordpress.org/support/topic/social-authentication-not-working-for-jp-comments/

**Comment by jeherve** [comment] 2021-01-07 10:06
Closing as duplicate of #15030

**Closed by jeherve** 2021-01-07 10:06 UTC
Labels: Comments
