### ISSUE TITLE
Lazy Load: clarify that the feature settings are available in 2 different interfaces

### ISSUE THREAD

**Issue by galakhyati** [Automattic/jetpack#24002] opened 2022-04-12 13:12 UTC
### Quick summary

When Jetpack's Lazy load setting is enabled and the Jetpack Boost plugin is installed and activated, it by default enables the Lazy Load setting under the plugin.

And when I turn off Lazy load from the Jetpack Boost plugin, it turns off from the Jetpack Settings too. They both are interlinked.

Ref chat: 34778200-hc, Follow up: 4940855-zen

### Steps to reproduce

1. Have WordPress.com → Settings → Performance → Enable Lazy Loading for images enabled.
2. Install Jetpack Boost plugin and activate it.
3. The Lazy Load setting from the plugin is activated automatically.
4. Turn off Lazy load from Jetpack Settings, it turns off under the Jetpack Boost plugin too.
5. Turning off Lazy load under Jetpack Boost turns off Lazy load under Jetpack.

### What you expected to happen

Didn't expect both the setting to be interdependent. Expected the setting to be stand-alone and work on its own.

### What actually happened

The settings are interdependent and cause confusion which one to use for the user. This also causes the images on the site to not load at some instance.

### Context

Customer report.

Internal reference and discussion as per potential next steps to avoid such confusion:
p1HpG7-fGP-p2

### Simple, Atomic or both?

Atomic

### Reproducibility

Consistent

### Severity

Most (> 50%)

**Comment by cuemarie** [comment] 2022-04-19 18:47
I'm not sure if this is a bug or the intended behavior - transferring to the Jetpack repo to get their weigh-in. 

Should sites on WordPress.com see the Lazy Load settings within the Jetpack Boost and under Settings > Performance work independently from one another?

**Comment by sdixon194** [comment] 2022-04-20 16:29
This is expected behavior - Jetpack Boost and Jetpack-the-plugin rely on the same underlying library to handle lazy loading, so toggling one will change the other and vice-versa. This is something that should definitely be improved on a UI/UX level though, since the confusion here is definitely understandable. Internal discussion: p1HpG7-fGP-p2

> This also causes the images on the site to not load at some instance.

This is likely unrelated to the Boost/Jetpack issue - it sounds like everyone else is able to view the images, but the issue seems to persist on a specific set of devices (but seems okay on an ipad?). Does it work on other mobile devices when connected to mobile data vs wifi? Can they see images loaded via lazy load on other sites aside from their own? Wondering if some network configuration or firewall setting is the issue.

**Comment by syhussaini** [comment] 2022-04-21 17:12
I am checking here to see if we have any updates on this issue.

**Comment by jeherve** [comment] 2022-04-22 11:22
I'm tempting to close this as invalid, since this is intended behaviour as discussed above. 

If there are still issues with images not loading on the site at times, I would recommend investigating in the ticket to find out more about this, and figure out what's causing it.

**Comment by jeherve** [comment] 2022-04-22 11:27
> this is intended behaviour as discussed above.

Internal reference and discussion as per potential next steps to avoid such confusion:
p1HpG7-fGP-p2

As per this post, I think I'll reopen this so this confusion can be addressed in the future.

**Comment by inaikem** [comment] 2022-04-26 05:41
Replying to the user via 4940855-zen to let them know JP and JP Boost lazy loading settings are interlinked their experience is expected behaviour.

**Closed** 2023-10-25 20:08 UTC
Labels: [Type] Enhancement, [Focus] Performance, [Status] In Progress, [Pri] Normal, [Feature] Lazy Images, Customer Report, [Package] Lazy Images, [Plugin] Jetpack, [Plugin] Boost, [Boost Feature] Lazy Images
