### ISSUE TITLE
Enhancement:Jetpack search 'author' query

### ISSUE THREAD

**Issue by erikdemarco** [Automattic/jetpack#21185] opened 2021-09-24 10:02 UTC
### Impacted plugin

Jetpack

### What

Please add support for author filtering and search query. when I have query_var ?s=keyword&author=x it will not search for author which break our site. We have a lot of author page indexed by Google. Because jetpack not support this, it show the same content. So we get duplicate content penalty.

Another use case is woocommerce multivendor cant use this to search product by author_id

**Comment by gibrown** [comment] 2021-09-24 18:30
Ya, right now we don't have any filtering by author supported: https://github.com/Automattic/jetpack/issues/17704 and https://github.com/Automattic/jetpack/issues/8563.

I'm going to close this issue as a duplicate of those two. I think we are getting closer to supporting this, but thanks for nudging us on it.

**Closed by gibrown** 2021-09-24 18:30 UTC
Labels: [Type] Enhancement, Search, Instant Search, [Plugin] Jetpack
