### ISSUE TITLE
Infinite Scroll: Not possible to choose 10 posts per page when theme sets posts_per_page in IS settings

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/jetpack#8300] opened 2017-12-04 17:44 UTC
#### Steps to reproduce the issue
1. Start with a site running a theme that includes a `posts_per_page` setting in the infinite scroll settings (eg. Dyad 2 https://dyad2demo.wordpress.com, which has 12 posts per page).
2. If testing on a self-hosted WordPress site, turn on infinite scroll. If testing on a WordPress.com site, it's on by default.
3. Add footer widgets to change the behaviour to click-to-scroll.
4. Change the posts per page setting to 8. Save and view site.
5. Change the posts per page setting to 10. Save and view site.
6. Change the posts per page setting to a higher number, like 14. Save and view site.

#### What I expected

I expected the posts per page setting to be followed.

#### What happened instead

The setting is mostly followed -- unless you set it to 10. 10 always seems to display whatever the theme's posts-per-page setting is instead. This happens even after you change it away from 10 (which is the WordPress default), then change it back again.

So with Dyad 2, setting the site to load 10 posts per page will load 12. With Sketch, setting the site to load 10 posts per page will load 9. 

This came up while testing a theme issue, but was not actually the issue the user was reporting. 

Related ticket: 4923-wpcom-themes

**Comment by jesscga** [comment] 2017-12-28 15:07
Reported in 852262-t

**Comment by juliasydnor** [comment] 2018-05-16 07:59
1161958-zen

**Comment by erricgunawan** [comment] 2018-05-16 08:11
1162441-zen

**Comment by rantoncuadrado** [comment] 2018-05-16 09:15
User in 1161958-zen says they have not the issue any longer.

**Comment by eduardozulian** [comment] 2018-05-16 18:19
Not sure if related, but had this with Baskerville on 1163735-zen

Apparently, clearing the cache worked for this user.

**Comment by erricgunawan** [comment] 2018-05-16 21:06
The case for the site in 1162441-zen is resolved. Confirming with the user now.

**Comment by eduardozulian** [comment] 2018-05-17 11:46
Oh, thanks for the info, @laurelfulford ! 🙌

**Comment by Robertght** [comment] 2018-07-11 10:28
Tortuga with its default 6 posts per page - 1273321-zen

**Comment by mlaetitia** [comment] 2018-07-11 17:00
Aquene also started to behave like this today. Checked WebArchive for the reported site and two days ago the homepage showed 40+ posts while today only 6 appear. 

4938829-hc / 1274249-zd

**Comment by laurelfulford** [comment] 2018-07-11 18:28
@mlaetitia I'm not sure that's the same issue as reported -- in it, they'd only run into this problem if they've set the posts per page to 10, but it looks like it's at 45.

There's also a theme report for this, here: 2421-wpcom-premium-themes. I'm going to move your report there, I'm betting something changed in the theme recently.

**Comment by zinigor** [comment] 2018-07-13 20:58
Just FYI: the problematic change that was reverted in r175426-wpcom was deployed again on Monday, and reverted on Wednesday, so the spike in related theme weirdness may have been caused by that. Please comment if the problem still persists.

**Comment by liviopv** [comment] 2018-07-18 13:57
@zinigor it fixed 1273321-zen at least. I'm going to check the other tickets later today and I'll let you know if we can go ahead and close it.

**Closed as completed** 2018-07-18 15:25 UTC
Labels: Bug, [Feature] Infinite Scroll, [Pri] Low
