### ISSUE TITLE
WP admin is styleless after updating to WordPress 5.0

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#10859] opened 2018-12-06 19:56 UTC
Reported in 1626248-zen

<blockquote>As soon as I upgraded my site to Wordpress 5.0 the backend went 'styleless'. I 
went through a process of turning off plugins, and when i turn off Jetpack it 
clears up the problem.</blockquote>
 
and then

<blockquote>It looks like WPMU Dev's Hummingbird create an issue with jetpack. When I deactivated Hummingbird, and reactivated Jetpack, the admin loaded, but looked "odd"... icons missing on the left admin bar, etc. I went into the site directory structure, and deleted Hummingbird's cached asset files, and all was good.</blockquote>
 
Note: I was unable to reproduce on my test site, but since I had just installed Hummingbird and went with the default settings, I don't know what settings combination could have caused this. Maybe something to do with the Asset CDN? Labeling as such for now.

**Comment by jeherve** [comment] 2018-12-06 20:07
Closing as duplicate of #10857. The problem should be solved now. The files were still being deployed. Emptying cache and trying again should work.

**Closed by jeherve** 2018-12-06 20:07 UTC
Labels: Admin Page, Asset CDN, [Type] Bug, [Type] Duplicate
