### ISSUE TITLE
Send to Email Sharing pop-up is not responsive

### ISSUE THREAD

**Issue by boboz** [Automattic/jetpack#8872] opened 2018-02-18 18:45 UTC
#### Steps to reproduce the issue
Jetpack 5.8
Place an email sharing icon after for example two other sharing icons. View on a small screen .

#### What I expected
Responsive behaviour of the send to email sharing pop-up

#### What happened instead
No responsive behaviour of the send to email sharing pop-up. See image below.

![email-sharing2](https://user-images.githubusercontent.com/141707/36355093-0da2fb36-14de-11e8-94f1-0397ad0cdc8a.PNG)

**Comment by jeherve** [comment] 2018-09-05 11:05
Closing as duplicate of #6617

**Closed by jeherve** 2018-09-05 11:05 UTC
Labels: Sharing, [Pri] Low, [Status] Needs Design Review, [Type] Enhancement
