### ISSUE TITLE
Empty "connected as" section

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#6915] opened 2017-04-05 04:20 UTC
https://goo.gl/photos/ykxumoGTgqV6D3h9A

See screenshot

**Comment by dereksmart** [comment] 2017-04-05 13:30
This almost certainly the same problem reported in #6916 

Both of these rely on the [Jetpack::get_connected_user_data()](https://github.com/Automattic/jetpack/blob/91580cdd6ffc65f6584b3efa0d059d9e56be7408/class.jetpack.php#L1469) method that will return false and cause this bug if the xml request to get the wpcom user data fails for some reason.  

We're caching this result, and the transient key is based on the local user ID, so I guess you're viewing this as a user who has never logged into wp-admin Jetpack dashboard before?

**Comment by jeherve** [comment] 2017-04-07 19:00
Closing as duplicate of #6916

**Closed by jeherve** 2017-04-07 19:00 UTC
Labels: [Pri] Normal, [Type] Bug
