### ISSUE TITLE
Subscriptions: Add Like button to bottom of post notification email

### ISSUE THREAD

**Issue by isocialtish** [Automattic/jetpack#7572] opened 2017-08-02 03:30 UTC
#### What I see
The Post notification email does not include a like box at the bottom of the email
<img width="817" alt="jetpack post notification email" src="https://user-images.githubusercontent.com/6664819/28856396-9c0322b4-76f7-11e7-94a7-f621e4b7f365.png">

#### What I expected
A like box to appear at the bottom, just like with WordPress.com post notification emails
<img width="615" alt="wordpress com post notification email" src="https://user-images.githubusercontent.com/6664819/28856439-eaf9f7d0-76f7-11e7-971f-053b11549c14.png">

#### Why this feature should be added
So that this is consistent between WordPress.com and Jetpack sites.

**Comment by aheckler** [comment] 2017-08-28 15:26
Would also be good for Atomic users, e.g. 648994-zen

**Comment by aheckler** [comment] 2017-08-28 15:31
@isocialtish Going to close this as a duplicate of https://github.com/Automattic/jetpack/issues/7444

**Closed by aheckler** 2017-08-28 15:31 UTC
Labels: Likes, [Type] Enhancement
