### ISSUE TITLE
Jetpack Boost: Incompatibility with SyntaxHighlighter Evolved

### ISSUE THREAD

**Issue by joashrajin** [Automattic/jetpack#37055] opened 2024-04-24 13:09 UTC
### Impacted plugin

Boost

### Quick summary

When using Jetpack Boost alongside SyntaxHighlighter Evolved (an A8C Supported plugin), the site webpage doesn't render correctly. Reporting on this repo since it seems to be related to the Critical CSS feature. 

### Steps to reproduce

1. Install [SyntaxHighligher](https://wordpress.org/plugins/syntaxhighlighter/)
2. Enable Jetpack Boost
3. Enable Optimize Critical CSS
4. Add a syntax block to a page and notice that the page is not rendered properly. This causes an endless loading issue.
5. Disable Jetpack Boost and recheck the page

### A clear and concise description of what you expected to happen.

The webpage should load completely 

### What actually happened

The webpages are loading partially

### Impact

One

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

Report on the SyntaxHighligher Repo: https://github.com/Automattic/syntaxhighlighter/issues/275

**Comment by liviopv** [comment] 2024-04-25 09:32
📌 REPRODUCTION RESULTS
- Tested on Atomic – Replicated
- 
📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated, even with Optimize Critical CSS turned off

![CleanShot 2024-04-25 at 10 27 58@2x](https://github.com/Automattic/jetpack/assets/14153300/9a46565e-c751-4b83-9435-b8458c64781e)


📌 ACTIONS
- Triaged, switched to Normal

**Comment by haqadn** [comment] 2024-05-06 04:02
Can you confirm that it's still an issue? I tried but couldn't reproduce it https://dreamily-total.jurassic.ninja/syntax-highlighter/

**Comment by liviopv** [comment] 2024-06-13 13:25
@haqadn I can't repro anymore, closing.

**Closed as completed by liviopv** 2024-06-13 13:25 UTC
Labels: Bug, [Pri] Normal, [Plugin] Boost, [Boost Feature] Critical CSS, Triaged, [Status] Priority Review Triggered
