### ISSUE TITLE
Masterbar: Add "Edit" button

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/jetpack#9293] opened 2018-04-12 13:22 UTC
This came up originally on 1073675-zen , the Jetpack Masterbar does not have an "Edit" button to edit the current page or post, however it has a 

The solution if you want to keep your current workflow is simple: Deactivate the Masterbar (however not the best option if we want folk to use it). The problem comes **when the site is Atomic**, as the Masterbar cannot be deactivated by design, so the customer does not have this choice, disrupting their workflow by forcing a Masterbar with less options.

For the moment we have provided a workaround to that customer, that's installing a Code Snippets plugin and adding the following code to disable the Masterbar programmatically, which is not the best solution neither if we want the Masterbar to be used always when the site is Atomic:

```
function disable_wpcomtoolbar ( $modules ) {
   if ( isset( $modules['masterbar'] ) ) {
     unset( $modules['masterbar'] );
   }
   return $modules;
}    
add_filter( 'jetpack_get_available_modules', 'disable_wpcomtoolbar' );
```

Would be great to enhance this module by adding an "edit" button that allows you to edit via one click the page or post you're currently visit.

**Comment by jeherve** [comment] 2018-04-12 18:49
Closing as duplicate of #6848

**Closed by jeherve** 2018-04-12 18:49 UTC
Labels: Masterbar, [Type] Duplicate, [Type] Enhancement
