### ISSUE TITLE
Enhancement:

### ISSUE THREAD

**Issue by halilesen** [Automattic/jetpack#34294] opened 2023-11-24 14:12 UTC
### Impacted plugin

Jetpack

### What

Hide/Show for subscribers

### How

I wonder if it would be possible to hide the Subscribers Block if the logged in user is subscribed via email. If it is an email subscriber, I want to show something else instead.

**Comment by jeherve** [comment] 2023-11-24 14:53
Thanks for the suggestion!

I'll close this as duplicate of #30955.

**Closed as completed by jeherve** 2023-11-24 14:53 UTC
Labels: [Closed] Duplicate, Enhancement, [Feature] Subscriptions, [Block] Subscribe, [Plugin] Jetpack
