### ISSUE TITLE
Calendly block: Inline emebd is being cut off 

### ISSUE THREAD

**Issue by alaczek** [Automattic/jetpack#15266] opened 2020-04-03 03:48 UTC
#### Steps to reproduce the issue

1. Add Calendly block to a site with Premium or Business plan.
2. Use the "Inline" block style.
3. Notice how the embed's height is too small, resulting in a scrollbar.

#### What I expected
For the whole content to be visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/4550351/78322145-922c5580-75b9-11ea-8782-52fbcb641a20.png)

**Comment by jeherve** [comment] 2020-04-03 07:00
Closing as duplicate of #14566

**Closed by jeherve** 2020-04-03 07:00 UTC
Labels: [Block] Calendly
