### ISSUE TITLE
Escaping issues on redirect URL

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#19943] opened 2021-05-26 17:26 UTC
I don't know if this is causing other side-effects, but I noticed an incorrectly escaped URL in a redirect chain starting from the Plans tab title in the Jetpack dashboard.

`https://cloud.jetpack.com/pricing/?unlinked=1&amp;site=proper-hoopoe.jurassic.ninja&site=proper-hoopoe.jurassic.ninja&admin_url=https%3A%2F%2Fproper-hoopoe.jurassic.ninja%2Fwp-admin%2F`

The issue appears to be caused by the escaping on the URL at the end of the get_base_url() function in the `jetpack-redirects` library on WPCOM.

#### Steps to reproduce the issue

1. Connect the site without connecting a user
2. Click on the Plans tab
3. Note that you redirect via a URL with escaping issues

**Comment by jeherve** [comment] 2021-05-27 07:48
cc @leogermani

**Comment by leogermani** [comment] 2021-05-27 13:14
Apparently, the problem is in our UI to save the redirects rules

See MC /jetpack-crew/redirects

I'll look into it

**Comment by leogermani** [comment] 2021-05-31 18:55
This was fixed on WPCOM side. See D62002-code

**Closed by leogermani** 2021-05-31 18:55 UTC
Labels: [Package] Redirect, [Type] Bug
