### ISSUE TITLE
'You are not connected to WordPress.com' is confusing to users

### ISSUE THREAD

**Issue by smerriman** [Automattic/jetpack#5187] opened 2016-09-20 21:57 UTC
After Jetpack was upgraded to 4.3.1, an admin on our WordPress site, looking for the Stats page, went to the Dashboard and was provided with a big warning message:

'You, xxx, are not connected to WordPress.com'.

They therefore thought everything was broken and stats were not being collected.

This wasn't true; stats were being collected perfectly fine. It seems the new version of Jetpack shows this for everyone except the one WordPress user who connected Jetpack.

I can't find any documentation anywhere suggesting that every single user on the site needs to connect separately to WordPress.com, and this makes no sense for a site-level connection anyway.

This error/warning message, if necessary, needs to be made a lot more clear as to what it means to the user.

**Comment by jeherve** [comment] 2016-09-26 09:32
> I can't find any documentation anywhere suggesting that every single user on the site needs to connect separately to WordPress.com

They don't need to, but it allows them to access more features, like the Advanced Stats view on WordPress.com for example.

>This error/warning message, if necessary, needs to be made a lot more clear as to what it means to the user.

Can you think of a different wording you would use? How would you phrase it to make things less confusing for your users?

**Comment by smerriman** [comment] 2016-09-30 03:46
> They don't need to, but it allows them to access more features, like the Advanced Stats view on WordPress.com for example.

I don't think this is true. Being able to view advanced stats on WordPress.com requires being logged into WordPress.com. This has no relation to my self-hosted WordPress user being "connected" to Jetpack which is what the prompt tells me I need to do.

I am actually yet to find any feature that requires my wordpress.org user to be connected, as opposed to the site connection being set up. Site Stats works fine, Publicize works fine, etc.

If there are some features that require a separation user connection, perhaps the notice could be placed there, with details of what the benefit of the second connection would mean.

**Comment by jeherve** [comment] 2016-09-30 09:11
> I don't think this is true. Being able to view advanced stats on WordPress.com requires being logged into WordPress.com. This has no relation to my self-hosted WordPress user being "connected" to Jetpack which is what the prompt tells me I need to do.

It is related. Being logged in to your WordPress.com account isn't enough. You need to be allowed to view the stats for that specific Jetpack site, and that's done by linking your local WordPress account to your WordPress.com account. Publicize works the same way.

To confirm this, you can try the following:

1. Start with a brand new site.
2. Go to Users > Add New. Create an additional admin for that site.
3. Install and activate Jetpack.
4. Go to the Jetpack menu, and connect Jetpack to WordPress.com.
5. Go to Jetpack > Settings, and ensure that both Stats and Publicize are enabled.

-> You will now be able to view stats on your site, as well as on WordPress.com by going to `https://wordpress.com/stats/mysite.com`
-> You will be able to manage your Publicize connections by going to Settings > Sharing in your dashboard, or to this page on WordPress.com: `https://wordpress.com/sharing/mysite.com`

Let's now simulate what another admin would see and be able to do. To do that, you'll need another WordPress.com account, for that other admin.

6. Now log out of your WordPress.com account.
7. Log out of your local admin account on your site.
8. Log in to your site with the new admin account you created earlier.
9. Log in to that other WordPress.com account.
10. Try going to `https://wordpress.com/stats/mysite.com` -> You won't have access to the page, and will be redirected to stats for that WordPress.com account's other sites.
11. Try going to `https://wordpress.com/sharing/mysite.com`-> You won't have access to the page, and will be redirected to the Publicize management screen for that WordPress.com account's other sites.
12. Try going to Settings > Sharing in your dashboard -> The Publicize options won't be there, and instead you'll see an option to link your local account to your WordPress.com account.
13. Use that option to link your accounts, or click on the Link button appearing in the Jetpack dashboard.
14. Now that your local account is connected to WordPress.com, you'll have access to everything.

I hope this clarifies things a bit.

> If there are some features that require a separation user connection, perhaps the notice could be placed there, with details of what the benefit of the second connection would mean.

Most of the links on that Jetpack dashboard redirect to site management tools on WordPress.com, and those tools require the user connection. Do you think we could add something like "Link your site to WordPress.com to manage your site from a single dashboard on WordPress.com." Would that help?

**Comment by jeherve** [comment] 2016-11-09 17:56
Should be fixed by #5461

**Comment by rickybanister** [comment] 2017-06-22 19:33
This is more or less a duplicate of #6293 and since the settings UI has been updated I think most of the feedback in this ticket has been addressed.

**Closed by rickybanister** 2017-06-22 19:33 UTC
Labels: Admin Page, [Status] Needs Author Reply, [Status] Needs Design Review, [Status] Requires String Changes, [Type] Enhancement
