### ISSUE TITLE
"You can also add a Like Box"

### ISSUE THREAD

**Issue by donalirl** [Automattic/jetpack#33611] opened 2023-10-16 01:40 UTC
### Impacted plugin

Social

### What

After connecting Facebook on a WordPress.com site, there is text that says "You can also add a Like Box". There are two issues:

**Comment by jeherve** [comment] 2023-10-16 09:53
closing as duplicate of https://github.com/Automattic/wp-calypso/issues/83032

**Closed as completed by jeherve** 2023-10-16 09:53 UTC
Labels: [Closed] Duplicate, Enhancement, [Plugin] Social
