### ISSUE TITLE
Blog subscriptions: Email reveals shortcodes in post

### ISSUE THREAD

**Issue by Klooven** [Automattic/jetpack#7330] opened 2017-06-09 08:16 UTC
#### Steps to reproduce the issue

Insert a shortcode at the beginning of a post. (I used a shortcode that is generated by a **plugin**). Publish the post, and wait for the email to arrive.

[Here's an example how it looked like](https://drive.google.com/file/d/0B026nZLKNEymT3Y3VTU5cV9KU0k/view?usp=sharing)

There was no output in the "body" of the mail, the only place where the shortcode was "revealed" was in the header, like in the example.

#### What I expected

The shortcode should have been converted to code, or then no output at all in the mail.

#### What happened instead

The shortcode wasn't converted to code, and showed like:

`[part part="1" of="2" tag="herrainmaki-2016"]`

Example of the mail in the link above...

--

If you need source code for the plugin, just ask me. The plugin is not in the WP.org plugin repository.

**Comment by zinigor** [comment] 2017-06-09 09:49
Hello, thank you for the report!

This happens due to how we manage Jetpack subscriptions. Because we prepare the emails on WordPress.com servers, we can only properly transform shortcodes that are implemented in Jetpack, plus we have some simple versions of most frequently used shortcodes. In case we don't know how to parse a certain shortcode, we remove the shortcode and keep its content, if there's any.

In your case I think the problem is that WordPress.com hasn't yet synced the fact that your site supports the `[part]` shortcode, that's why it leaves it intact.

How long have you had it installed? Perhaps you need to give it time to sync properly with WordPress.com?

cc @lezama in case I missed something.

**Comment by Klooven** [comment] 2017-06-09 16:56
Oh, that explains it.

I installed the plugin just a few days ago, and this is the first time the shortcode was used in a post.

I'll check the situation in the next post, and let you know about the results in that email.

**Comment by Klooven** [comment] 2017-06-10 09:23
I published a new post today. Still the same problem.

**Comment by ebinnion** [comment] 2017-06-14 08:54
Hello @Klooven - We only support a subset of shortcodes. You can find more about this at https://jetpack.com/support/subscriptions/, under the `Why are the shortcodes not rendering correctly?` section.

In this case, I don't think we'll support the part shortcode. That being said, it does seem off that it showed up in the header of the email, as opposed to the body. So, we'll look into that.

cc @lezama

**Comment by Klooven** [comment] 2017-06-15 08:30
Thanks for the info.

> That being said, it does seem off that it showed up in the header of the email, as opposed to the body.

That's right. Thanks for checking it.

**Comment by spectreg4** [comment] 2017-07-06 19:43
I apologize if I am adding information to the wrong post. However, I recently had a blog post email include some shortcode and I am not sure why. The email before it did not include any shortcode of this type. The only thing changed in the post format was I used a new full-width header that contains an image and some blog meta text. Does this also have to do with the need to 'sync' with WordPress?

Here is the shortcode that appeared `[et_pb_fullwidth_post_title global_parent="30981" _builder_version="3.0.53" title="on" meta="on" author="on" date="on" categories="on" comments="on" featured_image="on" featured_placement="background" parallax_effect="off" parallax_method="on" text_orientation="center" text_color="light" text_background="on" border_style="solid" custom_padding="150px||150px|" custom_padding_phone="100px||100px|" custom_padding_last_edited="on|phone" module_bg_color="rgba(0,0,0,0.5)" title_font_size_last_edited="on|tablet" title_font_size="40px" title_font_size_tablet="35px" title_font_size_phone="28px" title_line_height="1.2em" title_font="|||on|" custom_padding_tablet="125px||125px|" text_bg_color="rgba(0,0,0,0.5)" /]
[et_pb_row_inner background_position_1="top_left" background_repeat_1="no-repeat" _builder_version="3.0.53"]`

I have since made this shortcode which resembles a non-global module within my theme to see if that fixes the problem as I had not included any before.

**Comment by ebinnion** [comment] 2017-07-06 19:55
Hello @spectreg4 -

From what I can tell, that looks like it might be a Elegant Themes specific shortcode. While we do support a subset of shortcodes in subscription in emails, there are many that we don't currently, including `et_pb_fullwidth_post_title`.

In the meantime, you could customize the email content that gets out by switching to using summaries in the feed. https://jetpack.com/support/subscriptions/#customize-content

**Comment by ebinnion** [comment] 2017-07-06 19:59
Hi @Klooven -

I'm not able to replicate this issue. Are you still experiencing the shortcode in the header of your emails?

**Comment by Klooven** [comment] 2017-07-19 18:12
Hello @ebinnion .

I haven't sent any posts with shortcodes in them lately.

In the last post where I used this shortcode, the `[part]` shortcode was still there.

_Sorry for answering this late._

**Comment by ebinnion** [comment] 2017-07-20 14:57
Hey @Klooven -

Having the source code to the plugins with the shortcodes, and perhaps the source code to your them could be helpful. Would you mind sending those to `support@jetpack.com` and referencing this Github issue URL? Our support engineers will pass that on to us and we can start looking into it.

Thanks.

**Comment by enejb** [comment] 2018-04-05 23:46
@jeherve I am going to close this but feel free to open this if this is still an issue.

**Closed by enejb** 2018-04-05 23:46 UTC
Labels: Subscriptions, Sync, [Status] Needs Author Reply, [Type] Bug
