### ISSUE TITLE
Contact Form: "Set up" button in settings leads to strange message/dead end

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/jetpack#9113] opened 2018-03-21 18:30 UTC
#### Steps to reproduce the issue

1. Start on a Jetpack site with the Contact Form module activated.
2. Go to Jetpack > Settings.
3. Search for `contact form` to find the contact form settings.
4. Note that the only actions to take here are "Learn more" (under the i popover, to go to the support doc) and "Set up." Click the "Set up" button.

#### What I expected

I expected this button to set up a contact form for me.

#### What happened instead

I was taken to https://wordpress.com/plugins/setup/{SITE_ADDRESS}?only=contact-form which showed the message "Setting up your Premium Plan" and then auto-advanced to the message "Nothing to do here..."

The flow ended on that screen with no clear path forward.

#### Screencast

![jpcontactformsetup](https://user-images.githubusercontent.com/8658164/37729747-c4bb365c-2d35-11e8-9e5c-4fbb9076ac6a.gif)

**Comment by oskosk** [comment] 2018-03-21 18:33
Thanks for the report @rachelmcr . This issue is a generic problem for all searchable modules, and  is a duplicate of #8525 and currently a PR is providing the fix: #9096 .

**Comment by rachelmcr** [comment] 2018-03-21 18:35
Aha! Thanks, I missed that issue while searching earlier.

**Closed** 2018-03-22 16:22 UTC
Labels: Contact Form, FixTheFlows, [Type] Bug
