### ISSUE TITLE
Quick Edit on Post saves all in html instead of Markdown syntax

### ISSUE THREAD

**Issue by shihkuang** [Automattic/jetpack#636] opened 2014-06-03 19:41 UTC
When using the quick edit function on post list, the content will be saved as html instead of Markdown syntax.

It happens when I updated the post title and slug.

**Comment by synapticism** [comment] 2015-10-30 10:33
I'm also experiencing this... glad to know what the root cause is (using quick edit) so at least I can avoid destroying the Markdown content for any more of my posts.

**Comment by blueliquiddesigns** [comment] 2015-11-08 23:57
Had the same issue and submitted a PR to fix the problem (I can't believe a problem like this has been left open for over a year?!).

**Comment by shprink** [comment] 2015-12-02 06:09
+1

**Comment by jeherve** [comment] 2015-12-02 13:17
Fixed in #2978.

@shprink I'd suggest updating 3.8.1 and see if that helps!

**Closed** 2015-12-02 13:17 UTC
Labels: bug, in progress, Markdown, Needs Review
