### ISSUE TITLE
Widget Visibility: filters to customize categories/values

### ISSUE THREAD

**Issue by paulschreiber** [Automattic/jetpack#3779] opened 2016-05-09 19:16 UTC
Currently, the widget visibility list of categories (Category, Author, User, Role, Tag, Date, Page, Post Type, Taxonomy) and values for each category is fixed.

It would be very helpful if we could filter the list to reduce the number of available options and declutter the UI.

**Comment by jeherve** [comment] 2016-05-10 10:24
That's something we've indeed looked at. I'll close this issue as duplicate of #434, as we've started working on filters there.

Thanks for the feedback!

**Closed by jeherve** 2016-05-10 10:24 UTC
