### ISSUE TITLE
Facebook widget: Page timeline doesn't load

### ISSUE THREAD

**Issue by KokkieH** [Automattic/jetpack#17818] opened 2020-11-16 13:04 UTC
It appears the Facebook Page Plugin widget isn't loading the page feed if enabled in the widget settings, and instead shows an error pop-up which pulls the focus to wherever on the site that widget has been added.

#### Steps to reproduce the issue

1. Open the Customizer ->Widgets, and add a Facebook Page Plugin widget
2. Paste in the URL of a public Facebook page
3. Make sure to select the option to display page timeline in the widget.
4. The error should be visible even in the Customizer preview

#### What I expected
For the widget to display the Facebook page's feed

#### What happened instead
The widget displays an error, and if the widget is, for example, added to a footer widget area, opening the site will cause the browser to jump down to the footer widget area the moment the error loads in the widget iframe.

**Screenshots**
![if_all_else_fails…use_a_hammer_–_an_exercise_in_percussive_maintenance](https://user-images.githubusercontent.com/11873759/99254950-dc4a0a80-281b-11eb-9aeb-42f627df3082.png)

I can replicate in Firefox, Safari and Edge on MacOS, but not in Chrome.

It looks like this might be an issue on Facebook's end: https://developers.facebook.com/support/bugs/2526305424326407/

But opening the issue here in case we receive other reports.

Reported in the WordPress.com forums in https://wordpress.com/forums/topic/preview-not-working-10

**Comment by jeherve** [comment] 2020-11-16 13:05
Closing as duplicate of #17797. 

> It looks like this might be an issue on Facebook's end

That does indeed seem to be the case.

**Comment by KokkieH** [comment] 2020-11-16 13:06
I promise I searched for existing reports before posting :)

**Closed by jeherve** 2020-11-16 13:05 UTC
Labels: Extra Sidebar Widgets, [Type] Bug
