### ISSUE TITLE
Blog Subscriptions Widget: Include follower counts from publicize-connected services in the total number of subscribers 

### ISSUE THREAD

**Issue by alexjgustafson** [Automattic/jetpack#5210] opened 2016-09-27 17:37 UTC
The Blog Subscriptions widget includes this option:

> "Show Total Number of Subscribers?"

In the analogous widget on WordPress.com, [the "Follow Blog" widget](https://en.support.wordpress.com/widgets/follow-blog-widget/), when that option is checked it includes not only email subscribers but also the number of followers from each of the services connected through Publicize. 

Users migrating from WordPress.com often do not appreciate seeing their follower count artificially go down. Anyone wanting to display this number would be incentivized to make the number as high as accurately possible, so it also affects Jetpack users not coming from WordPress.com that their count in some respects is artificially low without these numbers.

**Comment by alexjgustafson** [comment] 2016-09-27 17:40
2846067-t

**Comment by jeherve** [comment] 2016-09-27 18:30
Closing as duplicate of #800

**Closed by jeherve** 2016-09-27 18:30 UTC
Labels: Extra Sidebar Widgets, Subscriptions, [Type] Enhancement
