### ISSUE TITLE
Post By Email: Pixelated Images 

### ISSUE THREAD

**Issue by fresatomica** [Automattic/jetpack#14652] opened 2020-02-12 11:36 UTC
#### Steps to reproduce the issue

1. Create a post via email
2. Add an image
3. Send the email
4. Check the published post

#### What I expected
I expected to see the image with the same quality as the one uploaded.

#### What happened instead
The image is pixelated and can only be seen properly after clicking on it and displaying the single file.

![Screen Shot on 2020-02-12 at 12-31-36](https://user-images.githubusercontent.com/40177971/74331311-baef5600-4d93-11ea-8c5b-ff882ea7ab9b.png)

**Comment by olyinfos** [comment] 2020-02-12 12:05
hi i reported this initially. Also i thought perhaps "no gallery helps" but this did not help.

**Comment by jeherve** [comment] 2020-02-12 17:28
Closing as duplicate of #737

**Closed by jeherve** 2020-02-12 17:28 UTC
Labels: Post By Email, [Type] Bug, [Type] Duplicate

**Comment by olyinfos** [comment] 2020-02-12 19:20
@jeherve so did you close it and there is no fix for that Problem since 2014? Do i unterstand that Right? No fix for that simple Problem?

**Comment by jeherve** [comment] 2020-02-12 20:11
@olyinfos That is correct. We'll update the other issue whenever we make progress on this.

However, iterations for the Post By Email feature are currently not on our roadmap. If you're looking for an easy and safe way to post to your site when on the go, I would recommend turning to [the WordPress Mobile apps](https://apps.wordpress.com/mobile/).
