### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by ZeroWasteIngi** [Automattic/jetpack#16929] opened 2020-08-21 09:42 UTC
Error on my website. I read on another page that this is cause jetpack. 

Uncaught TypeError: Cannot read property 'classList' of null
    at eu-cookie-law.min.js:2
    at eu-cookie-law.min.js:2

Do you know how this can be corrected?

#### What happened instead

**Screenshots**

**Comment by jeherve** [comment] 2020-08-24 07:50
Thanks for the report. Closing as duplicate of #16625.

**Closed by jeherve** 2020-08-24 07:50 UTC
Labels: Extra Sidebar Widgets
