### ISSUE TITLE
[Boost] Enabling lazy loading causes images to disappear on Safari browser on themes like 2022 and Storefront

### ISSUE THREAD

**Issue by kaushikasomaiya** [Automattic/jetpack#25284] opened 2022-07-27 06:00 UTC
### Impacted plugin

Boost

5420128-zen

### Steps to Reproduce

1. Install Jetpack Boost
2. Do not install Jetpack
3. Enable Lazy loading in Jetpack Boost
4. Go to WooCommerce Shop page in Safari browser
5. Experiment loading different URL versions of shop page by appending random parameters ?v=123 or refresh the page
6. You'll see the top image rows does not load up
7. Surprisingly, this gets fixed if Jetpack plugin is active along with Jetpack Boost

This was fixed in #23553  but somehow it is not working in Boost plugin.

### Browser

Apple Safari

### Reproducibility

Intermittent

### Available workarounds?

Yes, easy to implement

### Workaround details

Install Jetpack plugin to fix this.

**Comment by anomiex** [comment] 2022-07-27 17:16
The fix from #23553 was included in Boost 1.5.1, which was released about a month ago. Can you double check that that's the installed Boost version?

There was another fix for a lazy images issue first included in Jetpack 11.1.2. Does Jetpack 11.1.1 also fix it or is installing 11.1.2 required to do so?

**Comment by NathalyaVides** [comment] 2022-07-27 20:03
An update from 5420128-zen, these are the current versions on the site:

Jetpack Boost: by Automattic - Website Speed and Performance team – 1.5.1
Jetpack: by Automattic – 11.1.2

**Comment by kaushikasomaiya** [comment] 2022-07-28 03:53
Hi @anomiex 

I tested this on the latest versions of Boost and Jetpack yesterday - and I was able to reproduce this issue. It is Intermittent though.

I may be wrong about installing Jetpack along with Boost fixes the issue because doesn't seem to be the case for the user.

**Comment by kaushikasomaiya** [comment] 2022-07-28 04:06
I also created a video of this issue: https://d.pr/v/KM3lDj (JP is not installed here.)

**Comment by marissaexplores** [comment] 2022-08-30 16:24
Similar behaviors were reported on [5515268-zen](5515268-zd-woothemes) where I suggested they disable lazy load in Jetpack and Jetpack Boost to see if that fixes the issue.
They responded that the issue is fixed, but did not confirm that it was because of the lazy load settings.

**Comment by sarbouw** [comment] 2022-09-24 13:36
Similar behaviors were reported on 5549576-zen where lazy load was disabled in Jetpack to see if that fixes the issue.

**Comment by haqadn** [comment] 2023-03-10 02:55
Closing as duplicate of #23553 Fixed in #29243

**Closed as completed by haqadn** 2023-03-10 02:55 UTC
Labels: Bug, [Status] In Progress, [Pri] Low, [Feature] Lazy Images, Customer Report [LEGACY], [Package] Lazy Images, [Plugin] Boost, [Boost Feature] Lazy Images, Needs triage
