### ISSUE TITLE
Identity Crisis check: admin warning message won't go away

### ISSUE THREAD

**Issue by chuckreynolds** [Automattic/jetpack#2016] opened 2015-04-24 00:21 UTC
after the 3.5 update in wp4.2 this pops up on staging sites in all pages in /wp-admin/.

![jetpack warn](https://cloud.githubusercontent.com/assets/46185/7310210/0cffe5e2-e9dd-11e4-9410-78c4c6108a3f.png)

Ignore link doesn't link to anything - in fact either does the 3rd link. I'd rather not click reconnect but.. how do we nuke this warning now?

**Comment by jeherve** [comment] 2015-04-24 10:42
Also reported here:
https://wordpress.org/support/topic/wordpress-update-42-issue

**Comment by jeherve** [comment] 2015-04-24 10:45
@chuckreynolds What's the URL of the site where you get the issue? edd.app? If so, could you try to enable [Jetpack's Development mode](http://jetpack.me/support/development-mode/) on that site, since it's probably a local installation of WordPress?

**Comment by nosegraze** [comment] 2015-04-24 11:18
My clients are also having this same issue. Presumably it's happening because we're using domain mapping on multisite and one URL redirects to the other. But the main problem is that none of the links actually do anything to dismiss the notice (at least not the second or third -- haven't tried the first, just like @chuckreynolds ).

![jetpack-domain-mapping](https://cloud.githubusercontent.com/assets/6324272/7317727/dfa45732-ea7b-11e4-8f75-bfc3247e262a.png)

**Comment by chuckreynolds** [comment] 2015-04-24 19:42
@jeherve yeah it's local but regardless of where it's at the link should actually dismiss the warning as it suggests it would ;)  Also have that warning on their 'in-the-wild' staging environment. 
I'll add the dev mode to my local but the purpose of testing plugin updates is to have it act as it would on live - so regardless of the warning nag in admin I'd rather see it there than not and have it happen on `production` and not on `staging`.  u know.
Got the ping from @dereksmart that you guys are already working on a fix so. i'm sure that'll push soon(ish).

**Comment by chuckreynolds** [comment] 2015-04-24 21:34
for reference - disconnecting and reconnecting worked fine on production. ty for pointing out `JETPACK_DEV_DEBUG` 

other two links are still bugged however, which is why this should remain open. #suggestion

**Comment by jeherve** [comment] 2015-04-25 09:03
> the link should actually dismiss the warning as it suggests it would 

Definitely, that's on our to-do list! That's something that should get fixed with #2018.

**Comment by jeherve** [comment] 2015-04-25 09:28
Also reported here:
https://wordpress.org/support/topic/something-has-gotten-mixed-up-error

**Comment by chuckreynolds** [comment] 2015-04-25 22:04
:+1:

**Comment by bethnicol** [comment] 2015-04-27 01:46
I've done the disconnect and reconnect more than once because the fix seems to be temporary.  Fix it, and come back a day or 2 later and it has returned. 

I'm  seeing it a subdomain multisite (with domain mapping); so far not a problem with a subdirectory multisite except for the one site on that network that uses domain mapping.

**Comment by jeherve** [comment] 2015-04-27 10:38
@bethnicol Could you tell us more about your Multisite setup? What are your domain mapping options under Settings > Domain Mapping in Network Admin?

**Comment by jeherve** [comment] 2015-04-27 13:23
Also reported here:
https://twitter.com/pixelyzed/status/592678604070383618

**Comment by bethnicol** [comment] 2015-04-27 14:01
Multisite 1: subdomain install
WordPress MU Domain Mapping plugin (Donncha's)
CNAME for mapping
options 1-4 on (Remote Login, Permanent redirect (better for your blogger's pagerank), User domain mapping page, Redirect administration pages to site's original domain (remote login disabled if this redirect is disabled)
In this network I went through last night and used the option 1 link. Today all is well. But previously, I had deactivated/activated, then reconnected Jetpack for each site which removed the message for a couple of days, but it returned.

Multisite 2: subdirectory install
WordPress MU Domain Mapping plugin (Donncha's)
Server IP Address for mapping
options 1-4 on (Remote Login, Permanent redirect (better for your blogger's pagerank), User domain mapping page, Redirect administration pages to site's original domain (remote login disabled if this redirect is disabled)
Only ever saw the message on the 1 mapped site 
 sites are generally domain.org/en/, domain.org/es/ and this is how the world sees them
 one site is domain.org/social mapped so that the external url is social.domain.org -- that is the only place I've seen the message.

**Comment by jeherve** [comment] 2015-04-27 14:09
Could you try to use the following settings, then disconnect and reconnect Jetpack to WordPress.com? Let me know if it helps.

![screen shot 2015-04-27 at 4 08 53 pm](https://cloud.githubusercontent.com/assets/426388/7349224/cb0fccce-ecf7-11e4-8ec7-787f1a8153ef.png)

**Comment by bethnicol** [comment] 2015-04-27 14:11
will do. Should I wait until the message reappears? Right now I wouldn't know if it helped.

**Comment by jeherve** [comment] 2015-04-27 14:14
Sure. Hopefully it won't reappear. :)

**Comment by bethnicol** [comment] 2015-04-27 14:16
FYI: I have yet another network (subdomain); I saw the message on one site; changed it like you asked, and the message disappeared without the disconnect/reconnect.

**Comment by nosegraze** [comment] 2015-04-27 14:16
I'm using the Domain Mapping plugin by WPMUDEV. Are there specific settings I should be using to avoid this message?

**Comment by jeherve** [comment] 2015-04-27 14:18
@bethnicol Could you let me know the URL of that other site?

@nosegraze Could you let me know your site URL as well, or [send us an email](http://jetpack.me/contact-support/)?

Thanks!

**Comment by bethnicol** [comment] 2015-04-27 14:21
journey2myself.org is the mapped site; the network is 321windsor.com  ( so 321windsor.com/journey2myself)

**Comment by nosegraze** [comment] 2015-04-27 14:24
@jeherve The URL is http://bookblog.io I have many domains mapped to various subdomains of that site.

**Comment by jeherve** [comment] 2015-04-27 14:28
@bethnicol I've just made some changes to your Jetpack settings. Could you try to disconnect and reconnect to WordPress.com once again?

Thanks!

@nosegraze Your site seems to be completely disconnected from WordPress.com right now. Could you try to reconnect?

**Comment by nosegraze** [comment] 2015-04-27 14:30
@jeherve The root site isn't connected, but each of the sites on a subdomain is connected to a different WordPress.com account (owned by other people - not me).

Here's one example:

http://girlinthepages.bookblog.io/
mapped domain: http://girlinthepages.com

**Comment by jeherve** [comment] 2015-04-27 14:34
@nosegraze I've made some changes to that site's Jetpack settings. Could you try to disconnect and reconnect to WordPress.com?

Thanks!

**Comment by bethnicol** [comment] 2015-04-27 14:34
OK -- for one site under 321windsor.com, I disconnected and reconnected and the message is gone. I have done nothing more with journey2myself because is has no message currently displaying. 

One point that may cause confusion: I have 2 wordpress.com accounts, one for my own stuff and one for a client. So 321windsor is attached to one, and the famvin sites are connected to a different one.

**Comment by nosegraze** [comment] 2015-04-27 14:35
@jeherve I don't own the WordPress.com site so I'll have to talk to my client about doing it. Thanks!

I have many, many sites using domain mapping though so will adjustments have to be made to each individual site or are you working on a more global fix?

**Comment by jeherve** [comment] 2015-04-27 14:59
> are you working on a more global fix?

We are. The fix will be part of the next release, 3.5.1.

**Comment by jeherve** [comment] 2015-04-27 17:45
Also reported here:
https://wordpress.org/support/topic/new-notice-about-inconsistent-site-names-unstyled-and-undismissable?replies=1&view=all

**Comment by bobbingwide** [comment] 2015-04-28 13:24
I've got a couple of comments to add to this:
1. I think it should be clearer that this message is something to do with Jetpack
2. It should be clearer that you've been given three options to choose from

**Comment by jeherve** [comment] 2015-04-28 13:27
@jeffgolenski Interesting comments from @bobbingwide above; they might help you when styling the notice.

**Comment by bethnicol** [comment] 2015-04-28 17:30
@jeherve -- message reappeared ( on http://aic.ladiesofcharity.us/ dashboard) in the famvin.com multisite.  WordPress.com user bethnicol308;  I used option 1 this time to disconnect/reconnect. 

No idea if this will fix things or not.

**Comment by samhotchkiss** [comment] 2015-04-29 17:29
Fixed by eb0d2ea322d5482b1816096bdb23d3ddd4f7f2c2

**Closed** 2015-04-29 17:29 UTC
Labels: bug, General

**Comment by RavanH** [comment] 2015-04-29 23:03
Ehm... can we call hiding the message a fix? Should it not be made possible to have back-end / admin running on a different domain? I've noticed that even http on the front end and https on the back-end can cause this issue. 

Disconnecting and reconnecting on the new back-end domain will make the message disappear ( as does fix eb0d2ea ) but suddenly the Stats are no longer displaying the stats from the front end.

It seems to me the only real solution is to allow one connection to use multiple domains. There are many multi-lingual sites out there that use a different domain for each language for example. How's that affecting WordPress.com Stats? And the Publicize linked URL? Related Posts?

**Comment by jeherve** [comment] 2015-04-30 11:44
@RavanH To clarify, the message itself was useless, because we hadn't deployed the code that would allow you to click on one of the options in the prompt and update Jetpack settings.

We're still working on that code (see #2018), but it's not ready for production yet. Until it is, we'll hide the message.

No worries though, you can have your backend running on a different domain. That's actually how most multisite networks work, as soon as they allow custom domains.

> Suddenly the Stats are no longer displaying the stats from the front end.

That's most likely because the reconnection forced an update of your Jetpack settings, and a new data set was created for the new site URL. If you let us know your site URL here, or [send us an email](http://jetpack.me/contact-support/), we can get you your stats back.

> There are many multi-lingual sites out there that use a different domain for each language for example. How's that affecting WordPress.com Stats? And the Publicize linked URL? Related Posts?

In such cases, a new Jetpack connection is created for each domain, thus making things work properly.

**Comment by RavanH** [comment] 2015-04-30 11:58
@jeherve thanks for that explanation!  :)  One of the site stats I was talking about are from http://www.outlawpoetry.com which is now using https://m-etropolis.com/outlawpoetry/ as admin domain. There are others but it's not so important since we're mosty using Google Analytics anyway ;)

**Comment by jeherve** [comment] 2015-04-30 12:31
@RavanH I updated your Jetpack settings for that site. If you disconnect Jetpack from WordPress.com thanks to the link at the bottom of the Jetpack menu page, and then reconnect, you should get your stats back!

**Comment by kteare** [comment] 2015-05-03 15:31
Mine isn't fixed by disconnect and connect.

It continues to think my site is "0" and "1"

I have exactly the same message on anther site - seriouslytech.com.


I host both on my own server - 4.2.1 installation


see below

"Something has gotten mixed up!
Your siteurl option is set up as http://seriouslypolitics.com, but your WordPress.com connection lists it as 0!
Your home option is set up as http://seriouslypolitics.com, but your WordPress.com connection lists it as 1!
The data listed above is not for my current site. Please disconnect, and then form a new connection to WordPress.com for this site using my current settings.
Ignore the difference. This is just a staging site for the real site referenced above.
That used to be my URL for this site before I changed it. Update the WordPress.com Cloud's data to match my current settings."

**Comment by jeherve** [comment] 2015-05-04 11:03
@kteare I've made some changes to your Jetpack settings. Could you try to disconnect Jetpack from WordPress.com thanks to the link at the bottom of the Jetpack menu page, and then try to reconnect?

Thanks!

**Comment by shivamtyagi** [comment] 2015-05-04 20:22
i ahving the same issue
Something has gotten mixed up!

Your siteurl option is set up as http://techsmashit.com, but your WordPress.com connection lists it as 0!
Your home option is set up as http://techsmashit.com, but your WordPress.com connection lists it as 1!
The data listed above is not for my current site. Please disconnect, and then form a new connection to WordPress.com for this site using my current settings.
Ignore the difference. This is just a staging site for the real site referenced above.
That used to be my URL for this site before I changed it. Update the WordPress.com Cloud's data to match my current settings.

and it is not resolving by disconnecting and reconnecting

**Comment by kteare** [comment] 2015-05-04 22:44
This worked - thank you 
---
Best Regards

Keith Teare
Chat with me instantly at https://chat.center/keith
________________________________________________________

**Comment by jeherve** [comment] 2015-05-05 09:20
@shivamtyagi Can you please use Jetpack's Debugger module to send us some more information about your site?

1) Go to the Jetpack page in your dashboard.
2) Click on the Debug link appearing at the bottom of the page.
3) Click the link that says "click here to contact Jetpack support."
4) Fill in the description box and your name and email address.
5) Click the "Contact Support" button.

Thanks!

**Comment by shivamtyagi** [comment] 2015-05-05 09:43
hi,
i am clicking the option "click here to contact Jetpack support" but
nothing happens.
and the issue of 0 and 1 message is not resolved yet.

**Comment by jeherve** [comment] 2015-05-05 09:48
> i am clicking the option "click here to contact Jetpack support" but nothing happens.

Could you check for Javascript errors on the page, as explained here:
http://codex.wordpress.org/Using_Your_Browser_to_Diagnose_JavaScript_Errors

Let me know what you find!

**Comment by shivamtyagi** [comment] 2015-05-05 10:03
i am not able to understand the error . iam sending u that.
and the o and 1 error is in my 2 websites
guideofcydia.com
techsmashit.com

please tell me what to do.
should i deactivate jetpack

**Comment by jeherve** [comment] 2015-05-05 12:26
> the o and 1 error is in my 2 websites
> guideofcydia.com
> techsmashit.com

Both sites appear to have some connection issues, caused by some security rules on your server:
- http://guideofcydia.com/cydia/xmlrpc.php?for=jetpack
- http://techsmashit.com/xmlrpc.php?for=jetpack

Could you contact your hosting provider, and ask them to take a look at this issue?
