### ISSUE TITLE
The ampersand in "&ssl=1" breaks RSS feeds that include featured images (eg for mailchimp)

### ISSUE THREAD

**Issue by sublines** [Automattic/jetpack#9690] opened 2018-06-06 09:19 UTC
Hi,  

I am using a simple function inside my functions.php to include the posts featured images inside the RSS feed as a valid _Media element_ (media:content). 

The function uses _wp_get_attachment_image_src();_ to retreive the URL of the featured image. 
This URL of course includes the "&ssl=1" that jetpack has added to all images retrieved over https. 

Unfortunaltey, RSS can't handle raw ampersands which means that RSS feeds can't include any images  served from jetpack over https.

**Comment by brbrr** [comment] 2018-06-11 18:41
Hi @sublines!

Thanks for the report. Could you please provide steps to reproduce this, so developers can easily see what is going on? Thanks!

**Comment by kraftbj** [comment] 2018-06-11 22:24
With the reproduction steps, please include the full code of the function you're using. My first hypothesis is that you may need to escape the URL and may not be already.

**Comment by chaintng** [comment] 2018-06-24 05:38
I think i have this problem also

I have problem when enable photon on https wordpress site.

Wordpress tried to request to this 
https://i2.wp.com/www.witcastthailand.com/wp-content/uploads/2017/12/unnamed-2.jpg?resize=272%2C182&ssl=1

and it return `Sorry, the parameters you provided were not valid`

All of the below URL work fine
https://i2.wp.com/www.witcastthailand.com/wp-content/uploads/2017/12/unnamed-2.jpg?resize=272%2C182
https://www.witcastthailand.com/wp-content/uploads/2017/12/unnamed-2.jpg
http://www.witcastthailand.com/wp-content/uploads/2017/12/unnamed-2.jpg

Could you please check if there is any bug in jetpack?

**Comment by sublines** [comment] 2018-06-24 09:36
@chaintng Yes, this is exactly the problem I had. 

@kraftbj Yes, I'm sure that would fix the problem but unfortunately I don't have time to reproduce the issue and see if you're right. It was easier for me to solve the issue by using the image path from my server instead of the jetpack URL.

**Comment by kraftbj** [comment] 2018-06-25 02:45
@chaintng Can you confirm the URL? https://i2.wp.com/www.witcastthailand.com/wp-content/uploads/2017/12/unnamed-2.jpg?resize=272%2C182&ssl=1 works for me. It may make sense to redirect this to support -- jetpack.com/contact-support/ 

@sublines Without duplication steps, I think I'll need to close this as invalid. Checking various sites, all of the images/URLs have ampersands encoded properly. My guess is the feed is being modified by a plugin that is not properly escaping the URls and would be where the bug is actually at.

**Comment by chaintng** [comment] 2018-06-25 02:49
@kraftbj weird... it didn't work yesterday... may be because of DNS populating... 

Anyway, Thanks for the update!

**Comment by jeherve** [comment] 2018-09-04 10:34
Closing as invalid, as the problem should be fixed by escaping the URLs.

**Closed by jeherve** 2018-09-04 10:34 UTC
Labels: Photon, [Status] Invalid, [Status] Needs Author Reply, [Type] Bug
