### ISSUE TITLE
Publicize: Custom message is not being pushed out to social media channels when in wpcom editor and message not saved

### ISSUE THREAD

**Issue by aleone89** [Automattic/jetpack#18948] opened 2021-02-26 17:07 UTC
#### Steps to reproduce the issue

1. In the WordPress.com Editor.
1. When in a post click on the Jetpack icon in the top right corner 
2. Tick Facebook and Twitter 
3. Enter in a message under "Customize your message" 
4. Publish post without saving the post as a draft.

[https://en-support.files.wordpress.com/2021/02/jetpack-publicize-custom-message.png](https://en-support.files.wordpress.com/2021/02/jetpack-publicize-custom-message.png
)

#### What I expected

On social media channels to see the custom message entered in to the Publicize settings in the post.

#### What happened instead

For Facebook: The content of the post was published, followed by a link to the post
For Twitter: Just the title of the post followed by a link

#### Context 

Reported here: https://wordpress.com/forums/topic/wordpress-doesnt-share-my-description-when-posting-to-facebook-and-twitter/ 

Reported here: https://twitter.com/MissPiinnkkii/status/1365323673331138562 

#### Workaround

Save your post as a draft after entering the custom message, so the custom message can be saved too.

#### Possible fix for WordPress.com

D66429-code

**Comment by jeherve** [comment] 2021-02-26 17:18
This is interesting, it reminds me of #11752, which was fixed a while ago. I can't reproduce right now on a WordPress.com site, the custom message seems to be used every time in my tests.

Are you able to consistently reproduce? If so, could you post the exact steps you follow to reproduce the issue, so we can try to reproduce on our end as well?

Thank you!

**Comment by supernovia** [comment] 2021-02-26 17:19
Let me see if I can get this on my test site / test account that I'd set up for testing last time we had this issue ...

**Comment by supernovia** [comment] 2021-02-26 17:39
I couldn't duplicate it yet (and last time I couldn't consistently duplicate it either.)

**Comment by aleone89** [comment] 2021-02-27 10:14
I have definitely been able to replicate this consistently. For good measure, I disconnected and reconnected Facebook and Twitter to my personal blog, and I've just published a post with the same results.

Facebook: https://d.pr/i/gvS3KU 
Twitter: https://d.pr/i/1WkELw 

The message I put into the custom message box was: "And this is how I built a hedgehog hotel, let's hope I get some guests soon." - making a point to make it different from the title of the post. 

I hope this is all useful.

**Comment by joweber123** [comment] 2021-03-01 06:10
I am able to reproduce this on my Atomic test site as well.  Strangely, if I try to reshare this, the custom message is correctly shared. 

![Markup on 2021-03-01 at 15:09:21](https://user-images.githubusercontent.com/24914028/109458456-26d85580-7aa0-11eb-8d13-0fc2b2bfd6f7.png)

**Comment by jeherve** [comment] 2021-03-02 08:52
> I have definitely been able to replicate this consistently. 

Excellent. Could you walk us through the exact steps you follow to create and publish your post, in the order you follow to get to the bug, so we can try to reproduce on our end as well? Thank you!

**Comment by aleone89** [comment] 2021-03-02 12:36
Hey, 

Sure thing, 

1. I first went to Tools > Marketing > Connections. 
2. I clicked disconnect under Facebook and Twitter. 
3. Then I clicked reconnect > followed the permissions in the pop-up modals 

I then went to: 

1. Site > Posts > Add New
2. Added a title > added the content > added tags > assigned a category 
3. Clicked on the Jetpack icon > Facebook, Twitter, Tumblr were already ticked > Added the custom message in the "Customize you message" field > Clicked publish > Final checks (Facebook, Twitter and Tumblr are ticked, customize message is the same as previously entered) > Clicked publish.

The Facebook, Twitter and Tumblr customized messages do not present. 

I've also just checked my Tumblr, and it looks like this is affected to: https://carrottopsallotment.tumblr.com/ 

I hope this helps.

**Comment by jeherve** [comment] 2021-03-02 14:08
> I then went to:
> Site > Posts > Add New

Do you know if the same problem happens when you write the post from wp-admin?

 > Added the custom message in the "Customize you message" field
> Clicked publish
> Final checks (Facebook, Twitter and Tumblr are ticked, customize message is the same as previously entered)
> Clicked publish.

What happens if you save your post as draft after entering the custom message, and before you hit publish?

**Comment by aleone89** [comment] 2021-03-02 15:41
> Do you know if the same problem happens when you write the post from wp-admin?

Ah interestingly, this doesn't happen when posting from WP Admin, I've just tested this with a new post:

Twitter: https://d.pr/i/kFqwPa
Facebook: https://d.pr/i/W8nk44
Tumblr: https://d.pr/i/poIJkr

> What happens if you save your post as draft after entering the custom message, and before you hit publish?

I entered the custom message in > saved > left the post > re-entered the post (again via wp-admin) the message was still there > hit publish and the message looks like it's gone out.

**Comment by jeherve** [comment] 2021-03-03 08:12
> I entered the custom message in > saved > left the post > re-entered the post (again via wp-admin) the message was still there > hit publish and the message looks like it's gone out.

Could you try to follow the same steps from the WordPress.com editor the next time you get to publish a new post?

**Comment by aleone89** [comment] 2021-03-03 08:50
Hello, 

> Could you try to follow the same steps from the WordPress.com editor the next time you get to publish a new post?

The steps detailed [here ](https://github.com/Automattic/jetpack/issues/18948#issuecomment-788878118) were done via the WordPress.com editor, following these steps here: https://wordpress.com/support/publicize/#customize-your-message 

Unless you mean the classic editor?

**Comment by aleone89** [comment] 2021-03-03 10:54
As discussed [here](https://a8c.slack.com/archives/C0CMN0V97/p1614762425383200). 

It looks like this is happening whereby there isn't a save between entering a custom message and hitting publish, in the WordPress.com editor only. 

To get this to work in the WordPress.com editor:

1. Created a new post
2. Create post
3. Add  the custom message
4. Saved draft 
5. Published and it looks like the custom message goes out:

Facebook: https://d.pr/i/07lAEy
Tumblr: https://d.pr/i/pUrU0Y

Twitter: Interestingly, it didn’t get pushed out to Twitter (at least I haven’t seen it yet with this latest post).

**Comment by aleone89** [comment] 2021-03-07 15:28
Another report here: https://wordpress.com/forums/topic/customizing-share-message-when-publishing/

**Comment by amamujee** [comment] 2021-03-08 00:28
This happened to me today as well on Twitter for this post -  https://aadil.blog/2021/03/07/the-why-behind-work/. I don't think this is a low priority personally - it's a pretty broken experience for WP.com users. cc @cathymcbride

**Comment by kraftbj** [comment] 2021-03-09 22:15
I'd be curious exactly when this started, if it impacts Simple, WoA, Jetpack self-hosted, all three, etc?

WordPress added some hooks to aid in plugins (like us) be able to get a completed post object from the REST API whereas before we could get a post before the meta was saved—which sounds like this may be that. @mdbitz -- Did those changes to sync land?

**Comment by nagpai** [comment] 2021-03-10 04:16
User report 
#28303200-hc

**Comment by NoHopeRadio** [comment] 2021-04-06 18:24
Another report here: hc-17349599

**Comment by chatoxz** [comment] 2021-04-10 18:32
I have another one here #3881334, the workaround did not work. The problem occurs with Twitter.

**Comment by supernovia** [comment] 2021-04-17 14:48
Another report on Twitter:
https://twitter.com/bookdout/status/1383340285980073993

**Comment by KokkieH** [comment] 2021-04-30 05:33
Another report in https://wordpress.com/forums/topic/customise-your-message-field-not-working/

**Comment by kriskarkoski** [comment] 2021-05-04 14:52
3922172-zen

**Comment by JessixBlade** [comment] 2021-05-06 00:42
3957251-zen

**Comment by marianearchimbaud** [comment] 2021-05-13 14:32
Found the same case here: 3969635-zen on a free site using the Twenty Fifteen theme.
I tried the same on my test site, but I was not able to reproduce the issue, everything worked as expected. I used the block editor for this test.
https://d.pr/i/Axgtg3
![image](https://user-images.githubusercontent.com/72237737/118140533-101e7b00-b3ce-11eb-9a2e-2c1cc3fbb618.png)

**Comment by rinazrina** [comment] 2021-05-27 01:16
Another report: 3993787-zd-woothemes

**Comment by Robertght** [comment] 2021-05-27 11:09
A new case in 23045307-hc

**Comment by AtrumGeost** [comment] 2021-05-31 15:01
+1 to this. I faced this issue on a new site when recording a webinar demo.

**Comment by mdbitz** [comment] 2021-06-03 14:17
Putting this task on my list for next week to review. It looks to be an issue with order of operations and the async publish job.

**Comment by mdbitz** [comment] 2021-06-11 18:24
didn't have time to get the root of this yet, still looking.

**Comment by zdenys** [comment] 2021-06-29 07:26
10219615-hc

**Comment by Robertght** [comment] 2021-07-01 11:55
Another case in 3892836-hc

The workaround worked for them.

**Comment by sophiegyo** [comment] 2021-07-23 07:48
Another report in 30682930-hc - confirmed that the workaround "customize Twitter message, save post as draft, then publish" works for them.

**Comment by pablinos** [comment] 2021-09-06 16:42
I've been doing a bit of digging on this, and I can replicate it both from `wp-admin` and in the Gutenframe.

It appears to be a race condition between the post being saved (and the data propagated) and the async job picking up the new post. I sandboxed the job, and ran it a few seconds after publish and it used the correct message. Hopefully we can fix it by queuing the job later in the publish process.

**Comment by pablinos** [comment] 2021-09-06 22:18
I've started a patch with a potential fix in D66429-code, but I still need to check if this is going to help with Jetpack sites or just wpcom Simple sites.

It's hard to replicate the race condition while developing, but I can confirm that the post meta we use to store the custom message is not saved by the time we queue the async job. Changing the hook to `wp_after_insert_post` fixes this. The jobs run so fast in production, that I can believe it's running before the metadata has been updated.

**Comment by mdbitz** [comment] 2021-09-06 22:29
@pablinos The patch in  D66429-code would apply to WP.com sites only. 

Publicize for Jetpack powered sites are hooked elsewhere see the jetpack_sync_remember_to_publicize_post function. For jetpack sites we explicitly moved the jetpack_published_post action to be triggered on [wp_after_insert_post](https://github.com/Automattic/jetpack/blob/master/projects/packages/sync/src/modules/class-posts.php#L631) to help with this race condition.

**Comment by pablinos** [comment] 2021-09-07 05:32
Thanks @mdbitz, yes I noticed that. There are equivalent hooks that are Jetpack specific, triggered as the post is synced, and I'm going to test them next. If we can see the job being queued before the metadata is synced then we can be fairly sure it's the same problem.

The biggest issue is that by making these processes run in development, it slows everything down and the race condition isn't occurring - at least for me.

I think the best we can do is make sure that any change doesn't break things and then test in production with specific users/sites.

**Comment by pablinos** [comment] 2021-09-07 15:34
Ok I've done a bit more digging on the Jetpack side of things. I'm not actually able to replicate this problem on a Jetpack site (more on this below), but as it's a race condition, that doesn't mean it's fixed. Assuming it is still an issue:

Again, when I sandbox all the requests, the problem doesn't occur. It's pure speculation, but I'm wondering if the multiple sync actions could have something to do with it. I see the following sync actions as I publish a post:

```
[07-Sep-2021 10:50:30 UTC] Jetpack sync action - jetpack_sync_save_post
[07-Sep-2021 10:50:30 UTC] Jetpack sync action - added_post_meta - spay_email
[07-Sep-2021 10:50:30 UTC] Jetpack sync action - added_post_meta - _wpas_mess <-- this is the customised publicize message
[07-Sep-2021 10:50:30 UTC] Jetpack sync action - added_post_meta - _wpas_tweetstorm
[07-Sep-2021 10:50:30 UTC] Jetpack sync action - jetpack_published_post
```

As you say @mdbitz it's the `jetpack_published_post` action where the post will be shared. I was wondering:

- Could it be that the sync actions are all separate requests and the publish action is happening on a different server (or simply in a separate request) to the post meta action which sets the message? If that's the case, then that could cause the race. Is there a way to ensure that a batch of requests are sent together, and that they're processed in a given order?
- Why does this not affect all networks? Perhaps twitter generally gets processed first? The initial report says that Facebook does not have this problem.
- It's very hacky, but how about scheduling the Publicize job for a short time in the future. I think we're talking about a matter of seconds, so sending the tweet 10-20 seconds after we process the publish event would probably solve it. This might help with something else I've noticed that Jetpack sites get a proper twitter card whereas simple sites often a simple link. I'm not sure if this is another bug, or a symptom of the post not being available at the time of the tweet, but it could also just be because I have Yoast installed on this test Jetpack site!
- Could we send a specific Publicize event, like the Re-publicize events, and pass the up to date data as arguments? That way we could schedule the job using that data, and know that we haven't got anything stale.

Lastly, and maybe most importantly, I've gone through a number of the above reports of this problem, and I can't find one that isn't a wordpress.com simple site. It could be that this is fixed for Jetpack sites, and we would need to merge my patch, or similar, to bring the same sort of change as #17838 to simple sites.

Is anyone able to replicate this on a Jetpack site? @aleone89 Was this specifically a problem with Jetpack sites or was the issue reported here because it relates to Publicize?

**Comment by mdbitz** [comment] 2021-09-07 15:54
> Could it be that the sync actions are all separate requests and the publish action is happening on a different server (or simply in a separate request) to the post meta action which sets the message? If that's the case, then that could cause the race. Is there a way to ensure that a batch of requests are sent together, and that they're processed in a given order?

Sync is designed to be order based. How it works is that the site sends us x actions and those items remain in the remote site's queue until WP.com sends back "we've processed these items." The site then will remove those items from the queue and send the next batch. 

With the jetpack_publishes_post firing on the wp_after_insert_post it means that the meta should all be processed before the publicize job is queued/run. However it is possible that if there was replication lag it could lead to the data not being picked up by the jobs when doing a read of the db..

As you mention a way to safe guard against this would be to put a delay on the publish jobs but it goes further than this in that there are other jobs triggered on the action including elastic indexing and they would all possible suffer from any replication lag issues.

**Comment by pablinos** [comment] 2021-09-07 16:46
Thanks for clarifying, I have very limited sync knowledge!

> However it is possible that if there was replication lag it could lead to the data not being picked up by the jobs when doing a read of the db..

I know that's possible but, on WordPress.com simple sites at least, I've not had a problem with jobs getting out of sync data from the database, as long as the function call to update the database has happened before the call to queue the job. As this code is run on WordPress.com it seems like it should show the same behaviour. If the requests got out of sync, then it's more likely to be an issue.

All this, and the guaranteed ordering you mention, along with not being able to replicate this on Jetpack sites, makes me think that this is a WordPress.com issue as I can reliably reproduce the problem there.

**Comment by aleone89** [comment] 2021-09-14 14:51
To note, I can't see/remember this working when an autosave happens between when the Custom Message is being written and when Publish is clicked.

From memory also, this is not replicable when post is written and published via wp-admin (for example something.wordpress.com/wp-admin/post-new.php)

**Comment by pablinos** [comment] 2021-09-23 09:48
I've deployed the fix to wpcom (r232173-wpcom) and that has fixed the issue for me on simple sites. I can't replicate this on Jetpack sites and @aleone89 confirmed to me that this is an issue on WordPress.com.

I'll close this issue for now, but obviously we can reopen it if the issue persists.

**Closed by pablinos** 2021-09-23 09:48 UTC
Labels: [Type] Bug, Publicize, [Status] In Progress, [Package] Sync, [Type] Happiness Request, Involves Happiness
