### ISSUE TITLE
Protect: Two math questions have to be answered

### ISSUE THREAD

**Issue by lumpysimon** [Automattic/jetpack#5263] opened 2016-10-05 18:53 UTC
#### Steps to reproduce the issue
- Activate the Protect module.
- Log out.
- Math fallback question is shown on login form. 
- Attempt to log in without answering the math question.
- The message "Please solve this math problem to prove that you are not a bot. Once you solve it, you will need to log in again." is shown with a math question.
- Answer the math question correctly.
- The login screen is shown again, but there is another math question on it.
#### What I expected

That after answering the math question correctly I would not have to immediately answer another one.
#### What happened instead

I have to answer two math questions.

**Comment by jom** [comment] 2017-01-22 17:40
I was able to reproduce this issue and am working on a fix. Tracking it, it looks like the `process_generate_math_page` action init action (added in `Jetpack_Protect_Math_Authenticate::__construct()`) is never actually called.

**Comment by jom** [comment] 2017-01-22 22:00
Related to #5646 (PR #5648) and #5131.

In working on this issue, I've fixed the issue in an alternative way to PR #5648 in my commit: jom/jetpack@f0254cdd116343a389d1e09b0a1b22dde74d77b4

Do we want the math equation to not show up if they've successfully gotten passed the independent math form? If so, should the `jpp_math_pass` cookie be checked in `Jetpack_Protect_Module::check_login_ability()` or in the form (#5648).

**Comment by jom** [comment] 2017-02-02 17:30
@dereksmart @samhotchkiss Looks like this was bumped to March, but do y'all have any insight into what should happen?

**Comment by samhotchkiss** [comment] 2017-02-08 05:32
The goal is that, when possible, we show a math question on the login form (either /wp-login.php or an embedded login form that fires the right hook).  If we can’t show that form for some reason, then there should be an interstitial with a math q

**Comment by jom** [comment] 2017-02-08 09:01
Thanks, @samhotchkiss. It looks like the interstitial math form is not being processed. This form is currently shown if the math question if the math answer was left blank _or_ the math form wasn't rendered on the login page when it should have (if, for example, you used an old login form on one tab when you've been trying to login in a second tab). When processed, I think this form should continue to show until the correct value is entered.

The question is, once the correct value has been entered, should the math question be displayed in the login form that shows up after the interstitial math form is processed. 

This is related to #5131. Right now, the scenarios that cause to the math question showing on the login page is different than what causes it to get processed. The `jpp_math_pass` transient (using the client's cookie) is never checked before showing the form, but is checked before processing it. That is what causes the login form to sometimes show the math problem but then not care what the user entered.

**Comment by samhotchkiss** [comment] 2017-02-10 05:41
Thanks, @jom -- are you planning to submit a PR on this to solve, or does #5131 properly address it?

**Comment by RavanH** [comment] 2017-03-23 13:56
@samhotchkiss 

> The goal is that, when possible, we show a math question on the login form (either /wp-login.php or an embedded login form that fires the right hook).

Addressed for widgets (like bbPress) that call hook login_form (not login_init!) in #5647 ... Or was there another hook planned for this occasion? 

The bbPress widget issue (where the math puzzle is not included even if JetPack needs to fall back to it) and this "two math questions" issue are not related except in the sense that the first makes the math treatment logic issue more evident because it causes it to occurs more often.

@jom thanks for looking into this! I'm still not sure why but I seem to run into this issue quite a lot on an Nginx server using FastCGI_Cache where WordPress Multisite and JetPack activated network wide. Have never been able to identify what actually causes it but many times the first math fallback puzzle is included on wp-login.php and when it's not, many times the second stand-alone path puzzle page comes up. At that point, this issue occurs where the math response is not treated properly.

> I think the jpp_math_pass transient (using the client's cookie) is never checked before showing the form, but is checked before processing it. That is what causes the login form to sometimes show the math problem but then not care what the user entered.

Addressed in #5648 where in protect.php at line 63 https://github.com/Automattic/jetpack/pull/5648/files#diff-123147fcf814053af680ad12c50a3381L62 the math fallback is included (again) so math_authenticate() and process_generate_math_page() can run (again) to check either cookie or response.

Note that I added a second cookie check to math_form() in math-fallback.php https://github.com/Automattic/jetpack/pull/5648/files#diff-a802e21ffd5ce5e370f7aaf1233b1a10L114 ... it might be better to move the cookie check to its own method.

Also note that I had to switch some class method calls (in the transient related methods) in protect.php to static because now, these can occur in different context. Feels like a work-around to me so it might be wise to pay closer attention to that logic...

**Comment by jom** [comment] 2017-03-23 15:23
@RavanH I was just picking this back up as well. Happy with using your branch.

I agree with moving the cookie check to its own method. I also placed the logic for checking the interstitial form input next to where the main form is checked (jom/jetpack@f0254cdd116343a389d1e09b0a1b22dde74d77b4). Next I was trying to track all the places that added the interstitial form (by constructing a new `Jetpack_Protect_Math_Authenticate` object) to see if we could check the cookie beforehand to prevent that from happening. 

I was also switching some methods to static methods.

**Comment by RavanH** [comment] 2017-03-23 15:49
@jom excellent! Let me know if you need me to test your code or anything :)

**Comment by RavanH** [comment] 2018-07-04 21:46
I feel silly replying to a bot here but... yes, it's still a valid issue. Steps to reproduce are here https://github.com/Automattic/jetpack/pull/5648#issuecomment-396745110 

Please note that the steps needs version 6.2.1 because that version is still susceptible to another (but related) incompatibility with the bbPress login widget. A patch to fix the incompatibility has been accepted for later release but that patch does not fix the issue raised in this thread (it just prevents it from occurring as a side-effect in that particular case)

**Comment by RavanH** [comment] 2019-01-01 22:55
Again marked as stale, but still relevant. The latest related PR can be found on https://github.com/Automattic/jetpack/pull/10602

**Comment by RavanH** [comment] 2019-01-28 15:16
Can this be closed since https://github.com/Automattic/jetpack/pull/10602 has been merged?

**Comment by jeherve** [comment] 2019-01-28 15:18
Yeah, you're right! Closing.

**Closed by jeherve** 2019-01-28 15:18 UTC
Labels: Protect, [Pri] Normal, [Type] Bug

**Comment by RavanH** [comment] 2019-01-28 15:19
There is https://github.com/Automattic/jetpack/issues/5131 referenced too but I'm not sure that one is related...
