### ISSUE TITLE
WooCommerce Image Thumbnail Crops Don't Work with Jetpack's Image CDN Enabled

### ISSUE THREAD

**Issue by ash1eygrace** [Automattic/jetpack#30404] opened 2023-05-02 17:05 UTC
### Impacted plugin

Jetpack

### Quick summary

For WooCommerce sites, a problem arises when both thumbnail crop settings and Jetpack's Image CDN are enabled. When the thumbnail crop ratio is set to 1:1 in Customizer → WooCommerce → Product Images, the cropping fails to maintain the desired ratio when Jetpack's Image CDN is active.

Deactivating the Image CDN solves the issue. 

### Steps to reproduce

1. Set up an Atomic site on WordPress.com or create a self-hosted WordPress site.
2. Install and activate WooCommerce.
3. In Customizer, navigate to WooCommerce → Product Images and set the image crop ratio for thumbnails to 1:1.
4. Create a product and add portrait-sized images (height greater than width) to the Product Gallery in the product. 
5. Install and activate Jetpack, then enable the Image CDN module at {siteaddress.com}/wp-admin/admin.php?page=jetpack_modules 

### A clear and concise description of what you expected to happen.

The image thumbnails on the product pages should maintain a perfect square crop (1:1) based on the settings in Customizer. Like this: 

<img width="902" alt="Markup 2023-05-02 at 10 55 49" src="https://user-images.githubusercontent.com/29527450/235733392-120a1641-5de5-4257-812b-ae3b2ca1c51d.png">

### What actually happened

The image thumbnail cropping does not retain the 1:1 ratio when Jetpack's Image CDN is enabled.  Instead, the images just display as the default image ratio without honoring the crop: 

<img width="896" alt="Markup 2023-05-02 at 10 57 18" src="https://user-images.githubusercontent.com/29527450/235733769-17bf9532-c2e4-4b36-8461-d8f87c6bdcd1.png">

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic, Self-hosted

### Logs or notes

 p1683042919231269-slack-C03TY6J1A

**Comment by jeherve** [comment] 2023-05-03 07:16
Closing as duplicate of #9345.

**Closed as completed by jeherve** 2023-05-03 07:16 UTC
Labels: Bug, [Closed] Duplicate, [Feature] Photon, [Pri] Normal, [Plugin] Jetpack, [Platform] Atomic
