### ISSUE TITLE
Pay with PayPal: Currency indicator is fixed on the end.

### ISSUE THREAD

**Issue by kwight** [Automattic/jetpack#17336] opened 2020-09-30 20:39 UTC
Instead of the currency indicator always being after the value, its placement should depend on the currency itself (eg. dollars at the front).

<img width="603" alt="Screen Shot 2020-09-30 at 1 34 03 PM" src="https://user-images.githubusercontent.com/349751/94737178-42d5a080-0322-11eb-977d-590b23519cef.png">

**Comment by jeherve** [comment] 2020-10-01 07:51
closing as duplicate of #11897.

**Closed by jeherve** 2020-10-01 07:51 UTC
Labels: Pay with Paypal, [Pri] Normal, [Type] Bug
