### ISSUE TITLE
Video: The "Media & Text" Block Does Not Render The VideoPress Player

### ISSUE THREAD

**Issue by jgcaruso** [Automattic/jetpack#15152] opened 2020-03-27 18:33 UTC
#### Steps to reproduce the issue
1. Ensure 'Enable high-speed, ad-free video player' is enabled under Jetpack -> Performance -> Media -> Video
2. Create a new post
3. Add a "Media & Text" block
4. Upload a new video file, then wait (there isn't a progress indicator)...

#### What I expected
The VideoPress player should have rendered since it is enabled in the settings. Doing the same steps with the standard Video block works correctly.

#### What happened instead
An error 'No video with supported format and MIME type found' was displayed. If you inspect the element, it is an HTML5 video component, not the VideoPress player, and the `src` link is to the attachment page, not the media file.

**Screenshots**
<img width="1313" alt="Screen Shot 2020-03-27 at 2 29 14 PM" src="https://user-images.githubusercontent.com/4081020/77788283-5d5b5400-7037-11ea-9046-c2606c43d67e.png">
<img width="1492" alt="Screen Shot 2020-03-27 at 2 32 53 PM" src="https://user-images.githubusercontent.com/4081020/77788569-dce92300-7037-11ea-99c5-c15671c51fbc.png">

If there wasn't meant to be support for the VideoPress player in this block, then I think the `src` link in the html5 video tag should be the direct link to the media file, instead of the link to the 'attachment page'

**Comment by jeherve** [comment] 2020-03-27 18:35
That's indeed a known issue. I'll close this as duplicate of #13239.

**Closed by jeherve** 2020-03-27 18:35 UTC
Labels: VideoPress
