### ISSUE TITLE
Allow nested tiered plans for paid content using Paid Content Block

### ISSUE THREAD

**Issue by sajmes** [Automattic/jetpack#33669] opened 2023-10-18 19:53 UTC
### Impacted plugin

Jetpack

### What

It would be great to add a feature where a user can designate parent tiers in their paid content plans, allowing higher tier plans to provide access to lower tiers.

### How

Perhaps when designating a new plan, and when more than one plan is present on a site, there is an option to 'include access to content from other plans', where a user can designate that the plan the subscriber is purchasing can access content added to other tiers.

Example would be a Gold tier which provides access to all content, a Silver tier with limited access, and Bronze with more limited still. 

Currently users have to use elaborate workarounds: https://wordpress.com/learn/courses/membership-sites-101/paid-content-block/

**Comment by millerf** [comment] 2023-10-19 08:53
Duplicates https://github.com/Automattic/wp-calypso/issues/41606

**Comment by cuemarie** [comment] 2023-10-19 19:30
Thanks @millerf - if you see any reason to keep this open, feel free to reopen, but otherwise I'll close this as a dupe.

📌 ACTIONS
- Closed as duplicate of https://github.com/Automattic/wp-calypso/issues/41606

**Closed as not planned by cuemarie** 2023-10-19 19:30 UTC
Labels: [Closed] Duplicate, New Feature, [Plugin] Jetpack, [Feature] Paid Content
