### ISSUE TITLE
jetpack subscribe does not validate

### ISSUE THREAD

**Issue by gemal** [Automattic/jetpack#2665] opened 2015-09-03 07:57 UTC
I have the JetPack subscribe widget activated

But when I try to HTML validate my blog I get an error for the JetPack subscribe widget:
https://validator.w3.org/nu/?doc=http%3A%2F%2Fblog.dinnerbooking.com

"The for attribute of the label element must refer to a non-hidden form control."

The code produced on the page:
http://blog.dinnerbooking.com/

is this
```
<p id="subscribe-email">
	<label id="jetpack-subscribe-label" for="subscribe-field">
	E-mail-adresse
	</label>
	<input type="email" name="email" required="required" class="required" value="" id="subscribe-field-blog_subscription-2" placeholder="E-mail-adresse" />
</p>

**Comment by dereksmart** [comment] 2015-09-03 13:39
Thanks for the report.  Is duplicate of #2632.

**Closed by dereksmart** 2015-09-03 13:39 UTC
