### ISSUE TITLE
Contact Form: Checkbox with Multiple Items in a form does not appear in Calypso

### ISSUE THREAD

**Issue by abidhahmed** [Automattic/jetpack#9976] opened 2018-08-02 07:51 UTC
#### Steps to reproduce the issue

1. Add a new form with Field Type set to `Checkbox with Multiple Items` from WP-Admin
2. Add multiple options and save
3. Edit the same form under Calypso

#### What I expected

I expect to see the Checkbox with Multiple Items (or Radio with multiple options) in the form to be editable in Calypso.

#### What happened instead

I see no checkbox / radio. However, switching over to HTML tab does show that the option exists, just not visible. While trying to edit the form in Calypso, I see an empty Field Type with the options added earlier.

(missing the whole checkbox with multiple items in the screenshot below)
![form calypso 1](https://user-images.githubusercontent.com/7570415/43569945-b711c720-9656-11e8-8548-16cd258fdafb.png)

(empty field type with options added in the form from wp-admin)
![form calypso](https://user-images.githubusercontent.com/7570415/43569870-76812b24-9656-11e8-9fd4-08cc7d50bc16.png)

**Comment by jeherve** [comment] 2018-09-05 10:40
Closing this as duplicate of https://github.com/Automattic/wp-calypso/issues/14117. The option was added to the form, but not to Calypso itself. 
That is where it will need to be fixed.

**Closed by jeherve** 2018-09-05 10:40 UTC
Labels: Contact Form, [Pri] Low, [Type] Bug, [Type] Duplicate
