### ISSUE TITLE
Tiled galleries: Uploading image from the existing gallery not working

### ISSUE THREAD

**Issue by bindlegirl** [Automattic/jetpack#14508] opened 2020-01-29 09:44 UTC
When I try uploading a new image to the existing tiled gallery and use Upload an image link at the bottom of the gallery, I do get to select the file but clicking on the Open button does nothing. No image is added. Adding images through Edit window works.

The same problem happens in WP-Admin and WordPress.com dashboard.
Tested on a clean site, a default theme and no other plugins than Jetpack were enabled.
Tested in: Chrome, FF and DuckDuckGo

#### Steps to reproduce the issue

1. Go to existing tiled gallery
2. Click on Upload an image
3. Pick an image and click Open
4. Nothing happens

#### What I expected

The image should be uploaded and added to the gallery.

#### What happened instead

Nothing

**Screenshots**

![tiledgall-bug](https://user-images.githubusercontent.com/1242807/73344628-f57ccd00-4282-11ea-87cd-02efaf9644fe.png)

Reported in zd-2664014

@jeherve Can you take a look at this?

**Comment by jeherve** [comment] 2020-01-29 10:49
closing as duplicate of #14457

**Closed by jeherve** 2020-01-29 10:49 UTC
Labels: Tiled Galleries, [Block] Tiled Gallery, [Type] Bug, [Type] Happiness Request
