### ISSUE TITLE
Simple Payments: Duplicating the block and editing it doesn't work as expected

### ISSUE THREAD

**Issue by bplv112** [Automattic/jetpack#11406] opened 2019-02-23 13:00 UTC
#### Steps to reproduce the issue

1. Create new page/post.
2. Use block editor and add simple payments block.
3. Add data to the block and duplicate it from the block menu.
5. Enter new data on the duplicated block.
4. Preview the post/page or save it and check front-end to see the error.

#### What I expected
I expected to see two different blocks as I duplicated the first one to create a new one.

#### What happened instead
I saw that on the front-end the two blocks look the same even though you change the content and have the same block id.

**Comment by torres126** [comment] 2019-02-23 17:26
Automattic/wp-calypso#30892

**Comment by jeherve** [comment] 2019-02-25 10:17
Thanks for the report. I'll close this as duplicate of https://github.com/Automattic/wp-calypso/issues/30892 , where the problem is being discussed right now.

**Comment by scruffian** [comment] 2019-04-03 14:02
Opening this instead of the Calypso issue: https://github.com/Automattic/wp-calypso/issues/30892

**Comment by GeoJunkie** [comment] 2020-03-25 14:42
This isn't only happening in duplicated Simple Payments blocks. The duplication also happens when a second block is added: https://github.com/Automattic/jetpack/issues/12801#issuecomment-603874149

**Comment by jeherve** [comment] 2020-03-26 08:03
I'll close this as duplicate of #12801

**Closed by jeherve** 2020-03-26 08:03 UTC
Labels: Gutenberg, Simple Payments, [Type] Bug
