### ISSUE TITLE
dashicons.min.css Loading When Jetpack Site Is Connected, Yet All Modules Are Deactivated

### ISSUE THREAD

**Issue by pmciano** [Automattic/jetpack#9913] opened 2018-07-13 11:26 UTC
#### Steps to reproduce the issue

1. Activate Jetpack and connect it to WordPress.com
2. Deactivate all modules
3. Load frontend of site

#### What I expected

dashicons.min.css would not load.

#### What happened instead

dashicons.min.css loads.

Thanks to @zinigor's troubleshooting, it appears that the Jetpack Identity Crisis-handling UI may be using dashicons.

Originally, this issue was [reported in the forums](https://wordpress.org/support/topic/jetpack-loads-dashicons-css-in-frontend/).

**Comment by jeherve** [comment] 2018-09-05 09:18
@vijayaraghavanramanan You are correct, it comes from this feature.

Closing this issue as duplicate of #10089

**Closed by jeherve** 2018-09-05 09:18 UTC
Labels: Geo Location, [Pri] Low, [Type] Bug, [Type] Duplicate
