### ISSUE TITLE
Settings: Discussion > Comments; align help icons better

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#6196] opened 2017-01-27 20:41 UTC
Line up the (?) icons properly with the labels they are about:

![screen shot 2017-01-27 at 1 41 21 pm](https://cloud.githubusercontent.com/assets/108942/22386895/5ac3b0c8-e496-11e6-97e4-31d5b547904b.png)

**Comment by beaulebens** [comment] 2017-02-02 23:58
Related: #6273

**Comment by MichaelArestad** [comment] 2017-02-10 06:12
Closing this as it's a duplicate of #6273.

**Closed by MichaelArestad** 2017-02-10 06:12 UTC
Labels: Admin Page
