### ISSUE TITLE
Twitter Timeline Widget user profile photo not displaying

### ISSUE THREAD

**Issue by agoll** [Automattic/jetpack#9197] opened 2018-03-30 19:27 UTC
Steps to reproduce this issue: 
1. Set up widget on test site with user’s Twitter profile; profile photo did not display

2. Set up widget on test site with random user Twitter profile; profile photo did not display.

3. Switched out themes and tweaked basic settings to check for conflicts; issue persisted 

4. Asked another person to test this issue; they were able to replicate. 

User came to us with the problem in 1052613-zen. User is unable to see twitter profile image in the Twitter Timeline Widget.
![twitter-screenshot](https://user-images.githubusercontent.com/34747792/38150831-0ff49750-341e-11e8-9426-19f905eee2f4.jpeg)

**Comment by keynet** [comment] 2018-03-31 10:19
I have the same issue, started a week or 2 back. 
Tried with other plugins, they show the avatar OK, so it seems to be a Jetpack plugin issue
![image](https://user-images.githubusercontent.com/5302023/38162221-61c4711a-34d5-11e8-8cff-6fa723cb2491.png)

**Comment by jeherve** [comment] 2018-04-03 09:39
The problem does not seem to be limited to Jetpack. I experience the same problem on a site that does not use Jetpack, but instead uses a text widget and the HTML code provided by Twitter here:
https://publish.twitter.com/#

```
<a class="twitter-timeline" href="https://twitter.com/jeherve?ref_src=twsrc%5Etfw">Tweets by jeherve</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```

I let the Twitter developers know about the issue here:
https://twittercommunity.com/t/profile-picture-not-displayed-in-embedded-twitter-profile-widget/103761

@keynet You mentioned that you did not experience the issue with other plugins. It is possible that those plugins do not use the official Twitter library to display the embedded timelines. That most likely explains the difference.

Closing this issue, but I will update it when I receive a reply on that thread I created to report the issue to the Twitter developers.

**Closed by jeherve** 2018-04-03 09:39 UTC
Labels: Sharing, [Type] Bug

**Comment by keynet** [comment] 2018-04-03 10:14
Yes, it's possible. I tried a few other plugins, but none as as good as the Jetpack one. 
I noted myself that the Twitter code doesn't show the avatar, but then again it doesn't seem to allow space for it, so perhaps that's working as designed

**Comment by jeherve** [comment] 2018-04-04 12:53
The Twitter developers have now fixed the issue, as per their reply here:
https://twittercommunity.com/t/profile-picture-not-displayed-in-embedded-twitter-profile-widget/103761/4?u=jeherve

You should consequently be all set now!
