### ISSUE TITLE
Gallery Widget: Existing Gallery widget is cut off to the sides.

### ISSUE THREAD

**Issue by chaitanyamsv** [Automattic/jetpack#14235] opened 2019-12-14 02:53 UTC
#### Steps to reproduce the issue

This issue is not reproducible on the newly added widgets. However, the existing gallery widgets are getting truncated to the right.

So far I have seen this on the sidebars of two sites: 

https://lorieubanks.blog/
https://dimcfarlane369.wordpress.com/

#### What I expected
Gallery to be displayed correctly in three-columns as set up on the widget.

#### What happened instead

The gallery is getting cut off on the right.

In both cases, I noticed the following error in the browser console:

`tiled-gallery.min.js:1 Failed to load resource: the server responded with a status of 404 ()`

**Comment by chaitanyamsv** [comment] 2019-12-14 03:04
2560254-zen and 2560404-zen

**Comment by kristarella** [comment] 2019-12-14 03:48
2560484-zen

**Comment by hacchism** [comment] 2019-12-14 06:55
Another report: 2560614-zen

Seeing the same console error too:
`tiled-gallery.min.js:1 Failed to load resource: the server responded with a status of 404 ()`

**Comment by nagpai** [comment] 2019-12-14 08:02
Another report: #2560586-zen

Site: http://profoodieorlando.wordpress.com

theme on the site: Independent Publisher 2 with sidebar enabled.

The gallery container is forced to a width of 1100px with inline CSS,  whereas the content container width is far less. 

I see same console errors as noted earlier.

**Comment by kriskorn** [comment] 2019-12-14 08:25
2560769-zen

**Comment by sophiegyo** [comment] 2019-12-14 08:36
Another thing that a user pointed out to us is that image captions are showing permanently, not just on hover.  Chait's second example shows it: https://dimcfarlane369.wordpress.com/

I noticed it due to a report from a user who doesn't have tiled mosaics (so there's no content cut-off) but they are seeing the captions.
Site: https://danielmielniczek.com/reportages/travaux-recents/la-cimade-de-beziers/

When I check the console for the page above, this is the error I see:
`GET https://s0.wp.com/wp-content/mu-plugins/jetpack/_inc/build/tiled-gallery/tiled-gallery/tiled-gallery.min.js?ver=5.3.1 net::ERR_ABORTED 404`

Report: 2560340-zen

**Comment by edwinho89** [comment] 2019-12-14 09:47
2560835-zen

**Comment by rachelwinspear** [comment] 2019-12-14 12:51
2560839-zen

**Comment by rachelwinspear** [comment] 2019-12-14 13:22
2561022-zen

**Comment by rachelwinspear** [comment] 2019-12-14 13:25
2561057-zen

**Comment by JoshuaGoode** [comment] 2019-12-14 14:53
Referencing similar issue: https://github.com/Automattic/wp-calypso/issues/38434

Appears to be impacting WordPress.com sites without plugins or hosting configurations enabled (simple).   Haven't reproduced on self-hosted yet.

**Comment by JoshuaGoode** [comment] 2019-12-14 15:58
Should be resolved by D36769-code cc @kraftbj

**Closed by JoshuaGoode** 2019-12-14 15:58 UTC
Labels: [Pri] High, [Type] Happiness Request

**Comment by JoshuaGoode** [comment] 2019-12-14 17:10
While the primary issue here was missing styling, and that is now resolved, there are issues with the gallery widget missing style settings that appear somewhat related.


`Failed to load resource: the server responded with a status of 404 ()`
`https://s1.wp.com/wp-content/mu-plugins/jetpack/_inc/build/gallery-settings.min.js?ver=20121225`

Creating a new issue.
