### ISSUE TITLE
Core Video block does not validate when Jetpack is active

### ISSUE THREAD

**Issue by erickyle** [Automattic/jetpack#23953] opened 2022-04-14 17:18 UTC
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Install WordPress v5.9.3.
2. Create a new page.
3. Insert a Video block and upload/select a video to/from the Media Library. (Used 2014-slider-mobile-behavior.mov from Theme Unit Test data).
4. Publish and view the page.
5. Install and activate Jetpack 10.8.
6. Do not establish a connection to Jetpack, instead set it to use Offline Mode.
7. Edit the page containing the Video block.

### A clear and concise description of what you expected to happen.

The Video block should display properly in the editor and not trigger a validation notice.

![image](https://user-images.githubusercontent.com/14015502/163438349-692f24a0-57b2-4329-bf01-10e519eba67c.png)

The source code for the block was expected to be:

```
<!-- wp:video {"id":7} -->
<figure class="wp-block-video"><video controls src="https://wordpress.local/wp-content/uploads/2022/04/2014-slider-mobile-behavior.mov"></video><figcaption>This is a caption for the video.</figcaption></figure>
<!-- /wp:video -->
```

### What actually happened

The Video block is accompanied by a notice stating "This block contains unexpected or invalid content.".

![image](https://user-images.githubusercontent.com/14015502/163438221-7c1417ca-8349-4a21-a541-ffecec51b6d1.png)

Clicking the "Attempt Block Recovery" button results in the source code being transformed to:

```
<!-- wp:video {"id":7} -->
<figure class="wp-block-video"><figcaption>This is a caption for the video.</figcaption></figure>
<!-- /wp:video -->
```

Essentially the video tag is removed. It is possible to select the video again and all is well, though having to do so is inconvenient. When selecting the video again with Jetpack active, the source code is transformed to:

```
<!-- wp:video {"id":7,"src":"http://wordpress.local/wp-content/uploads/2022/04/2014-slider-mobile-behavior.mov"} -->
<figure class="wp-block-video"><video controls src="http://wordpress.local/wp-content/uploads/2022/04/2014-slider-mobile-behavior.mov"></video><figcaption>This is a caption for the video.</figcaption></figure>
<!-- /wp:video -->
```

### Other information

This report is an expanded version of issue #22836.

Interestingly enough, if you disable Jetpack and edit the page again, no validation notice is displayed. So this only seems to affect Video blocks that were inserted without the Jetpack plugin being active.

### Operating System

macOS

### OS Version

12.3.1

### Browser

Firefox

### Browser Version(s)

99.0.1

**Comment by richardmorrison** [comment] 2022-08-15 22:43
This issue still exists, and looks to have been resolved for the VideoPress block, and not in the standard Video Block.
The initial description/issue is still relevant information, and the same with WordPress 6.0.1.

Are we able to have this looked at for the standard Gutenberg Video Block?

**Comment by samiff** [comment] 2022-08-16 19:53
@richardmorrison I'm not able to reproduce the error mentioned in the original issue. Are you able to provide reproduction steps or the full JS error from the console?

I did however notice an issue unrelated to Jetpack that might have added to confusion here:

- Start with a fresh WP 6.0.1 site
- Create a post with a new `core/video` block & caption then publish the post.
- Install the Gutenberg plugin.
- Edit the published post and it now shows the following error:

```js
Block validation: Block validation failed for `core/video` (Object).

Content generated by `save` function:

<figure class="wp-block-video"><video controls src="https://example.com/wp-content/uploads/2022/08/sm-wp-support-test-video-2.mp4"></video><figcaption class="wp-element-caption">Test Caption added with no plugins active.</figcaption></figure>

Content retrieved from post body:

<figure class="wp-block-video"><video controls src="https://example.com/wp-content/uploads/2022/08/sm-wp-support-test-video-2.mp4"></video><figcaption>Test Caption added with no plugins active.</figcaption></figure>
```

**Comment by richardmorrison** [comment] 2022-08-16 22:13
To reproduce what I am seeing:
- Create new post (with Gutenberg and Jetpack plugins active)
- Add Video Block, and any video
- Block video settings, select "**play inline**"
- Safe draft
- Refresh page
- See error appear on Video Block

<img width="912" alt="Screen Shot 2022-08-17 at 10 09 42 AM" src="https://user-images.githubusercontent.com/61720320/184993969-c63f20f3-2c15-4d18-844a-6c9345c2d44d.png">

Console errors:

<img width="1217" alt="Screen Shot 2022-08-17 at 9 51 57 AM" src="https://user-images.githubusercontent.com/61720320/184993881-d7f48c29-0705-4c0d-ae07-676bfee91227.png">

Environment:
WordPress 6.0.1
PHP 7.4

Thoughts:
It does only appear to happen when the "play inline" option is selected for the Video Block.

<img width="275" alt="Screen Shot 2022-08-17 at 10 12 46 AM" src="https://user-images.githubusercontent.com/61720320/184994326-a8657fa7-a747-4e34-a066-011ed47fc62c.png">

**Comment by samiff** [comment] 2022-08-23 19:50
@Automattic/greenhouse Is the [above report](https://github.com/Automattic/jetpack/issues/23953#issuecomment-1217223583) something one of you could have a look at? I tried playing with it on my end by adding a selector to the `playsinline` attribute, but didn't have any luck in getting the block validation error to go away. I'm probably misunderstanding the flow of deprecations or some other block settings nuance here.

**Comment by jgcaruso** [comment] 2022-08-24 14:31
I can't seem to reproduce this issue. I tried on a brand new Jurassic ninja site (using default options) and in my jetpack dev environment with latest code pulled.


I was able to see it though once I disabled VideoPress in the Jetpack settings. Maybe this is what I was missing?

The issue appears to be the inclusion of `=""` after the attributes for `controls` and `playsinline`. Not entirely sure what is responsible for that. But it is only happening for a `/video` block that is not the Jetpack overrided `/video` block.

<img width="1280" alt="Screen Shot 2022-08-24 at 10 38 04 AM" src="https://user-images.githubusercontent.com/4081020/186446971-b76148b7-73aa-4422-962b-c107c7445c8c.png">

**Comment by dhasilva** [comment] 2023-02-21 16:35
I could only reproduce the issue with `playsinline`, and that only happens to non-videopress videos.
The diff here is not the same, though:

```
<!-- wp:video {"id":12,"title":"people-pouring-a-warm-drink-around-a-campfire"} -->
<figure class="wp-block-video"><video controls src="https://typical-planarian.jurassic.ninja/wp-content/uploads/2023/02/people-pouring-a-warm-drink-around-a-campfire.mp4"></video><figcaption class="wp-element-caption">Test</figcaption></figure>
<!-- /wp:video -->
```
to
```
<!-- wp:video {"id":12,"title":"people-pouring-a-warm-drink-around-a-campfire"} -->
<figure class="wp-block-video"><video controls src="https://typical-planarian.jurassic.ninja/wp-content/uploads/2023/02/people-pouring-a-warm-drink-around-a-campfire.mp4" playsinline></video><figcaption class="wp-element-caption">Test</figcaption></figure>
<!-- /wp:video -->
```

The only change is: `....mp4" playsinline>...`

The other issues seems to be resolved at this point.

**Comment by dhasilva** [comment] 2023-02-21 17:00
I created a more specific issue about the `playsinline` issue: https://github.com/Automattic/jetpack/issues/29075.
Closing this issued as fixed in favor of the specific issue above. Feel free to reopen the issue if you think it is necessary.

**Closed by dhasilva** 2023-02-21 17:00 UTC
Labels: [Type] Bug, VideoPress, [Pri] Normal, [Plugin] Jetpack, [Block] VideoPress
