### ISSUE TITLE
Subscriptions: Tiled Galleries not showing correctly on Email Subscriptions

### ISSUE THREAD

**Issue by muffinpeace** [Automattic/jetpack#19955] opened 2021-05-27 14:02 UTC
#### Steps to reproduce the issue

1. Enable subscription by email for posts and comments: Jetpack > Discussion > **Let visitors subscribe to new posts and comments via email**.
2. Subscribe to the blog and enable **Email me new posts** and **Instantly**.
3. Activate Site Accelerator on Jetpack > Performance.
4. Create a new post and add a Tiled Gallery with 5+ images, Tiled Columns at 3 colums.
5. Publish the post and see how they show up on the email.

#### What I expected

Images showing a little bit more organized almost identical to how they show up on the post.

#### What happened instead

- Images are scattered and almost taking space from each other.
**Screenshots**
On the post: https://d.pr/i/wH3knT
![](https://cdn-std.droplr.net/files/acc_1159618/wH3knT)
In the email: https://d.pr/i/787sh2
![](https://cdn-std.droplr.net/files/acc_1159618/787sh2)

I am adding this as I had reproduced the issue after we received a query on 4023329-zen.

**Comment by jeherve** [comment] 2021-05-27 14:03
closing as duplicate of #18909.

**Closed by jeherve** 2021-05-27 14:03 UTC
Labels: [Type] Bug, [Type] Happiness Request
