### ISSUE TITLE
Contact Info Widget Using Unsupported Code

### ISSUE THREAD

**Issue by sageBrownell** [Automattic/jetpack#8130] opened 2017-11-08 18:52 UTC
The Contact Info Widget with the Google map iframe is using "frameborder=0" in the code which is not supported by HTML 5 and no longer valid with W3C Standards. Should be using CSS for this instead.

<img width="153" alt="screen shot 2017-11-08 at 10 51 59 am" src="https://user-images.githubusercontent.com/3833099/32568378-e9b8dc1a-c472-11e7-8200-8c2981fb0315.png">

Reported in 776679-zen

**Comment by jeherve** [comment] 2017-11-09 09:31
Closing as duplicate of #1071

**Closed by jeherve** 2017-11-09 09:31 UTC
Labels: Performance, [Pri] Low, [Type] Quick Fix
