### ISSUE TITLE
Error when a turning on a custom role under Count logged in page views from in Jetpack Stats

### ISSUE THREAD

**Issue by pehaa** [Automattic/jetpack#31205] opened 2023-06-06 09:18 UTC
### Impacted plugin

Jetpack

### Quick summary

Jetpack stats allows to configure "Count logged in page views from" for different user roles. This setting is switched off for all roles by default. For a custom role, there is an error when this setting is toggled on.

### Steps to reproduce

1. Install and connect Jetpack
2. Add a new custom user role:
```
/* Create Author Pro User Role */
add_role(
    'author_pro', //  System name of the role.
    __( 'Author Pro'  ), // Display name of the role.
    array(
    )
);
```
3. Notice that 'Author Pro' role is correctly added
4. Notice that 'Author Pro' role is correctly listed in Jetpack > Settings > Traffic > Jetpack Stats
5. Make sure that no role is switched on (see note below)
6. Swich 'Author Pro' on under **Count logged in page views from**
7. Notice `Error updating settings. Invalid parameter(s): count_roles (Status 400)` error 
8. The setting is not saved

Alternative way of testing:
- Install WooCommerce plugin
- Go to Jetpack > Settings > Traffic > Jetpack Stats
- Make sure that no role is switched on
- Switch on Customer or Shop Manager
- Notice `Error updating settings. Invalid parameter(s): count_roles (Status 400)` error 
- The setting is not saved

**Note:** Interestingly, the error is gone if one  of the built-in roles is toggled on under  **Count logged in page views from**

![Markup on 2023-06-06 at 11:16:37](https://github.com/Automattic/jetpack/assets/774920/7cdbc331-45c6-44e5-8a22-1a9ce15f4673)

### A clear and concise description of what you expected to happen.

It's possible to activate  **Count logged in page views from** for a given custom role.

### What actually happened

`Error updating settings. Invalid parameter(s): count_roles (Status 400)` and setting is not saved

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

Tested Jetpack 12.1.1 and 12-2beta

**Comment by pehaa** [comment] 2023-06-06 09:22
Reported by user 6316984-zd-woothemes

**Comment by pehaa** [comment] 2023-06-06 14:53
I tested and confirmed the same issue on Atomic sites.
Not sure if it's possible to add a custom role on a Simple site.

**Comment by formosattic** [comment] 2023-06-12 14:11
> Not sure if it's possible to add a custom role on a Simple site.

It's not possible.  Simple sites only have these roles: Administrator, Editor, Author, Contributor, Viewer, Subscriber.
Reference doc: https://wordpress.com/support/user-roles/#list-of-user-roles

**Comment by bizanimesh** [comment] 2023-06-13 06:36
One more report: 6351677-zd-woothemes

**Comment by kangzj** [comment] 2024-06-05 02:27
I tested both on self hosted Jetpack site and an Atomic site, and I wasn't able to reproduce this. Does anyone have an existing site with the issue that I can take a look? Thanks



https://github.com/Automattic/jetpack/assets/1425433/0e9a3c15-29d0-44bc-a52a-0adbaf646abe

**Comment by kangzj** [comment] 2024-07-24 23:06
I'm closing it as I was not able to reproduce. Feel free to reopen if it still happens for you. Thanks all!

**Closed as not planned by kangzj** 2024-07-24 23:06 UTC
Labels: Bug, [Feature] Stats Data, [Pri] Low, Customer Report [LEGACY], [Plugin] Jetpack, Triaged, [Package] Stats Data, [Status] Priority Review Triggered
