### ISSUE TITLE
Facebook comments not posting

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/jetpack#7465] opened 2017-07-14 12:07 UTC
When trying to post a comment using Facebook, the FB authentication works fine, but when you actually click 'Post Comment', the form disappears, and it just shows a loading spinner and the comment is never posted.

Reported in 3320619-t and confirmed by myself and @codestor4 on test sites.

**Comment by kraftbj** [comment] 2017-07-14 15:07
Is this happening on dotcom sites with FB auth too or only Jetpack?

**Comment by danjjohnson** [comment] 2017-07-14 15:38
Hmm, on a dotcom site I authorized FB but then after clicking Post Comment I got

> ERROR: please fill the required fields (name, email).

**Comment by kraftbj** [comment] 2017-07-14 20:26
I suspect it may be related to Facebook v2.3 being deprecated earlier this week. Asking IO for a consult.

**Comment by timmyc** [comment] 2017-07-14 23:27
I have a fix for this but am unsure how to test.  Can someone provide details on how to reproduce the error?

**Comment by designsimply** [comment] 2017-07-15 01:57
> Can someone provide details on how to reproduce the error?

Steps to reproduce:

1. Log in to https://wordpress.com/
1. Go to any WordPress.com blog posts with comments enabled.
1. Add content to a comment.
1. Click the "Change" link below the comment and select Facebook.
1. If prompted, click "Continue" to allow WordPress access to Facebook.
1. Click the "Post Comment" button below the comment.

<strong>Result:</strong> the comment isn't posted and the following error appears:

> Error: Please fill the required fields (name, email).

![screen shot 2017-07-14 at fri jul 14 7 16 28 pm](https://user-images.githubusercontent.com/1119271/28235529-d140a2dc-68cc-11e7-9870-954c982c63af.png)

![screen shot 2017-07-14 at fri jul 14 7 16 39 pm](https://user-images.githubusercontent.com/1119271/28235531-d55739bc-68cc-11e7-9001-d2af2713923b.png)

![screen shot 2017-07-14 at fri jul 14 7 16 49 pm](https://user-images.githubusercontent.com/1119271/28235534-d9f3edf8-68cc-11e7-87d2-b6ead0910db6.png)

Also see https://en.support.wordpress.com/facebook-and-twitter-comments/

**Comment by correliebre** [comment] 2017-07-16 20:14
Another report in 3325367-t. I also tried it out on a test site, and got the same message:
<img width="803" alt="screen shot 2017-07-16 at 10 07 29 pm" src="https://user-images.githubusercontent.com/25516017/28250956-23f11ad6-6a74-11e7-86e0-ff5d5288bbc7.png">

**Comment by timmyc** [comment] 2017-07-17 19:41
Should be fixed up in r159316-wpcom - but please re-open and ping me if any further issues are encountered.

**Comment by codestor4** [comment] 2017-07-17 20:38
3327352-t 
@timmyc this ticket looks similar to this issue. The user mentions the following points:

> The comment widget on my articles doesn't post comment if I'm logged in as a
> Facebook user. However it does post well if I'm connected via Google+, Twitter,
> Wordpress, or not connected at all.
> The comment form disappear, and the loader gif keep spinning endlessly

While you reply, I'm going to simply ask them to reinstall and see if that works for them :)

**Comment by timmyc** [comment] 2017-07-17 22:05
@codestor4 I just ran a test on one of my JP sites and was able to post a comment using a Facebook account.  Based upon the timestamp of the ticket, the user likely had the problem prior to the fix being deployed.  Could you see if they are able to verify the issue is no longer present?  Uninstalling Jetpack shouldn't be necessary for the fix to work.

**Comment by danjjohnson** [comment] 2017-07-18 09:48
The issue is fixed for wp.com sites, but now when testing again on a Jetpack site, I'm unable to authenticate with FB. I just get this loading image indefinitely:

![image](https://user-images.githubusercontent.com/1990037/28311119-8d115b2e-6ba6-11e7-8620-7d8f573bfcb4.png)

Can anyone else test & confirm/deny?

**Comment by codestor4** [comment] 2017-07-18 10:27
@danjjohnson I was able to comment on my test JP site using facebook comment - https://omkarbhagat1.mystagingwebsite.com/2017/07/test-2/#comment-6

**Comment by danjjohnson** [comment] 2017-07-18 10:50
Hmm ok. Seems like it's just me still having trouble. I'll ask the user to test.

**Comment by timmyc** [comment] 2017-07-18 17:16
@danjjohnson curious are there any errors shown in the console during that operation?  I tested on a JP site and had no issues.

**Comment by danjjohnson** [comment] 2017-07-19 13:40
@timmyc only this 404:
https://github.com/Automattic/jetpack/issues/7435

Not sure if that would affect it?

**Comment by timmyc** [comment] 2017-07-19 15:46
yeah that would not be related at all.  @danjjohnson perhaps try purging cookies or using an incognito tab to test with a fresh state?

**Comment by danjjohnson** [comment] 2017-07-19 16:08
Ok I got it to work in incognito. Not sure what was going on there.

**Comment by timmyc** [comment] 2017-07-19 16:20
The process leans heavily on data being persisted in cookies, so guessing maybe when you first had issues with the bug, some bad data was cached in a cookie.  I'm going to close this back out now.

**Closed by timmyc** 2017-07-19 16:20 UTC
Labels: Comments, [Team]  I/O, [Type] Bug

**Comment by danjjohnson** [comment] 2017-07-19 17:52
User also confirmed it is fixed for him. Thanks!
