### ISSUE TITLE
Likes: Notifications go to blow owner, not post author

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/jetpack#1622] opened 2015-02-12 00:38 UTC
When liking a post, only the blog owner currently gets notified of the Like, not the post author, even if the post author has linked their WordPress.com account.

Tested this twice on my test site and each time the blog owner gets a notification but not the post author.

I think if the Author has linked their account with WordPress.com, the notification should go there.

**Comment by dereksmart** [comment] 2015-02-12 01:07
Duplicate of #620

**Closed by dereksmart** 2015-02-12 01:07 UTC
Labels: bug, Likes
