### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by robertdall** [Automattic/jetpack#1496] opened 2015-01-13 18:49 UTC
I keep getting a script error on every single admin page. See Screenshot of WP Debug. 
![screen shot of WP Debug](https://cloud.githubusercontent.com/assets/1909677/5726561/24e4bc02-9b11-11e4-81f0-3e521cf3ec2d.png)

Biggest question why is being called on every single admin page? Even Admin pages that has absolutely no need or connection to Jetpack what so ever?

**Comment by jeherve** [comment] 2015-01-13 18:53
That file is used to serve the Retina version of an image when available. It runs in the dashboard as well since there might be images needing an upscale in the admin as well.

That error is new to me, though. Could you try to deactivate all other plugins, one at a time, and let me know if you find a conflict with another plugin?

**Comment by georgestephanis** [comment] 2015-01-13 18:57
It was initially added explicitly to the admin by this commit --

https://github.com/Automattic/jetpack/commit/9baad8eee36b64bdb90ded9d05b061c5ba7beae5

by @beaulebens -- whereas it was previously just being enqueued by the constructor from @skeltoac's initial addition here:

https://github.com/Automattic/jetpack/commit/6aac543758c91a29cc4b4447240193b4d83b0987

I'm honestly wondering if the admin inclusion was just an oversight.  Doing some digging now.

**Comment by robertdall** [comment] 2015-01-13 19:02
> That file is used to serve the Retina version of an image when available. 

Just wondering why we need to serve a retina image on any page other then jetpack admin page.

Thanks for looking into this.

**Comment by skeltoac** [comment] 2015-01-13 19:08
Gravatars.

**Comment by beaulebens** [comment] 2015-01-13 19:13
Yeah, it was explicitly added to the admin to handle Gravatars; it could probably be more explicitly enqueued in places where they appear (posts, comments, dashboard...?)

**Comment by georgestephanis** [comment] 2015-01-13 19:17
I'd almost want to run it off of some action in Core's `get_avatar()` call so it's only used on pages that have a gravatar.

... but then I realized that every page has the logged in user's gravatar in the user menu in the adminbar.  I guess if want them all realized, we do need it everywhere -- at least until srcset support rolls in.

**Comment by robertdall** [comment] 2015-01-13 20:33
Do I still need to provide **reporter feedback** then?

**Comment by georgestephanis** [comment] 2015-01-13 20:58
Possible fix to let gravatars handle themselves for retinification in core -- https://core.trac.wordpress.org/ticket/31004

**Comment by georgestephanis** [comment] 2015-01-13 20:59
@robertdall And -- Jeremy had asked for more debug information to attempt to duplicate the glitch.  That was the requested feedback.

**Comment by robertdall** [comment] 2015-01-14 19:32
Okay Here is how to replicate the error: 

1. Have Jetpack installed on single site or multisite it doesn't matter.
2. Install Gravity Forms
3. Connect Jetpack to WordPress.com the error does not occur in my testing if you do not connect. 
4. Go to any Gravity Forms settings / set up page in the admin.  
5. Get Script error.

**Comment by jeherve** [comment] 2015-01-15 09:11
Thanks for the details! I'll see if I can reproduce and update you on what I find!

**Comment by jeherve** [comment] 2015-01-15 17:29
I could reproduce.

A quick search also revealed this forum thread where someone else experienced the same issue:
https://wordpress.org/support/topic/javascript-error-47?replies=2

`Uncaught TypeError: Cannot read property 'style' of null`
On line 7:
`else if(typeof document.body.style.webkitMarquee==='string'){func=webkit;}`

It seems that when Gravity Forms is active, devicepx-jetpack.js is loaded in the `head` instead of the bottom of the body. Since it's loaded before the `body`, it triggers an error.

devicepx is added to the footer of the dashboard via `admin_enqueue_scripts` ([ref. 1](https://github.com/Automattic/jetpack/blob/3.3/class.jetpack.php#L456) [ref. 2](https://github.com/Automattic/jetpack/blob/3.3/class.jetpack.php#L626)). I don't see anything wrong in there.

When I comment out `wp_print_scripts();` on line 919 of gravityforms.php, it solves the issue but obviously creates some with Gravity Forms.

I'm not really familiar with Gravity Forms, though, so I couldn't find out more. I got in touch with one of the plugin developers to see if they can find out more.

**Comment by acancado** [comment] 2015-01-15 19:16
Hello. This is Alex from Gravity Forms. Thanks for the head up. 
We are looking into this issue and will let you know when we have something. The wp_print_scrits() does seem a bit odd, so we will see what we need to do to either get rid of it or make sure it doesn't interfere with other scripts.

**Comment by spivurno** [comment] 2015-01-15 19:46
Hi guys, Dave here from Gravity Forms. We removed the unnecessary call to wp_print_scripts(). This fix is available in Gravity Forms 1.8.20.18 ([download here](http://www.gravityhelp.com/downloads/)).

@jeherve You mentioned that you experienced some issues when you removed the wp_print_scripts() on your end. I didn't see any on my end. Could you drop me a line at david [at] rocketgenius [dot] com with details on those issues?

**Comment by jeherve** [comment] 2015-01-16 09:46
@spivurno I looked again today, and didn't see any issues.

Closing this ticket then, thank you all!

**Closed by jeherve** 2015-01-16 09:46 UTC
Labels: bug
