### ISSUE TITLE
Carousel: Closing a gallery scrolls the page up to the top

### ISSUE THREAD

**Issue by ChrisBegley** [Automattic/jetpack#3024] opened 2015-11-17 07:34 UTC
When you close a Carousel gallery it scrolls the page back up to the top, rather than keeping the scroll position where you opened the gallery. This just started happening with 3.8.0.

**Comment by jeherve** [comment] 2015-11-17 14:02
Closing as duplicate of #1125

**Closed by jeherve** 2015-11-17 14:02 UTC
