### ISSUE TITLE
Subscription Emails: Images from Elementor don't appear

### ISSUE THREAD

**Issue by xpurichan** [Automattic/jetpack#17682] opened 2020-11-01 19:27 UTC
#### Summary
When a post is made using the WordPress block editor we can add images via the image (or other) blocks and they will appear in the subscription notification emails sent to followers of the site.

If a new post is made using the Elementor editor and images are added then they won't appear in the subscription notification email.

#### Steps to reproduce the issue
1. Ensure you are following and set to receive email notifications to your test site.
2. Create a new blog post using the Elementor plugin, make sure to include at least one image in the body of the post, then publish it
3. Wait to receive the post notification email and note that the images are missing.

**Comment by jeherve** [comment] 2020-11-02 10:37
> make sure to include at least one image in the body of the post, then publish it

Would you happen to know the format of that image (if you look at the HTML version of the post in the editor, is that image inside a shortcode)? That may help us adding support for it.

Thank you!

**Comment by jeherve** [comment] 2020-11-03 09:46
>  format of that image

```
<div class="wp-block-image is-style-default">
<figure class="aligncenter is-resized">
[caption id="" align="aligncenter" width="640"]<img src="https://site.com/wp-content/uploads/2020/10/d95fbf9a81e6ebe8c093edf4d559c38c-2.jpg" alt="" width="640" height="360"> Scenic Porto, Portugal[/caption]</figure>
</div>
```

**Comment by jeherve** [comment] 2020-11-03 10:46
I can't seem to reproduce at the moment:

![image](https://user-images.githubusercontent.com/426388/97975725-d5f27200-1dc9-11eb-89f2-9103a9049a76.png)

Can you reproduce on your end? Does it happen with all posts on the site? What are the site's Reading Settings under Settings > Reading (is it set to show the full post in RSS feeds and subscription emails, or just an excerpt and thus no image)?

**Comment by msilbers** [comment] 2020-11-03 22:07
Their site is set to "

For each post in a feed, include: Full text

FWIW this is what I see as the HTML for the first image in the post:


```
<div class="elementor-element elementor-element-83d3d63 elementor-widget elementor-widget-image" data-id="83d3d63" data-element_type="widget" data-widget_type="image.default">
<div class="elementor-widget-container">
<div class="elementor-image">
<figure class="wp-caption">
<img src="site.com/example image url" />											<figcaption class="widget-image-caption wp-caption-text">Sunset</figcaption>
 </figure>
</div>
</div>
 </div>
```

**Comment by jeherve** [comment] 2020-11-04 09:21
Yes, this matches what I see on my test site as well. Were you able to reproduce the issue on a test site of yours? Does this happen for all posts on their site, or just one?

**Comment by kristarella** [comment] 2020-11-06 22:52
I asked the user for a few more details.

The issue is that for posts created with Elementor, the post notification shows text until the first image, then shows an image placeholder, then the rest of the post is missing.

Screenshot from customer:

![Screen-Shot-2020-10-28-at-11 25 54-AM](https://user-images.githubusercontent.com/2031017/98421711-13af0d80-20de-11eb-8253-8fc2e2aff368.png)

1. This happens for all posts created with Elementor on their site, not for posts made with block editor
2. If they try to switch from Elementor to block editor in the same post the same thing happens in the editor itself

Screenshot from customer:

![Screen Shot 2020-10-28 at 11 35 24 AM](https://user-images.githubusercontent.com/2031017/98421950-a9e33380-20de-11eb-84d9-1ba914dd69e0.png)

Might be something deeper going on with the content?

I am yet to try it on a test site.

**Comment by arunsathiya** [comment] 2020-11-08 08:33
I was testing this situation with @ajaykj on p1604821308470100-slack-wpcom-support, but neither of us could get Elementor-based post emails on our Atomic sites. The same sites with Gutenberg-based posts do send out emails. As such, we are a bit lost on why Elementor-based posts are not going out, when the rest of the Happiness Engineers on this thread were able to do that fine. 🤔

**Comment by ajaykj** [comment] 2020-11-08 08:47
I could receive an email notification for a post created using Elementor after I activated the classic editor plugin. Maybe that's what was missing in our testing earlier, @arunsathiya

**Comment by kristarella** [comment] 2020-11-08 23:44
I have tested this and also couldn't get email from an Elementor post.

I had no problem converting a post from Elementor back to WordPress editor.

I just realised that the customer is using Elementor Pro, so maybe it is specific to that, or a conflict from another plugin. I've asked them to contact Elementor support. I'll close this ticket for now, I don't think the problem is specific to Jetpack.

**Closed by kristarella** 2020-11-08 23:44 UTC
Labels: Subscriptions, [Status] Needs Author Reply, [Type] Enhancement
