### ISSUE TITLE
Jetpack: Search widget - "wp-editor script should not be enqueued together with the new widgets editor"

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#26091] opened 2022-09-07 18:09 UTC
### Impacted plugin

Jetpack

### Steps to Reproduce

1. On a site with Jetpack (not Jetpack Search) connected and `WP_DEBUG` set to `true`
2. Visit `wp-admin/widgets.php`
3. Confirm you see a notice logged 
![image](https://user-images.githubusercontent.com/746152/188948700-48300b7b-c1c9-4f18-bbe5-75a0e46f2d09.png)

### What actually happened

A notice is shown/logged
```
Notice: Function wp_enqueue_script() was called incorrectly. "wp-editor" script should not be enqueued together
with the new widgets editor (wp-edit-widgets or wp-customize-widgets). Please see [Debugging in WordPress]
(https://wordpress.org/support/article/debugging-in-wordpress/) for more information. 
(This message was added in version 5.8.0.) in /srv/users/user19a660f3/apps/user19a660f3/public/wp-includes/functions.php on line 5831
```

Update

### Reproducibility

Consistent

### Severity

Most (> 50%)

**Comment by kangzj** [comment] 2022-09-08 02:05
The issue persists even when search widget is disabled, so it should be from other parts of Jetpack. Still looking...

**Comment by kangzj** [comment] 2022-09-08 02:35
`jetpack-blocks-editor` seems very suspicious because when I stopped it from loading, the notice is gone. However, it doesn't really have any deps?

https://github.com/Automattic/jetpack/blob/70361e56f8fdc79a6fb92b13ef5b7a12b51b78c0/projects/plugins/jetpack/class.jetpack-gutenberg.php#L656

**Comment by jeherve** [comment] 2022-12-09 11:35
Closing as duplicate of #20357

**Closed as completed by jeherve** 2022-12-09 11:35 UTC
Labels: Bug, [Closed] Duplicate, [Pri] High, [Feature] Search, [Plugin] Jetpack
