### ISSUE TITLE
Jetpack: Enhancing UX of plans page

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#8941] opened 2018-02-27 19:05 UTC
We've recently[ introduced Jetpack Plans grid into the "my plan" tab of the dashboard
](https://github.com/Automattic/jetpack/pull/8903)

I posted some quick wins to launch a v.1 of this edition, but also a bit more in terms of enhancing the overall NUX/UX of this page.

![jetpack-plans-before](https://user-images.githubusercontent.com/214813/36699162-e40dc4e4-1b19-11e8-8f0f-6efcb1b0ce98.png)

The plans page within the plugin is rather lengthy and I think there's some things we can do to really make it more concise and provide some better UX. 

I whipped up this sketch to explore a better UX for our "my plan" page within the dash, that isn't quite so long as what we currently have:

![jetpack-plans-sketch](https://user-images.githubusercontent.com/214813/36700124-c9c41fae-1b1c-11e8-968d-f1d9a507a635.jpg)

**1) My plan**

The my plan block would quickly display which plan the user currently has (free as well), and offer a "manage plan" button

**2) Checklist**

As part of ongoing NUX work by @joanrho we're building out a Jetpack checklist to better help folks understand the value of Jetpack—more specifically the tools included with their plan. I think as a start, we should offer a small text block here that says something like:

"Jetpack offers a lot of tools. View your personalized checklist to make sure you're getting the more out of it!" [View Checklist]  (verbiage TBD cc @nicoleckohler )

**3) Plans columns**

Here the plans columns will come into play with the changes listed above. But let's remove the 3 different "see all features" buttons. They're redundant and add clutter

<img width="796" alt="screen shot 2018-02-26 at 5 49 15 pm" src="https://user-images.githubusercontent.com/214813/36700551-0fd5e044-1b1e-11e8-8a12-06a39aa7759d.png">

**4) A single "see all features block"**

Let's add another quick block here where we take the 3 buttons and make them into one button that take the user to view the full feature comparison chart (https://jetpack.com/features/comparison/) so they can quickly see everything jetpack has to offer.  verbiage TBD

**Comment by joanrho** [comment] 2018-03-01 17:23
Here's an updated mockup of Jeff's sketches that incorporates my designs from the NUX Plans grid view and our future My Plan Checklist view. Yay for consistency!

![wp-admin plans](https://user-images.githubusercontent.com/204742/36859004-5df2639c-1d3a-11e8-830e-83cfcebb25ee.png)

**Comment by withinboredom** [comment] 2018-03-05 17:32
@joanrho Just to be clear, we're adding back in the slashed prices?

**Comment by joanrho** [comment] 2018-03-06 18:43
@withinboredom let's go with what @jeffgolenski has designed for that section (no prices), but can we add back in the top CTA buttons for all plans, even if it just says "Learn more" or "Manage Plan"? It helps to balance the layout and fill in the empty spaces (looking at that page on a Pro plan testing 5.9).

**Comment by jeherve** [comment] 2020-09-24 17:30
Closing this for now since the "My Plans" page now redirects to WordPress.com.

**Closed by jeherve** 2020-09-24 17:30 UTC
Labels: Admin Page, FixTheFlows, NUX, Plans, [Pri] Normal, [Type] Enhancement
