### ISSUE TITLE
Email-only subscribers unable to subscribe to WordPress.com sites

### ISSUE THREAD

**Issue by mgozdis** [Automattic/jetpack#34922] opened 2024-01-09 18:57 UTC
### Impacted plugin

Jetpack

### Quick summary

When trying to subscribe to a WordPress.com site as an "email-only" subscriber, you are redirected to a "Manage your subscription" page where you are asked to submit your email address again. Submitting the form and clicking the link in this email sends you to manage your subscriptions at the following link and never subscribes you to the site: https://wordpress.com/subscriptions/sites

Additionally, when viewing your subscriptions at the link provided in the email, you are not actually logged in and can still manage subscriptions. Clicking the login link in top right requires you to login to the account and submitting the email address states "User does not exist. Would you like to create a new account?" 

Appears related to changes mentioned in p7DVsv-jxi-p2

### Steps to reproduce

1. Add Subscribe block to a page and publish
2. View the published page from a PC/device that is not logged into a WordPress.com account and submit an email-only address not tied to a WordPress.com account
3. See that no confirmation of subscription is presented and that you are presented with another form like this: ![ETxrmf.png](https://github.com/Automattic/jetpack/assets/121042930/61c0b825-6f72-4d49-b79f-0177c378cd37)
4. When submitting your email again for the link to manage your subscriptions and clicking the link in the email, see that you are still not subscribed to the site, nor actually logged in: ![pWsVzt.png](https://github.com/Automattic/jetpack/assets/121042930/7e91d23d-799e-44dd-aead-07fc2b522aad)

### A clear and concise description of what you expected to happen.

Email-only subscribers should be subscribed to the site.

### What actually happened

Site is never subscribed to. 

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

This was tested on AT and self-hosted sites only. It was only reproducible on WordPress.com sites and appears to work fine on a self-hosted site.

**Comment by jeherve** [comment] 2024-01-10 14:04
@Automattic/apex @Automattic/zap Could you take a look at this? That seems like something we should fix quickly.

On my end I was not able to reproduce that exact subscription flow on a self-hosted site. Upon clicking on the link to confirm my subscription in the email I had received, I spent a few seconds on a blank log-in page in Calypso, then was redirected to the Subscribe page on the site, but saw no confirmation of subscription. I only got to know I was subscribed because I got an email about it, and then checked and confirmed that a WordPress.com account was created for me.

**Comment by mgozdis** [comment] 2024-01-10 18:51
Adding this interaction for reference: 7559786-zd-a8c
They've added a Form block as a workaround to manually add subscribers after submissions.

**Comment by JuanLucha** [comment] 2024-01-22 12:32
After being unable to reproduce, we contacted the user again for more info (thanks @mgozdis ). Seems like it's working on their site now. I suspect they were using a user already subscribed to test the subscribe block, which gives the described scenario.
Closing the issue.

**Closed as completed by JuanLucha** 2024-01-22 12:32 UTC
Labels: Bug, [Feature] Subscriptions, [Pri] BLOCKER, Customer Report [LEGACY], Earn, [Plugin] Jetpack, Triaged, [Platform] Simple, [Platform] Atomic, [Status] Priority Review Triggered
