### ISSUE TITLE
[Publicize] Posting without excerpt

### ISSUE THREAD

**Issue by joendotcom** [Automattic/jetpack#8545] opened 2018-01-17 12:52 UTC
Users are asking for a way to post to social media without including an excerpt. This issue is to track those requests.

Currently it's possible to override the excerpt using a Custom Message [(screenshot)](https://jetpackme.files.wordpress.com/2013/11/publish-meta-publicize-expanded-38-2.png?w=300&h=216), but users are asking for a way to remove the excerpt entirely and just post the link (perhaps with title).

**Comment by jeherve** [comment] 2018-01-17 19:41
Closing as duplicate of #261; this larger issue, once solved, would allow one to decide exactly what gets posted, and what does not.

**Closed by jeherve** 2018-01-17 19:41 UTC
Labels: Publicize, [Type] Enhancement
