### ISSUE TITLE
CPT: WSOD incompatibility with "Front-end Editor" plugin

### ISSUE THREAD

**Issue by aduth** [Automattic/jetpack#4710] opened 2016-08-09 23:46 UTC
#### Steps to reproduce the issue
1. Install [`wp-front-end-editor`](https://wordpress.org/plugins/wp-front-end-editor/) plugin (an ["inactive" feature plugin](https://make.wordpress.org/core/features-as-plugins/))
2. Activate the Jetpack Custom Content Types module
3. Navigate to the home page of your site
#### What I expected

To see the home page of my site.
#### What happened instead

WSOD
#### Error Log

> 2016/08/09 19:36:44 [error] 19108#0: *750423 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined function get_current_screen() in --REDACTED--/wp-content/plugins/jetpack/modules/custom-post-types/testimonial.php on line 366" while reading response header from upstream, client: --REDACTED--, server: --REDACTED--, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "--REDACTED--", referrer: "--REDACTED--"
#### Suspected Cause

The [`Jetpack_Testimonial#change_default_title` function](https://github.com/Automattic/jetpack/blob/228818acf252165c732cfecce643036958b22bc0/modules/custom-post-types/testimonial.php#L362-L372) triggered by the `enter_title_here` filter is [invoked by the front-end editor plugin](https://github.com/iseulde/wp-front-end-editor/blob/02ef14de695481a0f376ee16ba2e0ce62db85031/class-fee.php#L176). I suspect `get_current_screen` is not a function which can be called on the front-end? Though I'm a bit surprised it fatals.

**Comment by oskosk** [comment] 2018-02-14 19:22
Closing as can't reproduce the WSOD. Also the `wp-front-end-editor` plugin kept asking for the [WP REST API plugin](https://wordpress.org/plugins/rest-api/).

**Closed by oskosk** 2018-02-14 19:22 UTC
Labels: Custom Content Types, [Pri] Normal, [Type] Bug
