### ISSUE TITLE
WSOD when a non-admin author tries to disconnect a user connection

### ISSUE THREAD

**Issue by manzoorwanijk** [Automattic/jetpack#36969] opened 2024-04-18 09:09 UTC
### Impacted plugin

Jetpack

### Quick summary

When a non-admin author tries to disconnect their WPCOM account in My Jetpack, there is White Screen of Death and a 403 error in the network request.

```json
{
	"code": "invalid_user_permission_jetpack_disconnect",
	"message": "You do not have the correct user permissions to perform this action.\n\t\t\tPlease contact your site admin if you think this is a mistake.",
	"data": {
		"status": 403
	}
}

```

### Steps to reproduce

1. Add a WPCOM connection to a site using an admin account
2. Create a non-admin author account
4. Login as the new author account
5. Goto My Jetpack and add a user connection for the author account
6. Now click on Manage for the user connection
7. Try to disconnect

### A clear and concise description of what you expected to happen.

The connection should be removed and the UI should not crash

### What actually happened

There is a 403 error for the network request and WSOD

```log
Warning: Failed prop type: Invalid prop `disconnectError` of type `object` supplied to `StepDisconnect`, expected `boolean`.
StepDisconnect@http://my-site.com/wp-content/plugins/social/jetpack_vendor/automattic/jetpack-my-jetpack/build/index.js?minify=false&ver=d8ce31cc41cdde19710e:18146:7
DisconnectDialog@http://my-site.com/wp-content/plugins/social/jetpack_vendor/automattic/jetpack-my-jetpack/build/index.js?minify=false&ver=d8ce31cc41cdde19710e:17693:96
ManageConnectionDialog@http://my-site.com/wp-content/plugins/social/jetpack_vendor/automattic/jetpack-my-jetpack/build/index.js?minify=false&ver=d8ce31cc41cdde19710e:18696:7
div
ConnectionStatusCard@http://my-site.com/wp-content/plugins/social/jetpack_vendor/automattic/jetpack-my-jetpack/build/index.js?minify=false&ver=d8ce31cc41cdde19710e:21325:7
ConnectionsSection@http://my-site.com/wp-content/plugins/social/jetpack_vendor/automattic/jetpack-my-jetpack/build/index.js?minify=false&ver=d8ce31cc41cdde19710e:21533:83
div
Col@http://my-site.com/wp-content/plugins/social/jetpack_vendor/automattic/jetpack-my-jetpack/build/index.js?minify=false&ver=d8ce31cc41cdde19710e:15716:7
div
Container@http://my-site.com/wp-content/plugins/social/jetpack_vendor/automattic/jetpack-my-jetpack/build/index.js?minify=false&ver=d8ce31cc41cdde19710e:15776:19
div
AdminSection@http://my-site.com/wp-content/plugins/social/jetpack_vendor/automattic/jetpack-my-jetpack/build/index.js?minify=false&ver=d8ce31cc41cdde19710e:14322:22
div
```

### Impact

One

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by jeherve** [comment] 2024-04-18 09:17
Closing as duplicate of #34535.

**Closed as completed by jeherve** 2024-04-18 09:17 UTC
Labels: Bug, [Closed] Duplicate, [Pri] High, [Plugin] Jetpack, Needs triage, [Status] Priority Review Triggered
