### ISSUE TITLE
SEO Tool link needs to be finished

### ISSUE THREAD

**Issue by samhotchkiss** [Automattic/jetpack#5691] opened 2016-11-17 02:44 UTC
![image](https://cloud.githubusercontent.com/assets/574752/20374315/0695d254-ac35-11e6-9809-1bba31cc5e53.png)

cc: @richardmuscat

**Comment by jeherve** [comment] 2016-11-17 09:19
Closing as duplicate of #5668

**Closed by jeherve** 2016-11-17 09:19 UTC
Labels: SEO Tools, [Pri] BLOCKER
