### ISSUE TITLE
Post count discrepancy for a Business WordPress.com site

### ISSUE THREAD

**Issue by davoraltman** [Automattic/jetpack#7848] opened 2017-09-25 09:06 UTC
The number of posts in /wp-admin and in wordpress.com/posts is not the same.

Ticket: 697875-zen
Site: 122212242

Previously posted in 1033-gh-jpop-issues

**Comment by designsimply** [comment] 2017-11-17 18:50
Tested and confirmed using the following steps:

1. Go to https://wordpress.com/ and select a Jetpack Site.
1. Note the number of drafts.
1. Click the Add button next to Blog Posts.
1. Add a title and some body text and save changes.
1. Click the back arrow at top left.
1. Check the count next to Drafts to see if the number incremented by one.

<strong>Result:</strong> the count does not update after adding a new draft.

<strong>Video:</strong> [2m17s](https://cloudup.com/cMHoUUamCGq)
<sup>Tested with WPDesktop 3.1.0-beta2 and WordPress.com Business Plan with plugins enabled and WordPress.com for a Jetpack site only hosted at WP Engine running WP 5.0-alpha-42199 and Jetpack 5.6-beta-16346-b0f1aa8-master and PHP 5.6.31-4.</sup>

![screen shot 2017-11-17 at fri nov 17 11 48 25 am](https://user-images.githubusercontent.com/1119271/32963489-5ebe9920-cb8d-11e7-84ab-881f3131d72b.png)
<sup>Seen at https://wordpress.com/posts/drafts/alittletestblog.com using Firefox 57.0 on Mac OS X 10.12.6.</sup>

**Comment by brezocordero** [comment] 2019-01-08 19:02
Another case here:
Ticket: 1676124-zen
Site: 144976815

**Comment by iamgabrielma** [comment] 2019-01-09 07:30
Also possibly related to this issue here: https://github.com/Automattic/jpop-issues/issues/2987

This happens when the shadow site has the incorrect values and we have seen this happening very often when rewinding a site, as there's a value miss match for the post count. We try to Jetpack sync first but most of times this does not solve the problem.

**Comment by iamgabrielma** [comment] 2019-01-09 07:38
Also p9F6qB-1LM-p2

**Comment by donpark** [comment] 2019-03-11 20:12
Calypso fetches post counts from WPCOM via `https://public-api.wordpress.com/wpcom/v2/sites/$site_id/post-counts/post` endpoint which is handled by `WPCOM_JSON_API_GET_Post_Counts_V1_1_Endpoint` class which queries Jetpack shadow tables, meaning it relies on Jetpack Sync to display the latest stats.

Calypso also seems to update the count itself directly after certain user actions like delete. This is why, after a post is deleted, post counts are immediately updated. Updated post count is not fetched in this case. When user action involves more complex flows, like creating a new draft post, direct update cannot be made so Calypso updates by fetching from WPCOM.

Most of the time, current mechanism displays correct  value. But Jetpack Sync does not seem to cover all possible flows. `wp post delete 123` CLI command, for example, does trigger Jetpack Sync and Calypso displays the correct stats after a second or two. But when posts are changed using uncommon commands like `wp site empty`,  Jetpack Sync gets confused and shadow tables get out of sync with remote site tables.

Long term fix is to find and address events we overlooked if possible or improve how Jetpack detects changes. Short term fix is to call the remote server instead of relying on shadow tables, if not every time then at least regularly. I'll need to discuss with Calypso and Jetpack teams to see best way to resolve this issue.

**Comment by donpark** [comment] 2019-03-12 20:52
Turns out short term fix will requires more work than initially thought because remote site does not have equivalent endpoint for `post-counts`. Even if a remote API is added and used to fetch latest post stats, underlying Jetpack Sync problems could still cause discrepancies.

**Comment by donpark** [comment] 2019-03-12 22:04
Given that:

1. post counts takes only a single query to build and
2. we're already pounding the remote site for each post on the Calypso posts page where
3. post counts are also displayed,

I think it'll be more performant to forego using the shadow tables, at least for this use-case, and query the remote site directly, adding new Jetpack API endpoints if they're missing.

Thoughts? @gwwar @jhnstn ^^

**Comment by gwwar** [comment] 2019-03-12 22:13
p1HpG7-4QY-p2 Yes, shadow site data is not reliable enough for API use.

**Comment by donpark** [comment] 2019-03-12 22:20
When the time is right, perhaps we should widen the discussion to re-assess the need for the shadow tables.

**Comment by donpark** [comment] 2019-03-12 23:10
Oh. If shadow tables survive the re-re-visit, we can play switchroo on them.
https://github.com/Automattic/jpop-issues/issues/2825#issuecomment-471736939

**Comment by donpark** [comment] 2019-03-13 21:43
D25544-code routes `post-counts` API call to remote Jetpack/Atomic site.

Calypso needs to be patched to use the v1.1 API instead of v2 API which only uses  shadow sites.

**Comment by donpark** [comment] 2019-03-15 15:53
D25544-code will be deferred in favor of broader fix recommended in p9o2xV-hM-p2.

**Comment by donpark** [comment] 2019-03-21 18:36
I think we need following  two features.

1. Remove expired (ghost?) posts
2. Reset shadow tables

First tool will compare posts on remote site against posts in shadow tables to find what shouldn't be there and _removes_ them. This is what I'm working on now.

Second tool will replace shadow tables with empty blog tables and trigger full sync.

**Comment by lezama** [comment] 2019-03-22 14:41
> Remove expired (ghost?) posts

Take a look at `wp-content/mu-plugins/jetpack/sync/class.jetpack-sync-validator.php` on wpcom!

> Reset shadow tables

There's an open issue for this https://github.com/Automattic/jpop-issues/issues/3338, I think @dereksmart team is already working on it

**Comment by donpark** [comment] 2019-03-28 18:44
Closing this issue as it's site specific and general solution for the underlying problem is being addressed in https://github.com/Automattic/jpop-issues/issues/3338

**Closed by donpark** 2019-03-28 18:44 UTC
Labels: WPCOM API, [Status] Needs Review, [Type] Bug
