### ISSUE TITLE
Tiled Gallery Block causes pointer cursor on every block that has nesting

### ISSUE THREAD

**Issue by jasmussen** [Automattic/jetpack#13428] opened 2019-09-04 18:15 UTC
#### Steps to reproduce the issue

1. Go to block editor
2. Insert a Tiled Gallery block and add some images
3. Insert any block that features nesting. E.g. Group, Columns, Media & Text.
4. Preview the page and observe that every nesting block has a `pointer` cursor

**Probably cause**

The gallery appears to change the container divs of every block containing child blocks, not just the tiled gallery itself, and adds `data-carousel-extra` with a few image properties. This on its own seems a bit overreachy, but the actual cursor happens because this CSS is output by Jetpack:

```
[data-carousel-extra] { cursor: pointer }
```

**Expected behavior**

Tiled Gallery should probably just affect itself.

**Comment by donalirl** [comment] 2019-10-24 01:41
Seen in #16173198-hc

**Comment by darnelldibbles** [comment] 2019-12-05 19:53
Seen in https://wordpress.org/support/topic/carousel-and-pointer-cursor-over-text-problem/#post-12209854

**Comment by lezama** [comment] 2019-12-10 19:16
Seen in zd-2548654

**Comment by khristiansnyder** [comment] 2020-03-04 22:28
Seen in #18730714-hc
A Tiled Gallery was within a column. Converting to Masonry Gallery fixed the issue.

**Comment by chaitanyamsv** [comment] 2020-03-16 18:22
Just had this report in 19440801-hc

**Comment by tanjoymor** [comment] 2020-03-19 00:09
Another case here: #18635664-hc
Converting to Masonry Gallery fixed the issue.

**Comment by otpidusprime** [comment] 2020-03-26 18:58
Another report seen in 2820101-zen _(during a 1:1 Support session)_
I did not find the Masonry Gallery option there, but switching to a Slideshow fixes it.

**Comment by ebinnion** [comment] 2020-03-31 01:26
I was just about to create a new issue and Github pointed me here. Here are some steps that I used to reproduce the issue.

1. Create a new Jetpack site
2. Enable carousel
3. Create a post that has columns, with content in each column
4. Add a cover block with a background image and some nested text
4. Add tiled gallery block, with or without media
5. Publish page
6. View page and observe that pointer cursor shows when hovering over column content

The root issue here seems to be that we're adding `data-carousel-extra` in a lot of places and`data-carousel-extra` is what has the `cursor: pointer;` rule. Perhaps we should figure out how to not add `data-carousel-extra` in so many places.

Here's a screenshot of how I set up my test post:

![Screen Shot 2020-03-30 at 8 24 35 PM](https://user-images.githubusercontent.com/1126811/77977152-847a8580-72c4-11ea-881a-ab11f859c46d.png)

**Comment by ebinnion** [comment] 2020-03-31 01:42
Perhaps an easy win here would be to change the selector to something like `.tiled-gallery__item` that way we're specifically only applying the cursor to a Tiled Gallery item?

It seems like the latest patch above has been stalled for a bit.

**Comment by sourourn** [comment] 2020-04-28 14:51
Another case reported here: #20603495-hc

**Comment by jordesign** [comment] 2020-06-29 02:45
FWIW - I was able to use this CSS to work around the issue in the time being:

```
div.wp-block-columns, 
div.wp-block-column {
    cursor:default
}
```

**Comment by fresatomica** [comment] 2020-07-07 13:12
Another report: https://wordpress.com/forums/topic/cover-block-hover-issue/

**Comment by aleone89** [comment] 2020-07-15 14:41
Another report: hc-22637348 

I had to apply the css above, to pretty much every block on the page to help for the time being.

**Comment by jasmussen** [comment] 2020-08-08 08:39
Could a bandaid fix be to simply remove the cursor CSS, or attach it to a class? That would fix the visual issue until the underlying issue can be addressed.

**Comment by benchilcote** [comment] 2021-02-24 18:58
Another case surfaced in #27985992-hc

Gave this CSS as temporary workaround: [data-carousel-extra] {cursor: default !important;}

After I had a chance to check, it indeed was a gallery block that was present on the page. Changing to a masonry block fixed the issue.

Follow up:  #3770531-zd

**Comment by ivan-ottinger** [comment] 2021-04-27 07:23
Another report: 3939250-zd-woothemes

Applying @benchilcote's CSS workaround helped. Thanks!

**Comment by davrox123** [comment] 2021-05-17 23:24
Another report: zd 3987866

Applying @benchilcote's CSS workaround helped. Thanks!

**Comment by happychait** [comment] 2021-06-02 04:24
4035130-zen

Can be worked around by the regular Gallery block to one of the other galleries that's not a Tiled Gallery block.

**Comment by daria2303** [comment] 2021-06-25 07:59
4092207-zd-woothemes

applied CSS

**Comment by samiff** [comment] 2021-06-29 22:10
This is still an issue with JP 9.9-beta and either the Gallery or Tiled Gallery block.

**Related**: https://github.com/Automattic/jetpack/issues/7771

**Comment by kbrown9** [comment] 2021-08-31 16:19
I fixed the cursor problem in PR #20882 by making the CSS selector more specific. However, we're still adding `data-carousel-extra` to many elements that shouldn't have it. I'm leaving this issue open so we can continue investigating better gallery parsing.

**Comment by jeherve** [comment] 2021-08-31 17:58
@kbrown9 Thanks for taking a look at this! ❤️ Do you think we could close this one now, and keep #13531 open for more improvements down the line?

**Comment by kbrown9** [comment] 2021-08-31 20:51
> @kbrown9 Thanks for taking a look at this! ❤️ Do you think we could close this one now, and keep #13531 open for more improvements down the line?

I think that makes sense! That issue should cover the future improvements, so I'm closing this one.

**Closed by kbrown9** 2021-08-31 20:51 UTC
Labels: [Type] Bug, Carousel, [Status] In Progress, [Pri] Normal, Gutenberg, [Type] Happiness Request, [Block] Tiled Gallery
