### ISSUE TITLE
Admin Page Stats: Black bar echos on quick mouse movements

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#5191] opened 2016-09-22 20:13 UTC
#### Steps to reproduce the issue
On both Firefox 49 (stable) and 50 (dev/aurora channel), moving the cursor quickly over the stats chart results in some echos of what looks like the tool tip.

https://cloudup.com/c0TV8nQwDGF

Reported 2835684-t

**Comment by jeherve** [comment] 2016-09-26 09:28
Closing as duplicate of #4541

**Closed by jeherve** 2016-09-26 09:28 UTC
Labels: Admin Page, [Type] Bug
