### ISSUE TITLE
SEO tools not making it clear that user needs to upgrade

### ISSUE THREAD

**Issue by samhotchkiss** [Automattic/jetpack#5687] opened 2016-11-16 23:34 UTC
On a site with Premium (but not professional) activated, I get this:
![image](https://cloud.githubusercontent.com/assets/574752/20370174/807564f6-ac1a-11e6-9c42-c24c0c8587cf.png)

However, I shouldn't have SEO Tools yet because it requires professional

**Comment by vindl** [comment] 2016-11-17 05:57
This looks like a duplicate of https://github.com/Automattic/jetpack/issues/5652? The Upgrade button was present in original SEO Tools PR, but now it's no longer there regardless of site's plan (Free or Premium).

**Closed** 2016-11-17 09:19 UTC
Labels: [Pri] BLOCKER
