### ISSUE TITLE
Support contact form redirecting to jetpack.me/contact-support

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#769] opened 2014-06-24 21:00 UTC
Support contact form redirects the user to http://jetpack.me/contact-support/
with a message https://cloudup.com/chhwDlKVfLf.
It would be best to stay inside their own dashboard with a confirmation message that the email has been sent.

**Comment by jeherve** [comment] 2016-02-16 16:24
Closing this, as duplicate of #1315

**Closed by jeherve** 2016-02-16 16:24 UTC
Labels: General, [Type] Enhancement
