### ISSUE TITLE
Update stand-alone plugin onboard dialogues w/a link to add a license key

### ISSUE THREAD

**Issue by ilonagl** [Automattic/jetpack#27671] opened 2022-11-30 10:26 UTC
![Search pricing table](https://user-images.githubusercontent.com/100145243/204771771-7d0b8282-0631-44ed-8b9f-af3d5fdc62bf.png)

Task:

- Add a link: "Already have an existing plan or license key? Click here to get started" at the top of right corner in the VideoPress pricing table.

Flow after pressing the link:
<img width="15115" alt="Proposed flow-8" src="https://user-images.githubusercontent.com/100145243/204771827-2b4f5b3c-5fba-4265-8f96-1cedf57a2c54.png">

**Comment by jeherve** [comment] 2022-12-07 07:59
Closing as duplicate of #27668.

**Closed as completed by jeherve** 2022-12-07 07:59 UTC
Labels: [Closed] Duplicate, [Plugin] VideoPress
