### ISSUE TITLE
VideoPress: some data is not available in the media endpoint response

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#27068] opened 2022-10-25 21:13 UTC
Some video posts don't have defined properties, triggering a PHP warning:

![Image](https://user-images.githubusercontent.com/77539/197883739-54a90f47-4880-4bec-85cf-cb2ce0836825.png)

We should have to at least, check their existence and research what's happening with them.

**Comment by retrofox** [comment] 2022-10-25 21:24
p1666730829433759-slack-C03TA48NSUX

**Comment by lhkowalski** [comment] 2022-10-31 17:44
I will start taking a look at this.

We may have missing properties on the some VideoPress video metadata due to when the given fields got added, so this is a matter of:

- identifying the source for the data (so we can confirm they are new properties that may be breaking older videos)
- setting defaults to the values to overcome the warnings
- alternatively, migrate missing data (similar to the plan for #26822)

**Comment by lhkowalski** [comment] 2022-10-31 20:52
The three missing properties showed on the image and the lines of code mentioned on the error are related to listing local videos. The data is coming from the core `media` endpoint, and this endpoint serves the data from the `_wp_attachment_metadata` meta field. My hypothesis is that they are missing on the metadata for some reason, probably because the file itself lacks the info or the code could not extract this info when the file got uploaded.

The first step here is to make sure we check if the properties exists before using them, and then build upon it.

**Comment by lhkowalski** [comment] 2022-11-03 22:09
It's very hard to duplicate the problem, because uploading the problematic file to a JN site will not work:

![image](https://user-images.githubusercontent.com/6760046/199843775-d743b0fe-54fd-4e25-8449-e847b286dc98.png)

But it works on my local setup, and I can confirm that the source of the missing properties is a problem with the file itself. I uploaded it to the admin panel and checked the metadata for it, and it misses a lot of properties.

**Comment by lhkowalski** [comment] 2022-11-07 20:46
I will close this as something that was related to problems on the uploaded file. We can reopen it if something similar pops again.

**Closed as completed by lhkowalski** 2022-11-07 20:46 UTC
Labels: [Package] VideoPress
