### ISSUE TITLE
Network Admin: Connection fails

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/jetpack#3771] opened 2016-05-06 18:14 UTC
When I log into a multi-site as a super admin, and I try to connect a sub-site via the network admin, the connection fails and I get an error message.

![screen shot 2016-05-06 at 2 11 41 pm](https://cloud.githubusercontent.com/assets/2694219/15082210/8b3224de-1394-11e6-99c5-5126fe3af85d.png)

To reproduce:
- Log into a multisite with Jetpack network activated, and the main site already connected
- Go to Jetpack's network admin page and try to connect a disconnected sub-site
- Receive error message

Props to @kovshenin for reporting

**Comment by kovshenin** [comment] 2016-05-06 18:15
Worth mentioning that the `WP_Error` behind the scene says: "Error Details: The Jetpack server encountered the following client error: Secret mismatch"

**Comment by roccotripaldi** [comment] 2016-05-06 18:18
Also worth noting, for technical support, you can advise folks to connect via the sub-site's main dashboard until this is patched.

**Comment by jeherve** [comment] 2016-05-06 18:32
Closing as duplicate of #3641

**Closed by jeherve** 2016-05-06 18:32 UTC
Labels: General, Multisite, [Status] In Next Release, [Type] Bug
