### ISSUE TITLE
Publicize: Custom message not saved when updating a scheduled post

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#1586] opened 2015-02-03 01:34 UTC
User reported that trying to save a custom Publicize message for a scheduled post does not save. See http://d.pr/v/18GoG for a screencast.

**Comment by marygalioto** [comment] 2015-03-02 15:16
Thank you, Chase. The problem was resolved within a day or so but reappeared yesterday, 3/1/15.

**Comment by matt-schroeder-datalytyx** [comment] 2015-03-06 10:01
We're having the same issue. We change the custom message, click Update. We click customize again to ensure that the change has saved, but it reverts back to the default message.

**Comment by marygalioto** [comment] 2015-03-15 14:27
I'm still following this thread but have not seen an update about the progress of working toward a solution. Matt and I can't be the only people with this problem.

**Comment by kraftbj** [comment] 2015-03-15 19:20
We have this currently marked to be worked on for 3.5, which is the version after the one that will be released (most likely) in the next few days.

It doesn't appear to be straightforward as I can't duplicate using the steps used in the screencast, so may need additional information/testing to determine what's actually happening.

**Comment by jkudish** [comment] 2015-05-02 03:28
#1836 sounds related

**Comment by chaselivingston** [comment] 2015-05-26 18:00
@matt-schroeder-datalytyx and @marygalioto: Can both of you confirm whether or not this is still an issue for you?

**Comment by marygalioto** [comment] 2015-05-26 20:06
It is still an issue for me.

**Comment by chaselivingston** [comment] 2015-05-26 20:29
@marygalioto Interesting, could you perhaps record a quick screencast showing the issue? Also, include what versions of WordPress and Jetpack you're using. I'm no longer able to recreate this after some recent updates on our end.

**Comment by kraftbj** [comment] 2015-06-11 17:37
Related: Report of selecting/unselecting social media networks not preserved for scheduled posts.

**Comment by marygalioto** [comment] 2015-06-11 17:39
The problem is identical to the video I shared before. I type in new text in the social media box, hit "save draft" and the text reverts back to the original.

**Comment by kraftbj** [comment] 2015-06-11 18:26
I couldn't duplicate this behavior either trying with scheduled posts, adding the message before saving a draft or after, or straight to the scheduled status.

**Comment by jeherve** [comment] 2017-03-13 12:27
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.

**Closed by jeherve** 2017-03-13 12:27 UTC
Labels: Bug, [Feature] Publicize, [Status] Needs Author Reply
