### ISSUE TITLE
Set up banner has janky image layout

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#8909] opened 2018-02-23 02:23 UTC
In our banner prompting people to set up Jetpack, the layout of the images is off when viewed on a wide screen:

![screen shot 2018-02-22 at 4 11 07 pm](https://user-images.githubusercontent.com/108942/36575044-d2bd6512-1805-11e8-8825-2cda10bb3da9.png)

**Comment by dereksmart** [comment] 2018-02-23 13:41
Duplicate of #8677

**Closed by dereksmart** 2018-02-23 13:41 UTC
Labels: FixTheFlows, General, [Type] Bug
