### ISSUE TITLE
Widget editor broken

### ISSUE THREAD

**Issue by BinaryMoon** [Automattic/jetpack#3716] opened 2016-04-22 15:04 UTC
Running wp 4.5 and jp 4.0.2 locally the widget editor is broken in the customizer.

I spotted this when I tried to edit some sidebars and the customizer only showed 1 sidebar when I had three registered (and they all displayed in the theme). I narrowed the problem down to 2 modules that generate javascript errors in the customizer when enabled.

The modules are 'extra sidebar widgets' and 'tiled galleries'

The errors are:

1) customizer-utils.js?ver=4.5:11 Uncaught ReferenceError: wp is not defined(anonymous function) @ customizer-utils.js?ver=4.5:11

2) tiled-gallery.js?ver=4.5:163 Uncaught TypeError: wp.customizerHasPartialWidgetRefresh is not a function

![screen shot 2016-04-22 at 16 01 46](https://cloud.githubusercontent.com/assets/1004130/14745535/aea7fc78-08a3-11e6-8005-ad367a870b8a.png)

**Comment by eliorivero** [comment] 2016-04-22 16:29
Hi, thanks for the report. Can you please check if the issue persists with the TwentySixteen theme? It's odd that `wp` is not defined since it's an essential part of Customizer. If I add
```js
console.log( typeof wp );
```
at the top of the `customizer-utils.js` file it shows that it's defined as an object which is correct.

**Comment by BinaryMoon** [comment] 2016-04-22 20:09
I've done a small amount of work with the customizer and so I know about the wp variable so I was surprised by the error as well.

I've tried with Twenty Sixteen and get the same error.

I've just tried deactivating all the plugins on my install and am still getting the same error.

I have also just deleted Jetpack entirely and reinstalled it but still the same.

Added the console.log you mentioned and it's displaying 'undefined'

Don't know if it's relevant but I'm using the dev version of Chrome so perhaps something there has broken it.

**Comment by eliorivero** [comment] 2016-04-23 00:09
Thanks for the feedback! I'm a bit in the dark since I can't reproduce it, can you please try this?
Edit `jetpack/modules/widgets.php` and replace
```php
wp_enqueue_script( 'jetpack-customizer-widget-utils', plugins_url( '/widgets/customizer-utils.js', __FILE__ ), array( 'jquery' ) );
```
with
```php
wp_enqueue_script( 'jetpack-customizer-widget-utils', plugins_url( '/widgets/customizer-utils.js', __FILE__ ), array( 'wp-util' ) );
```
this will make it load after `wp` is defined for sure in `wp-util.js`. The dependencies loaded by `wp-util` are always loaded by Customizer so this doesn't add any additional load, it just loads it after those.
Let me know how it goes.

**Comment by BinaryMoon** [comment] 2016-04-23 06:36
I replaced the code with the following and it seems to have fixed it. Thought I'd keep both dependencies since I assume jquery is still needed as well.

`wp_enqueue_script( 'jetpack-customizer-widget-utils', plugins_url( '/widgets/customizer-utils.js', __FILE__ ), array( 'jquery', 'wp-util' ) );`

**Comment by eliorivero** [comment] 2016-04-23 13:36
The `customize-selective-refresh` encompasses both (actually `wp-util` requires `jquery` as dependency) but great, good to know this solves it. We'll include this change in the next release. Thanks for the feedback!

**Comment by lukecarbis** [comment] 2016-05-24 06:54
I'm getting the same thing. Multisite. Looking forward to a fix. Let me know if I can help.

**Comment by jeherve** [comment] 2016-05-24 08:03
@lukecarbis This will be fixed in an upcoming Jetpack release. Until then, you can apply the patch in #3738 to fix this issue on your site.

**Closed by jeherve** 2016-05-24 08:03 UTC
Labels: Extra Sidebar Widgets, [Status] In Progress, [Type] Bug

**Comment by fanalecreative** [comment] 2016-06-02 17:58
Thank you for this fix - just as a heads up the fix that eliorivero posted still returned this: 

`Uncaught TypeError: wp.customizerHasPartialWidgetRefresh is not a function`

Whereas the fix that BinaryMoon posted removed the errors entirely. This is on a multisite installation with the twenty fifteen theme activated for testing.

**Comment by jeherve** [comment] 2016-06-02 18:15
@fanalecreative We ended up going with a different solution, mentioned in #3738. Could you try applying the changes listed there, and let us know if this fixes the issue for you?

Thanks!

**Comment by fanalecreative** [comment] 2016-06-02 18:24
@jeherve - Thanks for the reply - hadn't noticed the other commit - works great, thanks!

**Comment by SiobhyB** [comment] 2016-06-04 21:41
Noting for posterity: I was able to reproduce the `wp.customizerHasPartialWidgetRefresh` error when activating the Pique theme and then navigating to Appearance > Customize > Theme Options.

I tested both on localhost and a Pressable testing site across multiple browsers:

<img width="1440" alt="screen shot 2016-06-04 at 22 36 04" src="https://cloud.githubusercontent.com/assets/2998162/15802279/c98bd85c-2aa4-11e6-8b6c-6e935e3c14a7.png">

Disabling the Extra Sidebar Widgets module resolved the issue:

<img width="1421" alt="screen shot 2016-06-04 at 22 37 32" src="https://cloud.githubusercontent.com/assets/2998162/15802284/f5364a0a-2aa4-11e6-973c-f7bce8eee9b9.png">

I added @kathrynwp as an admin to the same Pressable site where I saw the error, and all of the Theme Options loaded correctly for her even with the Extra Sidebar Widgets module enabled. Two Theme Wranglers were also unable to reproduce. 3936-wpcom-themes for full details. I'm still not certain why only I was able to reproduce.

Looking forward to the fix! :)

**Comment by superskill** [comment] 2016-06-14 11:09
is there a fix for this, with Jetpack widgets enabled, each time I delete my browser's cache and go to the customizer I get those errors. Here is a screencast: https://vid.me/zHMJ

I've also removed all enqueued js files from my theme (to test if it was a problem on my end) and I still get those errors.

It only works if I disable those widgets.

I am using WP v4.5.2, Jetpack 4.0.3, `add_theme_support( 'customize-selective-refresh-widgets' )` Chrome Version 51.0.2704.84 m

Thank you!

**Comment by jeherve** [comment] 2016-06-14 11:15
@superskill The fix will be included in the next Jetpack release, but until then you can apply the patch available [here](https://github.com/Automattic/jetpack/pull/3738/files) to solve the issue on your end.

If you don't feel comfortable editing Jetpack plugin files yourself, you can join [our Beta program](https://jetpack.com/beta/). A new beta will be available later today, and will include the patch above, among other things.
