### ISSUE TITLE
Boost: if page setup error is dismissed and module is enabled, settings aren't visible

### ISSUE THREAD

**Issue by dilirity** [Automattic/jetpack#36116] opened 2024-03-01 11:50 UTC
This happened on Jurassic Ninja during testing, so I'm not sure if this is an actual thing, or it happened because of my shenanigans which were:
- deleted advanced-cache.php in hopes of getting it to run;
- I enabled caching, so the module state (on) got stored in the DB;
- Setup ran and it created a wp-config.php (https://github.com/Automattic/jetpack/pull/36115 will properly check where wp-config.php is) that wasn't there;
- this resulted in an error 500 during the setup phase (probably because JN doesn't work with anything other than its files), which didn't clear the error state and since it was dismissed.

I guess we should add a check for the setup request as well and if it errors out, disable the module as well.

![Image](https://github.com/Automattic/jetpack/assets/11799079/9f82460c-8f26-4c05-bebf-29628d21a46c)

**Comment by pyronaur** [comment] 2024-03-04 12:58
Tested this but couldn't reproduce. Could it be that https://github.com/Automattic/jetpack/pull/36022 fixed this? It got merged around a similar time when this issue was opened.

@haqadn also tested and couldn't reproduce.

p1709531819904069-slack-C016BBAFHHS

**Comment by haqadn** [comment] 2024-03-05 04:17
Closing based on the conversation here: p1709566754938389/1709531819.904069-slack-C016BBAFHHS

**Closed as completed by haqadn** 2024-03-05 04:17 UTC
Labels: [Plugin] Boost, [Boost Feature] Page Cache
