### ISSUE TITLE
Declaration of Jetpack_IXR_Client::query() should be compatible with IXR_Client

### ISSUE THREAD

**Issue by Njengah** [Automattic/jetpack#16865] opened 2020-08-17 14:17 UTC
I am getting this warning after the latest WordPress 5.5 update :

`Declaration of Jetpack_IXR_Client::query() should be compatible with IXR_Client::query(…$args)` in

The wp_config debug mode is set to false but the warning is persistent. 

This error appears on the classic editor **Add Post** or **Edit post**. I found out it is related to the way Jetpack class is used in the new WordPress version 5.5.

I have downgraded the version to 5.4 and it is fixed. Is there a better solution for version 5.5?

**Comment by jeherve** [comment] 2020-08-17 14:17
closing as duplicate of #16857.

**Closed by jeherve** 2020-08-17 14:17 UTC
