### ISSUE TITLE
Sitemaps: missing tag error in Google search console

### ISSUE THREAD

**Issue by eliorivero** [Automattic/jetpack#7650] opened 2017-08-16 22:05 UTC
#### Steps to reproduce the issue
submit news-sitemap.xml of your site.
Note: this sitemap was empty at the moment of submission.

#### What I expected
No errors

#### What happened instead
After submitting the sitemap, it shows
<img width="652" alt="captura de pantalla 2017-08-16 a la s 19 03 45" src="https://user-images.githubusercontent.com/1041600/29387284-b0c6cccc-82b5-11e7-803c-14b0bdda78f4.png">

clicking on the sitemap link takes you to
<img width="900" alt="captura de pantalla 2017-08-16 a la s 19 02 40" src="https://user-images.githubusercontent.com/1041600/29387285-b2a86636-82b5-11e7-8367-ff0415337282.png">

**Comment by zinigor** [comment] 2017-08-17 15:56
What was the content of `news-sitemap.xml` at that time? Is there a reproducible case? If there is, I'd love to take a look.

**Comment by eliorivero** [comment] 2017-08-17 18:31
I pointed it in the original description since I think this is one of the causes, the map was (and still is) empty since it's the one for recent articles.
This is the map https://elio.blog/news-sitemap.xml

**Comment by jeherve** [comment] 2018-09-04 16:46
Closing as duplicate of #9753

**Closed by jeherve** 2018-09-04 16:46 UTC
Labels: Sitemaps, [Type] Bug, [Type] Duplicate
