### ISSUE TITLE
JetPack Modules / Plugins conflict map not working when JP is installed first.

### ISSUE THREAD

**Issue by rantoncuadrado** [Automattic/jetpack#10015] opened 2018-08-13 07:06 UTC
#### Steps to reproduce the issue

1. Install & customize JP first (As on Atomic sites: when you make a site Atomic, JP gets installed) 
2. Install & customize one of the plugins in the conflict map. (For instance, YOAST SEO, with the sitemaps module installed). I'm referring the conflict map here: https://github.com/Automattic/jetpack/blob/dccb87c8481c972d8e92c376667b7438e1c5a930/class.jetpack.php#L98
3. The conflict map lists some plugins and the incompatibility they case working together with some JetPack modules.

> Map of modules that have conflicts with plugins and should not be auto-activated
> * if the plugins are active. Used by filter_default_modules

#### What I expected

If we know some incompatibilities and they are on this list, could we either 1) run a check to warn the users that they are using incompatible with JetPack plugins or 2) deactivate the corresponding JP module when we detect one of these plugins ?

#### What happened instead

Nothing. Both modules are enabled.
In thes example, site aprehendizajes.com, we have 2 sitemaps for this site:

https://aprehendizajes.com/sitemap.xml (JETPACK sitemap)
https://aprehendizajes.com/sitemap_index.xml (YOAST SEO sitemap)

**Comment by jeherve** [comment] 2018-09-05 10:58
Closing as duplicate of #8146.

**Closed by jeherve** 2018-09-05 10:58 UTC
Labels: General, [Pri] Normal, [Type] Bug, [Type] Duplicate
