### ISSUE TITLE
Cannot share duplicated Products

### ISSUE THREAD

**Issue by alexsanford** [Automattic/jetpack#29779] opened 2023-03-29 15:30 UTC
### Impacted plugin

Social

### Quick summary

Auto-sharing previously published posts is [not supported for custom post types](https://jetpack.com/support/jetpack-social/social-sharing-new-posts/#auto-sharing-previously-published-posts). However, when I duplicate a WooCommerce Product, I am unable to share the duplicated product even before it is published.

This came up in 6073265-zen

### Steps to reproduce

1. Create and publish a WooCommerce Product.
2. On the "All Products" page, use the "Duplicate" link under the product name in the table to create a duplicate of the Product.
3. In the sidebar, click "Edit" beside "Jetpack Social".
4. See that the sharing checkbox(es) are greyed out.

### A clear and concise description of what you expected to happen.

I expected to be able to share the new Product, since it has not been published yet.

### What actually happened

I was unable to share the Product before publishing.

### Impact

All Jetpack users also using WooCommerce. This may also apply to other custom post types.

### Available workarounds?

Yes, difficult to implement. The user must manually copy all data into a new Product.

**Comment by jeherve** [comment] 2023-03-29 17:23
Related: #264

**Comment by danjjohnson** [comment] 2023-03-30 10:56
I previously opened this as an enhancement: https://github.com/Automattic/jetpack/issues/25978

@jeherve do you think it makes more sense as a bug or an enhancement?

**Comment by jeherve** [comment] 2023-03-30 11:09
I think it may qualify as a bug, as we fail to strip the necessary meta data. I'm not sure yet if this should be addressed in Jetpack or in WooCommerce's duplicate feature.

Previous discussions on this:

https://github.com/woocommerce/woocommerce/issues/13180
https://github.com/woocommerce/woocommerce/issues/26192

With this in mind, I'll close this issue in favour of #6376.

**Closed as completed by jeherve** 2023-03-30 11:09 UTC
Labels: Bug, [Closed] Duplicate, [Feature] Publicize, [Pri] Low, Customer Report [LEGACY], [Plugin] Jetpack, [Plugin] Social

**Comment by sdarte** [comment] 2023-04-06 12:44
So is this issue fixed?

**Comment by jeherve** [comment] 2023-04-06 16:46
@sdarte It is not. As you figured out, the issue is still open and tracked in #6376.

**Comment by sdarte** [comment] 2023-04-06 16:55
Who in their right mind is going to create each product over and over again, when duplicate works so well. This is a major flaw!
Off my soapbox!

Sue
________________________________
