### ISSUE TITLE
Publicize: Allow for customizing of each social network's custom message individually

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#9789] opened 2018-06-18 15:03 UTC
It would be great to allow for a specific custom message (or optional custom message) for each social network for cases in which a user may only want to write a custom message for one particular social network, such as Twitter.

**Comment by jeherve** [comment] 2018-09-04 09:55
Closing as duplicate of #261

**Closed by jeherve** 2018-09-04 09:55 UTC
Labels: Publicize, [Pri] Normal, [Type] Duplicate, [Type] Enhancement
