### ISSUE TITLE
Able to sent email also to email address in email field

### ISSUE THREAD

**Issue by samikeijonen** [Automattic/jetpack#11490] opened 2019-03-05 21:44 UTC
If there is email field in contact form (block) can the form info be sent to that email also. That would be nice option to have.

I'm not sure where and how in block settings or in inspector this settings should be. Perhaps a checkbox if there is an email field. And in that case maybe there should be a checkbox in front-end also. Lot's of maybe:)

**Comment by jeherve** [comment] 2019-03-05 21:52
Thanks for the suggestion. I believe this is a duplicate of this issue: #631

I'll add your comment there.

**Closed by jeherve** 2019-03-05 21:52 UTC
Labels: Contact Form, [Type] Duplicate
