### ISSUE TITLE
Site Logo: Do not require a connection to WordPress.com to work.

### ISSUE THREAD

**Issue by philiparthurmoore** [Automattic/jetpack#3269] opened 2016-01-14 12:50 UTC
It appears that on live, remote websites, a connection to WordPress.com is necessary in order for the site logo feature to work, but on localhost (when Jetpack is in debug mode), the site logo feature works fine. I've attempted to put a remote site into debug mode but the site logo feature won't show up.

Is there a reason why a connection to .com is required for remote sites to use the site logo feature, and are my above assumptions/findings correct? If so, could this be changed so that users don't have to connect to .com in order to use the site logo feature?

**Comment by jeherve** [comment] 2016-01-14 13:16
I can't seem to be able to reproduce the issue. I installed a theme using the Site Logo feature (Sapor) on a remote site set to use Jetpack's Development mode, and the Site Logo option was there:
![screen shot 2016-01-14 at 2 13 49 pm](https://cloud.githubusercontent.com/assets/426388/12325254/2e2257ce-bac9-11e5-83e4-e5afe1ab87fe.png)

The logo was also displayed on the frontend:
![screen shot 2016-01-14 at 2 14 54 pm](https://cloud.githubusercontent.com/assets/426388/12325262/39a99ef4-bac9-11e5-9c0e-6eeaa41e3af5.png)

Jetpack's Theme Tools aren't tied to Jetpack's connection system, so you should be able to use them without a connection to WordPress.com.

Could you try with a different theme? If that doesn't help, could you try on a different site, to make sure the issue isn't linked to your current testing site?

Thanks!

**Comment by philiparthurmoore** [comment] 2016-01-14 13:49
@jeherve, Thanks for the sanity check on this. I'll close the issue because I trust that if it's working with your setup, then it should be working. Thanks for the heads up about Theme Tools not requiring the .com connection.

**Comment by philiparthurmoore** [comment] 2016-01-27 02:30
Related: #3345

**Comment by jeherve** [comment] 2016-01-27 11:39
@philiparthurmoore Could you let me know if you could reproduce the issue when in Development mode, or if this only happened when your site was neither connected to WordPress.com, neither in Dev mode (as outlined in #3345)?

Thanks!

**Comment by jeherve** [comment] 2016-02-17 14:24
Closing in favor of #3345

**Closed by jeherve** 2016-02-17 14:24 UTC
Labels: Theme Tools, [Status] Needs Author Reply
