### ISSUE TITLE
Login with WP.com does not preserve full redirect URL for certain url parameters

### ISSUE THREAD

**Issue by richardmuscat** [Automattic/jetpack#1461] opened 2014-12-29 15:17 UTC
When logging into a Jetpack-connected site with WP.com credentials (SSO) if the redirect URL contains "/wp-admin/plugin-install.php?tab=plugin-information&plugin=jetpack", the "&plugin=jetpack" is discarded upon successful login.

**Comment by jeherve** [comment] 2015-01-05 07:52
Closing as duplicate of #1342

**Closed by jeherve** 2015-01-05 07:52 UTC
Labels: bug, SSO
