### ISSUE TITLE
Modify JITM: Add more relevant JITM to plans page within JP dash.

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#11528] opened 2019-03-08 16:24 UTC
The current help JITM that's displayed on the plans page takes the customer to a redundant page. From one plans page to another. See expectation details below!

#### Steps to reproduce the issue

1. Spin up a JN site
2. Connect jetpack. 
3. Once back in wp-admin, navigate to the Plans page in the jetpack dashboard

#### What I expected
I expected to be taken to a contact form or live chat box to ask any specific questions I had about the plans.

#### What happened instead
I'm taken from a jetpack plans grid in wp-admin to the jetpack plans grid in calypso. It doesn't seek to answer any of my questions as a customer. Just a bit redundant. 

**Screenshots**
<img width="1666" alt="screen shot 2019-03-08 at 10 55 35 am" src="https://user-images.githubusercontent.com/214813/54040920-80009d80-4194-11e9-86df-b7040c35e355.png">

**Comment by jeherve** [comment] 2019-03-08 16:38
hm. That's definitely a regression. It was previously redirecting you to https://jetpack.com/contact-support/?rel=support
Internal reference: r185772-wpcom

For reference, here is how the link looks like:
https://jetpack.com/redirect/?source=jitm-presales_support&site=mysite.com&u=1&redirect=%2Fwp-admin%2Fadmin.php%3Fpage%3Djetpack

**Comment by jeffgolenski** [comment] 2019-03-08 16:42
That's strange. The "just ask" button takes me to the same link (different site obviously): https://jetpack.com/redirect/?source=jitm-presales_support&site=peculiar-wildebeest.jurassic.ninja&u=1&redirect=%2Fwp-admin%2Fadmin.php%3Fpage%3Djetpack

Here's it in action:

![just-ask-jitm](https://user-images.githubusercontent.com/214813/54042082-5006c980-4197-11e9-9aae-3a607a8911ab.gif)

**Comment by jeherve** [comment] 2019-03-20 10:48
Fixed in D25770-code

**Closed by jeherve** 2019-03-20 10:48 UTC
Labels: Admin Page, JITM, Plans, [Type] Bug
