### ISSUE TITLE
(default theme), doesn't support Infinite Scroll.

### ISSUE THREAD

**Issue by hinaloe** [Automattic/jetpack#2081] opened 2015-05-04 19:19 UTC
![](https://puu.sh/hBoN5/0edd08dc5b.png)

I know that _Infinite-Scroll_ is available in default themes by [`the_neverending_home_page_theme_support`](https://github.com/Automattic/jetpack/blob/master/modules/infinite-scroll/infinity.php#L1274), but when not activated infinite-scroll, it say that

> At this time, your theme, Twenty Thirteen, doesn't support Infinite Scroll. Unlike other Jetpack modules, Infinite Scroll needs information from your theme to function properly.

I think it is too old bug...not?

**Comment by georgestephanis** [comment] 2015-05-04 19:22
What version of Jetpack are you running?

**Comment by hinaloe** [comment] 2015-05-04 19:25
I checked in now:

- 3.3.x
- 3.5.0
- 3.5.1 (master)

thanks.

**Comment by jeherve** [comment] 2015-05-04 19:37
I can reproduce the problem with all the default themes, including Twenty Fifteen.

I can actually activate the module, but the module description text is wrong:

![screen shot 2015-05-04 at 9 35 26 pm](https://cloud.githubusercontent.com/assets/426388/7460720/85d9e104-f2a5-11e4-8b21-658cad29e712.png)

Here is where the text is pulled from:
https://github.com/Automattic/jetpack/blob/730fcc62d7aeda5f6eeb852079e98dbb18b44006/modules/module-info.php#L632

**Comment by michaeldcain** [comment] 2015-05-14 13:19
@jeherve I can't reproduce this locally. Does the issue still exist for you?

**Comment by kraftbj** [comment] 2015-05-14 19:07
@michaeldcain I was able to reproduce on my production site running Jetpack master. ( @jeherve is afk atm).

I think it is because the theme annotations for the defaults are added in /modules/infinite-scroll.php which isn't loaded unless the IS module is active. When IS isn't active, the annotation files aren't included so we've never added theme support for IS so the check at https://github.com/Automattic/jetpack/blob/730fcc62d7aeda5f6eeb852079e98dbb18b44006/modules/module-info.php#L627 fails, else'ing us to the no support text.

**Comment by michaeldcain** [comment] 2015-05-15 13:39
+1, thanks for verifying @kraftbj

**Comment by eliorivero** [comment] 2017-02-10 20:53
Closing since this an issue in the old interface. The new one doesn't have this issue.

**Closed** 2017-02-13 14:22 UTC
Labels: Infinite Scroll, Theme Tools, [Team] tdiv, [Type] Bug
