### ISSUE TITLE
Publicize: CPTs not publicizing in 4.2.x (unconfirmed

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#4963] opened 2016-08-24 18:57 UTC
In 2784432-t it seems that CPTs are not publicizing properly. The user has added the following code: `add_action('init', 'pub_que');
function pub_que() {
add_post_type_support( 'question', 'publicize' );
}`

However, we don't seem to be syncing the CPTs over to WordPress.com, as the postid's aren't appearing in the RC. As a fix, we've tried also adding 
`add_filter( 'rest_api_allowed_public_metadata', 'bk_add_cpt_test');
function bk_add_cpt_test( $cpts ){
$cpts[] = 'CPT SLUG HERE';
return $cpts;
}` 
to see if that helps with getting them synced over.

**Comment by jeherve** [comment] 2016-08-25 11:58
> (unconfirmed)

Can you reproduce on your end with a test CPT?

**Comment by chaselivingston** [comment] 2016-08-25 14:38
I'm not able to reproduce, a test CPT on my sandbox publicized to Facebook.

**Comment by gravityrail** [comment] 2016-08-26 17:43
Until we have a way to reproduce this issue, there's not too much we can do. We do sync post types and the post type support global, and I have double-checked that this particular site has successfully synced the `question` post type, AND that on WPCOM `post_type_supports( 'question', 'publicize' );` returns `TRUE`.

On WPCOM we call `$replica->load_custom_post_type( $post->post_type );` to install synced CPT data when we check if a post is publicizable, and this seems to work for ensuring that synced CPTs work properly (unless it's failing for some reason?). Perhaps there's a code path we missed, and/or we need to load custom post types for Jetpack sites earlier in the request.

**Comment by lezama** [comment] 2016-09-01 02:40
@chaselivingston I am closing this as we couldn't reproduce and there were no recent reports of it, please reopen if needed.

**Closed by lezama** 2016-09-01 02:40 UTC
Labels: Publicize, Sync, [Team] Poseidon
