### ISSUE TITLE
Subscriptions Block: Inconsistent placeholder text for subscribe button in wpcom between editor and front end

### ISSUE THREAD

**Issue by andrewserong** [Automattic/jetpack#18704] opened 2021-02-04 02:38 UTC
In wpcom, the placeholder text for the submit button in the Subscriptions block is rendered as `Subscribe` in the editor, however we override the defaults for the rendering of the block to use `Follow` if the block is rendered in a wpcom environment. This makes for a small but slightly confusing difference between the editor and the front end.

The subscribe button is set to use the word `Follow` in its default placeholder text in this line: https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/plugins/jetpack/modules/subscriptions/views.php#L658

Shall we update this to use the word `Subscribe` instead so that it matches?

#### Steps to reproduce the issue

1. In a dotcom simple site go to add a Subscriptions block (or select a design from `/new` that includes the block, such as Bowen)
2. In the editor see that the default placeholder text for the submit button is Subscribe
3. Publish or preview the post and you should see that the submit button says `Follow`

#### What I expected

Consistency between the editor view and the front end view. In this case as reported by @p-jackson I expected to see `Subscribe` instead of follow.

#### What happened instead

The button rendered with `Follow` as the placeholder text.

**Screenshots**

Editor view:

![image](https://user-images.githubusercontent.com/14988353/106836736-d4e51f80-66ed-11eb-8b13-31e0682abea6.png)

Front end view:

![image](https://user-images.githubusercontent.com/14988353/106836878-107fe980-66ee-11eb-8419-58b9454ba9a6.png)

**Comment by jeherve** [comment] 2021-02-04 07:14
Closing as duplicate of #18518.

**Closed by jeherve** 2021-02-04 07:14 UTC
Labels: [Block] Subscriptions, [Type] Bug
