### ISSUE TITLE
Block: Add a new Google Docs/Sheets/Presentations Embed Block

### ISSUE THREAD

**Issue by glendaviesnz** [Automattic/jetpack#14970] opened 2020-03-13 00:31 UTC
#### Is your feature request related to a problem? Please describe.

Currently it is not possible to add a Google Doc/Sheet/Presentation embed Block within the editor, or to transform an existing Google Apps shortcode into an embed

#### Describe the solution you'd like

These embed blocks should be based around the [Block Variations API](https://make.wordpress.org/core/2020/02/27/introduce-block-variations-api/), with the bulk of the code shared between them. The UI design should be as follows:

![gblock](https://user-images.githubusercontent.com/3629020/76578620-12691900-652e-11ea-97de-7ad73bb8fb4f.png)

#### Additional context

- An example of the [transformation of Google Apps short code](https://github.com/Automattic/jetpack/blob/master/extensions/blocks/google-calendar/index.js#L52)
- The Google Calendar block will eventually be refactored to use this Block Variation, but this can't happen until the minimum WordPress version supported by Jetpack is 5.4, as the Gutenberg version in this release is the minimum required to support Block Variations.
- These blocks should be available to all users regardless of there Jetpack/WP.com plan

**Comment by davemart-in** [comment] 2020-05-25 14:22
Duplicate of https://github.com/Automattic/dotcom-manage/issues/32 Closing this one.

**Closed by davemart-in** 2020-05-25 14:22 UTC
Labels: Shortcodes / Embeds, [Block] Google Apps, [Pri] Normal, [Size] M, [Type] Feature
