### ISSUE TITLE
Subscription: Add 'Like' link in the subscription emails

### ISSUE THREAD

**Issue by lamdayap** [Automattic/jetpack#7444] opened 2017-07-10 15:07 UTC
Subscription emails from WordPress.com has a link to 'like' either the post/comment:

http://cld.wthms.co/D3TqUB

This link isn't available for Jetpack Subscription Emails:

http://cld.wthms.co/vJIbZp

Reported in 3316096-t

**Comment by aheckler** [comment] 2017-08-28 15:30
648994-zen

**Comment by jeherve** [comment] 2018-09-04 16:45
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.

**Comment by danjjohnson** [comment] 2018-09-27 09:08
Mentioned in 3186002-hc

**Comment by carladoria** [comment] 2020-03-09 16:31
Re-opened this issue. Reported in 2739684-zen (Atomic site)

**Comment by AtrumGeost** [comment] 2020-03-09 16:36
Since the original screenshots are missing, I'm adding some new ones:

Email notifications from WordPress.com simple sites:

![Screen Shot on 2020-03-09 at 11:12:46](https://user-images.githubusercontent.com/3696121/76235952-da926680-61f9-11ea-89b1-c4817a111113.png)

Email notifications on Atomic and Jetpack sites:

![Screen Shot 2020-03-09 at 11 22 00](https://user-images.githubusercontent.com/3696121/76235993-f5fd7180-61f9-11ea-913d-47fbe8d91239.png)

![Screen Shot 2020-03-09 at 11 34 24](https://user-images.githubusercontent.com/3696121/76236001-f8f86200-61f9-11ea-94e1-5507dea985bb.png)

(For the Atomic and JP sites, I confirmed the Likes are enabled and they are displayed on the single posts)

**Comment by lancewillett** [comment] 2020-03-09 16:43
+1 to enable this — both for feature parity with WP.com sites — but also it's one of my most used links in WordPress.com emails, in my own experience it saves me time. Click one button, open and like the post in one go. Boom!

**Comment by nagpai** [comment] 2020-05-05 06:06
Reported in 2938634-zen and 2888499-zen

**Comment by AtrumGeost** [comment] 2020-06-08 21:37
I got another request here 21758028-hc

**Comment by ersatzpenguin** [comment] 2020-09-11 15:26
Another request here: 3296692-zen

**Comment by galakhyati** [comment] 2020-10-27 11:33
Reported in 3330991-zen

**Comment by chrisfromthelc** [comment] 2020-10-29 22:38
Another report in 25205741-hc

**Comment by fashuvo** [comment] 2020-11-07 03:40
Another request in 3470131-zen

**Comment by julsyd** [comment] 2021-03-26 13:54
3852393-zen

> I have noticed that when i follow other blogs and get email updates, they have a like button at the bottom of the post in the email. However, the email notifications that are sent out when someone follows our site only shows a comment button instead.

**Comment by happychait** [comment] 2021-04-15 21:48
A customer asked for it in 29040062-hc

> having emailers be able to like in the business plan

**Comment by jeherve** [comment] 2022-04-25 16:19
Closing, as this has now been added.

**Closed by jeherve** 2022-04-25 16:19 UTC
Labels: [Type] Enhancement, Subscriptions, Likes, [Pri] Low, [Type] Happiness Request
