### ISSUE TITLE
Site Accelerator/Photon invalidates Atom RSS feeds

### ISSUE THREAD

**Issue by tw2113** [Automattic/jetpack#13722] opened 2019-10-11 06:23 UTC
```
XML Parsing Error: not well-formed
Location: https://www.example.com/blog/feed/atom/
Line Number 19, Column 123:
<icon>https://i0.wp.com/www.example.com/wp-content/uploads/2018/04/example-e1524437311719.png?fit=32%2C32&ssl=1</icon>
```
Specifically around the `ssl=1` and the 1 specifically according to a passing of the feed URL through https://www.feedvalidator.org/

#### Steps to reproduce the issue

1. Enable Accelerator support for the site.
2. Visit https://www.MYSITE.com/feed/atom/

I can provide a hard example if needed, though I'll want to request permission to provide the domain I have most recently found that has the error.

**Comment by jeherve** [comment] 2019-10-11 08:00
This is most likely a duplicate of #8321.

**Closed by jeherve** 2019-10-11 08:00 UTC
Labels: Photon, [Type] Duplicate
