### ISSUE TITLE
Sharing: All social media buttons open popup with post instead of social media site

### ISSUE THREAD

**Issue by bobbydams** [Automattic/jetpack#7775] opened 2017-09-12 21:15 UTC
All social media buttons, except whatsapp and send in email, open a popup window with the post instead of social media site. We are using the following URL scheme: `http://example.com/en/2017/09/12/this-is-a-post`. At the end of the URL is `/?share=reddit&nb=1`. So after clicking a share button the full URL is `http://example.com/en/2017/09/12/this-is-a-post/?share=reddit&nb=1`. The social sharing buttons built into my theme work as expected so it only seems to be an issue with Publisize.

Example from Publisize
http://example.com/en/2017/09/12/this-is-a-post/?share=facebook&nb=1

Example from built-in social sharing
http://www.facebook.com/sharer.php?u=http://example.com/en/2017/09/12/this-is-a-post/&t=This%2028%20Is%20A%20Post

Wordpress v4.8.1
Jetpack v5.3

#### Steps to reproduce the issue

1. Enable Sharing on posts
2. Click Share this on Facebook button

#### What I expected
A popup with a Facebook sharing window

#### What happened instead
The post from my site was in the popup.

**Comment by kraftbj** [comment] 2017-09-13 17:26
Hi @bobbydams -- In many cases, this is related to caching on the site ignoring the query string and returning the post without processing it through PHP or server rules (.htaccess or nginx conf files) that are ignoring the string.

I'm going to close this since, at this point, it sounds like a support issue and not a bug, but if there's more to it, we can reopen.

**Closed by kraftbj** 2017-09-13 17:26 UTC
