### ISSUE TITLE
Users can enable a paid feature "Ads" without being a paid member

### ISSUE THREAD

**Issue by gagan0123** [Automattic/jetpack#6754] opened 2017-03-26 21:08 UTC
By default, the features that are "Paid" are disabled in Jetpack, and we don't get a button to enable them, but not for Ads, here's a screencast to reproduce the issue.

[![Enabling ads in non premium accounts Jetpack](https://img.youtube.com/vi/MLqOMGB5dY8/default.jpg)](https://www.youtube.com/watch?v=MLqOMGB5dY8)

**Comment by jeherve** [comment] 2017-03-27 14:45
I was able to reproduce on my end as well.

cc @dbspringer

**Comment by jeherve** [comment] 2017-03-30 18:08
Fixed in #6811

**Comment by dbspringer** [comment] 2017-03-30 18:12
Thanks @gagan0123 and @jeherve for pointing this out/shepherding this while I've had some afk 🙇

**Comment by jeherve** [comment] 2017-10-27 08:55
Looks like this issue is back. Reopening.

**Comment by rclations** [comment] 2018-04-04 20:35
@jeherve are you still able to reproduce?
I tried testing but it appears the /search route where the toggles were showing in the video above is no longer available.

**Comment by rachelmcr** [comment] 2018-04-12 17:37
Reopening this as I'm still seeing an issue here — let me know if you'd prefer a new, separate issue for this. If a site had ads enabled and then downgraded their plan, they can't toggle the ads feature on/off but the ads still appear on their site.

I reproduced with these steps:

1. Upgrade a Jetpack site to the Premium plan.
2. Enable Jetpack ads on the site and confirm they appear on the front end.
3. Cancel the Premium plan.
4. Check the front end of the site.

Result: The ads still appear on the front end, even though the plan is cancelled. The module is disabled in WP Admin so there's no way to turn it off from there.

**Comment by rclations** [comment] 2018-04-13 11:44
I think this may be solved by extension of the work done in  https://github.com/Automattic/jetpack/pull/9268

**Comment by jeherve** [comment] 2018-09-10 13:58
I ran some tests, and although the ads may not disappear right away, they are eventually deactivated by the cron that is run by the WordAds module.

I think this is good to close for now. If we decide to implement something to deactivate the ads faster, we could add a `Jetpack::active_plan_supports( 'wordads' )` check to the `should_bail` function that is run when the ads are rendered.

**Closed by jeherve** 2018-09-10 13:58 UTC
Labels: WordAds, [Pri] High, [Status] Needs Testing, [Type] Bug
