### ISSUE TITLE
Suggestion: Use pre-fed Publicize message as post content for Facebook

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/jetpack#9151] opened 2018-03-26 19:01 UTC
**Steps to reproduce**: Follow the steps below to reproduce the issue. 

- Start at https://wordpress.com/sharing and connect your Facebook page
- Create a new post on https://wordpress.com/posts Can be done on any WordPress.com site or Jetpack site, on any plan.
- Enter title and content. 
- You can also choose to enter SEO description (only on WordPress.com Business plan) and excerpt if necessary. These two fields do not really have an effect here.
- Don't enter a Publicize message. But, you can click the Publicize box and notice that the title is pre-fed here. Do not edit this pre-fed message even a bit.
- Publish the post.

**What is suggested:** Use the pre-fed content on the Publicize box, when posting to Facebook. 

**What happens instead:** 

- The post is Publicized to Facebook **without** the pre-fed message as the post content on Facebook. Instead, a post summary is seen as the post content.

![image](https://user-images.githubusercontent.com/18581859/37926856-1838965c-3156-11e8-8b4f-6b65b69a1641.png)

- On Twitter though, the pre-fed content is used as post content. 
- Have not tested this on other social networks.

**One more thing to try:** Try editing the Publicize message before publishing the post by doing any of these changes:

- Add a single character
- Remove a single character
- Remove the last character and add it again. 

![image](https://user-images.githubusercontent.com/18581859/37926868-1da99f32-3156-11e8-944f-e03c58ef9931.png)

When these are done, this Publicize message is used as Facebook post content.

**Comment by arunsathiya** [comment] 2018-03-26 19:05
#1041456-zen

**Comment by jeherve** [comment] 2018-03-27 16:08
Thanks for the report. I'll close this as duplicate of #6760, as I believe this is part of a bigger rework of the behaviour of the Publicize message box, that currently behaves differently on WordPress.com and in wp-admin.

**Closed by jeherve** 2018-03-27 16:08 UTC
Labels: Publicize, [Type] Duplicate
