### ISSUE TITLE
Tiled Gallery: Link To Media File not showing full image

### ISSUE THREAD

**Issue by formosattic** [Automattic/jetpack#20980] opened 2021-09-07 08:36 UTC
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Create a tiled gallery, using horizontal and/or vertical images
2. In the Block settings, set **Link To** to **Media File**

### A clear and concise description of what you expected to happen.

Media file should show in full.

### What actually happened

On self-hosted, with Gutenberg on/off, the media file should shows cropped as squares.
![troubleshooting](https://user-images.githubusercontent.com/15944096/132310492-4f90a247-3f52-419a-8c85-6734f735d357.gif)

### Other information
At WordPress.com (Simple, Atomic with Gutenberg on/off), the image shows in full, but not if the Tiled Gallery is in a Reusable block.

![troubleshooting](https://user-images.githubusercontent.com/15944096/132312575-498b5d2d-157b-46b6-b697-fe68e4d0da86.gif)

Ticket: 4278458-zd-woothemes

### Browser

Chrome/Chromium

**Comment by jeherve** [comment] 2021-09-07 10:47
I cannot seem to be able to reproduce on my end. When I pick the "Link to media file" option, the images link to the full-size image as I uploaded it to my site, where no cropping can be applied.

On the user's site in the ticket you linked to, the gallery on the home page doesn't appear to be set to "Link to media file", since the Carousel view opens when I click on the images. I also see the full images in the carousel view, and not just a cropped version.

I tried transforming the block into a reusable block, but that didn't help me reproduce, unfortunately.

Could you give me an example of an image URL you see when clicking on an image and seeing a cropped image?

Thank you!

**Comment by formosattic** [comment] 2021-09-11 07:54
@jeherve  see follow-up on Slack, p1631346656470000-slack-C0CMN0V97

**Comment by jeherve** [comment] 2021-09-13 12:03
Thanks for the extra details. This turns out to be the same issue as in #16940. I'll close this one as duplicate.

**Closed by jeherve** 2021-09-13 12:03 UTC
Labels: [Type] Bug, [Status] Needs Author Reply, [Type] Happiness Request, [Block] Tiled Gallery, [Plugin] Jetpack
