### ISSUE TITLE
JS Error in EU cookie widget

### ISSUE THREAD

**Issue by scruffian** [Automattic/jetpack#17701] opened 2020-11-03 16:19 UTC
#### Steps to reproduce the issue

1. Go to https://peridotfood.com/
2. Open the console
3. See error

This is breaking the responsive nature of the site.

**Screenshots**
<img width="1440" alt="Screenshot 2020-11-03 at 16 19 23" src="https://user-images.githubusercontent.com/275961/98011863-588e2800-1df0-11eb-8714-377e3a05178c.png">

**Comment by jeherve** [comment] 2020-11-03 16:23
Closing as duplicate of #17560

**Closed by jeherve** 2020-11-03 16:23 UTC
Labels: Extra Sidebar Widgets, [Type] Bug
