### ISSUE TITLE
VideoPress: VideoPress toggle on Atomic sites always disabled with no option to enable 

### ISSUE THREAD

**Issue by ash1eygrace** [Automattic/jetpack#32348] opened 2023-08-08 17:35 UTC
### Impacted plugin

Jetpack, VideoPress

### Quick summary

When an Atomic site owner navigates to Jetpack > Dashboard > Settings > Performance, they see that the toggle is grayed out and a message that says: 

> Enable VideoPress
This feature has been disabled by a site administrator. [Learn more](https://jetpack.com/redirect/?source=jetpack-support-module-overrides&site=woosensei111111.wpcomstaging.com).  

The module can become deactivated during migrations to WordPress.com. It's expected that Atomic Sites will have VideoPress enabled by default. If the VideoPress module becomes disabled, the user cannot enable it from the settings, and HEs need to enable it manually. 

### Steps to reproduce

1. Start with any atomic site 
2. Diable the VideoPress module (use CLI) 
3. Navigate to Jetpack > Dashboard > Settings > Performance 
4. Scroll down to the Media card

### A clear and concise description of what you expected to happen.

I expect VideoPress to be enabled by default on all Atomic sites; at the very least, if we're not programmatically keeping it enabled at all times, the user should be able to enable the feature if it's disabled for some reason, like migrating to WordPress.com. 

Since VideoPress is enabled on nearly every Atomic Site, the message "This feature has been disabled by a site administrator. [Learn more](https://jetpack.com/redirect/?source=jetpack-support-module-overrides&site=woosensei111111.wpcomstaging.com)" could use some clarification. Maybe, it would help clear up confusion to say something like: 

> This feature is managed by WordPress.com. 

### What actually happened

It shows VideoPress is disabled, and the user can't enable it: 
<img width="1106" alt="image" src="https://github.com/Automattic/jetpack/assets/29527450/ffdb81fb-db7d-47a6-9c9e-74a738e16510">

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Related to: 
- p1686144887015699-slack-C03TY6J1A 
- p1647286666372709-slack-C03TY6J1A

**Comment by jeherve** [comment] 2023-08-08 18:10
I can see the override on any of my test sites as well, but I cannot figure out where it is added:

<img width="950" alt="image" src="https://github.com/Automattic/jetpack/assets/426388/d3258aeb-c414-4c5e-a854-333115a600de">

I initially thought there may be some code in wpcomsh that would force this on via filters, but I cannot find anything obvious:

https://github.com/Automattic/jetpack/blob/d46758873e25a473ae3dc63e028badee0b377fea/projects/plugins/jetpack/src/class-jetpack-modules-overrides.php#L96-L102

We do have some code in place when a site is private, but I can reproduce the issue on public WoA sites as well.

@retrofox Does this ring any bells? Do you have any ideas to what may be happening here?

**Comment by CGastrell** [comment] 2023-09-25 19:23
Waiting for deploy/confirmation, but this one should be fixed as of automattic/wpcomsh#1507

**Comment by CGastrell** [comment] 2023-09-27 14:54
This should be fixed since https://github.com/Automattic/wpcomsh/pull/1508 and its release https://github.com/Automattic/wpcomsh/releases/tag/v3.13.21

**Comment by jsnmoon** [comment] 2023-10-13 19:23
@CGastrell: I am closing this issue as it appears to be complete.

**Closed as completed by jsnmoon** 2023-10-13 19:23 UTC
Labels: Bug, [Pri] Normal, [Plugin] Jetpack, [Platform] Atomic, Needs triage, [Plugin] VideoPress

**Comment by CGastrell** [comment] 2023-10-14 14:24
Thanks!
