### ISSUE TITLE
Viewing images in carousel gallery breaks the back button

### ISSUE THREAD

**Issue by lumpysimon** [Automattic/jetpack#2703] opened 2015-09-14 23:21 UTC
When a visitor views a page with a gallery on it, views some images in the carousel, closes the carousel, then clicks the back button, the desired behaviour would be to go to the previous page in the browsing history. However, the individual image URLs that have been viewed are added to the browsing history, so the back button no longer goes to the previous page, but cycles back through each image.

e.g. https://chagfordfilmfestival.com/photos/2014-batman-v-the-badger/

Click a couple of images then close the carousel, click the back button, and the browsing history will contain URLs such as https://chagfordfilmfestival.com/photos/2014-batman-v-the-badger/#jp-carousel-511

I'm fairly sure that in previous versions of Jetpack this was not the case - you would close the carousel gallery and clicking the back button would take you to the previous page.

**Comment by jeherve** [comment] 2015-09-15 10:54
This problem was fixed in #415, but might have been introduced back in #1051. We'll look into this.

Thanks for the report!

**Comment by osiux** [comment] 2015-09-17 06:25
So, what should be the behavior of this? I was looking at previous versions and seems like it always (or at least from some time) has keep the hash in the history, so if you are viewing an image and refresh the page (or sharing an url with the hash like the one from OP), the gallery is shown.

The current issue, if this is the right behavior, is that when you close the gallery and use the browser buttons, the history is kind of messed up and the UI doesn't update according to the url. I have a patch that fix this, but I would like to be sure on the right behhavior.

a) Hash changes should not be added to history so the back/forward button takes you to the page you were before (like the index), or
b) You can navigate the gallery with the browser buttons since the hash changes are tracked in history.

**Comment by jeherve** [comment] 2015-09-17 08:11
> the history is kind of messed up and the UI doesn't update according to the url

Yeah, that's the bug. The UI should match the URL.

I think #415 does a good job of describing the expected behaviour. Let me know if you have more questions!

**Comment by lumpysimon** [comment] 2015-11-05 11:25
This doesn't look to be fixed in 3.8.0

If I navigate to a page with a carousel on it, click an image to open up the overlay, scroll through a few images, close the overlay, then click the back button, the overlay opens up again, rather than directing me back to the page I was on prior to the page with the carousel.

Or am I misunderstanding the intended behaviour?

**Comment by jeherve** [comment] 2015-11-05 16:01
@lumpysimon I think that's the intended behaviour: The UI (the carousel overlay) should match the URL. 


Before #2719, clicking the back button would change the URL and add the carousel ID, but the Carousel ID wouldn't appear.

Do you think that the browser history should ignore all Carousel overlays, and basically directly go back to whatever page you were viewing before to look at the gallery? That's a valid idea I think. Worth opening a new issue.

**Comment by lumpysimon** [comment] 2015-11-05 16:17
> Do you think that the browser history should ignore all Carousel overlays, and basically directly go back to whatever page you were viewing before to look at the gallery? That's a valid idea I think.

Yes, that was my initial reason for opening this ticket and I thought that was how it was intended to work. When I view something that opens in an overlay I don't feel that is a page in its own right with its own URL. However, I can see there may be different opinions about this, and I can see the advantage of being able to link directly to an individual image within a carousel.

**Comment by jeherve** [comment] 2015-11-10 16:52
> Do you think that the browser history should ignore all Carousel overlays, and basically directly go back to whatever page you were viewing before to look at the gallery?

Also suggested here:
https://wordpress.org/support/topic/returning-to-gallery-after-seeing-jetpack-caroussel-?replies=1&view=all

**Comment by jeherve** [comment] 2016-04-25 15:30
Also suggested here:
https://wordpress.org/support/topic/browser-back-button-carousel?replies=1&view=all

**Comment by thupsi** [comment] 2016-06-10 13:05
Hello, I agree that the current behavior is indeed a bit confusing. I believe most users would expect the back button to take them to the previous page, not the previous photo in the gallery, especially if the pop-up is closed at the time of hitting the back button.

**Comment by illustribe** [comment] 2016-06-22 14:00
I agree as well, although it could be handy in some cases to go back to the carousel, the common user expects the carousel to behave as any other lightbox, meaning continue and use the back button as a tool to navigate through the website. IMO at least an option should be given as to which behavior is needed, since the one lacking is the one most common and (imo) useful.

**Comment by karpad3** [comment] 2016-08-16 15:38
Hi,
I've created a patch to fix this issue.
Feel free to use it or to integrate it into the next version.

https://dl.dropboxusercontent.com/u/3957893/carousel_fix.patch

**Comment by jeherve** [comment] 2016-08-16 15:43
@karpad3 Feel free to [create a Pull Request](https://jetpack.com/contribute/#patch) with that patch, we'll be happy to review it.

**Comment by karpad3** [comment] 2016-08-16 16:22
Hi Jeremy,

I'd be happy to create a pull request, but there seems to be a problem with
my access permissions.
I've created a new branch in your repo and committed the changes, but when
trying to push them into the server I get this error:
*ERROR: Permission to Automattic/jetpack.git denied to karpad3.*
*fatal: Could not read from remote repository.*

*Please make sure you have the correct access rights*
*and the repository exists.*

Do you have any idea how to overcome this issue?

Thanks,
Yotam

**Comment by jeherve** [comment] 2016-08-16 16:26
You'll need to fork the Jetpack repository first, as explained here:
https://help.github.com/articles/fork-a-repo/

Once you've done so, you can add that fork to your local copy of Jetpack with the following command:
`git remote add karpad3 git@github.karpad3/jetpack.git`

Once you've done so, you can push your branch to your fork (`git push -u karpad3 name-of-your-branch`), and an option to create a Pull Request will then appear at the top of this page:
https://github.com/Automattic/Jetpack/

**Comment by karpad3** [comment] 2016-08-16 16:39
Thanks for your help.
I've created the pull request: https://github.com/Automattic/jetpack/pull/4825

**Comment by karpad3** [comment] 2016-09-12 19:51
I'm sorry, but my pull request has a bug: when using the back or forward buttons while the gallery is open, history messed up after gallery close.
I've created a new pull request: [#5168](https://github.com/Automattic/jetpack/pull/5168)
Please use this one and not the previous one.

**Closed** 2016-11-10 13:15 UTC
Labels: Carousel, Cheesy Ticket, [Type] Enhancement
