### ISSUE TITLE
Infinite Scroll: Unprompted changes to number of posts shown per page.

### ISSUE THREAD

**Issue by supernovia** [Automattic/jetpack#16471] opened 2020-07-13 17:53 UTC
Recent changes to Jetpack's Infinite Scroll seem to have caused some issues with the number of posts appearing on sites. The theme hasn't changed, but with this update, sites went from displaying 12 posts per page, to only showing 8.

#### Steps to reproduce the issue

1. Use Pictorico + Jetpack
2. Choose to show 12 posts per page (this is how the demo is configured)
3. Note with IS on, we only see 8 posts. Or 9. It's a bit random from site to site. If we disable infinite scroll, it works as expected.

#### What I expected
For the number of posts displayed to stay the same even after updating Jetpack.

#### What happened instead
The number of posts on the front page changed. Disabling Infinite Scroll, or disabling Jetpack on my .org test site, seems to address it.

**Screenshots**
Here's a screenshot from our showcase page:
![pictorico](https://user-images.githubusercontent.com/3476361/87336373-f5098300-c4fe-11ea-89db-561754096f1c.jpg)

Here's a screenshot from the live showcase. Neither Pictorico nor its settings have been updated
![screencapture-pictoricodemo-wordpress-2020-07-13-11_50_37](https://user-images.githubusercontent.com/3476361/87336495-2d10c600-c4ff-11ea-925c-177e7e6a5289.png)
 anytime recently.

### Context
User complaints:
https://wordpress.com/forums/topic/pictorio-theme-grid-on-homepage/
3135164-zen

**Comment by jeherve** [comment] 2020-07-14 08:24
cc @scruffian; could that be linked to #16317?

**Comment by jeherve** [comment] 2020-08-04 07:23
Some additional info from @BinaryMoon in #16686:


*********

Hi - I sell themes on wordpress.com and recently I have had a number of users complain that the number of posts on the homepage has changed.

You can see the support requests here:
https://premium-themes.forums.wordpress.com/topic/the-section-latest-shows-more-posts-than-it-should/
https://premium-themes.forums.wordpress.com/topic/front-page-keeps-showing-articles-that-are-not-sticky/
https://premium-themes.forums.wordpress.com/topic/homepage-latest-posts-2/

I don't know if you have access to see this but there's also a support ticket from the theme team here:
https://premium-review-trac.wordpress.com/ticket/7368

The issue seems to be with the `posts_per_page` property in the infinite scroll settings. The number of posts seems to always be used in all situations, however I think it should only be used when the infinite scroll type is set to `scroll`. I use the value to make the number of posts displayed larger than the height of the page. If it's shorter then the IS does not trigger. If the type is set to `click` then this is not needed.

I don't know what the old behaviour was but this is how I believe it should work.

*******

**Comment by npcommunication** [comment] 2020-08-07 10:28
It seems that the problem keeps on with 'Pictorico' theme... (and possibly with many others). 

And it's a very embarrassing problem, especially for those who have been designing the header graphics for each post in order to build a kind of 'puzzle' with at least 4 columns x 8 rows ... (or even more rows):

<a href="https://naturepress.tv/">https://naturepress.tv/</a>
<a href="https://feronianaturehouse.com/">https://feronianaturehouse.com/</a>

In my opinion, the switch button 'blog posts' (...displays 44 per page, or other quantity), in the submenu 'content types', inside the 'writing' subsection... (which belongs to the 'Manage / settings' section... has been DISABLED, on purpose:

![WP-Menu 'number of blog posts' disabled-2](https://user-images.githubusercontent.com/69346477/89636683-48c27e80-d8a9-11ea-9ed1-d73aabb59ce4.jpg)

Meanwhile, some WordPress 'happy engineers' argue that it's some kind of unwilled bug.

**Comment by aaronrobertshaw** [comment] 2020-08-10 05:32
Hi everyone, I've been investigating this issue and appreciate all the extra information and reports.

The short version of what I've found is that the loading of posts per page is happening in accordance with the information on the [Jetpack support page about adding Infinite Scroll support for themes](https://jetpack.com/support/infinite-scroll/#theme).

The relevant section of the above linked page states for the `posts_per_page` Infinite Scroll setting the following:

> By default, the type argument controls how many posts are loaded each time Infinite Scroll acts. For the scroll type, seven (7) posts are loaded each time Infinite Scroll is activated. For the click type, a site’s “Blog pages show at most” value found under Settings → Reading is used.

> If, however, a theme’s layout expects a certain number of posts, the posts_per_page argument will override the defaults discussed in the preceding paragraph. This control is beneficial, for example, in a theme with a three-column layout where greater or fewer than three posts would result in an uneven layout.

For the Pictorico theme used in the initial report, it sets the `posts_per_page` argument to 8 so the second paragraph applies and with Infinite Scroll turned on only 8 posts at a time are loaded irrespective of the general blog posts per page setting.

So to summarise:

- When selecting to "use the theme's default behaviour" and not turning on Infinite Scroll, the general blog posts per page setting is used.
- If turning on Infinite Scroll (either click or scroll types) the theme's override for the `posts_per_page` argument is always used.

I've also run a bisect to identify any changes in behavior regarding to the number of posts per page. I went back as far as March. The only change I could find in relation to this behavior came on 9 April from commit c74a43948 ( [Fix: Append all posts from IS response](https://github.com/Automattic/jetpack/pull/15368) ). This change fixed a bug where despite the correct posts being returned they were not appended to the page correctly.

It doesn't appear that the Pictorico theme's `posts_per_page` value nor the Jetpack code deciding upon the posts per page limit has changed in nearly 2 years.

Is it possible that there were settings changes on the affected sites that resulted in Infinite Scroll being turned on where it wasn't previously and thus displaying "different" numbers of posts?

@supernovia Can you confirm or add to this?

**Comment by BinaryMoon** [comment] 2020-08-10 14:08
Hi @aaronrobertshaw thanks for looking into this.

You are correct that what the docs describe is what's happening, however that is not what used to happen. _I think it used to be that the posts_per_page was only used for scroll mode, and not for click mode._

This problem is happening for me in the themes Carmack and Beacon.

I have had 4 or 5 users complain about their homepage layout changing, and I'm sure there are more who have seen the problem and haven't said anything.

You can see from the user reports [I linked](https://github.com/Automattic/jetpack/issues/16471#issuecomment-668428364) that they have checked and double checked the blog post display settings and the number isn't changing.

> Is it possible that there were settings changes on the affected sites that resulted in Infinite Scroll being turned on where it wasn't previously and thus displaying "different" numbers of posts?

afaik infinite scroll is always turned on for WordPress.com sites (possible exception is for business customers).

Note: I do not work for Automattic but I have been selling themes on WordPress.com for over 7 years now, so have a lot of experience with integrating Jetpack into themes.

**Comment by AtrumGeost** [comment] 2020-08-13 21:36
Hi folks! I got an ES user saying they won't renew their WordPress.com subscriptions on the sites that still experience this bug: 6269121-hc

**Comment by supernovia** [comment] 2020-08-13 22:24
Hi @aaronrobertshaw,

> Is it possible that there were settings changes on the affected sites that resulted in Infinite Scroll being turned on where it wasn't previously and thus displaying "different" numbers of posts?
> 
> @supernovia Can you confirm or add to this?

We don't really touch the settings for the theme demo sites at all once they're live, and it's somehow changed automatically on https://pictoricodemo.wordpress.com -- note how it's different from the snapshot here: https://wordpress.com/theme/pictorico

**Comment by dashkevych** [comment] 2020-08-14 03:45
I have a WordPress.com user who has also reported a strange behavior of Infinite Scroll: https://premium-themes.forums.wordpress.com/topic/category-does-not-show-everything/

**Comment by jeherve** [comment] 2020-08-14 07:08
@dashkevych In this case, this was most likely this issue: #16807

**Comment by aaronrobertshaw** [comment] 2020-08-21 08:15
@scruffian Any chance you might be able to shed some light on the cause of this issue?

I haven't been able to replicate anything other than the documented behaviour or pin point any change that lines up with what people have seen.

**Comment by ricjcs** [comment] 2020-09-05 15:06
In the Aquene theme (https://wordpress.com/theme/aquene) it also does not show the number of posts that I define. And it seems to have to do with this bug.

It would be good if the bug was fixed as soon as possible, I have had the site defaced for more than two months, and other users are having the same problem.

**Comment by scruffian** [comment] 2020-09-10 11:20
It looks to me like this was introduced by this PR: https://github.com/Automattic/jetpack/pull/9120

**Comment by scruffian** [comment] 2020-09-10 12:14
I have a fix here if someone could have a look: https://github.com/Automattic/jetpack/pull/17130

**Comment by scruffian** [comment] 2020-09-17 14:42
It would be great if someone could give this a review :)

**Comment by aisajib** [comment] 2020-10-07 17:14
Another WordPress.com user reported the issue on live chat as well. #20799321-hc

**Comment by susanjanec** [comment] 2020-10-13 12:31
Another WordPress.com user reported this issue - 3398143-zd

**Comment by supernovia** [comment] 2020-10-19 19:07
@scruffian anything more we can do as HEs?

**Comment by scruffian** [comment] 2020-10-19 19:09
Keep nagging @kraftbj to get https://github.com/Automattic/jetpack/pull/17130 merged I guess!

**Comment by supernovia** [comment] 2020-10-19 19:24
Thanks :D

**Closed** 2020-10-20 14:22 UTC
Labels: Infinite Scroll, [Status] In Progress, [Type] Bug, [Type] Happiness Request

**Comment by kraftbj** [comment] 2020-10-20 14:24
Available on Simple sites now, as of r215511-wpcom. On WoA and Jetpack when 9.1. ships on November 10.
