### ISSUE TITLE
Export assigns data to wrong row when fields reordered

### ISSUE THREAD

**Issue by iandunn** [Automattic/jetpack#29429] opened 2023-03-10 22:15 UTC
### Impacted plugin

Jetpack

### Quick summary

If you reorder the fields in a form, it messes up the export process, and data will be assigned to the wrong row in the CSV, and be missing from the correct row. This started in `8.0`

Possibly caused by #28678 and/or #28425, cc @CGastrell 

xref https://wordpress.slack.com/archives/C08M59V3P/p1677927125878589

### Steps to reproduce

1. Install Jetpack `11.7.1`
1. Create a contact form
1. Add two text fields; one named `text 1` and the other named `text 2`
1. Submit the form with values in both of those fields
1. Edit the form and swap the order of the two fields
1. Submit the form again
1. Export a CSV and open it. There'll be two entries for each field; e.g. `9_text1`, `9_text2`, `10_text2`, and `10_text1`, and  the data will be in the correct fields.
1. Update to Jetpack `11.8`
1. Export the CSV again and open it. There will only be a single `text1` field and a single `text2`, and there won't be any data in them.

In other situations, the data may show up, but in the wrong row. For a real-world example, check the shadow site for https://barcelona.wordcamp.org/2023/. Filter to the `llamada-a-ponentes` source, and look at the `Web` field for post ID `2604`. When exported, that value shows up in the row for a different entry.

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by liviopv** [comment] 2023-03-13 15:23
It sounds like a dupe of https://github.com/Automattic/jetpack/issues/8512

I have another report in:

- [ ] 6032809-zd-woothemes

In this case above, exported CSV shows certain fields in the wrong order, and it is missing data for some submissions.

**Comment by iandunn** [comment] 2023-03-13 17:16
I don't think this is a duplicate. It sounds like that issue is with the order of the _column headers_. This one is reporting that _data_ is missing from cells, or shows up in the wrong row.

This problem also only started a few months ago, but #8512 is much older.

**Comment by CGastrell** [comment] 2023-03-13 19:56
I'm looking into this, in the spirit of giving more clean export results we might have filtered the field names in the wrong place, causing erroneous data merging (only on export, response data is not altered).

BTW @liviopv #8512 should have been fixed already, at least that was the idea based on which the underlying cause of this issue came to be

**Closed as completed** 2023-03-14 14:43 UTC
Labels: Bug, [Feature] Forms, [Status] In Progress, [Pri] Normal, Customer Report [LEGACY], [Plugin] Jetpack, [Package] Forms

**Comment by iandunn** [comment] 2023-03-15 20:28
It looks like that fixed it, thanks!

**Comment by nuriarai** [comment] 2023-03-16 11:30
Thanks, it has fixed this problem. And now we have the previous problem but this is for report in another issue.
