### ISSUE TITLE
Likes: Invalid CSS issue causing un-necessary 404 Request

### ISSUE THREAD

**Issue by asadkn** [Automattic/jetpack#7435] opened 2017-07-06 23:31 UTC
I noticed Jetpack was causing a 404 HTTP request. This line in css/jetpack.css seems to be causing it:

`@font-face{font-family:"Open Sans";src:url('"https://fonts.googleapis.com/css?family=Open+Sans"')}
`

It seems like it's from modules/likes/style.css even though it's properly formatted there. It's probably related to build system.

**Comment by danjjohnson** [comment] 2017-07-07 08:58
Also reported here:
https://wordpress.org/support/topic/jetpack-css-404-error-in-site-statistics/

And in 3310395-t

**Comment by codestor4** [comment] 2017-07-07 12:07
3309853-t

Someone shared a quick fix on the link shared by @danjjohnson 
https://wordpress.org/support/topic/jetpack-css-404-error-in-site-statistics/

Quick fix until JetPack issues a patch: remove the offending line from the file `wp-content/plugins/jetpack/css/jetpack.css`, i.e. remove line
`@font-face{font-family:”Open Sans”;src:url(‘”https://fonts.googleapis.com/css?family=Open+Sans”‘)}`

And add a line in your header `(in the <head></head> section)` saying
`<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">`

**Comment by seejacobscott** [comment] 2017-07-07 17:32
Also reported here: 3311161-t

**Comment by madhattermattic** [comment] 2017-07-07 20:52
Also reported here: 3311033-t

**Comment by madhattermattic** [comment] 2017-07-07 21:23
And in 3311085-t

**Comment by Ne0Logic** [comment] 2017-07-08 10:45
@codestor4 yep that was me. I'm not a css expert though, so I'm not sure what the permanent fix would have to be.

**Comment by seejacobscott** [comment] 2017-07-08 18:38
reported here: 3313062

**Comment by pmciano** [comment] 2017-07-09 16:59
Seeing errors here 3311730-t

**Comment by pmciano** [comment] 2017-07-10 13:27
Reported 3312581-t

**Comment by codestor4** [comment] 2017-07-10 16:03
3313123-t

**Comment by keizha** [comment] 2017-07-10 17:15
just try this : 
https://wordpress.org/support/topic/jetpack-css-404-error-in-site-statistics/page/2/#post-9305851

**Comment by kraftbj** [comment] 2017-07-10 21:16
I don't think we need to continue to report impacted users. The cause is known and we should advise folks it'll be fixed in an upcoming release.

**Comment by kraftbj** [comment] 2017-07-19 18:59
@kvibber Thanks for the report. I hadn't heard that particular symptom of this. I've upgraded this and the patch to `blocker` status to ensure we get it in the next release.

**Closed** 2017-07-24 15:47 UTC
Labels: Likes, [Pri] BLOCKER, [Type] Bug
