### ISSUE TITLE
Width bug on .com sites, not on .org

### ISSUE THREAD

**Issue by lizkarkoski** [Automattic/jetpack#14140] opened 2019-11-27 19:44 UTC
Originally reported by @supernovia . I have copied that report from October 21st 2019 here for visibility. 

Original posting at our video p2 press internal blog. 

Check this out. If you specify a width on a .com site, the width gets ignored. The height gets adjusted. The preview image, if there is one, gets stretched horizontally and is cropped to fit.

This happens in multiple themes on .com, and it doesn't matter whether I use classic or block editor:

If I use the same theme on a Pressable installation, I don't have an issue. Any ideas?

I'm using the following shortcode (add your own brackets since this broke here)
videopress CuC7pb3G w=400

Noting this was brought up here: https://en.forums.wordpress.com/topic/videopress-video-width/

Some of us see the issue here on Mac: https://en.support.wordpress.com/videopress/

**Comment by jeherve** [comment] 2019-11-28 08:00
Closing as duplicate of 8181-wpcom.

**Closed by jeherve** 2019-11-28 08:00 UTC
Labels: [Type] Duplicate
