### ISSUE TITLE
Slideshow block: SVG icons don't show reliably in different contexts

### ISSUE THREAD

**Issue by mirka** [Automattic/jetpack#28254] opened 2023-01-10 12:10 UTC
### Impacted plugin

Jetpack

### Steps to Reproduce

For easy testing, choose a theme that shows a good chunk of the post excerpts on the home page, such as Twenty Fifteen or Twenty Twenty.

1. In the editor, add the Slideshow block to a post. The arrow icons are **not visible**.
2. Publish the post.
3. On the front end, go to the permalink page for the post. The arrow icons are **visible**.
4. On the front end, go to the home page of the site, where the slideshow should be visible in the post excerpt. The arrow icons are **not visible**.

### A clear and concise description of what you expected to happen.

The arrow icons should be visible.

### What actually happened

<img width="400" alt="Arrow icons are not visible" src="https://user-images.githubusercontent.com/555336/211544038-f061785e-713d-4fc1-9518-65fb9af7fde5.png">

### Other information

The issue seems to have been introduced in #27907, where the data URI for the SVG now includes a fragment identifier:

```html
<mask id="maskNext" mask-type="alpha" maskUnits="userSpaceOnUse" x="8" y="6" width="8" height="12">
<!-- snipped -->
<g mask="url(#maskNext)">
```

I'm not exactly sure why, but this identifier does not reliably work in all contexts. In the editor and on the home page, if you check devtools you can see that the data URI renders the `url()` as:

```html
<g mask='url(/wp-content/mu-plugins/jetpack-plugin/production/_inc/blocks/slideshow/#a)'>
```

and this prevents the browser from finding the correct fragment. Perhaps some backend filter is mangling the identifiers?

cc @lhkowalski

Reported in 5850657-zd-woothemes

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

**Comment by jeherve** [comment] 2023-01-10 14:14
cc @lhkowalski Could you take a look at this?
Thanks!

**Comment by jordesign** [comment] 2023-01-11 02:33
I've confirmed this with another user in 39260709-hc - however they don't need following up.

Site: https://akvhs.org/services/
Theme: Geologist
Simple Site

**Comment by sophiegyo** [comment] 2023-01-12 10:53
It also happens with the pause button when the slideshow's set to autoplay - the SVG is broken there too.

Example from Simple wpcom site using Sketch theme (classic, not FSE):
<img width="597" alt="image" src="https://user-images.githubusercontent.com/36608681/212047922-e0bf8f8c-2b30-4cf8-ba67-e8505736755e.png">

Example from my own Simple wpcom site using Antonia theme (FSE):

<img width="862" alt="image" src="https://user-images.githubusercontent.com/36608681/212048148-e8e4933c-79d6-406d-bca5-4ba31cee8532.png">

It came to my attention because the user's having trouble seeing the pause button when their images don't cover the slideshow area:
https://wordpress.com/forums/topic/photo-gallery-it-used-to-be-a-photo-column-of-4/?view=all

**Comment by zdenys** [comment] 2023-01-20 07:12
This is affecting the internal P2s too. See here: p7DVsv-gfF-p2

![kaCDTJ.png](https://user-images.githubusercontent.com/39308239/213638175-998fca98-8676-40de-a704-348940f25887.png)

**Comment by obenland** [comment] 2023-01-31 09:00
Duplicate of https://github.com/Automattic/wp-calypso/issues/71453

**Closed as not planned by obenland** 2023-01-31 09:00 UTC
Labels: Bug, [Pri] Low, [Block] Slideshow, Customer Report [LEGACY], [Plugin] Jetpack, [Platform] Simple, Needs triage
