### ISSUE TITLE
Don't show the [xx more words] on Facebook if the user has a custom excerpt

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#508] opened 2014-05-02 14:13 UTC
This was requested in the following thread:

http://wordpress.org/support/topic/how-do-i-remove-xx-more-words?replies=7#post-5525436

In [this Facebook post](https://www.facebook.com/permalink.php?story_fbid=10152035610981867&id=270213811866&stream_ref=10) we see that there is an excerpt and then the mention of [109 more words]. If the user has a custom excerpt, should we show the word length for the full post?

**Comment by jeherve** [comment] 2015-07-10 17:15
Closing as duplicate of #1183

**Closed by jeherve** 2015-07-10 17:15 UTC
Labels: enhancement, Publicize, Team Partnerships

**Comment by Moridin3335** [comment] 2015-07-27 12:14
We're using the `<!--more-->` tag and we're seeing the [ xx more words. ] on our Facebook posts.

Link to example post: http://imagazine.pl/2015/07/26/znajdowanie-hasla-sieci-wi-fi-z-terminala/
Link to Facebook post: https://www.facebook.com/iMagazinePL/posts/1029080970458119
Screenshot:
<img width="488" alt="screen shot 2015-07-27 at 14 13 42" src="https://cloud.githubusercontent.com/assets/1881957/8905819/ba79abdc-3469-11e5-8525-6b8d38abcbc3.png">

How do we get rid of the [ xx more words. ] message?

**Comment by sheilaburke** [comment] 2016-04-22 16:32
Hello, has a fix ever been found for this?  (getting rid of xx more words and replacing with "Read More" or something similar?)   Thank you :)

**Comment by jeherve** [comment] 2016-04-22 16:51
@sheilaburke We don't have a fix yet, but you can follow our progress in #1183
