### ISSUE TITLE
AI Assistant: Featured Image Generator Shows Navigation Options when Previous/Next Images Don't Exist

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/jetpack#37833] opened 2024-06-12 21:00 UTC
### Impacted plugin

Jetpack

### Quick summary

When using the Featured Image Generator, the previous/next image controls show when one doesn't exist

### Steps to reproduce

1. Open the Featured Image Generator
2. As the image generates, see that the swiper controls for previous/next appear even though there are no previous/next options

### A clear and concise description of what you expected to happen.

I would expect the controls only show when relevant

### What actually happened

![Annotation on 2024-06-12 at 16-57-26](https://github.com/Automattic/jetpack/assets/45246438/beb51dcd-ac82-4882-8f28-f0001b41fc38)
![Annotation on 2024-06-12 at 16-57-53](https://github.com/Automattic/jetpack/assets/45246438/ebff6e7a-1f08-4841-b971-8eaa98466226)

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by BogdanUngureanu** [comment] 2024-08-13 14:13
Closing this since it's no longer reproducing.

**Closed as completed by BogdanUngureanu** 2024-08-13 14:13 UTC
Labels: Bug, [Pri] High, [Plugin] Jetpack, Triaged, [Status] Priority Review Triggered, [Extension] AI Assistant
