### ISSUE TITLE
Subscriptions: Show Image when in Subscription Emails when Excerpts Enabled

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/jetpack#19888] opened 2021-05-19 14:22 UTC
#### Is your feature request related to a problem? Please describe.

When the Subscriptions feature is set to use excerpts (via Reading > For each post in a feed, include > Summary), images are dropped from the auto-generated excerpt.

#### Describe the solution you'd like

Before the excerpt is displayed, the first image to appear in the post should be displayed.

**Comment by jeherve** [comment] 2021-05-19 14:26
Closing as duplicate of #2957.

**Closed by jeherve** 2021-05-19 14:26 UTC
Labels: Involves Happiness, Subscriptions, [Type] Feature
