### ISSUE TITLE
WordPress 5.8: Image Compare Block Not Working in Site Editor

### ISSUE THREAD

**Issue by bizanimesh** [Automattic/jetpack#20215] opened 2021-06-29 16:09 UTC
I have:

- WordPress Version: 5.8-beta4
- Jetpack Version: 9.9-beta-983222196-g76ef471
- Gutenberg plugin installed
- Jurassic Ninja site

#### Steps to reproduce the issue

1. Go to WP Admin area and click _Site Editor_ from the left sidebar.

<img width="313" alt="Markup 2021-06-29 at 21 18 52" src="https://user-images.githubusercontent.com/52444539/123828972-a88da200-d91f-11eb-9410-0abcea7c756a.png">

2. Add _Image Compare_ Block.

<img width="476" alt="Markup 2021-06-29 at 21 21 23" src="https://user-images.githubusercontent.com/52444539/123829422-133edd80-d920-11eb-8fb8-a76f05ba85ee.png">

As you will add the block, you will see this error: _This block has encountered an error and cannot be previewed._

<img width="431" alt="Markup 2021-06-29 at 21 24 47" src="https://user-images.githubusercontent.com/52444539/123829938-7cbeec00-d920-11eb-97b1-ba4867b2ac61.png">

I got the same error with WordPress _Image_ Block also. Nothing changes even if I deactivated the Jetpack plugin. I'm not sure if the error is coming from WordPress.

One more thing to notice is: You will not get the same above error if you will try adding _Image Compare_ or _Image_ Blocks by going to _Posts > All Posts > Edit_ or _Add New_ post in WP Admin.

<img width="512" alt="Markup 2021-06-29 at 21 34 24" src="https://user-images.githubusercontent.com/52444539/123831837-5b5eff80-d922-11eb-8339-90bf8358a360.png">

Let me know if more information needed!

**Comment by bizanimesh** [comment] 2021-06-29 16:36
Primary issue: #19654

**Comment by jeherve** [comment] 2021-06-29 17:49
Thanks for the report. Closing this as a duplicate of #20184, where we're tracking this issue.

**Closed by jeherve** 2021-06-29 17:49 UTC
Labels: Full Site Editing, [Block] Image Compare, [Pri] Normal, [Type] Bug
