### ISSUE TITLE
Sharing buttons: "Customize buttons" unstyled when using AMP Standard

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/jetpack#16732] opened 2020-08-05 17:51 UTC
#### Steps to reproduce the issue

1. On a test site running Twenty Twenty and the latest version of Jetpack (8.8), install and activate the [AMP](https://wordpress.org/plugins/amp/) plugin.
2. Navigate to WP Admin > AMP, and set it to use "Transitional" mode (to make it easier to toggle between the AMP and non-AMP versions of the page).
3. Enable Sharing buttons on your posts.
4. View a non-AMP version of a post and note the appearance of the 'Customize buttons' link -- it's been styled to be smaller and a serif font.
5. Click the "AMP" link in the Admin Toolbar to switch to the AMP version of the post; note the appearance of the 'Customize buttons' link.

#### What I expected
That the 'Customize buttons' link would appear the same.

#### What happened instead
The 'Customize buttons' no longer has any special styles, and is picking up the body font size and family. 

**Screenshots**
Non-AMP version of the page:

![image](https://user-images.githubusercontent.com/177561/89446344-46292300-d709-11ea-9fbb-e7c70a292064.png)

AMP version of the page: 

![image](https://user-images.githubusercontent.com/177561/89446374-4de8c780-d709-11ea-884f-d135164ac640.png)

**Comment by jeherve** [comment] 2020-08-05 17:58
Related: #16472

cc @blackjackkent Maybe we should hide that link altogether on AMP views (we can check that with something like `class_exists( 'Jetpack_AMP_Support' ) && Jetpack_AMP_Support::is_amp_request()`)? I'm not sure what's best here.

**Comment by danjjohnson** [comment] 2021-01-27 12:32
Just noting that we have had a couple of requests about removing the link entirely:

- https://wordpress.org/support/topic/how-to-remove-customize-buttons-text/
- https://wordpress.org/support/topic/remove-customize-buttons-from-share-on-front-end/

Currently custom CSS is the only option for that. Would it be worth providing a filter?

**Comment by jeherve** [comment] 2021-01-27 17:24
> Would it be worth providing a filter?

We can always add in a filter, sure. 👍

**Comment by fditrapani** [comment] 2024-12-17 16:05
This issue is more than 3 years old and has had very little movement. While the issue is valid it's not critical to the experience. I doubt people will be comparing the two. I'm going to close this for now. If someone feels compelled to open it and work on it, please do.

**Closed by fditrapani** 2024-12-17 16:05 UTC
Labels: [Type] Bug, [Feature] Sharing, [Pri] Low, AMP
