### ISSUE TITLE
<span>%d</span> Appearing at the Start of "bloggers like this" List

### ISSUE THREAD

**Issue by macmanx2** [Automattic/jetpack#19668] opened 2021-04-27 18:51 UTC
#### Steps to reproduce the issue

1. Go to any post with Likes, like https://wordpress.com/blog/2021/04/19/introducing-a-new-design-for-the-wordpress-apps/
2. Click on "You and [number] other bloggers like this."
3. See error

#### What I expected

"[number] bloggers like this"

#### What happened instead

<img width="354" alt="Screen Shot 2021-04-27 at 11 50 10 AM" src="https://user-images.githubusercontent.com/4856235/116296176-bf145300-a74e-11eb-931e-c98e83671fb4.png">

@leogermani was able to identify the issue at both https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/modules/likes/jetpack-likes-master-iframe.php#L33 and the mirrored code in wpcom.

originally reported via https://wordpress.com/forums/topic/all-themes-d-bloggers-like-this/

**Comment by leogermani** [comment] 2021-04-27 19:14
Looks like a regression introduced by https://github.com/Automattic/jetpack/pull/19221/files

**Comment by sdixon194** [comment] 2021-04-27 22:37
Got a fix for this that should be able to get reviewed and out soon 👍 

Code was specific to wpcom. Just something that was escaped _too_ much.

**Comment by kraftbj** [comment] 2021-04-28 16:45
Fixed via r224926-wpcom

**Closed by kraftbj** 2021-04-28 16:45 UTC
Labels: Likes, [Type] Bug
