### ISSUE TITLE
Subscriptions Block: padding is not applied as expected

### ISSUE THREAD

**Issue by mashikag** [Automattic/jetpack#25268] opened 2022-07-26 10:46 UTC
### Impacted plugin

Jetpack

### Steps to Reproduce

1.  Go to post editor
2. Add subscription block
3. Choose `Padding` under`Dimensions` Block settings
4. Apply 100px left and right padding
![Screenshot 2022-07-26 at 12 32 53](https://user-images.githubusercontent.com/2019970/180986037-577ecce4-f32e-445b-8ac2-118fd76a0d1d.png)
5. Notice how the block is back in its original position and width. Seems like there is no padding applied to the block.

### A clear and concise description of what you expected to happen.

For the right and left padding be applied to the subscribe block. Causing the block to get squeezed 100px from left and 100px from right.

Expected to see this in editor (created with chrome dev tools):
![Screenshot 2022-07-26 at 12 41 44](https://user-images.githubusercontent.com/2019970/180987729-77ec0225-cbcc-4c6a-9036-e6792ddaac75.png)

### What actually happened

The block is back in its original position as if no padding was set. Only once the block is re-selected it is sort of visible that the block became wider (this should not be the case) hence the padding is actually applied but not in the way a user expects.

###### Before padding applied
![Screenshot 2022-07-26 at 12 40 44](https://user-images.githubusercontent.com/2019970/180988040-d92e09fa-a6cb-45bb-a78a-76eceae6ec5e.png)

###### After padding applied
![Screenshot 2022-07-26 at 12 40 22](https://user-images.githubusercontent.com/2019970/180987849-328d9090-b5da-41aa-a2d8-7cafd4b94b72.png)

Notice in the above screenshots how the position relative to the rest of the page content, i.e. relative to title, is the same with and without right and left padding applied.

### Browser

Google Chrome/Chromium

### Other information

Tested with theme: Twenty Twenty-Two

https://user-images.githubusercontent.com/2019970/180984601-51f5aabe-bd80-4a76-a280-f3f8c2b1013b.mp4

### Reproducibility

Consistent

**Comment by ivan-ottinger** [comment] 2022-10-18 12:38
We investigated this issue with @JuanLucha today and couldn't reproduce it anymore. The padding is properly applied in both editor and published post. We tested with multiple themes (including Twenty Twenty-Two) and on Simple, Atomic and Jetpack-connected site.

![Markup on 2022-10-18 at 14:27:21](https://user-images.githubusercontent.com/25105483/196429303-35b68d4b-6f46-4ed3-9346-71d4798e7b59.png)

→ We are closing this issue.

**Closed as not planned by ivan-ottinger** 2022-10-18 12:38 UTC
Labels: Bug, [Pri] Normal, [Block] Subscribe, [Plugin] Jetpack, Apex
