### ISSUE TITLE
Jetpack causing wp database errors

### ISSUE THREAD

**Issue by Fengist** [Automattic/jetpack#13606] opened 2019-10-01 03:44 UTC
Massive debug log spam from apparently jetpack.

https://pastebin.com/vkHfr0DT

**Comment by jeherve** [comment] 2019-10-01 09:19
For future reference, those errors all look like this:

```
WordPress database error Commands out of sync; you can't run this command now
```

I can't seem to reproduce on my end, so I wonder if this may be caused by another plugin on your site that may conflict with other plugins doing database queries. Could you try to deactivate each one of your plugins, one at a time, and see if the errors disappear when you deactivate a specific plugin?

Thank you.

**Comment by Fengist** [comment] 2019-10-01 12:30
I'm certain it's a conflict. It's with a plugin I'm developing that makes extensive use of wp_cron and a lot of queries.  The questions are, why is this conflict with jetpack arising and how can it be prevented?

**Comment by jeherve** [comment] 2019-10-01 15:29
> why is this conflict with jetpack arising and how can it be prevented?

That's hard to say without knowing more about your plugin. The SQL queries mentioned in your logs happen quite often on Jetpack sites, which is why you see them there.

In your plugin, do you use the `wpdb` Class and the tools that come with it, including `prepare`?

**Comment by Fengist** [comment] 2019-10-02 12:20
Exclusively. wpdb->update, wpdb->delete, wpdb->get_results, etc.  I am using some outside resources so to double check I just did a search of the entire project looking for direct mysql or mysqli queries or connections and found nothing.

**Comment by Fengist** [comment] 2019-10-07 01:06
So far, so good.  Been running thousands of queries and with the switch to InnoDB, no butting heads with jetpack.

**Comment by jeherve** [comment] 2019-10-07 07:14
Closing this issue for now, do not hesitate to comment again if needed.

**Closed by jeherve** 2019-10-07 07:14 UTC
Labels: Sync, [Status] Needs Author Reply
