### ISSUE TITLE
Contact form does not pass on non-required/extra fields in email

### ISSUE THREAD

**Issue by arjenlentz** [Automattic/jetpack#7152] opened 2017-05-08 23:52 UTC
Contact form does not pass on non-required/extra fields in email. I don't know whether it's about required fields of extra fields or some other piece of the logic inside the Jetpack contact form code.

Here's the actual form data from the site:
`
[contact-form to='<site email addr>' subject='Inquiry: {Subject}'][contact-field label='Name' type='name' required='1'/][contact-field label='Position' type='text'/][contact-field label='Organisation (school)' type='text'/][contact-field label='City' type='text'/][contact-field label='Email' type='email' required='1'/][contact-field label='Phone number' type='text'/][contact-field label='Subject' type='text' required='1'/][contact-field label='Message' type='textarea' required='1'/][/contact-form]`

Yep I realise there's spaces in some of the labels, or other characters such as (), however since there's no distinction between the text shown to users and the field label, I can't help that. Given that that is the case, I presume that to work ok.
In any case, the fields Position, Organisation (School), City and Phone number fields do not show up in the email sent. Nor the Subject field, actually!
All fields show up in the Feedback tab on the WP site Admin pages.

#### Steps to reproduce the issue

Add an extra non-required field, for instance "Organisation".

#### What I expected

Should show up in email went the form is submitted.

#### What happened instead

It doesn't show up.
Only the basic fields (Name, email, and main text content) show up in the email. Subject doesn't either, actually.

**Comment by arjenlentz** [comment] 2017-05-08 23:59
This is another form with the same effects. Note that here Organisation doesn't have () and it still doesn't work, so that might not be a factor anyhow. There are still field labels that contain a space.

`[contact-form to='<site email addr>' subject='<fixed topic text>'][contact-field label='Name' type='name' required='1'/][contact-field label='Position' type='text'][contact-field label='Organisation' type='text'][contact-field label='City' type='text'][contact-field label='Email' type='email' required='1'/][contact-field label='Phone number' type='text'/][contact-field label='Additional info' type='textarea'/][/contact-form]`

**Comment by jeherve** [comment] 2017-05-09 13:59
I can't seem to be able to reproduce the issue on my end, when using the shortcode you posted above, whether I submit the form when logged in or logged out. Whether I enter data into the non-required fields or not, the fields are part of the emails I receive:

![451d3b7212d2b6957838743fa0e874bd _screen shot 2017-05-09 at 15 55 49](https://cloud.githubusercontent.com/assets/426388/25854416/30d99ea0-34d0-11e7-900b-9c7c5c615829.png)
![cb395413ea7cff45caa7f9163269db3d _screen shot 2017-05-09 at 15 56 42](https://cloud.githubusercontent.com/assets/426388/25854421/33128218-34d0-11e7-8249-d3e199dae6ae.png)

Do you happen to use the W3 Total Cache plugin or another caching plugin on your site? If so, what happens if you disable the database cache option? Does it change anything?

Possibly related to #5629

**Comment by arjenlentz** [comment] 2017-05-10 01:23
I think you're probably right, @jeherve . Good catch!
However, turning off db caching on busy sites is not an option.
So I'll just have to shift to using another plugin to handle contact forms. Pity.

**Comment by jeherve** [comment] 2017-05-10 10:58
Closing as duplicate of #5629

**Closed** 2017-05-18 11:48 UTC
Labels: Contact Form, [Type] Duplicate
