### ISSUE TITLE
WP-ADMIN -> JS Error -> Uncaught ReferenceError: tinymce is not defined

### ISSUE THREAD

**Issue by michael-ecklund** [Automattic/jetpack#9812] opened 2018-06-22 14:51 UTC
#### Steps to reproduce the issue

Visit Dashboard.

#### What I expected

Page to load properly.

#### What happened instead

Admin page is broken due to JS error. Things fail to load because of this.

**Error:**
`Uncaught ReferenceError: tinymce is not defined
    at HTMLDocument.<anonymous> ((index):2865)
    at i (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-widget,jquery-ui-core,jquery-ui-mouse,jquery-ui-sortable,underscore,wp-util,thickbox,&load[]=jquery-ui-draggable,jquery-ui-slider,jquery-touch-punch,iris,wp-color-picker,backbone,wp-api-request,wp-backbone,media-models,mo&load[]=xiejs,plupload,wp-plupload&ver=218f73c4f2a960bbc03a54ecf2b60768:2)
    at Object.fireWith [as resolveWith] (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-widget,jquery-ui-core,jquery-ui-mouse,jquery-ui-sortable,underscore,wp-util,thickbox,&load[]=jquery-ui-draggable,jquery-ui-slider,jquery-touch-punch,iris,wp-color-picker,backbone,wp-api-request,wp-backbone,media-models,mo&load[]=xiejs,plupload,wp-plupload&ver=218f73c4f2a960bbc03a54ecf2b60768:2)
    at Function.ready (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-widget,jquery-ui-core,jquery-ui-mouse,jquery-ui-sortable,underscore,wp-util,thickbox,&load[]=jquery-ui-draggable,jquery-ui-slider,jquery-touch-punch,iris,wp-color-picker,backbone,wp-api-request,wp-backbone,media-models,mo&load[]=xiejs,plupload,wp-plupload&ver=218f73c4f2a960bbc03a54ecf2b60768:2)
    at HTMLDocument.K (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-widget,jquery-ui-core,jquery-ui-mouse,jquery-ui-sortable,underscore,wp-util,thickbox,&load[]=jquery-ui-draggable,jquery-ui-slider,jquery-touch-punch,iris,wp-color-picker,backbone,wp-api-request,wp-backbone,media-models,mo&load[]=xiejs,plupload,wp-plupload&ver=218f73c4f2a960bbc03a54ecf2b60768:2)`

**Code:**
`jQuery( function() {
	tinymce.on( 'AddEditor', function( event ) {
		event.editor.on( 'BeforeSetContent', function( event ) {
			var editor = event.target;
			Object.keys( editor.schema.elements ).forEach( function( key, index ) {
				editor.schema.elements[ key ].attributes['markdown'] = {};
				editor.schema.elements[ key ].attributesOrder.push( 'markdown' );
			} );
		} );
	}, true );
} );`

**Specific line:**
`tinymce.on( 'AddEditor', function( event ) {`

**Comment by dereksmart** [comment] 2018-06-26 13:35
Thanks for reporting! Duplicate of #9761

We'll have it fixed in the next release.

**Closed by dereksmart** 2018-06-26 13:35 UTC
Labels: [Type] Duplicate
