### ISSUE TITLE
"Connect your social media accounts" link goes to wrong place. Customers currently can't set this feature up.

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#12937] opened 2019-07-03 13:12 UTC
Related issue: https://github.com/Automattic/jetpack/issues/12929

### Two screen recordings of the issues so you can see everything outlined below

https://cloudup.com/cMk0sheXxEf

### 1) In Jetpack: "Connect your social media accounts" link goes to wrong place. Customers currently can't set this feature up.

When a customer clicks "Connect your social media accounts" link in the jetpack settings within wp-admin they're taken to https://wordpress.com/stats/day. They become lost and cannot get to the place they need to.

I actually can't even get to the page I need to either.

![Screen Shot 2019-07-02 at 5 28 50 PM](https://user-images.githubusercontent.com/214813/60548415-087cee00-9cf0-11e9-87b1-1e530b19b0c8.png)

![Screen Shot 2019-07-02 at 5 29 03 PM](https://user-images.githubusercontent.com/214813/60548429-10d52900-9cf0-11e9-9b5a-c0fb44662543.png)

**Comment by jeffgolenski** [comment] 2019-08-16 14:53
Any movement on this?

**Comment by jeherve** [comment] 2019-08-19 16:15
That's an old issue I'm afraid. It impacts Publicize, but also all other screens in Calypso. It happens when you've just connected your site to WordPress.com, and then try to access Calypso before sync is fully triggered. If you wait a couple of minutes, the issue disappears.

cc @oskosk who will know more.

**Comment by dereksmart** [comment] 2019-08-20 21:03
It's mostly fixed via https://github.com/Automattic/wp-calypso/pull/35626

The problem at the root is how calypso gets its data. It first loads the route, then queries the cached site to see if the module is active. The problem is that the controller depends on logic from the query, and by the time it queries it's too late. 

That Calypso PR will ensure that you land on the correct Calypso route, and the queried shadow data will eventually populate the publicize card there.

**Closed by dereksmart** 2019-08-20 21:03 UTC
Labels: Sync, [Pri] High, [Type] Bug
