### ISSUE TITLE
Publicize Facebook Settings Selector Not Showing More than Twenty-Five Pages

### ISSUE THREAD

**Issue by sageBrownell** [Automattic/jetpack#7928] opened 2017-10-03 21:19 UTC
The settings to connect Jetpack to Facebook with Publicize only show twenty-five pages. That doesn't help if the user has more pages than that, because they aren't able to find the right page if it isn't included in that first twenty-five.

714702-zen

**Comment by jeherve** [comment] 2017-10-04 10:02
Closing as duplicate of #1659

**Closed by jeherve** 2017-10-04 10:02 UTC
Labels: Publicize, [Pri] Normal
