### ISSUE TITLE
Latest Instagram Posts: add lazy loading

### ISSUE THREAD

**Issue by rsmith4321** [Automattic/jetpack#23601] opened 2022-03-24 17:04 UTC
### Impacted plugin

Jetpack

### What

Instagram Lazyload

### How

Can you please make the Instagram block have loading=lazy added to the images.

**Comment by jeherve** [comment] 2022-03-24 17:17
Closing as duplicate of #19086.

**Closed by jeherve** 2022-03-24 17:17 UTC
Labels: [Type] Enhancement, [Block] Latest Instagram Posts, [Plugin] Jetpack
