### ISSUE TITLE
Old links to http://jetpack - need to be updated to https://

### ISSUE THREAD

**Issue by edent** [Automattic/jetpack#3714] opened 2016-04-22 11:30 UTC
#### What I expected
All links should point to the http**s** version where available.

#### What happened instead
Many links point to the http version of the site.

While the connection is often upgraded, it would be helpful to users to know that their communications with the site are secure.

#### Steps to reproduce the issue
Look for links which point to http://jetpack.com

**Comment by jeherve** [comment] 2016-04-22 12:20
Closing as duplicate of #3704

**Closed by jeherve** 2016-04-22 12:20 UTC
