### ISSUE TITLE
Tiled Gallery Images Skewed after Older Posts Button

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/jetpack#12494] opened 2019-05-29 20:30 UTC
The Tiled Gallery images are skewed on the Home page if they display after the `Older Posts` button and use either the **Tiled Columns** or **Tiled Mosaic** styles.

I have seen this with my test site on *The Four* and *Twenty Nineteen*, so I don’t think it is theme specific.

#### Steps to reproduce the issue

1. Set theme to Twenty Nineteen 
2. Go to **Customize > Homepage Settings** and set to **Your Latest Posts** 
3. Open an existing post and modify the publish date so it is older than the first 10 posts.
4. Add a Tiled Gallery to the post and set Style to **Tiled Columns** 
5. Save Post
6. View home page and scroll down and click `Older Posts`

#### What I expected
I expected the Tiled Gallery to look like this:

![screenshot](https://cld.wthms.co/wPhqvV+)

#### What happened instead
The Tiled Gallery looked like this:
![screenshot](https://cld.wthms.co/e9tUpW+)

Related ticket: 2067310-zen

**Comment by jeherve** [comment] 2019-05-29 20:33
closing as duplicate of #12453

**Closed by jeherve** 2019-05-29 20:33 UTC
Labels: [Type] Duplicate, [Type] Happiness Request
