### ISSUE TITLE
My Jetpack: Action Button misaligned 

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#22825] opened 2022-02-11 23:01 UTC
A little regresion here 
![image](https://user-images.githubusercontent.com/746152/153682137-36a2b489-f751-4951-b470-279722a77768.png)

**Comment by renatoagds** [comment] 2022-02-17 19:06
Could not reproduce. Closing it

**Closed by renatoagds** 2022-02-17 19:06 UTC
Labels: [Type] Bug, [Package] My Jetpack
