### ISSUE TITLE
"Best Day So Far" stats displaying code instead of number

### ISSUE THREAD

**Issue by gsmumbo** [Automattic/jetpack#11473] opened 2019-03-03 18:17 UTC
## Summary
Instead of displaying a number, the stats under "Best Day So Far" are displaying `%(number)` when the site's language is Polish:

<img width="1439" alt="pastedgraphic-1" src="https://user-images.githubusercontent.com/3220181/53699452-6affc500-3db6-11e9-8f6e-513d5ff8b4ea.png">

1848049-zen

**Comment by kraftbj** [comment] 2019-03-04 22:32
@gsmumbo I confirmed the issue when setting the site language to Polish and so moving it over here from an internal repo as a bug.

**Comment by jeherve** [comment] 2019-03-04 22:35
Closing as duplicate of #9783

**Closed by jeherve** 2019-03-04 22:35 UTC
Labels: Admin Page, Internationalization, Stats, [Type] Bug, [Type] Duplicate
