### ISSUE TITLE
Instant Search: date filters are sometimes improperly formatted 

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#13811] opened 2019-10-22 21:46 UTC
#### Steps to reproduce the issue

1. Follow instructions in https://github.com/Automattic/jetpack/pull/13761 to get search running
2. Filter jetpack.com site by "security" post type (with no search query)
3. The yearly filters will look like:

<img width="457" alt="Screen Shot 2019-10-22 at 1 53 08 PM" src="https://user-images.githubusercontent.com/820871/67336700-0a5aff00-f4e3-11e9-8923-63cbd764d4a1.png">

**Comment by jsnmoon** [comment] 2019-10-28 18:49
@gibrown I'm having trouble reproducing the bug on the latest `instant-search-master`. 

<img width="325" alt="Screen Shot 2019-10-28 at 12 46 36 PM" src="https://user-images.githubusercontent.com/4044428/67708157-4974ce80-f981-11e9-928a-870d82fdabc1.png">


What's the filter definition for the year filter specified above? Date, Date GMT, Modified, or Modified GMT?

**Comment by bluefuton** [comment] 2019-10-28 23:06
I'm also not able to reproduce this with any permutation of the date fields:

<img width="329" alt="Screen Shot 2019-10-29 at 12 03 01" src="https://user-images.githubusercontent.com/17325/67724603-6de5af00-fa44-11e9-9431-e05199b64e25.png">

I'll close this for now. Let us know if you see it happen again @gibrown 🙂

**Comment by gibrown** [comment] 2019-10-29 01:03
Does it not happen for you on http://gibrown.wpsandbox.me/demo/ either?

![Screen Recording 2019-10-28 at 6 57 23 PM 2019-10-28 19_02_44](https://user-images.githubusercontent.com/820871/67729164-a7bba480-f9b5-11e9-9539-9b47e3df3d0a.gif)

**Comment by bluefuton** [comment] 2019-10-29 01:47
It does happen there. Is it definitely up to date with `instant-search-master`? If so, is there anything special about the widget setup on `gibrown.wpsandbox.me`?

**Closed** 2020-01-21 20:16 UTC
Labels: Instant Search, Search, [Type] Bug
