### ISSUE TITLE
Facebook Login Doesn't Work in Jetpack Comments

### ISSUE THREAD

**Issue by muffinpeace** [Automattic/jetpack#22698] opened 2022-02-07 08:50 UTC
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Install, activate and connect the latest Jetpack release.
2. Make sure comments are activated.
3. Activate the option for visitors to use WordPress.com, Google, Twitter, or Facebook to comment (Jetpack Settings > Discussion).
4. Try commenting using Facebook

### A clear and concise description of what you expected to happen.

Being able to comment using the Facebook account.

### What actually happened

Nothing happens and the page only does animation as if it loaded. An error is also shown in the console: Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings

### Other information

This was initially received on 4751158-zen and I've been able to reproduce that on my end.

### Browser

Firefox

**Comment by jeherve** [comment] 2022-02-07 08:57
Thanks for the report! That seems to be new. For reference, here is the full error:

```json
{
   "error": {
      "message": "Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.",
      "type": "OAuthException",
      "code": 191,
      "fbtrace_id": "AyGDq-JvegnrjwQ-FfkybGv"
   }
}
```

**Comment by jeherve** [comment] 2022-02-07 09:01
cc @renanferrari Could this be linked to the recent changes you made to the app settings, as part of pbArwn-3xe-p2?

**Comment by renanferrari** [comment] 2022-02-07 19:35
Hey @jeherve, thanks for the ping! Looking at the error message above, it does seem related. 

For reference, here's how this issue was addressed on the backend: r238579-wpcom

**Comment by jeherve** [comment] 2022-02-08 08:28
Thanks for the extra details!

cc @pablinos, who worked on that change.

**Comment by pablinos** [comment] 2022-02-08 21:43
I think D74630-code should fix it.

**Comment by philnick206** [comment] 2022-02-09 11:32
Reported here: #4761250-zen

**Comment by spsiddarthan** [comment] 2022-02-09 11:53
@jeherve, 

Wanted to ask about a different, but related issue. 

I did this
```
Activate the option for visitors to use WordPress.com, Google, Twitter, or Facebook to comment (Jetpack Settings > Discussion).
```

I was able to see the options to log in from WordPress.com, Google, Twitter, or Facebook on Firefox to add a comment, but on Chrome or Safari, I can't see them. 

I tried it on a JN site, should I open a new issue for it? 

Firefox:

<img width="910" alt="Screenshot 2022-02-09 at 5 20 46 PM" src="https://user-images.githubusercontent.com/6594561/153194637-3f5a090f-ff6e-40d8-ba17-e14918d6bbaa.png">

Chrome

<img width="928" alt="Screenshot 2022-02-09 at 5 21 54 PM" src="https://user-images.githubusercontent.com/6594561/153195320-d957e808-6804-4549-a6f2-3a8c3a623ed1.png">

**Comment by spsiddarthan** [comment] 2022-02-09 14:55
My bad, chrome works fine if I tried from a different profile, might probably have something to do with ad-blockers, so ignore my previous comment

**Comment by jeherve** [comment] 2022-02-09 15:37
> might probably have something to do with ad-blockers

Yes, that would be it. Some ad-blockers specifically target and hide "social" things like logos.  ¯\_(ツ)_/¯

**Comment by pablinos** [comment] 2022-02-11 13:16
Should be fixed now. I merged it a few moments ago.

r239934-wpcom

**Comment by jenhooks** [comment] 2022-02-27 18:36
There's still something going on here, but I can't figure it out. The social login option seems to show up _intermittently_ on both https://davidpaulandthepeople.com/ and my test site https://jenhooks.wpsandbox.me/ The user is back in 4816666-zen

* I've confirmed it doesn't show up on mobile [for the user's site](https://d.pr/i/pLKhqF) or [my test site](https://d.pr/i/56mlrt)
* I WAS able to log into the comment form on the user's site with Facebook in my regular working tab in Chrome, _at first._ [Brief screencast here.](https://d.pr/v/ULhBjj)
* When I tested in an incog window in Chrome (also logged into a Facebook account in the same window), the social options stopped showing up. Brief gifs: [User's site](https://d.pr/i/qIYzOd) || [My test site.](https://d.pr/i/zq12ul)
* When I tested in incog Firefox, the social icons show up, but they just spin; they don't actually do anything. (Note that I'm also logged into a Facebook account in this window as well.) Brief gifs: [User's site](https://d.pr/i/995MgW) || [My test site.](https://d.pr/i/us42FA)
* [There are some console errors](https://d.pr/i/UVDGWi), but I'm not sure what they mean or if they're relevant.

The common thread seems to be the incognito window?

* User has ruled out the theme. 
* User has done the plugin dance.
* User has cleared browser cache and cookies. 
* "Users must be registered and logged in to comment" is deselected

**Comment by jeherve** [comment] 2022-02-28 11:37
> There are some console errors, but I'm not sure what they mean or if they're relevant.

Those are definitely relevant, thank you!

> The common thread seems to be the incognito window?

Indeed. Do you happen to remember if you unchecked that option when opening the Chrome Incognito window? On my end it seems to work well on your test site when I uncheck that box.

**Comment by jenhooks** [comment] 2022-02-28 13:20
I'm not sure which box you're referring to. Here's a quick summary of what I tried:

* Chrome, regular window, my test site and the user's site: I logged out of my WordPress.com account and was able to log in with Facebook.
* Chrome incognito window, my test site and the user's test site: no social sign-in options at all
* Firefox regular window, my test site and the user's test site: social sign-in options show up, but they just spin. Google sign-in **_does_** work.
* Firefox private window, my test site and the user's test site: social sign-in options show up, but they just spin. Google sign-in **_does_** work.
* Mobile iPhone 12, Ghostery browser. both sites: no social sign-in options

**Comment by jeherve** [comment] 2022-02-28 15:13
> I'm not sure which box you're referring to. 

Sorry, I should have been clearer. this one:
<img width="882" alt="Screenshot 2022-02-28 at 16 09 41" src="https://user-images.githubusercontent.com/426388/156007063-dcce2201-a14f-462f-bb10-389cea65041b.png">

**Comment by pablinos** [comment] 2022-02-28 15:51
Although this affects the same feature, I think it's a different problem. That `sameorigin` error is unrelated to the fix we implemented for the Facebook app settings change, but is probably the problem.

Firefox is particularly strict about not letting you retrieve Facebook URLs on sites, especially with private browsing. 

I've been testing using Facebook containers with more success. You need to allow jetpack.wordpress.com in the container too. 

I'll have a try with the test site as soon as I can.

**Comment by jenhooks** [comment] 2022-02-28 21:07
> Sorry, I should have been clearer. this one:

Thanks for the clarification @jeherve -- I _do_ have that toggled on.

**Comment by pablinos** [comment] 2022-02-28 21:14
>  I do have that toggled on.

I think that would break it, as it relies on being able to communicate with Facebook, but it looks like some kind of tracker to the browser.

**Comment by ebinnion** [comment] 2022-02-28 21:31
Right. Third-party cookies are required for the social logins to work. 

To the point about the social login buttons do not sometimes show, I added a check a month or so ago on the WordPress.com side that attempts to check for 3rd-party cookie support and hide the social login buttons if 3rd-party cookies are not supported. We do have it in our roadmap to fix third-party cookie support for comments this year, but I wouldn't expect it for a few months. Hiding the login buttons for browsers that were not supported seemed a simple way to improve the overall UX in the short-term.

**Comment by jeherve** [comment] 2022-03-01 07:04
👍 For now, I'll close this issue again since the issue seems to only be happening when third-party cookies are blocked.

**Closed by jeherve** 2022-03-01 07:04 UTC
Labels: [Type] Bug, Comments, [Status] Needs Author Reply, [Pri] High, [Type] Happiness Request, [Plugin] Jetpack
