### ISSUE TITLE
Infinite scrolling: Load more button showing for tag pages with fewer than posts_per_page posts

### ISSUE THREAD

**Issue by alexisbellido** [Automattic/jetpack#6070] opened 2017-01-11 18:33 UTC
I upgraded from Jetpack 4.0.4 to 4.4.2 and noticed that tag pages (URLs like /tag/some-tag) using infinite scrolling and containing fewer than posts_per_page posts still show the load more button on its first and only page. Apparently, the problem is in function is_last_batch in infinity.php:

	/**
	 * Is this guaranteed to be the last batch of posts?
	 */
	static function is_last_batch() {
		$post_type = get_post_type();
		$entries = wp_count_posts( empty( $post_type ) ? 'post' : $post_type )->publish;
		if ( self::wp_query()->get( 'paged' ) && self::wp_query()->get( 'paged' ) > 1 ) {
			$entries -= self::get_settings()->posts_per_page * self::wp_query()->get( 'paged' );
		}
		return $entries <= self::get_settings()->posts_per_page;
	}

The call to wp_count_posts is returning a count for all posts instead of just the posts with the tag I'm viewing. As I couldn't find a filter to hook into and modify the query to return the correct number of counts, I've worked around this by using the version from Jetpack 4.0.4:

	/**
	 * Is this guaranteed to be the last batch of posts?
	 */
	static function is_last_batch() {
		return (bool) ( count( self::wp_query()->posts ) < self::get_settings()->posts_per_page );
	}

This may be related to https://github.com/Automattic/jetpack/issues/282

**Comment by jeherve** [comment] 2017-01-11 20:21
Closing as duplicate of #5550

**Closed by jeherve** 2017-01-11 20:21 UTC
Labels: Infinite Scroll
