### ISSUE TITLE
Podcast Player: Inconsistent content padding

### ISSUE THREAD

**Issue by WunderBart** [Automattic/jetpack#15340] opened 2020-04-07 14:02 UTC
#### Steps to reproduce the issue

The Left and right padding of the block are not inlined vertically.

| Cover On, Description On  | Cover Off, Description On | Cover Off, Description Off | 
| ------------- | ------------- | ------------- |
|<img width="800" alt="Screenshot 2020-04-07 15 50 44" src="https://user-images.githubusercontent.com/1451471/78678054-bef9a900-78e8-11ea-9ebf-63526e0d24fc.png">|<img width="802" alt="Screenshot 2020-04-07 15 50 55" src="https://user-images.githubusercontent.com/1451471/78678058-c15c0300-78e8-11ea-961c-8d1b3cae1cb0.png">|<img width="803" alt="Screenshot 2020-04-07 15 52 08" src="https://user-images.githubusercontent.com/1451471/78678060-c28d3000-78e8-11ea-9d36-d311a5ea3db3.png">|

#### What I expected

To see the content side padding vertically consistent.

**Comment by obenland** [comment] 2020-04-07 16:40
Duplicate of #15262.

**Closed by obenland** 2020-04-07 16:40 UTC
Labels: [Block] Podcast Player
