### ISSUE TITLE
SEO: Publicize uses SEO Description in Opengraph ahead of Post Excerpt

### ISSUE THREAD

**Issue by chrisfromthelc** [Automattic/jetpack#8400] opened 2017-12-21 06:42 UTC
#### Steps to reproduce
1. Create a new post on a site with connected Publicize connections (Facebook, Twitter)
2. Set a post excerpt.
3. Set a SEO Description.
4. Published/publicized post will utilize the SEO description for the `og:description`.

#### What I expected
Since all plans have access to the post excerpt, it makes sense to stick with the custom excerpt as the `og:description` across the board, reserving the SEO Description for the `meta name="description"` tag only (or as a last resort above auto-generating an excerpt). For SEO and social media purposes, the SEO Description should not be prioritized as the social media description/preview as well, since many users will want to craft these separately.

The optimal order should be:

1. Publicize custom message.
2. Excerpt.
3. SEO Description.
4. Autogenerated from post.

#### Examples
Oldest post: SEO Description + Post Excerpt
Middle post: SEO Description + Post Excerpt + Publicize Excerpt
Newest post: Post Excerpt only

![screen shot 2017-06-06 at 12 21 36 am](https://cloud.githubusercontent.com/assets/8002138/26818152/70ee9732-4a4e-11e7-88b9-d1ca201e42e2.png)
![screen shot 2017-06-06 at 12 21 10 am](https://cloud.githubusercontent.com/assets/8002138/26818153/70f00a40-4a4e-11e7-863f-a298a7e752a1.png)

**Comment by jeherve** [comment] 2017-12-29 17:39
> The optimal order should be:
>
> 1. Publicize custom message.

I would not use the Publicize custom message in the Open Graph meta tags, as you would then get a preview with duplicated text.

I agree with the rest of the proposed order though.

**Comment by chrisfromthelc** [comment] 2017-12-29 18:07
@jeherve Re-reading this, yes, that makes sense. I seemed to have forgotten for a moment what Publicize's custom message was actually for. :)

**Comment by jeherve** [comment] 2018-09-04 17:11
Closing as duplicate of #6181

**Closed by jeherve** 2018-09-04 17:11 UTC
Labels: SEO Tools, [Pri] Low, [Type] Duplicate, [Type] Enhancement
