### ISSUE TITLE
VideoPress: fix the `VideoPressUploader` warning

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#25866] opened 2022-08-26 14:01 UTC
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at VideoPressUploader (https://retrowolf.sa.ngrok.io/wp-content/plugins/videopress/jetpack_vendor/automattic/jetpack-videopress/build/block-editor/index.js?ver=169b23bac1d040cca2b6:2124:5)
```

![Image](https://user-images.githubusercontent.com/77539/186920824-5d2269cb-09d8-4f33-9ab8-a01f7169f46b.png)

**Comment by nunyvega** [comment] 2022-10-10 14:42
As a note, @dhasilva was not able to reproduce it, we'll need to confirm that this still happens, as it may not be an issue anymore.

**Comment by nunyvega** [comment] 2022-10-24 14:08
I tried to replicate it both locally and in Jurassic Ninja sites, but was not able to get this error. Closing this issue as it seems fixed.

**Closed as completed by nunyvega** 2022-10-24 14:08 UTC
Labels: [Block] VideoPress, [Package] VideoPress
