### ISSUE TITLE
VideoPress: Be able to pick video frame to be used as video cover

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#25964] opened 2022-08-31 17:19 UTC
Currently, it's only possible right as soon as a video is uploaded. But then once published for example, you can't go back and pick a video frame as a cover.

**Comment by dhasilva** [comment] 2022-09-23 13:37
Duplicate of https://github.com/Automattic/jetpack/issues/26153

**Closed as completed by dhasilva** 2022-09-23 13:37 UTC
Labels: [Block] VideoPress, [Package] VideoPress
