### ISSUE TITLE
Contact Info/Map Widget: Better Error Messaging

### ISSUE THREAD

**Issue by mzakariya** [Automattic/jetpack#10355] opened 2018-10-18 23:11 UTC
## Summary
On **self-hosted sites** (doesn't seem to impact WPcom `*`) the Contact Info/Map widget is not accepting **any** address. This includes the default address shipped with the plugin:

![](http://cld.wthms.co/z2lJQW+)
Image Link: http://cld.wthms.co/z2lJQW
 
Tested using an **unrestricted** API key with access to the _Maps Embed API:_

![](http://cld.wthms.co/2xRH1O+)
Image Link: http://cld.wthms.co/2xRH1O

**NOTE:** Since I'm posting this in the public repo, I've regenerated both API keys. They're no longer valid.

Bug replicated across different platforms:

- Pressable
- Atomic
- Self-hosted (Google Cloud Platform)
- A user's site

Unclear if this has an impact on _existing_ widgets that already saved the address. Didn't have any to check on. 

`*` **WPcom-specific stuff; check here, there's another oddity:**

- p1539903252000100-slack-jpop-support

Internal ref:
1494815-zen

**Comment by danjjohnson** [comment] 2018-10-19 09:58
Reopening to enquire if there's any way we can detect if the key does not have the Geocoding API enabled, or at least give a hint in the widget that that could be the issue.

**Comment by kraftbj** [comment] 2018-10-19 19:13
It may be possible. There are a number of status codes the API will return that would indicate some type of key error https://developers.google.com/maps/documentation/geocoding/intro#StatusCodes

We probably could at least pass the error message through.

**Comment by htdat** [comment] 2018-10-29 08:18
1506303-zen

**Comment by htdat** [comment] 2018-11-06 02:45
> 1506303-zen

@mzakariya - When working on this ticket, I've tested more than one time and in my testing, I just need to choose `Maps` without `Places`, the key is still working for me.

**Comment by arunsathiya** [comment] 2018-11-07 15:03
1548677-zen

**Comment by mzakariya** [comment] 2018-12-18 16:52
1644371-zen

**Comment by brezocordero** [comment] 2018-12-26 15:38
1668616-zen

**Comment by sarahfg** [comment] 2018-12-26 19:53
Looking at Google's documentation you must now enable Billing to get this API to work https://developers.google.com/maps/documentation/geocoding/usage-and-billing

![google billing info from https://developers.google.com/maps/documentation/geocoding/usage-and-billing](http://cld.wthms.co/WkRcWC+)

(Image link: http://cld.wthms.co/WkRcWC )

**Comment by erricgunawan** [comment] 2018-12-29 03:42
1674153-zen

**Comment by erricgunawan** [comment] 2019-01-09 01:55
1699926-zen

**Comment by htdat** [comment] 2019-01-09 09:22
1692948-zen

**Comment by ezebecke** [comment] 2019-01-10 16:54
1707581-zen

**Comment by Robertght** [comment] 2019-02-04 05:03
6131015-hc
1771283-zen

**Comment by nielslange** [comment] 2019-02-07 11:11
Chat: 10139652-hc
Follow-up: 1783357-zen

**Comment by jeremypaavola** [comment] 2019-02-11 12:46
1777442-zen

**Comment by kosiew** [comment] 2019-02-27 09:29
#1835564-zen

**Comment by thebud15** [comment] 2019-03-28 20:17
11651903-hc

**Comment by samiff** [comment] 2019-04-19 02:34
> I just need to choose Maps without Places, the key is still working for me.

Seems like an existing embedded map will work (with Maps Embed API enabled), but if you try to change the address shown in Customize, that is where things fail without the Geocoding API enabled.

[Using this endpoint](https://github.com/Automattic/jetpack/blob/0b4a693eb4dfbeb75e8f9df0bb48c6025ae859fc/modules/widgets/contact-info.php#L193) with a valid API key but having **Geocoding API disabled**:
```json
{
    "error_message": "This API project is not authorized to use this API.",
    "results": [],
    "status": "REQUEST_DENIED"
}
```

Same API key with **Geocoding API enabled**:
```json
{
    "results": [
        {
            "address_components": [
                {
                    "long_name": "201",
                    "short_name": "201",
                    "types": [
                        "street_number"
                    ]
                },
                {
                    "long_name": "Presidents' Circle",
                    "short_name": "Presidents' Cir",
                    "types": [
                        "route"
                    ]
                },
                {
                    "long_name": "University",
                    "short_name": "University",
                    "types": [
                        "neighborhood",
                        "political"
                    ]
                },
                {
                    "long_name": "Salt Lake City",
                    "short_name": "Salt Lake City",
                    "types": [
                        "locality",
                        "political"
                    ]
                },
                {
                    "long_name": "Salt Lake County",
                    "short_name": "Salt Lake County",
                    "types": [
                        "administrative_area_level_2",
                        "political"
                    ]
                },
                {
                    "long_name": "Utah",
                    "short_name": "UT",
                    "types": [
                        "administrative_area_level_1",
                        "political"
                    ]
                },
                {
                    "long_name": "United States",
                    "short_name": "US",
                    "types": [
                        "country",
                        "political"
                    ]
                },
                {
                    "long_name": "84112",
                    "short_name": "84112",
                    "types": [
                        "postal_code"
                    ]
                }
            ],
            "formatted_address": "201 Presidents' Cir, Salt Lake City, UT 84112, USA",
            "geometry": {
                "location": {
                    "lat": 40.7650458,
                    "lng": -111.8489555
                },
                "location_type": "ROOFTOP",
                "viewport": {
                    "northeast": {
                        "lat": 40.7663947802915,
                        "lng": -111.8476065197085
                    },
                    "southwest": {
                        "lat": 40.7636968197085,
                        "lng": -111.8503044802915
                    }
                }
            },
            "place_id": "ChIJpyXgx-1fUocRfxeIPt5NPwo",
            "plus_code": {
                "compound_code": "Q582+2C Salt Lake City, Utah, United States",
                "global_code": "85GCQ582+2C"
            },
            "types": [
                "street_address"
            ]
        }
    ],
    "status": "OK"
}
```

[The support page ](https://jetpack.com/support/extra-sidebar-widgets/contact-info-widget/)only mentions `In the list that appears, choose the “Google Maps Embed API” under “Google Maps APIs”.` Should consider updating that for users/HEs while upgraded error messaging is worked on.

---
12182642-hc

**Comment by kriskorn** [comment] 2019-04-22 12:40
#12121416-hc

**Comment by jeremypaavola** [comment] 2019-04-22 12:43
1978094-zen
- Fixed by including the Geocode API

**Comment by jessestu** [comment] 2019-05-15 20:14
12809350-hc We spent so long trying to get this work and never could. This compounded a user's frustration in moving from our simple to atomic product.

**Comment by kbrown9** [comment] 2019-05-23 01:10
@kraftbj @aduth It looks like many of these recent Contact Info & Map widget problems are caused by the user not enabling the Geocoding API or not setting up the Geocoding API's required billing information. In 2016, you were discussing [removing the geocoding](https://github.com/Automattic/jetpack/pull/4242#issuecomment-229960320). What do you think of removing it now?

Instead of using geocoding, the map could be embedded in the widget's admin form. This would provide error messaging to the user; an invalid address would display an incorrect map, and an invalid API key would display a useful error message.

If you agree that this is a potential solution, I can work on a PR.

**Comment by jeherve** [comment] 2019-05-23 09:30
> Instead of using geocoding, the map could be embedded in the widget's admin form. This would provide error messaging to the user; an invalid address would display an incorrect map, and an invalid API key would display a useful error message.

Wouldn't you still need the Geocoding API to plot a set of coordinates on the map from an address?

**Comment by kbrown9** [comment] 2019-05-23 15:39
> Wouldn't you still need the Geocoding API to plot a set of coordinates on the map from an address?

The embedded map URL is created using the address, not the lat/long coordinates.

The `widget()` function calls `build_map()` to create the embedded map. The beginning of the `build_map()` function is shown below. The docblock mentions the latitude and longitude, but this function actually uses the address to create the URL.

```
/**
		 * Builds map display HTML code from the supplied latitude and longitude.
		 *
		 * @param string $address Address.
		 * @param string $api_key API Key.
		 *
		 * @return string HTML of the map.
		 */
		function build_map( $address, $api_key = null ) {
			$this->enqueue_scripts();
			$src = add_query_arg( 'q', rawurlencode( $address ), 'https://www.google.com/maps/embed/v1/place' );
			if ( ! empty( $api_key ) ) {
				$src = add_query_arg( 'key', $api_key, $src );
			}
```

**Comment by jeherve** [comment] 2019-05-23 16:35
Oh ok. I think I still had the old version of the widget in mind!

Feel free to give it a try then, for sure. Maybe you can update that docblock at the same time :)

**Comment by JessBoctor** [comment] 2019-06-02 23:31
I have run into this issue on a WP.com site.

#13185249-HC
Follow Up #2079712-ZD

**Comment by ajaykj** [comment] 2019-06-04 07:25
@JessBoctor #2079712-ZD seems to have resolved on its own. Can you check and confirm? I have contacted the user as well to check on their end.

**Comment by allykmyta** [comment] 2019-06-17 00:30
Ran into a similar issue with this widget - Google Maps API Key and Address returns "Sorry. We can not plot this address. A map will not be displayed. Is the address formatted correctly?" on WordPress.com Business site.

#13461284-hc
Follow-up: #2111269-zen

**Comment by edequalsawesome** [comment] 2019-06-19 22:22
I ran into the same issue in #13462849-hc / #2117924-zen on a site that was recently AT'd.

I tried to set it up on my test AT and self-hosted sites with a key that included the Geocaching API, but I'm still getting the `Sorry. We can not plot this address. A map will not be displayed. Is the address formatted correctly?` error.

**Comment by kbrown9** [comment] 2019-06-20 22:28
@allykmyta @edequalsawesome Do you know if billing was enabled for the Geocoding API? The [Google Maps Geocoding API documentation](https://developers.google.com/maps/documentation/geocoding/start) states that billing must be enabled.

**Comment by carinapilar** [comment] 2019-07-06 12:42
Another report here: https://github.com/Automattic/jpop-issues/issues/4057.

I'm not sure if the billing thing is related, because the user has 2 widgets, in one of them the API works, but in the second it shows the error.

Where it works:

![APIWorks](https://user-images.githubusercontent.com/16104522/60756286-43be3c00-9fd2-11e9-9991-61b6fdc4b978.png)

Where it doesn't work:

![APIDoesntWork](https://user-images.githubusercontent.com/16104522/60756287-47ea5980-9fd2-11e9-9f6d-84b82fec0027.png)

**Comment by sarahfg** [comment] 2019-08-01 22:03
I had a user in chat  #14339238-hc who has also run into this. They've run through all our documentation 3 times and have not had success. Something is wrong with our widget!

**Comment by sarahfg** [comment] 2019-08-01 22:08
I updated our documentation to include that billing must be enabled. The user in the above situation already had it enabled

**Comment by samiff** [comment] 2019-08-01 22:17
@sarahfg Did you check if they had the Geocoding API enabled? https://github.com/Automattic/jetpack/issues/10355#issuecomment-484748746

**Comment by sarahfg** [comment] 2019-08-01 22:19
@samiff Checking with the user now! Will let you know

**Comment by sarahfg** [comment] 2019-08-01 22:24
Added the Geocoding API to the documentation for users at https://jetpack.com/support/extra-sidebar-widgets/contact-info-widget/

**Comment by sarahfg** [comment] 2019-08-01 22:27
@samiff that did it!!! Thank you! The user (and I) are so happy

**Closed** 2019-08-22 17:22 UTC
Labels: Extra Sidebar Widgets, [Pri] Normal, [Type] Enhancement, [Type] Happiness Request
