### ISSUE TITLE
Like Button: Like Button Disappears on AMP Standard Mode

### ISSUE THREAD

**Issue by druesome** [Automattic/jetpack#15881] opened 2020-05-21 12:31 UTC
When AMP is set to Standard mode, the Like button does not appear on posts on the site.

#### Steps to reproduce the issue

1. Install AMP Plugin and activate it.
2. Activate the Likes module in Jetpack > Settings > Modules
2. Go to Settings > Sharing and make sure Likes are on for all posts.
2. Click on AMP and select Standard mode, then Save Changes.
3. View any published post.

#### What I expected

For the Like button to appear on posts.

#### What happened instead

The Like button is nowhere to be found.

**Screenshots**

Like button showing up on Reader or Transitional AMP mode:

<img src="https://d.pr/i/C0oVnY+" width="600" />

Like button not showing up on Standard AMP mode:

<img src="https://d.pr/i/NMSN9E+" width="600" />

Reference: p9F6qB-5gN

**Comment by jeherve** [comment] 2020-05-22 07:57
Closing as duplicate of #9555.

**Closed by jeherve** 2020-05-22 07:57 UTC
Labels: AMP, Likes, [Type] Bug
