### ISSUE TITLE
Site Accelerator doesn't replace images using html style attribute with background-image

### ISSUE THREAD

**Issue by jessefriedman** [Automattic/jetpack#16406] opened 2020-07-06 13:22 UTC
With Site Accelerator enabled add a Gutenberg block that appends the background image via inline css.  Here's an example: 

`<div class="wp-block-cover alignfull has-background-dim-20 has-background-dim is-position-center-center  is-cropping" style="background-image:url(https://mywebsite.com/wp-content/uploads/2020/07/woman-in-front-of-her-computer-3059745.jpg);background-position:53% 55%;min-height:560px"><div class="wp-block-cover__inner-container">
`

This Gutenberg block adds the image using a style attribute on a div.  From what I can tell this prevents Site Accelerator from being able to find and replace the image.

**Comment by jeherve** [comment] 2020-07-06 13:49
Closing as duplicate of #16396

**Closed by jeherve** 2020-07-06 13:49 UTC
Labels: Photon, [Type] Bug
