### ISSUE TITLE
OpenTable: Block styles look broken

### ISSUE THREAD

**Issue by alaczek** [Automattic/jetpack#15144] opened 2020-03-27 02:44 UTC
OpenTable block provides four block styles, but the preview in the sidebar does not show them properly:

![image](https://user-images.githubusercontent.com/4550351/77715469-ca6aeb80-702f-11ea-8d6b-6e41ec797942.png)

#### Steps to reproduce the issue

1. On a site with Premium plan, add a new post or a page.
2. Add OpenTable block.
3. Note how the block styles look in the sidebar.

#### What I expected
To see a miniature of what the block actually looks like.

**Comment by jeherve** [comment] 2020-03-27 08:52
Yes, this is happening since https://github.com/Automattic/jetpack/pull/14528#issuecomment-598162165

cc @Copons

**Comment by Copons** [comment] 2020-03-27 11:19
Yup, thanks for reporting but we're already aware of this!
Closing as duplicate of https://github.com/Automattic/jetpack/issues/15064

**Closed by Copons** 2020-03-27 11:19 UTC
Labels: [Block] OpenTable, [Type] Bug
