### ISSUE TITLE
Extra Sidebar Widgets: Only load the Stylesheet for Social Icons when the Widget is active

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/jetpack#10106] opened 2018-09-06 11:44 UTC
A user reached out to us in 2757371-hc confused because they were still seeing the 

`<link rel='stylesheet' id='jetpack-widget-social-icons-styles-css' href='https://kunaldesai.blog/wp-content/plugins/jetpack/modules/widgets/social-icons/social-icons.css?ver=20170506' type='text/css' media='all' />`

 file despite the fact that they had disabled the Social Icons Widget. 

Doing some digging, we discovered that this file is loaded automatically with the Extra Sidebar Widgets module. If possible, let's only the loading of this file when the Social Icons Widget is in use. 

#### Steps to reproduce the issue

1. Install and connect Jetpack.
2. Note that even with the Social Icons Widget disabled, the stylesheet is still loaded. 
3. Disable Extra Sidebar Widgets. 
4. Note that the stylesheet is not loaded. 

#### What I expected

The stylesheet should only be loaded when the Social Icons Widget is active.

**Comment by jeherve** [comment] 2018-09-06 11:51
Closing as duplicate of #10009

**Closed by jeherve** 2018-09-06 11:51 UTC
Labels: Extra Sidebar Widgets, [Type] Duplicate, [Type] Enhancement
