### ISSUE TITLE
Impossible hook timing

### ISSUE THREAD

**Issue by szepeviktor** [Automattic/jetpack#19166] opened 2021-03-14 11:24 UTC
First `Jetpack::init` is hooked to `init` action

https://github.com/Automattic/jetpack/blob/c95c00fcb42e2329525e7d2c39bcc75b2e3468ff/projects/plugins/jetpack/load-jetpack.php#L77

then in that method something is hooked into `plugins_loaded`

https://github.com/Automattic/jetpack/blob/c95c00fcb42e2329525e7d2c39bcc75b2e3468ff/projects/plugins/jetpack/class.jetpack.php#L418

As `plugins_loaded` is fired **before** `init`

https://codex.wordpress.org/Plugin_API/Action_Reference#Actions_Run_During_a_Typical_Request

that method will **never** be executed. 😿 

Please consider studying hook firing order and fix this and potentially other problems.
Thank you.

**Comment by jeherve** [comment] 2021-03-15 11:50
Closing as duplicate of #5684.

**Closed by jeherve** 2021-03-15 11:50 UTC
Labels: General, [Type] Bug, [Type] Duplicate
