### ISSUE TITLE
Comments: Threaded replies don't work with Jetpack 6.4

### ISSUE THREAD

**Issue by dougaitken** [Automattic/jetpack#10000] opened 2018-08-08 10:24 UTC
#### Steps to reproduce the issue

1. Using Jetpack `6.3.2` reply to a comment on the front-end. Comment will be threaded
2. Update to Jetpack `6.4`
3. Reply to comment on the front-end

#### What I expected

When I press reply on a comment, it will thread the reply

#### What happened instead

Replying to a comment on the front-end on Jetpack 6.4, the reply is a new comment and not a reply
This can be seen in `/wp-admin/edit-comments.php` as the reply doesn't say "In reply to..."

Compare: 
`https://beta.doug.press/2018/04/hello-world/` on 6.4
`https://delighted-toad.jurassic.ninja/2018/08/08/hello-world` on 6.3.2

**Comment by zinigor** [comment] 2018-08-08 11:51
Thanks for reporting this! This bug is apparently caused by #9681. Furthermore, I'm having some troubles sending comments with Firefox, which is fixed by rolling back the sandbox change introduced by that PR.

**Comment by StefMattana** [comment] 2018-08-08 13:06
Dropping a ticket related issue just to keep track on that and cross-posting: 1333177-zen

**Comment by dougaitken** [comment] 2018-08-08 16:07
Thanks for dropping the ticket link, Stef. 

I've replied back to the customer to let them know we're fixing

**Closed** 2018-08-08 18:29 UTC
Labels: Comments, [Pri] High, [Type] Bug
