### ISSUE TITLE
Add sharing link to the Settings tabs

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack#6228] opened 2017-01-28 01:22 UTC
It should look like this:

![image](https://cloud.githubusercontent.com/assets/1123119/22393029/53d6cd46-e4bd-11e6-9ef9-02f47e4fe8b2.png)

And it should send users to the sharing section in Calypso. After some recent discussion, we put together https://github.com/Automattic/wp-calypso/issues/11023 for the Sharing section of Calypso to move into the Settings section as a single tab. This seems feasible with a small team.

**Comment by eliorivero** [comment] 2017-02-02 18:03
The Sharing area is composed of two areas in Calypso:
- Connections (what is Publicize in Jetpack)
- Sharing buttons
Now, Publicize requires connection but Sharing does not. Should we update this link based on whether it's connected or not?
- if it's connected, go to Calypso Sharing
- if it's not connected, go to WP Admin > Sharing

**Comment by MichaelArestad** [comment] 2017-02-02 18:04
> Should we update this link based on whether it's connected or not?

On whether Jetpack is connected? Or a publicize connection?

**Comment by eliorivero** [comment] 2017-02-02 18:05
On whether Jetpack is connected.

**Comment by MichaelArestad** [comment] 2017-02-02 18:06
Ah. We should still send them to Calypso, but disable or hide the publicize settings that require a connection. We should have a message explaining they need to connect to use it.

**Comment by eliorivero** [comment] 2017-02-02 18:08
If site is in Dev Mode, they can use Sharing buttons, but they don't have a link to a Calypso since there's not a shadow site created.

**Comment by MichaelArestad** [comment] 2017-02-02 18:09
@beaulebens ideas? Ideally, I'd like to be able to completely remove the old sharing settings.

**Comment by beaulebens** [comment] 2017-02-02 19:02
I think if we follow what happens elsewhere with disabled features, then the top link (Sharing) would remain active, but when you get to that view in Calypso, all the Publicize options would be disabled. I believe right now, Calypso completely removes Publicize options (the entire view/page) if you have Publicize turned off in Jetpack. So we can do that for now (just remove them in Calypso), but probably makes sense to go towards including them, and just having them automatically enable Publicize if you start the connection process (that would be handled primarily in Calypso though).

**Comment by eliorivero** [comment] 2017-02-02 19:23
@beaulebens to clarify: the issue is not Publicize but the Sharing module. It's available without connection, for example, in Dev Mode, and it makes the social buttons available.
So, in Dev Mode, should we point this link to WP Admin Sharing settings so user can configure social buttons?

**Comment by beaulebens** [comment] 2017-02-02 21:31
Oh, oh, got ya. Sorry, I got off on a different tangent. Yeah, since they've in Dev Mode, they won't be connected, thus no access to a WP.com page. Yes, in that case, I think it'd be a reasonable compromise to link to the WP-admin page for now.

**Comment by eliorivero** [comment] 2017-02-03 20:47
Closed in #6274

**Closed by eliorivero** 2017-02-03 20:47 UTC
Labels: Admin Page, Sharing
