### ISSUE TITLE
Earn blocks: "Sales disabled" notice after reconnecting to Stripe

### ISSUE THREAD

**Issue by mmtr** [Automattic/jetpack#16989] opened 2020-08-26 12:29 UTC
When a user disconnects their Stripe account in `wordpress.com/earn/payments`, all plans are invalidated by setting a `'account_disconnected' => true` flag in all of them (see `A8C\Billingdaddy\Api\Connected_Accounts::disconnect_connected_account` in the WP.com codebase).

That ensures that any existing Earn block (Payments, Premium Content, Donations) don't go through the checkout process if a user tries to submit a payment. Instead we display a "Sales disabled" notice:

<img width="476" alt="Screen Shot 2020-08-26 at 14 18 26" src="https://user-images.githubusercontent.com/1233880/91303166-e96cd580-e7a7-11ea-8c36-14cc0d84be50.png">

However, if that user decides to reconnect their Stripe account, the `account_disconnected` flag is not removed from the plans, so all Earn blocks previously published continue displaying the "Sales disabled" notice.

This can be worked around for the Payments and Premium Content blocks, since a user can delete the old plan and create a new one that won't have the `account_disconnected` flag. But for the Donations block this is rather problematic, since a user cannot manage donation-type plans, so Donations blocks published after the reconnection won't work either.

**Comment by mmtr** [comment] 2020-08-26 12:34
cc @artpi in case he has any advice

**Comment by mmtr** [comment] 2020-08-27 10:55
Ok, this is weird. I cannot longer reproduce this, so I guess I was a problem on my sandbox (maybe I wasn't sandboxing everything correctly).

**Comment by mmtr** [comment] 2020-09-01 17:03
Reopening this since @blackjackkent started experienced it too. To be honest, all the code I investigated seems correct, so I think the issue is only happening when there is some sandbox misconfiguration and likely is not going to affect final users.

But if we want to avoid this, one way is by completely removing the plan IDs from the Donations block attributes. Given that plans are automatically set/created without the user noticing it, we can actually do that as part or the [dynamic block rendering](https://github.com/Automattic/jetpack/blob/cb462a76f4d0d94dfbfb81dbce860341213cb0d3/extensions/blocks/donations/donations.php#L41).

That would mean that plan IDs won't be fetched as [part of the block edit logic](https://github.com/Automattic/jetpack/blob/cb462a76f4d0d94dfbfb81dbce860341213cb0d3/extensions/blocks/donations/edit.js#L56-L77), instead we can fetch them during execution time as part of the dynamic block rendering (render callbacks are executed when visiting a post that contains the block).

Since that logic runs in the server, we should be able to check the `account_disconnected` flag and if for any reason the flag exists but the Stripe connection is set, we can recreate the plans with the new Stripe account, making sure that the returned plans will work in the payment dialog.

**Comment by chaitanyamsv** [comment] 2020-11-29 21:16
I just had a customer report this in 25987821-hc

**Comment by jonnyruzek** [comment] 2020-11-30 16:11
I encountered this same error message with the Premium Content block in 25938511-hc

**Comment by jonnyruzek** [comment] 2020-11-30 16:46
Got another in 26008195-hc

**Comment by eamcgill90** [comment] 2020-11-30 18:08
Another - 26008195-hc

**Comment by nagpai** [comment] 2020-12-01 02:47
Observed in a case where users first register on WooCommerce Payments (that apparently creates a Stripe Express account), and then use the same credentials for Premium content block. 

3519340-zd

**Comment by eurello** [comment] 2020-12-07 21:11
@mmtr Is it possible to fix this for individual customers while we're waiting for the bug itself to be fixed? I don't understand the bit about deleting the old plan. What sort of plan? How does the user do this? [I asked in #payments here](https://a8c.slack.com/archives/C02BEP610/p1607361090429500).

**Comment by mmtr** [comment] 2020-12-08 11:29
> @mmtr Is it possible to fix this for individual customers while we're waiting for the bug itself to be fixed? I don't understand the bit about deleting the old plan. What sort of plan? How does the user do this? I asked in #payments: [p1607361090429500-slack-C02BEP610](https://href.li/?p1607361090429500-slack-C02BEP610)

They have to create a new payment plan in `wordpress.com/earn/payments-plans/:site`(Tools > Earn > Manage payments > Collect payments > Manage plans > Payment plans): https://wordpress.com/support/wordpress-editor/blocks/payments/#managing-payment-plans

Once the plan has been created, they have to switch any existing Payments / Premium content block to the new plan by editing the posts containing such blocks: https://wordpress.com/support/wordpress-editor/blocks/payments/#payment-block-settings

**Comment by yashitamittal11** [comment] 2020-12-17 10:06
Another one - [26398923-hc](26398923-hc)
The user created a new plan and added it again to the payment block. But they are still seeing the same issue.

**Comment by jonnyruzek** [comment] 2020-12-22 22:26
3593671-zen

**Comment by jamiepalatnik** [comment] 2020-12-30 23:34
Another report in 26335896-hc, suggested deleting plan and re-adding as a workaround.

**Comment by NoHopeRadio** [comment] 2021-01-11 21:24
Another report in 23452958-hc, the new plan workaround did not work for them.

**Comment by kathleenjross** [comment] 2021-01-31 19:14
Another report in 3698959-zd, with the Donation block

**Comment by eoinsav** [comment] 2021-02-11 00:59
Another report for the Payments Block: 18504186-zen

**Comment by retnonindya** [comment] 2021-02-11 03:23
Another report: 27662821-hc

Re-created the plan didn't do the trick. I'm going to do the workaround @yashitamittal11 provided on their follow-up: Creating a new Stripe account.

**Comment by noteeth** [comment] 2021-02-13 04:06
Another report for Payments block in 27711962-hc

**Comment by bsanevans** [comment] 2021-02-16 00:53
Another report for Payments block in 17465695-hc
I'll ask them to make a new payment option.

**Comment by thabotswana** [comment] 2021-03-03 11:35
Another report for Payments block in 28150296-hc

**Comment by vinnykaur** [comment] 2021-03-04 09:41
With Donations block hc-21506261

**Comment by Nic-Sevic** [comment] 2021-03-07 08:07
Another case with the donations block here: 3791649-zen

**Comment by liviopv** [comment] 2021-03-10 09:10
Another 3782418-zen with the Donations Block.

@mmtr @artpi are there any expectations that this will be fixed for the Donations block? Since it seems to be so easy to trigger this, it makes the block very fragile.

**Comment by artpi** [comment] 2021-03-10 10:02
> are there any expectations that this will be fixed for the Donations block?

No.

Neither me nor @mmtr are no longer able to work on this. My best suggestion is to post on autopay and maybe the payments teams have some capacity.

**Comment by tarunvijwani** [comment] 2021-03-10 10:10
Another one 28308521-HC
Deleting the plan and re-adding a new plan fixed the issue for them.

**Comment by michaeldcain** [comment] 2021-03-16 21:15
> This can be worked around for the Payments and Premium Content blocks, since a user can delete the old plan and create a new one that won't have the account_disconnected flag. But for the Donations block this is rather problematic, since a user cannot manage donation-type plans, so Donations blocks published after the reconnection won't work either.

@mmtr: for the donations block, can the user delete the current block and then create a new one? Will a new plan be provisioned in the background, or does it check for the old donations plan again?

**Comment by mmtr** [comment] 2021-03-17 09:54
> @mmtr: for the donations block, can the user delete the current block and then create a new one? Will a new plan be provisioned in the background, or does it check for the old donations plan again?

Unless this has changed since I worked on it, it'll get the previous generated plan. See https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/extensions/blocks/donations/fetch-default-products.js and the `Memberships_Product::generate_default_products` method in the WP.com codebase (`wp-content/lib/memberships/class.membership-product.php`).

**Comment by galakhyati** [comment] 2021-03-20 07:15
Another case here: #3819056-zen

**Comment by retnonindya** [comment] 2021-03-29 05:09
Another report: 27172626-hc

**Comment by kavyagokul** [comment] 2021-04-01 09:41
Another report in 16931649-hc

They moved the site to WordPress.com, from a self-hosted site, and donations block now show an error

>We could not find this payment plan on ... site.

**Comment by michaeldcain** [comment] 2021-04-06 14:21
I started looking into the Donations block issue yesterday. A lot of this revolves around the backend, so I created Automattic/payments-shilling#243 to track the issue.

There is a manual workaround for simple sites that requires a sandbox that I'll leave here until a better fix is made. If any of the issues above are still valid, we could look into doing the following:

- query `/wpcom/v2/sites/{site}/memberships/products` endpoint for plans `type:donation`
- delete the posts via wp-cli: `wp post delete {ID} --url={simple site address} --force`
- add a new donations block on the user's site

**Comment by michaeldcain** [comment] 2021-04-07 16:18
@kavyagokul: I've used the process above to delete the user's old donations plans. If they have a connected Stripe account, they should be able to follow the final step to re-add the donations block. Can you follow-up with them and let me know if they run into an issue?

**Comment by michaeldcain** [comment] 2021-04-07 16:27
@galakhyati: I've used the process above to delete the user's old donations plans. They don't seem to have a connected Stripe account, but if they connect a new one, they should be able to follow the final step to re-add the donations block. Can you follow-up with them and let me know if they run into an issue?

**Comment by michaeldcain** [comment] 2021-04-07 16:37
@Nic-Sevic: I've used the process above to delete the user's old donations plans. If they have a connected Stripe account, they should be able to follow the final step to re-add the donations block. Can you follow-up with them and let me know if they run into an issue?

**Comment by Nic-Sevic** [comment] 2021-04-08 10:42
Followed up with user in this case and pending result: 3791649-zen

**Comment by kavyagokul** [comment] 2021-04-10 05:08
Followed up as per workaround in 3872470-zen

**Comment by vajrasar** [comment] 2021-04-17 15:01
Following up with workaround #3916247-zen

**Comment by nerdysandy** [comment] 2021-04-17 19:22
> Re-created the plan didn't do the trick. I'm going to do the workaround @yashitamittal11 provided on their follow-up: Creating a new Stripe account.

It didn't work on #3916247-zen too. Asked them to create new account too when they connected back on #29073845-hc

**Comment by AtrumGeost** [comment] 2021-04-18 13:22
Hi @michaeldcain

Thanks for the workaround you mentioned above. Can you please do the same for this user?

3906702-zd-woothemes

**Comment by yashitamittal11** [comment] 2021-04-19 05:21
Another one- #3918459-zen

**Comment by tanjoymor** [comment] 2021-04-23 01:35
Another one #29175192-hc

**Comment by aleone89** [comment] 2021-04-27 09:02
Another report #29186380-hc - I got the user to connect to a fresh Stripe account and this solved the issue in this instance.

**Comment by kriskorn** [comment] 2021-04-27 10:46
@michaeldcain We have more reports above. Is there another workaround we could follow to take care of this in the meantime? Thank you!

**Comment by retnonindya** [comment] 2021-04-28 07:31
Another report: 3943995-zd-woothemes

I asked the user to create new payment plan and create new Stripe account (it was a ticket so I provided them both options.)

**Comment by thesacredpath** [comment] 2021-04-29 23:33
Another report here for the Donations Block on an AT site: 29312878-hc
Follow-up ticket: 3949561-zd-woothemes

@michaeldcain, any chance you could whack this one with your hammer as well? Thanks in advance.

**Comment by kosiew** [comment] 2021-05-04 02:30
Hi @michaeldcain ,

Folllowing up on [this comment](https://github.com/Automattic/jetpack/issues/16989#issuecomment-829686275), pending from 4 days ago.

**Comment by sanjeev00733** [comment] 2021-05-07 05:45
Another report in #12603179-hc
Follow up ticket: #3970578-zen

**Comment by ezebecke** [comment] 2021-05-07 19:59
#29448169-hc
Follow up: #3972370-zen

**Comment by noteeth** [comment] 2021-05-13 18:54
#28480129-hc
Follow up #3987768

We walked through workaround which didn't help, though this issue is with the donations block and it sounds like the workaround is not setup to work for this block.

**Comment by susanjanec** [comment] 2021-05-13 19:30
Another report of this here - 3985307-zen

**Comment by julsyd** [comment] 2021-05-14 13:33
Another report here: 3980302-zen

**Comment by jenlynnemc** [comment] 2021-05-16 13:06
Another report here: 3993368-zen
Suggested the workaround, although it does not appear to work for the donation block, from reading above.

**Comment by annacmc** [comment] 2021-05-19 02:57
another report here: 28387386-hc
They are using donations block, but they are going to try PayPal donation button in the meantime.

**Comment by nagpai** [comment] 2021-05-22 06:14
Another report here 
#3999248-zen

**Comment by dcoleonline** [comment] 2021-05-30 16:47
#4028987-zen (payment block, but given the workaround)

**Comment by dhackneya8c** [comment] 2021-05-31 23:57
Another site with this issue here: #29896866-hc

Would appreciate it if the sandbox workaround could be run for them. Thanks!

**Comment by tanjoymor** [comment] 2021-06-04 23:54
Another site with this issue here: #29974446-hc

Would appreciate it if the sandbox workaround could be run for them. Thanks!

cc @michaeldcain

**Comment by sbathompson-he** [comment] 2021-06-07 21:14
I just found this issue here as well: HC-30018128

Opened a ticket for them: Zen-4050745

**Comment by Nic-Sevic** [comment] 2021-06-15 13:04
Another instance here: 4062309-zen

They were originally having issues with the payments block as well but reconfigured their Stripe account and got them working. Now, they are only having issues with donations blocks
Per this thread with a similar case it sounds like switching Stripe accounts is still the issue: p1615859105014200-slack-CS0SC36SX

@ michaeldcain would you be able to run the sandbox fix you mention for this site please?

**Comment by Robertght** [comment] 2021-06-18 06:28
@michaeldcain Can we get a hand with [this one](https://github.com/Automattic/jetpack/issues/16989#issuecomment-851721197) as well, please?

**Comment by michaeldcain** [comment] 2021-06-21 19:09
In D63079-code, we're now deleting donation products when Stripe gets disconnected. This should effectively prevent this issue from happening in the future, but doesn't fix it for users already in this state. I'll pull together a script to run on the users in this thread.

**Comment by jp-imagines** [comment] 2021-06-29 13:14
Another report for the user in 4099663-zen. Could you take a look at this one as well, @michaeldcain?

**Comment by donalirl** [comment] 2021-07-01 02:08
Another report in #4107714-zen. Is this something we can fix?

**Comment by rosepajaroja** [comment] 2021-07-02 14:15
Another report in zd-4104153

**Comment by cuemarie** [comment] 2021-07-13 19:36
Returning user with this issue with their site, [originally reported on may 31 above](https://github.com/Automattic/jetpack/issues/16989#issuecomment-851721197): 4136689-zen

**Comment by poojashetty18** [comment] 2021-08-02 12:11
Another report on 30212485-hc

**Comment by tanjoymor** [comment] 2021-08-07 17:38
Another report on 31004750-hc

**Comment by wpshellbelle** [comment] 2021-08-07 23:18
Another report on 30156645-hc
Reconnecting Stripe and then deleting old payment plans and adding new payment plans resolved issue for this user.

**Comment by jartes** [comment] 2021-08-13 10:15
Another one on 29443169-hc

Suggested removing the donation block and re-connect their Stripe account. Waiting for confirmation on: 4219260-zen

**Comment by marutim** [comment] 2021-08-19 10:48
Another report here: 31071027-hc

**Comment by DavidSaladu** [comment] 2021-08-23 07:42
Another report in [4238162-zd-woothemes](https://woothemes.zendesk.com/agents/tickets/4238162)

**Comment by ClassicRKR27** [comment] 2021-08-28 15:53
Another report [31368988-hc](31368988)

**Comment by donalirl** [comment] 2021-08-28 23:55
This came up in #25641117-hc for the Premium Content buttons. We have tried deleting the payment plan and creating a new one, but the Sales Disabled notice persists. No error notices in their Stripe account. I'd like to avoid having to create a new Stripe account - @michaeldcain is there something you can do to get this working for this and other recently-reported cases?

**Comment by sajmes** [comment] 2021-09-07 12:48
Another report: 4275252-zd-woothemes

**Comment by benchilcote** [comment] 2021-09-21 15:45
Another report: #4313971-zen

**Comment by Sandkorner** [comment] 2021-09-22 06:40
31806370-HC Might be the same/similar issue as well. User is trying to delete all and try again connecting Stripe to the Payments block in the widget area.

**Comment by kerrynicl** [comment] 2021-10-01 18:55
31041805-HC Another report as well. User tried workaround and that did not resolve issue

**Comment by gaurav1984** [comment] 2021-10-12 06:10
Hi @michaeldcain do we have updates for the users reported on this thread?

**Comment by isocialtish** [comment] 2021-10-21 18:52
This came up in a Quick Start, I'm having them delete plan, delete Stripe, and then reconnect Stripe and add plan again. 

Follow up ticket: #4395421-zen

**Comment by DavidRothstein** [comment] 2021-11-02 15:22
Task: Finish script at 406-gh-Automattic/payments-shilling and run it for the affected users.

**Comment by michaeldcain** [comment] 2021-11-03 21:03
@purplepioneer: I don't have access to that ticket. Can you provide a url to the page with the broken Donation block?

**Comment by michaeldcain** [comment] 2021-11-03 21:04
@isocialtish: Can you provide a url to the page with the broken Donation block?

**Comment by michaeldcain** [comment] 2021-11-03 21:07
@supernovia: that user seems to be using simple payments buttons now (not the donations block that this bug applies to). It seems like the original fix of deleting and recreating the plans has worked for the user.

**Comment by michaeldcain** [comment] 2021-11-03 21:10
@mikeicode: [this user](https://github.com/Automattic/jetpack/issues/16989#issuecomment-943642791) seems to be using simple payments buttons now (not the donations block that this bug applies to). The original fix in this issue of deleting the plan (via Calypso), recreating it, and updating the button should work.

**Comment by michaeldcain** [comment] 2021-11-03 21:14
@poojashetty18: [this user](https://github.com/Automattic/jetpack/issues/16989#issuecomment-939887779) never responded and doesn't seem to be using a Donation block. If they have an issue with a non-Donation plan, the original fix in this issue of deleting the plan (via Calypso), recreating it, and updating the button should work.

**Comment by michaeldcain** [comment] 2021-11-03 21:15
@a8ck3n: I don't have access to [that ticket](https://github.com/Automattic/jetpack/issues/16989#issuecomment-937473032). Can you provide a url to the page with the broken Donation block?

**Comment by michaeldcain** [comment] 2021-11-03 21:19
@kerrynicl: [this user](https://github.com/Automattic/jetpack/issues/16989#issuecomment-932475812) seems to be the same as [this one](https://github.com/Automattic/jetpack/issues/16989#issuecomment-960074325).

**Comment by michaeldcain** [comment] 2021-11-03 21:22
@Sandkorner: I'm not seeing a Payment Block on [this user's](https://github.com/Automattic/jetpack/issues/16989#issuecomment-924631827) site. Can you provide a url to the page with the broken Donation block?

**Comment by michaeldcain** [comment] 2021-11-03 21:25
@benchilcote: [this user](https://github.com/Automattic/jetpack/issues/16989#issuecomment-924115960) doesn't seem to have a connected Stripe account or a Donations block. If they reconnect their Stripe account and have an issue with a non-Donation plan, the original fix in this issue of deleting the plan (via Calypso), recreating it, and updating the button should work.

**Comment by isocialtish** [comment] 2021-11-03 21:29
> @isocialtish: Can you provide a url to the page with the broken Donation block?

Home page, right under the blue and yellow logo that says "leddysetgo productions" is a blank whitespace area. This is where the donation block is, so if you click in this area you'll see the error.

**Comment by michaeldcain** [comment] 2021-11-03 21:33
@isocialtish: I've deleted the donations plans for that user. Can you have the user delete the donations block, save and reload the editor, and add a new donations block?

**Comment by michaeldcain** [comment] 2021-11-03 21:38
@donalirl: I don't see where [this user](https://github.com/Automattic/jetpack/issues/16989#issuecomment-907704513) has any Payments Blocks active. Can you provide a url to the page with the broken Donation block?

**Comment by michaeldcain** [comment] 2021-11-03 21:42
@ClassicRKR27: [this user](https://github.com/Automattic/jetpack/issues/16989#issuecomment-907645413) seems to be fixed.

**Comment by donalirl** [comment] 2021-11-05 04:19
> @donalirl: I don't see where [this user](https://github.com/Automattic/jetpack/issues/16989#issuecomment-907704513) has any Payments Blocks active. Can you provide a url to the page with the broken Donation block?

Yes, it's here (Premium Content block): https://live-life-healthy-and-fit-health.com/2021/08/26/common-genetically-modified-foods/?

**Comment by sbathompson-he** [comment] 2021-11-05 17:04
Howdy! This user reported this and was not able to fix it by disconnecting and reconnecting.
32585701-hc
https://thefreedomgrind.blog/products-and-services/

**Comment by marianearchimbaud** [comment] 2021-11-05 17:06
Same case here: 32502119-hc
It seems like the suer used this same Stripe account for another site.
https://wellsbaum.blog/stepping-into-the-future/

**Comment by dragstor** [comment] 2021-11-11 14:15
I had a chatter today with the same issue: **32599701-HC**

✅  Got it resolved by following the steps from this comment: https://github.com/Automattic/jetpack/issues/16989#issuecomment-740564174

**Comment by jordesign** [comment] 2021-11-16 23:26
@michaeldcain When you're able - could you please also run the patch for the most recently reported cases:

* https://github.com/Automattic/jetpack/issues/16989#issuecomment-961616901
* https://github.com/Automattic/jetpack/issues/16989#issuecomment-962064559
* https://github.com/Automattic/jetpack/issues/16989#issuecomment-962066110

**Comment by reginabally** [comment] 2021-11-17 05:58
I'm following up on [this comment](https://github.com/Automattic/jetpack/issues/16989#issuecomment-932475812).

@michaeldcain Can you please run the script for the site https://730romanticrelationships.com?

Product page: https://730romanticrelationships.com/products/

**Comment by wpshellbelle** [comment] 2021-11-17 17:45
Another report at 24105836-hc
Donation Block is not working on site. Reconnecting Stripe didn't help. No existing payment plans. 

@michaeldcain Can you please run the script mentioned above for the site https://prjktpayday.com/

**Comment by seanbelly** [comment] 2021-11-18 15:58
Another report here: 4465636-zd-woothemes
Donation block reports sales disabled. 
Deleted plan and created a new one, awaiting response.

**Comment by metabreakr** [comment] 2021-11-18 20:57
4466307-zen

**Comment by kosiew** [comment] 2021-11-19 07:14
Hi @DavidRothstein ,
Can you run the script for site id 182812520 ?
ref: #4463364-zen

**Comment by gabriel-fuentes** [comment] 2021-11-20 23:53
4532641-zen

**Comment by syds87** [comment] 2021-11-21 11:55
Hi @michaeldcain ,

Could you run the same script for site id 179630244 as well?
Reported in #4533699-zen

**Comment by spsiddarthan** [comment] 2021-11-22 06:59
Hi @michaeldcain, 

The website mentioned in 4458035-zen  appears to have the same issue and needs to be fixed/looked at again. 

Issue summary: The Donations block was throwing off an error saying that the Plan is not found. 

What has the user tried so far:
- Remove the donation block from your pages/posts.
- Save those pages/posts without the block.
- Reload the editor again and then add a new donation block.

The above steps didn't help them resolve the issue.

**Comment by KirkwallDay** [comment] 2021-11-22 17:49
Hi @michaeldcain I have a user in this ticket: 4466307-zen with a donations block showing the "Sales disabled" message.

They have tried removing and re-adding the block.

Can you run the script for rbkande.wordpress.com

URL for the page is: rbkande.wordpress.com/2021/07/12/example-post-3/

**Comment by ccwalburn** [comment] 2021-11-24 15:05
4466307-zen 
I let the user know that the issue has been fixed and they can remove the donations block and re-add it following  @michaeldcain 's steps.

**Comment by poeticabdul** [comment] 2021-11-24 16:51
For 4466307-zen user is back, running the script didn't work for them @michaeldcain 

For now, I have suggested they recreate the donation block in a new test post and let us know how that goes

**Comment by bizanimesh** [comment] 2021-11-30 00:55
> Hi @michaeldcain,
> 
> The website (blog id: 183549065) mentioned in 4458035-zen appears to have the same issue and needs to be fixed/looked at again.
> 
> Issue summary: The Donations block was throwing off an error saying that the Plan is not found.
> 
> What has the user tried so far:
> 
> * Remove the donation block from your pages/posts.
> * Save those pages/posts without the block.
> * Reload the editor again and then add a new donation block.
> 
> The above steps didn't help them resolve the issue.

Hey @michaeldcain - is there any other thing that we can try?

**Comment by annbingle** [comment] 2021-12-02 21:45
Same issue reported here - 26896965-hc using the Payments Block. I had them delete their current Payments Plan and create a new one. Also, remove and create a new Payments button on their on About page but still the same error.

**Comment by AnthonyFaxlandez** [comment] 2021-12-07 07:11
@michaeldcain Hey! Wanted to check and see if you had a chance to take another look at this one yet? 🙂

**Comment by bobmatyas** [comment] 2021-12-08 22:14
@michaeldcain Can you take a look and advise if there is anything else we can do? https://github.com/Automattic/jetpack/issues/16989#issuecomment-982179383

**Comment by goblinartificer** [comment] 2021-12-23 21:02
another case in 33337017-hc. No donation/payment plans visible, before or after removing/readding blocks or disconnecting/reconnecting Stripe. Problem still persists.

**Comment by ccwalburn** [comment] 2021-12-28 15:59
Another report here: 4642555-zen

@michaeldcain - It looks like the fix we tried for a similar situation here 4466307-zen didn't work; is it worth trying for this user or is there another workaround?

**Comment by rinazrina** [comment] 2021-12-29 04:06
Related to the above ^ [4642555-zen](4642555-zd-woothemes)

Removing the button and adding it again did not work for this user.

**Comment by Codexpart** [comment] 2021-12-29 05:29
Another report here: 4642725-zen

**Comment by nagpai** [comment] 2021-12-31 07:35
For case 4642555-zen - The user also has a WC Payment account ( linked to Stripe Express - check Blog RC or search Stripe Dashboard with the user's email ). My hypothesis (could be wrong), is that if their browser had the session of the Stripe Express on while creating the payment block, this may get latched on to the WP.com Donate block and cause errors ( since it is not a regular Stripe account ) 

User has now moved on to use GiveWP.

**Comment by kylemcph** [comment] 2022-01-04 15:51
Another report 31887032-hc / 4659106-zen. Removing the button and adding it again did not work for this user.

**Comment by arinoch** [comment] 2022-01-06 03:50
+1: 4656029-zd-woothemes

Deleting and re-adding the block didn't fix.

**Comment by gabriel-fuentes** [comment] 2022-01-15 17:23
4689801-zd

**Comment by devNigel** [comment] 2022-01-21 02:16
Another case: 33770811-hc

**Comment by allanftd** [comment] 2022-01-21 07:34
Another case, user followed up today 33772060-hc 4706551-zd

**Comment by ClassicRKR27** [comment] 2022-01-25 14:33
Have another case here: 3687943-hc

**Comment by donalirl** [comment] 2022-01-30 23:52
Seen in #33586431-hc. Would it be possible to run a fix to get their payments working again, @michaeldcain ?

We tried deleting old payment plan and creating a new one. No change. They also checked their Stripe account but saw no errors present.

**Comment by jordesign** [comment] 2022-02-15 10:34
Another instance in #4779784-zen. User with donations block - so couldn't create a new payment plan. Re-adding new block and dis/reconnection Stripe connection had no impact.

I'm going to go back through this thread to check the current status - and see what our next steps might be.

**Comment by thekingsprojects** [comment] 2022-02-26 00:20
Another case here: 4810674-zen

I've asked them to try recreating the block and dis/reconnecting Stripe; hopefully that will work!

**Comment by rw-ye** [comment] 2022-02-27 03:13
Iv'e closed 4779784-zd-woothemes

Please re-open a new ticket with the user when a fix has been deployed.

**Comment by happychait** [comment] 2022-03-23 04:03
Another one with the Payments block, in 30713789-hc.

I followed up in 4884217-zen and suggested trying the workaround of removing the existing Payments plans and Stripe connection and re-adding everything.

**Comment by desnum** [comment] 2022-04-15 15:20
<img width="500" alt="Screen Shot 2022-04-15 at 11 05 50 AM" src="https://user-images.githubusercontent.com/43796228/163588248-a8f8251c-3c00-4eb3-b1cb-ea2bb4f51cc3.png">

Another case for the Donations block on 35135522-hc. I had them disconnect and reconnect Stripe. The message then changed to this on my end:
<img width="543" alt="Screen Shot 2022-04-15 at 11 18 42 AM" src="https://user-images.githubusercontent.com/43796228/163588630-5595535f-00af-4394-ad0f-cf58cdb47e2e.png">

Then the user removed and re-added the Donations block, which circled us back to the first "Sales Disabled" error

**Comment by ClassicRKR27** [comment] 2022-05-03 20:38
Another report here: 5185542-zd-woothemes

User has tried reconnecting, re-adding - nothing worked.

**Comment by marutim** [comment] 2022-06-27 11:50
Another report here: 15332414-hc

The user created a new payment button, added a new plan, and then disconnected and reconnected Stripe but that did not work.

- [ ] User returned here 5345255-zd-woothemes. They request to be notified when the issue is resolved.

**Comment by aleone89** [comment] 2022-06-29 17:42
Another report here: zen-5336271

Have asked the user to disconnect Stripe and recreate the donation form.

**Comment by pottedmeat** [comment] 2022-07-06 21:41
> Another case for the Donations block on 35135522-hc.

This account still has the donation block set up and I was able to inspect their site to see what could have happened:

```
> gprjson SELECT * FROM wp_205306317_posts WHERE post_type = 'jp_mem_plan' AND post_name = 'donation'
[
    {
        "ID": "271",
        "post_author": "220036949",
        "post_date": "2022-04-15 11:22:39",
        "post_date_gmt": "2022-04-15 15:22:39",
        "post_content": "",
        "post_title": "Donation",
        "post_excerpt": "",
        "post_status": "publish",
        "comment_status": "closed",
        "ping_status": "closed",
        "post_password": "",
        "post_name": "donation",
        "to_ping": "",
        "pinged": "",
        "post_modified": "2022-04-15 11:22:39",
        "post_modified_gmt": "2022-04-15 15:22:39",
        "post_content_filtered": "",
        "post_parent": "0",
        "guid": "https:\/\/leanneslifechangingfairies.com\/?jp_mem_plan=donation",
        "menu_order": "0",
        "post_type": "jp_mem_plan",
        "post_mime_type": "",
        "comment_count": "0"
    }
]
> gpr SELECT * FROM wp_205306317_postmeta WHERE post_id = 271
+---------+---------+---------------------------------------+----------------------------------------------------+
| meta_id | post_id | meta_key                              | meta_value                                         |
+---------+---------+---------------------------------------+----------------------------------------------------+
| 2345    | 271     | _jetpack_post_is_public               |                                                    |
| 2346    | 271     | _jetpack_post_is_excluded_from_search | 1                                                  |
| 2347    | 271     | permalink                             | https://leanneslifechangingfairies.com/?jp_mem_pla |
| 2348    | 271     | _jetpack_amp_permalink                | https://leanneslifechangingfairies.com/?jp_mem_pla |
| 2349    | 271     | _jetpack_post_author_external_id      | 220036949                                          |
| 2350    | 271     | _jetpack_post_modified                | 2022-04-15 11:22:39                                |
| 2351    | 271     | _jetpack_post_modified_gmt            | 2022-04-15 15:22:39                                |
| 2352    | 271     | _jetpack_remote_meta_ids              | a:2:{i:474;i:2353;i:475;i:2354;}                   |
| 2353    | 271     | jetpack_memberships_price             | 5.00                                               |
| 2354    | 271     | jetpack_memberships_currency          | USD                                                |
| 2387    | 271     | _elasticsearch_indexed_on             | 2022-04-15 15:24:41                                |
+---------+---------+---------------------------------------+----------------------------------------------------+
```

Important to notice is that much of the `jetpack_memberships_*` values are missing from the postmeta. Without `jetpack_memberships_acct_id`, disconnecting Stripe won't delete the donation products. Interestingly, all of the payment products created for this site lack these fields. I'll be looking into this more closely soon.

**Comment by pottedmeat** [comment] 2022-07-07 21:48
Patch created in D83897-code

**Comment by Greatdane** [comment] 2022-07-12 04:59
Another here; 5366412-zd-woothemes

Asked the user to reconnect Stripe and recreate the donation form.

**Comment by annbingle** [comment] 2022-07-17 15:46
Another report here, 5399788-zen

I asked them to disconnect/reconnect Stripe and recreate the Payments Block buttons.

**Comment by sirbrillig** [comment] 2022-07-19 17:35
Since D83897-code is merged, I assume this is resolved and I'm going to close this.

**Comment by pottedmeat** [comment] 2022-08-22 14:25
An additional patch is needed D85900-code

**Comment by sirbrillig** [comment] 2022-08-22 23:42
👍

**Comment by galakhyati** [comment] 2022-09-30 12:48
Found another case on https://e-meds.org/
Chat: 37097029-hc
Followup: 5596252-zd-woothemes

**Comment by Greatdane** [comment] 2022-10-01 05:02
Another: 5583308-zd-woothemes

**Comment by pottedmeat** [comment] 2022-10-03 20:09
Once their Stripe account is confirmed by an HE in the "Earn Tools" section of the blog report card, the user should be able to hit "Edit" on the page in question then hit "Publish" once the payment plans are assigned to any payment blocks.

**Comment by pottedmeat** [comment] 2022-10-03 20:09
Tickets have been updated with feedback.

**Closed by pottedmeat** 2022-10-03 20:09 UTC
Labels: [Type] Bug, [Block] Payment Button, [Type] Happiness Request, Earn, [Block] Premium Content, Payments: Solved by Woo, [Block] Donations, [Interaction #] > 50

**Comment by CodeAllNightNDay** [comment] 2022-12-07 15:36
Had a case here: 38555125-hc
