### ISSUE TITLE
Sharing Buttons:  problems saving options on custom post types in Calypso

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/jetpack#9126] opened 2018-03-22 18:12 UTC
#### Steps to reproduce the issue
1. Go edit your Sharing options in Calypso
2. Save sharing buttons on a Custom Post type (Product in my case)
3. This might be specific to sites with WooCommerce installed, not sure.

#### What I expected
I expected it to save!

#### What happened instead
It did not save.

If you look at Calypso, my site has a lot of sharing button options:
![screen shot 2018-03-22 at 11 01 51 am](https://user-images.githubusercontent.com/3220162/37789173-76cd5958-2dc0-11e8-92cf-d48ae5a8571f.png)

That's a bit strange - Order, Feedback, Revisions, Product & Products?  What is going on?  Some of those should not be sharable.

I tried first saving Product, but when the page refreshes, the option just doesn't save!
![jp-sharing](https://user-images.githubusercontent.com/3220162/37789334-de18924e-2dc0-11e8-91b0-69bdca7c361e.gif)

Let me try to save Products now, that works!

But then, if I save Media... prepare yourselves:
![media-saved](https://user-images.githubusercontent.com/3220162/37789564-7a604ade-2dc1-11e8-9763-27e1a25038d6.gif)

Now nothing is clickable!  I can't uncheck, check... it's a big mess.
The solution ended up being that I had to go back to my site, and then uncheck Media, Save - and then the options in Calypso worked again.

What I think should happen:
- [ ] We should not show Post Types in Calypso which are invalid / not shareable (Orders, Revisions, Product)
- [ ] We should not break things when Media is shared

Bonus:  When I'm done saving this in Calypso- how in the world do I get back to my site?  I just wanted to save a setting and now I'm totally lost and can't get back to where I was and this leaves me mad at Jetpack.

**Comment by designsimply** [comment] 2018-03-22 23:51
Thanks for the report! I think this is a duplicate of https://github.com/Automattic/wp-calypso/issues/22811 and that it's a Calypso issue, so I'm going to close this one in favor of the other. Please re-open if you have a look at the other issue and think a jetpack-specific report is still needed.

<blockquote>When I'm done saving this in Calypso- how in the world do I get back to my site? I just wanted to save a setting and now I'm totally lost and can't get back to where I was and this leaves me mad at Jetpack.</blockquote>

There might be some places where options are only available in one place or the other. We are trying to close the gaps, but some areas may take a bit more time. I'd be happy to help review the specific flow you're thinking of with you in a bit more detail if you'd like to start a post on an internal blog such as +kibbling or a public testing blog such as https://test.wordpress.com/ and tag me.

**Closed by designsimply** 2018-03-22 23:51 UTC
Labels: Sharing, [Type] Bug
