### ISSUE TITLE
Improve Pinterest support in social menu links

### ISSUE THREAD

**Issue by BinaryMoon** [Automattic/jetpack#8831] opened 2018-02-13 20:15 UTC
Hi - I have had a user on wordpress.com try to add a link to their pinterest account using the social menu but the link did not display. It turned out she was using a pinterest.co.uk link instead of pinterest.com. I checked a bit more and it seems that pinterest are using all of the major local domains (.co.uk, .de, .se, .fr etc)

The css that needs changing is in here:
https://github.com/Automattic/jetpack/blob/master/modules/theme-tools/social-menu/social-menu.css#L123-L126

I wonder if it could be changed to the following

```
/* Pinterest */
.jetpack-social-navigation-genericons a[href*="pinterest."]:before {
	content: "\f210";
}
```

As an aside - I checked the docs for the social menu and it's a bit out of date. The list of links is wrong and it suggests using Jetpacks custom css.
https://jetpack.com/support/extra-sidebar-widgets/social-media-icons/

**Comment by jeherve** [comment] 2018-02-15 11:19
Thanks for the report. I'll close it as duplicate of #8422

> I checked the docs for the social menu and it's a bit out of date.

Thanks! We'll get that updated!

**Closed by jeherve** 2018-02-15 11:19 UTC
Labels: Extra Sidebar Widgets
