### ISSUE TITLE
Boost: Deferring non-essential JS causes GetResponse contact forms to display in site footer

### ISSUE THREAD

**Issue by lakellie** [Automattic/jetpack#22199] opened 2022-01-03 19:47 UTC
### Impacted plugin

Boost

### Steps to Reproduce

1. Activate Boost and turn on non-essential JS deferral
2. Insert the embed code for a GetResponse form onto a page (for example, by using the Custom HTML block in the block editor)

### A clear and concise description of what you expected to happen.

Form should be embedded on the page in the same spot the code was inserted.

### What actually happened

Form is displayed at the bottom of the site footer. 

Form displays in the correct spot if non-essential JS deferral is disabled. 

### Other information

I have an example GetResponse form code snippet that I used to test and replicate this on my own site, but I don't want to share the exact snippet here because it's an actual form sent to us by the Boost user who encountered this issue. However, I will share the general format of the code snippet, with the IDs stripped out and replaced with ***s. Hopefully that will be enough info to debug this, but if not, reach out to me and I can send you the actual snippet.

```
<script type='text/javascript' src='https://app.getresponse.com/view_webform_v2.js?u=***&amp;webforms_id=***' data-webform-id='***'></script>
```

### Browser

Chrome/Chromium

**Comment by thingalon** [comment] 2022-01-06 05:29
Hi @lakellie! Thanks for the report and your initial investigation. 

Do you know how the user adds the script to their site? Do they manually paste the script tags in?

If so they can fix the issue by adding an HTML attribute to their script tag called `data-jetpack-boost` with a value of `ignore` like so:

```
<script data-jetpack-boost="ignore" src=".......">
</script>
```

Can you let me know if that helps?

**Comment by thingalon** [comment] 2022-01-06 05:34
P.S: I've filed a new issue for us to document these sorts of internal tricks for HEs and users alike. https://github.com/Automattic/jetpack/issues/22235

**Comment by lakellie** [comment] 2022-01-06 21:37
Hey @thingalon thanks so much for the tip! I'll reach out to the user and suggest this. Documenting internally too is a great idea - thanks for getting the ball rolling on that!

**Comment by jenhooks** [comment] 2022-01-08 15:18
Hi @thingalon - I have a few updates from the user:

> But unfortunately, the code doesn't work. After activating Defer-Non essential in boost, the form is pushed down to the footer. I have attached a screenshot for verification.

![Screen Shot 2022-01-08 at 10 16 29 AM](https://user-images.githubusercontent.com/7585054/148649537-b5992851-7874-4f5e-adf4-c6d4720a709a.png)

_and_ 

> I read this on WordPress.org and think this issue might not be related to Getresponse JS but the way the JetPack Boost is developed to handle JS files. You may want to take a look at it (https://wordpress.org/support/topic/how-does-jetpack-boost-deals-with-javascript/).
> 
> Read the response from the JetPack plugin support tech.

**Comment by thingalon** [comment] 2022-01-10 01:10
@jenhooks this is a tiny bit embarrassing, but the problem is that our code detecting `data-jetpack-boost="ignore"` is too fussy, and requires double-quotes on the attribute.

This should work for the user if they change from `data-jetpack-boost='ignore'` to `data-jetpack-boost="ignore"`.

I've [filed a new issue](https://github.com/Automattic/jetpack/issues/22268) for us to address this in a future release of Jetpack Boost but in the meantime the user should use double-quotes on the attribute.

**Comment by AnthonyFaxlandez** [comment] 2022-01-10 19:00
It looks like the double quotes did the trick! Since there is a new issue filed to address it in the future, I'm closing this one out. Thank you!

**Closed by AnthonyFaxlandez** 2022-01-10 19:00 UTC
Labels: [Type] Bug, [Plugin] Boost, [Boost Feature] Defer JS
