### ISSUE TITLE
Shortcode: Twitter embed doesn't embed with trailing slash

### ISSUE THREAD

**Issue by spencerberry** [Automattic/jetpack#10864] opened 2018-12-06 23:05 UTC
#### Steps to reproduce the issue

1. Publish a post with a tweet in it, like `https://twitter.com/photomatt/status/1070800752120074242/` or `[tweet https://twitter.com/photomatt/status/1070800752120074242/ ]` and it won't embed.
2. Remove the trailing slash.
3. Now it works.

![screen shot 2018-12-06 at 3 04 16 pm](https://user-images.githubusercontent.com/1162736/49617144-37a0cc00-f968-11e8-977a-0ff2ec3eb8fb.png)

**Comment by jeherve** [comment] 2018-12-07 12:43
Closing as duplicate of https://github.com/WordPress/gutenberg/issues/12664

**Closed by jeherve** 2018-12-07 12:43 UTC
Labels: Shortcodes, [Type] Bug, [Type] Duplicate
