### ISSUE TITLE
Thumbnails in the Latest Posts block are displayed or not depending if Jetpack is connected

### ISSUE THREAD

**Issue by pehaa** [Automattic/jetpack#29286] opened 2023-03-03 15:00 UTC
### Impacted plugin

Jetpack

### Quick summary

There is a significant inconsistency in the **Latest Posts** block layout depending on if Jetpack is connected or not.
This issue does not affect all themes, but I was able to confirm it with Twenty Twenty-One, Twenty Twenty and Twenty Nineteen and 

It does not affect block themes (no Customizer).

### Steps to reproduce

1. Add a few posts and set featured images for them.
2. Add a new **page** and add the **Latest Posts** block.
3. In the block settings, switch on **Display featured image**.
4. Install, activate and connect Jetpack, this will add the **Content Options** tab in **Appearance > Customize**
5. Open **Customize > Content Options** and UNCHECK **Display on pages** in the **Featured Images** section
6. Check the frontend view of the page with the Latest posts block - thumbnails are not displayed
7. Disconnect Jetpack
8. Check the frontend view of the page with the Latest posts block again - thumbnails are displayed.

### A clear and concise description of what you expected to happen.

We should have consistent behavior regardless if Jetpack is activated or now. 

I am not sure if thumbnails should be or not be displayed on the page (given the unchecked **Display on pages** setting). Still, this should not depend on the Jetpack connection. 

### What actually happened

When Jetpack is connected, image thumbnails within the Latest Posts block are not displayed on the frontent. They appear when you disconnect Jetpack.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Self-hosted

**Comment by pehaa** [comment] 2023-03-03 15:00
cc @zinigor

**Comment by jeherve** [comment] 2023-03-06 08:35
closing as duplicate of 8116-gh-jpop-issues

**Comment by jeherve** [comment] 2023-04-07 08:37
After investigation, this appears to be caused by one of Jetpack's Theme Tools, content options:
https://jetpack.com/support/content-options/

We declare support for Content Options for those themes in Jetpack:

https://github.com/Automattic/jetpack/blob/3a3c4adc1c0913bac224ddb832713bd6101fe1ab/projects/plugins/jetpack/modules/theme-tools/compat/twentytwentyone.php#L32-L50
https://github.com/Automattic/jetpack/blob/3a3c4adc1c0913bac224ddb832713bd6101fe1ab/projects/plugins/jetpack/modules/theme-tools/compat/twentytwenty.php#L34-L52
https://github.com/Automattic/jetpack/blob/3a3c4adc1c0913bac224ddb832713bd6101fe1ab/projects/plugins/jetpack/modules/theme-tools/compat/twentynineteen.php#L37-L58

When you deactivate Jetpack, you lose access to all this, and thus the block starts looking different.

I think it would be fair to expect that Jetpack's Content Options should not impact the Latest Posts Block, since that block includes its own content settings that should take precedence.

Ideally, we would shortcircuit all our content altering functions here, whenever we're in a block:
https://github.com/Automattic/jetpack/blob/3a3c4adc1c0913bac224ddb832713bd6101fe1ab/projects/plugins/jetpack/modules/theme-tools/content-options.php#L44-L53

Unfortunately, and given how and when the block is built, it may not be simple.

**Comment by Aurorum** [comment] 2023-12-23 07:54
7453720-zen - user would like to be informed when fixed 

I tried to dig into this, but it is, indeed, very frustrating to fix. I suppose one solution might be wrapping thumbnails in a class whenever there's a block on the page, and then using CSS to hide the thumbnails, but that feels less than ideal.

**Comment by Aurorum** [comment] 2023-12-24 07:18
7484074-zen

**Comment by Aurorum** [comment] 2023-12-24 08:15
7485965-zen

**Comment by Aurorum** [comment] 2023-12-24 18:09
7482639-zen

**Comment by Aurorum** [comment] 2023-12-24 18:09
7482639-zen

**Comment by Aurorum** [comment] 2023-12-24 18:33
7493007-zen

**Comment by Aurorum** [comment] 2023-12-24 18:40
This has become quite problematic since Automattic/themes#7518, which introduced Content Options to Varia and all its child themes, which is a lot of the WP.com directory - wonder if it's possible to bump the priority on this? I'd argue it's probably High at this point (see number of interactions in Automattic/wp-calypso#85369 and Automattic/wp-calypso#85672). 

I've given it a go but no luck on a fix. It was decided that the Varia change shouldn't be reverted in Automattic/themes#7568 because of those who have might be using the new settings since it was introduced.

**Comment by Greatdane** [comment] 2023-12-28 00:47
I can say, anecdotally, I am seeing this issue daily. More reports are here; https://github.com/Automattic/wp-calypso/issues/85672

**Comment by Aurorum** [comment] 2023-12-28 23:39
> I suppose one solution might be wrapping thumbnails in a class whenever there's a block on the page, and then using CSS to hide the thumbnails, but that feels less than ideal.

TBH, I think there's enough cases of this bug to justify fixing it through whatever mechanism, so I've proposed this in #34805.

**Comment by Aurorum** [comment] 2024-01-03 21:56
7523952-zen

**Comment by anomiex** [comment] 2024-01-03 22:17
Some brainstorming of other ways we might fix blocks displaying featured images than by hiding them with CSS:

* Since it looks like the actual featured image is added outside of 'the_content' while blocks are normally rendered inside `the_content`, we could abort the filter when `doing_filter( 'the_content' )`. Although I don't know if there are exceptions to that.
* Or, since blocks are going to be rendered by a call to some `WP_Block` method like `->render()`, we could do like this to see if we're called from something in that class and abort:
  ```php
  $trace = debug_backtrace( DEBUG_BACKTRACE_IGNORE_ARGS );
  foreach ( $trace as $frame ) {
          if ( ! empty( $frame['class'] ) && class_exists( $frame['class'], false ) && is_a( $frame['class'], WP_Block::class, true ) ) {
                  return $metadata;
          }
  }
  ```

**Comment by Aurorum** [comment] 2024-01-03 22:31
That's excellent - thanks so much! I tested option two since there might be exceptions to the first, and I got this warning when trying to change the PR:

>  74 | WARNING | [ ] debug_backtrace() found. Debug code should not normally be
     |         |     used in production.
     |         |     (WordPress.PHP.DevelopmentFunctions.error_log_debug_backtrace)

Do you think it's worth ignoring it in this case?

**Comment by anomiex** [comment] 2024-01-03 22:48
Yes. Assuming no one else objects to the idea anyway. 🙂

**Comment by Aurorum** [comment] 2024-01-03 22:50
👍 I've switched the PR to that approach since it tests nicely and avoids unnecessarily calling the images.

**Comment by Aurorum** [comment] 2024-01-04 19:45
7502636-zen - making a note that user would like to be informed when it's fixed

**Comment by Aurorum** [comment] 2024-01-04 20:08
7534525-zen

**Closed as completed** 2024-01-10 16:00 UTC
Labels: [Feature] Theme Tools, [Pri] Low, Customer Report [LEGACY], [Plugin] Jetpack

**Comment by Aurorum** [comment] 2024-01-14 18:43
Popped up in 7576516-zen too 

@anomiex, would you know if that patch has been deployed to Simple sites yet? I wonder if it's still awaiting release or if it doesn't work (is it possible that function names are changed on WP.com so that `debug_backtrace` won't work?)

**Comment by jeherve** [comment] 2024-01-15 09:49
@Aurorum It has been deployed to simple, yes.

**Comment by Aurorum** [comment] 2024-01-15 12:31
That's annoying - thanks for checking though! I've had another go in #35033.

**Comment by Aurorum** [comment] 2024-01-18 09:51
7603228-zen

**Comment by anomiex** [comment] 2024-01-18 15:04
The problem with Simple was that it wasn't using the Jetpack code, instead it had its own copy (details at https://github.com/Automattic/jetpack/pull/35033#issuecomment-1894222453).

D135079-code on Simple, which I've just deployed, updated it to use the Jetpack copy now.

**Comment by Aurorum** [comment] 2024-01-18 15:27
Thank you, and for all your help with fixing this. :)
