### ISSUE TITLE
Multiple Choice Block - Multiline text drops label to new line

### ISSUE THREAD

**Issue by janmckell** [Automattic/jetpack#34992] opened 2024-01-12 15:57 UTC
### Impacted plugin

Jetpack

### Quick summary

I tested that for the Multiple Choice Block, if the text in the option provided spans more than one line, then it drops the entire text area to a line below the input/checkbox.

### Steps to reproduce

Insert Form Block
Insert Multiple Choice Block
Write a line of text for an option which spans more than one line of text
In the Preview, the entire label drops below the input
<img width="750" alt="Screenshot 2024-01-07 at 2 06 17 PM" src="https://github.com/Automattic/jetpack/assets/84089207/31ca2a22-f844-4b02-bed0-5f265328867e">

### A clear and concise description of what you expected to happen.

I expected the line of text to stay on the same line as the input button, but the second line of text drop to a second line, below both input and label.

### What actually happened

The entire line of text dropped to the second line, beneath the input.

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Atomic

**Comment by janmckell** [comment] 2024-01-12 15:57
Happening here:
7548966-zd-a8c

**Comment by jeherve** [comment] 2024-01-15 09:52
@monsieur-z Could it be linked to #34272 and #34429?

**Comment by monsieur-z** [comment] 2024-01-15 19:30
I haven't been able to reproduce this on my side. Could you specify the Jetpack and browser versions used?

**Comment by janmckell** [comment] 2024-01-16 19:36
In the users site as well as my test site, Jetpack 13.0 is in use. I'm using a Chrome browser (Version 120.0.6099.216).

Please note the issue is happening when there is multi-line text in the multiple choice option. Note the screenshots below showing the Editor view and the live view ('Live view - multiple choice' → first image)
![Live view - multiple choice](https://github.com/Automattic/jetpack/assets/84089207/ae914a73-7a63-4a7d-afd1-81748bf839a0)
![Editor view - multiple choice](https://github.com/Automattic/jetpack/assets/84089207/5b2815a2-af77-4aac-987c-fa9b7ce23476)

**Comment by monsieur-z** [comment] 2024-01-17 16:31
Thank you @janmckell. I could see the issue now. When several Jetpack modules are activated, stylesheets are concatenated into a single file, and that file doesn't contain up-to-date styles. The issue's already been documented. I'll report back in this thread.

**Comment by monsieur-z** [comment] 2024-01-17 20:24
https://github.com/Automattic/jetpack/pull/35091 fixes the issue. It'll be included in the next Jetpack release.

**Comment by monsieur-z** [comment] 2024-01-30 21:24
This is working well with the bleeding-edge version of Jetpack. I'll close the issue since the fix has been merged with `trunk`.

The next Jetpack release (13.1) is scheduled for Feb. 6.

**Closed as completed by monsieur-z** 2024-01-30 21:24 UTC
Labels: Bug, [Feature] Forms, [Pri] Low, Customer Report [LEGACY], [Plugin] Jetpack, [Block] Form, Triaged, [Platform] Atomic, [Status] Priority Review Triggered, [Feature] Forms Blocks
