### ISSUE TITLE
[Boost] Improvements to messaging

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#28220] opened 2023-01-09 05:46 UTC
P2 link: pbNhbs-4Nw-p2

@augurlu has recommended a range of improvements to the copy around Critical CSS, to better explain the differences between the paid and free versions, and to explain to users when to regenerate their CSS.

See the linked P2 post for details.

**Comment by thingalon** [comment] 2023-01-10 01:28
Note: updated figmas here: pbNhbs-4Nw-p2#comment-12408

**Comment by haqadn** [comment] 2023-03-10 02:52
Duplicate of Automattic/boost-cloud#216

**Closed as completed by haqadn** 2023-03-10 02:52 UTC
Labels: Enhancement, [Status] In Progress, [Plugin] Boost
