### ISSUE TITLE
Autoresponder option on Form blocks

### ISSUE THREAD

**Issue by vinnykaur** [Automattic/jetpack#32653] opened 2023-08-24 09:55 UTC
### Impacted plugin

Jetpack

### What

Add a autorespond feature for the form blocks. An autoresponder email option is a feature that sends out an email to the person who submits the form.

**Comment by cuemarie** [comment] 2023-08-24 17:21
Duplicate of https://github.com/Automattic/jetpack/issues/32654

📌 ACTIONS
- Closed as duplicate

**Closed as not planned by cuemarie** 2023-08-24 17:21 UTC
Labels: [Closed] Duplicate, Enhancement, [Feature] Forms, [Plugin] Jetpack, [Block] Form, Needs triage, [Feature] Forms Blocks
