### ISSUE TITLE
No mention of Publicize after publishing

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#8925] opened 2018-02-23 15:47 UTC
If you activate Publicize and connect a service, we will auto-push your posts out to that service when you publish. There's no indication in the UI that we do it though, which feels like a lost opportunity to let people know what has happened.

Suggestion: after publishing a post, you get this from core WP:

![screen shot 2018-02-23 at 8 45 59 am](https://user-images.githubusercontent.com/108942/36602724-fdfc08a8-1875-11e8-98fa-9f518d8571ab.png)

I think we could relatively easily do something like:

![screen shot 2018-02-23 at 8 46 48 am](https://user-images.githubusercontent.com/108942/36602777-1ace0dc8-1876-11e8-8780-9bd3e0e60b42.png)

**Comment by jeherve** [comment] 2018-02-23 16:26
Also in #5151

**Comment by jeherve** [comment] 2018-02-23 16:32
Closing as duplicate of #5151

**Closed by jeherve** 2018-02-23 16:32 UTC
Labels: FixTheFlows, Publicize, [Type] Duplicate, [Type] Enhancement
