### ISSUE TITLE
[Payments] Donations Form block disappears after site transfers to AT

### ISSUE THREAD

**Issue by lizswafford** [Automattic/jetpack#32614] opened 2023-08-21 21:46 UTC
_Updated this report to reflect my findings from triaging. -cuemarie_

### Impacted plugin

Jetpack

### Quick summary

When a Donations Form block or Paid Content block are set up on a Simple site, and then the site transfers to AT, these blocks are hidden from the live site.  

### Steps to reproduce

1. Start a new page on a Simple Site
2. Add and set up each Payments block: Payment Buttons, Donations Form, and Paid Content
3. Follow the prompts to connect your account to Stripe if needed
5. Publish the page and view
6. Upgrade the site and activate hosting configuration
7. Refresh the published page

### A clear and concise description of what you expected to happen.

After transferring to AT, the Donations Block and Paid Content block should still appear on the page.

### What actually happened

The Donations Form and Paid Content block don't appear.

As a workaround, disconnecting/reconnecting Stripe helps to resolve the issue.

### Impact

Some

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

6699482-zd

**Comment by cuemarie** [comment] 2023-08-22 22:00
📌 REPRODUCTION RESULTS
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
I've been unable to replicate this so far. My AT test site shows a functioning Donations Form block in both the editor and live site, just as expected:

https://github.com/Automattic/jetpack/assets/27249804/61baba3f-8ced-4880-97c6-51fa8ab36bf4

---

I've seen this crop up a couple times in slack recently, though, so I know it's stumping HEs and customers alike. Example: p1692025141348829-slack-C03TY6J1A

Leaving open to see if we can spot a pattern between these reports. 

📌 ACTIONS
- Set to ON HOLD while we try to gather more intel.

**Comment by cuemarie** [comment] 2023-08-22 22:19
A little research into recent reports:

6699482-zen (helped by @lizswafford above)
- the user reported: `I purchased a package that is supposed to enable donations and payments through Stripe, but I keep getting an error when trying to connect to Stripe` & `I also get an email each time I try to connect saying "Action Needed! Update your Stripe account information to continue processing payments".`
- until they get their Stripe account connected to their WordPress.com site, I wouldn't expect the donations form to appear on this site, so this doesn't seem at the moment to reflect a bug.

6658947-zen / 6663025-zen (helped by @the-misha on 2023-08-14)
- we asked the user to check their stripe dashboard and/or try disconnecting/reconnecting, and that resolved it
- the user shared: `I've managed to solve the donations block issue. I set it up when I was using the free wordpress domain. Then when I upgraded my plan and bought my own domain, I think that's when this problem started.....I guess my Stripe account didn't get updated when I got my new domain. So I disconnected my stripe account on the wordpress dashboard, and then reactivated it...and then the problem got solved.`

Unknown interaction reported by another HE, who shared:
- `ran into a similar issue last week on an AT site. We fixed it by disconnecting stripe & reconnecting.  So I think we indeed may be looking at some type of bug.
Something that stands out to me is that it was a recently AT’d site, but the donation blocks were there prior to going AT.`
p1692114781808369/1692025141.348829-slack-C03TY6J1A

Testing upgrading an existing site of mine with working Donation Form blocks to AT to see if I can repro...

**Comment by cuemarie** [comment] 2023-08-22 22:32
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated** by going Atomic

📌 FINDINGS/SCREENSHOTS/VIDEO
Was able to replicate!  On my Premium plan site, I set up a page with Payment Buttons, Donations Form, and Paid Content.  Then I transferred to AT, and afterwards, the Donations Form and Paid Content blocks were hidden on the site. 

### Recording

_(Skip ahead to 1:30s to see the site AT and the page refresh showing the problem)_

https://github.com/Automattic/jetpack/assets/27249804/36f3957e-72f0-4cb4-916f-ee2acdecf0b9

📌 ACTIONS
- @Automattic/gold  FYI for the Earn Blocks
- Updated report with accurate steps to replicate

**Comment by cuemarie** [comment] 2023-08-22 22:49
I tried disconnecting and reconnecting this site to Stripe, but it's a pretty old connection, set up in 2021. Disconnecting goes as expected, but when I reconnect, and select the same account that I had connected to this site originally, I am directed to this:

`https://public-api.wordpress.com/rest/v1.1/me/stripe_connect/oauth/redirect?scope=read_write&code=ac_OV3QTPxtgTK6AxH9gAJzNMcHor2kxvgV&state=eyJibG9nX2lkIjoxOTQ4MTI0MDQsInVzZXJfaWQiOjIwMjAxODc2NCwibm9uY2UiOiIzOTc3OGM5ZWFjIiwic3JjIjoiY2FseXBzbyJ9`


![Image](https://github.com/Automattic/jetpack/assets/27249804/324e6d21-8a06-4d0b-b9dd-7e1de4c0814e)

So far all my attempts to resolve this have failed; my Earn page actually shows that I'm connected to Stripe again (after returning to the dashboard once I hit the error above), but my actual page still shows the missing blocks: https://mcqtestpremiumplan.wpcomstaging.com/earn-blocks-and-transferring-at/

Reported this part of the issue here: https://github.com/Automattic/jetpack/issues/32637

**Comment by cuemarie** [comment] 2023-08-23 19:33
Update, #32637 is resolved, so I've followed up with the user who was encountering `There was an error` as shown above and asked them to try again on the reconnection steps to workaround this issue. Follow up happened here: 6702507-zen

**Comment by millerf** [comment] 2023-08-24 06:32
> Follow up happened here: 6702507-zd-a8c

Unfortunately I don't have access...

**Comment by cuemarie** [comment] 2023-08-24 17:59
> Unfortunately I don't have access...

Hey @millerf ! I was mainly noting that for tracking purposes. The user replied and let us know that dis/reconnecting Stripe resolved the Donations Form block issue this report is about (disappearing after site goes AT).

LMK if I can get you anything else from the interactions noted on this issue!  They've all now dis/reconnected Stripe, so the users' sites are no longer presenting the problem, but the steps to resolve in the original report did consistently reproduce for me!

**Comment by cuemarie** [comment] 2023-09-18 19:54
Retitled to just cover Donations form block, as we also have a report of the Paid Content block now here: https://github.com/Automattic/jetpack/issues/33151

**Comment by cuemarie** [comment] 2023-09-18 19:56
Escalated here: p1695066962939419-slack-C01LXBU1N21

**Comment by n3f** [comment] 2023-09-22 23:38
Until this is properly fixed this solution might work: https://github.com/Automattic/jetpack/issues/33151#issuecomment-1730527209

> Running this from CLI seemed to clear this case: `option update jetpack-memberships-has-connected-account 1`

**Comment by philnick206** [comment] 2023-12-04 13:09
I encountered this issue in 7374275-zd-a8c

The workaround shared above resolved the issue.

**Comment by n3f** [comment] 2023-12-05 22:07
See D131026-code for additional changes necessary.

**Comment by n3f** [comment] 2023-12-06 17:33
Tested above change after merging update and it appears to work!

**Closed as completed by n3f** 2023-12-06 17:33 UTC
Labels: Bug, [Pri] Normal, Customer Report [LEGACY], Earn, [Block] Paid Content, [Block] Donations, Triaged, [Platform] Atomic, [Feature] Earn Blocks, [Feature Group] Customer Seller Experience

**Comment by kathrynwp** [comment] 2024-01-17 14:45
Ran into this issue in 7508117-zd-a8c

Running this in CLI made the form reappear:

`option update jetpack-memberships-has-connected-account 1`

@n3f Any idea why the issue would still be occurring if this issue is closed? Was it ever deployed? Thank you!

**Comment by n3f** [comment] 2024-01-17 18:27
If there was any sort of sync or backup applied it's possible that the setting was overwritten/deleted.  It's also possible that a site owner looking at the options (and not knowing what it's for) just deleted it...

**Comment by jp-imagines** [comment] 2024-02-14 21:47
Just came across another instance of this in 7731149-zd-a8c. 

The above CLI command again worked, though it's strange that the issue still somewhat exists. This particular site looks to have transferred to WoA on December 6 (possibly just a few hours before the above code was merged) – not sure if that's related, but it's worth noting.

**Comment by n3f** [comment] 2024-02-15 17:12
> This particular site looks to have transferred to WoA on December 6

That would almost definitely be the cause.  The "fix" was telling jetpack which options need to be preserved, so if the transfer occured before the plugin was updated then the option wasn't transferred with the site.
