### ISSUE TITLE
AMP: Add Social Sharing Buttons

### ISSUE THREAD

**Issue by supernovia** [Automattic/jetpack#10314] opened 2018-10-12 16:04 UTC
In the Jetpack forums, a user asked, "How do I make my social sharing buttons visible on AMP?" [#](https://wordpress.org/support/topic/how-do-i-make-my-social-sharing-buttons-visible-on-amp/)

#### Steps to reproduce the issue
Load any page in AMP; notice lack of sharing buttons.

#### What I expected
I know AMP is pretty stripped down and doesn't allow scripts and what not, but this might work:
https://www.ampproject.org/docs/reference/components/amp-social-share
https://ampbyexample.com/components/amp-social-share/

**Comment by gravityrail** [comment] 2018-12-11 18:43
Interesting. I am not able to reproduce this, at least with AMP 1.0.

**Comment by gravityrail** [comment] 2018-12-11 18:44
We should check whether this fixes their issue: https://github.com/Automattic/jetpack/pull/10945

**Comment by jeherve** [comment] 2019-01-07 14:22
@kristarella It does indeed seem like the same issue. This should be fixed in 6.9, scheduled to be released later this week, thanks to #10945

**Closed by jeherve** 2019-01-07 14:22 UTC
Labels: AMP, Sharing, [Type] Enhancement
