### ISSUE TITLE
Boost: ISA stats incomplete when it "completes", requires reload of page to update.

### ISSUE THREAD

**Issue by donnchawp** [Automattic/jetpack#32049] opened 2023-07-25 09:15 UTC
When the Image Size Analysis (ISA) is run on a site with lots of images the Boost settings page may show a "completed" message before the jobs are finished.
As a result, it will either show a smaller number of issues were found "after scanning 100 pages", and this number does not increase, or it will congratulate the user because no issues were found. A reload of the settings page later will show updates to that message if (more) issues were found.

I noticed "no issues found" message appears when there are no issues in the homepage and the first number of posts. The first post that caused an issue to appear was on page 2 of the site. My other blog has posts with issues that are linked from the homepage.

**Comment by dilirity** [comment] 2023-07-28 11:23
With https://github.com/Automattic/boost-cloud/pull/337 done, this should be fixed. I couldn't reproduce it.

**Comment by haqadn** [comment] 2023-08-15 09:32
Fixed via https://github.com/Automattic/boost-cloud/pull/337

**Closed as completed by haqadn** 2023-08-15 09:32 UTC
Labels: [Plugin] Boost, [Boost Feature] Image Guide
