### ISSUE TITLE
Feedback: CSV Export Fails

### ISSUE THREAD

**Issue by csonnek** [Automattic/jetpack#24159] opened 2022-04-28 20:04 UTC
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Have a contact form or other form on your site. Fill out the form to submit a single entry. 
2. Go to wp-admin dashboard and go to Feedback -> Form Responses. 
3. Scroll down to "Export responses as CSV" and click the "Download" button. Choosing anything under "Select responses to download" has no impact. 
4. Page will refresh to an error message to `wp-admin/admin-post.php` or `ERR_INVALID_RESPONSE`

### A clear and concise description of what you expected to happen.

I should have gotten a .csv download file. 

### What actually happened

Page errors out. 

### Other information

I can replicate the error on both a self-hosted Jetpack site and on a WordPress.com - clicking the download button redirects to `wp-admin/admin-post.php` with the `ERR_INVALID_RESPONSE` error message.

### Operating System

macOS

### Browser

Chrome/Chromium

**Comment by jeherve** [comment] 2022-04-29 08:31
Closing as duplicate of #24170

**Closed by jeherve** 2022-04-29 08:31 UTC
Labels: [Type] Bug, Contact Form, [Plugin] Jetpack
