### ISSUE TITLE
Upload image from a URL fails with PHP error

### ISSUE THREAD

**Issue by johngodley** [Automattic/jetpack#7339] opened 2017-06-13 13:13 UTC
Using 'Add URL' from Calypso on a Jetpack 5.0 site results in the request failing and this PHP error:

```
PHP Fatal error:  Uncaught Error: Class 'Jetpack_Media_Sync' not found in
XXX/wp-content/plugins/jetpack/json-endpoints/class.wpcom-json-api-upload-media-v1-1-endpoint.php:31
```

#### Steps to reproduce the issue

1. Use Calypso to add URL to a Jetpack site
1. See an error in Calypso and the PHP error on the Jetpack site

**Comment by kraftbj** [comment] 2017-06-14 22:24
The `Jetpack_Media_Sync` is only defined on wp.com `/wp-content/mu-plugins/videopress/jetpack-media-sync.php` and looks like should not be brought over. My first read suggests the endpoint need to check context before assuming it is there.

**Comment by seejacobscott** [comment] 2017-06-14 22:25
similar report here: 3259091-t

**Comment by dereksmart** [comment] 2017-06-28 21:19
@dbtlr is looks like that's referencing a class defined in the wpcom codebase in a /videopress path.  Do you think you could have a look?

**Comment by dbtlr** [comment] 2017-06-28 21:21
Yep, that is the class that contains the logic in the wpcom codebase to call back to the Jetpack site. Forgive my ignorance, but I'm not sure what you need me to do here.

**Comment by dereksmart** [comment] 2017-06-28 21:23
@dbtlr It looks like the problem is when trying to use the `/media/new` endpoint on a Jetpack site, since that class is not defined anywhere in the Jetpack code base, it's throwing a fatal #7401

**Comment by seejacobscott** [comment] 2017-06-28 22:04
3290633-t

**Comment by dbtlr** [comment] 2017-06-29 14:44
@seejacobscott - That particular error is related to wordpress.com itself having issues talking to the Jetpack site, which is likely not related to this particular problem.

**Comment by kraftbj** [comment] 2017-06-29 22:04
@dbtlr The failure to communicate is because the Jetpack site is returning a 500, which is the error in the original post. In other words, that's the message clients are getting back when attempting to use the `media/new` endpoint on Jetpack sites.

**Comment by dbtlr** [comment] 2017-06-30 02:13
Right, the media/new endpoint (for VideoPress) should ONLY execute in the WPcom context, so unless someone changed this, then this code shouldn't even be in Jetpack.

I'll take a look, but it would be nice to understand if something got changed.

**Comment by dbtlr** [comment] 2017-06-30 02:57
I pushed a fix for the WPCOM error that appears to have happened when the WPCOM endpoint was merged into Jetpack without testing. This is now in sync on both WPCOM and in #7408 

This has now uncovered another error with HMAC testing:

```
[30-Jun-2017 02:50:38 UTC] PHP Warning:  hash_hmac_file(): Filename cannot be empty in .../wp-content/plugins/jetpack/class.jetpack.php on line 3375
[30-Jun-2017 02:50:38 UTC] PHP Stack trace:
[30-Jun-2017 02:50:38 UTC] PHP   1. {main}() .../wp-admin/admin-ajax.php:0
[30-Jun-2017 02:50:38 UTC] PHP   2. do_action() .../wp-admin/admin-ajax.php:101
[30-Jun-2017 02:50:38 UTC] PHP   3. WP_Hook->do_action() .../wp-includes/plugin.php:453
[30-Jun-2017 02:50:38 UTC] PHP   4. WP_Hook->apply_filters() .../wp-includes/class-wp-hook.php:323
[30-Jun-2017 02:50:38 UTC] PHP   5. Jetpack->remote_request_handlers() .../wp-includes/class-wp-hook.php:298
[30-Jun-2017 02:50:38 UTC] PHP   6. Jetpack->upload_handler() .../wp-content/plugins/jetpack/class.jetpack.php:3283
[30-Jun-2017 02:50:38 UTC] PHP   7. hash_hmac_file() .../wp-content/plugins/jetpack/class.jetpack.php:3375
```

A quick look at the vars related to this testing shows that the file upload data looks like this: 

```
Array
(
    [name] => DSC_0010.JPG
    [type] => 
    [tmp_name] => 
    [error] => 1
    [size] => 0
)
```

The HMAC tester is testing tmp_name, which is empty. I'm investigating what might be causing this, but this part of the codebase is unknown territory to me.

**Comment by dbtlr** [comment] 2017-06-30 03:05
Further testing shows this working now, so I'm not sure if this was a fragment of too many XHR replays. Would love to get some more testing to verify this though

**Closed** 2017-07-03 13:07 UTC
Labels: WPCOM API, [Pri] BLOCKER, [Status] Needs Patch, [Type] Bug
