### ISSUE TITLE
Simple Payments Widget: No Pay with PayPal button

### ISSUE THREAD

**Issue by ktyfuller604** [Automattic/jetpack#14195] opened 2019-12-08 18:54 UTC
## Summary of the issue:
Creating a new Simple Payments "product" from the Widget in the customizer does not consistently create the Buy with PayPal option. It appears isolated to Atomic sites. I've tested on both, and while in Simple Sites the button doesn't immediately appear in the customizer, once you "save" the new widget, it does appear in the customizer and the live site.

## Steps to reproduce
1. Starting at URL: /wp-admin/customize.php
2. Click Widgets → Add New, and search for "Simple Payments"
3. Click "Add New" instead of selecting an existing Simple Payments button
4. Enter data in all the fields
5. Publish changes

## What I expected
The widget would include the "Pay with PayPal" button that shows in the Simple Payments block.

## What happened instead
The PayPal Button does not appear, either in the customizer or on the published site. 

Note: if you use an existing Simple Payments option from the drop-down, then everything displays as it should.

#2541100-zen

**Comment by jeherve** [comment] 2019-12-09 09:37
Closing as duplicate of #10514

**Closed by jeherve** 2019-12-09 09:37 UTC
Labels: Simple Payments, [Type] Duplicate
