### ISSUE TITLE
Sharing: Customized message seems to be ignored when tweet is published

### ISSUE THREAD

**Issue by lcollette** [Automattic/jetpack#20711] opened 2021-08-16 19:25 UTC
#### Steps to reproduce the issue

1. Open a post in the editor.
2. Verify there is a connected social account (I tested with Twitter), if not, connect one.
3. Edit the text within the "Customize your message" input field.
4. Publish post.
5. Check the social account to verify the message posted.

#### What I expected

I expected to see my updated message on Twitter.

#### What happened instead
The edit I made was not reflecting in the posted tweet.

**Screenshots**

![Screen Shot 2021-08-16 at 12 02 31 PM](https://user-images.githubusercontent.com/181733/129616182-baac0506-79b4-416c-89b5-52e8bc37ce36.png)

**Comment by sdixon194** [comment] 2021-08-16 19:36
Thanks for the detailed instructions and screenshots! Looks like a dupe of https://github.com/Automattic/jetpack/issues/18948 

I'll close this one out in favor of the other one.

**Closed** 2021-08-18 07:52 UTC
Labels: [Type] Bug, [Type] Duplicate, Publicize
