### ISSUE TITLE
BuddyPress Group images can't be cropped when Lazy Images is enabled.

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/jetpack#10016] opened 2018-08-13 10:02 UTC
#### Steps to reproduce the issue

1. Activate BuddyPress and the User Groups feature.
2. Create a new Group. When you get to the photo, upload a photo from your computer.

#### What I expected

The photo should appear and be ready for cropping:

![image](https://user-images.githubusercontent.com/1990037/44025480-2ff07378-9ee8-11e8-9a52-f07324da8b64.png)
(Lazy Images disabled ^ )

#### What happened instead

The photo does not load:

![image](https://user-images.githubusercontent.com/1990037/44025403-f45cfdae-9ee7-11e8-92bc-f1186e0c6270.png)

1328476-zen

**Comment by khristiansnyder** [comment] 2018-08-14 03:12
1345964-zen looks like the same issue. Recommended they disable Lazy Loading for now.

**Comment by supernovia** [comment] 2018-11-12 17:01
Possibly the same issue here:
https://wordpress.org/support/topic/cropping-stops-working/

Will confirm whether disabling lazy load fixes it.

**Comment by macmanx2** [comment] 2019-02-08 22:33
And https://wordpress.org/support/topic/buddypress-compatibility-32/ too.

**Comment by tripleqs** [comment] 2019-04-25 08:45
Disable this will be fixed, but are there have no better solution?

**Comment by bindlegirl** [comment] 2019-07-10 08:37
zen-2167277 is another one. Recommended disabling Lazy images.

**Comment by felipelousantos** [comment] 2021-01-23 17:19
Had a user with the same issue while using Jetpack lazy-loading feature, BuddyPress, and the theme [BoomBox](https://themeforest.net/item/boombox-viral-buzz-wordpress-theme/16596434). 

I wasn't able to reproduce with only BuddyPress, so it seems to be a conflict with this theme only, in this case.

References: 26067107-hc (follow-up 3673908-zen)

**Comment by katiebethbrown** [comment] 2022-11-07 19:31
We've run into this issue on a Team51 partner site.

Notes from our troubleshooting:
- JP's lazyload applies automatically to all images, except for ones with a `skip-lazy` class set. 
- BuddyPress doesn't use this class and so the image gets replaced with a lazyload placeholder, the crop tool then does all its calculations on that before the lazyloading happens.

Possible resolution:
- For Jetpack to have some BP-specific logic to skip the avatar upload/crop images
- Alternatively BuddyPress could add the `skip-lazy` class to the relevant images out of the box.

Related closed ticket in BuddyPress Trac:
https://buddypress.trac.wordpress.org/ticket/6893

Multiple mentions in the BuddyPress Support forum as well, so it continues to be a recurring issue:
- https://buddypress.org/support/search/crop/ 
- https://buddypress.org/support/search/lazy+load/

**Closed** 2023-10-25 20:08 UTC
Labels: [Type] Bug, [Status] In Progress, [Pri] Normal, [Feature] Lazy Images, Customer Report
