### ISSUE TITLE
Donations Form Block: Currency Change throwing error

### ISSUE THREAD

**Issue by janmckell** [Automattic/jetpack#30538] opened 2023-05-08 16:00 UTC
### Quick summary

When trying to change the currency for the Donations Form Block, there is a Block error. I tried on an Atomic as well as Simple site. I tried on two themes: Morden, Twenty-Twelve, in Firefox and Chrome, and it occurs each time. I tried about 5 currencies, and it happened each time.

This occurred whilst using the dropdown in the toolbar to change the currency.

See screenshot below:
![Markup on 2023-05-08 at 9:45:56 AM](https://user-images.githubusercontent.com/84089207/236871639-019057ba-3a98-4a0d-92c1-72d6ebfc913e.png)

This was raised due to interaction: 6215710-ZD

### Steps to reproduce

Start in Page Editor
Add Donations Form Block
Select currency dropdown in toolbar and try to change the currency
Block error occurs

### What you expected to happen

Currency change

### What actually happened

Block error occurred.

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple, Atomic

**Comment by karenroldan** [comment] 2023-05-09 08:36
📌 ACTIONS

- Closed as duplicate of issue #30299

**Closed as completed by karenroldan** 2023-05-09 08:36 UTC
Labels: Bug, [Pri] Normal, Customer Report [LEGACY], [Block] Payments, [Block] Donations, [Platform] Simple, [Platform] Atomic
