### ISSUE TITLE
Comments: the "Notify me of new posts" checkbox is always displayed

### ISSUE THREAD

**Issue by kbrown9** [Automattic/jetpack#18022] opened 2020-12-08 17:46 UTC
#### Steps to reproduce the issue

1. Activate and connect Jetpack.
2. Navigate to Jetpack -> Settings -> Discussion.
3. Enable the "Let visitors use a WordPress.com ..." setting.
4. In the Subscriptions section, disable the "subscribe to site" and "subscribe to comments" settings.
5. Navigate to a post on the site.
6. The "Notify me of new posts via email" checkbox is displayed. The "subscribe to site" is option is disabled, so this checkbox should not be displayed.

#### What I expected
The "Notify me of new posts via email" checkbox should not be displayed when the "subscribe to site" option is disabled.

#### What happened instead
The "Notify me of new posts via email" checkbox is displayed when the "subscribe to site" option is disabled.

**Screenshots**

##### The Subscription settings:

<img width="1069" alt="Screen%20Shot%20on%202020-12-08%20at%2012-35-36" src="https://user-images.githubusercontent.com/50059399/101520906-19a14400-3953-11eb-8290-43d043c576b7.png">

##### The comment box:

<img width="878" alt="Screen%20Shot%20on%202020-12-08%20at%2012-35-13" src="https://user-images.githubusercontent.com/50059399/101520963-2b82e700-3953-11eb-9c6c-6b78af0502d7.png">

**Comment by jeherve** [comment] 2020-12-08 17:48
Closing as duplicate of #12904.

**Closed by jeherve** 2020-12-08 17:48 UTC
Labels: Comments, Subscriptions, [Pri] Normal, [Type] Bug
