### ISSUE TITLE
Genericons update for Google Plus icon

### ISSUE THREAD

**Issue by sunipeyk** [Automattic/jetpack#2720] opened 2015-09-18 09:43 UTC
Genericons updated Google plus new icon. Are you going to update too? 
Thank you.

**Comment by jeherve** [comment] 2015-09-18 09:44
Closing as duplicate of #2670.

Yes, we'll update the G+ icon in Jetpack as well.

**Closed by jeherve** 2015-09-18 09:44 UTC

**Comment by sunipeyk** [comment] 2015-09-18 09:55
Sorry for dublicate. Thank you for your quick answer.
