### ISSUE TITLE
get_request_url()  within class.jetpack-sync-listener.php returns undefined index

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/jetpack#10851] opened 2018-12-06 13:21 UTC
When activating Jetpack modules via WP-CLI I get the following PHP notices:

```
[1049018] $ wp jetpack module deactivate protect
Success: Protect has been deactivated.
[1049018] $ wp jetpack module activate protect
PHP Notice:  Undefined index: HTTP_HOST in /opt/sites/1049018/wordpress/plugins/jetpack/6.8-pressable/sync/class.jetpack-sync-listener.php on line 307
PHP Notice:  Undefined index: HTTP_HOST in /opt/sites/1049018/wordpress/plugins/jetpack/6.8-pressable/sync/class.jetpack-sync-listener.php on line 307
PHP Notice:  Undefined index: HTTP_HOST in /opt/sites/1049018/wordpress/plugins/jetpack/6.8-pressable/modules/protect.php on line 888
Success: Protect has been activated.
```
This seems to be coming from` get_request_url()` within `class.jetpack-sync-listener.php` , as `HTTP_HOST` is not always defined, but` isset() `is not wrapping `$_SERVER['HTTP_HOST']`.

#### Steps to reproduce the issue

1. Go to any Atomic site (Which seems that do not define HTTP_HOST, but this may happen in other type of hosting as well)
2. Activate any module via `wp jetpack module deactivate $MODULE_NAME`
3. See notice

Proposed solution:  Wrapping `{$_SERVER['HTTP_HOST']}{$_SERVER['REQUEST_URI']}` with `isset()` should return either true or false, but not undefined.

**Comment by jeherve** [comment] 2018-12-10 11:56
Closing as duplicate of #10717

**Closed by jeherve** 2018-12-10 11:56 UTC
Labels: Jetpack CLI, Sync, [Pri] Low, [Type] Bug, [Type] Duplicate
