### ISSUE TITLE
Development Mode: Filter only works in another plugin

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#3827] opened 2016-05-17 20:02 UTC
If adding the `jetpack_development_mode` filter, it needs to be added in a plugin vs in a theme's functions.php because we load `load_modules` on the `plugins_loaded` hook, which fires before the functions.php of a theme is loaded.

I'm tempted to document this behavior and say that's fine. Thoughts?

**Comment by jeherve** [comment] 2016-05-17 21:40
This should be fixed by #3635

**Comment by jeherve** [comment] 2016-12-08 17:33
Reverted in #5830

**Comment by jeherve** [comment] 2024-12-17 18:56
Closing as duplicate of #1462

**Closed by jeherve** 2024-12-17 18:56 UTC
Labels: [Type] Bug, [Feature] Offline Mode, Good For Community
