### ISSUE TITLE
Masterbar blocks access to wp-admin menu items on mobile

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#6914] opened 2017-04-05 04:18 UTC
#### Steps to reproduce the issue

On mobile device such as Google Pixel
Enable WordPress.com toolbar
Click menu
All links go to WordPress.com
Try to disable toolbar using WordPress.com, can't find option

#### What I expected

Ability to still browse wp-admin
Ability to disable WordPress.com toolbar after enabling

#### What happened instead

No way to browse wp-admin
No way to go back to old toolbar

**Comment by dereksmart** [comment] 2017-04-05 13:18
@gravityrail Are you not seeing the `dashboard` menu item at the bottom?  I'm seeing it in mobile view with the chrome dev tools. 

![screen shot 2017-04-05 at 9 17 46 am](https://cloud.githubusercontent.com/assets/7129409/24707226/cca68380-19e0-11e7-8a05-4a13de44b263.png)

**Comment by gravityrail** [comment] 2017-04-05 13:47
No :(

https://goo.gl/photos/1P5wibqXDS5meWqE9

**Comment by dereksmart** [comment] 2017-04-05 14:48
Ah, yep, I can reproduce on (a real life) iPhone 7.  Chrome tools doesn't reproduce.

**Comment by vindl** [comment] 2017-04-05 16:05
Tried it on Google Nexus and I can't reproduce. Could this be related to the fact that `Dashboard` is hidden in WP Admin views, and only shown on front-end? If that is the case, clicking on top level item that opens the menu again will close it, and reveal the underlying WP Admin page.

**Comment by gravityrail** [comment] 2017-04-07 13:56
Let me reiterate what's going on (now typed on desktop so I can be more verbose), because this is definitely still an issue for me.

- On a Jetpack site, enable the WordPress.com toolbar
- On the same Jetpack site, go to (e.g.) mysite.com/wp-admin
- Now, how do you get to (say) the wp-admin "posts" list? 

The W menu only shows links to WordPress.com tools. What if my site has some special extension to the post editor? The only way to reach it now is to type in the URL of the posts page on my phone.

You can reproduce this on desktop too. Just make the window as narrow as possible, in any browser, and the hamburger menu you'd normally use to access wp-admin features is gone, even though you're still in wp-admin. This prevents access to the Jetpack UI that's necessary to disable the problematic toolbar.

**Comment by vindl** [comment] 2017-04-10 23:21
> You can reproduce this on desktop too. Just make the window as narrow as possible, in any browser, and the hamburger menu you'd normally use to access wp-admin features is gone, even though you're still in wp-admin.

Thanks for the clarification @gravityrail, I see what you meant now, and yes, this is definitely an issue.

**Closed** 2017-06-19 17:17 UTC
Labels: Masterbar, [Pri] Normal, [Type] Bug
