### ISSUE TITLE
PHP notices when activating Jetpack 4.5 on Multisite

### ISSUE THREAD

**Issue by rcoll** [Automattic/jetpack#6192] opened 2017-01-27 19:01 UTC
#### Steps to reproduce the issue
Install Jetpack 4.5 on a multisite, and then network activate.

#### What I expected
No notices

#### What happened instead
<img width="1401" alt="screen shot 2017-01-27 at 8 58 57 am" src="https://cloud.githubusercontent.com/assets/5528445/22383689/e1344816-e46e-11e6-8ed7-9f93523aeb59.png">

`Notice: Trying to get property of non-object in /home/jetpack-multi.ftlwp.com/wp-content/plugins/jetpack/modules/custom-css/migrate-to-core.php on line 47`

`Notice: Trying to get property of non-object in /home/jetpack-multi.ftlwp.com/wp-content/plugins/jetpack/modules/custom-css/migrate-to-core.php on line 217`

**Comment by jeherve** [comment] 2017-01-27 19:03
Closing as duplicate of #6158

**Closed by jeherve** 2017-01-27 19:03 UTC
Labels: Multisite, [Pri] Low, [Type] Bug
