### ISSUE TITLE
Stats: JS file returning 400 error and showing up in GTMetrix report

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#16084] opened 2020-06-06 19:25 UTC
The user in 3019081-zen reported that the following file is showing up in the `Avoid bad requests` section of their GTMetrix report. I was able to reproduce this on several other Jetpack-connected sites.

`/wp-content/plugins/jetpack/https:/stats.wp.com/s-202023.js`

![](https://d.pr/i/9H013e+)
Image Link: https://d.pr/i/9H013e

Is it possible to resolve this or otherwise provide some sort of workaround, or is this just something that they'll need to live with?

**Comment by jeherve** [comment] 2020-06-07 14:01
Closing as duplicate of #16047. Check the PR description for a work-around.

**Closed by jeherve** 2020-06-07 14:01 UTC
Labels: Stats, [Pri] Normal, [Type] Bug, [Type] Happiness Request
