### ISSUE TITLE
The Site Performance JITM doesn't dismiss, it's permanent

### ISSUE THREAD

**Issue by jessefriedman** [Automattic/jetpack#16025] opened 2020-06-01 14:26 UTC
I spooled up a Jurassic.ninja site. Connected it. Now I see the "Improve your site's performance and speed".  I then went to settings and enabled Photon and Static Assets but the JITM still shows.  So then I clicked "Activate" on the JITM but that still didn't make it go away.  

<img width="522" alt="Screen Shot 2020-06-01 at 10 18 55 AM" src="https://user-images.githubusercontent.com/1749986/83418697-046eba00-a3f2-11ea-99a8-ca8015dc1d64.png">

Started by enabling that ^

then I went here: 

<img width="985" alt="Screen Shot 2020-06-01 at 10 24 27 AM" src="https://user-images.githubusercontent.com/1749986/83418745-18b2b700-a3f2-11ea-9610-269152614bfa.png">

That didn't work so I went back to the main wp-admin dash and hit "Activate" on the JITM

<img width="1169" alt="Screen Shot 2020-06-01 at 10 21 31 AM" src="https://user-images.githubusercontent.com/1749986/83418823-308a3b00-a3f2-11ea-833b-56678d2e926d.png">

The JITM persists. 

@robertf4  I wonder if this is related to any work recently done on JITMs

**Comment by jeherve** [comment] 2020-06-01 14:42
This could be a duplicate of #12891. 

What happens when you refresh the page? Does the JITM eventually disappear?

**Comment by jessefriedman** [comment] 2020-06-01 15:08
It didn't the first few times but eventually, it did seem to go away on it's own.  Not sure how long it took, it's just gone now.

**Comment by jeherve** [comment] 2020-06-01 16:41
The JITMs are cached, so it may have been a combination of the bug above and caching. I'll close this one for now, but will keep this in mind.

**Closed by jeherve** 2020-06-01 16:42 UTC
Labels: JITM, [Type] Bug
