### ISSUE TITLE
Jetpack_PostImages: methods from_gallery & from_slideshow don't work with slideshows

### ISSUE THREAD

**Issue by eliorivero** [Automattic/jetpack#4069] opened 2016-06-03 17:49 UTC
#### Steps to reproduce the issue
1. activate the Shortcodes module in Jetpack

2. add a post and add a gallery in `slideshow` mode. Example:
    ```
Gallery shortcode - Type slideshow

[gallery type="slideshow" ids="12,34,56"]

Slideshow shortcode

[slideshow]
    ```
    - Replace these sample IDs with your own image IDs.
    - Note that to use the `[slideshow]` shortcode you need to have images uploaded to the post where you're adding the shortcode.

3. add the following in the `functions.php` of your theme or somewhere similar where it's run:
    ```php
add_action( 'wp_footer', function() {
	var_dump( Jetpack_PostImages::from_gallery( get_the_ID() ) );
	var_dump( Jetpack_PostImages::from_slideshow( get_the_ID() ) );
} );
    ```
    and view your post in the front end.

#### What I expected

I expected to see an array dumped with URLs in it for each `Jetpack_PostImages` method.

#### What happened instead

Empty arrays were dumped.
```
siteroot/wp-content/themes/twentytwelve/functions.php:25:
array (size=0)
  empty
siteroot/wp-content/themes/twentytwelve/functions.php:26:
array (size=0)
  empty
```

#### What works

The `[gallery]` shortcode works when it's not of [slideshow](url) type. To verify, add something like this to your post:
```
[gallery ids="12,34,56"]
```
Again, view the post in front end. One of the dumps at the bottom shows the array correctly populated.
```
siteroot/wp-content/themes/twentytwelve/functions.php:25:
array (size=3)
  0 => 
    array (size=4)
      'type' => string 'image' (length=5)
      'from' => string 'gallery' (length=7)
      'src' => string 'http://example.tld/wp-content/uploads/2016/03/image-150x150.jpg' (length=72)
      'href' => string 'http://example.tld/testing-12/' (length=39)
  1 => 
    array (size=4)
      'type' => string 'image' (length=5)
      'from' => string 'gallery' (length=7)
      'src' => string 'http://example.tld/wp-content/uploads/2016/02/image-150x150.jpg' (length=75)
      'href' => string 'http://example.tld/testing-12/' (length=39)
  2 => 
    array (size=4)
      'type' => string 'image' (length=5)
      'from' => string 'gallery' (length=7)
      'src' => string 'http://example.tld/wp-content/uploads/2016/03/image-150x150.jpg' (length=90)
      'href' => string 'http://example.tld/testing-12/' (length=39)
```

**Comment by jeherve** [comment] 2016-06-03 18:02
I believe that's a duplicate of #3572, but your issue has a lot of details. Which one do you want to keep? :)

**Comment by eliorivero** [comment] 2016-06-04 23:26
Let's use mine since the testing steps are more complete (the other doesn't specify which module to activate), can be tested with Jetpack only (the other uses a theme) and covers the cases with gallery and `slideshow` shortcode (not covered in the other).

**Comment by eliorivero** [comment] 2016-06-04 23:27
Comment from @jeherve in the previous report:

> 
> Since ae784dc, we use core's get_post_galleries_images() function to retrieve images from galleries. It's useful when looking for images in a gallery, but slideshows work a bit differently: the gallery HTML isn't built the same way (reference), so Core's get_post_galleries() (reference) can't get the image sources from the galleries.
> 
> On the other hand, we also have Jetpack_PostImages::from_slideshow() (reference) that was built to retrieve images from the old [slideshow] shortcode. Maybe we should refactor that to grab slideshow images.

**Closed** 2016-06-09 14:30 UTC
Labels: General, [Type] Bug
