### ISSUE TITLE
Slider not loading in mobile.

### ISSUE THREAD

**Issue by tarunvijwani** [Automattic/jetpack#12901] opened 2019-06-28 05:56 UTC
A use has added the slider block which is not visible on their mobile phone.

#### Steps to reproduce the issue

1. Create a slider block and add 10-15 images
2. Publish the change and check it on the mobile.

#### What I expected
Slider should be visible in mobile
#### What happened instead
Sometimes, it sometimes gets loaded for a second and then goes away and rest of the times it doesn't load at all.

![screenshot_20190628-151229_chrome](https://user-images.githubusercontent.com/5654161/60587348-e4c3b180-9d9c-11e9-90b6-01fa3fba8872.jpg)

Screenshot: https://travelivingwithuscom.files.wordpress.com/2019/06/screenshot_20190628-151229_chrome.jpg

#2140810-zen

**Comment by jeherve** [comment] 2019-07-03 11:04
I can't seem to reproduce on my end on that site, in Chrome on an iPhone. Did this happen in a specific browser? Are you able to reproduce on that site, or on a test site?

**Comment by jeherve** [comment] 2019-07-05 09:08
I believe this is due to Safari. Closing as duplicate of #12961

**Closed by jeherve** 2019-07-05 09:08 UTC
Labels: Gutenberg, [Block] Slideshow, [Status] Needs Author Reply, [Type] Happiness Request
