### ISSUE TITLE
Carousel + Tiled Galleries loads full size image

### ISSUE THREAD

**Issue by ChrisBegley** [Automattic/jetpack#2969] opened 2015-11-05 22:47 UTC
I think this just started happening... if you have Carousel and Tiled Galleries activated, the full sized image is being loaded when you click on a thumbnail. Previously I believe the "large" size would load in.

Also, the full size image that loads when you click a thumbnail is not being served by Photon (if it's activated).

**Comment by kraftbj** [comment] 2015-11-05 22:50
Marking as 3.8.1 since we may be able to pick this up as part of the srcset work, but if it ends up being unrelated, probably should be fine punting to vNext.

I haven't tested to confirm behavior or to blame back when/if behavior changed.

**Comment by jeherve** [comment] 2015-11-06 15:28
This could be caused by #2508.

**Comment by Draikin** [comment] 2015-11-06 19:10
The full size image being loaded could be intentional, it'll show the full size image if the "large" image would otherwise be upscaled.

I looked into the image not being served by Photon. That appears to be the case for the full-size image. The issue is that it's using the original source, which always points to the local image. I'm trying to figure out if this can be solved easily, I'm not sure if the Photon url to the original image is readily available.

**Comment by ChrisBegley** [comment] 2015-11-06 19:26
You're right! I was testing on my new 4k iMac when I reported this, but here on my work laptop the "large" image size is being used.

**Comment by Draikin** [comment] 2015-11-06 19:32
If my assumption is correct, on your work laptop the "large" image will be served by Photon. I think it's only the full image that isn't being served by Photon. Disregarding the Photon issue, do you see any issue with the full image being shown when the available screen resolution exceeds that of the "large" image?

**Comment by ChrisBegley** [comment] 2015-11-06 20:09
Yep, that's right. The "large" image is being served by Photon on my laptop. 

The only issue with the full image being shown is performance, those files can be huge. It'd be nice if there were image sizes inbetween "large" and "full" for 2x displays like the 4k iMac, but maybe that's where the 4.4 srcset enhancements will come in handy?

**Comment by kraftbj** [comment] 2015-11-06 21:53
> I'm not sure if the Photon url to the original image is readily available.

The original URL is what is uploaded by Photon for the rest of the image serving. e.g. if the images are example.com/whatever/image.jpg, example.com/whatever/image-500x500.jpg, example.com/whatever/image-1000x1000.jpg, then the photon URLs would be i{0-2}.wp.com/example.com/whatever/image.jpg ,  i{0-2}.wp.com/example.com/whatever/image.jpg?w=500&h=500, etc

**Comment by Draikin** [comment] 2015-11-06 22:05
In that case I could change it accordingly. In fact, I think Photon should be capable of serving images that fit the carousel exactly. Since we know the aspect ratio of the image based on the original image, we could calculate the new dimensions the image needs and let Photon handle those. But I think that would cause Photon to create a lot of new images for just about every user that views the carousel. I'm guessing that's not a good idea?

In any case, I've noticed Photon tends to add the dimensions to the url even if they're the same as the original image. Is there a particular reason for that? And does it matter which of the i0, i1 or i2 is used when creating the url?

**Comment by kraftbj** [comment] 2015-11-06 23:10
FWIW, on creating a Photon URL, once you have the actual URL and the sizes you want, if needed, you can use https://github.com/Automattic/jetpack/blob/b5fd4cfc5dff8f59cc60b0fa8a2c8dc0edde6739/functions.photon.php#L12

I'm not sure wrt always adding the dims. My first thought on why it makes sense is to ensure we get what we're expecting, in terms of size, and not being surprised. Just a quick guess though.

I'm not terribly concerned about Photon creating a lot of different sizes—we're setup to dynamically resize images on the fly and that's why we intentionally pull the original image in, not a smaller size even if the request is only for a very small variant.

**Comment by Draikin** [comment] 2015-11-07 01:52
For now I think I should just create a pull request to fix the issue with the original image not being served from Photon. The custom size images would be an interesting change but I'd really have to look into the PHP code you linked to. I more or less have an idea of how that would work but there are probably a lot of details that I don't know.

**Comment by kraftbj** [comment] 2015-11-10 16:03
Noting #975 as related along with #2918. tl;dr Carousel, Photon, srcset, and HiDPI is all in a bit of flux and need of eyes.

**Comment by Draikin** [comment] 2015-11-13 21:48
In that case, would there still be a point in me making that pull request I mentioned earlier?

**Comment by kraftbj** [comment] 2015-11-24 17:50
@Draikin The PR would still be good. It's all in some flux, but I would expect all images to be served by Photon while active. Your PR would likely land sooner than anything bigger, which may or may not actually touch what is in flux.

**Comment by eliorivero** [comment] 2016-01-13 18:32
@ChrisBegley after updating to latest Jetpack, are you still experiencing this issue you mentioned?
> Also, the full size image that loads when you click a thumbnail is not being served by Photon (if it's activated).

**Comment by ChrisBegley** [comment] 2016-01-13 18:51
@eliorivero do you mean 3.8.2 or the latest release in the "master" build? It's still an issue in 3.8.2.

**Comment by eliorivero** [comment] 2016-01-13 18:53
@ChrisBegley please check with the master build that includes latest changes in this repo.

**Comment by ChrisBegley** [comment] 2016-01-14 02:09
@eliorivero sorry for the delay. Unfortunately I can't get Tiled Galleries working with the master build. I have it activated, but it's behaving like it's not. I deleted 3.8.2 and installed the master build.

**Comment by eliorivero** [comment] 2016-01-14 13:07
@ChrisBegley oh that's interesting, in an unfortunate way of course. We've released a 3.9 beta 
https://github.com/Automattic/jetpack/releases/tag/3.9.0-beta
Can you please try one last time with it? link is at the bottom of that page. If it's still not working, can you let me know which part is behaving like it's inactive? a) you're not seeing the additional options for galleries in Media Library and when you go to `wp-admin/options-media.php` there are no options titled Image Gallery Carousel and/r b) options are there and shortcode is ok, but you're not seeing a tiled gallery in front end.
Thanks for looking into this!

**Comment by ChrisBegley** [comment] 2016-01-14 18:10
@eliorivero Got it working! I had another gallery plugin activated that was conflicting with Tiled Galleries.

Unfortunately, the issue does not appear to be fixed. I have Photon, Tiled Galleries, and Carousel activated with Jetpack 3.9.0 beta and the "View Full Size" link is still not using a Photon URL.

**Comment by Draikin** [comment] 2016-01-14 19:02
It does in fact appear to be working now for me using the beta version, even without the workaround I made earlier (https://github.com/Automattic/jetpack/pull/3200).

@ChrisBegley Is Photon actually working for the other images? Perhaps something else is causing it not to work for you.

**Comment by ChrisBegley** [comment] 2016-01-14 19:10
@Draikin yes, Photon is working for the Carousel images, just not for the "View full size" link. I can try it on a different server a little later tonight when I get home from work. I'll let you know how it goes.

**Comment by eliorivero** [comment] 2016-01-14 20:13
@ChrisBegley can you please try it on a fresh WP install, maybe there's something that's conflicting like with Tiled Galleries. If it works in a fresh install, maybe that will help diagnose what is going on in your other site.

**Comment by ChrisBegley** [comment] 2016-01-14 20:26
@eliorivero @Draikin unfortunately it's still not working. The "View full size" link isn't using Photon. I'm on a different test site running WordPress 4.4.1 with Jetpack 3.9.0 beta. Jetpack is the only plugin that I have activated, and I'm using the default Twenty Sixteen theme. Here's the test gallery:
http://halo.techyourworld.com/carousel-tiled-galleries-photon-test/

**Comment by Draikin** [comment] 2016-01-14 21:04
Interesting. After doing some more testing, the problem does indeed persist at times. The original link doesn't appear to be always pointing to the Photon image. When it does, my workaround isn't needed. If it doesn't, my workaround should fix the problem for the actual image being displayed, but not for the "View Full Size" link. I could be wrong, but I don't think the latter problem was introduced with my earlier changes. The full size link appears to be set before that, so I imagine it would never have pointed to Photon even in older Jetpack versions. I think I could also fix this in my pull request for this problem, but if it's possible to get the original file to point to Photon consistently that would probably be the better approach.

@eliorivero Do you know what was changed in the beta version that influenced the original file link?

**Comment by ChrisBegley** [comment] 2016-01-14 21:07
Wow, I'm sorry! I was confusing this with another issue I reported (the "view full size" issue).

Yes, the image being loaded *is* using Photon.

**Comment by Draikin** [comment] 2016-01-14 21:15
But if the full image is shown in the carousel, it's not using Photon, right? In the link you posted above, the full sized images aren't using Photon for me (both the image and the link). This of course depends on your screen resolution. What's weird is that something has changed, and now the original file link is pointing to Photon sometimes (but not always). And I'm not sure what's causing the difference.

**Comment by ChrisBegley** [comment] 2016-01-14 21:17
Right now I'm at work on a PC laptop (1366x768) and the full image is using Photon:
http://i0.wp.com/halo.techyourworld.com/wp-content/uploads/2016/01/BVS-25543r-CC.jpg?fit=840%2C560

I can let you know what I see when I get home on my 4K iMac.

**Comment by Draikin** [comment] 2016-01-14 21:20
What you linked to is actually the resized version though... The original is a lot bigger, and that's what it's showing here on my desktop (1920x1080):

http://halo.techyourworld.com/wp-content/uploads/2016/01/BVS-25543r-CC.jpg

**Comment by ChrisBegley** [comment] 2016-01-14 21:24
Oh ok. Yes, that's what happened to me too on a desktop (iMac) and prompted me to log this issue.

**Closed** 2016-01-18 21:18 UTC
Labels: Carousel, Photon, Tiled Galleries, [Type] Bug

**Comment by eliorivero** [comment] 2016-01-19 22:58
Hi @ChrisBegley, I've pushed a commit that modifies this fd57ed85271e796d29546a101a8b96405b2a1b59
You can quickly test it if you open `/wp-content/plugins/jetpack/modules/carousel/jetpack-carousel.js` in your installation and replace its contents with these https://raw.githubusercontent.com/Automattic/jetpack/fd57ed85271e796d29546a101a8b96405b2a1b59/modules/carousel/jetpack-carousel.js
After that, either run `grunt` so the minified JS is generated or open `jetpack-carousel.min.js` and replace its contents with this one for testing purposes.

**Comment by ChrisBegley** [comment] 2016-01-20 00:19
@eliorivero yes, that fixed it!

**Comment by eliorivero** [comment] 2016-01-20 02:21
@ChrisBegley great! :tada: Thank you very much for your report and all the help testing this.

**Comment by ChrisBegley** [comment] 2016-01-20 02:22
@eliorivero my pleasure! Thanks for getting it fixed.
