### ISSUE TITLE
Twitter Block not correctly embedding

### ISSUE THREAD

**Issue by rachelwinspear** [Automattic/jetpack#17491] opened 2020-10-15 16:21 UTC
Twitter Block is not embedded correctly on the site `mattwhitefootballwanderer.wordpress.com`.

#### Steps to reproduce the issue

1. Go to a page or post
2. Add the Twitter Block and embed link (Tested with various Twitter links)
3. Click to embed and the Twitter link either turns into a Paragraph Block, showing the link or shows error: `The block has encountered an error`. Screenshot: https://d.pr/i/qWJ2tn

On some pages the user was able to embed the Twitter Block, but then flashes like this: https://d.pr/v/HYqXYM 
When you go to edit it, you then see the Attempt to Recover Block error.

#### What I expected

I expected the Twitter link to be embedded correctly like this screenshot: https://d.pr/i/re5a5j
The screenshot was from a test site, with the Premium plan and Hever theme, same as the users site.

#### What happened instead

The Twitter Block did not display correctly, converting to a Paragraph Block with the link or shows error: `The block has encountered an error`. Screenshot: https://d.pr/i/qWJ2tn

On some pages the user was able to embed the Twitter Block, but then flashes like this: https://d.pr/v/HYqXYM

**Comment by rachelwinspear** [comment] 2020-10-15 16:22
#3407958-zen

**Comment by jeherve** [comment] 2020-10-15 16:32
Since the block is not a Jetpack block, but is provided by WordPress Core directly, I'm not sure I'll be of much help.

I gave the block a try on another WordPress.com simple site, with tweets from the same Twitter account, and everything worked there.
I then tried on that specific site and could see the issue. I wonder if the problem may be linked to the theme and its use of Google Fonts. It may be worth trying to reproduce on another WordPress.com site with the same theme, see if the same thing happens there.

I'll close this issue for now. If the problem remains, it may be worth bringing it up in #triage; depending on whether the problem comes from the theme or something else, we should be able to figure out whether that's an issue with the Core Twitter block, with a theme, or something else.

**Closed by jeherve** 2020-10-15 16:32 UTC
