### ISSUE TITLE
Related posts: Improve rendering of block in subscription emails

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#31824] opened 2023-07-11 21:38 UTC
Improve the rendering for related posts.

This is how it render on the reader

![image](https://github.com/Automattic/jetpack/assets/746152/196718cc-7b2a-4b6a-8ff0-e41cc9a3b817)

We may need an update like D113272-code

**Comment by jeherve** [comment] 2023-07-12 10:22
Closing as duplicate of #31802.

**Closed as completed by jeherve** 2023-07-12 10:22 UTC
Labels: Bug, [Closed] Duplicate, [Feature] Related Posts, [Pri] Normal, [Plugin] Jetpack

**Comment by oskosk** [comment] 2023-07-12 10:33
thanks
