### ISSUE TITLE
Sitemaps: Updating Jetpack breaks sitemap

### ISSUE THREAD

**Issue by seejacobscott** [Automattic/jetpack#7992] opened 2017-10-15 18:54 UTC
After updating Jetpack, visiting the 'sitemap.xml' URL gives the error "No sitemap found. Maybe it's being generated. Please try again later."

If you toggle the sitemap feature on and off it will start working again. 

Steps to reproduce: 

* Set up a site running JP 5.3
* Check sitemap (Screenshot of sitemap page from 5.3: http://cld.wthms.co/6yRXUz) 
* Update to 5.4
* Check Sitemap again (Screenshot: http://cld.wthms.co/ABj0ne)
* Go to Jetpack → Settings → Traffic and toggle on and off Sitemaps
* Check sitemap again, it works now. 

Originally reported in 732886-zen, I tested as well updating from 5.3 to 5.4 and experienced the same issue.

**Comment by zinigor** [comment] 2017-10-16 20:36
This happens because the sitemap gets erased on Jetpack update, and it should get regenerated on next scheduled cron event. But I agree, we probably need to schedule another regeneration event right after the update so that there is no service interruption.

**Comment by brbrr** [comment] 2018-05-02 12:39
I re-tested this issue with JN site with update 6.0 -> 6.1 and my sitemaps was right there. Toggling Sitemaps setting also works as expected. I'm going to close this issue as fixed. Please feel free to re-open it if you'll be able to reproduce this issue with newer versions.

**Comment by jeherve** [comment] 2018-05-11 09:06
Reopening as we got another report in 1151005-zen

**Comment by gsmumbo** [comment] 2018-05-12 18:51
Above site is not using custom cron or having issues scheduling posts.

**Comment by aheckler** [comment] 2018-09-05 15:36
Similar issue in 1392188-zen, but toggling sitemaps off and on again doesn't fix it.

**Closed** 2018-10-11 19:06 UTC
Labels: Sitemaps, [Pri] High, [Type] Bug

**Comment by jeherve** [comment] 2018-10-12 08:38
@locvfx We've just merged a fix for this; it will be included in the next major Jetpack release, in the beginning of November.

**Comment by locvfx** [comment] 2018-10-12 10:46
Thank you very much, I hope to receive a new update early.
Thank you

**Comment by aheckler** [comment] 2018-10-15 12:17
Updated the user from 1392188-zen in a followup ticket: 1494180-zen.
