### ISSUE TITLE
Related Posts: Disable it from loading on the WooCommerce Onboarding Wizard 

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/jetpack#3732] opened 2016-04-25 21:16 UTC
If you activate Jetpack and then run the WooCommerce Onboarding Wizard, you get this:
![screen shot 2016-04-25 at 2 15 30 pm](https://cloud.githubusercontent.com/assets/3220162/14799201/3339443a-0af0-11e6-8a0b-e57e036f032c.png)

We should be smart and prevent it from trying to load Related Posts on the Wizard.  You can test this by installing WooCommerce on your site, and going to 
`http://YOURSITE.com/wp-admin/index.php?page=wc-setup`

**Comment by jeherve** [comment] 2016-04-26 05:53
Closing as duplicate of #3688

**Closed by jeherve** 2016-04-26 05:53 UTC
