### ISSUE TITLE
After the Deadline - do not strip code when proofreading posts

### ISSUE THREAD

**Issue by HardeepAsrani** [Automattic/jetpack#468] opened 2014-04-17 12:06 UTC
Hey folks,

I use Jetpack's After the Deadline feature and I love it, but there's one small problem in it. If there's some php code (like 10-15l lines) it will most-likely mess with my code & will completely destroy it. ;(

After the Deadline shouldn't check for spellings on the <code>&lt;code&gt;</code> tag.

Thank you!

**Comment by jeherve** [comment] 2018-02-23 12:12
Closing as duplicate of #156

**Closed by jeherve** 2018-02-23 12:12 UTC
Labels: AtD, [Type] Bug
