### ISSUE TITLE
Sharing: Show greater than 10K+ Facebook shares

### ISSUE THREAD

**Issue by chaselivingston** [Automattic/jetpack#2736] opened 2015-09-21 15:55 UTC
For sites with more than 10,000 Facebook shares, we stop rounding and show 10K+. The user in 2352072-t requests that we show something like 20K+, 30K+, 40K+, etc...

**Comment by jeherve** [comment] 2016-11-23 15:53
Closing as duplicate of #5107

**Closed by jeherve** 2016-11-23 15:53 UTC
Labels: Sharing, [Team]  I/O, [Type] Enhancement
