### ISSUE TITLE
Like Block: ensure that it can be displayed on CPTs too

### ISSUE THREAD

**Issue by foleynotrose** [Automattic/jetpack#38227] opened 2024-07-07 10:45 UTC
### Impacted plugin

Jetpack

### What

Enable Likes on Custom Post Types 

### How

In ticket 8327637-zd-a8c, user requests that Likes be available for Custom Post Types.

**Comment by jeherve** [comment] 2024-07-11 08:43
Likes are already available on CPTs:
https://github.com/Automattic/jetpack/issues/8074#issuecomment-340846339

Looking at the linked ticket, I believe the problem is more about how we manage the display of Likes on a site when you deactivate the Likes module and only rely on the newer Like block instead. That Like Block should work on CPTs too, but looking at their report, it may not work yet. We will need to test this.

**Comment by coder-karen** [comment] 2024-08-14 15:42
With Custom Post Types, likes work for me if I add the Like Block, but don't if I enable the Like module. The older Settings > Sharing page in wp-admin doesn't appear to be available any more, so I don't see a way to enable this for CPTs.
This seems to match the issue reported in the ticket. @jeherve have you got a test site that shows the legacy settings?


---
On reading the ticket, an issue was mentioned with templates Like placement as well, but I don't believe that is an issue. 
  * On templates, if I add a Like Block as well as having Likes enabled, I see the like this feature on the page twice. However that's also the same elsewhere too (posts, pages).
  * If likes are not enabled on the Sharing page, then the like feature only appears once.
  * The issue they mentioned appears to be the placement of the Likes feature if it isn't added as a block to a template, but when the module itself is enabled site-wide and gets placed where it doesn't appear to make as much sense.
  * I'm not sure this is an issue though, as I would imagine having likes above tags makes sense - that's the case elsewhere (posts / pages) as well.

**Comment by jeherve** [comment] 2024-08-14 16:03
> The older Settings > Sharing page in wp-admin doesn't appear to be available any more, so I don't see a way to enable this for CPTs.

You should be able to activate them in Calypso blue, at `https://wordpress.com/marketing/sharing-buttons/yoursite.com`

Using a classic theme like Twenty Eleven, classic likes (i.e. via the module) seem to work well. I indeed do not have the flexibility to control where exactly Likes are hooked into `the_content`, but that's expected on classic themes.

<img width="443" alt="image" src="https://github.com/user-attachments/assets/5ac2aacc-eb9f-4728-9105-5efd5f1445a5">

Using a block theme like Twenty Twenty Four, and disabling the module to use a Like block instead, I am also able to add the LIke block:

<img width="343" alt="image" src="https://github.com/user-attachments/assets/46fc05d7-38ee-4262-9af4-7ad9b60bfd29">

It seems to me like we can close this issue?

**Comment by coder-karen** [comment] 2024-08-14 16:20
> You should be able to activate them in Calypso blue, at https://wordpress.com/marketing/sharing-buttons/yoursite.com

Oh! I see that in the support docs too now, but I'll make an edit to make explicit mention of CPTs. Yes, in that case, it looks like we can close it out.

**Closed as completed by coder-karen** 2024-08-14 16:20 UTC
Labels: Bug, [Feature] Likes, [Focus] Blocks, Customer Report [LEGACY], [Plugin] Jetpack, Triaged, [Block] Like
