### ISSUE TITLE
Plans: Two Emails Sent When Canceling Jetpack Pro

### ISSUE THREAD

**Issue by roundhill** [Automattic/jetpack#5388] opened 2016-10-20 17:40 UTC
During testing I canceled a Jetpack Pro plan. I received two of the exact same emails about the cancelation. Maybe it's a wpcom store bug, but thought I'd report it here:

<img width="275" alt="screen shot 2016-10-20 at 10 37 10 am" src="https://cloud.githubusercontent.com/assets/789137/19571049/6767b55a-96b1-11e6-8055-fe6ef0ffb3a3.png">

#### Steps to reproduce the issue
1. Add Jetpack Pro to a site that you administrate.
2. Go to the store admin and cancel the subscription
3. You'll receive two cancelation emails.

**Comment by jeherve** [comment] 2016-10-20 19:03
Most likely a duplicate of https://github.com/Automattic/wp-calypso/issues/6334

@roundhill Since Plans live in Calypso, I'd recommend creating issues there. For all issues related to plans, you can use the ".org Plans" label.

**Closed by jeherve** 2016-10-20 19:03 UTC
Labels: Subscriptions, [Type] Bug

**Comment by roundhill** [comment] 2016-10-20 19:06
ok, many thanks!
