### ISSUE TITLE
Boost: insecure ajax api endpoint

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#21136] opened 2021-09-21 02:20 UTC
API endpoint for dismissing advanced critical css recommendations uses a generic nonce which doesn't describe the action, and does not use `current_user_can` to verify the user has access to undertake the action.

See: https://github.com/Automattic/jetpack/blob/master/projects/plugins/boost/app/modules/critical-css/class-critical-css.php#L984

**Comment by amustaque97** [comment] 2021-09-21 06:53
I would love to work on this issue. There are few things I want to discuss before jumping into its implementation.
* I can see there are two places where we have written `check_ajax_referer( self::AJAX_NONCE, 'nonce' );` 

https://github.com/Automattic/jetpack/blob/master/projects/plugins/boost/app/modules/critical-css/class-critical-css.php#L984
https://github.com/Automattic/jetpack/blob/master/projects/plugins/boost/app/modules/critical-css/class-critical-css.php#L1010

In both places, same changes are required or not? If no why it is like that?

* I want to purpose change something like this:
```
if ( check_ajax_referer( 'dismiss_notice' ) &&  current_user_can( 'manage_options' ) ) {
    $response = array(
		'status' => 'ok',
	);
} else {
    wp_die();
}
```

* After making changes how can I test and verify?

Please share your thoughts @thingalon  @eAdnan007 
Thank You

**Comment by thingalon** [comment] 2021-09-21 07:13
Hi @amustaque97 - thanks for offering to help out. 

Overall your proposal looks right to me. I don't mind if both of those endpoints use the same nonce - either called `dismiss_notice` or `manage_dismissed_notices` given they are so closely related. Just so long as it's not something as generic / prone to being reused as `ajax_nonce` ;)

As for how to test - there are a few steps involved. First you'd need Boost to give you an Advanced Critical CSS Recommendation. That occurs when it fails to generate Critical CSS for an area of your site, but not all of your site. The easiest way to do that is with a plugin which causes all posts with a custom post_type to redirect to an external URL - such as [simple-urls](https://wordpress.org/plugins/simple-urls).

Once you have an advanced recommendation, try using the X button to dismiss it. That should trigger one of the AJAX calls. Once all Advanced recommendations have been dismissed, a link will appear which lets you trigger the other AJAX call; resetting the dismissals. :)

**Comment by jeherve** [comment] 2021-09-21 07:38
If we're touching this, it may be a good opportunity to switch to using `wp_send_json_error` and `wp_send_json` instead of `wp_json_encode` / `wp_die` combos?

**Comment by amustaque97** [comment] 2021-09-21 10:43
@eAdnan007 this issue is still open or you're already working on it? Because I can see earlier you linked this Issue and then removed it? What is the final status for this issue?

**Comment by eAdnan007** [comment] 2021-09-22 02:33
> @eAdnan007 this issue is still open or you're already working on it? Because I can see earlier you linked this Issue and then removed it? What is the final status for this issue?

@amustaque97, The issue is still open. The PR I linked has some overlaps with this issue. I later realized that merging that would close this issue and I didn't want that.

**Closed** 2021-09-23 05:49 UTC
Labels: [Type] Bug, [Pri] High, [Plugin] Boost, [Boost Feature] Critical CSS
