### ISSUE TITLE
Plugin search hints: plugin search results should not be modified

### ISSUE THREAD

**Issue by jchristopher** [Automattic/jetpack#11815] opened 2019-04-02 17:10 UTC
I think modifying search results should not happen. 

If it is problematic that Jetpack users are not finding features of the plugin, perhaps the plugin has too much variation in its feature set and the features should be turned into their own plugins and marketed as such.

**Comment by mgibbs189** [comment] 2019-04-02 17:22
Agreed, I think this sets a dangerous precedent.

@jeherve curious to hear your thoughts, but honestly this should be marked as a `Bug`, not as an `Enhancement`.

**Comment by kraftbj** [comment] 2019-04-05 15:35
We're constantly reassessing the meta structure of Jetpack and what's the best way to deliver the functionality we've built into WordPress.com to WordPresses on other server environments.

In terms of the functionality where we are adding a "hint" of an existing feature to the plugin installer screen, we are iterating on it and will continue to investigate ways to do it. For more about the rationale, [we went into it a bit more on the 7.2.1 release post](https://jetpack.com/2019/04/04/jetpack-7-2-1-maintenance-release/).

I think the community-driven approach Yoast suggested in [46763-core](https://core.trac.wordpress.org/ticket/46763) is good and something we intend to work with the community on. Once that's in place, we will move to using that.

I'm going to close this ticket for now since we'll wait until any core functionality to be in place. In the meantime, we did make changes to address the absolutely valid and correct concerns made about hints for features that required (additional) payment. These include https://github.com/Automattic/jetpack/pull/11876 to only display hints for modules on the site's plan, https://github.com/Automattic/jetpack/pull/11929 that further tightened it since our backups/security scanning feature offer different levels of service at different plan levels, https://github.com/Automattic/jetpack/pull/11908 to prevent further hints once a few have been dismissed, and https://github.com/Automattic/jetpack/pull/11909 to make the cards indicate stronger they are coming from Jetpack which were all released yesterday as part of the [7.2.1 release](https://github.com/Automattic/jetpack/releases/tag/7.2.1) as an immediate set of changes to correct our error in judgement.

We intend to do more, but didn't want to delay the correction.

@mgibbs189 This was labeled an `enhancement` because of the way we try to classify reports. A bug is when is something is broken and not functioning as intended. An enhancement is a change in expected behavior. The feature technically works, so doing something different is an enhancement with our nomenclature, but sounds weird sometimes when the issue is the intended functionality itself.

Thanks to everyone for their feedback on Twitter, Post Status Slack and elsewhere.

**Closed by kraftbj** 2019-04-05 15:35 UTC
Labels: Feature Hints, [Type] Enhancement
