### ISSUE TITLE
Video Block - Upgrade notice broken on Gutenberg v8.1.0

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/jetpack#15796] opened 2020-05-14 22:49 UTC
#### Steps to reproduce the issue

1. Using a 'Free' plan site with `gutenberg-edge` sticker (for v8.1.0), visit the editor.
2. Insert a video block.
3. Notice the banner has disconnected from the block and the 'upload' button is enabled.

![Screen Shot 2020-05-14 at 1 10 52 PM](https://user-images.githubusercontent.com/28742426/81993336-76ce5480-9613-11ea-9894-027b46a54cf2.png)

#### What I expected

![Screen Shot 2020-05-14 at 1 10 44 PM](https://user-images.githubusercontent.com/28742426/81993353-7b930880-9613-11ea-8a03-82c3a6671ff2.png)

**Comment by ockham** [comment] 2020-05-19 14:57
@roo2 found [this change](https://github.com/WordPress/gutenberg/commit/42d6f4289c91f1f03bd0c6e35c22ca93fad117ed#diff-97aaeddffef631da3c66dd479c0c6418R132) on the Gutenberg side that seems to have caused this.

I think the problem is specifically that the VideoPress block [wraps around the `core/video` block](https://github.com/Automattic/jetpack/blob/a92abfd326067811f74e9a55af0a8218bd1cdbe2/extensions/blocks/videopress/edit.js#L267), and the latter's new extra `div` wrapper is messing up the styling.

**Comment by apeatling** [comment] 2020-05-19 18:31
I'm not seeing any way to easily fix the notice placement issue with the new wrapper. :/

**Comment by apeatling** [comment] 2020-05-19 18:34
It's possible to hack it visually with CSS, but I suspect this to be incredibly fragile and not a good idea.

**Comment by scruffian** [comment] 2020-05-19 20:38
The UpgradeNotice was meant to be following the same patterns as other notices in Gutenberg - how do other warning notices look in this block with this change?

**Comment by creativecoder** [comment] 2020-05-19 20:39
That [`<Block.div>` change](https://github.com/WordPress/gutenberg/commit/42d6f4289c91f1f03bd0c6e35c22ca93fad117ed#diff-97aaeddffef631da3c66dd479c0c6418R132) comes from an "experimental" component. Let's ask to have it put it back the way it was!

**Comment by apeatling** [comment] 2020-05-19 21:15
I don't think there is any way for us to do it, if someone else has any ideas please drop them here -- otherwise I think we should disable the notice here and see if we can get some sort of hook into core.

**Comment by apeatling** [comment] 2020-05-19 23:44
Left a note on the core issue to see how we can proceed. I don't have any suggestions there at this point, but Riad may have some thoughts.

**Comment by apeatling** [comment] 2020-05-19 23:44
> The UpgradeNotice was meant to be following the same patterns as other notices in Gutenberg - how do other warning notices look in this block with this change?

Those looks fine and continue to display within the placeholder.

**Comment by roo2** [comment] 2020-05-20 03:04
We've noticed that after uploading a video, the video block cannot be selected in 8.1.0. I wonder if that is related p1589943272033100-slack-create-gardeners

**Comment by ockham** [comment] 2020-05-20 13:03
> That [`<Block.div>` change](https://github.com/WordPress/gutenberg/commit/42d6f4289c91f1f03bd0c6e35c22ca93fad117ed#diff-97aaeddffef631da3c66dd479c0c6418R132) comes from an "experimental" component. Let's ask to have it put it back the way it was!

Andy asked here: https://github.com/WordPress/gutenberg/pull/22028#issuecomment-631145184

**Comment by ockham** [comment] 2020-05-20 16:52
We're reverting [this Gutenberg commit](https://github.com/WordPress/gutenberg/commit/42d6f4289c91f1f03bd0c6e35c22ca93fad117ed#diff-97aaeddffef631da3c66dd479c0c6418R132) for WP.com as a temporary fix (D43703-code).

However, we'll need to sort this out in Jetpack since that change is here to stay, and the issue would break on self-hosted sites with Gutenberg >= 8.1. Riad left [some pointers on how to fix](https://github.com/WordPress/gutenberg/pull/22028#issuecomment-631357407).

**Comment by apeatling** [comment] 2020-05-20 21:29
@ockham Based on this being in your backlog now, are you taking this change on in the Create Focus?

**Comment by ockham** [comment] 2020-05-20 22:10
I added it to our maintenance board to keep track of it (but wasn't planning to work on it myself). We should get it sorted out tho, I realized that we basically need the Jetpack fix for Atomic sites. @apeatling Do you have any spare cycles to work on this? Otherwise I can look into it.

@youknowriad Do you have some additional pointers for us how to best tackle this within the light wrapper setting? Unlike the block toolbar (that uses a Popover, as you've mentioned in [your other comment](https://github.com/WordPress/gutenberg/pull/22028#issuecomment-631357407)), the upgrade nudge is supposed to take up some vertical space above the block permanently (well, until the user upgrades their plan).

**Comment by youknowriad** [comment] 2020-05-21 09:39
@ockham I think we need some explorations here. The Popover component can potentially be used to cover the anchor I believe using maybe `getAnchorRect`. that said, it's not something I've tried, the Popover component also changed a lot that I don't know how it works entirely at the moment. 

If it doesn't work, or it's too complex, I think it's reasonable to consider a dedicated API to add "children" or content inside the block wrappers which could be used to add an absolute positioned element right.

**Comment by ockham** [comment] 2020-05-21 13:04
I played with this a bit. The Popover approach looks very complex (potentially a lot of manual calculations of dimensions, and I'm not sure it'd give us more than the div we have now). I might've found a simpler way tho :slightly_smiling_face:

**Comment by ockham** [comment] 2020-05-25 17:19
Fixed by #15883 and #15906.

**Closed by ockham** 2020-05-25 17:19 UTC
Labels: Gutenberg, VideoPress, [Pri] High, [Type] Bug
