### ISSUE TITLE
Markdown: Enabling does nothing on latest master

### ISSUE THREAD

**Issue by aheckler** [Automattic/jetpack#6442] opened 2017-02-18 15:06 UTC
To repro:

1. Run latest master of Jetpack.
2. With Markdown module off, enable it.
3. Add a new post/page, enter some markdown.
4. Publish it.

What I expected: markdown to be changed to HTML.

What happened: markdown comes out raw. Screenshot:

<img width="303" alt="screen shot 2017-02-18 at 10 05 00 am" src="https://cloud.githubusercontent.com/assets/5512652/23094164/b9528948-f5c1-11e6-80b8-a24a80545f68.png">

I think this is because the new setting under Settings > Writing does not automatically get turned on:

<img width="535" alt="screen shot 2017-02-18 at 10 05 46 am" src="https://cloud.githubusercontent.com/assets/5512652/23094168/d6112382-f5c1-11e6-97b3-e74df9a51f93.png">

Probably related to https://github.com/Automattic/jetpack/pull/6406 cc @eliorivero

**Comment by Stoyan0v** [comment] 2017-03-02 08:59
It seems that there are two PRs for Markdown module.
The first one is #6406 and it adds new endpoint and removes the code that enables the module.

The second one #6396 is similar to the first one, but it has additional commit (8c1ba3dc9d27dffc184e786f8f7c45d3ed7ccbd3) which contains the code for enabling the module ( this code is missing in master branch right now ).  

The issue is that the second PR is merged in [feature/settings-overhaul](https://github.com/Automattic/jetpack/tree/feature/settings-overhaul) branch not in master, while the first one is merged in master. So I think that if the [feature/settings-overhaul](https://github.com/Automattic/jetpack/tree/feature/settings-overhaul) branch will be merged in master before 4.7 release, the module will work as expected.

cc @jeherve @eliorivero

**Comment by jeherve** [comment] 2017-03-02 11:19
@eliorivero Do you think we should bring that commit over to `master`?

**Comment by eliorivero** [comment] 2017-03-02 13:39
@jeherve that commit referenced by @Stoyan0v is only for the new settings UI.

I'll try to devise something for the current UI.

**Closed** 2017-03-06 16:23 UTC
Labels: Markdown, [Pri] BLOCKER, [Type] Bug
