### ISSUE TITLE
Put the setting link back in the header like the previous version

### ISSUE THREAD

**Issue by robertdall** [Automattic/jetpack#5147] opened 2016-09-08 16:34 UTC
Where is the setting link that use to be on the top of the page. I clicked all three links that are their. One is the dashboard, but you call also call it at a glance? Lets call it one thing and stick to it ok? It can be "at a glance" or it can be "dashboard" but it can't be both. 

There is no link in the header that show you the setting page. You have to go into the WordPress menu Bar to find that settings link and then click on to find the Jetpack modules that you want to edit.

Also Apps and Plans links start with large adds for WordPress apps and WordPress.com Advertisements and not related Jetpack Functionality.

So out of three links on the front page one has a confusing title that doesn't show all that jetpack is actually capable of and two are glorified adds for Automattic projects. 

Disappointing to say the least.

<img width="783" alt="screen shot 2016-09-08 at 9 27 22 am" src="https://cloud.githubusercontent.com/assets/1909677/18357609/7c902d30-75a6-11e6-8928-d8c043289540.png">

**Comment by jeherve** [comment] 2016-09-08 16:39
Closing as duplicate of #4821.

Also related, for more discussion about navigation items: #4482

**Closed by jeherve** 2016-09-08 16:39 UTC
