### ISSUE TITLE
Paid content block / Paywall block doesn't show content after going Atomic

### ISSUE THREAD

**Issue by aleone89** [Automattic/jetpack#33151] opened 2023-09-18 17:37 UTC
### Impacted plugin

Jetpack

### Quick summary

The Paywall block does not show content of any kind once the site goes from Simple to Atomic on WordPress.com. 

### Steps to reproduce

1. Go to pages/posts > Add new > Add page title 
2. Create a Paid Newsletter as per these steps here: https://en.support.wordpress.com/paid-newsletters/ 
3. Upgrade to the WordPress.com Business plan
4. Sign out of WordPress.com
5. Visit page with Paid Content block present 

### A clear and concise description of what you expected to happen.

I expected to see a sign up prompt as detailed here: https://wordpress.com/support/paid-newsletters/#what-your-subscribers-will-see

### What actually happened

There is a blank space where the content block resides. 

When signed in, the site owner will see "Connect to Stripe in the editor to use this block on your site." message. 

<img width="691" alt="Screenshot on 2023-09-18 at 18-36-34" src="https://github.com/Automattic/jetpack/assets/39101026/86de17a8-94f7-43de-90bc-a7da106fbc53">

In the site itself, Stripe would already be connected. 

### Impact

Most (> 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Atomic

**Comment by aleone89** [comment] 2023-09-18 17:38
Reported here: https://wordpress.com/forums/topic/premium-content-not-showing-up-stripe-connection-issue/?view=all

**Comment by cuemarie** [comment] 2023-09-18 17:44
@millerf KitKat is at a team meetup and we can't quite look at this immediately, so flagging for your awareness!

**Comment by cuemarie** [comment] 2023-09-18 19:33
📌 REPRODUCTION RESULTS
- Tested on Simple -> Atomic – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated as described. Once I AT'd my site, the Paid Content block is hidden on my page.

Dis/reconnecting Stripe restored the block on the page, but my site owner's logged in view of the page still shows the Guest View, without the Log In button anymore, reflecting the description in this report:

- https://github.com/Automattic/jetpack/issues/33154

However, I am able to successfully subscribe to the block and view the subscriber-only content from another account - so this doesn't seem like an absolute blocker.

📌 ACTIONS
- Dropping to High Priority for now, but will escalate as well for 👀 asap
- FYI @jeherve & @Automattic/gold

**Comment by cuemarie** [comment] 2023-09-18 19:54
Possibly the same underlying issue as:

- https://github.com/Automattic/jetpack/issues/32614

**Comment by cuemarie** [comment] 2023-09-18 19:56
Escalated here: p1695066962939419-slack-C01LXBU1N21

**Comment by supernovia** [comment] 2023-09-22 00:23
Running this from CLI seemed to clear this case:
`option update jetpack-memberships-has-connected-account 1
`

**Comment by cuemarie** [comment] 2023-09-27 23:57
📌 ACTIONS
- Since the user from this report is taken care of, and the remaining issue is resolved by dis/reconnecting Stripe, I'm lowering this to `Normal` priority for now. Thanks all!

**Comment by millerf** [comment] 2023-10-02 11:58
> @millerf KitKat is at a team meetup and we can't quite look at this immediately, so flagging for your awareness!

Sorrt I was AFK last week. I think I saw related discussions somewhere where @n3f answered? Gold will be in a meetup soon but we could look into this then...

[EDIT] Discussions are in Slack, see https://github.com/Automattic/jetpack/issues/33151#issuecomment-1724279654

**Comment by n3f** [comment] 2023-10-02 17:11
@millerf I don't know if I ever wrote down the problem.  I can't find it if I did, so I'll put it here.  When the site goes atomic the jetpack memberships options aren't being synced with the new site.  Not sure why or how to fix, but that's the base issue.  Recreating the option manually does fix the issue though.

**Comment by n3f** [comment] 2023-12-06 19:41
Solved in D131026-code (let me know if you still see errors).

**Closed as completed by n3f** 2023-12-06 19:41 UTC
Labels: Bug, [Pri] Normal, [Plugin] Jetpack, Triaged, [Platform] Atomic, [Feature] Paid Content, [Status] Priority Review Triggered, [Feature Group] Customer Seller Experience
