### ISSUE TITLE
Contact Form Conflict with Page Builder by SiteOrigin Plugin

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#2073] opened 2015-05-01 20:37 UTC
In Jetpack ticket 2176211, a user reported that his Jetpack contact form was not working correctly.

After testing the contact form myself, I was able to verify that the contact form did not submit.

After receiving admin credentials from the user, I noticed that the Jetpack contact form successfully worked after deactivating the Page Builder by SiteOrigin plugin.

User is using this theme: https://siteorigin.com/theme/vantage/

@mikeyarce mentioned that he has noticed many themes in ThemeForest require Page Builder. So, perhaps we should find a way to support that plugin?

@kraftbj mentioned that an issue with Advanced Custom Fields might be related. http://support.advancedcustomfields.com/forums/topic/wysiwyg-and-apply_filters-the_content-issue/#post-23935

**Comment by kraftbj** [comment] 2015-05-01 20:39
Marking as vFuture as @georgestephanis has things in the planning stages for the contact form.

**Comment by jeherve** [comment] 2017-03-06 16:39
Closing as duplicate of #3109

**Closed by jeherve** 2017-03-06 16:39 UTC
Labels: Contact Form, [Type] Bug
