### ISSUE TITLE
Plans: upgrade/setup link incorrect for multisite

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#9103] opened 2018-03-20 22:11 UTC
The links for upgrading from the ProStatus component (which is used on the main dashboard) goes to urls such as: https://wordpress.com/plugins/setup/greg.ichneumon.net?only=akismet

See: https://github.com/Automattic/jetpack/blob/0ac028407650baec830efc613100ef1c6ffc06c8/_inc/client/pro-status/index.jsx#L138

For multi-site installations, that page doesn't work: https://cloudup.com/clxq04f92Sz

<img width="1035" alt="screen shot 2018-03-20 at 4 09 46 pm" src="https://user-images.githubusercontent.com/1119271/39386880-dc82412a-4a33-11e8-9410-79a4dab5dd8c.png">

This is probably a very significant bug that is blocking people from trying to upgrade. (Found while trying to implement an upgrade button for Search).

**Comment by designsimply** [comment] 2018-04-30 23:01
I would like to help test this but I am not sure I have the right steps. Are the following steps right?

1. Install WordPress Multisite.
1. Go to wp-admin > Jetpack > Settings.
1. Search for 'akismet'.
1. Click the 'Upgrade' button and make sure it leads to an appropriate location.

Result: I landed at https://jetpack.com/pricing/settings-spam/?cta=https%3A%2F%2Fwordpress.com%2Fjetpack%2Fconnect%2Fstore%2F%3Fsite%3Dbh.testjetpack.blog%3A%3Amulti%3A%3Aone&site=bh.testjetpack.blog%3A%3Amulti%3A%3Aone

Video example: [29s](https://cloudup.com/csTVHUTli_g)

**Comment by gibrown** [comment] 2018-05-01 19:29
The upgrade buttons are the ones on the Jetpack dashboard like these:

![screen shot 2018-05-01 at 12 34 08 pm](https://user-images.githubusercontent.com/820871/39489581-47ea0bf2-4d43-11e8-827a-ecbf20a68513.png)

But I can't seem to get those links to display in the current UI with the wordpress.com/plugins/setup/ url for some reason. I think because you need the correct combo of plans and things not configured. I ran into this while trying to reuse that code for other upgrade buttons, but pretty sure I did recreate it. :/

This button does supposedly get used in a number of places though: https://github.com/Automattic/jetpack/blob/0ac028407650baec830efc613100ef1c6ffc06c8/_inc/client/pro-status/index.jsx#L132

**Comment by jeherve** [comment] 2018-09-13 12:43
I'll close this one as duplicate of https://github.com/Automattic/wp-calypso/issues/11759 , since it seems to be the same underlying problem.

**Closed by jeherve** 2018-09-13 12:43 UTC
Labels: FixTheFlows, Multisite, Plans, [Pri] High, [Type] Bug, [Type] Duplicate
