### ISSUE TITLE
Subscriptions: confirmation emails use wrong url

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/jetpack#9119] opened 2018-03-22 11:14 UTC
#### Steps to reproduce the issue

Subscribe to posts on a site with different urls for Site url and Home url

e.g. https://www.dfstudio.com

#### What I expected

The confirmation emails would include links to https://www.dfstudio.com

#### What happened instead

Both the 'Confirm your subscription' and 'Confirmed Subscription' emails contain links to the site url:

![image](https://user-images.githubusercontent.com/1990037/37767412-fac5e5e4-2dc1-11e8-9cb2-ea0b603eb5eb.png)

![image](https://user-images.githubusercontent.com/1990037/37767476-29e37832-2dc2-11e8-8607-12439ce1bb9e.png)

1015881-zen

**Comment by jeherve** [comment] 2018-03-22 16:18
Closing as duplicate of 3056-wpcom

**Closed by jeherve** 2018-03-22 16:18 UTC
Labels: Subscriptions, [Type] Bug, [Type] Duplicate
