### ISSUE TITLE
Contact Info & Map widget not recognizing address

### ISSUE THREAD

**Issue by thebud15** [Automattic/jetpack#11100] opened 2019-01-08 03:30 UTC
## Summary

When using a Google-appropriate Australian address, a user for an Atomic site is unable to properly use this address in the widget. The error appears as follows: `Sorry. We can not plot this address. A map will not be displayed. Is the address formatted correctly?`. The user had also generated and used an API code that seemed to be without error.

The address being used, which match up with Google's formatting of is (and confirmed by Google's support team) is:

```
21 Eustace St
Manly NSW 2095, Australia
```

## Steps to Reproduce

1. Added the Contact Info & Map widget to my own test Jetpack site. 
2. Used the address mentioned above in the `Address` field. 
3. I added the user's same API code in the appropriate field. 

### Expected Result
I expected for this to properly add the map to the widget. 

### Actual Result
I came across the same error of `Sorry. We can not plot this address. A map will not be displayed. Is the address formatted correctly?`, even before being able to add the API code.

**Comment by thebud15** [comment] 2019-01-08 03:32
Reported here and can be replied to at 1699926-zen

**Comment by htdat** [comment] 2019-01-08 08:56
@thebud15 - closing this issue as it's a duplicate of https://github.com/Automattic/jetpack/issues/10355

**Closed by htdat** 2019-01-08 08:56 UTC
Labels: Extra Sidebar Widgets, [Pri] Normal
