### ISSUE TITLE
Comments: Comment field sizing is broken, text is hidden.

### ISSUE THREAD

**Issue by scosgro** [Automattic/jetpack#18338] opened 2021-01-13 22:23 UTC
#### Steps to reproduce the issue

1. Found on WordPress.com - Activate a newer theme, like Twenty Twenty One, or Twenty Twenty, or Twenty Nineteen, or any Varia based theme.
2. Enable comments on a post, publish the post, visit the post, view the comment form.

#### What I expected
The Comment form/field to be legible and visible on the page. 

#### What happened instead
The comment form/field is squished, and the text is not legible, making the field obscured to visitors.

**Screenshots**
Twenty Twenty One:
![image](https://user-images.githubusercontent.com/30731356/104517380-bd14f280-55aa-11eb-9c1b-43d8f8d7e320.png)

Twenty Twenty: 
![image](https://user-images.githubusercontent.com/30731356/104517427-d0c05900-55aa-11eb-95a0-a66429c327d1.png)

Spearhead: 
![image](https://user-images.githubusercontent.com/30731356/104517450-dc138480-55aa-11eb-9233-b2cb40e686d1.png)

**Comment by Aurorum** [comment] 2021-01-14 10:41
Came here to report this issue as I received some comments on it. :) 

It also appears to affect non-WordPress.com themes too; this one is Ashe.

<img width="910" alt="Screenshot 2021-01-14 at 10 39 42" src="https://user-images.githubusercontent.com/43215253/104580280-f73ace80-5654-11eb-83ef-0f341c53c3a2.png">

**Comment by jeherve** [comment] 2021-01-14 13:26
@sgomes Could it be caused by r219199-wpcom?

**Comment by jeherve** [comment] 2021-01-14 13:27
Also reported here:
https://wordpress.org/support/topic/enter-your-comment-here-message-is-cut-off-in-comments-box/

**Comment by sgomes** [comment] 2021-01-14 13:32
@jeherve It's possible that it's related, I'll investigate.

**Comment by sgomes** [comment] 2021-01-14 13:37
That does indeed appear to be what's causing the issue. I'll prepare a fix.

**Comment by sgomes** [comment] 2021-01-14 13:56
Fix ready for review at D55356-code. This should not affect Jetpack code.

**Comment by sgomes** [comment] 2021-01-15 11:35
The fix is now live! Closing the issue, as it should be fixed, but please feel free to reopen if there are any further issues.

**Comment by firdousebareen** [comment] 2021-01-20 11:11
Hello, this was fixed (I last checked yesterday). But this morning, the same issue seems to be back.

**Comment by sgomes** [comment] 2021-01-20 11:18
Thanks for letting me know, @firdousebareen! Can you give me an example of a site where the issue pops up? I can't seem to reproduce it in my test page.

**Comment by firdousebareen** [comment] 2021-01-20 11:20
Ah ok that's interesting. I've noticed it on my site: https://www.samwoolfe.com/ I've attached a screenshot as well.

![Screen Shot 2021-01-20 at 11 20 17](https://user-images.githubusercontent.com/77728493/105168019-6ad75280-5b11-11eb-8dbf-beba687ae5c7.png)

**Comment by sgomes** [comment] 2021-01-20 11:21
Thank you, @firdousebareen! 👍  I'll investigate.

**Comment by firdousebareen** [comment] 2021-01-20 11:21
Thank you! Much appreciated :)

**Comment by sgomes** [comment] 2021-01-20 12:21
It appears that the comments box doesn't resize correctly when it's inside of an iframe. However, I can't find any connection between this and any of my changes. Continuing to investigate.

**Comment by sgomes** [comment] 2021-01-20 13:12
The issue turned out to be related to my code indeed. It was a tricky scheduling issue between jQuery and non-jQuery code. D55685-code has the fix.

**Comment by sgomes** [comment] 2021-01-20 13:23
The issue should now be fixed again. Could you please confirm that's the case for you. @firdousebareen?

**Comment by firdousebareen** [comment] 2021-01-20 13:30
Hi @sgomes It's working! Thanks for fixing that.

**Comment by sgomes** [comment] 2021-01-20 13:32
No worries, @firdousebareen! Thank you for letting me know it was broken again 🙂

**Closed by sgomes** 2021-01-20 13:32 UTC
Labels: Comments, Involves Happiness, [Pri] High, [Status] In Progress, [Type] Bug
