### ISSUE TITLE
Masterbar: Most links don’t work on mobile devices

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#9139] opened 2018-03-23 19:54 UTC
Related: #9098 

- Enable the WP.com Toolbar on a Jetpack site
- Go to the front-end of the site on a mobile device (specifically, an iPad)
- Open the My Sites menu, and attempt to tap on any of the items
- Note that a lot of them are non-responsive

In my testing (tried every menu item), the following items _do not_ work (again, on an iPad) at all. The other items which do work require 2 taps.

My Sites
- Site Icon (URL/title does work)
- Plan
- Site Pages (or Add)
- Blog Posts (or Add)
- Themes (or Customize)
- People (or Add)
- Plugins (or Manage)

Reader
- Followed Sites (or Manage)

**Comment by crunnells** [comment] 2018-06-28 21:48
Looks like a similar report to #8038

**Comment by jeherve** [comment] 2018-09-04 11:11
@crunnells You're correct. Closing as dupe of #8038.

**Closed by jeherve** 2018-09-04 11:11 UTC
Labels: Masterbar, [Type] Bug, [Type] Duplicate
