### ISSUE TITLE
Undefined function (get_user_attribute) errors in admin pages

### ISSUE THREAD

**Issue by yohgaki** [Automattic/jetpack#5287] opened 2016-10-08 23:25 UTC
#### Steps to reproduce the issue

I moved my blog from CentOS6+PHP5.6 to CentOS7+PHP7.1RC3, then I start getting Undefined function (get_user_attribute) errors in admin pages somehow. No additional module nor data changes at all.

I had to change

if ( defined( 'IS_WPCOM' ) && IS_WPCOM ) {

to

if ( false && defined( 'IS_WPCOM' ) && IS_WPCOM ) {

in

wp-content/plugins/jetpack/modules/after-the-deadline.php

I grepped all php files to see if get_user_attribute() is defined anywhere and didn't find any. Letting 'if' condition false seems to solve this issue.

#### What I expected

No errors.

#### What happened instead

Blank pages in admin pages due to undefined function.

**Comment by jeherve** [comment] 2016-10-10 11:17
Could you tell us about your installation of WordPress? Did you build it from a specific image, or clone it from somewhere?

**Comment by jeherve** [comment] 2016-10-27 11:43
Closing this for now as I can't reproduce. Let us know if you still experience the issue, and if that seems specific to your set up.

Thanks!

**Closed by jeherve** 2016-10-27 11:43 UTC
Labels: AtD, [Status] Needs Author Reply

**Comment by yohgaki** [comment] 2016-12-18 07:35
You should be able to reproduce with any PHP version if
`( defined( 'IS_WPCOM' ) && IS_WPCOM ) `
is true. It's a simple "undefined function error". To reproduce error, just set the if condition to true.

I checked plain Wordpress tarball and my installation, there is no **get_user_attribute** definition found with 

`find . -type f | xargs grep -n 'get_user_attribute'`

I suppose it's dead/legacy from the comment.
`// This wpcom-specific code should eventually be moved elsewhere.`

**Comment by jeherve** [comment] 2016-12-18 14:23
`get_user_attribute()` is a WordPress.com-specific function. That's why we check if `IS_WPCOM` is defined before to use that code. It is not run anywhere outside of WordPress.com, except if you intentionally set `IS_WPCOM ` to true on your WordPress installation. If you did, you'll want to set it to `false`. `IS_WPCOM` is only meant to be used on WordPress.com.

I hope this helps.

**Comment by yohgaki** [comment] 2016-12-19 01:00
Ok then, something should be wrong, but I don't change single line on my wordpress except the line to disable the "if". I get this error on occasion, but it persists and I can reproduce error always when it persists.

I did more checks. It may be opcache issue. There is no "define()" not "const" in the source. It seems opcode is messed up somehow.
So bug will be handled on PHP devs. Thank you for the info.
(FYI, the issue is disappeared for now. I should have kept the backup that can trigger this bug)
