### ISSUE TITLE
Pay with PayPal Block: image alignment issues on the frontend

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#17666] opened 2020-10-30 17:14 UTC
#### Steps to reproduce the issue

1. Start from a site with a paid plan
2. Go to Posts > Add New, and add a new Pay with PayPal Block.
3. Add an image to that block, and publish your post.
4. On the frontend, you'll see that the image does not align with the title of the product.

![image](https://user-images.githubusercontent.com/426388/97736191-9aab2700-1adb-11eb-8d7a-567233af5f8e.png)

------

p8oabR-za-p2#comment-4767

**Comment by rcrdortiz** [comment] 2022-01-10 11:28
Could not reproduce. This is how the Pay with PayPal Block actually looks:
<img width="778" alt="Captura de pantalla 2022-01-10 a las 12 26 38" src="https://user-images.githubusercontent.com/1989914/148758862-03a698e1-c7ec-4e68-942e-2f497120b1e6.png">
I'll close the issue.

**Closed by rcrdortiz** 2022-01-10 11:28 UTC
Labels: [Type] Bug, [Pri] Low, Pay With Paypal, [Block] Pay With Paypal
