### ISSUE TITLE
Unauthorized sharing to Facebook

### ISSUE THREAD

**Issue by Shelob9** [Automattic/jetpack#3281] opened 2016-01-15 19:40 UTC
In the publicize module, at sometime I authorized the connection to Facebook. I have since removed it. I am still seeing my posts shared to Facebook and it is happening via WordPress.com.

Maybe there is another setting on WordPress.com I should be aware of, in which case, yes this is a support issue and I can take it up with them, but then I would argue this is a UI issue in Jetpack.

![screen shot 2016-01-15 at 1 01 53 pm](https://cloud.githubusercontent.com/assets/1994311/12363223/a1bde2f8-bb95-11e5-9eed-07957d28c8f3.png)

![screen shot 2016-01-15 at 2 38 35 pm](https://cloud.githubusercontent.com/assets/1994311/12363246/baa4aae0-bb95-11e5-9a5f-f6a92cf6f56a.png)

**Comment by jeherve** [comment] 2016-01-16 14:48
Could you [send us an email](http://jetpack.me/contact-support/) with more information about your site, and the steps you followed to disconnect your Facebook account? Once we can reproduce the issue and understand what happened, we should be able to update this issue with more actionable info!

Thanks!

**Comment by Shelob9** [comment] 2016-01-16 18:32
@jeherve I honestly just noticed this. I thought I turned if off months ago, which is before I did a site migration. I presume I clicked disconnect button in the Jetpack settings.

And yes, on WordPress.com, Facebook was still listed as connected. I disconnected that. I don't have any posts queued up right now to test with though.

Seems like if there is going to be two buttons, they should be synced up somehow...

**Comment by jeherve** [comment] 2016-01-18 10:09
> if there is going to be two buttons, they should be synced up somehow...

That'd be best, yes! :) It turns out that there won't be two buttons for much longer, though.

I'll close this issue since that second interface will disappear in Jetpack 4.0, and thus solve that synchronization issue. Feel free to subscribe to #3258 to follow our progress on this.

**Closed by jeherve** 2016-01-18 10:09 UTC
Labels: Publicize, [Status] Needs Author Reply, [Team]  I/O, [Type] Bug
