### ISSUE TITLE
Top posts widget not handling post types well

### ISSUE THREAD

**Issue by leogermani** [Automattic/jetpack#15104] opened 2020-03-24 19:48 UTC
When Top Posts & Pages widget is configured to fetch only one or few post types, it may not behave as expected.

If a site has a large number of posts of a certain post type, and you add a widget to show the Top Posts of another post type, it may not find any.

That's because WordPress.com API doesn't allow you to fetch the top posts filtered by a post type. This filter has to be done later on the client side. So if a site has a large number of popular posts of a post type, the widget might never find the post type it is looking for.

Also, when no posts are found, it displays only one post for the visitor and ignores the post type configuration.

**Comment by jeherve** [comment] 2020-03-25 08:17
Closing as duplicate of #2369.

**Closed by jeherve** 2020-03-25 08:17 UTC
Labels: Extra Sidebar Widgets
