### ISSUE TITLE
Jetpack: undefined prop ref notice from widget-conditions.php

### ISSUE THREAD

**Issue by samiff** [Automattic/jetpack#20956] opened 2021-09-03 20:52 UTC
### Impacted plugin

Jetpack

### Steps to Reproduce

* With Jetpack active and debug/logging enabled, and a couple pages published, visit `/wp-admin/widgets.php`
* In your error log, you will see:

> Undefined property: stdClass::$post_status in /var/www/html/wp-admin/includes/misc.php on line 1434

We grab site pages here:

https://github.com/Automattic/jetpack/blob/79175ec45357f2da99a0c174aaf1e63007563335/projects/plugins/jetpack/modules/widget-visibility/widget-conditions.php#L236

But we customize how we fetch pages by only picking off some properties (id, post_parent, post_title):

https://github.com/Automattic/jetpack/blob/79175ec45357f2da99a0c174aaf1e63007563335/projects/plugins/jetpack/modules/widget-visibility/widget-conditions.php#L322-L335

Which is causing the `Undefined property` when `_wp_privacy_settings_filter_draft_page_titles()` is hit in `wp-admin/includes/misc.php`:

```php
function _wp_privacy_settings_filter_draft_page_titles( $title, $page ) {
	if ( 'draft' === $page->post_status && 'privacy' === get_current_screen()->id ) {
```

Would picking off the `post_status` property in that db query be overkill? Or just add it on manually after fetching the pages? Not sure on the best approach here.

**Comment by jeherve** [comment] 2021-09-06 08:26
Closing this as duplicate of #18616. 

> Would picking off the post_status property in that db query be overkill?

That's what I would go for as well. 👍

**Closed by jeherve** 2021-09-06 08:26 UTC
Labels: [Type] Bug, Widget Visibility, [Plugin] Jetpack
