### ISSUE TITLE
Admin UI: Admin card titles and content are not localized.

### ISSUE THREAD

**Issue by kwight** [Automattic/jetpack#9150] opened 2018-03-26 18:27 UTC
![screen shot 2018-03-26 at 11 25 00 am](https://user-images.githubusercontent.com/349751/37925107-986307cc-30e8-11e8-8559-d99afe1b60d3.png)

**Comment by jeherve** [comment] 2018-03-27 15:57
I could reproduce with another language, and the problem does not appear to be limited to Sharing.

**Comment by kwight** [comment] 2018-03-27 16:06
> I could reproduce with another language, and the problem does not appear to be limited to Sharing.

Indeed, it was my attempt at limiting scope 🙃 I didn't verify either if it's a case of the strings are not properly coded for i18n, or if they are, and those strings simply haven't been translated in the languages I looked at.

**Comment by jeherve** [comment] 2018-03-27 16:16
> I didn't verify either if it's a case of the strings are not properly coded for i18n, or if they are, and those strings simply haven't been translated in the languages I looked at.

I checked in French, where the strings are translated. Here is an example:

https://translate.wordpress.org/projects/wp-plugins/jetpack/stable/fr/default?filters%5Bterm%5D=Publicize+connections&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

https://github.com/Automattic/jetpack/blob/master/_inc/client/sharing/publicize.jsx#L66

<img width="452" alt="screenshot 2018-03-27 at 18 16 13" src="https://user-images.githubusercontent.com/426388/37980236-fa8b86ec-31ea-11e8-84a2-e920e97713a4.png">

**Comment by gwwar** [comment] 2018-04-09 17:50
cc @Automattic/i18n would you have any time to look into this?

**Comment by akirk** [comment] 2018-04-09 18:35
I took a look at this and the main reason seems to be that the translation is not included in the page HTML. I though via _inc/lib/admin-pages/class.jetpack-react-page.php just the language JSON would be included in the page on a quick first attempt it seemed this page wasn't used at all. Is there some caching of the admin pages happening? Does this pointer help?

**Comment by dereksmart** [comment] 2018-05-29 14:10
@kwight did you try updating the translations in `/wp-admin/update-core.php` after switching languages?

**Comment by jeherve** [comment] 2018-05-29 14:39
Noting that my translations were up to date when I tested above, but I was running a development version of Jetpack. That may play a role here.

**Comment by kwight** [comment] 2018-05-29 15:45
Ditto as @jeherve .

**Comment by jeherve** [comment] 2018-09-10 14:06
I can't seem to be able to reproduce the issue anymore, regardless of the version of Jetpack installed on my site. I'll close this issue for now; let's reopen if this starts happening again.

**Closed by jeherve** 2018-09-10 14:06 UTC
Labels: Admin Page, Internationalization, [Pri] High, [Type] Bug
