### ISSUE TITLE
Donations Block: Reblog button appearing in payment pop-up

### ISSUE THREAD

**Issue by dhackneya8c** [Automattic/jetpack#29105] opened 2023-02-22 21:03 UTC
### Impacted plugin

Jetpack

### Quick summary

When logged into a WPCOM account and viewing a Donations block on a page, if you select a frequency and payment amount and then click Pay, the payment pop-up form appears. In the bottom left corner, an odd unstyled reblog button also loads:

![Markup on 2023-02-22 at 12:36:01](https://user-images.githubusercontent.com/24231249/220752846-34a828c3-b7cb-40c0-b488-2a8a4931eb16.png)

CSS not an option as it's included in the iframe. Disabling sharing buttons (reblog) for the site at large as well as the individual page does not affect it.

### Steps to reproduce

1. Add a donations block to any page, set up payment plans/Stripe connection
2. Stay logged into a WPCOM account
3. View on the live page, click Pay to launch payment pop-up

### A clear and concise description of what you expected to happen.

The reblog button should not appear at all.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

We tested on multiple themes, both FSE and classic, on both atomic and simple sites.

**Comment by dhackneya8c** [comment] 2023-02-22 21:16
Original reporting user in #5982870-zen

**Comment by cuemarie** [comment] 2023-03-22 22:06
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: **Replicated**
- Tested on AT: **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated on AT and Simple sites - "Reblog" content appears at bottom of page after selecting "Donate"


**AT Example**
![Markup on 2023-03-22 at 14:58:35](https://user-images.githubusercontent.com/27249804/227048983-d8baa984-d42e-47a9-b636-b42b2376a0e7.png)

**Simple Example**
![Markup on 2023-03-22 at 15:00:29](https://user-images.githubusercontent.com/27249804/227048990-bce08374-0142-4fd1-a25c-c480968d9e33.png)

📌 ACTIONS
- Scrubbed; assignment pending

**Comment by cuemarie** [comment] 2023-04-04 23:46
📌 ACTIONS
- Assigned to Apex (for lack of a better home)

**Comment by jeherve** [comment] 2023-04-05 07:16
Closing as duplicate of #29616.

**Comment by romarioraffington** [comment] 2023-04-17 23:06
Re-opening since this issue a bit different from the issue above. I will create a fix for this!

**Comment by romarioraffington** [comment] 2023-04-17 23:19
The fix can be found in D108112-code

**Comment by romarioraffington** [comment] 2023-04-18 14:47
Code has been deployed to WordPress.com

**Closed as completed by romarioraffington** 2023-04-18 14:47 UTC
Labels: Bug, [Closed] Duplicate, [Pri] High, Customer Report [LEGACY], [Plugin] Jetpack, [Block] Donations, Triaged, [Platform] Simple, [Platform] Atomic, [Status] Priority Review Triggered
