### ISSUE TITLE
Videopress: Video block within column block, videos looking too tall 

### ISSUE THREAD

**Issue by ezebecke** [Automattic/jetpack#15363] opened 2020-04-08 00:42 UTC
#### Steps to reproduce the issue

This seems to be happening on simple sites only.

1. Open a new page and add a column block with 2 columns
2. Add a video inside each column
3. Publish or preview the page

#### What I expected

To see the videos being displayed with the same size that I see on the page editor.

#### What happened instead

Videos are looking too tall. They look OK on the page editor, but if we preview or check the published page then we see the videos getting resized. 

**Screenshots**

Published page:

<img width="915" alt="Screen Shot 2020-04-07 at 19 25 47" src="https://user-images.githubusercontent.com/24919469/78731858-88cb2200-7906-11ea-8e40-03caa90a4689.png">

Page editor:

<img width="970" alt="Screen Shot 2020-04-07 at 19 34 01" src="https://user-images.githubusercontent.com/24919469/78731944-d6478f00-7906-11ea-970c-bdbdef0ac9b0.png">

**Comment by jeherve** [comment] 2020-04-08 08:12
Closing as duplicate of #13168.

**Closed by jeherve** 2020-04-08 08:12 UTC
Labels: Gutenberg, VideoPress, [Type] Bug, [Type] Happiness Request

**Comment by eduardozulian** [comment] 2020-08-18 22:15
The only solution I see for now is adding some custom CSS to force a max-height for the video iframe:

```
.wp-block-column .wp-block-video iframe {
  max-height: 400px;
}
```
