### ISSUE TITLE
Hovering over the Tiled Gallery/Slideshow breaks the editor

### ISSUE THREAD

**Issue by Robertght** [Automattic/jetpack#21801] opened 2021-10-13 08:32 UTC
### Quick summary

I'm creating this issue as it's related to this one(https://github.com/WordPress/gutenberg/issues/35229) so we can track other reports.

It appears it's a conflict between CoBlocks and Gutenberg at the moment.

Video:

https://user-images.githubusercontent.com/6737345/137097007-c5714b95-fdf1-4654-a093-d8fe0a637d45.mp4

### Steps to reproduce

1. Access any page
2. Click on the + icon to expand the block library at the top left corner
3. Search for "gallery"
4. Hover over the Tiled Gallery block and wait for 2-3 seconds

### What you expected to happen

Not to break

### What actually happened

We got this:

![image](https://user-images.githubusercontent.com/6737345/137096254-dba515f0-07a0-47f9-a075-83ca3dcb3bcf.png)

### Context

#4371793-zen

### Operating System

macOS

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

No

### Other notes

The error messages:

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Sh (https://atomicbobv22018.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:152:147)
    at Rh (https://atomicbobv22018.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:148:115)
    at Sh (https://atomicbobv22018.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:151:394)
    at Rh (https://atomicbobv22018.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:148:115)
    at Sh (https://atomicbobv22018.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:151:394)
    at Qj (https://atomicbobv22018.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:174:181)
    at unstable_runWithPriority (https://atomicbobv22018.com/wp-content/plugins/gutenberg/vendor/react.min.755b0ae9.js:24:26)
    at Za (https://atomicbobv22018.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:8)
    at eb (https://atomicbobv22018.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:170:163)
    at gf (https://atomicbobv22018.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:162:317)
```

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Turn off Coblocks

**Comment by JoshuaGoode** [comment] 2021-11-18 20:37
I could not reproduce, across multiple browsers, on an active user report but it appears the user encounters it consistently. 

I've provided the user some troubleshooting steps including attempting to use another browser, clearing cache, and temporarily deactivating Gutenberg.

When resolved, let's try letting them know.

Internal references:

* p9F6qB-7GN-p2
* 4462270-zd-woothemes

**Comment by jeherve** [comment] 2021-11-22 11:20
I'm able to reproduce when first hovering (and thus triggering the block preview) for CoBlocks' carousel block, and then moving to any other block. This only happens with CoBlocks' carousel block, so I would recommend reporting this to the team in charge.

**Closed by jeherve** 2021-11-22 11:20 UTC
Labels: [Type] Bug, [Type] Happiness Request, [Block] Tiled Gallery, [Plugin] Jetpack

**Comment by filipanoscampos** [comment] 2021-11-22 16:37
I have another similar case here 32856617-hc.
The user can't add or edit posts and I was able to replicate the issue.

And the follow-up ticket is at 4536158-zd-woothemes.

I'm letting them know of the temporary workaround.

**Comment by AtrumGeost** [comment] 2021-11-23 20:15
Got another report here:

32387205-hc

**Comment by Gustavo-Hilario** [comment] 2021-11-27 18:07
Another report here: https://woothemes.zendesk.com/agent/tickets/4550288

**Comment by cat-og** [comment] 2021-12-05 21:09
Found a similar case with the same error report, but user was not able to open their pages at all. The temporary workaround of deactivating Gutenburg works for now.  33065466-hc

**Comment by ktyfuller604** [comment] 2021-12-06 21:46
Could reproduce the issue with the gif block when reported by 32045248-hc. Deactivating the Gutenberg plugin resolved the issue.

**Comment by poeticabdul** [comment] 2021-12-13 09:21
Another report here 33152413-hc

**Comment by filipanoscampos** [comment] 2022-01-20 12:52
The user on this chat (33758583-hc) and follow-up ticket (4704244-zd-woothemes) has the issue when they attempt to add a slideshow to a page.

Recommended deactivating Gutenberg for now and asked them to get back to us.

**Comment by kettultim** [comment] 2022-04-12 09:34
I don't know if this is related... but wen accessing a user's site and selecting any block in the hierarchy, an `The publisher encountered an unexpected error` error would prevent any editing. I've included the error code below. 

Disabling Gutenberg didn't fix it - *but* disabling and re-enabling did. Strange. Adding this for reference but I'm unable to replicate the issue again:

4941272-zd-woothemes

Screencast: https://d.pr/v/FLgsSC

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Sh (https://lesfrimoussesdesfaribambelles.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:152:165)
    at Qj (https://lesfrimoussesdesfaribambelles.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:174:181)
    at unstable_runWithPriority (https://lesfrimoussesdesfaribambelles.com/wp-includes/js/dist/vendor/react.min.js?ver=17.0.1:24:26)
    at Za (https://lesfrimoussesdesfaribambelles.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:73:8)
    at eb (https://lesfrimoussesdesfaribambelles.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:170:163)
    at gf (https://lesfrimoussesdesfaribambelles.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:162:317)
    at https://lesfrimoussesdesfaribambelles.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:73:230
    at unstable_runWithPriority (https://lesfrimoussesdesfaribambelles.com/wp-includes/js/dist/vendor/react.min.js?ver=17.0.1:24:26)
    at Za (https://lesfrimoussesdesfaribambelles.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:73:8)
    at $g (https://lesfrimoussesdesfaribambelles.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1:73:176)
```
