### ISSUE TITLE
Sharing: display the aggregation number of shared counts from all social networks

### ISSUE THREAD

**Issue by htdat** [Automattic/jetpack#8530] opened 2018-01-16 02:12 UTC
We can get the shared counts from each social networks as it is mentioned in https://jetpack.com/support/sharing/

> Some services have an additional option allowing you to display “official” buttons that show the number of times the post has been shared. Just choose your display option and drag the services you would like to display to the Enabled Services box.

We can save these shared numbers and create an aggregation number of shared counts, which is nice.

Ref: 859769-hc

**Comment by jeherve** [comment] 2018-09-05 09:20
Closing as duplicate of #844

**Closed by jeherve** 2018-09-05 09:20 UTC
Labels: Sharing, [Pri] Low, [Type] Duplicate, [Type] Feature
