### ISSUE TITLE
Sync: Site url syncing error for multisite

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#7997] opened 2017-10-16 19:07 UTC
#### Steps to reproduce the issue
Run the latest version of Jetpack and WP on a multi site withe the sub site setup. 
- have the following constants
```
define( 'WP_SITEURL', 'https://example.com' );
define( 'WP_HOMEURL', 'https://example.com' );
```

#### What I expected
That the sites would work as expected when interactiing with the API.

#### What happened instead
The sites returned the error jsonAPI not found. 
the siteurl for the subsites was being synced as the main sites url. 

cc @ebinnion. 

Note that 
`define( 'JETPACK_SYNC_USE_RAW_URL', false ); `
fixed the issue for me.

**Comment by jeherve** [comment] 2017-10-30 11:02
@ebinnion Would you mind taking a look at site ID 137325493?

- It's a subsite, part of a Multisite network, running Jetpack 5.5 Alpha (including #8006)
- The network uses [Bedrock](https://roots.io/bedrock/), so `siteurl` actually lives in a subdirectory.
- For some reason we did not pick that up when syncing. Right now the site options on our end have `siteurl` set to the same value as `home`.

Thank you!

**Comment by ebinnion** [comment] 2017-10-30 15:36
Would you get the user to run `wp jetpack sync start` on their site?

I just moved my multisite install into a subdirectory, ran that sync command, and the siteurl synced correctly.

https://wordpress.com/wp-admin/network/site-settings.php?id=132849040

<img width="535" alt="screen shot 2017-10-30 at 10 36 09 am" src="https://user-images.githubusercontent.com/1126811/32179738-29557e4e-bd5e-11e7-8c59-e658a86d824a.png">

Also, a new debug might be helpful now that the user has changed the Jetpack code they're running.

**Comment by jeherve** [comment] 2017-10-31 13:22
> Would you get the user to run wp jetpack sync start on their site?

That did not help unfortunately.

**Comment by jeherve** [comment] 2017-11-07 09:10
@ebinnion Is there anything else we could try to fix this?

**Comment by lamdayap** [comment] 2017-11-16 00:12
The user came back with the JP debug info (it's in the ticket).
@ebinnion - would you mind looking at this again?

**Comment by ebinnion** [comment] 2017-11-16 16:32
Dug in and left reply on ticket.

**Comment by jeherve** [comment] 2017-11-16 21:37
Thanks a lot. I replied to the user.

**Comment by JulienMelissas** [comment] 2017-11-18 22:14
Hey there! I'm pretty sure I'm the "user" here 😉... I appreciate all of your team's help!

I'm quite active on GitHub as I'm on the Roots team and seeing your references pop up here and there...

I've added your code as an `mu-plugin` and have responded to the ticket, but let me know if I need to do anything here as well.

**Comment by JulienMelissas** [comment] 2017-11-19 23:57
@ebinnion no worries! This should hopefully go by quicker, even though we're all done. I'm happy to do anything to get it working long-term, and I know we will all appreciate the built-in Bedrock support.

I ran it on production and this is what I've got:
```
commerce@lak-commerce:~/public$ wp jetpack sync start --modules=functions
PHP Notice:  Undefined index: HTTP_HOST in /www/{sorry, not this time ;)}/public/config/application.php on line 97
Initialized a new full sync with modules: functions
Sent data to WordPress.com
Success: Finished syncing to WordPress.com
```

It looks like the PHP Notice is a specific Cookie thing (`define('COOKIE_DOMAIN', $_SERVER['HTTP_HOST']);`) that was configured specific to our host popping up because I'm running a command in WP-CLI. Hopefully that doesn't cause any problems on your side.

Let me know what you think/if it worked!

**Comment by ebinnion** [comment] 2017-11-20 16:06
Hey @JulienMelissas - 

I can confirm that your siteurl now shows as having the `/wp` on our end. Also, your site has a clean debug at https://jetpack.com/support/debug/. All seems to be well with the world now! 💪 

Thanks for working with us on this.

**Comment by ebinnion** [comment] 2017-11-20 16:09
I created #8213 to track support for Bedrock. Closing this issue for now.

**Closed by ebinnion** 2017-11-20 16:09 UTC
Labels: IDC, Multisite, Sync, [Pri] High, [Type] Bug

**Comment by JulienMelissas** [comment] 2017-11-20 16:16
@ebinnion -- thanks for your help! I'm seeing a successful connection on the WP.com side of things too 👍 

If you need help in #8213 I help to maintain Bedrock (although mostly support and use-cases, I have much more time invested in our other projects) and we might be able to find a way to detect it. Bedrock is used by hundreds (possibly more) of popular sites, so this will be appreciated I'm sure.

**Comment by JulienMelissas** [comment] 2018-01-27 22:18
Hey folks! I'm getting this issue again on a new site, even with the above code mentioned. Should I re-open this here or would you like me to refer to our previous thread?

(ping @jeherve, @ebinnion)

**Comment by ebinnion** [comment] 2018-01-27 23:19
Hey @JulienMelissas –

Would you please submit a support request from the debugger in your Jetpack site? You can do that by going to `$site.com/wp-admin/admin.php?page=jetpack-debugger`, clicking the "click here to contact Jetpack support" link, and then filling out the form. Please mention me in the ticket and a happiness engineer will pass it off.

**Comment by JulienMelissas** [comment] 2018-02-02 20:24
@ebinnion I hate to do this over GitHub, but I just wanted to check in... I sent a request in a few days ago and haven't heard anything since. I mentioned you in the request. Request came from julien@craftpeak.com.

**Comment by ebinnion** [comment] 2018-02-02 20:28
No. That's perfectly fine. I'll try and track down that ticket right now.

**Comment by ebinnion** [comment] 2018-02-02 20:42
@JulienMelissas – I've sent you an email so we can chat there.

**Comment by ebinnion** [comment] 2018-02-06 16:19
Hey @JulienMelissas – I didn't receive a reply back to my email. 

We did get a ticket in about 40 minutes ago to which I have replied. I wanted to be sure to let you know I responded so you can be on the lookout.
