### ISSUE TITLE
Admin Page: Error on hovering stat bars on IE11

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack#5724] opened 2016-11-19 17:19 UTC
With Jetpack 4.4-rc2, when browsing my site in IE11, I get console errors when hovering over the stats bars. In one of the two IE11 setups, this caused a dialog to be shown over and over, which was a horrible experience. In the other IE11 setup, errors were constantly being thrown in to the console. The rest of the admin page seemed to work in both cases.

![error_dialog](https://cloud.githubusercontent.com/assets/1126811/20457108/d0472a9c-ae49-11e6-9f9a-c2005b510982.jpg)

#### Steps to reproduce the issue

Open IE11 browser. Ensure you have 4.4-rc2. Hover over stats bars.

#### What I expected

No errors and to see a tooltip.

#### What happened instead

Errors.

**Comment by eliorivero** [comment] 2016-11-19 22:55
While I can't reproduce this with my Win10 + Edge even when it's in IE 11 emulation mode, from the message I can't tell there's something trying to call the `.assign()` JavaScript object method which is not supported at all in IE as this link shows
https://developer.mozilla.org/nl/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Browser_compatibility

I opened this PR https://github.com/Automattic/dops-components/pull/73 since I found that there's an usage of `Object.assign` in the popover component and maybe that's the issue.

Can you please pull, link, build and see if the issue is solved?

cc @samhotchkiss

**Comment by samhotchkiss** [comment] 2016-11-21 21:41
Fixed in Automattic/dops-components#73

**Closed by samhotchkiss** 2016-11-21 21:41 UTC
Labels: Admin Page, [Pri] BLOCKER, [Type] Bug
