### ISSUE TITLE
Sharing module strips footnote links from displaying

### ISSUE THREAD

**Issue by mattwiebe** [Automattic/jetpack#2417] opened 2015-07-19 00:42 UTC
PHP 5.3.29 / WP 4.2.2 / Jetpack 3.6

1. Enable Sharing and Markdown modules
2. Write a post with footnotes.
3. After saving a draft and previewing, note that all footnote links (eg `<sup id="fnref-7449-2"><a href="#fn-7449-2" rel="footnote">2</a></sup>`) are stripped on frontend display.
4. Note that browsing through the revisions interface still shows the footnote links properly, so they're there in the DB
5. Deactivating the sharing module: see the footnote links restored

**Comment by mattwiebe** [comment] 2015-07-19 00:45
It appears that the same thing happens with the Publicize module. Very odd.

**Comment by jeherve** [comment] 2015-12-10 18:13
I can't seem to reproduce anymore, using JP 3.8.1 / WP 4.4 / PHP 5.4.

Closing for now, since we haven't had any other reports about this. @mattwiebe If this is still an issue for you, could you paste a text sample here, so I can try to reproduce with the exact same markup you used?

Thanks!

**Closed by jeherve** 2015-12-10 18:13 UTC
Labels: bug, Publicize, Sharing

**Comment by mattwiebe** [comment] 2015-12-10 22:26
I can still reproduce in my own theme, but I tried previewing in a core theme in the Customizer and the footnote links render fine. It must be an issue in my theme somewhere.
