### ISSUE TITLE
Proposal/idea: Carousel Image Size with title & meta descr always visible

### ISSUE THREAD

**Issue by StefMattana** [Automattic/jetpack#8418] opened 2017-12-25 08:40 UTC
A user [has recently asked on the forum](https://wordpress.org/support/topic/jetpack-carousel-size/#post-9809572) if it'd be possible to set up Carousel so to display elements such as title and meta description on the screen without having the users scroll down to see options such as “view full size image”, the full comment box etc.
I see another user [asked this a while ago too on the forum](https://wordpress.org/support/topic/jetpack-carousel-image-size/). 

Not sure if it's doable/possible technically speaking, or relevant module-wise, but I thought it was worth reporting this :)

**Comment by annatly2** [comment] 2017-12-28 23:19
This sounds like a great idea. I hope I can help in the development of a carousel for Jetpack. I know there are a couple of HTML, CSS, and JS libraries that have carousels that are easy to use, just not sure how compatible they are with Wordpress.

**Comment by mhk1058** [comment] 2019-08-14 10:54
This is still a reproducible issue. The metedata is only half visible in the JetPack lightbox regardless of screen or resolution. It's also not easy to see any way to scroll down to see the rest. The only way it is possible is by clicking the word 'comment' above the EXIF data.
![jetpack lightbox exif](https://user-images.githubusercontent.com/54103861/63015976-4a21bc80-be8a-11e9-80c5-7555c956d2ec.JPG)

**Comment by coviller** [comment] 2020-04-27 16:05
As an alternative way to solve this: instead of resizing the carousel, could a scroll bar be integrated into it? Right now I can only scroll down by clicking and down-dragging, or if my pointer is over an image I can use the mousewheel to scroll. 

A simple scroll-bar would make this gallery a solution for me, but because there's no way to scroll down I'll need to find a different carousel plugin that enables users to access images and their descriptions.

I'm surprised this issue is not a higher priority. Comments, image details, and some meta data are included as a feature, and yet these features are barely accessible because of this sizing/scrolling UI issue.

**Comment by mhk1058** [comment] 2020-04-27 16:40
Agrre

> 
> 
> As an alternative way to solve this: instead of resizing the carousel, could a scroll bar be integrated into it? Right now I can only scroll down by clicking and down-dragging, or if my pointer is over an image I can use the mousewheel to scroll.
> 
> A simple scroll-bar would make this gallery a solution for me, but because there's no way to scroll down I'll need to find a different carousel plugin that enables users to access images and their descriptions.
> 
> I'm surprised this issue is not a higher priority. Comments, image details, and some meta data are included as a feature, and yet these features are barely accessible because of this sizing/scrolling UI issue.

Totally agree, been an issue for years. Such a good, simple lightbox spoiled by what seems to be an easily sortable issue.

**Comment by apeatling** [comment] 2021-06-22 17:37
This will be addressed in https://github.com/Automattic/jetpack/pull/20139

**Closed** 2021-06-29 19:11 UTC
Labels: Carousel, [Pri] Low, [Status] Proposal, [Type] Enhancement
