### ISSUE TITLE
Comments: iframe is initially too large

### ISSUE THREAD

**Issue by WillJW** [Automattic/jetpack#2841] opened 2015-10-13 11:12 UTC
Summary of the issue: The Jetpack Comments widget sets too much height on the iframe when it's first loaded. Without guest commenting enabled, it only needs to allow 58px height, but allows 315px, resulting in lots of unnecessary whitespace.

Screenshots:

The initial load of the comment form, with the iframe's `<html>` element highlighted:
![image](https://cloud.githubusercontent.com/assets/1878977/10453343/45092f40-71a3-11e5-8af5-3717b1e7cd2f.png)

The widget's code, where the iframe height is being set. See: https://github.com/Automattic/jetpack/blob/master/modules/comments/comments.php#L262
![image](https://cloud.githubusercontent.com/assets/1878977/10453372/65ffcd80-71a3-11e5-8503-86a957576d6c.png)

**Comment by jeherve** [comment] 2015-10-13 18:51
I can't seem to reproduce on my end. Could you post your site URL here, so I can have a look?

If you want it to remain private, you can also contact us via this contact form:
http://jetpack.me/contact-support/

**Comment by WillJW** [comment] 2015-10-14 13:48
No problem @jeherve, there's a live example here: http://readliverpoolfc.com/2015/10/14/klopps-right-hand-man-arrives-liverpool/

**Comment by jeherve** [comment] 2015-10-14 17:56
Thanks. I can see the problem on your site, but can't reproduce on my own sites.

Do you have a copy of that site on a local test environment, where you could try switching to another theme and let me know if the problem persists?

**Comment by WillJW** [comment] 2015-10-14 18:14
@jeherve I've just enabled Jetpack Comments on my staging site, and it's fine. The only major difference between the two is that the production site has ads. So I've enabled ad-blocker on the production site, and it's fine! Looks like one of the ad scripts is interrupting it. Do you have any clues about this, or shall I delve deeper myself?

**Comment by jeherve** [comment] 2015-10-14 18:37
It might be worth removing each ad, one at a time, until you narrow things down to the one ad that seems to cause the problem.

**Comment by WillJW** [comment] 2015-10-14 18:39
Absolutely, I'll try that. Thanks for your help.

**Comment by mahangu** [comment] 2016-02-09 05:29
A user reported this in #2531482-t, and I'm able to reproduce it on my test site using Twenty Fifteen/Sixteen.

We set the initial height of the `jetpack_remote_comment` `<iframe>` here - 

https://github.com/Automattic/jetpack/blob/c447170a842712494948736b54a8f5d0525ba022/modules/comments/comments.php#L286

And then update it here, based on JSON data we receive from WordPress.com -

https://github.com/Automattic/jetpack/blob/c447170a842712494948736b54a8f5d0525ba022/modules/comments/comments.php#L384

On Firefox 44.0/Mac, the `<iframe>` correctly loads at 315px when logged in, but the JS does not update it -

![screen shot 2016-02-09 at 10 33 12 am](https://cloud.githubusercontent.com/assets/10125810/12908066/dca85b96-cf18-11e5-822b-0eacae924306.png)


When not logged in, it loads at `430px`, and the JS correctly updates the the height to `55px` -

![screen shot 2016-02-09 at 10 33 48 am](https://cloud.githubusercontent.com/assets/10125810/12908070/f69ce9b8-cf18-11e5-936a-cb1ad1cfe9b7.png)

On Chrome 48.0.2564.103/Mac, the issue persists whether you're logged in or not. Logged out loads at `430px`, and logged in at `315px`, but the JS does not set it to `55px` in either case.

I cannot replicate this on Safari 9.0.3/Mac at all. The JS correctly resizes the `<iframe>` whether logged in or not.

Will continue testing and update the ticket with anything else I find.

**Comment by jeherve** [comment] 2016-02-17 12:14
Also reported here:
https://wordpress.org/support/topic/comments-box-has-set-height-and-no-scroll?replies=1&view=all

**Comment by jeherve** [comment] 2016-02-25 13:34
Also reported here:
https://wordpress.org/support/topic/huge-white-space-underneath-comment-section-in-chrome?replies=2&view=all

**Comment by cherrybombsoftware** [comment] 2016-03-07 23:46
Also experiencing this. 

At [Line 389](https://github.com/Automattic/jetpack/blob/c447170a842712494948736b54a8f5d0525ba022/modules/comments/comments.php#L389):
 
`if ( <?php echo json_encode( esc_url_raw( $url_origin ) ); ?> !== event.origin ) {
     return;
}`

And [Line 316](https://github.com/Automattic/jetpack/blob/c447170a842712494948736b54a8f5d0525ba022/modules/comments/comments.php#L316) has:

`$url_origin = set_url_scheme( 'http://jetpack.wordpress.com' );`

In my case `$url_origin` is correctly set to "http://jetpack.wordpress.com". (I'm not on SSL.)

However `event.origin` gets set to "https://jetpack.wordpress.com/". Consequently the URLs don't match and the JS that adjusts the height is not run.

Why would Jetpack be requesting its AJAX content over SSL when a site its installed on isn't running under SSL?

**Comment by kraftbj** [comment] 2016-03-08 16:41
@cherrybombsoftware That'll be updated in 3.9.3. jetpack.wordpress.com always redirects to https://jetpack.wordpress.com now, so we're going to forego seeing the scheme and always use https.

**Comment by Alan-FGR** [comment] 2016-07-01 03:43
I'm also experiencing this problem, it seems related to caching somehow... the first time I've accessed it on both on Firefox and Vivaldi (Chromium based) that ugly spacing appeared, and when I open it on a private window it stills happens on both browsers, but it goes away after the first access for the whole private session. On Firefox there's another way to always reproduce the problem: middle-click the link to open in a new tab and let that tab fully load, only switch to it after it's loaded: that problem always happens.
My website uses my own child theme based on the popular Zerif theme.
I've tried to apply some tricks with css styling but couldn't solve that issue, only with a javascript but it was breaking the other functionality (expand, etc.) so I'm living with that problem :disappointed:.
Here's a link: http://alangamedev.com/packing-and-unpacking-bits-faster-than-bitconverter/

**Comment by jeherve** [comment] 2017-09-25 13:48
Also reported here:
https://wordpress.org/support/topic/jetpack-comments-huge-white-space/#post-9522203

**Comment by richardmtl** [comment] 2017-11-13 18:53
Even though this issue had a merged fix ( #7831 ) it was never actually closed; good thing, too, but I have another case with Jetpack 5.5:

http://www.psmtickling.com/blog/psm-stands-with-orlando/

Reported here: https://wordpress.org/support/topic/comment-area-size-height/page/2/#post-9676230

So I think this issue still needs a fix.

**Comment by jeherve** [comment] 2017-11-13 21:39
>  I have another case with Jetpack 5.5:

Does this happen with one of the default themes as well?

**Comment by tycooko** [comment] 2017-11-14 06:11
It does; I've just tried to switch my site to one of the default themes. 

The issue seems pretty common on Firefox.

**Comment by dwisetiyadi** [comment] 2017-11-14 06:22
The problem is here:

File : wp-content/plugins/jetpack/modules/comments/comments.php
Line number 286

change from this:
$height           = $params['comment_registration'] || is_user_logged_in() ? '315' : '430'; // Iframe can be shorter if we're not allowing guest commenting

to this:
$height           = $params['comment_registration'] || is_user_logged_in() ? '60' : '430'; // Iframe can be shorter if we're not allowing guest commenting

But this is not total solution, if we update jetpack, the white space height will be back.

**Comment by predictedblog** [comment] 2018-10-22 15:57
I experience the same issue and the solution given by dwisetiyadi dose not work for me. 

I even tried to hardcode the height with $height = '60'; or directly changing the iframe code to 
... height: <?php //echo $height; ?>60px; ...

The site seems to simply ignore the code change and keeps presenting me 570px (and yes I checked if FTP upload worked and cleared my cache). 

![bildschirmfoto 2018-10-22 um 17 50 42](https://user-images.githubusercontent.com/44035142/47302960-12a80200-d623-11e8-805f-5a572074abba.jpg)

Why is that?

The Number 570px is especially strange because it's nowhere in the whole comments.php file.

Here is the site: https://predicted.blog/multiprocessing-for-kids/

Thanks for your help!

**Comment by umeshnevase** [comment] 2018-11-27 12:40
The issue us still persist. I can see large gap below the response box and we cannot edit the plugin.

**Comment by pawelpotoniec** [comment] 2019-04-11 12:47
I confirm it also

**Comment by mzakariya** [comment] 2019-08-07 16:57
Reported in #2255408-zen, complete with a screenshot of how it looks on the user's site.

**Comment by kclarke10** [comment] 2019-12-06 03:12
still got this issue as described above...... on a native amp site.

**Comment by tiffanybridge** [comment] 2019-12-27 19:48
Confirming this issue on a site we're working on.

**Comment by emilylaguna** [comment] 2020-01-21 21:58
Also reported here: #2649702-zen

**Comment by LfournierKHS** [comment] 2020-06-04 16:56
Confirming this issue still exists on one of my sites.

**Comment by arunsathiya** [comment] 2020-06-11 03:28
This is still an issue. I can reproduce consistently on any WordPress website using Twenty Twenty theme.

**Comment by coder-karen** [comment] 2020-12-29 08:47
Also reported here: https://wordpress.org/support/topic/issue-with-amp-4/

**Comment by user746655** [comment] 2021-04-27 02:02
So this is a 6 year old problem with a plugin that is installed on millions of websites. really? I found this post as I'm having the same issue. So what's the solution? Disable and uninstall Jetpack or can I just disable Jetpack from handling the comments section?

**Comment by jeherve** [comment] 2021-04-27 08:45
> can I just disable Jetpack from handling the comments section?

That's indeed an option. You can disable Jetpack's custom comment form by going to Jetpack > Settings > Discussion.

**Comment by jeherve** [comment] 2022-06-14 18:55
Also reported in 5297469-zen

**Comment by jeherve** [comment] 2024-12-17 18:55
I believe this is now fixed with the last round of improvements to the Comments feature. Closing.

**Closed by jeherve** 2024-12-17 18:55 UTC
Labels: [Type] Bug, [Feature] Comments, [Pri] Normal, Customer Report
