### ISSUE TITLE
Accessing any jetpack admin panel breaks is broken completely and throws JS errors

### ISSUE THREAD

**Issue by gkweb** [Automattic/jetpack#15757] opened 2020-05-12 05:49 UTC
#### Steps to reproduce the issue

1. Go to `jetpack` in wp-admin
2. Click on `/wp-admin/admin.php?page=jetpack#/performance`
3. Error thrown

#### What I expected
Admin settings panel to work

#### What happened instead
Accessing any jetpack admin panel is broken completely and throws JS errors.

**Screenshots**

<img width="1883" alt="Screen Shot 2020-05-12 at 3 43 39 pm" src="https://user-images.githubusercontent.com/1525923/81643021-0b944f00-9468-11ea-8a5d-aee0405ae0c2.png">

**Comment by jeherve** [comment] 2020-05-12 06:42
Could you try to deactivate every other plugin on your site, one at a time, and let us know if you find a conflicting plugin?

Thank you.

**Comment by vladolaru** [comment] 2020-05-13 07:36
The same here.

**Comment by jeherve** [comment] 2020-05-13 07:37
@vladolaru Could you try what I suggested above, and let me know what you find?

Thanks!

**Comment by vladolaru** [comment] 2020-05-13 07:40
Unfortunately I can't do that. But I've disconnected from WordPress.com via the debug page, reconnected, and now the problem is gone.

**Comment by vladolaru** [comment] 2020-05-13 07:42
Although I do get some JS errors when navigating around. But things seem to be working
![Screenshot 2020-05-13 at 10 41 30](https://user-images.githubusercontent.com/8830539/81784996-641a2980-9506-11ea-9601-975d746e1420.png)

**Comment by jeherve** [comment] 2020-05-13 07:50
Do you think you could add `define( 'SCRIPT_DEBUG', true );` to your site's `wp-config.php` file, and then check those JavaScript errors again? It may give us more info about what exact files the error is happening in.

Thank you!

@gkweb Could you try to disconnect your site from WordPress.com as @vladolaru suggested above? You can do so via this page:
`yoursite.com/wp-admin/admin.php?page=jetpack-debugger`

**Comment by vladolaru** [comment] 2020-05-13 08:33
Ok @jeherve. I activated SCRIPT_DEBUG and now many things popped up.

Warnings (tens of them) related to `wp-content/plugins/jetpack/_inc/build/admin.js?ver=8.5`
![Screenshot 2020-05-13 at 11 29 32](https://user-images.githubusercontent.com/8830539/81789817-2e2c7380-950d-11ea-8af1-2772bc6d0a19.png)

But I realized that the `Syntax error, unrecognized expression: #/dashboard` error is not related to Jetpack, but another plugin.

**Comment by jeherve** [comment] 2020-05-13 08:53
Thanks for the extra details. I logged the Jetpack warnings in #15773.

Could you let the other plugin's author know about those errors? Could you also let me know what plugin that was? It may be helpful on our end if other Jetpack site owners reach out to us with similar issues. 

Thank you!

**Comment by vladolaru** [comment] 2020-05-18 13:55
@jeherve It's the ActiveWoo plugin for integrating WooCommerce and ActiveCampaign. It refers specifically to the izimodal.js library (version 1.5.1).

**Comment by jeherve** [comment] 2020-05-19 13:39
Thank you! I'll close this issue now that the Jetpack issue is tracked in #15773.

**Closed by jeherve** 2020-05-19 13:39 UTC
Labels: Admin Page, [Status] Needs Author Reply
