### ISSUE TITLE
Infinite Scroll: posts_per_page is not respected when passed through infinite_scroll_query_args

### ISSUE THREAD

**Issue by yuleugim** [Automattic/jetpack#9457] opened 2018-05-01 15:49 UTC
#### Steps to reproduce the issue

* Jetpack 6.0
* Replace `posts_per_page` with a value different from the one in set in wp admin

```
add_filter( 'infinite_scroll_query_args', function ( $args ) {
  $args['posts_per_page'] = 3; // insert any number
  return $args;
} );
```

#### What I expected

Posts loaded through infinite scroll will use the passed `posts_per_page`.

#### What happened instead

Posts loaded through infinite scroll will continue to use the `posts_per_page` set in wp admin.

I noticed that the `$query_args` from the filter are passed separately after instantiation of `WP_Query`.

https://github.com/Automattic/jetpack/blob/dd315a50fdad701e98d96f513f2a6e314234a9bb/modules/infinite-scroll/infinity.php#L1243-L1245

Just passing `$query_args` to the `WP_Query` object seems to resolve the issue for me.

```
$GLOBALS['wp_the_query'] = $GLOBALS['wp_query'] = $infinite_scroll_query = new WP_Query( $query_args );

// No longer needed
// $infinite_scroll_query->query( $query_args );
```

**Comment by jeherve** [comment] 2018-05-02 10:10
This is most likely a duplicate of #9327. Could you try to update to Jetpack 6.1, and make the changes outlined here:
https://github.com/Automattic/jetpack/issues/9327#issuecomment-382683116

That should solve your issue.

**Closed by jeherve** 2018-05-02 10:10 UTC
Labels: Infinite Scroll, [Type] Duplicate

**Comment by yuleugim** [comment] 2018-05-02 14:53
@jeherve Thanks! This is what I ended up with.

```
add_action( 'pre_get_posts', function ( $query ) {
  if ( $query->is_main_query() && ! is_admin() ) {
    if ( $query->is_paged ) {
      $query->set( 'posts_per_page', 3 );
    }
  }
}, 11 );
```
