### ISSUE TITLE
Sharing: Separate options for Front Page, Archive Pages, and Search Results

### ISSUE THREAD

**Issue by bhubbard** [Automattic/jetpack#3678] opened 2016-04-18 00:12 UTC
Currently right now there is one checkbox to enable sharing for Front Page, Archive Pages, and Search Results. These should be separated out into three different checkboxes. 

Some sites want the sharing buttons on archive pages, but not the front-page or search pages, etc.

**Comment by jeherve** [comment] 2016-04-18 07:51
Closing as duplicate of #2749

**Closed by jeherve** 2016-04-18 07:51 UTC
