### ISSUE TITLE
Adding loading=lazy to the Spotify player iframe

### ISSUE THREAD

**Issue by asafm7** [Automattic/jetpack#16454] opened 2020-07-10 13:49 UTC
Hi,

I suggest adding "loading=lazy" to the Spotify player iframe for better page performance.

https://web.dev/native-lazy-loading/

Thanks,
Asaf

**Comment by avlisesac** [comment] 2020-07-24 20:29
I will work on this one

**Comment by avlisesac** [comment] 2020-07-24 20:45
pull request created: https://github.com/Automattic/jetpack/pull/16574

**Comment by amustaque97** [comment] 2021-08-05 15:26
Hey @jeherve , Is this still a valid issue? I want to work on this.

I don't think we need to do any changes. Because I can see `loading=lazy` in the iframe

![Screenshot 2021-08-05 20:54:24](https://user-images.githubusercontent.com/21127788/128376677-a51f1874-b2d1-4cf9-9747-e91b453851df.png)

so we don't require any changes and we can close this issue.

**Comment by sdixon194** [comment] 2021-08-09 17:59
Hmm, doing some testing and it looks like it's currently not lazy-loaded still.  

![Screen Shot on 2021-08-09 at 13:58:29](https://user-images.githubusercontent.com/33553323/128751983-db85a078-943a-4a05-a58a-51a2946b185a.png)

I see you submitted a PR for a fix (thanks!) - were you able to reproduce the issue of it not being lazy loaded?

**Comment by amustaque97** [comment] 2021-08-09 18:58
@sdixon194 , Later I was able to reproduce this issue. I have already submitted my PR. Here is my PR link:
https://github.com/Automattic/jetpack/pull/20594

**Closed** 2021-08-23 19:39 UTC
Labels: [Type] Enhancement, Shortcodes / Embeds, [Type] Good First Bug, Performance, [Pri] Low, Good For Community
