### ISSUE TITLE
CRM does tons of duplicate queries

### ISSUE THREAD

**Issue by devicenull** [Automattic/jetpack#38623] opened 2024-07-30 17:34 UTC
### Impacted plugin

CRM

### Quick summary

A fresh install of the CRM plugin does a ton of duplicate queries, including 69 duplicate `SELECT * FROM wp_zbs_settings WHERE zbsset_key = 'secondaddresslabel' ORDER BY ID DESC LIMIT 0,1` and 23 copies of `SELECT * FROM wp_zbs_settings WHERE zbsset_key = 'coororg' ORDER BY ID DESC LIMIT 0,1`

### Steps to reproduce

1. Install Jetpack CRM plugin
2. Run through the normal setup process of configuring a business name, etc
3. Load the blog frontpage and check out the queries debug tab

Here's a query list from my test blog - [crm_queries.txt](https://github.com/user-attachments/files/16431509/crm_queries.txt)

### A clear and concise description of what you expected to happen.

Queries for individual pieces of metadata should happen at most once (and should probably be cached between requests)

### What actually happened

Many duplicate queries :(

I'm not 100% sure on impact, but I can't really figure out how this wouldn't be hitting every user.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

My test blog is at https://braktest9.wpcomstaging.com/ if you want to see this

**Comment by coder-karen** [comment] 2024-07-31 07:38
Thanks for the report @devicenull ! I am going to close this one though as there is another issue in the CRM internal repository here too: https://github.com/Automattic/zero-bs-crm/issues/3449. 
Since that was transferred over from here in March, that'll be why the issue is not searchable within the Jetpack repository. But closing this particular issue instead of moving it means it will be searchable now, with reference to the earlier issue.

**Closed as completed by coder-karen** 2024-07-31 07:38 UTC
Labels: Bug, [Pri] High, [Platform] Atomic, Needs triage, [Plugin] CRM, [Status] Priority Review Triggered
