### ISSUE TITLE
Carousel: doesn't work with the latest Chrome update

### ISSUE THREAD

**Issue by ricjcs** [Automattic/jetpack#34653] opened 2023-12-14 19:33 UTC
### Impacted plugin

Jetpack

### Quick summary

Today I noticed that the carousel wasn't working. When clicking on an image in a gallery, the carousel opens but the buttons don't work. It's not possible to go to the next or previous image, it's not possible to press the "i" button or close the carousel using the "x" button.

I cleared the cache, deactivated some plugins but the problem persisted. I tested on Chrome (desktop and mobile) and Edge (desktop), the problem continued. I tested on Firefox (desktop), the problem didn't happen.

I tested it on sites with a classic theme and a block theme, the behavior was the same.

I thought the problem arose after the last update of Chrome-based browsers.

### Steps to reproduce

1. Have the carousel option activated in Jetpack
2. Create a post or page with a gallery
3. Open an image from the gallery
4. Notice that the carousel buttons don't work

### A clear and concise description of what you expected to happen.

I was hoping the buttons would work, that I could go to the next image and close the carousel.

### What actually happened

Carousel buttons don't work.

### Impact

All

### Available workarounds?

Yes, easy to implement

**Comment by jeherve** [comment] 2023-12-15 12:08
Closing as duplicate of #34657.

**Closed as completed by jeherve** 2023-12-15 12:08 UTC
Labels: Bug, [Closed] Duplicate, [Feature] Carousel, [Pri] Normal, [Plugin] Jetpack, Triaged
