### ISSUE TITLE
Calypsoify: fix layout of all plugin notices

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#10526] opened 2018-11-02 16:05 UTC
Here are the notices added by the WordFence plugin.

> Blue bar on left side is too short

![plugins-e280b9-randomtestsitebrbrr-mystagingwebsite-com-at-pressable-e28094-wordpress-2018-11-02-16-51-121](https://user-images.githubusercontent.com/426388/47926664-64714780-dec1-11e8-9565-067b516325d6.png)

> WordFence notice located higher than other notices, and it is a bit “off”

<img width="387" alt="msedge-win10-2018-11-02-16-54-04" src="https://user-images.githubusercontent.com/426388/47926684-7357fa00-dec1-11e8-8425-7258b085e012.png">

> WordFence notice on Jetpack settings page

<img width="1189" alt="jetpack randomtestsitebrbrr mystagingwebsite com at pressable wordpress 2018-11-02 18-13-56" src="https://user-images.githubusercontent.com/5654161/47927148-22e59a00-decb-11e8-94a6-b0bfdee79434.png">

**Comment by georgestephanis** [comment] 2018-12-04 18:59
For comparison, here is the same notice with and without calypsoify:

<img width="1357" alt="screen shot 2018-12-04 at 1 50 50 pm" src="https://user-images.githubusercontent.com/941023/49465945-cc6ec280-f7cc-11e8-9c53-8dd0717aabf7.png">

<img width="1357" alt="screen shot 2018-12-04 at 1 54 58 pm" src="https://user-images.githubusercontent.com/941023/49465946-cc6ec280-f7cc-11e8-8a34-92f90edaecd3.png">

It looks like the blue bar is as intended.

**Comment by georgestephanis** [comment] 2018-12-04 19:40
The "Notice Higher Than Others" bit --

<img width="1357" alt="screen shot 2018-12-04 at 2 38 35 pm" src="https://user-images.githubusercontent.com/941023/49468280-7866dc80-f7d2-11e8-8f81-538f57fd751a.png">

<img width="1357" alt="screen shot 2018-12-04 at 2 38 53 pm" src="https://user-images.githubusercontent.com/941023/49468281-7866dc80-f7d2-11e8-9457-cbba8e077cd8.png">

I can see maybe trying to tweak some padding to align it, but I think the messy placement is the plugin developer's fault as it's consistent with and without calypsoify.

**Comment by georgestephanis** [comment] 2018-12-04 19:51
Unless there's any strong objections, I'm going to close this out as I don't think it's necessarily our job to handle ever edge case a plugin developer does.

**Closed by georgestephanis** 2018-12-04 19:51 UTC
Labels: Calypsoify, [Type] Bug
