### ISSUE TITLE
Video Block: Update Post When Enabling/Disabling the "Allow Download" option

### ISSUE THREAD

**Issue by alinclamba** [Automattic/jetpack#24892] opened 2022-06-29 16:10 UTC
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Add a Video block to a post. 
2. Enable any option you want from the `Video Settings` section, and you will notice the `Update` button becomes active each time. 
3. Instead, when enabling/disabling the `Allow download` option, the `Update` button stays _inactive._  

https://user-images.githubusercontent.com/6790170/176481399-0a1772eb-7ecf-4990-9d61-c6038f5f7ea6.mp4

↳ Video link: https://d.pr/v/UqjPAL

### A clear and concise description of what you expected to happen.

I expect to be able to update the post after enabling or disabling the `Allow download` option. 

### What actually happened

Nothing happens, as mentioned above, the `Update` button is inactive, even if the post content is refreshed. 

### Reproducibility

Once

### Operating System

macOS

### OS Version

Monterey 12.3.1

### Browser

Chrome/Chromium, Firefox, Safari

### Browser Version(s)

Chrome 103.0.5060.53, Firefox 101.0.1, Safari 15.4

**Comment by coder-karen** [comment] 2022-06-30 06:54
Related: #24132 

From my testing the 'Allow download' toggle does work, but the issue is that the update button isn't clickable which makes it seem that the option isn't being enabled. On the site in question, when you enable downloads do you see the option showing on the video itself?

The download video button becomes visible when clicking the share icon in the top right of the video, and should look like this:

<img width="632" alt="Screenshot 2022-06-30 at 07 52 48" src="https://user-images.githubusercontent.com/16754605/176611907-6cb003b3-0a8b-4542-8cad-fe438f752203.png">

**Comment by alinclamba** [comment] 2022-06-30 15:08
@coder-karen, you are right: the "Allow download" button "works" even if I don't update the post after toggling the option.

**Comment by coder-karen** [comment] 2022-06-30 16:20
Thanks for confirming that! I'll close this issue in favor of the other (although it's 'expected', it's still confusing).

**Closed as completed by coder-karen** 2022-06-30 16:20 UTC
Labels: Bug, [Feature] VideoPress, [Plugin] Jetpack, [Block] VideoPress
