### ISSUE TITLE
Tiled Mosaic Gallery Displays in Single Line Based on Image Order

### ISSUE THREAD

**Issue by jesscga** [Automattic/jetpack#9553] opened 2018-05-14 20:28 UTC
#### Steps to reproduce the issue:
Add gallery to page. Use Tiled Mosaic type.

#### What I expected
Gallery displays on front-end in Tiled Mosaic as it appears on Calypso page

#### What happened instead
Calypso page shows Tiled Mosaic, while front-end page shows small images in single line.

Changing image order seems to work but there's no logic as to what image order created the expected mosaic.

Reported on 1159301-zen

**Comment by jeherve** [comment] 2018-05-15 20:34
> while front-end page shows small images in single line.

I can't seem to reproduce on my end. Could you walk me through the steps you followed to get this error? Does this happen on any site? Does this happen on Jetpack sites, on WordPress.com sites, or on both?

Thank you!

**Comment by jesscga** [comment] 2018-06-02 23:41
Unfortunately it seems to happen with a random image order and is hard to reproduce -- I'll see if I can run across it on a test site and report back.

The initial report was on a WordPress.com site, but the site owner fixed it by changing image order in the gallery.

**Comment by jeherve** [comment] 2018-09-03 19:52
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.

**Comment by jesscga** [comment] 2018-12-14 22:16
It looks like we have another case of this on 1645884-zen - reopening.

**Comment by jesscga** [comment] 2018-12-15 13:37
Also mentioned in p1498159199152300-slack-C029FM1EH

**Comment by jeherve** [comment] 2018-12-17 08:21
1645884-zen adds more context:

- This happens on a WordPress.com site.
- This is about the old Tiled Galleries (pre-Gutenberg)
- This is about differences between the preview in the old Calypso editor and the actual look of the gallery on the front end of the site.
- **Both galleries (in the front end and in the editor) actually work well, but they don't look the same.**

That is to be expected I am afraid. Tiled Galleries's format is impacted by different things:

- the number of images in a gallery
- the dimensions and orientation of each image.
- **the width of the container around the images**
- the `$content_width` value provided by the theme.
- the type of gallery picked in the options.

As a result, the preview can sometimes look a bit different as the images have to be reorganized in the Calypso editor to match a different container.

The Calypso editor could probably be improved to try to look as similar as possible to the actual front end of the site, but I do not think this will happen now that we are moving towards a different editor (Gutenberg) and a different gallery format (the Tiled Galleries block).

I will consequently close this issue.

**Closed by jeherve** 2018-12-17 08:21 UTC
Labels: Tiled Galleries, [Status] Invalid, [Type] Bug
