### ISSUE TITLE
Slideshow Block: Fade/Slide effect alters block background

### ISSUE THREAD

**Issue by brbrr** [Automattic/jetpack#15640] opened 2020-05-01 08:23 UTC
#### Steps to reproduce the issue

1. Start a new post and add a slideshow block
2. Enable autoplay
3. Change sliding effect
4. Note that background got changed

#### What I expected

Block background stays the same on matter what transition effect is used

#### What happened instead

Different backgrounds for different transition effects

**Screenshots**
Slide effect
<img width="300" alt="slide" src="https://user-images.githubusercontent.com/5654161/80792686-c33e7c80-8b9d-11ea-9734-bb502782dc69.png">

Fade effect
<img width="300" alt="fade" src="https://user-images.githubusercontent.com/5654161/80792691-c5a0d680-8b9d-11ea-8a8c-a4fef331c081.png">

**Comment by jeherve** [comment] 2021-01-11 11:35
Closing as duplicate of #12962.

**Closed by jeherve** 2021-01-11 11:35 UTC
Labels: [Block] Slideshow, [Pri] Normal, [Type] Bug
