### ISSUE TITLE
Enhancement: Jetpack Social - reset sharing settings when using WooCommerce 'copy to a new draft'

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/jetpack#25978] opened 2022-09-01 11:33 UTC
### Impacted plugin

Jetpack, Social

### What

When copying a Woo product to a new draft, the auto-share settings should be reset.

### How

After you publish a WooCommerce product, the publicize settings are no longer active, as expected:

![image](https://user-images.githubusercontent.com/1990037/187903874-9dbfdd7b-f786-4eb3-b4d7-ff19b5d713f2.png)

However, if you then use the 'copy to new draft' link, the publicize settings are also inactive on the new draft.

Since you are creating a new product, the publicize settings should be reset so that the new product can also be auto-shared.

**Comment by jeherve** [comment] 2023-03-30 11:08
Closing as duplicate of #6376.

**Closed as completed by jeherve** 2023-03-30 11:08 UTC
Labels: [Closed] Duplicate, Enhancement, [Feature] Publicize, [Plugin] Jetpack, [Plugin] Social
