### ISSUE TITLE
Youtube shortcode stopped working after upgrading to WordPress 4.4

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#3121] opened 2015-12-09 17:08 UTC
Several reports in the forums:

https://wordpress.org/support/topic/youtube-shortcode-no-longer-working-after-updating-to-44?replies=10#post-7755539
https://wordpress.org/support/topic/youtube-shortcode-stopped-working-with-wp-44?replies=5

I confirmed with this shortcode:

`[youtube=https://www.youtube.com/watch?v=zbn5_3yf6VQ&w=660]`

**Comment by kraftbj** [comment] 2015-12-09 17:38
Caused by https://core.trac.wordpress.org/changeset/34747 per `git bisect`

Looks like Core no longer trips on the `[shortcode=something]` style, which it still did in 4.3.1.

**Comment by kraftbj** [comment] 2015-12-09 18:00
I can't tell if 34747's breaking of the format was intentional or not per the Shortcode Roadmap. Opened https://core.trac.wordpress.org/ticket/34939 to get a clarification/report it.

**Comment by pilarmonge80** [comment] 2015-12-09 22:32
Hello,

I can't see any video from my blog.

I only see de the shortcode for example [youtube=https://youtu.be/IGrqiSYc1oM&w=600&h=440] in my post http://postresoriginales.com/pastel-de-naranja/ and i have more than 200 pages with this shortcode for YouTube

![shortcode](https://cloud.githubusercontent.com/assets/16228422/11700722/c0eba138-9ecb-11e5-8ca5-de76307cef90.png)

Also I inserted your code [youtube=https://www.youtube.com/watch?v=zbn5_3yf6VQ&w=660] and i don't see anything 
![shortcode 02](https://cloud.githubusercontent.com/assets/16228422/11700933/04e1b14c-9ecd-11e5-95c8-2e1e9f0e7102.png)

Thanks

**Comment by kraftbj** [comment] 2015-12-09 22:41
Hi @pilarmonge80 - your issue is the one being discussed in this ticket. WordPress 4.4 stopped processing shortcodes built like that (e.g. `[youtube=http://something]`), though unintentionally. We're working toward determining best path forward.

For an immediate fix, you can update to `[youtube url=http.....]` instead. If you feel able to do so, inclusive of creating and restoring backups, you can search and replace for `[youtube=` to `[youtube url=` in your db (using a plugin, or something else). Again, please don't do this unless you are able to recover if the search and replace breaks something.

**Comment by pilarmonge80** [comment] 2015-12-09 22:52
Thanks @kraftbj I'll wait because I find myself unable to make that change :)

**Comment by kraftbj** [comment] 2015-12-10 02:41
While https://core.trac.wordpress.org/ticket/34939 is still in play, we should start preparing a PR to do an early filter on `the_content` to `str_replace` to a proper shortcode. I'm not sure we'll be able to help the further edge cases if anyone used a shortcode outside of `the_content` somehow.

Also noting the en.support docs need to be updated as they have this format all over the place. :)

**Comment by Musicuratum** [comment] 2015-12-10 06:10
Do you happen to know yet whether the Youtube shortcode will be reinstated in the same form -- and when? Likewise I have used it a great number of times on my website, and should very much prefer to avoid having to change all that code.

**Comment by kraftbj** [comment] 2015-12-10 06:21
@musicuratum - Details will be posted here as they're known. Long-term, it is probably best to not use this format (rather `[youtube url=` format or simply paste the URL directly in as it'll auto-embed without the need of a shortcode).

[Per my comment above](https://github.com/Automattic/jetpack/issues/3121#issuecomment-163467930), we'll likely have a shim to convert, on display, the `[youtube=` style to the standard format. Timeline TBD.

**Comment by Musicuratum** [comment] 2015-12-10 06:27
Of course I won't be using that shortcode again -- unless it's simply reinstated. For all the instances when I have used it, however, I'm waiting eagerly for your solution. All the more as it was the official Jetpack shortcode and as such abandoned without notice. (Given that I modify several of the parameters, embedding YT works best, I've found, with a shortcode, as opposed to simply including the URL on its own line.)

**Comment by kraftbj** [comment] 2015-12-10 06:31
@Musicuratum - It wasn't abandoned, as much as an unintended change upstream by WordPress led to it no longer being seen as a shortcode. We'll figure out something so you're not stuck. But, in any case, I would suggest using `[youtube url=http://example.com]` format over `[youtube=http://example.com]`.

**Comment by Musicuratum** [comment] 2015-12-10 06:35
For the moment I don't have any YT materials to embed, fortunately. Yes, when I do, I'll use that other shortcode. Do you happen to know when the documentation concerning it and its various possible parameters will be written?

**Comment by kraftbj** [comment] 2015-12-10 06:35
It's the same shortcode. Same exact behavior. https://en.support.wordpress.com/videos/youtube/

**Comment by Musicuratum** [comment] 2015-12-10 06:41
Very well, I see that that page has been updated -- earlier it provided the shortcode I've been using.

Please do let me know when the solution for dealing with the now deprecated one is ready.

**Comment by pilarmonge80** [comment] 2015-12-10 22:11
Thank you for being looking for a solution because I do not feel able to enter the code to put the patch :)

**Comment by darrenbrett** [comment] 2015-12-11 05:00
I assume it's known that this goes beyond just YouTube shortcode. I use the popular Starter theme in various places, and it's shortcode functions are also broken with 4.4.

**Comment by kraftbj** [comment] 2015-12-11 05:08
@darrenbrett - For the broader conversation, see https://core.trac.wordpress.org/changeset/34747 . This format is non-standard, though, so we're going to work toward not using them here on out.

**Comment by pilarmonge80** [comment] 2015-12-11 09:30
Sorry @kraftbj  but I do not hear . If you have already prepared a patch why not directly upload that file to modify it with FILEZILLA .
Or do we have to get into those files to write the new code.
Thanks :)

**Comment by jeherve** [comment] 2015-12-11 14:41
@pilarmonge80 The patch is available here:
https://github.com/Automattic/jetpack/pull/3127/files

If you don't feel comfortable editing PHP files yourself, I'd suggest joining [Jetpack's Beta group](http://jetpack.me/beta/) and installing the Beta plugin. You will then get to test the patch as soon as we release a Beta for the next version of Jetpack, 3.8.2. It should happen in the next few days.

**Comment by pilarmonge80** [comment] 2015-12-11 15:48
thanks @jeherve 

I've change the two files functions.compat.php and modules/shortcodes/youtube.php but now i don't see the videos again.

Have I change more codes??

**Comment by dereksmart** [comment] 2015-12-11 15:50
@pilarmonge80 on the front-end of your site, are you seeing the shortcode text or nothing at all?  

Could you please paste the exact shortcode you're using? Thanks!

**Comment by pilarmonge80** [comment] 2015-12-11 15:52
Hello @dereksmart 

I have this type of code in more than 200 pages in my blog
[youtube=https://youtu.be/IGrqiSYc1oM&w=600&h=440]

And I see this
![shortcode](https://cloud.githubusercontent.com/assets/16228422/11748232/975c1b88-a027-11e5-9def-fe780dbccb39.png)

**Comment by jeherve** [comment] 2015-12-11 15:56
@pilarmonge80 Could you try the following:

1. Go to the Plugins menu in your dashboard, deactivate Jetpack, and then delete it.
2. Go to Plugins > Add New > Upload, and upload and install this version of Jetpack:
http://i.wpne.ws/e3YB
3. Once activated, go to the Jetpack menu and connect Jetpack to your WordPress.com account again.

Let us know how it goes.

**Comment by dereksmart** [comment] 2015-12-11 15:57
It's worth noting that the link to https://youtu.be/IGrqiSYc1oM&w=600&h=440 is a 404, which is probably why it's not showing.  I tested it in WordPress 4.3.1 and no luck there either.

**Comment by dereksmart** [comment] 2015-12-11 15:57
When I remove the width and height arguments, it works ok

**Comment by dereksmart** [comment] 2015-12-11 16:11
I don't think the youtu.be urls work with parameters.  When I use [youtube=https://www.youtube.com/watch?v=IGrqiSYc1oM&w=600&h=440] it works ok

**Comment by pilarmonge80** [comment] 2015-12-11 16:12
@jeherve I've done the three steps and go on whatching only the code like [youtube=https://youtu.be/IGrqiSYc1oM&w=600&h=440]
Have I do something else?
Regards,


@dereksmart I wrote the shortcode for whatching the video. The last parameters are the width and height. Before the update of wordpress i could see the vide like this 
![shortcode 03](https://cloud.githubusercontent.com/assets/16228422/11748778/4059681a-a02a-11e5-8ef0-b97783627e30.png)

For whatching now the videos I have to add in the shortcode [youtube url=https://youtu.be/IGrqiSYc1oM&w=600&h=440] but the problem is that i have more than 200 pages.

Regards

**Comment by dereksmart** [comment] 2015-12-11 16:15
thanks @pilarmonge80 working up a patch to look for the shortened youtu.be urls

**Comment by pilarmonge80** [comment] 2015-12-11 16:17
thanks @dereksmart so i have to wait and i don't to change anything, don't I??

**Comment by dereksmart** [comment] 2015-12-11 16:25
yep we will have a patch ready today!

**Comment by pilarmonge80** [comment] 2015-12-11 16:26
Great!!! @dereksmart thanks a lot for being working so much :D

**Comment by darrenbrett** [comment] 2015-12-11 16:43
Just to clarify, will the patch cover the shortcodes issue in general, or just the YouTube issue specificaly?

**Comment by dereksmart** [comment] 2015-12-11 16:44
@darrenbrett I believe our youtube shortcode is the only one that we use the `[shortcodeName=]` syntax, so it's the only one we are aiming to fix for this release.

**Comment by dereksmart** [comment] 2015-12-11 16:55
@pilarmonge80.  If you update to the most recent version of this <a href="https://github.com/Automattic/jetpack/pull/3127/files">this patch</a> it should work ok now.

<a href="https://github.com/Automattic/jetpack/pull/3127/files#diff-4022100acca3ed34c622459b74c603f6R374">this line</a> is what changed from the last patch:

**Comment by pilarmonge80** [comment] 2015-12-11 17:03
Thank you very much @dereksmart and @jeherve I've change the line 

$content = preg_replace( '@\[youtube=(.*?youtu(be)?\.(com|be).+?)\]@', '[youtube $1]', $content );

and now everything is ok :)

Have a nice weekend

**Comment by dereksmart** [comment] 2015-12-11 17:11
you as well, thanks for testing :)

**Comment by darrenbrett** [comment] 2015-12-11 17:20
So just to clarify, re: the issues discussed here: https://core.trac.wordpress.org/changeset/34747, will it be up to individual people to update the PHP - or will there be some patching made available via WordPress at some point? Just trying to understand this in terms of the commitment to backwards compatibility as well. Thanks.

**Comment by dereksmart** [comment] 2015-12-11 17:23
I can't speak for the core team ATM, but afaik they have no plans to rollback that change and it will be up to theme/plugin devs to update their products to adhere to this change.  

https://core.trac.wordpress.org/ticket/34939 would be a good place to ask / follow for more info.

**Comment by darrenbrett** [comment] 2015-12-11 17:24
Okay, thanks.

**Comment by BigDave44** [comment] 2015-12-11 17:48
If it helps, I successfully changed 1,786 instances of [youtube= ...] to [youtube url= ...] on posts going back over 6 years, using the excellent "Search Regex" plugin - and it only took a few seconds.

**Closed** 2015-12-11 20:40 UTC
Labels: bug, in progress, Shortcodes

**Comment by darrenbrett** [comment] 2015-12-11 22:34
So, generally, if [shortcode=XXX] no longer works, what should be used in it's place?
