### ISSUE TITLE
videopress-uploader.js uses undefined function

### ISSUE THREAD

**Issue by leogermani** [Automattic/jetpack#25819] opened 2022-08-24 18:22 UTC
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Enable VideoPress module
2. Go to Media
3. Click Add new
4. Upload a video with an unsupported video format (e.g. mkv)
5. there will be no good error response

Another way of testing is trying to upload a video while connected to Jetpack only at a site level

### A clear and concise description of what you expected to happen.

I expected to have a proper error message

### What actually happened

No error message in the UI and a Error in the console:

error is not defined

The `error` function used there is not declared: https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/modules/videopress/js/videopress-uploader.js#L13

### Reproducibility

Consistent

### Severity

All

**Comment by phcp** [comment] 2024-11-08 15:01
Tested on atomic and jetpack-connected sites and couldn't reproduce it, so I'm closing this issue. I'm getting an error message (and no console errors), as you can see in the screenshot below:

<img src="https://github.com/user-attachments/assets/463950ad-be49-4b4f-9d3c-f8a1afc4dad7" width="400" />

**Closed as completed by phcp** 2024-11-08 15:01 UTC
Labels: Bug, [Feature] VideoPress, [Pri] Low, Triaged
