### ISSUE TITLE
Calendly: Block Height Too Large

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#20277] opened 2021-07-06 18:21 UTC
When someone embeds their Calendly link to embed all available appointment types, i.e https://calendly.com/[calendly-username], the height of the block doesn't adjust to the height of appointment types, which can leave a good deal of blank space: 

![Screen Shot on 2021-07-06 at 14:19:40](https://user-images.githubusercontent.com/33553323/124648404-378d4380-de65-11eb-8e4b-75fcfcbdf80b.png)

Ideally the height of the block would change based on the height of available appoints to prevent that.

**Comment by jeherve** [comment] 2021-07-07 07:20
Closing as duplicate of https://github.com/Automattic/jetpack/issues/14566

**Closed by jeherve** 2021-07-07 07:20 UTC
Labels: [Block] Calendly, [Type] Bug
