### ISSUE TITLE
Eventbrite Block: Default text color of modal button is too dark

### ISSUE THREAD

**Issue by creativecoder** [Automattic/jetpack#14506] opened 2020-01-29 01:55 UTC
#### Steps to reproduce the issue

1. Add an Eventbrite Block while editing a page or post
1. Select the "Button & Modal" embed type in the sidebar

#### What I expected

To be able to see the button text

#### What happened instead

On some themes, the button text defaults to being very dark

**Screenshots**

<img width="629" alt="Screen Shot 2020-01-28 at 19 54 56" src="https://user-images.githubusercontent.com/1699996/73321453-194efd00-4208-11ea-847f-ef3cd4367a0e.png">

**Comment by jeherve** [comment] 2020-01-29 11:00
👍 Twenty Nineteen is a good example of that.

**Comment by iamtakashi** [comment] 2020-01-29 12:56
If it's not going to be a big headache, adding a CSS class `wp-block-button` to the `div.wp-block-jetpack-eventbrite.is-modal-button` in the markup might be a quicker solution. Like...

<img width="573" alt="Screenshot 2020-01-29 at 12 39 53" src="https://user-images.githubusercontent.com/908665/73357625-adff3c80-4294-11ea-8253-ea4b6fa7e891.png">

That would make the pill shape button like other buttons in the template-first themes because they override the default button style with `.wp-block-button`:/ Ideally, this should be fixed in the themes, but I doubt that's going to happen as no one is actively working on the template-first themes at the moment. I think Calendly block does the same workaround. What do you think?

**Comment by Copons** [comment] 2020-01-29 13:33
I think the change proposed by @iamtakashi is not a workaround but the intended behaviour of `wp-block-button__link`.
As far as I can see in Core Guten, `wp-block-button__link` is the inner element inside a `wp-block-button`.
So, it's to be expected that it malfunctions when used "outside" `wp-block-button`.

E.g. this is how a normal Button block is rendered in the editor:
<img width="921" alt="Screenshot 2020-01-29 at 13 31 50" src="https://user-images.githubusercontent.com/2070010/73360952-e0606800-429b-11ea-83dd-ee617fde9fd5.png">

**Comment by creativecoder** [comment] 2020-01-29 20:05
Agreed, not adding the `wp-block-button` class was an oversight--that seems like the best solution to me because it emulates the Core button block (which was the idea in implementing to modal embed type for Eventbrite).

**Closed** 2020-01-31 21:55 UTC
Labels: [Block] Eventbrite, [Pri] High, [Type] Bug
