### ISSUE TITLE
CSS Concatenating: jetpack.css loads all styles, even if they've been manually dequeued

### ISSUE THREAD

**Issue by cferdinandi** [Automattic/jetpack#1258] opened 2014-11-04 22:31 UTC
As of this weekend, I'm now seeing `jetpack.css` loading on the front-end, even though the only feature I'm using in Markdown. This file contains CSS for all Jetpack features.

I'm currently overriding this behavior using this snippet in `functions.php`, but this feels like it may be a bug:

``` php
add_filter( 'jetpack_implode_frontend_css', '__return_false' );
```

More info: https://www.twirlingumbrellas.com/wordpress/remove-deregister-jetpack-contact-form-styles/

**Comment by jeherve** [comment] 2017-01-27 18:47
Also reported here:
https://wordpress.org/support/topic/too-much-css-loading/

**Comment by jeherve** [comment] 2017-09-08 13:20
Related suggestion:

> Concatenated jetpack.css should only include CSS for active modules

#7656

**Comment by jeherve** [comment] 2019-11-06 15:23
This was brought up again in #11123.

**Comment by cferdinandi** [comment] 2020-10-22 21:59
Just wanted to comment that it's been six years and I'm _still_ seeing this issue. 😔

**Comment by jeherve** [comment] 2020-10-23 06:26
Reopening this, as it is still a valid enhancement.

**Comment by adaminfinitum** [comment] 2020-10-26 02:00
I came across this thread after a google search led me to [issue #15734](https://github.com/Automattic/jetpack/issues/15734), which is closed because it's basically a duplicate of this issue.

I'm glad this is still open because it is a valid enhancement, what I am working on now to address it is [adding a filter to disable the concatenation](https://developer.jetpack.com/hooks/jetpack_implode_frontend_css/) and then using the "Asset CleanUp" plugin to disable the files I don't need and letting my caching plugin concatenate everything else into as few files as possible.

Hopefully others will find this approach helpful.

**Comment by jeherve** [comment] 2023-03-07 13:17
This was also brought up in [this post](https://felix-arntz.me/blog/rebuilding-my-website-using-a-block-theme/):

> The only feature of Jetpack that I use in the frontend of my site is the Subscribe block that you can see in my site footer. There’s no way that simple text input and button needs 21.5 KB of CSS.

As we had discussed in #7656, we should try to find a way to not include everything in the concatenated file if it is not needed.

**Comment by jeherve** [comment] 2023-04-13 17:18
I'd like to come back to this issue and summarize the conversations above a bit:

We currently use [this](https://github.com/Automattic/jetpack/blob/9721658f081d51c97efdc79cc0940c34d135459a/projects/plugins/jetpack/class.jetpack.php#L6151-L6179) to [enqueue a concatenated](https://github.com/Automattic/jetpack/blob/9721658f081d51c97efdc79cc0940c34d135459a/projects/plugins/jetpack/class.jetpack.php#L774-L783) `jetpack.css` file on all frontend views when Jetpack is connected to WordPress.com (as long as you do not use the filter to disable the feature nor have `SCRIPT_DEBUG` set on your site).

That `jetpack.css` file is built off [a list of stylesheets](https://github.com/Automattic/jetpack/blob/9721658f081d51c97efdc79cc0940c34d135459a/projects/plugins/jetpack/class.jetpack.php#L77-L115) from individual modules that are [not enqueued](https://github.com/Automattic/jetpack/blob/9721658f081d51c97efdc79cc0940c34d135459a/projects/plugins/jetpack/class.jetpack.php#L6237-L6245) when the concatenated file is enqueued.

This has a few inconvenients:

1. It doesn't take module status into account; you end up with a full `jetpack.css` even if you don't actually need any of the styles. In that case, not actually doing the whole concatenation would be better. With the advent of http/2, we may also ask ourselves if concatenation is even needed at all anymore.
2. That list of stylesheets also doesn't take stylesheets added by blocks into account. Those are [added individually, only when needed](https://github.com/Automattic/jetpack/blob/0bf40c77c6748e5a57bd6367f59998c728dfbd3e/projects/plugins/jetpack/class.jetpack-gutenberg.php#L501-L510) (when the block is present on the page), and with their potential dependencies. This may not have to be modified right now.

Also of note, this is only about CSS. We do not have anything similar for the different JavaScript files needed by different Jetpack modules.

I'll cc @Automattic/heart-of-gold on this conversation, since they may have some useful input on performance here.

**Comment by cferdinandi** [comment] 2023-04-13 18:05
> With the advent of http/2, we may also ask ourselves if concatenation is even needed at all anymore.

This is pretty key, IMO. There's no benefit to end-users when HTTP/2 is enabled, and it can often be worse than just loading the CSS that's needed.

**Comment by thingalon** [comment] 2023-04-14 01:48
> This is pretty key, IMO. There's no benefit to end-users when HTTP/2 is enabled, and it can often be worse than just loading the CSS that's needed.

It depends. Concatenating resources can still assist with improving compression, as compressing similar text patterns together is more efficient than separately. Based on a quick test, Brotli compression brings jetpack.css down from 99.7 kB to 17.1 kB.

Reviewing the contents of the uncompressed 99.7 kB, the big parts appear to be:

- 18.3 kB for carousel.
- 16.5 kB for sharedaddy.
- 16.2 kB for contact forms.
- 12.2 kB for swiper.
- 6.0 kB for related posts.
- The remaining ~30 kB is comprised of many files smaller than 5 kB each.

My gut feeling is that it's worth splitting out the bigger items that aren't always needed into their own files (e.g.: carousel), but it's better to keep the tiny files and the non-optional files combined. It's hard to estimate exactly how much of the compressed size would be saved by removing things like carousel, but we can expect at least a few kB savings there, which makes it worthwhile IMHO.

But we should probably test actual compressed sizes with different bundling to verify my gut feeling. Compression is a little hard to predict without testing. :)

**Comment by cferdinandi** [comment] 2023-04-14 01:57
> Brotli compression brings jetpack.css down from 99.7 kB to 17.1 kB

17.1kb is not an insignificant amount of code, especially on slower connections and older devices.

> it's better to keep the tiny files and the non-optional files combined

How would you define "non-optional"? I don't use Jetpack for a single front-end feature.

**Comment by p3ob7o** [comment] 2023-10-15 22:35
One specific case that we could handle is when no feature using jetpack.css on the front end is activated. Then we should not load it at all.

**Closed** 2024-10-02 17:59 UTC
Labels: [Type] Enhancement, General, [Focus] Performance, [Status] In Progress, [Pri] Normal, [Plugin] Jetpack
