### ISSUE TITLE
Attachments etc. should be excluded from Related Posts by default

### ISSUE THREAD

**Issue by aldavigdis** [Automattic/jetpack#11412] opened 2019-02-25 14:46 UTC
#### Is your feature request related to a problem? Please describe.
Results of irrelevant post types are being returned from the Related Posts endpoint. This includes attachments and possibly other post types.

<img width="836" alt="screenshot 2019-02-25 at 15 34 56" src="https://user-images.githubusercontent.com/191583/53344527-c3dce280-390a-11e9-8423-eecbd40e05b8.png">

As can be seen in the above screenshot, an Attachment (item from the Media Library) is included in the list if related posts as the last item (bottom-right).

#### Describe the solution you'd like

Users should be able to select which post types are included in responses from the Related Posts endpoint, defaulting on only including posts, and possibly pages only.

This requires work on the WPCOM API side as well as in the Jetpack settings.

#### Describe alternatives you've considered

We could do this on the Jetpack side as well by providing an additional filtering, as is done in the `_filter_non_public_posts` function that is already in the `Jetpack_RelatedPosts` class.

Furthermore, we could go deeper and apply Elasticsearch filters manually as described in the API documentation, using the `filter` request parameter.

**Comment by jeherve** [comment] 2019-03-04 17:58
Related: #10067

**Comment by supernovia** [comment] 2020-06-08 20:44
We have a case here:
https://wordpress.org/support/topic/related-post-showing-media-image/

**Comment by jeherve** [comment] 2023-05-03 14:27
Closing as duplicate of #10067.

**Closed by jeherve** 2023-05-03 14:27 UTC
Labels: [Type] Enhancement, Related Posts, [Pri] Normal
