### ISSUE TITLE
Enhancement: Option to Hide 7 Day Stat Summary on Stat Dashboard

### ISSUE THREAD

**Issue by sdixon194** [Automattic/jetpack#28896] opened 2023-02-10 16:48 UTC
### Impacted plugin

Jetpack

### What

We've received a few requests from users to hide the 7 day stat summary.

### How

Some folks have requested an option to hide the 7 day stat summary at the top of the stats dashboard.

**Comment by sdixon194** [comment] 2023-02-10 16:49
Created from this issue here: https://github.com/Automattic/jpop-issues/issues/8068

cc @Automattic/red

**Comment by jsnmoon** [comment] 2023-02-10 19:14
This is a duplicate of https://github.com/Automattic/wp-calypso/issues/69981; please re-open the ticket if I'm mistaken.

**Closed as not planned by jsnmoon** 2023-02-10 19:14 UTC
Labels: Enhancement, [Feature] Stats Data, [Plugin] Jetpack, [Package] Stats Data
