### ISSUE TITLE
Activity log: Add a file export feature

### ISSUE THREAD

**Issue by dartiss** [Automattic/jetpack#8877] opened 2018-02-19 15:05 UTC
Please add an ability to export the activity log as a file (e.g. csv format). This has been requested by a WordPress.com VIP client who is currently using the activity log featured.

**Comment by jeherve** [comment] 2018-02-19 21:55
Closing as duplicate of 1753-gh-jpop-issues

**Closed by jeherve** 2018-02-19 21:55 UTC
Labels: Activity Log, [Type] Duplicate
