### ISSUE TITLE
Sharing: Print button doesn't work in IE11

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#3743] opened 2016-04-27 16:40 UTC
From [#2842294-org](https://wordpress.org/support/topic/sharing-sharedaddy-print-on-ie?replies=1&view=all):

> Print functionality on IE 11 is not working. All other browsers work perfectly (icons are hidden on mobile by design). I have narrowed down the problem to sharing.js
> 
> If I force IE to use printUrl( uid , ref ); rather than print(); it works fine.

Reference:
https://github.com/Automattic/jetpack/blob/4.0.2/modules/sharedaddy/sharing.js#L293

**Comment by timmyc** [comment] 2016-04-29 22:28
I am not able to reproduce this with 4.0.2 and IE 11 myself.

**Comment by RCowles** [comment] 2016-05-09 18:34
The issues is reported with the following setup:

> OS Name: Microsoft Windows 7 Professional
> OS Version: 6.1.7601 Service Pack 1 Build 7601
> Internet Explorer 11- Version: 11.0.9600.18230

**Comment by kraftbj** [comment] 2021-05-31 16:29
We will be deprecating IE 11 support this summer and thus are wontfix'ing IE 11 issues now. See p1HpG7-c8n-p2

**Closed by kraftbj** 2021-05-31 16:29 UTC
Labels: Sharing, [Type] Bug
