### ISSUE TITLE
Don't use negative numbers for error codes

### ISSUE THREAD

**Issue by edent** [Automattic/jetpack#4410] opened 2016-07-15 07:23 UTC
#### Steps to reproduce the issue
* My blog displays the error message:

> Something which should never happen, happened. Sorry about that. If you try again, maybe it will work.

> Error code: -32300

I decided to [Google the error code](https://www.google.co.uk/search?q=Error+code%3A+-32300).

#### What I expected

To see information about the error.

#### What happened instead

Google treats the `-` symbol as an excludes operator. So it returned information about error codes, but nothing about error 32300.

I removed the `-` and [received meaningful results](https://www.google.co.uk/search?q=Error+code%3A+32300)

![google results for searching for an error code-fs8](https://cloud.githubusercontent.com/assets/837136/16866582/a43c1fa0-4a64-11e6-8551-39feca810034.png)

![google search for error code without a negative number - correct results returned-fs8](https://cloud.githubusercontent.com/assets/837136/16866597/ba438cd4-4a64-11e6-9f5b-8894ec3cc150.png)

May I suggest that when the error code is displayed to the user, you remove the `-` symbol.  This will make it easier for users to select the error code and then search for it.

The specific line of code is https://github.com/Automattic/jetpack/blob/8d13e90a72b1afad48a6d3c380019c4834c922f3/class.jetpack-ixr-client.php#L49

**Comment by jeherve** [comment] 2016-07-18 09:55
Thanks for the suggestion. We would indeed like to improve those error messages in the future. I'll close this issue as duplicate of #2534.

**Closed by jeherve** 2016-07-18 09:55 UTC
