### ISSUE TITLE
Sharing: issues when creating a custom sharing button on Archive CPT page

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#211] opened 2014-02-13 13:10 UTC
Steps to reproduce:
1. Register a new Custom Post Type on your site, named `product` ([like so](https://gist.github.com/jeherve/e3a69b5512027efe80fd)).
2. In Settings > Sharing in your dashboard, activate sharing buttons for that CPT.
3. In your theme, create a new `archive-product.php` template file
4. In this template, remove all references to `the_content` and `the_excerpt`, and place the following code at the top of the page:

``` php
<?php if ( function_exists( 'sharing_display' ) ) {
    sharing_display( '', true );
} ?>
```

A new set of sharing buttons will appear, and we want this set of sharing buttons to allow us to share links to the CPT archive page. By default, the buttons link to the first CPT item of the loop.
5. Let's add the following code to our theme's functions.php file:

``` php
function jeherve_archive_cpt_display_link( $url ) {
    if ( is_post_type_archive( 'product' ) ) {
        $url = get_post_type_archive_link( 'product' );
    }
    return $url;
}
add_filter( 'sharing_display_link', 'jeherve_archive_cpt_display_link' );

function jeherve_archive_cpt_sharing_link( $url, $post_id ) {
    if ( is_post_type_archive( 'product' ) ) {
        $url = get_post_type_archive_link( 'product' );
    } else {
        $url = get_permalink( $post_id );
    }
    return $url;
}
add_filter( 'sharing_permalink', 'jeherve_archive_cpt_sharing_link', 10, 2 );
```

It should allow us to change the links used by the sharing buttons on this page.
6. Hit the sharing buttons
- The pop up appears, and seems to be using the right URL, but doesn't get redirected to the Social Media site.

Does something need to be changed on the Javascript end of things as well?

Reported here:
- http://wordpress.org/support/topic/sharing_display_link-sharing_title?replies=3#post-5225801

**Comment by abombelli** [comment] 2016-03-18 14:37
An news here?

**Comment by jeherve** [comment] 2016-03-18 14:41
@abombelli We haven't made any progress on this, and it's not currently on our priority list since it's a fairly rare scenario.

If you have any suggestions on how to approach this issue, do not hesitate to [submit a Pull Request](https://github.com/Automattic/jetpack/blob/master/.github/CONTRIBUTING.md). We'd welcome community contributions on this issue!

**Comment by enejb** [comment] 2016-08-09 19:20
So I think I understand the issue here much better now. 
The issue is that we can only share permalink to pages or single post types and not to any arbitrary url of the site. Part of the reason for this is we don't explicitly declare what the text should be but instead dynamically generate that part from a single post. ( What is the post title of an archive page? )

I think this issue could be fixed by providing our users with more filters that they could use to declare these things. 

I wasn't able to reproduce the issue where we link to the wrong post url. Maybe that part is resolved?

**Closed as completed** 2018-09-13 11:19 UTC
Labels: Bug, [Feature] Sharing, Good For Community

**Comment by asafm7** [comment] 2020-06-15 16:30
Any plans to make it happen?

**Comment by jeherve** [comment] 2020-06-15 16:37
@asafm7 As mentioned above in https://github.com/Automattic/jetpack/issues/211#issuecomment-198390926, it's not on our roadmap at the moment, but if you'd like to contribute a patch we'll be happy to review it. Thank you!

**Comment by bobmatyas** [comment] 2021-08-06 19:58
Another request here:

https://wordpress.org/support/topic/facebook-post-share-image-issues/page/2/#post-14733502
