### ISSUE TITLE
Possible bug on All Tag Pages in Widget Visibility Settings

### ISSUE THREAD

**Issue by StefMattana** [Automattic/jetpack#5352] opened 2016-10-15 14:14 UTC
The All Tag Pages in the Widget's Visibility settings is not working. 

When defining a specific tag, such as 'Chase', the widget comes up: 
<img width="1117" alt="screen shot 2016-10-15 at 15 04 26" src="https://cloud.githubusercontent.com/assets/11662998/19410655/646e9934-92e9-11e6-85ac-ac9f2ab1935a.png">

When defining the tag as All Pages, it won't appear: 
<img width="1124" alt="screen shot 2016-10-15 at 15 06 54" src="https://cloud.githubusercontent.com/assets/11662998/19410658/68142ce8-92e9-11e6-96c2-74d1cf728d83.png">

I tested it in my test site (Pressable) and my online sites and blogs (all SiteGround hosted) and had the same issue. Another user had the same issue as well.

**Comment by jeherve** [comment] 2016-10-17 10:55
Closing as duplicate of #3020

**Closed by jeherve** 2016-10-17 10:55 UTC
Labels: Widget Visibility, [Type] Bug
