### ISSUE TITLE
VideoPress: Set up a "watch" job

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#25828] opened 2022-08-25 11:28 UTC
That will allow us to use `jetpack watch plugins/videopress` and quickly build the js assets when we make changes to the files

**Comment by renatoagds** [comment] 2022-08-26 15:42
@retrofox today I have been doing it by executing:  `jetpack watch packages/videopress`, it got reflected into the `plugin`, it's not worth?

**Comment by leogermani** [comment] 2022-08-29 16:37
@renatoagds currently yes, it is the same because we don't have anything in the plugin. But in theory we could have additional code and dependencies in the plugin. It would be nice to have a watch in the plugin as well

**Comment by lhkowalski** [comment] 2022-09-23 13:53
I added the `watch` command on #26329. Currently, it's only an alias for `jetpack watch packages/videopress`, but we can expand it in the future. I will close this issue, but feel free to reopen it if there is something missing.

**Comment by lhkowalski** [comment] 2022-09-23 13:53
Duplicate of #26325.

**Closed as completed by lhkowalski** 2022-09-23 13:53 UTC
Labels: [Plugin] VideoPress
