### ISSUE TITLE
Plaintext Shortcode Content Stripped from Excerpt Sent via Publicize

### ISSUE THREAD

**Issue by BrazenlyGeek** [Automattic/jetpack#2697] opened 2015-09-11 15:58 UTC
On my site, I use a shortcode, [sitename], to output the name of my site ("On Sixes & Sevens") with slight styling -- a special class on the ampersand. (This also lets me change the branding on the site while updating any reference to the name instantly across the whole site.)

The issue, though, is that if I use [sitename] within paragraph or so, the content is sent to Facebook w/o the name included, which results in a broken sentence. "[sitename] would like to remind you..." becomes " would like to remind you..."

I know now that making custom excerpts circumvents this, and I also know that shortcodes are stripped because plenty of them output HTML which wouldn't make any sense to send to Facebook. But is it possible to enable plaintext shortcodes that are safe for HTML to be striped from without losing meaning?

**Comment by kraftbj** [comment] 2015-09-11 16:33
There's an ongoing project to improve the way we sync content, including rendered shortcode content.

Closing as a duplicate of #869.

**Closed by kraftbj** 2015-09-11 16:33 UTC
