### ISSUE TITLE
Shortcode Embeds: YouTube embed links blocked with ERR_BLOCKED_BY_RESPONSE

### ISSUE THREAD

**Issue by ahegyes** [Automattic/jetpack#33580] opened 2023-10-12 15:31 UTC
### Impacted plugin

Jetpack

### Quick summary

YouTube has started introducing a new COOP policy that is affecting YouTube embeds when Jetpack's shortcode embeds module is activated. Namely, it prevents the video from opening in a new tab when clicking the title **or** the `Watch on YouTube` banner: ![3AdN85.png](https://github.com/Automattic/jetpack/assets/36231502/086406a7-010a-469c-88b5-7da70c3351b8)

This is because of the `sandbox` parameter added by the module at this line: https://github.com/Automattic/jetpack/blob/f90120b19e02f2b3a806a7c3e8c8a21c75b6b2b0/projects/plugins/jetpack/modules/shortcodes/youtube.php#L345

I confirmed that the error goes away if the `sandbox` attribute is either not present or if the list includes the `allow-popups-to-escape-sandbox` value, [as suggested by this comment](https://bugs.chromium.org/p/chromium/issues/detail?id=1463173#c13).

### Steps to reproduce

1. Ensure that the Jetpack Shortcode Embeds module is active
2. Add a YouTube embed to a post (via Gutenberg, e.g.)
3. Try to click on the `Watch on YouTube` banner when viewing the post

### A clear and concise description of what you expected to happen.

A new tab would open where the video opens on YouTube.

### What actually happened

The error `www.youtube.com is blocked` shows up.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by cuemarie** [comment] 2023-10-12 23:59
Duplicate of https://github.com/Automattic/jetpack/issues/33593

@ahegyes  I'll share your findings regarding Jetpack's shortcodes modules on the open issue - thanks for those notes!

**Closed as not planned by cuemarie** 2023-10-12 23:59 UTC
Labels: Bug, [Pri] High, [Plugin] Jetpack, Needs triage, [Status] Priority Review Triggered
