### ISSUE TITLE
Authorize Screen: Old Logo and not mobile friendly

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/jetpack#1769] opened 2015-03-13 15:58 UTC
When connecting a page with Jetpack, you are sent to this screen to authorize your account:
![screen shot 2015-03-12 at 2 14 19 pm](https://cloud.githubusercontent.com/assets/3220162/6641994/b6cfab74-c95e-11e4-9b95-568163aab85b.png)

- The page is not responsive so it's tricky to do on a phone.
- It uses an old Jetpack Logo 
- If your site name is too large, it wraps around oddly
![screen shot 2015-03-13 at 8 57 04 am](https://cloud.githubusercontent.com/assets/3220162/6642032/f3cc11b6-c95e-11e4-8908-d0c613ebcace.png)

I am pretty sure this is a duplicate report, just writing it again for posterity.

**Comment by kraftbj** [comment] 2015-03-13 16:10
Related and duplicate of #823 :)

**Closed** 2015-03-13 16:12 UTC
Labels: General
