### ISSUE TITLE
Donation Block: does not render in Subscriber Emails

### ISSUE THREAD

**Issue by ktyfuller604** [Automattic/jetpack#17730] opened 2020-11-05 21:32 UTC
#### Steps to reproduce

1. Create a new Post on a site that has email subscribers
2. Add a donation block to the post
3. Publish the post
4. Check the email received by a subscriber

#### What I expected

The donation block renders in the subscriber email.

#### What happened instead

A blank box where the donation block should be. 

#### Screenshot / Video

![image](https://user-images.githubusercontent.com/38542929/98298761-81dfbd00-1f84-11eb-83e8-3e6c69c231e3.png)

#### Context / Source

#user-report

**Comment by mmtr** [comment] 2020-11-09 08:42
Thanks for your report @ktyfuller604! I think this is the expected behavior right now, since we implemented a fallback version for the Donations block to use on emails in https://github.com/Automattic/jetpack/pull/17381 / D51410-code which will be released tomorrow with Jetpack 9.1. 

Once JP 9.1 is out, emails should include links to the post and will look like this: 

![image](https://user-images.githubusercontent.com/1233880/98518526-c95d9600-226f-11eb-9a9c-d8709ae12d53.png)

**Closed by mmtr** 2020-11-09 08:42 UTC
Labels: [Block] Donations, [Pri] Normal, [Type] Enhancement
