### ISSUE TITLE
Error messages unreadable

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#3653] opened 2016-04-12 22:16 UTC
![screen shot 2016-04-12 at 15 12 37](https://cloud.githubusercontent.com/assets/115071/14477228/41f6f19a-00c1-11e6-8930-dcd2b6bdf89f.png)

#### What I expected
To be able to read the text in the error messages.

#### What happened instead
See the screenshot ^

#### Steps to reproduce the issue
Connect Jetpack. 
The error messages read 
`Post Types Order must be configured. Please go to Settings Page make the configuration and save`
and 
`You are currently running a development version of Jetpack. Submit your feedback`

The reason why I can't read them is because of this css
```
.jetpack-message p {
    color: #fff;
}
```

cc: @jeffgolenski

**Comment by jeherve** [comment] 2016-04-13 09:04
Closing as duplicate of #3045

**Closed by jeherve** 2016-04-13 09:04 UTC
Labels: General, [Type] Bug
