### ISSUE TITLE
Editor: Underline is sometimes missing [1]

### ISSUE THREAD

**Issue by kwight** [Automattic/jetpack#12386] opened 2019-05-15 20:00 UTC
The underline tool, added as part of the WordPress.com block editor work, is missing.

<img width="788" alt="Screen Shot 2019-05-15 at 12 53 58 PM" src="https://user-images.githubusercontent.com/349751/57805083-0b585b00-7711-11e9-9d0c-9f0840e30da2.png">

#### Steps to reproduce the issue

1. With Jetpack v7.3.1+ active, create a new post.
2. Add a paragraph block, and some text.
3. Select some text, and click the dropdown shown above.
4. Justify will be present, but not Underline.

**Comment by gwwar** [comment] 2019-05-17 18:55
If folks can't reproduce this one and we receive no reports, let's close this out.

**Comment by kraftbj** [comment] 2019-05-20 14:17
I believe that's intentional (for Gutenberg) as underlining on the web is usually associated with links. The keyboard shortcut but there's no UI for it.

**Comment by jeherve** [comment] 2019-05-20 15:44
> The keyboard shortcut but there's no UI for it.

The WordPress.com Block Editor adds it to Jetpack-sites though, when you use Calypsoify on the site or when you load the iFramed block editor in Calypso.

**Comment by gwwar** [comment] 2019-10-30 00:17
Let's sort out if Jetpack would like underline/strikethrough in https://github.com/Automattic/wp-calypso/issues/34476

This is a customization as @kraftbj noted. See https://github.com/Automattic/wp-calypso/issues/28696 for past history.

**Closed by gwwar** 2019-10-30 00:17 UTC
Labels: Calypsoify, WordPress.com Block Editor, [Type] Bug
