### ISSUE TITLE
alert message while editing posts

### ISSUE THREAD

**Issue by amirhkhadem** [Automattic/jetpack#7846] opened 2017-09-25 08:14 UTC
hello automattic people, 

i am having a very annoying problems for all my users using my wordpress website,

the issue is an **error message** we receive **when editing a post**

i receive the below message

`Failed to load content css: http://www.example.com/wp-content/plugins/jetpack/modules/videopress/css/videopress-editor-style-rtl.css`

and i dont know why you guys dont fix this in your updates, i have seen this issue posted on other sites too.

**Comment by jeherve** [comment] 2017-09-25 08:17
Closing as duplicate of #7464

**Closed by jeherve** 2017-09-25 08:17 UTC
