### ISSUE TITLE
Jetpack Stats: Subscriber Data Display Issue - Timestamps Missing and Click Metrics Showing as 0% Instead of Numerical Values

### ISSUE THREAD

**Issue by michaelglorydev** [Automattic/jetpack#40697] opened 2024-12-20 10:06 UTC
### Impacted plugin

Jetpack

### Quick summary

Jetpack Stats subscriber view is displaying incorrect data and missing information. The "Since" column shows "-" instead of subscription timestamps, and click data for emails has changed from numerical values to percentages (most showing 0%). 

While the correct data for the "since" column is still accessible through the "Manage Subscribers" interface, the main Stats dashboard display is not functioning as intended. 

Issue has been verified through user reports, direct dashboard access, and test site replication. The problem appears to be a recent change affecting all users with Jetpack Stats.

Initial report: 9179725-zd-a8c
![Image](https://github.com/user-attachments/assets/2fa50e7e-3e45-450f-a327-f9413a8c6cb2)

### Steps to reproduce

1. Create a new WordPress site
2. Add a Subscribe block to any page/post
3. Generate test subscriptions through the frontend
4. Wait approximately 5 minutes for stats to update
5. Navigate to https://wordpress.com/stats/subscribers/{site_url}
6. Observe the subscribers list in the Stats dashboard 

### A clear and concise description of what you expected to happen.

"Since" column should display the subscription date/time for each subscriber
Click data should display as numerical values

### What actually happened

"Since" column shows only "-" for all subscribers in the Stats dashboard
Click data is displaying mostly as "0%" instead of numerical values.

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

Users can access accurate subscription timestamps by:

Scrolling to the bottom of the Subscribers Stats page
Clicking "Manage Subscribers" link
Viewing the full subscriber list, where "Since" dates are correctly displayed

### Platform (Simple and/or Atomic)

Simple

**Comment by Robertght** [comment] 2024-12-20 10:54
I believe this is tied to this same issue https://github.com/Automattic/wp-calypso/issues/9763

I am flagging this for you as well @Automattic/zap

**Comment by simison** [comment] 2024-12-20 11:18
Thanks, I'll close this as duplicate of https://github.com/Automattic/wp-calypso/issues/97601

**Closed as completed by simison** 2024-12-20 11:18 UTC
Labels: Bug, [Feature] Stats Data, [Pri] High, Customer Report [LEGACY], [Plugin] Jetpack, Triaged, [Platform] Simple, [Status] Priority Review Triggered, [Status] Escalated to Product Ambassadors
