### ISSUE TITLE
Subscribe Block: "Place button on new line" setting is not respected.

### ISSUE THREAD

**Issue by happychait** [Automattic/jetpack#33228] opened 2023-09-21 04:57 UTC
### Impacted plugin

Jetpack

### Quick summary

On the Subscribe Block, the button is not stacked in the new line even selecting "Place button on new line" option is enabled in block settings. 

Works fine in the editor, but on the actual site, the button is not displayed on the new line.

### Steps to reproduce

1. Open the page/post editor.
2. Add a Subscribe Block.
3. From the block settings, enable "• Place button on new line".
4. Update the page/post.

### A clear and concise description of what you expected to happen.

The button should be in the new line in the editor as in this screenshot:  

![Subscribe Block in the editor](https://github.com/Automattic/jetpack/assets/1519466/6e86ea05-d199-489f-b004-475f9df5a0dc)

### What actually happened

On the site, the button is not on the new line and skewed as in this screenshot:  

![Place button on new line](https://github.com/Automattic/jetpack/assets/1519466/9dfc7f03-ad38-4270-a18f-b2c7232662cc)

### Impact

One

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

This CSS workaround worked:

```
footer .is-style-split .wp-block-jetpack-subscriptions__form-elements { 
    flex-direction: column !important;
} 
footer .is-style-split #subscribe-email {
     width: 100%;
} 
footer .is-style-split button[type="submit"] {
     width: 100% !important;
}
```

**Comment by jeherve** [comment] 2023-09-21 07:15
Closing as duplicate of #33197

**Closed as completed by jeherve** 2023-09-21 07:15 UTC
Labels: Bug, [Closed] Duplicate, [Feature] Subscriptions, [Pri] Normal, [Block] Subscribe, [Plugin] Jetpack, [Platform] Simple, [Platform] Atomic
