### ISSUE TITLE
Jetpack Search language search on multilingual site

### ISSUE THREAD

**Issue by McNCo** [Automattic/jetpack#16150] opened 2020-06-12 14:13 UTC
#### Is your feature request related to a problem? Please describe.
Apparently Jetpack Search does not support multilingual search, i.e. the ability only to search one language sub-directory at a time. This is a problem if you want to search specific language content on a multilingual site. 

#### Describe the solution you'd like
I am developing a multilingual site, most likely with language-specific subdirectories, e.g. website.com/en for English and website.com/es for Spanish. 

I want to use Jetpack Search only to search individual languages / sub-directories. I.e. When some accesses website.com/es, it will only search the Spanish language content in that subdirectory and deliver Spanish results, and not the English content on website.com/en.

#### Describe alternatives you've considered
Perhaps creating categories / sub-categories for some kind of faceted search but this is not ideal as the content will not be the same for each sub-directory.  

#### Additional context
N/A

**Comment by jeherve** [comment] 2020-06-15 11:14
Closing as duplicate of #8766.

**Closed by jeherve** 2020-06-15 11:14 UTC
Labels: Instant Search, Internationalization, Search, [Type] Enhancement
