### ISSUE TITLE
SSO: Add a link to user site regisration page

### ISSUE THREAD

**Issue by enejb** [Automattic/jetpack#8600] opened 2018-01-23 22:50 UTC
Currently if a user's site has SSO enabled and also allows user registrations on the site. 
We should expose the link for users to register better. 

Currently we see this:
![screen shot 2018-01-23 at 2 46 59 pm](https://user-images.githubusercontent.com/115071/35305002-8e258eb4-004c-11e8-8066-f7f0e0c0b16f.png)

This is what you see when you don't have sso enabled. 
![screen_shot_2018-01-23_at_2_47_12_pm](https://user-images.githubusercontent.com/115071/35305048-c5b50986-004c-11e8-9b65-80170e42a3bd.png)

**Comment by jeherve** [comment] 2018-01-24 09:09
Closing as duplicate of #5279

**Closed by jeherve** 2018-01-24 09:09 UTC
Labels: SSO, [Type] Enhancement
