### ISSUE TITLE
Can't unsubscribe from "is now following your blog" emails

### ISSUE THREAD

**Issue by iandunn** [Automattic/jetpack#9330] opened 2018-04-17 16:45 UTC
I recently started getting "{email | username} is now following your blog" emails for a few sites that I connected to WordPress.com. I'd like to unsubscribe from those, but the link in the footer doesn't work.

The footer says, "Want less email? Modify your [Discussion Settings](https://2018.us.wordcamp.org/wp-admin/options-discussion.php?sn=s)." There isn't anything on that page that allows me to disable the emails, though. I also looked for ways to unsubscribe at `wp-admin/admin.php?page=jetpack#/discussion`, `wordpress.com/people/email-followers/{url}`, and `subscribe.wordpress.com`, but couldn't find anything. 

I think the email should contain a link to unsubscribe from these types of notifications.

For what it's worth, I also think it'd be worth reconsidering whether these emails should be sent without the user's consent to begin with. I can see some people wanting to receive them, but if you have even a modest amount of followers they lose value and become irritating very quickly. At the very least, though, there should be a working opt-out mechanism.

The email address is my automattic.com one, and the sites are `2018.us.wordcamp.org` and `2018.europe.wordcamp.org`.

**Comment by jeherve** [comment] 2018-04-18 07:05
Closing as duplicate of #709.

@iandunn For now you should be able to deactivate this in Calypso, as per this comment:
https://github.com/Automattic/jetpack/issues/709#issuecomment-381006862

**Closed by jeherve** 2018-04-18 07:05 UTC
Labels: Subscriptions, [Type] Duplicate
