### ISSUE TITLE
Subscriber-role users see Akismet and Protect stats on dashboard

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#8403] opened 2017-12-21 17:05 UTC
This was raised in 860124-zen

If you log in to a site with a Subscriber user, you see this:

<img width="693" alt="screen shot 2017-12-21 at 12 02 41 png" src="https://user-images.githubusercontent.com/3676359/34266430-07e46092-e647-11e7-856f-8468e82b7ef7.png">

Should we be showing this by default to non-admin users?

**Comment by jeherve** [comment] 2017-12-29 17:35
Closing as duplicate of #2405

**Closed by jeherve** 2017-12-29 17:35 UTC
Labels: Admin Page, [Type] Enhancement
