### ISSUE TITLE
Jetpack Contact Form Block: Error validation is not consistent

### ISSUE THREAD

**Issue by mapk** [Automattic/jetpack#11867] opened 2018-11-14 22:02 UTC
As @fditrapani discovered, the error validation is inconsistent on the frontend. With two fields set to be "required", if form submits when fields are empty, only ONE error msg appears.

**Example of **problem:**

![validation](https://user-images.githubusercontent.com/617986/48515509-c14ff480-e815-11e8-9f17-f359ffedfedd.gif)

**Solution:**
Both error messages should show.

**Comment by scruffian** [comment] 2019-04-03 14:47
See also https://github.com/Automattic/wp-calypso/issues/29085

**Comment by jeherve** [comment] 2024-07-23 10:52
Closing as duplicate of #7888.

**Closed by jeherve** 2024-07-23 10:52 UTC
Labels: [Type] Enhancement, [Feature] Contact Form, [Focus] Blocks
