### ISSUE TITLE
Instant Search: search results can contain unexpected elements (e.g. h2)

### ISSUE THREAD

**Issue by bluefuton** [Automattic/jetpack#17823] opened 2020-11-17 01:08 UTC
#### Steps to reproduce the issue

1. Go to https://wordpress.com/support?s=heading
2. Note that some results contain a h2:

<img width="783" alt="Screen Shot 2020-11-17 at 14 06 23" src="https://user-images.githubusercontent.com/17325/99327115-1976d100-28de-11eb-8c0e-e46ab4509c89.png">
<img width="524" alt="Screen Shot 2020-11-17 at 14 06 26" src="https://user-images.githubusercontent.com/17325/99327121-1c71c180-28de-11eb-86ca-357bfab09f4f.png">

#### What I expected

The result excerpt should have most elements stripped except for basic formatting (like i and strong).

#### What happened instead
The h2 was included in the result, and it looked odd.

**Comment by gibrown** [comment] 2020-11-17 03:23
Just leaving a note here that I assume this is getting caused by our new content stripping, though I still don't see how it can happen. There are also some potential fixes in the api response as well where we could be stripping more tags than we already are.

**Comment by robfelty** [comment] 2020-11-17 16:10
I debugged some more, and I do not think it is getting caused by the new content cleaning. However, that hint got me to within 10 lines of the culprit. I think the issue arises from calling `html_entity_decode` . In this example, the 

original text is:
`at <code>&lt;h2&gt;</code> and so on` 
which after calling `strip_tags` becomes
`at &lt;h2&gt; and so on`
and then after calling `html_entity_decode` becomes:
`at <h2> and so on`

I see 2 possible solutions:
1. Stop calling html_entity_decode - this will make it impossible to search for things like "<" though
2. Call htmlentities before rendering content
Possible solution at D52858-code

**Comment by robfelty** [comment] 2020-11-27 11:57
Fixed in D52858-code

**Closed by robfelty** 2020-11-27 11:57 UTC
Labels: Instant Search, Search, [Status] In Progress, [Type] Bug
