### ISSUE TITLE
Video block: Block validation failed in site editor

### ISSUE THREAD

**Issue by brbrr** [Automattic/jetpack#22836] opened 2022-02-14 09:31 UTC
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Setup Jetpack with block based theme
2. Open post or site editor
3. check JS console

### What actually happened

JS error thrown:

```
Block validation: Block validation failed for `core/video`

Content generated by `save` function:

<figure class="wp-block-video"></figure>

Content retrieved from post body:

<figure class="wp-block-video"><video controls src="https://capitalist-marten.jurassic.ninja/wp-content/themes/twentytwentytwo/assets/videos/birds.mp4"></video></figure>
```

### Browser

Chrome/Chromium

**Comment by jeherve** [comment] 2022-04-22 14:44
Closing as duplicate of #23953.

**Closed by jeherve** 2022-04-22 14:44 UTC
Labels: [Type] Bug, [Plugin] Jetpack, [Block] VideoPress
