### ISSUE TITLE
Move the "Share" and "Like" buttons into blocks, to allow better control on alignment

### ISSUE THREAD

**Issue by kimclow** [Automattic/jetpack#34917] opened 2024-01-09 15:18 UTC
### Impacted plugin

Social

### What

It would be great to have more control over the position and layout of the like and share buttons. 

### How

If the share and like buttons are enabled, they sit one below the other, which uses up a lot of real estate on the post. It would be great if there was a way for us to have these aligned horizontally. There doesn't seem to be a simple CSS solution for aligning the two. 

I'm not a developer, so not 100% sure of the "how", however, I think if we could bundle the buttons into blocks, we'd be able to move them around a bit, and customise them further. 

<img width="342" alt="Screenshot 2024-01-09 at 17 16 22" src="https://github.com/Automattic/jetpack/assets/83212200/0c0c7346-53be-4e23-8090-48338379ed4c">

**Comment by jeherve** [comment] 2024-01-09 15:40
Closing as duplicate of #31920

**Closed as completed by jeherve** 2024-01-09 15:40 UTC
Labels: [Closed] Duplicate, Enhancement, [Feature] Sharing, [Feature] Likes, [Plugin] Jetpack, Triaged
