### ISSUE TITLE
Contact Form: Editing labels in Safari causes cursor to skip to input field

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/jetpack#11255] opened 2019-02-03 22:29 UTC
#### Steps to reproduce the issue

1. Load any site running Gutenberg, in Safari
2. Via either Calypso or WP Admin, add a default Form block to a page or post
3. Click "Add Form" to add it to the page
4. Try to edit any of the form field labels, either by double-clicking the text to select it, or putting your cursor to the end of it and backspacing to overwrite it

#### What I expected
I expected to be able to edit the form label text.

#### What happened instead
The moment I try to select the label text, the cursor pops into the input field, making it almost impossible to edit the label.

####  Screencast

https://cloudup.com/cW6K6jbfJOe

#### Testing Conditions
Tested in Safari 12.0.3 and Jetpack version 6.9 on:
- self-hosted localhost install (WP 5.0.3)
- WordPress.com Simple site
- WordPress.com Atomic site

No issues in Firefox 65.0 or Chrome 72.0.3626.81.

#### Tickets

First encountered during a Business concierge session in 1771869-zen

**Comment by jeherve** [comment] 2019-02-04 07:54
Closing as duplicate of https://github.com/Automattic/wp-calypso/issues/29973

**Closed by jeherve** 2019-02-04 07:54 UTC
Labels: Contact Form, Gutenberg, [Type] Bug, [Type] Duplicate
