### ISSUE TITLE
Defer loading of stats.wp.com script

### ISSUE THREAD

**Issue by tillkruss** [Automattic/jetpack#1487] opened 2015-01-12 06:34 UTC
They way the `stats.wp.com` script is currently loaded is a bad practice and slows down the rendering of the page.

Please implement a non render-blocking loading of the statistics script like [Google Analytics][1] or [HTML5 Boilerplate][2] does.

[1]: https://developers.google.com/analytics/devguides/collection/analyticsjs/
[2]: https://github.com/h5bp/html5-boilerplate/blob/master/src/index.html#L30

**Comment by tillkruss** [comment] 2015-01-12 07:34
In order to achieve that, the script hosted on `stats.wp.com` needs to be adjusted as well, because it's currently using `document.write` in the called `st_go()` function. Which is also a bad practice, because if it runs after a page finishes loading, it overwrites the entire document with the content it outputs.

**Comment by tillkruss** [comment] 2015-01-12 08:03
The code below uses the `template_redirect` action to override Jetpack's `$stats_footer`. The JavaScript code can easily be compressed into a 1-3 liner.

```PHP
add_action( 'template_redirect', function() {

	global $stats_footer;

	if ( preg_match( '~/e-(\d+).js"~', $stats_footer, $matches ) && isset( $matches[1] ) ) {
		$week = $matches[1];
	}

	if ( preg_match( '~st_go\((.+)\);~', $stats_footer, $matches ) && isset( $matches[1] ) ) {
		$data = $matches[1];
	}

	if ( preg_match( '~linktracker_init\(.+\);~', $stats_footer, $matches ) && isset( $matches[0] ) ) {
		$linktracker = $matches[0];
	}

	if ( ! isset( $week, $data, $linktracker ) ) {
		return;
	}

	$stats_footer = <<<END
<script type="text/javascript">
	(function(i,z,x){
		r = i.createElement(z);
		d = i.getElementsByTagName(z)[0];
		r.src='//stats.wp.com/e-$week.js';
		r.async=true;
		r.onload = r.onreadystatechange = function() {
			a = this.readyState;
			if(a&&a!="complete"&&a!="loaded") return;
	
			u = '//pixel.wp.com/g.gif?host='+escape(i.location.host)+'&rand='+Math.random();
			for(v in x){u=u+'&'+v+'='+escape(x[v]);}
			u=u+'&ref='+escape(i.referrer);
	
			b = i.createElement('img');
			b.src = u;
			b.id = 'wpstats';
	
			i.body.appendChild(b);
	
			$linktracker
	
		};
		d.parentNode.insertBefore(r,d);
	}(document, 'script', $data ));
</script>
END;

} );
```

**Comment by jeherve** [comment] 2015-01-12 08:47
Closing as duplicate of #566

**Closed by jeherve** 2015-01-12 08:47 UTC
Labels: duplicate, enhancement, Stats
