### ISSUE TITLE
Payments - Donation Form and Premium Content pattern cannot be added on Simple Sites

### ISSUE THREAD

**Issue by masperber** [Automattic/jetpack#30006] opened 2023-04-08 18:37 UTC
### Quick summary

When adding the Payments Block, users are prompted to choose a pattern upon block creation. On Simple sites, the Donation Form pattern cannot be selected. Clicking on the button produces no effect.

<img width="994" alt="Screenshot 2023-04-08 at 2 35 36 PM" src="https://user-images.githubusercontent.com/12906034/230737528-38ecdb5f-2ba8-452d-9939-0f3ce229af87.png">

### Steps to reproduce

1. Start a Simple Site
2. Add a Payments Block
3. Click on the Donation Form button

### What you expected to happen

The Donation Form pattern should be applied to the block

### What actually happened

No effect

### Impact

All

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple

**Comment by karenroldan** [comment] 2023-04-10 10:12
📌 REPRODUCTION RESULTS

- Tested on Simple – Replicated
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
I cannot select the Donations Form or Premium Content on the Simple site.

![donations-form-premium-content-simple](https://user-images.githubusercontent.com/67279475/230881846-a3edec12-8097-46a6-9b14-26d05147d274.gif)

Similar to: https://github.com/Automattic/jetpack/issues/29640

📌 ACTIONS
- Transferred to Jetpack repo
- Escalated here: p1681121737343689-slack-C02FMH4G8

**Comment by danielbachhuber** [comment] 2023-04-10 11:18
Some debugging...

`usableVariations` has this data:

https://github.com/Automattic/jetpack/blob/b01b38e4dd7ebafbf396d8a1136e34bdc1e68bca/projects/plugins/jetpack/extensions/blocks/payments-intro/edit.js#L32

```
usableVariations 
(3) [{…}, {…}, {…}]
0
: 
{name: 'jetpack/donations', title: 'Donations Form', description: 'Collect one-time, monthly, or annually recurring donations.', icon: {…}}
1
: 
{name: 'jetpack/payment-buttons', title: 'Payment Buttons', description: {…}, icon: {…}}
2
: 
{name: 'premium-content/container', title: 'Premium Content', description: 'Restrict access to your content for paying subscribers.', icon: {…}}
length
: 
3
[[Prototype]]
: 
Array(0)
```

Clicking 'Premium Content' also doesn't produce a replacement. However, it does call `setVariation` as expected:

https://github.com/Automattic/jetpack/blob/b01b38e4dd7ebafbf396d8a1136e34bdc1e68bca/projects/plugins/jetpack/extensions/blocks/payments-intro/edit.js#L27-L30

```
wpcom-block-editor:tracking action "replaceBlock" called with 
(2) ['1c56cc1d-24b4-41e4-b717-53b4b4db637d', {…}]
0
: 
"1c56cc1d-24b4-41e4-b717-53b4b4db637d"
1
: 
{clientId: '77664eff-4c9b-4c2b-83f8-082354074baa', name: 'premium-content/container', isValid: true, attributes: {…}, innerBlocks: Array(0)}
length
: 
2
[[Prototype]]
: 
Array(0)
```

It seems like `replaceBlock` is the problem. https://github.com/WordPress/gutenberg/issues/46740 might be related

**Comment by WunderBart** [comment] 2023-04-11 10:45
Works for me on a Simple site with Gutenberg v15.4. Are there any console and/or request errors when you click the button?

**Comment by danielbachhuber** [comment] 2023-04-11 11:55
@WunderBart and I debugged together. It works for him and not for me 🙃

We tracked the discrepancy down to:

```
wp.data.select('core/block-editor').canInsertBlockType('premium-content/container', '');
```

This function returns `true` for Bart and `false` for me.

It's called in https://github.com/WordPress/gutenberg/blob/ac871a255805c922f780fb125ab2104b2dbcb664/packages/block-editor/src/store/actions.js#L411-L416, which then calls https://github.com/WordPress/gutenberg/blob/ac871a255805c922f780fb125ab2104b2dbcb664/packages/block-editor/src/store/selectors.js#L1529-L1536

When I inspect `wp.data.select('core/block-editor').getSettings();`, I see:

![image](https://user-images.githubusercontent.com/36432/231155190-38e7da56-9900-485a-b47d-8676b95250fc.png)

However, Bart simply sees `allowedBlockTypes: true`.

We've found the discrepancy! But no idea why these are different.

**Comment by WunderBart** [comment] 2023-04-11 12:59
For the fix, see https://github.com/Automattic/jetpack/issues/28523#issuecomment-1503286721. I think we can close this one in favor of #28523.

**Comment by karenroldan** [comment] 2023-04-11 13:26
Thanks for investigating, @danielbachhuber and @WunderBart! 

I can confirm that enabling the preferences for both the `Donations Form` and `Premium Content` will fix the issue. I'm closing this issue in favor of #28523. 

![Donations Form](https://user-images.githubusercontent.com/67279475/231174915-9bc3851b-575a-46b8-bdf0-4c3be3b7d996.gif)

**Closed as completed by karenroldan** 2023-04-11 13:26 UTC
Labels: Bug, [Pri] BLOCKER, [Block] Paid Content, [Block] Payments, [Block] Donations, [Platform] Simple, [Status] Priority Review Triggered
