### ISSUE TITLE
Carousel: Under some themes navigation in Carousel becomes non-functional

### ISSUE THREAD

**Issue by andrewspittle** [Automattic/jetpack#20671] opened 2021-08-12 17:35 UTC
#### Steps to reproduce the issue

1. Start with [Twenty Twenty-One](https://wordpress.org/themes/twentytwentyone/), [Twenty Twenty](https://wordpress.org/themes/twentytwenty/), or [Screenr](https://wordpress.org/themes/screenr/) as your active theme.
2. Ensure Jetpack is connected; if it isn't, connect it.
3. Ensure the "Display images in a full-screen carousel gallery" setting is enabled at Jetpack > Settings > Writing.
4. Create a new post from Posts > Add New
5. Add a Tiled Gallery block.
6. Pick at least 2 images to include in the Tiled Gallery.
7. Publish the post.
8. View the post and click an image to launch the full-screen carousel gallery.
9. Click the left or right arrow in the gallery to advance the images.

#### What I expected
The full-screen carousel should go through images within the gallery when you click the left or right arrow on screen. And the "X" in the top right should close out the full-screen carousel and go back to the post content.

#### What happened instead
What you'll see instead is that the image is bound to your mouse cursor. Moving your mouse will move the image horizontally. But the carousel gallery at this point is non-functional. Using left or right arrow keys sort of works (it advances between 2 images when there are more than 2 in the gallery but doesn't go through all of them).

If you take steps 2 through 9 with a theme like [Pique](https://wordpress.org/themes/pique/) or [Twenty Nineteen](https://wordpress.org/themes/twentynineteen/) active the full-screen carousel works as expected.

#### Context

Internal: p1628787040463600-slack-C0CMN0V97

**Comment by sdixon194** [comment] 2021-08-12 17:59
Thanks for reporting @andrewspittle! This sounds similar to [this JPOP issue](6793-gh-Automattic/jpop-issues).

Unfortunately it's proving difficult to reproduce. 

Are you able to reproduce this consistently on a fresh JN site? Or is this happening on a different self hosted site? Is it an issue across all devices and browsers, or localized to one machine/network?

[I spun up a site here](https://missing-hyena.jurassic.ninja/2021/08/12/test/) and the carousel works correctly for me with a tiled gallery, Twenty Twenty One and Twenty Twenty. Is the site causing issues for you, or does this work? 

Thanks!

**Comment by andrewspittle** [comment] 2021-08-12 18:23
The default themes seem more inconsistent in their behavior than Screenr. However, they consistently don't work for me. The carousel will load but then I can't click through images. The arrows don't bind the image to my cursor every time, though.

On your test site, for example, none of the buttons (left, right, X) work for me in either Chrome or Safari.

And here's a short screencast of my own fresh JN site running first Screenr and then Pique.

https://user-images.githubusercontent.com/86101/129248664-50181cc2-de2c-4167-930e-4114fb756e7e.mov

[This is the post](https://young-cephalopod.jurassic.ninja/2021/08/12/tiled-gallery-test/) I created on that JS site.

**Comment by sdixon194** [comment] 2021-08-12 18:48
> On your test site, for example, none of the buttons (left, right, X) work for me in either Chrome or Safari.

Yeah this sounds like that JPOP issue. So there are two issues here: the arrows/X not working at all which is what we're having trouble reproducing, and the issue of the mouse sticking to arrows. 

The mouse sticking I can definitely reproduce on Screenr, just not on Twenty-x themes. Tried running the beta on bleeding edge, since there were [some fixes included](https://github.com/Automattic/jetpack/pull/20599) set to release in 10.1, but no dice. 

Getting a few console errors too: 

> Uncaught TypeError: swiper.container is undefined
    <anonymous> https://missing-hyena.jurassic.ninja/wp-content/themes/screenr/assets/js/theme.js?ver=20120206:652

> Uncaught TypeError: e.zoom is undefined
    C https://missing-hyena.jurassic.ninja/wp-content/plugins/jetpack-dev/_inc/build/carousel/jetpack-carousel.min.js?ver=10.1-alpha:3

Looks like this might be an issue that needs to be addressed at the theme level, per @samiff's [find here on the theme forums](https://wordpress.org/support/topic/screenr-not-working-with-jetpack-9-9-slider/). 

cc @apeatling, not sure who from the old View team could take a look and see if this is something we need to address, or up to the theme.

**Comment by samiff** [comment] 2021-08-12 20:00
> Looks like this might be an issue that needs to be addressed at the theme level, per @samiff's find here on the theme forums.

Yes there does appear to be some needed changes at the theme level at least, for example it's casting a wide net on the `.swiper-container` class:

```
var swiper = new Swiper('.swiper-container:not(.elementor-image-carousel-wrapper)', {
```

One concern I had would be when Jetpack is calling in the swiper.js library, it seems that is surfaced at `window.Swiper`, which other themes may also reference (but be depending on different version). Is it possible this could cause conflicts, and could we avoid that some way?

cc: @glendaviesnz as well since I know you worked on the swiper portion quite a bit

**Comment by glendaviesnz** [comment] 2021-08-13 01:52
@samiff We could add a version number to the window.Swiper global as in this PR https://github.com/Automattic/jetpack/pull/20679 in order to prevent any conflicts with other plugins/themes that may be loading different versions of the library?

**Comment by glendaviesnz** [comment] 2021-08-13 01:55
> Yes there does appear to be some needed changes at the theme level at least, for example it's casting a wide net on the .swiper-container class:

Yeh, they shouldn't be expecting that every `.swiper-container` in the page is theirs. They should be targeting specific selectors as we are doing with Jetpack carousel, eg. `new window.Swiper( '.jp-carousel-swiper-container'`

**Comment by glendaviesnz** [comment] 2021-08-13 02:30
> [This is the post](https://young-cephalopod.jurassic.ninja/2021/08/12/tiled-gallery-test/) I created on that JS site.

This is strange, I wasn't able to replicate the issue on that site:

![swiper-bug](https://user-images.githubusercontent.com/3629020/129296583-854eb53a-21c0-4598-b35a-141713ffc14a.gif)

I wonder what is different about different setups that is causing this?

**Comment by samiff** [comment] 2021-08-13 18:26
> I was able to replicate the Screenr issue locally and with with the above PR applied it fixed the issue, so it does seem like it is an issue with clashes between different instances of swiperjs.

It won't fix the issue with Screenr in particular since we still have the `.swiper-container` class on our elements which is being caught up by their Swiper initialization. I'll drop a comment over on that theme support forum.

I do think it's still beneficial that we be explicit with our Swiper version usage, thanks for getting that PR up 👍 

I'll go ahead and close out this issue as we have a separate issue for tracking the unresponsive carousel nav some people are experiencing: 6793-gh-Automattic/jpop-issues

**Closed by samiff** 2021-08-13 18:26 UTC
Labels: [Type] Bug, Carousel, [Block] Tiled Gallery
