### ISSUE TITLE
Free vs premium block identification in block inserter

### ISSUE THREAD

**Issue by jeryj** [Automattic/jetpack#14626] opened 2020-02-10 20:46 UTC
* Identify ways to add the premium icon

**Comment by jeryj** [comment] 2020-02-10 20:49
- We can use classes in our icon path to color the featured symbol: `<paths class="featured-symbol">`. I was able to color a part of the Image block class this way.

<img width="393" alt="Mountain colored red on image icon" src="https://user-images.githubusercontent.com/967608/74188536-3d510c00-4c14-11ea-8fb6-b5bb7ac5445e.png">

**Comment by jeherve** [comment] 2020-02-10 21:13
Closing as duplicate of #11875

**Closed by jeherve** 2020-02-10 21:13 UTC
