### ISSUE TITLE
Widget Visibility on Taxonomy-sometaxname.php template

### ISSUE THREAD

**Issue by aous77** [Automattic/jetpack#3559] opened 2016-03-16 20:24 UTC
**What I expected**
can you please add this feature so we can control the visibility of widgets on a custom taxonomy archive page. 

**What happened instead**
right now all we get is the option to show a widget on a single post if that post belong to a certain taxonomy

**Steps to reproduce the issue**
1. create a custom taxonomy and lets call it "sampletax"
2. create a template for it and call it taxonomy-sampletax.php and make sure that it displays a sidebar (any existing sidebar)
3. add a widget to that sidebar and try to restrict the widget's visibilty to that taxonomy archive page only.

**Comment by jeherve** [comment] 2016-03-16 21:00
Closing as duplicate of #3020.

@aous77 You can try to apply the patch in #3288 to add that functionality to your site. Feel free to comment on the Pull Request if you have questions / remarks.

**Closed by jeherve** 2016-03-16 21:00 UTC
