### ISSUE TITLE
WP CLI Commands Not Working

### ISSUE THREAD

**Issue by ChaosExAnima** [Automattic/jetpack#1713] opened 2015-03-06 18:05 UTC
Summary of the issue: Using WP-CLI commands cause warnings and do not work.

Steps to reproduce:

Using wp-cli, type the following command: `wp jetpack module list`, or `wp jetpack module activate infinite-scroll`, or `wp jetpack disconnect blog`.

Version of wp-cli is 0.18.0, version of Jetpack is 3.3.2, pulled from Github as of 3/6/2015.

Expected behavior or result: The function works as expected, with no error messages.

Actual behavior or result: The command does not function, and error messages about having an invalid synopsis occur. Screenshot:

![screen shot 2015-03-06 at 1 03 18 pm](https://cloud.githubusercontent.com/assets/1760168/6530707/2e3077ba-c401-11e4-98f3-3dbb4db7cb13.jpg)

**Comment by jeherve** [comment] 2015-03-06 18:41
Closing as duplicate of #1175

**Closed by jeherve** 2015-03-06 18:41 UTC
