### ISSUE TITLE
Weird iframe after the update

### ISSUE THREAD

**Issue by emiluzelac** [Automattic/jetpack#1840] opened 2015-03-23 00:01 UTC
Hi folks,

Few moments ago I've upgraded the Jetpack and all went well:

```
Update Plugin
Downloading update from https://downloads.wordpress.org/plugin/jetpack.3.4.1.zip…

Unpacking the update…

Installing the latest version…

Removing the old version of the plugin…

Plugin updated successfully.
```

However just under this Jetpack page showed up in an iframe: `/wp-admin/admin.php?page=jetpack`

![screen shot 2015-03-22 at 6 24 05 pm](https://cloud.githubusercontent.com/assets/1784526/6772186/b2c03134-d0c5-11e4-8530-5b18c32edbda.png)

Thanks!

Cc: @georgestephanis

**Comment by kraftbj** [comment] 2015-03-23 01:07
Taking a bit of a stab in the dark. Perhaps something tied onto the `upgrader_process_complete` action or the output buffer having the JP stored (by way of the upgrader firing `$this->skin->footer();`

```
	public function footer() {
		$output = ob_get_contents();
		if ( ! empty( $output ) )
			$this->feedback( $output );
		ob_end_clean();
	}```

**Comment by kraftbj** [comment] 2015-03-23 02:59
No real determination of cause, but here's where it is coming from on the WP level:
Could duplicate it with the single plugin installer (via Plugins->Installed Plugins-> Upgrade on the JP line item).

Loading: `<iframe style="border:0;overflow:hidden" width="100%" height="170px" src="update.php?action=activate-plugin&amp;networkwide&amp;plugin=jetpack%2Fjetpack.php&amp;_wpnonce=xxxxx"></iframe>`

Via the bulk updated (Dashboard->Updates->check JP & Update), it does not load.

Looking, it's the iframe that is called by https://core.trac.wordpress.org/browser/trunk/src/wp-admin/includes/class-wp-upgrader-skins.php#L172

The iframe itself should just output "Plugin reactivated successfully" ( https://core.trac.wordpress.org/browser/trunk/src/wp-admin/update.php#L82 ), but then includes the plugin file at https://core.trac.wordpress.org/browser/trunk/src/wp-admin/update.php#L90

**Comment by emiluzelac** [comment] 2015-03-23 03:21
Thanks Brandon 😀

**Comment by samhotchkiss** [comment] 2015-04-21 00:02
Seems to be fixed by #1984, I can't reproduce now

**Comment by jeffgolenski** [comment] 2015-04-23 19:25
Still seeing it upon upgrade to 3.5: 

https://cloudup.com/cHhRxVe0cYd

**Comment by jeffgolenski** [comment] 2015-04-29 18:25
Haven't been able to reproduce since all of my sites are 4.2.x, closing!

**Closed by jeffgolenski** 2015-04-29 18:25 UTC
Labels: bug, General
