### ISSUE TITLE
Bug: failed to load resource on loading posts

### ISSUE THREAD

**Issue by EllieKennard** [Automattic/jetpack#3383] opened 2016-02-08 13:19 UTC
I see this bug when viewing posts. http://stevenkennard.com/blog/
![error](https://cloud.githubusercontent.com/assets/17123364/12886578/c81cb43a-ce44-11e5-9555-b718eccf709b.PNG)

Failed to load resource: the server responded with a status of 404 (Not Found)send @ s0.wp.com/wp-includes/js/jquery/jquery.js?ver=20151215:1

I am just a user, not technical at all but am told this is a bug to be reported here. Thanks!

**Comment by jeherve** [comment] 2016-02-08 13:24
Thanks for the report.

I can't seem to be able to reproduce the issue right now. Could you let me know if the problem remains when using a different browser, and when logging out of your account?

Thanks!

**Comment by EllieKennard** [comment] 2016-02-11 00:34
I'm not sure how to tell if it's there on other browsers. I see it easily on Chrome.

**Comment by jeherve** [comment] 2016-02-11 09:35
I tested in Chrome, Firefox, and Safari, but could not reproduce.

Does it happens when logged out of your WordPress account as well?

**Comment by jeherve** [comment] 2016-03-14 15:24
Closing this. Do not hesitate to comment again if you still experience issues.

**Closed by jeherve** 2016-03-14 15:24 UTC
Labels: General, [Status] Needs Author Reply
