### ISSUE TITLE
JetPack Breaks Site 100%

### ISSUE THREAD

**Issue by KipperedSnack** [Automattic/jetpack#9344] opened 2018-04-18 13:49 UTC
I am using the latest release of Wordpress and Jetpack plugin.

I am on 1and1 shared hosting. My site runs 100% fine, until I enable Jetpack.

Then it slows to a crawl, to the point where its unusable. I have to manually kill PHP and disable the plugin.

I have disabled all modules in Jetpack, and even tried the CSS @font-face bug mentioned here. No avail.

Jetpack literally appears to be 100% useless with 1and1.com

Advice? Site literally won't even finish loading with Jetpack enabled. Which I need for WooCommerce Services USPS integration.

You can view the site here: https://www.hobbyhomebrew.com

I will leave Jetpack enabled so you all can suffer the same I have for weeks.

**Comment by kraftbj** [comment] 2018-04-18 14:47
Are there any PHP or server error logs that you could share? Is Jetpack currently enabled? It isn't running slow for me right now.

Please, if you could send any relevant log entries via https://jetpack.com/contact-support/?rel=support , we can help isolate the issue in private until there's a confirmed bug.

I'm closing this issue since there isn't enough to confirm a bug and it is best handled as a support issue until then. Thank you!

**Closed by kraftbj** 2018-04-18 14:47 UTC
