### ISSUE TITLE
Generated content duplicates existing content when there is no title

### ISSUE THREAD

**Issue by vianasw** [Automattic/jetpack#39436] opened 2024-09-18 13:04 UTC
For some reason, when I tried to use an action like “continue writing” after a paragraph when there is no title, the generated content copies the first paragraph. I replicated a couple of times but would be good if someone else can verify it.

![Image](https://github.com/user-attachments/assets/4efdc4fc-dc7a-4211-a323-f922bfd4a531)

**Comment by lhkowalski** [comment] 2024-09-25 18:59
I could not replicate this behavior. Maybe it was a hiccup or a model change we did, but I tried with multiple content on both Jetpack and Simple sites, and got the exepcted behavior: the assistant continues to write the new content after the previous paragraph without duplicating it.

**Comment by lhkowalski** [comment] 2024-09-25 19:07
Moved to "On hold" while we confirm the replication steps.

**Comment by lhkowalski** [comment] 2024-09-27 20:43
Closing because the problem is probably gone, I can't replicate it.

**Closed as not planned** 2024-09-27 20:52 UTC
Labels: [Extension] AI Assistant Plugin
