### ISSUE TITLE
vimeo width and height set to 0 and shortcode attributes not being used

### ISSUE THREAD

**Issue by gustavo-orellana4tu** [Automattic/jetpack#3510] opened 2016-03-04 15:21 UTC
#### What I expected
Adding a vimeo URL or a vimeo shortcode should display a video on the page.
#### What happened instead
Nothing shows. Inspecting the place where the video should be shows the iframe width and height set to zero.
#### Steps to reproduce the issue
Create/open post and add vimeo url in any format:
https://vimeo.com/154708719
[vimeo https://vimeo.com/154708719]
[vimeo 154708719 h=400&w=300]
[vime 154708719 width=300 height=400]

The video not showing happened in the latest jetpack update.
 Width and height set to 0 in the latest update to plugins/jetpack/modules/shortcodes/vimeo.php, 
function vimeo_shortcode( $atts )
Note: $atts only contains the URL, it does not have the shortcode attributes.
I also noticed that in the file's comments you guys say that you can specify width and height in the shortcode. However, I looked at the code and did some var_dumps here and there, and it doesn't look like you are using the shortcodes attributes at all. You are only using the $url.

**Comment by jeherve** [comment] 2016-03-04 15:31
I can't seem to be able to reproduce the issue on my end:

![screen shot 2016-03-04 at 4 27 44 pm](https://cloud.githubusercontent.com/assets/426388/13531284/13a5bb6e-e226-11e5-8244-ee16ee199bca.png)

![a133f113-4df1-4945-8dce-b2d240a78dbe](https://cloud.githubusercontent.com/assets/426388/13531275/01a4b21c-e226-11e5-8b10-f35cc992c87e.png)

Could you try to apply the patch in #3497, and let me know if it helps?

> it doesn't look like you are using the shortcodes attributes at all. You are only using the $url.

All the attributes can be used. Most of them are added to the URL itself before the iFrame is created:
https://github.com/Automattic/jetpack/blob/3.9.2/modules/shortcodes/vimeo.php#L126
https://github.com/Automattic/jetpack/blob/3.9.2/modules/shortcodes/vimeo.php#L134

The width and width, on the other hand, are added to the iFrame attributes here:
https://github.com/Automattic/jetpack/blob/3.9.2/modules/shortcodes/vimeo.php#L137

**Comment by gustavo-orellana4tu** [comment] 2016-03-04 15:51
Why did you guys set the default width and height to 0 in the new update?
$attr = array_map(
                'intval',
                shortcode_atts(
                        array(
                                'id'       => 0,
                                'width'    => 0,//Gustavo: previous to update, this was 400
                                'height'   => 0,//Gustavo: previous to update, this was 300
                                'autoplay' => 0,
                                'loop'     => 0,
                        ), $atts
                )
        );
The latest update we got doesn't have that patch you suggest ( to set the width if $content_width) is not set, which is why it's probably working for you. For now, I'm just making use of the filters to set width and height, until a new update comes with fixes.

**Comment by jeherve** [comment] 2016-03-04 15:57
> Why did you guys set the default width and height to 0 in the new update?

We made that change in 6dc128d1ec36a6e5359b98ebc6cbb079582b9115, because the defaults are then set later depending on your theme.

Unfortunately, it looks like your theme doesn't include a `$content_width` value, and thus never sets a default. That's what #3497 will address. It will be included in the next release.

Until then, and if you'd rather not edit Jetpack files until the update, the filters should indeed help! Another solution would be to be to add a `$content_width` value to your theme, as explained here:
https://codex.wordpress.org/Content_Width

**Closed by jeherve** 2016-03-04 15:57 UTC
Labels: Shortcodes, [Status] Needs Author Reply

**Comment by gustavo-orellana4tu** [comment] 2016-03-04 16:06
Thanks!
One more,
Defining the width (or w) and height (or h)  in the shortcode does not work for me.
I dump the $atts parameter in function vimeo_shortcode( $atts ) and it only contains the URL. That's why I have to rely on the filters. Do you have any idea what's going on here?

**Comment by jeherve** [comment] 2016-03-04 16:14
Would you happen to be running another shortcode plugin on your site, that may overwrite Jetpack's Vimeo shortcode?

**Comment by gustavo-orellana4tu** [comment] 2016-03-04 17:07
There is no other shortcode plugin.
It looks like wpcom_vimeo_embed_url is being called first and it's just passing a URL to function vimeo_shortcode($atts). So, width and height and any other attribute never makes it to the shortcode function.

wpcom_vimeo_embed_url( $matches, $attr, $url ) {
        return vimeo_shortcode( array( $url ) );
}

**Comment by jeherve** [comment] 2016-03-04 17:16
That function is only used for bare URLs on their own line.

Width and height attributes are properly returned on my end. Here is what I get for the 4 videos we tested earlier:
```
string(40) "https://player.vimeo.com/video/154708719" int(940) int(529)
string(40) "https://player.vimeo.com/video/154708719" int(940) int(529)
string(40) "https://player.vimeo.com/video/154708719" int(300) int(400)
string(40) "https://player.vimeo.com/video/154708719" int(300) int(400)
```

Could you apply the patch from #3497, and let me know the results you get?

**Comment by gustavo-orellana4tu** [comment] 2016-03-04 17:36
Adding $content_width to functions.php works.
Adding the patch to set width if $content_width is not defined also works.

Only thing not working is just not being able to set width and height in shortcode. That function is being used even if it's not a bar URL.

I put this in function vimeo_shortcode($atts) : 
echo "vimeo_shortcode: \$atts: ";
var_dump($atts); echo "DONE.<br/><br/>";

And I put ths in function wpcom_vimeo_embed_url( $matches, $attr, $url )  : 
echo "wpcom_vimeo_embed_url: \$attr:";   
var_dump($attr);
echo "<br/>\$url: $url DONE<br/><br/>";

OUTPUT:
wpcom_vimeo_embed_url: $attr:array(2) { ["width"]=> int(500) ["height"]=> string(3) "100" } 
$url: https://vimeo.com/150594088 DONE

vimeo_shortcode: $atts: array(1) { [0]=> string(27) "https://vimeo.com/150594088" } DONE.

wpcom_vimeo_embed_url: $attr:array(2) { ["width"]=> int(500) ["height"]=> string(3) "100" } 
$url: https://vimeo.com/150594088 DONE

vimeo_shortcode: $atts: array(1) { [0]=> string(27) "https://vimeo.com/150594088" } DONE.

wpcom_vimeo_embed_url: $attr:array(4) { ["width"]=> int(200) ["height"]=> int(100) ["w"]=> string(3) "200" ["h"]=> string(3) "100" } 
$url: https://vimeo.com/156684127 DONE

vimeo_shortcode: $atts: array(1) { [0]=> string(27) "https://vimeo.com/156684127" } DONE.

**Comment by jeherve** [comment] 2016-03-04 18:12
I got a different output on my end. `wpcom_vimeo_embed_url` was only used for the first video:

```
wpcom_vimeo_embed_url: $attr:array(2) { ["width"]=> int(940) ["height"]=> int(1000) } 
$url: https://vimeo.com/154708719 DONE

vimeo_shortcode: $atts: array(1) { [0]=> string(27) "https://vimeo.com/154708719" } DONE.

vimeo_shortcode: $atts: array(1) { [0]=> string(27) "https://vimeo.com/154708719" } DONE.

vimeo_shortcode: $atts: array(2) { [0]=> string(9) "154708719" ["h"]=> string(9) "400&w=300" } DONE.

vimeo_shortcode: $atts: array(3) { [0]=> string(9) "154708719" ["width"]=> string(3) "300" ["height"]=> string(3) "400" } DONE.
```

**Comment by jeherve** [comment] 2016-03-04 18:13
Could you let me know what other plugins are currently installed on your site, so I can try to reproduce?

**Comment by gustavo-orellana4tu** [comment] 2016-03-04 18:46
Jetpack is the only one.
Wordpress 4.4.2
PHP 5.5.9
system:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"

![image](https://cloud.githubusercontent.com/assets/14984695/13536621/07c32672-e20f-11e5-96ad-49ab7378f12e.png)

**Comment by jeherve** [comment] 2016-03-04 18:47
Does switching to one of the default themes, like Twenty Fifteen, change anything?

**Comment by gustavo-orellana4tu** [comment] 2016-03-04 18:54
Changed to Twenty Sixteen and I can see the videos now. The custom theme is the problem. I will take a closer look to figure out where the attributes are being removed.
Thank you Jeremy!
