### ISSUE TITLE
Search: & symbol converted to &amp in search results

### ISSUE THREAD

**Issue by kylemcph** [Automattic/jetpack#18148] opened 2020-12-18 15:53 UTC
#### Steps to reproduce the issue

1. First ensure the “Jetpack (Search)” widget settings have Posts, Pages, and Media checked for “Post types to search.”
2. Create a page or post with the `&` symbol
3. Search for a query that will find that particular page or post
4. See `&amp;` instead of `&`

#### What I expected

To see the proper page / post title.

#### What happened instead

& was converted to &amp; 

This was first noticed on the WordPress.com support docs when searching for Media Text looking for the Media & Text block.
https://en.support.wordpress.com/?s=media%20text

It was also replicated on a WordPress.com simple site with Jetpack Search enabled, Twenty Twenty theme. 

**Screenshots**

WordPress.com support forum: 

![](https://d.pr/i/y7t1YV+)
Direct link to image: https://d.pr/i/y7t1YV

---

Test site with Twenty Twenty theme: 

![](https://d.pr/i/BPzR8I+)
Direct link to image: https://d.pr/i/BPzR8I

---

I tested with a few other characters but was only able to replicate with the `&` symbol.

**Comment by gibrown** [comment] 2020-12-18 16:50
Thanks duplicate of https://github.com/Automattic/jetpack/issues/18044 so going to close this one.

**Closed by gibrown** 2020-12-18 16:50 UTC
Labels: Involves Happiness, Search, [Type] Happiness Request
