### ISSUE TITLE
Video: show plan storage indicator in settings

### ISSUE THREAD

**Issue by rickybanister** [Automattic/jetpack#6742] opened 2017-03-24 15:41 UTC
We have a storage indicator component in Calypso. I'd like to see us make that available in dops-components so that we can display a video storage indication in the /settings/writing/video card once activated. 

<img width="1001" alt="screen shot 2017-03-24 at 11 38 46 am" src="https://cloud.githubusercontent.com/assets/437258/24301725/b6aeb772-1086-11e7-8205-f74d4070560e.png">

cc @aheckler @dbtlr @MichaelArestad

**Comment by jeherve** [comment] 2017-03-27 13:59
Closing as duplicate of #6003 (I'll bring your screenshot there).

**Closed by jeherve** 2017-03-27 13:59 UTC
Labels: [Type] Enhancement
