### ISSUE TITLE
SSO: Provide better error message when attempting login with unactivated account

### ISSUE THREAD

**Issue by hoverduck** [Automattic/jetpack#7761] opened 2017-09-06 17:25 UTC
#### Steps to reproduce the issue
1) Create a new wpcom account, but do not click the Activation link in the e-mail
2) Connect a Jetpack site to the new account
3) Enable SSO
4) Attempt to SSO

#### What I expected
To be able to SSO, or have an error tell me why it didn't work

#### What happened instead
A generic error `There was an error logging you in via WordPress.com, please try again or try logging in with your username and password.` is given.

I spent _waaaay_ too much time troubleshooting this and trying to figure out why I couldn't sign on before I realized that it was just because I'd never activated my account.

**Comment by rachelmcr** [comment] 2018-02-26 12:53
+1 to this. I have been running into this while testing Jetpack connection flows, and I didn't realize the cause until I found this issue. I found it especially confusing in this scenario:

1. Sign up with a partner host.
2. Follow the prompts to set up Jetpack (before logging in to WP Admin).
3. Finish the Jetpack connection flow, which sends you back to WP Admin.

In that flow, you never see a prompt to activate your WordPress.com account and when you are sent to WP Admin you see a prominent SSO login button. It fails inexplicably, and if your site is new you don't necessarily know your WP Admin credentials (but if you signed up for WordPress.com during the Jetpack connection flow, you might have those credentials handy and not understand why they don't work in WP Admin).

It's a really confusing flow for a brand new WordPress customer.

**Comment by ebinnion** [comment] 2018-03-07 22:26
Fixed with r171325-wpcom. Now, if the user is unverified and tries to SSO, they will see a notice telling them to verify on WordPress.com and they will not be redirected to the site.

Screenshot below:

![sso-example](https://user-images.githubusercontent.com/1126811/37121942-5a8a7926-2224-11e8-98ad-6d712b2c7e69.png)

**Closed by ebinnion** 2018-03-07 22:26 UTC
Labels: FixTheFlows, SSO, [Pri] Low, [Status] Needs Copy, [Type] Enhancement
