### ISSUE TITLE
Enhancement: Mailchimp Block – Double Opt-in Support

### ISSUE THREAD

**Issue by asafm7** [Automattic/jetpack#32406] opened 2023-08-10 18:26 UTC
### Impacted plugin

Jetpack

### What

Mailchimp Block – Double Opt-in Support

### How

Does the Mailchimp Block support double opt-in?

According to my testing, it doesn't.

A different text message would also be needed ("A confirmation email was sent...")

**Comment by jeherve** [comment] 2023-08-14 10:33
> According to my testing, it doesn't.

Could you walk us through the steps you followed to test this, so we can try to reproduce?

Thank you.

**Comment by jeherve** [comment] 2024-11-20 08:32
Closing as duplicate of #14828

**Closed as completed by jeherve** 2024-11-20 08:32 UTC
Labels: [Closed] Duplicate, Enhancement, [Block] Mailchimp, [Plugin] Jetpack, [Feature] Mailchimp
