### ISSUE TITLE
Block Editor: console error "Cannot read property 'jetpack' of undefined"

### ISSUE THREAD

**Issue by kwight** [Automattic/jetpack#11730] opened 2019-03-27 20:36 UTC
#### Steps to reproduce the issue

1. Open the devtools console.
2. Load `/wp-admin/post-new.php` with the block editor active.
3. See the console error `post-new.php:323 Uncaught TypeError: Cannot read property 'jetpack' of undefined`.

<img width="1180" alt="Screen Shot 2019-03-27 at 1 31 39 PM" src="https://user-images.githubusercontent.com/349751/55110173-b3985e80-5094-11e9-96f3-097caa51d822.png">

**Comment by jeherve** [comment] 2019-03-27 20:58
Closing as duplicate of #11722

**Closed by jeherve** 2019-03-27 20:58 UTC
Labels: Gutenberg, Internationalization, [Type] Bug, [Type] Duplicate
