### ISSUE TITLE
Review all text on the new connection banner

### ISSUE THREAD

**Issue by samhotchkiss** [Automattic/jetpack#5676] opened 2016-11-16 22:36 UTC
![image](https://cloud.githubusercontent.com/assets/574752/20368659/387caf04-ac12-11e6-9b71-a7d3c7838ae2.png)

cc: @richardmuscat @jessefriedman @beaulebens

**Comment by jeherve** [comment] 2016-11-17 09:32
Closing as duplicate of #5623

**Closed by jeherve** 2016-11-17 09:32 UTC
Labels: General, [Pri] High
