### ISSUE TITLE
JetPack Comments: Can't login with Facebook in IE9

### ISSUE THREAD

**Issue by TwisterMc** [Automattic/jetpack#1063] opened 2014-08-29 17:42 UTC
We have a site going through QA and some are not able to login via Facebook in IE9. I've tried this with my Facebook account and it works fine. However, they continue to have failures.

Steps to reproduce:
1. Visit a self hosted blog running JetPack in IE9 Example: http://blog.nerdery.com/2014/08/the-ten-most-notable-features-of-ios-8-infographic/
2. Scroll down to the comments and login with Facebook
3. See the issue. https://cloudup.com/ct8iEeuHu15 (except it'd say Facebook)

This is much like issue #1040 only with Facebook and I can't reproduce it, but 4 of my QA devs can.

**Comment by samhotchkiss** [comment] 2015-11-06 06:46
Is anyone else able to reproduce this issue?  @jeherve, have we had other reports?

**Comment by jeherve** [comment] 2015-11-06 17:37
No other reports, but I'd guess that it's because the people experiencing the issue are most likely not the same people who would actually report it to us.

I was able to reproduce on my end. I saw no JS errors, just the endless login message @TwisterMc mentioned.

**Comment by TwisterMc** [comment] 2015-11-06 18:53
Since this was opened in 2014, I'm guessing a lot has changed with Facebook and JetPack since then and maybe it's a non-issue. I don't currently have any projects that I can test with to see if the issue still exists.

**Comment by jeherve** [comment] 2017-03-21 10:04
Closing as we do not support IE9 anymore.

**Closed by jeherve** 2017-03-21 10:04 UTC
Labels: Comments, [Type] Bug
