### ISSUE TITLE
Jetpack causes "internal server error" in WP All Export

### ISSUE THREAD

**Issue by flukefox** [Automattic/jetpack#7712] opened 2017-08-29 18:46 UTC
#### Steps to reproduce the issue

After finding out that WP All Export conflicted with the login (the 1000 millisecond timeout error reported here in 2016) I deactivated WP all Export in order to login to Jetpack.

After this successfully worked I reactivated WP All Export and it appeared to be still connected and functional.

#### What I expected

I export weekly orders through WP All Export so I can make delivery sheets out of them for drivers.
I should have been able to use WP All Export as per usual by using the plugin. I would do this by entering a New export or by Managing Exports that I already created.

#### What happened instead

Instead of showing the total of orders being exported for the week, I instead received a notice in the plugin saying "internal server error" . WP All Export successfully worked, immediately after disabling Jetpack....

Hopefully this gets fixed as I really like Jetpack, but I'm not going to be able to use it since the main functionality my site requires is broken by this plugin.

**Comment by jeherve** [comment] 2017-09-08 13:14
Unfortunately that is a known issue. Closing as duplicate of #5802.

**Closed by jeherve** 2017-09-08 13:14 UTC
