### ISSUE TITLE
Calendly block scrolls

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#15358] opened 2020-04-07 20:33 UTC
#### Steps to reproduce the issue

1. Create calendly block e.g. for https://calendly.com/dan-walmsley/online-business-zoom?back=1&month=2020-04
2. Look in front end
3. Block is scrolling (at least on my instance) and needs explicit height set.

#### What I expected

Block stretches to necessary length to avoid scrolling.

#### What happened instead

Block has internal scroll bar, which looks kind bad on desktop browsers and really messes with interaction on phones.

**Screenshots**

<img width="728" alt="iframe-border" src="https://user-images.githubusercontent.com/51896/78717674-d713fd00-78d5-11ea-9b93-ff6ee85f8d3f.png">

**Comment by jeherve** [comment] 2020-04-08 08:16
Closing as duplicate of #14566

**Closed by jeherve** 2020-04-08 08:16 UTC
Labels: [Block] Calendly, [Type] Bug
