### ISSUE TITLE
Publicize: Support Instagram 

### ISSUE THREAD

**Issue by htdat** [Automattic/jetpack#13776] opened 2019-10-18 08:48 UTC
#### Is your feature request related to a problem? Please describe.

It would be nice if we can add Instagram to Publicize. 

I've seen a few tickets but we have not had any tracking issue yet so here it is! 

2428533-zen

**Comment by jeherve** [comment] 2019-10-18 08:53
Closing as duplicate of #1870

**Closed by jeherve** 2019-10-18 08:53 UTC
Labels: Publicize, [Type] Feature, [Type] Happiness Request

**Comment by htdat** [comment] 2019-10-21 02:55
Thanks Jeremy, I just looked for open issues!
