### ISSUE TITLE
Jetpack has locked your site's login page.

### ISSUE THREAD

**Issue by PC-HelpZA** [Automattic/jetpack#10035] opened 2018-08-18 07:18 UTC
The IP address of my server has been used (by someone else) for something to cause blacklisting at some SBL's however that has been resolved and the blacklisting has been cleared.
However when I try to login on hedge.pc-help.co.za/wp-admin I get the message still Jetpack has locked your site's login page.

Could the IP 192.185.129.96 please be whitelisted again?

**Comment by abidhahmed** [comment] 2018-08-20 03:12
Hi there,

Having your IP blacklisted by some SBL's will not cause Jetpack to block you from logging in; it's usually caused by many failed log-in attempts directly made on your site.

Could you please follow the steps mentioned below to unblock/whitelist yourself and see if it works?
https://jetpack.com/support/security-features/#unblock

Do let us know an update on how it goes, thanks a bunch!

**Comment by VR51** [comment] 2018-08-23 17:12
Adding to this issue because it is a common fault. I am not associated with the OP.

I have had many reports of the same problem from multiple customers over the past 6 months or more. The IP detected by Protect is often not the real IP address of the site member at the time Protect blocks a login attempt made by a legitimate admin user. The blocked login attempt email, with recovery information, always (literally speaking) reports a different IP address to that detected by Google or other 'What's my IP?' services.

We use Cloudflare on all sites so could be that Protect is getting the real IP address too late for it to determine whether or not a login attempt is genuine.

I have begun to disable Protect in sites that show false positives. Switched to WP Bruiser instead. The same problem is not present for WP Bruiser.

**Comment by abidhahmed** [comment] 2018-08-24 09:28
@VR51 

Thanks for the feedback, and sorry to hear that Protect isn't working as expected.

If possible, could you let me know a sample IP address that was reported by Jetpack? We're looking into this issue and any further info would be very helpful. Thanks!

I believe #8322 is slightly interlinked to a similar issue.

**Comment by VR51** [comment] 2018-08-24 10:32
I do, oddly enough. A small selection:

`108.162.237.134
172.68.47.160
172.69.33.42
172.69.33.69
173.245.48.61
174.213.13.241`

**Comment by abidhahmed** [comment] 2018-08-24 10:57
Thanks for the IPs! All of them except the last belongs to CloudFlare - this could indicate a problem with Protect with it being unable to detect proper `X-Forwarded-For` headers or the header itself isn't correctly set.

We're looking into it and will keep you posted. Thanks again.

**Comment by VR51** [comment] 2018-08-24 13:01
You're welcome.

I thought that might be the issue. All these sites use Cloudflare with the Cloudflare (official) plugin installed.

**Comment by VR51** [comment] 2018-08-29 13:01
Thanks @abidhahmed. It is a nice offer but I won't take it up. I will continue to use alternatives to Protect in sites where Protect exhibits the fault.

**Comment by abidhahmed** [comment] 2018-08-29 13:10
That's a bummer, but we'd love to get you back on Protect @VR51 ~ in case you change your mind, do reach out.

We'll continue to investigate and see if this is a problem, and we'll update accordingly.

**Comment by jeherve** [comment] 2018-09-05 13:06
@VR51 We would need to know more about the sites where you are having this issue in order to run more tests. Without more information, we won't be able to confirm what is happening.

Could you contact us via the form linked to above so we can take a closer look? Thank you.

Until we know more, I will close this issue.

**Closed by jeherve** 2018-09-05 13:06 UTC
Labels: Protect, [Status] Needs Author Reply, [Type] Bug
