### ISSUE TITLE
Gallery: Image attachment page stretches pictures

### ISSUE THREAD

**Issue by suyogyashukla** [Automattic/jetpack#12148] opened 2019-04-24 18:59 UTC
#### Steps to reproduce the issue

- Add a gallery block in a post/page.
- Choose any Style from the block settings.
- Under linked to, choose "Attachment Page" https://cld.wthms.co/z4wgiv

#### What I expected

- The images to show up without getting stretched on the attachment page.

#### What happened instead

- The images were stretched on the attachment page. 

#### Debugging

The `.jp-carousel-slide img` is set to display the images at 100% height and width. This can be solved by setting it to `auto` and adding `margin: 0 auto;` should fix this. 

#### Other info:

- This seems to happen only when the gallery style is set to either "Circle" or "Square tiles"
- You can see this happening on my test site: https://jetpackgallerytesting01245.wordpress.com/2019/04/24/jetpack-gallery-test/
- I'm using Brave browser Version 0.62.51 Chromium: 73.0.3683.103 (Official Build) (64-bit)
- Here is a quick video demonstrating the issue: https://cld.wthms.co/ANqVjQ

**Comment by jeherve** [comment] 2019-04-24 19:08
Could you add some screenshots, as well as some information about the gallery type you chose, and the browser you were using?

Thank you!

**Comment by jeherve** [comment] 2019-04-24 19:08
Possibly related: #11150

**Comment by suyogyashukla** [comment] 2019-04-24 19:19
My bad! Added more info. @jeherve

**Comment by jeherve** [comment] 2019-04-24 19:38
> This seems to happen only when the gallery style is set to either "Circle" or "Square tiles"

Closing as duplicate of #11150

**Closed by jeherve** 2019-04-24 19:38 UTC
Labels: Carousel, [Type] Duplicate
