### ISSUE TITLE
Jetpack Dash Logo/Icon is blank in wp-admin

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#8330] opened 2017-12-07 01:40 UTC
This seems to only happen on an upgraded plan (only tested with Pro). On my free sites, the logo appears correctly. On two different pro sites, I see:

<img width="872" alt="screen shot 2017-12-06 at 6 38 03 pm" src="https://user-images.githubusercontent.com/820871/33694308-a9d0876c-dab4-11e7-8a9f-601c9d9af7d2.png">

That is from /wp-admin/admin.php?page=jetpack#/dashboard Happens no matter which wp-admin page I am on.

**Comment by Viper007Bond** [comment] 2017-12-07 02:14
I ran into the same issue. A hard refresh fixed it for me.

**Comment by jeherve** [comment] 2017-12-07 08:45
Closing as duplicate of #8312

**Closed by jeherve** 2017-12-07 08:45 UTC
Labels: Admin Page, [Pri] High, [Type] Bug
