### ISSUE TITLE
Copy a Post: Feature not working correctly in /wp-admin with Firefox on Windows

### ISSUE THREAD

**Issue by SiobhyB** [Automattic/jetpack#14879] opened 2020-03-04 11:47 UTC
The copy a post feature doesn't appear to be working correctly in /wp-admin with Firefox on Windows.

This was reported to us in 2755991-zen by a user who frequently uses the feature. They're on Windows 10 and noticed the issue this past weekend (Saturday February 29th and Sunday March 1st). They're able to use the feature from Calypso.

@kriskorn confirmed in p1583318050039400-slack-windows that he was able to replicate the issue on Firefox on his Windows device. He wasn't able to use the feature in either /wp-admin or Calypso. The feature worked as expected for Kris in Chrome and Edge.
 
The feature also works as expected for me if I test in both Chrome and Firefox on my Mac. 

The issue, therefore, appears to be specific to Firefox and Windows devices.

#### Steps to reproduce the issue

1. Go to _Posts_ → _All Posts_ in your site's /wp-admin area.
2. Hover over any posts and click on **Copy**.

#### What I expected

I expected to be taken to the post editor, with a copy of the contents of the post I'd selected and the ability to edit that content before publishing the new post.

#### What happened instead

In Firefox on Windows, it appears that users are taken to a blank white page instead of a post editor.

**Comment by jeherve** [comment] 2020-03-04 11:54
> In Firefox on Windows, it appears that users are taken to a blank white page instead of a post editor.

@kriskorn Are you able to reproduce on a Jetpack site?

Do you think you could also check for JavaScript errors on the blank page that loads?

Thanks!

**Comment by kriskorn** [comment] 2020-03-04 13:27
> > In Firefox on Windows, it appears that users are taken to a blank white page instead of a post editor.
> 
> @kriskorn Are you able to reproduce on a Jetpack site?
> 
> Do you think you could also check for JavaScript errors on the blank page that loads?
> 
> Thanks!

@jeherve Cannot reproduce on self-hosted site with Jetpack activated. Works well. 
However, using WP Admin or Calypso in WordPress.com shows the below results.

WP Admin: 

<img width="972" alt="wp-admin" src="https://user-images.githubusercontent.com/12064241/75883822-51abb180-5e2c-11ea-9fcf-0916b398337f.PNG">

Calypso:

<img width="970" alt="calypso" src="https://user-images.githubusercontent.com/12064241/75883828-5708fc00-5e2c-11ea-961a-6e79d096e368.PNG">

Could not find anything weird in Console nor in Network tabs. 
At least the status for each resource was 200. 

Let me know if I should check something else. :)

**Comment by jeherve** [comment] 2020-03-04 15:07
@kwight Do you think you could take a look? I am not sure what's special about wpcom here that could impact Copy Post?

**Comment by kwight** [comment] 2020-09-01 16:54
Hm, I can't think of anything that was browser- or platform-specific, but I'll try and take a look.

**Comment by blackjackkent** [comment] 2020-09-03 19:09
I tested this with a WPCom site and could not reproduce the issue. I was navigated as expected to the post editing screen.

![image](https://user-images.githubusercontent.com/13437011/92156639-e8aef180-edee-11ea-9c3d-ca8645ddc9dc.png)

![image](https://user-images.githubusercontent.com/13437011/92156717-054b2980-edef-11ea-8e7d-c7a00b3e4f73.png)

**Comment by kwight** [comment] 2020-09-03 20:16
Closing – may have been Gutenberg-related and fixed since. Thanks for the double-check @blackjackkent ! ❤️

**Closed by kwight** 2020-09-03 20:16 UTC
Labels: Copy a Post, [Type] Bug, [Type] Happiness Request
