### ISSUE TITLE
Auto-publish: Add instagram capabilities

### ISSUE THREAD

**Issue by AjkP** [Automattic/jetpack#11134] opened 2019-01-13 00:35 UTC
I want this added because instagram is a great way to connect with users / followers. An easy way to autopublish in instagram should be useful

#### Steps to reproduce the feature wanna-be

1. Got to jetpack settings
2. Go to sharing tab
3. Enable `Automatically share your posts to social networks`
4. Click on `Connect your social media accounts`

#### What I expected

- Instagram is one of the social medias supported

#### What happened instead

Im stuck with tumblr :P

**Comment by jeherve** [comment] 2019-01-14 10:22
That is unfortunately not an option right now, for the reasons highlighted in #1870.

I'll close this issue as duplicate of #1870.

**Closed by jeherve** 2019-01-14 10:22 UTC
Labels: Publicize, [Type] Duplicate
