### ISSUE TITLE
Search field icon overlays inline notifications

### ISSUE THREAD

**Issue by mattyza** [Automattic/jetpack#5057] opened 2016-09-01 11:05 UTC
#### Steps to reproduce the issue
- Using Jetpack 4.3 beta.
- Scroll your screen such that the search form is near the top-right corner of the window.
- Toggle something to trigger a top-right corner notification.

#### What I expected
I expected the notification to overlay all elements, including the search form icon.

#### What happened instead
![image](https://cloud.githubusercontent.com/assets/880803/18165274/9bac585e-7044-11e6-9b8c-1aeddf7fea0f.png)

**Comment by eliorivero** [comment] 2016-09-01 20:24
Closing as duplicate of #5042
Will be addressed in https://github.com/Automattic/dops-components/pull/56

**Closed by eliorivero** 2016-09-01 20:24 UTC
