### ISSUE TITLE
Styling Issue: At A Glance Page Content Touching Edge of Container

### ISSUE THREAD

**Issue by katiebethbrown** [Automattic/jetpack#33453] opened 2023-10-03 20:04 UTC
### Impacted plugin

Jetpack

### Quick summary

On the At A Glance Page, the content touches the edge of the viewport between 1251px and 1320px wide.

![CleanShot 2023-10-03 at 12 55 11@2x](https://github.com/Automattic/jetpack/assets/42279181/d4fef260-39d7-4118-a1cc-bb9fa2781fcd)

### Steps to reproduce

1. View the At A Glance page in a viewport between 1251-1320px wide.
2. See content touching the edge of the container.

### A clear and concise description of what you expected to happen.

I expected for the content to have margin/padding so it didn't touch the edge of the container.

### What actually happened

The content touches the edge of the container.

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Logs or notes

Screenshot is an atomic site, in Arc (Chrome).

**Comment by cuemarie** [comment] 2023-10-03 21:36
📌 REPRODUCTION RESULTS
- Tested on Atomic – Replicated
- Replicable outside of Dotcom - No

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated on Atomic test sites only. My Self-hosted site, when connected to JP, did not present the same issue.

https://github.com/Automattic/jetpack/assets/27249804/cc3ef71d-da14-4cf9-8971-01f8ac9f3c36

📌 ACTIONS
- Triaged
- Lowered Priority to Normal

**Comment by jeherve** [comment] 2023-11-22 16:30
Closing as duplicate of #31951.

**Closed as completed by jeherve** 2023-11-22 16:30 UTC
Labels: Bug, [Closed] Duplicate, Admin Page, [Pri] Normal, [Plugin] Jetpack, Triaged
