### ISSUE TITLE
Images not Appearing in New Post Notification Emails for Simple Sites

### ISSUE THREAD

**Issue by masperber** [Automattic/jetpack#32372] opened 2023-08-09 16:39 UTC
### Impacted plugin

Jetpack

### Quick summary

In addition, I encountered a bug where sites on the simple WordPress.com platform (Personal and Premium sites), sometimes show the image URL instead of the image.

### Steps to reproduce

1. Create a new post.
2. Add images to the post, along with some text between each image.
3. Publish the post.
4. Observe that the images are not included, and instead the image URLs appear.

### A clear and concise description of what you expected to happen.

Images should appear instead of image URLs in new post notifications for WordPress.com simple sites.

### What actually happened

On my WordPress.com simple site, images did not appear in the new post notification email, and instead the image URL appeared.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

**Comment by samiff** [comment] 2023-08-09 17:02
@masperber 👋 I wasn't able to reproduce this on my end from my simple wpcom test site.

* Are you able to consistently reproduce the issue on your site?
* Have there been any other HE/user reports of this issue recently?

If you are able to reproduce, could you please add details about the site you are testing from and the text from the code view of your post. And if it helps in your testing, you can try sending a test email with preview tool:

![Markup on 2023-08-09 at 10:58:51](https://github.com/Automattic/jetpack/assets/15803018/58556173-79d6-40c6-9857-8879cb06edaa)

**Comment by masperber** [comment] 2023-08-09 19:12
Hi @samiff !

I haven't seen other reports.

I am able to consistently reproduce this behavior on my test site, masperberpm.wordpress.com. The test site has a Premium plan with the theme Stewart activated. I have changed the theme to T23, and the same issue occurs.

Here is the code of the post:

> \<figure class="wp-block-image size-large"><img src="https://masperberpm.files.wordpress.com/2023/04/sample-jpg.jpeg?w=1024" alt="" class="wp-image-1126"/>\</figure>
> 
> \<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\</p>

I have verified that images are sent correctly when I publish a post on an Atomic test site.

I tried to publish a post on another test site with a Premium plan, masperber6.wordpress.com, and this time the images are sent correctly. The site used the exact same post code and the same theme is active.

**Comment by masperber** [comment] 2023-08-09 19:16
After some inspection, I see that the site I was testing on was set to Private. This seems to be the cause of the issue. Setting the site to Public resolves the issue.

This still seems like it's a bug. Perhaps it would be possible to embed the images into the new post notification email rather than referencing them.

**Comment by cuemarie** [comment] 2023-08-09 20:58
Thanks for the additional testing, @masperber ! It looks like this has been reported as a feature request, here:

- https://github.com/Automattic/wp-calypso/issues/70591


📌 ACTIONS
- Closing as duplicate

**Closed as not planned by cuemarie** 2023-08-09 20:58 UTC
Labels: Bug, [Closed] Duplicate, [Feature] Notifications, [Pri] Normal, [Platform] Simple
