### ISSUE TITLE
Add Twitter hashtag capability to Publicize?

### ISSUE THREAD

**Issue by TiBiker** [Automattic/jetpack#10927] opened 2018-12-11 01:30 UTC
Hi,

About 4 years ago, there was code posted to add the ability to use post tags as Twitter hashtags when Publicize sent a tweet:

https://jeremy.hu/jetpack-hashtags-tweets-publicize/

I've tried to get that to work, but so far no luck. Automatically adding hashtags to Twitter posts would be very useful. Is it possible to add (and/or update) the code to the Publicize module?

Thanks!

Cheers,

Steve

**Comment by htdat** [comment] 2018-12-11 03:00
The request above is from 10927-zen 

@jeherve - what do you think? After some years, we might change how we send the data from self-hosted site to WP.com for publicizing?

**Comment by jeherve** [comment] 2018-12-11 11:00
This is caused by the changes we've made to Publicize to make it work with WordPress' new editor, Gutenberg.

I'll close this in favor of https://github.com/Automattic/wp-calypso/issues/29128 , where we are tracking this problem.

**Closed by jeherve** 2018-12-11 11:00 UTC
Labels: Publicize, [Type] Duplicate, [Type] Question
