### ISSUE TITLE
Confirm all files check for WP

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#8818] opened 2018-02-12 16:36 UTC
I ran into a ticket in support where something had crawled every file and attempted to execute each PHP file. This resulted in a ton of fatal errors (the construct class of Jetpack_Admin uses the Jetpack class without checking, for example).

We could resolve this by a simple ABSPATH-> exit check at the top of PHP files to prevent direct execution.

**Comment by jeherve** [comment] 2018-02-12 17:25
Closing as duplicate of #3056

**Closed by jeherve** 2018-02-12 17:25 UTC
Labels: General, [Pri] Low, [Type] Enhancement
