### ISSUE TITLE
Admin: Increase max-width of dashboard

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#6112] opened 2017-01-17 17:45 UTC
Master Issue: https://github.com/Automattic/jetpack/issues/6135

Currently the width of the Jetpack dashboard maxes out at `720px` It was designed and built this way to match calypso.

Currently: 
![screen shot 2017-01-17 at 12 40 11 pm](https://cloud.githubusercontent.com/assets/214813/22032374/3533fef8-dcb2-11e6-8871-e70b6ee8cb71.png)

However, In many places, calypso has expanding to a max-width of `1040px`. In order to stay in line with calypso and afford jetpack users better readability, we should change this in jetpack as well.

Proposed:
![screen shot 2017-01-17 at 12 43 58 pm](https://cloud.githubusercontent.com/assets/214813/22032505/a6e84040-dcb2-11e6-97f3-a8863da5f118.png)

This only requires a few line changes to some `max-width` attrs for the masthead and dashboard body. Will also need to make a few tweaks on the landing pages. Should be quick.

**Comment by dereksmart** [comment] 2017-10-31 21:12
Duplicate of #6974

**Closed by dereksmart** 2017-10-31 21:12 UTC
Labels: Admin Page, [Status] Design Polish, [Type] Enhancement
