### ISSUE TITLE
Publicize: Twitter custom message truncated at 90 Characters

### ISSUE THREAD

**Issue by csonnek** [Automattic/jetpack#7029] opened 2017-04-21 19:59 UTC
When using a custom message, despite the [code](https://github.com/Automattic/jetpack/blob/master/modules/publicize/ui.php#L329) allowing for 116 characters, the message is cut off at exactly 90 characters. 

Tested using a post with this custom message (which took up all 140 characters):

`Testing Twitter OG Tags and other things to get the character count up to the limit to see what else is going on or if it's user error. Prob`

The post on Twitter (private testing account): 
![twitter_custom_message](https://cloud.githubusercontent.com/assets/2814452/25293891/57c7b1a0-26a2-11e7-8a7a-969598efdccf.png)

Text up to "see" equals 90 characters. Also reported by user in 3169617-t. 

With Twitter's [recent change](https://blog.twitter.com/2017/now-on-twitter-140-characters-for-your-replies) to not count Twitter usernames in tweets, could something else have changed in the API to limit custom messages?

**Comment by jeherve** [comment] 2017-04-21 21:29
I think the problem is that media is counts towards tweet length, so the image that was attached to your tweet ended up eating up another 24 characters (a 23-char link and a space).

I'll close this issue in favor of 432-gh-io, where we already keep track of the problem.

**Closed by jeherve** 2017-04-21 21:29 UTC
Labels: Publicize, [Team]  I/O
