### ISSUE TITLE
Subscriptions: remove comment and like buttons from emails

### ISSUE THREAD

**Issue by foleynotrose** [Automattic/jetpack#24052] opened 2022-04-22 16:13 UTC
### Impacted plugin

Jetpack

### What

Users would like subscription emails not to have the comment and like buttons at the bottom

### How

![image](https://user-images.githubusercontent.com/26651984/164753609-553665c2-d6eb-4d22-8bcc-f4a382081f09.png)

**Comment by foleynotrose** [comment] 2022-04-22 16:16
Requested in: 

4963821-zd-woothemes
4962551-zd-woothemes
4962942-zd-woothemes

**Comment by jeherve** [comment] 2022-04-25 16:22
closing as duplicate of https://github.com/Automattic/wp-calypso/issues/62997

**Closed by jeherve** 2022-04-25 16:22 UTC
Labels: [Type] Enhancement, Subscriptions, [Type] Happiness Request, [Plugin] Jetpack
