### ISSUE TITLE
(3P) External Media: Load More error separated from action

### ISSUE THREAD

**Issue by jeryj** [Automattic/jetpack#15895] opened 2020-05-22 14:54 UTC
#### Steps to reproduce the issue

1. Add an image block
2. Click on Select Image
3. Click on Pexels
4. Click Load More at the bottom of the modal
5. In Network Dev Tools, set your browser to offline
6. Click Load More
7. There's no communication in view as to what happened. The errors are all at the top of the modal.

#### What I expected

An error to show that was in view (near the load more button)

#### What happened instead
![load-more-error](https://user-images.githubusercontent.com/967608/82680349-c1526100-9c11-11ea-9e9a-357480ecae84.gif)

**Comment by keoshi** [comment] 2020-05-22 15:02
Hey @jeryj — it seems that this happened on WordPress.com, can you confirm?

**Comment by jeryj** [comment] 2020-05-22 19:21
Hi @keoshi! This isn't on WordPress.com yet, but is a new feature in Jetpack. The current Media Library on WordPress.com uses the infinite scrolling pattern. You can access this Pexels library by choosing the Free Photo Library on WordPress.com, but it also uses the infinite scrolling pattern.

<img width="1789" alt="Screen Shot 2020-05-22 at 2 16 34 PM" src="https://user-images.githubusercontent.com/967608/82702051-dbeb0100-9c36-11ea-8f0e-14a8d5489ab3.png">

**Comment by keoshi** [comment] 2020-05-25 11:19
@jeryj The reason I'm asking is because from the screenshots above it seems like this is happening in Calypso rather than on a self-hosted site, even if it's a Jetpack site. If that's the case, I wonder if https://github.com/Automattic/wp-calypso would be a better place to report this issue.

Some features are shared across the different code bases, so I'm unsure — cc'ing @jeherve because he'll know it. :)

**Comment by jeherve** [comment] 2020-05-25 13:43
From the looks of it, this is the iFramed block editor, so that's about the Jetpack feature currently being worked on.

**Comment by obenland** [comment] 2020-05-28 18:39
@jeryj For that state to occur, users would need to lose connection between the initial API request that populates the modal and the Load more click?

**Comment by obenland** [comment] 2020-05-29 20:51
Just tested it with Chrome's "Slow 3G" and a custom 50kb/s setting and couldn't reproduce this occurring "naturally".

How do you feel about classifying this one as nice-to-have for when we ran out of more important External Media tasks?

**Comment by jeryj** [comment] 2020-05-29 21:00
Sounds fine. Are there any other potential issues that could happen with the Load More button? If so, it'd be good to have an error state near the button. I can't think of any off the top of my head though.

**Comment by getdave** [comment] 2020-06-01 16:19
@jancavan 👋 Are you able to take a look at this from a Design point of view? Once we have this then it will be suitable for inclusion in an estimation.

**Comment by jancavan** [comment] 2020-06-02 21:37
@jeryj Out of curiosity, are there other types of error we display within this modal other than the internet connection error?

**Comment by jeryj** [comment] 2020-06-03 14:58
I think so, such as if pexels doesn't initially load any results. But for those instances, there aren't photos so you're already at the top of the modal. I'm not sure of all the possible errors though. If I had to guess, most of them will happen when the modal is initially opened, rather than when clicking "load more"

**Comment by eeeeevon13** [comment] 2020-06-09 17:36
Plus 1 for the sticky error message. That would be my suggestion!

**Comment by obenland** [comment] 2021-01-18 22:56
Let's close this for now, it doesn't look like it's caused any issues so far.

**Closed by obenland** 2021-01-18 22:56 UTC
Labels: [Extensions] External Media, [Pri] Low
