### ISSUE TITLE
Version 12.6.1 results in critical error when used with Timber theme

### ISSUE THREAD

**Issue by tylersticka** [Automattic/jetpack#33284] opened 2023-09-25 17:27 UTC
### Impacted plugin

Jetpack

### Quick summary

Upgrading to Jetpack 12.6.1 results in a critical PHP error for classic themes that use [the Timber plugin](https://upstatement.com/timber/).

The issue seems to occur because of this change: https://github.com/Automattic/jetpack/commit/becaca54e214d7f8122cbfb9f3cda1159e06abe0

We do not use the VideoPress feature, but we aren't able to easily call `remove_action` to disable since it is an anonymous function.

### Steps to reproduce

1. Install and activate Jetpack 12.6.1
2. Install and activate the Timber plugin
3. Download, install and activate [the Timber starter theme](https://github.com/timber/starter-theme)
4. Attempt to view any non-admin page

### Impact

All

### Available workarounds?

No and the platform is unusable

### Logs or notes

<pre><b>Fatal error</b>:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-includes/post-template.php:324
Stack trace:
#0 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-videopress/src/class-initializer.php(363): get_the_content()
#1 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-includes/class-wp-hook.php(310): Automattic\Jetpack\VideoPress\Initializer::Automattic\Jetpack\VideoPress\{closure}('')
#2 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-includes/class-wp-hook.php(334): WP_Hook-&gt;apply_filters(NULL, Array)
#3 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#4 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-includes/script-loader.php(2225): do_action('wp_enqueue_scri...')
#5 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-includes/class-wp-hook.php(310): wp_enqueue_scripts('')
#6 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-includes/class-wp-hook.php(334): WP_Hook-&gt;apply_filters(NULL, Array)
#7 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-includes/plugin.php(517): WP_Hook-&gt;do_action(Array)
#8 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-includes/general-template.php(3053): do_action('wp_head')
#9 [internal function]: wp_head()
#10 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/lib/Twig.php(296): call_user_func_array('wp_head', Array)
#11 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/vendor/twig/twig/src/Environment.php(497) : eval()'d code(70): Timber\Twig-&gt;exec_function('wp_head')
#12 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/vendor/twig/twig/src/Template.php(453): __TwigTemplate_28c4d9cbcf8c6d7ff58ba31b4ef679fb342af24a7a09df9c29a581cbd91d8695-&gt;doDisplay(Array, Array)
#13 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/vendor/twig/twig/src/Template.php(420): Twig\Template-&gt;displayWithErrorHandling(Array, Array)
#14 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/vendor/twig/twig/src/Environment.php(497) : eval()'d code(101): Twig\Template-&gt;display(Array)
#15 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/vendor/twig/twig/src/Template.php(214): __TwigTemplate_1f82296bcceac4ae49d87c8aa347a1e7deb6652c60c233ace653d3509b1cef97-&gt;block_html_head_container(Array, Array)
#16 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/vendor/twig/twig/src/Environment.php(497) : eval()'d code(35): Twig\Template-&gt;displayBlock('html_head_conta...', Array, Array)
#17 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/vendor/twig/twig/src/Template.php(453): __TwigTemplate_1f82296bcceac4ae49d87c8aa347a1e7deb6652c60c233ace653d3509b1cef97-&gt;doDisplay(Array, Array)
#18 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/vendor/twig/twig/src/Template.php(420): Twig\Template-&gt;displayWithErrorHandling(Array, Array)
#19 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/vendor/twig/twig/src/Environment.php(497) : eval()'d code(35): Twig\Template-&gt;display(Array, Array)
#20 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/vendor/twig/twig/src/Template.php(453): __TwigTemplate_7e4762580c0bd2e7137951194db301f145d96a7839bc3d333887c8fb4b3ec413-&gt;doDisplay(Array, Array)
#21 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/vendor/twig/twig/src/Template.php(420): Twig\Template-&gt;displayWithErrorHandling(Array, Array)
#22 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/vendor/twig/twig/src/Template.php(432): Twig\Template-&gt;display(Array)
#23 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/vendor/twig/twig/src/TemplateWrapper.php(47): Twig\Template-&gt;render(Array, Array)
#24 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/lib/Loader.php(79): Twig\TemplateWrapper-&gt;render(Array)
#25 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/lib/Timber.php(334): Timber\Loader-&gt;render('index.twig', Array, false, 'default')
#26 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/lib/Timber.php(383): Timber\Timber::compile(Array, Array, false, 'default', true)
#27 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/plugins/timber-library/lib/Timber.php(410): Timber\Timber::fetch(Array, Array, false, 'default')
#28 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-content/themes/starter-theme-1.x/index.php(23): Timber\Timber::render(Array, Array)
#29 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-includes/template-loader.php(106): include('/Users/tylersti...')
#30 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-blog-header.php(19): require_once('/Users/tylersti...')
#31 /Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/index.php(17): require('/Users/tylersti...')
#32 {main}
  thrown in <b>/Users/tylersticka/Local Sites/jetpack-upgrade-issue/app/public/wp-includes/post-template.php</b> on line <b>324</b></pre>

**Comment by cometgrrl** [comment] 2023-09-25 23:03
@CGastrell Can you take a look at this?

**Comment by CGastrell** [comment] 2023-09-26 00:55
> @CGastrell Can you take a look at this?

Gimme 30’

**Comment by CGastrell** [comment] 2023-09-26 03:21
I'll look again tomorrow, but it seems the theme or plugin are messing with some globals used at `get_the_content`:

```php
	global $page, $more, $preview, $pages, $multipage;
...
	if ( null === $post && did_action( 'the_post' ) ) {
		$elements = compact( 'page', 'more', 'preview', 'pages', 'multipage' );
	} else {
		$elements = generate_postdata( $_post );
	}
...
// the error is triggered here as $elements['pages'] (coming from global $pages) is null (not of type Countable|array)
	if ( $elements['page'] > count( $elements['pages'] ) ) {
		// Give them the highest numbered page that DOES exist.
		$elements['page'] = count( $elements['pages'] );
	}
```

I'd like some other members opinion, I'm not entirely sure we should indulge messing with core globals. Otherwise I'll revert the change.

cc @jeherve @oskosk

**Comment by anomiex** [comment] 2023-09-26 12:52
I was able to reproduce on a JN site, and tracked it down to the fact that [Timber runs the 'the_post' action itself](https://github.com/timber/timber/blob/a7fb34671bf3d1c7327ff946a998b0833fc4257e/lib/Post.php#L612) without setting up the globals that WordPress core [normally sets up when calling that action](https://github.com/WordPress/wordpress-develop/blob/6.3.1/src/wp-includes/class-wp-query.php#L4668-L4706).

Since the action was already run, `get_the_content()` assumes the globals exist and tries to use them instead of calling `generate_postdata()` itself, as shown in the snippet quoted above.

**Comment by oskosk** [comment] 2023-09-26 14:42
Thanks @anomiex @CGastrell . This seems indeed like an unexpected environment due to Timber's innerworkings. 

Closing this issue

**Closed as completed by oskosk** 2023-09-26 14:42 UTC
Labels: Bug, [Status] In Progress, [Pri] BLOCKER, [Plugin] Jetpack, Needs triage, [Status] Priority Review Triggered

**Comment by tylersticka** [comment] 2023-09-26 22:45
@anomiex @CGastrell @oskosk Thanks for taking a look. I've created an issue in Timber: https://github.com/timber/timber/issues/2809

In the meantime, do you have any advice for how to disable this logic from running at all? We aren't using the VideoPress feature, it's disabled in our settings, and I can't find a filter or action to toggle to keep this function from running.

**Edit:** This seems to be working, included within a plugin:

```php
add_filter('pre_option_jetpack_excluded_extensions', function ($pre_option) {
  $exclusions = ['videopress', 'videopress/video'];

  if (is_array($pre_option)) {
    return array_merge($pre_option, $exclusions);
  }

  return $exclusions;
});
```

**Comment by oskosk** [comment] 2023-09-28 20:37
@tylersticka I'll double check if there's anything we can do. I just saw in the Timber repo that they won't be addressing fixed for 1.x

**Comment by tylersticka** [comment] 2023-09-28 20:48
Thanks, @oskosk. (Long-term solution for us is to use Timber 2.x or block themes going forward, but that isn't always feasible for legacy projects.)

**Comment by oskosk** [comment] 2023-09-28 21:24
@tylersticka @CGastrell is working on an update as a workaround for this situation. it will only come out in the next Jetpack release.

**Comment by tylersticka** [comment] 2023-09-29 16:27
@oskosk @CGastrell Great news! Thanks so much!
