### ISSUE TITLE
Inconsistencies in the way WordPress re-post to Twitter, Tumblr and Facebook

### ISSUE THREAD

**Issue by ck-lee** [Automattic/jetpack#11750] opened 2019-03-20 00:42 UTC
#### Steps to reproduce
1. Connect WordPress site with Twitter, Tumblr and Facebook
2. Write a new post. (Add Title, Body, Tags)
3. Click Publish
4. Expand Share this post
5. Enter text in `Customize your message`

#### What I expected
Title, Body, Tags or Customized message should display consistently (as much as possible anyway) in Twitter, Tumblr and Facebook. 

A suggestion:

Platform | Title | Body | Tags | Custom message 
------------ | ------------- | ------------- | ------------- | -------------
Twitter | Yes | No | No | Yes
Tumblr | Yes | No | No | Yes
Facebook | Yes | No | No | Yes

#### What happened instead
The display of Title, Body, Tags or Customized message is different when the post is re-posted in Twitter, Tumblr and Facebook. 

Platform | Title | Body | Tags | Custom message 
------------ | ------------- | ------------- | ------------- | -------------
Twitter | Yes | No | No | No
Tumblr | Yes | Yes | Yes | Yes
Facebook | Yes | Yes | No | No

#### Browser / OS version
Chrome 72.0.3626.121 / Mac 10.14.3

#### Context / Source
#manual-testing
#user-report
`1883060-zen`

**Comment by simison** [comment] 2019-03-28 21:14
While it wasn't specified if this is an issue with simple sites or Jetpack sites, I've transferred this issue to Jetpack repo because that's likely where the issue is.

**Comment by jeherve** [comment] 2019-03-29 13:38
While we could make some improvements here, I don't think we should aim for consistency between the different platforms. They all offer different features, and readers consequently expect different behaviours from each platform:
- When on Twitter you expect things to remain short and to the point, with a link to find out more.
- When on Tumblr you expect things to look very differently depending on the type of post (image, link, standard, ...). Most Tumblr themes have very different templates depending on the content type.
- When on Facebook you expect Media to take a central role, and the limits of text content are not as strict as with Twitter.

Ultimately, there are 3 different things we could do that would improve the experience of both site owners and readers, for each platform.

- Publicize Custom Message Doesn't Show In Twitter #11752
- Publicize: Add custom templates #261
- Publicize: Give publishers control over Tumblr publishing #520

I'll close this issue in favor of the other ones, where there has been more discussion about potential solutions. Don't hesitate to chime in there with your ideas.

**Closed by jeherve** 2019-03-29 13:38 UTC
Labels: Publicize, [Type] Duplicate, [Type] Enhancement
