### ISSUE TITLE
Social Previews: Facebook preview shows page author

### ISSUE THREAD

**Issue by jamiepalatnik** [Automattic/jetpack#17363] opened 2020-10-02 21:12 UTC
#### Steps to reproduce the issue

1. Go to Jetpack Social Previews feature
2. Click on Preview > Facebook

#### What I expected

I would expect to see only the site address, since this matches what will appear on Facebook.

#### What happened instead

I see the page author shown in the preview with this format: Site | Author

**Screenshots**

This is the Facebook post:

<img width="495" alt="FB post" src="https://user-images.githubusercontent.com/30788962/94970126-f92bb800-04d1-11eb-9c24-8ba40f2a6449.png">

Social Previews:

<img width="904" alt="Social Previews" src="https://user-images.githubusercontent.com/30788962/94970130-fc26a880-04d1-11eb-8a73-443bc41f9ab3.png">

Reported in 24518332-hc

**Comment by jeherve** [comment] 2020-10-05 08:48
Closing as duplicate of #16876.

**Closed by jeherve** 2020-10-05 08:48 UTC
Labels: Involves Happiness, [Extensions] Social Previews, [Type] Bug, [Type] Happiness Request
