### ISSUE TITLE
Lazy Load not rendering base64 image

### ISSUE THREAD

**Issue by ffPjrZUGXfcxuAj** [Automattic/jetpack#10607] opened 2018-11-13 10:16 UTC
I have some image base64 encoded data:image/svg+xml;base64,PD94bW... when i active Lazy Load from jetpack it remove data: and image are not displayed.
I try also png tyoe and not work

**Comment by jeherve** [comment] 2018-11-13 16:15
Could you give us a few examples of pages where you experience this issue, so we can take a closer look at the problem?

If you want your site URL to remain private, you can also contact us via this contact form:
http://jetpack.com/contact-support/?rel=support

**Comment by camaran** [comment] 2018-11-13 16:25
ok we send you a private ticket

**Comment by jeherve** [comment] 2018-11-13 16:32
Closing in favour of email discussion.

**Comment by camaran** [comment] 2018-11-20 14:53
Hi, have you some news to this problem?

**Comment by aheckler** [comment] 2018-11-20 19:10
@camaran We sent you an email just now.

**Comment by htdat** [comment] 2018-12-06 11:08
From 3086-gh-jpop-issues, we've found out these things:

### The issue is reproducible as follows:

- Keep lazy-load module off
- Take a normal jpeg image from the internet and save it to your desktop
- Visit https://www.base64-image.de/ and convert it to base64. 
- Copy the code. 
- Wrap it in `img` tag as follows: https://cld.wthms.co/M3dUiw+
- Create a new post with it and publish it. It works - http://cld.wthms.co/96dSMg
- Enable the lazy-load module, it breaks - http://cld.wthms.co/uklnzB

### Debugging  

Troubleshooting further, it seems that whenever Lazy Images is loaded, it strips out the `data:` part of the `src` attribute. If I manually add `data:`, the base64 image displays well. 

![screen shot on 2018-12-06 at 08 36 07](https://user-images.githubusercontent.com/10045087/49555298-00172d00-f932-11e8-8eaf-9a847f18c299.png)

This happens because of the `wp_kses_hair` fuction with the `wp_allowed_protocols()` parameter here 
https://github.com/Automattic/jetpack/blob/6.8/modules/lazy-images/lazy-images.php/#L166

By default, wp_allowed_protocols() does not have the `data` protocol that explains why we strip out. 

### Workaround 

To "fix" this issue, we need to add the `data` protocol to wp_allowed_protocols() by using this snippet:

```php
/*
 * Add 'data' for based64 enconcoded images for wp_allowed_protocols()
 * With this, Jetpack Lazy Images will not strip out "data" in the "src" attribute https://github.com/Automattic/jetpack/blob/6.8/modules/lazy-images/lazy-images.php/#L166
 */

add_filter( 'kses_allowed_protocols', 'htdat_kses_allowed_protocols', 10, 1 );
               
function htdat_kses_allowed_protocols( $protocols ) {
	$protocols[] = 'data';
    return $protocols;
}
```

### Fix 

A simple fix is to change the line above to: 

```php
		$lazy_images_protocols = array_unique( array_push( wp_allowed_protocols(), 'data') );
		$old_attributes_kses_hair = wp_kses_hair( $old_attributes_str, $lazy_images_protocols );
```

We may consider adding a filter here also. 

I am not sure if there is any issue in this approach, or anything we need to consider. Otherwise, I am happy to create a PR for this :)

**Comment by kspilarski** [comment] 2020-05-26 14:33
Same case for 3007189-zd.  

With lazy-images on, URL shows base64 and the images are not displayed.

**Closed** 2023-10-25 20:08 UTC
Labels: [Type] Enhancement, [Status] In Progress, [Pri] Low, [Feature] Lazy Images, Customer Report
