### ISSUE TITLE
Can we do this better?

### ISSUE THREAD

**Issue by withinboredom** [Automattic/jetpack#8797] opened 2018-02-09 17:52 UTC
Discovered via GDPR Audit

https://github.com/Automattic/jetpack/blob/e26217c3de9a5f444627ccb3b89886e0ef1c5da1/modules/contact-form/admin.php#L495

Can we take another crack at it and do this better?

**Comment by jeherve** [comment] 2018-05-21 13:48
Closing as duplicate of #7713. We should be able to fix those 2 issues at once.

**Closed by jeherve** 2018-05-21 13:48 UTC
Labels: Contact Form, [Pri] Normal, [Type] Duplicate, [Type] Enhancement, [Type] Janitorial
